NATTQA-ENV/force-app/main/default/objects/NAC_WareHouseData__mdt/NAC_WareHouseData__mdt.object-meta.xml
<CustomObject>
    <description>Custom meta data for NAC warehouse selection</description>
    <label>NAC_WareHouseData</label>
    <pluralLabel>NAC_WareHouseData</pluralLabel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NAC_WareHouseData__mdt/fields/API_VALUE__c.field-meta.xml
<CustomField>
    <fullName>API_VALUE__c</fullName>
    <label>API VALUE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NAC_WareHouseData__mdt/fields/external_url__c.field-meta.xml
<CustomField>
    <fullName>external_url__c</fullName>
    <label>external url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NAC_WareHouseData__mdt/fields/Help_Text_needed__c.field-meta.xml
<CustomField>
    <fullName>Help_Text_needed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is to enable help text beside a country&apos;s warehouse selection option</description>
    <label>Help Text needed</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NAC_WareHouseData__mdt/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NAC_WareHouseData__mdt/fields/Redirection__c.field-meta.xml
<CustomField>
    <fullName>Redirection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Redirection</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NAC_WareHouseData__mdt/fields/sortorder__c.field-meta.xml
<CustomField>
    <fullName>sortorder__c</fullName>
    <label>sortorder</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NAC_WareHouseData__mdt/fields/Warehouse_Name__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Name__c</fullName>
    <label>Warehouse Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/NATT_ProductInventoryItem__c.object-meta.xml
<CustomObject>
    <description>Contains current inventory levels at each warehouse for all B2B Commerce product items.</description>
    <label>Product Inventory Item</label>
    <nameField>
        <displayFormat>INV-{000000000}</displayFormat>
        <label>Product Inventory Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/fields/NATT_AvailabilityDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_AvailabilityDate__c</fullName>
    <description>Date the product item is expected to be available at the specified warehouse.</description>
    <label>Availability Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/fields/NATT_AvailableQuantity__c.field-meta.xml
<CustomField>
    <fullName>NATT_AvailableQuantity__c</fullName>
    <description>Currently available quantity of the product item at the specified warehouse. Expected whole number values.</description>
    <label>Available Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/fields/NATT_ProductItem__c.field-meta.xml
<CustomField>
    <fullName>NATT_ProductItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product item to which the available quantity applies</description>
    <label>Product Item</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Inventory Items</relationshipLabel>
    <relationshipName>Product_Inventory_Items_del</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_SignalCode__c.field-meta.xml
<CustomField>
    <fullName>NATT_SignalCode__c</fullName>
    <description>JDE Signal Code for the item</description>
    <label>Signal Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>NLO</fullName>
            </value>
            <value>
                <fullName>NSI</fullName>
            </value>
            <value>
                <fullName>NSU</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S1D</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
            <value>
                <fullName>NRC</fullName>
            </value>
            <value>
                <fullName>BY2</fullName>
                <label>BUYER HOLD</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <label>NOT AVAILABLE</label>
            </value>
            <value>
                <fullName>OB1</fullName>
            </value>
            <value>
                <fullName>OBS</fullName>
            </value>
            <value>
                <fullName>PRC</fullName>
            </value>
            <value>
                <fullName>NEW</fullName>
            </value>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>PSR</fullName>
            </value>
            <value>
                <fullName>VIN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/WebCart/fields/Warehouse_selected__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_selected__c</fullName>
    <description>This field stores the selected warehouse by the user who has logged in</description>
    <label>Warehouse_selected</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/Nac_GetCustomSettingWareHouseData.cls
public without sharing class Nac_GetCustomSettingWareHouseData {
 /*Custom meta data class*/
   @AuraEnabled()
    public static List<CustomMetaDataWrapper> returWarehouses(String communityId,String effectiveAccountId,String activeCartOrId, String productId){
        List<NAC_WareHouseData__mdt> wareHouseConfigList=new List<NAC_WareHouseData__mdt>([SELECT external_url__c,API_VALUE__c,Help_Text_needed__c,sortorder__c, isActive__c,Redirection__c,Warehouse_Name__c from NAC_WareHouseData__mdt ORDER BY sortorder__c ]);
        List<CustomMetaDataWrapper> dataList=new List<CustomMetaDataWrapper>();
        String webstoreId = NAC_B2BUtils.resolveCommunityIdToWebstoreId(communityId);
        WebCart wc;
        if(!Test.isRunningTest()){
            ConnectApi.CartSummary getTheCartDetails=ConnectApi.CommerceCart.getOrCreateActiveCartSummary(webstoreId,effectiveAccountId,activeCartOrId);
            wc=[SELECT Id, Name, AccountId,Warehouse_selected__c, WebStoreId FROM WebCart where id=:getTheCartDetails.cartId];
        }

        //If product Id is sent, fetch the inventory for all those products and put it within the wrapper
        Map<String,NATT_ProductInventoryItem__c> productInventory = new Map<String,NATT_ProductInventoryItem__c>();
        if(productId != null){
            productInventory = Nac_InventoryUtility.getAllWarehouseAvailability(productId); 
        }
        for(NAC_WareHouseData__mdt it:wareHouseConfigList){
            CustomMetaDataWrapper cm=new CustomMetaDataWrapper();
            cm.WarehouseName=it.Warehouse_Name__c;
            cm.Redirection=it.Redirection__c;
            cm.isActive=it.isActive__c;
            cm.externalurl=it.external_url__c;
            cm.apiValue=it.API_VALUE__c;
            cm.Help_Text_needed=it.Help_Text_needed__c;
            if(!Test.isRunningTest()){
                cm.WarehouseStamped = wc.Warehouse_selected__c;
            }else{
                cm.WarehouseStamped= 'ATL';
            }
            System.debug(productInventory);
            if(productId != null && productInventory.get(it.API_VALUE__c) != null){
                if (productInventory.get(it.API_VALUE__c).NATT_AvailableQuantity__c != null && Integer.valueOf(productInventory.get(it.API_VALUE__c).NATT_AvailableQuantity__c) > 0) {
                    cm.inventoryAvailable = 'Available: ' + productInventory.get(it.API_VALUE__c).NATT_AvailableQuantity__c;
                    cm.inventoryExists = true;
                }
                else if(productInventory.get(it.API_VALUE__c).NATT_AvailableQuantity__c != null && Integer.valueOf(productInventory.get(it.API_VALUE__c).NATT_AvailableQuantity__c) <= 0){
                    cm.inventoryAvailable = 'Availability Date: ' + Date.valueOf(productInventory.get(it.API_VALUE__c).NATT_AvailabilityDate__c).format();
                }
                else if(productInventory.get(it.API_VALUE__c).NATT_ProductItem__r.NATT_SignalCode__c=='NSI'){
                    cm.inventoryAvailable = 'NSI';
                }
            }
            dataList.add(cm);
     }
        return dataList;
   }
    class CustomMetaDataWrapper{
        @AuraEnabled public String WarehouseName{get;set;}
        @AuraEnabled public String apiValue{get;set;}
        @AuraEnabled public Boolean Redirection{get;set;}
        @AuraEnabled public Boolean isActive{get;set;}
        @AuraEnabled public String externalurl{get;set;}
        @AuraEnabled public Boolean Help_Text_needed{get;set;}
        @AuraEnabled public String WarehouseStamped{get;set;}
        @AuraEnabled public String inventoryAvailable{get;set;}
        @AuraEnabled public Boolean inventoryExists{get;set;}
    }
    
    @AuraEnabled(cacheable=true)
    public static List<CustomMetaDataWrapper> getSelectedWarehouse(String ClickedWarehouse){
        List<NAC_WareHouseData__mdt> wareHouseConfigList=new List<NAC_WareHouseData__mdt>([SELECT external_url__c,Help_Text_needed__c,isActive__c,API_VALUE__c,Redirection__c,Warehouse_Name__c from NAC_WareHouseData__mdt where API_VALUE__c=:ClickedWarehouse]);
        List<CustomMetaDataWrapper> dataList=new List<CustomMetaDataWrapper>();
        system.debug('@@@@@@@@@@@wareHouseConfigList'+wareHouseConfigList);
        for(NAC_WareHouseData__mdt it:wareHouseConfigList){
           CustomMetaDataWrapper cm=new CustomMetaDataWrapper();
           cm.WarehouseName=it.Warehouse_Name__c;
           cm.Redirection=it.Redirection__c;
           cm.isActive=it.isActive__c;
           cm.apiValue=it.API_VALUE__c;
           cm.externalurl=it.external_url__c;
           cm.Help_Text_needed=it.Help_Text_needed__c;
           dataList.add(cm);
     }
        return dataList;
   }
    
   @AuraEnabled()
    public static WebCart updateTheCart(String communityId,String effectiveAccountId,String activeCartOrId,string ClickedWarehouse){
        String webstoreId = NAC_B2BUtils.resolveCommunityIdToWebstoreId(communityId);
        ConnectApi.CartSummary getTheCartDetails=ConnectApi.CommerceCart.getOrCreateActiveCartSummary(webstoreId,effectiveAccountId,activeCartOrId);
        WebCart wc=[SELECT Id, Name, AccountId,Warehouse_selected__c, WebStoreId FROM WebCart where id=:getTheCartDetails.cartId];
        wc.Warehouse_selected__c=ClickedWarehouse;
        update wc;
        
        return wc;
    }
    @AuraEnabled()
    public static string getCartDetails(String communityId,String effectiveAccountId,String activeCartOrId){
        String webstoreId = NAC_B2BUtils.resolveCommunityIdToWebstoreId(communityId);
        ConnectApi.CartSummary getTheCartDetails=ConnectApi.CommerceCart.getOrCreateActiveCartSummary(webstoreId,effectiveAccountId,activeCartOrId);
        WebCart wc=[SELECT Id, Name, AccountId,Warehouse_selected__c, WebStoreId FROM WebCart where id=:getTheCartDetails.cartId];
        return wc.Warehouse_selected__c;
    }
}