NATTQA-ENV/force-app/main/default/objects/Asset/fields/NATT_End_Customer_Price__c.field-meta.xml
<CustomField>
    <fullName>NATT_End_Customer_Price__c</fullName>
    <label>End Customer Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Asset/fields/NATT_Grouped_By_Line_Number__c.field-meta.xml
<CustomField>
    <fullName>NATT_Grouped_By_Line_Number__c</fullName>
    <description>stores the number for future amended quote lines</description>
    <label>Grouped By Line Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Asset/fields/NATT_Hide_Asset__c.field-meta.xml
<CustomField>
    <fullName>NATT_Hide_Asset__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide Asset</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Asset/fields/NATT_Is_Base_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Is_Base_Unit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>twin field from quote line</description>
    <label>Is Base Unit</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Asset/fields/NATT_Original_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>NATT_Original_Order_Id__c</fullName>
    <label>Original Order Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>The quote where the order is created from.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_Current_Effective_Quantity__c.field-meta.xml
<CustomField>
    <fullName>NATT_Current_Effective_Quantity__c</fullName>
    <description>sums the quantity of the ordered units including the amendments</description>
    <label>Current Effective Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_End_Customer_Price__c.field-meta.xml
<CustomField>
    <fullName>NATT_End_Customer_Price__c</fullName>
    <label>End Customer Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_Grouped_By_Line_Number__c.field-meta.xml
<CustomField>
    <fullName>NATT_Grouped_By_Line_Number__c</fullName>
    <description>The quote line number of the unit. used to group options and their unit.</description>
    <label>Grouped By Line Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_Is_Base_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Is_Base_Unit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that this is a top level bundle that is a unit that has options associated with it.</description>
    <label>Is Base Unit</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_Original_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>NATT_Original_Order_Id__c</fullName>
    <label>Original Order Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/SBQQ__QuotedListPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__QuotedListPrice__c</fullName>
    <description>List unit price for the product quoted by this line item. List Price originates from the price book.</description>
    <inlineHelpText>List unit price for the product quoted by this line item. List Price originates from the price book.</inlineHelpText>
    <label>Quoted List Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/SBQQ__QuotedQuantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__QuotedQuantity__c</fullName>
    <description>The quoted quantity.</description>
    <inlineHelpText>The quoted quantity.</inlineHelpText>
    <label>Quoted Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/SBQQ__QuoteLine__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__QuoteLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote line where this order product is created from.</description>
    <inlineHelpText>The quote line where this order product is created from.</inlineHelpText>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Is_Base_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Is_Base_Unit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>for base units only</description>
    <label>Is Base Unit</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__LookupData__c/SBQQ__LookupData__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__LookupQueryHelp</customHelpPage>
    <label>Lookup Data</label>
    <nameField>
        <displayFormat>DATA-{0000}</displayFormat>
        <label>Lookup Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lookup Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__LookupData__c/fields/NATT_End_Date__c.field-meta.xml
<CustomField>
    <fullName>NATT_End_Date__c</fullName>
    <description>For looking up the correct price for NATT Units</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__LookupData__c/fields/NATT_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>NATT_Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__LookupData__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For use with Product Selection Rules, represents the Product to which the Product Action applies.</description>
    <inlineHelpText>For use with Product Selection Rules, represents the Product to which the Product Action applies.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lookup Data</relationshipLabel>
    <relationshipName>LookupData</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__LookupData__c/fields/SBQQ__Type__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Type__c</fullName>
    <description>For use with Product Selection Rules, specifies the type of action to be performed on the Product.</description>
    <inlineHelpText>For use with Product Selection Rules, specifies the type of action to be performed on the Product.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Add</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
            </value>
            <value>
                <fullName>Enable</fullName>
            </value>
            <value>
                <fullName>Disable</fullName>
            </value>
            <value>
                <fullName>Enable &amp; Add</fullName>
            </value>
            <value>
                <fullName>Disable &amp; Remove</fullName>
            </value>
            <value>
                <fullName>Show</fullName>
            </value>
            <value>
                <fullName>Hide</fullName>
            </value>
            <value>
                <fullName>Show &amp; Add</fullName>
            </value>
            <value>
                <fullName>Hide &amp; Remove</fullName>
            </value>
            <value>
                <fullName>Default Filter</fullName>
            </value>
            <value>
                <fullName>Optional Filter</fullName>
            </value>
            <value>
                <fullName>Unit Pricing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Original_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>NATT_Original_Order_Id__c</fullName>
    <label>Original Order Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this quote.</description>
    <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Type__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Type__c</fullName>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
                <default>true</default>
                <label>Quote</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Re-Quote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_End_Customer_Price__c.field-meta.xml
<CustomField>
    <fullName>NATT_End_Customer_Price__c</fullName>
    <description>NATT</description>
    <label>End Customer Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_Grouped_By_Line_Number__c.field-meta.xml
<CustomField>
    <fullName>NATT_Grouped_By_Line_Number__c</fullName>
    <description>the quote line number that belongs to the unit. Groups all the options together with a unit that they are bundled with</description>
    <label>Grouped By Line Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_Is_Base_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Is_Base_Unit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT for all products that are base units only</description>
    <label>Is Base Unit</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_Original_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>NATT_Original_Order_Id__c</fullName>
    <label>Original Order Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quantity__c</fullName>
    <description>Quantity being quoted.</description>
    <inlineHelpText>Quantity being quoted.</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
    <inlineHelpText>The date the subscription for this product begins.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/TestUtil.cls
public class TestUtil {

    public static Product2 createProduct(String pName,String pCode){
        
        return new Product2(Name = pName,
                            ProductCode = pCode,
                            IsActive = true);
    }
    
    public static Order createOrder(Account acc,Date startDate,String status){
        
        return new Order(AccountId = acc.Id,EffectiveDate = Date.today(),Status = status);
    }
    
    public static OrderItem createOrderItem(Product2 product,Integer qty,Order odr,Integer gpLine,Boolean hasBaseUnit){
        
        return new OrderItem(Product2Id = product.Id,
                             ListPrice = 100,
                             UnitPrice = 100,
                             SBQQ__QuotedListPrice__c = 100,
                             NATT_End_Customer_Price__c = 150,
                             Quantity = qty,
                             OrderId = odr.Id,
                             NATT_Grouped_By_Line_Number__c = gpLine,
                             SBQQ__QuotedQuantity__c = qty,
                             NATT_Current_Effective_Quantity__c = 1,
                             NATT_Is_Base_Unit__c = hasBaseUnit,
                             NATT_Original_Order_Id__c = odr.NATT_Original_Order_Id__c);
    }
    
    public static Asset createAsset(Product2 product,String assetName,String odrId,Account acc){
        
        return new Asset(Name = assetName,
                         ContactId = null,
                         Product2Id = product.Id,
                         AccountId = acc.Id,
                         NATT_Original_Order_Id__c = odrId,
                         NATT_Hide_Asset__c = true);
    }
    
    public static SBQQ__LookupData__c createLookupData(String product,Date startDate,Date endDate,String type){
        
        return new SBQQ__LookupData__c(SBQQ__Product__c = product,
                                       NATT_Start_Date__c = startDate,
                                       NATT_End_Date__c = endDate,
                                       SBQQ__Type__c = type);
    }
    
    // Public method to create Price Book Entry record for testing.    
    public static PriceBookEntry createPriceBookEntry(String priceBookId, String productId){
        PriceBookEntry priceBookEntryRecord = new PriceBookEntry();
        priceBookEntryRecord.Pricebook2Id = priceBookId; 
        priceBookEntryRecord.Product2Id = productId;
        priceBookEntryRecord.IsActive = true;
        priceBookEntryRecord.UnitPrice = 100;
        return priceBookEntryRecord;
    } 
    
    public static SBQQ__QuoteLine__c createQuoteLine(String productId, String quoteId){
        SBQQ__QuoteLine__c quoteLine = new SBQQ__QuoteLine__c();
        quoteLine.SBQQ__Product__c = productId; 
        quoteLine.SBQQ__Quote__c = quoteId;
        quoteLine.SBQQ__Quantity__c = 1;
        quoteLine.SBQQ__StartDate__c = System.today() + 30;
        return quoteLine;
    }
}