NATTQA-ENV/force-app/main/default/objects/Asset/fields/NATT_CMRA_Term_Years__c.field-meta.xml
<CustomField>
    <fullName>NATT_CMRA_Term_Years__c</fullName>
    <label>Term (Years)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Asset/fields/NATT_Coverage_Type__c.field-meta.xml
<CustomField>
    <fullName>NATT_Coverage_Type__c</fullName>
    <description>natt twin field</description>
    <label>Coverage Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Coverage_Type</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Asset/fields/NATT_Extended_Basic_Hours__c.field-meta.xml
<CustomField>
    <fullName>NATT_Extended_Basic_Hours__c</fullName>
    <description>cpq twin field</description>
    <label>Extended Basic Hours</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_BluEdge_Hours</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Asset/fields/NATT_Extended_Basic_Months__c.field-meta.xml
<CustomField>
    <fullName>NATT_Extended_Basic_Months__c</fullName>
    <description>cpq twin field</description>
    <label>Extended Basic Months</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_BluEdge_Months</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Asset/fields/NATT_Is_Base_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Is_Base_Unit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>twin field from quote line</description>
    <label>Is Base Unit</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Asset/fields/NATT_Major_Component_Deductible__c.field-meta.xml
<CustomField>
    <fullName>NATT_Major_Component_Deductible__c</fullName>
    <description>cpq twin field</description>
    <label>Major Component Deductible</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Deductible</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Asset/fields/NATT_Major_Component_Hours__c.field-meta.xml
<CustomField>
    <fullName>NATT_Major_Component_Hours__c</fullName>
    <description>cpq twin field</description>
    <label>Major Component Hours</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_BluEdge_Hours</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Asset/fields/NATT_Major_Component_Months__c.field-meta.xml
<CustomField>
    <fullName>NATT_Major_Component_Months__c</fullName>
    <description>cpq twin field</description>
    <label>Major Component Months</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_BluEdge_Months</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Asset/fields/NATT_Optional_Coverage_Hours__c.field-meta.xml
<CustomField>
    <fullName>NATT_Optional_Coverage_Hours__c</fullName>
    <description>cpq twin field</description>
    <label>Optional Coverage Hours</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_BluEdge_Hours</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Asset/fields/NATT_Optional_Coverage_Months__c.field-meta.xml
<CustomField>
    <fullName>NATT_Optional_Coverage_Months__c</fullName>
    <description>cpq twin field</description>
    <label>Optional Coverage Months</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_BluEdge_Months</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Asset/fields/NATT_Original_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>NATT_Original_Order_Id__c</fullName>
    <label>Original Order Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>The quote where the order is created from.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Enforce_Amendment_Error__c.field-meta.xml
<CustomField>
    <fullName>NATT_Enforce_Amendment_Error__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will be by default set to true in for the amendment process, during the process of Amendment Quote creation. It will be automatically reset to false.</description>
    <label>Enforce Amendment Error</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Extended_Basic_Hours__c.field-meta.xml
<CustomField>
    <fullName>NATT_Extended_Basic_Hours__c</fullName>
    <label>Extended Basic Hours</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_BluEdge_Hours</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Extended_Basic_Months__c.field-meta.xml
<CustomField>
    <fullName>NATT_Extended_Basic_Months__c</fullName>
    <label>Extended Basic Months</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_BluEdge_Months</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Major_Component_Deductible__c.field-meta.xml
<CustomField>
    <fullName>NATT_Major_Component_Deductible__c</fullName>
    <label>Major Component Deductible</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Deductible</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Major_Component_Hours__c.field-meta.xml
<CustomField>
    <fullName>NATT_Major_Component_Hours__c</fullName>
    <label>Major Component Hours</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_BluEdge_Hours</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Major_Component_Months__c.field-meta.xml
<CustomField>
    <fullName>NATT_Major_Component_Months__c</fullName>
    <label>Major Component Months</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_BluEdge_Months</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Optional_Coverage_Hours__c.field-meta.xml
<CustomField>
    <fullName>NATT_Optional_Coverage_Hours__c</fullName>
    <label>Optional Coverage Hours</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_BluEdge_Hours</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Optional_Coverage_Months__c.field-meta.xml
<CustomField>
    <fullName>NATT_Optional_Coverage_Months__c</fullName>
    <label>Optional Coverage Months</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_BluEdge_Months</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Original_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>NATT_Original_Order_Id__c</fullName>
    <label>Original Order Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Source__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Source of cloned quote.</description>
    <inlineHelpText>Source of cloned quote. If cloned, this references the original quote cloned.</inlineHelpText>
    <label>Source</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quotes (Source)</relationshipLabel>
    <relationshipName>Clones</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_CMRA_Term_Years__c.field-meta.xml
<CustomField>
    <fullName>NATT_CMRA_Term_Years__c</fullName>
    <description>used with NATT BluEdge</description>
    <label>Term (Years)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_Coverage_Type__c.field-meta.xml
<CustomField>
    <fullName>NATT_Coverage_Type__c</fullName>
    <label>Coverage Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Coverage_Type</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_Extended_Basic_Hours__c.field-meta.xml
<CustomField>
    <fullName>NATT_Extended_Basic_Hours__c</fullName>
    <label>Extended Basic Hours</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_BluEdge_Hours</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_Extended_Basic_Months__c.field-meta.xml
<CustomField>
    <fullName>NATT_Extended_Basic_Months__c</fullName>
    <description>NATT Configuration</description>
    <label>Extended Basic Months</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_BluEdge_Months</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_Is_Base_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Is_Base_Unit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT for all products that are base units only</description>
    <label>Is Base Unit</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_Major_Component_Deductible__c.field-meta.xml
<CustomField>
    <fullName>NATT_Major_Component_Deductible__c</fullName>
    <description>natt</description>
    <label>Major Component Deductible</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Deductible</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_Major_Component_Hours__c.field-meta.xml
<CustomField>
    <fullName>NATT_Major_Component_Hours__c</fullName>
    <description>for cpq configuration</description>
    <label>Major Component Hours</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_BluEdge_Hours</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_Major_Component_Months__c.field-meta.xml
<CustomField>
    <fullName>NATT_Major_Component_Months__c</fullName>
    <label>Major Component Months</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_BluEdge_Months</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_Optional_Coverage_Hours__c.field-meta.xml
<CustomField>
    <fullName>NATT_Optional_Coverage_Hours__c</fullName>
    <label>Optional Coverage Hours</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_BluEdge_Hours</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_Optional_Coverage_Months__c.field-meta.xml
<CustomField>
    <fullName>NATT_Optional_Coverage_Months__c</fullName>
    <label>Optional Coverage Months</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_BluEdge_Months</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_Original_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>NATT_Original_Order_Id__c</fullName>
    <label>Original Order Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_Quote_Record_Type_ID__c.field-meta.xml
<CustomField>
    <fullName>NATT_Quote_Record_Type_ID__c</fullName>
    <formula>CASESAFEID(SBQQ__Quote__r.RecordTypeId)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote Record Type ID</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>NATT_Quote_Type__c</fullName>
    <formula>TEXT(SBQQ__Quote__r.SBQQ__Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote Type</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Source__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Source of cloned quote line.</description>
    <inlineHelpText>Source of cloned quote line.</inlineHelpText>
    <label>Source</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Lines (Source)</relationshipLabel>
    <relationshipName>Clones</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_BluEdge_Hours.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>500</fullName>
    </customValue>
    <customValue>
        <fullName>1000</fullName>
    </customValue>
    <customValue>
        <fullName>1500</fullName>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
    </customValue>
    <customValue>
        <fullName>2500</fullName>
    </customValue>
    <customValue>
        <fullName>3000</fullName>
    </customValue>
    <customValue>
        <fullName>3500</fullName>
    </customValue>
    <customValue>
        <fullName>4000</fullName>
    </customValue>
    <customValue>
        <fullName>4500</fullName>
    </customValue>
    <customValue>
        <fullName>5000</fullName>
    </customValue>
    <customValue>
        <fullName>5500</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>6500</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7500</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>8500</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9500</fullName>
    </customValue>
    <customValue>
        <fullName>10000</fullName>
    </customValue>
    <customValue>
        <fullName>10500</fullName>
    </customValue>
    <customValue>
        <fullName>11000</fullName>
    </customValue>
    <customValue>
        <fullName>11500</fullName>
    </customValue>
    <customValue>
        <fullName>12000</fullName>
    </customValue>
    <customValue>
        <fullName>12500</fullName>
    </customValue>
    <customValue>
        <fullName>13000</fullName>
    </customValue>
    <customValue>
        <fullName>13500</fullName>
    </customValue>
    <customValue>
        <fullName>14000</fullName>
    </customValue>
    <customValue>
        <fullName>14500</fullName>
    </customValue>
    <customValue>
        <fullName>15000</fullName>
    </customValue>
    <description>NATT for lookup table</description>
    <masterLabel>NATT BluEdge Hours</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_BluEdge_Months.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>24</fullName>
    </customValue>
    <customValue>
        <fullName>36</fullName>
    </customValue>
    <customValue>
        <fullName>48</fullName>
    </customValue>
    <customValue>
        <fullName>60</fullName>
    </customValue>
    <customValue>
        <fullName>72</fullName>
    </customValue>
    <customValue>
        <fullName>84</fullName>
    </customValue>
    <customValue>
        <fullName>96</fullName>
    </customValue>
    <customValue>
        <fullName>108</fullName>
    </customValue>
    <customValue>
        <fullName>120</fullName>
    </customValue>
    <description>NATT for lookup table</description>
    <masterLabel>NATT BluEdge Months</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Coverage_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Extended Basic</fullName>
    </customValue>
    <customValue>
        <fullName>Major Component Coverage</fullName>
    </customValue>
    <customValue>
        <fullName>Extended Basic + Major Component</fullName>
    </customValue>
    <masterLabel>NATT Coverage Type</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Deductible.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>250</fullName>
    </customValue>
    <customValue>
        <fullName>500</fullName>
    </customValue>
    <customValue>
        <fullName>750</fullName>
    </customValue>
    <customValue>
        <fullName>1000</fullName>
    </customValue>
    <description>for NATT CPQ</description>
    <masterLabel>NATT Deductible</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/QuoteLineTriggerHandlerNATT.cls
public class QuoteLineTriggerHandlerNATT extends QuoteLineTriggerHandlerAbstract{ 
    
    private final String nattUnitRecTypeId = Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByDeveloperName().get('NATT_Units_Quote').getRecordTypeId();
    
    public override void handleBeforeInsert(List<SObject> newQuoteLines){ 
        
        Set<Id> clonedQuoteLinesSet = new Set<Id>();
        Set<Id> amendmentQuoteSet = new Set<Id>();
        Map<String,Decimal> orginalOrderIdLinesMap = new Map<String,Decimal>();
        
        for(SBQQ__QuoteLine__c ql : (List<SBQQ__QuoteLine__c>)newQuoteLines){
            System.debug('qlqlqlq: ' + ql.SBQQ__ProductName__c + ql.NATT_Quote_Type__c + ql.NATT_Quote_Record_Type_ID__c + nattUnitRecTypeId + ql.NATT_Is_Base_Unit__c + ql.NATT_Original_Order_Id__c);
            if(ql.NATT_Quote_Type__c == 'Amendment' 
               && ql.NATT_Quote_Record_Type_ID__c == nattUnitRecTypeId
               && ql.NATT_Is_Base_Unit__c
               && ql.NATT_Original_Order_Id__c <> null)
            {
                amendmentQuoteSet.add(ql.SBQQ__Quote__c);
                
                if(orginalOrderIdLinesMap.containsKey(ql.NATT_Original_Order_Id__c)){
                    orginalOrderIdLinesMap.put(ql.NATT_Original_Order_Id__c, orginalOrderIdLinesMap.get(ql.NATT_Original_Order_Id__c) + ql.SBQQ__PriorQuantity__c);
                }else{
                    orginalOrderIdLinesMap.put(ql.NATT_Original_Order_Id__c, ql.SBQQ__PriorQuantity__c);
                }
            }
            
            // defaults values on clone
            if(ql.isClone() && ql.SBQQ__Source__c <> null){
                clonedQuoteLinesSet.add(ql.SBQQ__Source__c);
            }
           /* Removing becuase of issues with old design
            if(ql.NATT_Extended_Basic_Months__c != null && ql.NATT_Optional_Coverage_Months__c != null && ql.NATT_Optional_Coverage_Months__c > ql.NATT_Extended_Basic_Months__c){
                ql.addError('Optional Coverage Months must be less than or equal to Extended Basic Months.');
            }
            
            if(ql.NATT_Extended_Basic_Hours__c != null && ql.NATT_Optional_Coverage_Hours__c != null && ql.NATT_Optional_Coverage_Hours__c > ql.NATT_Extended_Basic_Hours__c){
                ql.addError('Optional Coverage Hours must be less than or equal to Extended Basic Hours.');
            }
            
            if(ql.NATT_Coverage_Type__c == 'Extended Basic + Major Component' && ql.NATT_Major_Component_Months__c != null && ql.NATT_Extended_Basic_Months__c != null && ql.NATT_Extended_Basic_Months__c > ql.NATT_Major_Component_Months__c){
                ql.addError('Extended Basic Months must be less than or equal to Major Component Months.');
            }
            // Removing becuase of error and change of design - CREEDY 1/10/22
            //if(ql.NATT_Coverage_Type__c == 'Extended Basic + Major Component' && ql.NATT_Major_Component_Hours__c != null && ql.NATT_Extended_Basic_Hours__c != null && ql.NATT_Extended_Basic_Hours__c > ql.NATT_Major_Component_Hours__c){
            //    ql.addError('Extended Basic Hours must be less than or equal to Major Component Hours.');
            //}
            
            if(ql.NATT_Coverage_Type__c == 'Extended Basic + Major Component' && ql.NATT_Major_Component_Months__c != null && ql.NATT_Optional_Coverage_Months__c != null && ql.NATT_Optional_Coverage_Months__c > ql.NATT_Major_Component_Months__c){
                ql.addError('Optional Coverage Months must be less than or equal to Major Component Months.');
            }
            
            if(ql.NATT_Coverage_Type__c == 'Extended Basic + Major Component' && ql.NATT_Major_Component_Hours__c != null && ql.NATT_Optional_Coverage_Hours__c != null && ql.NATT_Optional_Coverage_Hours__c > ql.NATT_Major_Component_Hours__c){
                ql.addError('Optional Coverage Months must be less than or equal to Major Component Hours.');
            } */
        }
        System.debug('orginalOrderIdLinesMap'+orginalOrderIdLinesMap);
        if(!orginalOrderIdLinesMap.isEmpty()){            
            System.debug('amendmentQuoteSet'+amendmentQuoteSet);
            Map<Id,SBQQ__Quote__c> quoteMap = new Map<Id,SBQQ__Quote__c>([Select Id,
                                                                          NATT_Enforce_Amendment_Error__c 
                                                                          From SBQQ__Quote__c 
                                                                          Where Id IN :amendmentQuoteSet]);
            
            Map<String, Decimal> assetQtyMap = new Map<String, Decimal>();
            
            for(AggregateResult agr : [Select NATT_Original_Order_Id__c,
                                       SUM(Quantity) agrQty
                                       From Asset
                                       Where NATT_Is_Base_Unit__c = true 
                                       AND NATT_Original_Order_Id__c IN :orginalOrderIdLinesMap.keySet() Group By NATT_Original_Order_Id__c])
            {
                assetQtyMap.put((String)agr.get('NATT_Original_Order_Id__c'),(Decimal)agr.get('agrQty'));
            }
            
            System.debug('assetQtyMap'+assetQtyMap);
            
            for(SBQQ__QuoteLine__c ql : (List<SBQQ__QuoteLine__c>)newQuoteLines){
                System.debug('aaaNATT_Enforce_Amendment_Error__c'+quoteMap.get(ql.SBQQ__Quote__c).NATT_Enforce_Amendment_Error__c);
                 System.debug('bbbNATT_Original_Order_Id__c'+assetQtyMap.get(ql.NATT_Original_Order_Id__c));
                 System.debug('cccNATT_Original_Order_Id__c'+orginalOrderIdLinesMap.get(ql.NATT_Original_Order_Id__c));
                if(quoteMap.get(ql.SBQQ__Quote__c).NATT_Enforce_Amendment_Error__c && assetQtyMap.get(ql.NATT_Original_Order_Id__c) > orginalOrderIdLinesMap.get(ql.NATT_Original_Order_Id__c)){
                    ql.addError('Please select all assets before you click the Amend button.');
                }
            }
            
            List<SBQQ__Quote__c> updateAmendedQuotes = new List<SBQQ__Quote__c>();
            for(SBQQ__Quote__c amendedQuote : quoteMap.values()){
                if(amendedQuote.NATT_Enforce_Amendment_Error__c){
                    amendedQuote.NATT_Enforce_Amendment_Error__c = false;
                    updateAmendedQuotes.add(amendedQuote);
                }
            }
            
            if(!updateAmendedQuotes.isEmpty()){
                update updateAmendedQuotes;
            } 
        }
        
        if(!clonedQuoteLinesSet.isEmpty()){
            
            Map<Id,SBQQ__QuoteLine__c> clonedQuoteLinesMap = new Map<Id,SBQQ__QuoteLine__c>([Select Id,
                                                                                             NATT_Extended_Basic_Months__c,
                                                                                             NATT_Extended_Basic_Hours__c,
                                                                                             NATT_Major_Component_Months__c,
                                                                                             NATT_Major_Component_Hours__c,
                                                                                             NATT_Major_Component_Deductible__c,
                                                                                             NATT_Optional_Coverage_Months__c,
                                                                                             NATT_Optional_Coverage_Hours__c,
                                                                                             NATT_CMRA_Term_Years__c,
                                                                                             NATT_Coverage_Type__c
                                                                                             From SBQQ__QuoteLine__c Where Id IN :clonedQuoteLinesSet]);
            
            for(SBQQ__QuoteLine__c ql : (List<SBQQ__QuoteLine__c>)newQuoteLines){
                
                // defaults values on clone
                if(ql.isClone() && ql.SBQQ__Source__c <> null && clonedQuoteLinesMap.containsKey(ql.SBQQ__Source__c)){
                    ql.NATT_Locked__c = false;
                    ql.NATT_Extended_Basic_Months__c = clonedQuoteLinesMap.get(ql.SBQQ__Source__c).NATT_Extended_Basic_Months__c != null ? clonedQuoteLinesMap.get(ql.SBQQ__Source__c).NATT_Extended_Basic_Months__c : '';
                    ql.NATT_Extended_Basic_Hours__c = clonedQuoteLinesMap.get(ql.SBQQ__Source__c).NATT_Extended_Basic_Hours__c != null ? clonedQuoteLinesMap.get(ql.SBQQ__Source__c).NATT_Extended_Basic_Hours__c : '';
                    ql.NATT_Major_Component_Months__c = clonedQuoteLinesMap.get(ql.SBQQ__Source__c).NATT_Major_Component_Months__c != null ? clonedQuoteLinesMap.get(ql.SBQQ__Source__c).NATT_Major_Component_Months__c : '';
                    ql.NATT_Major_Component_Hours__c = clonedQuoteLinesMap.get(ql.SBQQ__Source__c).NATT_Major_Component_Hours__c != null ? clonedQuoteLinesMap.get(ql.SBQQ__Source__c).NATT_Major_Component_Hours__c : '';
                    ql.NATT_Major_Component_Deductible__c = clonedQuoteLinesMap.get(ql.SBQQ__Source__c).NATT_Major_Component_Deductible__c != null ? clonedQuoteLinesMap.get(ql.SBQQ__Source__c).NATT_Major_Component_Deductible__c : '';
                    ql.NATT_Optional_Coverage_Months__c = clonedQuoteLinesMap.get(ql.SBQQ__Source__c).NATT_Optional_Coverage_Months__c != null ? clonedQuoteLinesMap.get(ql.SBQQ__Source__c).NATT_Optional_Coverage_Months__c : '';
                    ql.NATT_Optional_Coverage_Hours__c = clonedQuoteLinesMap.get(ql.SBQQ__Source__c).NATT_Optional_Coverage_Hours__c != null ? clonedQuoteLinesMap.get(ql.SBQQ__Source__c).NATT_Optional_Coverage_Hours__c : '';
                    ql.NATT_CMRA_Term_Years__c = clonedQuoteLinesMap.get(ql.SBQQ__Source__c).NATT_CMRA_Term_Years__c != null ? clonedQuoteLinesMap.get(ql.SBQQ__Source__c).NATT_CMRA_Term_Years__c : null;
                    ql.NATT_Coverage_Type__c = clonedQuoteLinesMap.get(ql.SBQQ__Source__c).NATT_Coverage_Type__c != null ? clonedQuoteLinesMap.get(ql.SBQQ__Source__c).NATT_Coverage_Type__c : '';
                }  
            }
        }
    }
    
    public override void handleBeforeUpdate(Map<Id,Sobject> trgOldMap, Map<Id,SObject> trgNewMap){
        /*
        Map<Id,SBQQ__QuoteLine__c> newQuoteLineMap = (Map<Id,SBQQ__QuoteLine__c>)trgNewMap;
        Map<Id,SBQQ__QuoteLine__c> oldQuoteLineMap = (Map<Id,SBQQ__QuoteLine__c>)trgOldMap;
        
        for(SBQQ__QuoteLine__c ql : newQuoteLineMap.values()){
            
            if(ql.NATT_Quote_Type__c == 'Amendment' 
               && ql.NATT_Quote_Record_Type_ID__c == nattUnitRecTypeId
               && ql.NATT_Locked__c)
            { 
                // quantity changes are not allowed on locked quote lines
                if(ql.SBQQ__Quantity__c <> oldQuoteLineMap.get(ql.Id).SBQQ__Quantity__c){
                    ql.addError('This unit has been locked for editing due to its order status (Quantity Changes) - '+ql.Name);
                }
                
                // Price changes are not allowed on locked quote lines
                if(ql.SBQQ__NetPrice__c <> oldQuoteLineMap.get(ql.Id).SBQQ__NetPrice__c){
                    ql.addError('This unit has been locked for editing due to its order status (Price Changes) - '+ql.Name);
                }
                
                // End Customer Price changes are not allowed on locked quote lines
                if(ql.NATT_End_Customer_Price__c <> oldQuoteLineMap.get(ql.Id).NATT_End_Customer_Price__c){
                    ql.addError('This unit has been locked for editing due to its order status (End Customer Prices) - '+ql.Name);
                }
            } 
            
            if(ql.NATT_Quote_Type__c == 'Amendment' 
               && ql.NATT_Quote_Record_Type_ID__c == nattUnitRecTypeId
               && ql.NATT_Locked__c
               && ql.SBQQ__UpgradedAsset__c <> null
               && ql.NATT_P_N__c == null
               && !ql.NATT_Is_Base_Unit__c)
            { 
                // quantity changes are not allowed on locked quote lines
                if(ql.SBQQ__Quantity__c <> oldQuoteLineMap.get(ql.Id).SBQQ__Quantity__c){
                    ql.addError('You may not change the Line # - '+ql.SBQQ__Number__c+' - '+ ql.SBQQ__ProductName__c +' because it is on unit.');
                }
                
                // Price changes are not allowed on locked quote lines
                if(ql.SBQQ__NetPrice__c <> oldQuoteLineMap.get(ql.Id).SBQQ__NetPrice__c){
                    ql.addError('You may not change the Line # - '+ql.SBQQ__Number__c+' - '+ ql.SBQQ__ProductName__c +' because it is on unit.');
                }
                
                // End Customer Price changes are not allowed on locked quote lines
                if(ql.NATT_End_Customer_Price__c <> oldQuoteLineMap.get(ql.Id).NATT_End_Customer_Price__c){
                    ql.addError('You may not change the Line # - '+ql.SBQQ__Number__c+' - '+ ql.SBQQ__ProductName__c +' because it is on unit.');
                }
            } 
          /* Removing because this moved from code to configuration  
            if(ql.NATT_Extended_Basic_Months__c != null && ql.NATT_Optional_Coverage_Months__c != null && ql.NATT_Optional_Coverage_Months__c > ql.NATT_Extended_Basic_Months__c){
                ql.addError('Optional Coverage Months must be less than or equal to Extended Basic Months.');
            }
            
            if(ql.NATT_Extended_Basic_Hours__c != null && ql.NATT_Optional_Coverage_Hours__c != null && ql.NATT_Optional_Coverage_Hours__c > ql.NATT_Extended_Basic_Hours__c){
                ql.addError('Optional Coverage Hours must be less than or equal to Extended Basic Hours.');
            }
            
            if(ql.NATT_Coverage_Type__c == 'Extended Basic + Major Component' && ql.NATT_Major_Component_Months__c != null && ql.NATT_Extended_Basic_Months__c != null && ql.NATT_Extended_Basic_Months__c > ql.NATT_Major_Component_Months__c){
                ql.addError('Extended Basic Months must be less than or equal to Major Component Months.');
            }
            
            //if(ql.NATT_Coverage_Type__c == 'Extended Basic + Major Component' && ql.NATT_Major_Component_Hours__c != null && ql.NATT_Extended_Basic_Hours__c != null && ql.NATT_Extended_Basic_Hours__c > ql.NATT_Major_Component_Hours__c){
            //    ql.addError('Extended Basic Hours must be less than or equal to Major Component Hours.');
            //}
            
            if(ql.NATT_Coverage_Type__c == 'Extended Basic + Major Component' && ql.NATT_Major_Component_Months__c != null && ql.NATT_Optional_Coverage_Months__c != null && ql.NATT_Optional_Coverage_Months__c > ql.NATT_Major_Component_Months__c){
                ql.addError('Optional Coverage Months must be less than or equal to Major Component Months.');
            }
            
            if(ql.NATT_Coverage_Type__c == 'Extended Basic + Major Component' && ql.NATT_Major_Component_Hours__c != null && ql.NATT_Optional_Coverage_Hours__c != null && ql.NATT_Optional_Coverage_Hours__c > ql.NATT_Major_Component_Hours__c){
                ql.addError('Optional Coverage Months must be less than or equal to Major Component Hours.');
            }
        }*/
    }
    
    public override void handleBeforeDelete(Map<Id,SObject> oldQuoteLinesMap){ 
        /*
        for(SBQQ__QuoteLine__c ql : (List<SBQQ__QuoteLine__c>) oldQuoteLinesMap.values()){
            
            if(ql.NATT_Quote_Type__c == 'Amendment' 
               && ql.NATT_Quote_Record_Type_ID__c == nattUnitRecTypeId 
               && ql.SBQQ__ProductCode__c == 'BluEdge')
            {
                ql.addError('BluEdge Bundle can not be modified during amendments. Create a new after market Quote for any changes to BluEdge.');
            }
            
            if(ql.NATT_Quote_Type__c == 'Amendment' 
               && ql.NATT_Quote_Record_Type_ID__c == nattUnitRecTypeId 
               && ql.NATT_Locked__c 
               && ql.NATT_Is_Base_Unit__c)
            {
                ql.addError('This unit has been locked and can not be deleted.');
            }
            
            if(ql.NATT_Quote_Type__c == 'Amendment' 
               && ql.NATT_Quote_Record_Type_ID__c == nattUnitRecTypeId 
               && ql.NATT_Locked__c 
               && ql.SBQQ__UpgradedAsset__c <> null
               && ql.NATT_P_N__c == null
               && !ql.NATT_Is_Base_Unit__c)
            {
                ql.addError('You may not change the Line # - '+ql.SBQQ__Number__c+' - '+ ql.SBQQ__ProductName__c+' because it is on unit.');
            }
        }*/
    }
}