NATTQA-ENV/force-app/main/default/objects/CONTAINER_Service_Agreement__c/CONTAINER_Service_Agreement__c.object-meta.xml
<CustomObject>
    <description>Custom Container Service Agreement object</description>
    <label>Service Agreement</label>
    <nameField>
        <displayFormat>SA-{00000}</displayFormat>
        <label>Service Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/CONTAINER_Service_Agreement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Account for Container Service Agreement object</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Agreements</relationshipLabel>
    <relationshipName>Service_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/ServiceAgreementBatch.cls
/* Created a Batch class to create a ServiceAgreementBatch records with read access to the existing records
 * Created by : Rajasekharreddy Kotella
 * Created on : o4-10-2024
 * Class Name : ServiceAgreementBatch
 * Description: Rub the below code in to excute Batch
 * 				ServiceAgreementBatch batch = new ServiceAgreementBatch();
 * 				Database.executeBatch(batch, 50);
 */
public class ServiceAgreementBatch implements Database.Batchable<SObject>, Database.Stateful {

    // Start method to define the query
    public Database.QueryLocator start(Database.BatchableContext bc) {
        // Query for the records you want to process in the batch
        return Database.getQueryLocator([SELECT Id, Account__c, Account__r.RecordType.Name 
                                         FROM CONTAINER_Service_Agreement__c  WHERE Account__r.RecordType.Name = 'CONTAINER Authorized Service Provider'  ]);
    }

    public void execute(Database.BatchableContext bc, List<CONTAINER_Service_Agreement__c> SAList) {
        ServiceAgreementTriggerHelper.ShareServiceAgriment(SAList);
    }

    // Finish method, called after all batches are processed
    public void finish(Database.BatchableContext bc) {
        System.debug('Batch process completed.');
    }
}