NATTQA-ENV/force-app/main/default/objects/Opportunity_Scheduled_Pick_Date__c/Opportunity_Scheduled_Pick_Date__c.object-meta.xml
<CustomObject>
    <label>Opportunity Requested Ship Date</label>
    <nameField>
        <displayFormat>OSPD-{0000}</displayFormat>
        <label>Opportunity Requested Ship Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Requested Ship Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/Opportunity_Scheduled_Pick_Date__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Opportunity_Scheduled_Pick_Dates</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity_Scheduled_Pick_Date__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <label>Requested Ship Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity_Scheduled_Pick_Date__c/fields/Scheduled_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Quantity__c</fullName>
    <label>Requested Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OpportunityLineItem/fields/NATT_Is_Base_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Is_Base_Unit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>represents that this line is a base unit</description>
    <label>Is Base Unit</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Is_Base_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Is_Base_Unit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>for base units only</description>
    <label>Is Base Unit</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/OpportunityScheduleHandler.cls
public class OpportunityScheduleHandler {

    public static void syncPickDatesToSchedule(List<Opportunity_Scheduled_Pick_Date__c> pickDates) {
        if (pickDates == null || pickDates.isEmpty()) return;

        Set<Id> oppIds = new Set<Id>();
        for (Opportunity_Scheduled_Pick_Date__c pd : pickDates) {
            if (pd.Opportunity__c != null) {
                oppIds.add(pd.Opportunity__c);
            }
        }
        if (oppIds.isEmpty()) return;

        List<OpportunityLineItem> baseUnitOLIs = [
            SELECT Id, OpportunityId, Product2.NATT_Is_Base_Unit__c, TotalPrice, Quantity,Product2.CanUseQuantitySchedule,Product2.CanUseRevenueSchedule,Product2.Name
            FROM OpportunityLineItem
            WHERE OpportunityId IN :oppIds AND Product2.NATT_Is_Base_Unit__c = true and Opportunity.RecordType.Name IN  ( 'Units', 'CTBR Units', 'MX Units', 'CONTAINER Opportunity') ];
        

        
        List<OpportunityLineItemSchedule> schedulesToInsert = new List<OpportunityLineItemSchedule>();

        for (Opportunity_Scheduled_Pick_Date__c pd : pickDates) {
            if (pd.Scheduled_Date__c == null || pd.Scheduled_Quantity__c == null) continue;
            Boolean errorAdded = false;
            for (OpportunityLineItem oli : baseUnitOLIs) {
                if (oli.OpportunityId != pd.Opportunity__c) continue;
                
                if (!oli.Product2.CanUseQuantitySchedule ||!oli.Product2.CanUseRevenueSchedule) {

                    if (!errorAdded) {
                      pd.addError('Scheduling cannot proceed for product "' + oli.Product2.Name + '" because it does not support both Quantity and Revenue scheduling. Please update the product configuration to enable these options.');
                        errorAdded = true;
                    }
                    continue;
                }

                   OpportunityLineItemSchedule sched = new OpportunityLineItemSchedule();
                    sched = new OpportunityLineItemSchedule();
                    sched.OpportunityLineItemId = oli.Id;
                    sched.Type = 'Both';
                    sched.Revenue = oli.TotalPrice;
                    sched.Quantity = oli.Quantity;
                    sched.ScheduleDate = pd.Scheduled_Date__c;
                    schedulesToInsert.add(sched);
            }
        }

        
        if (!schedulesToInsert.isEmpty()) {
            upsert schedulesToInsert;
        }
         
    }
}