NATTQA-ENV/force-app/main/default/objects/CONTAINER_Control_Trigger_And_Validation__mdt/CONTAINER_Control_Trigger_And_Validation__mdt.object-meta.xml
<CustomObject>
    <description>This metadata type is created for general utility class to control triggers</description>
    <label>CONTAINER Control Trigger And Validation</label>
    <pluralLabel>CONTAINER Control Trigger And Validation</pluralLabel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/CONTAINER_Control_Trigger_And_Validation__mdt/fields/CONTAINER_Skip_Trigger_Flag__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Skip_Trigger_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Trigger Flag?</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/CONTAINER_Control_Trigger_And_Validation__mdt/fields/CONTAINER_Trigger_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Trigger_Class_Name__c</fullName>
    <description>Class Name of Trigger to be used in general Utility</description>
    <label>Trigger Class Name</label>
    <type>TextArea</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_ASO_ID__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_ASO_ID__c</fullName>
    <label>ASO ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Sales_Region__c</fullName>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>APO</fullName>
            </value>
            <value>
                <fullName>NAO</fullName>
            </value>
            <value>
                <fullName>SNAO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/CONTAINER_TriggerHandler_Test.cls
@isTest public class CONTAINER_TriggerHandler_Test {
	@isTest static void testafterInsert(){
        CONTAINER_UtilityClass.createCustomerQuoteBulk_NT();  
        CONTAINER_TriggerHandler obj = new CONTAINER_TriggerHandler();
        obj.setMaxLoopCount(100);
        obj.clearMaxLoopCount();
        CONTAINER_TriggerHandler.bypass('ContainerQuoteTrigger');
        CONTAINER_TriggerHandler.clearBypass('ContainerQuoteTrigger');
        CONTAINER_TriggerHandler.isBypassed('ContainerQuoteTrigger');
        CONTAINER_TriggerHandler.clearAllBypasses();
        
    }
    public static testMethod void testRunAs() {
        /// This code runs as the system user
        Profile prof = [SELECT Id FROM Profile WHERE Name='CONTAINER Administrator'];
        User newUser = new User(Alias = 'contAdm', Email='contAdmin@carrier.com', LastName='AdminTest', ProfileId = prof.Id, 
                                UserName='testAdminUser@carrier.com', EmailEncodingKey='UTF-8', 
                                LanguageLocaleKey='en_US', LocaleSidKey='en_US', TimeZoneSidKey='America/Los_Angeles');
        insert newUser;
        
        System.runAs(newUser) {
            try{    
                
                CONTAINER_UtilityClass.createCustomerQuote();
                List<CONTAINER_Control_Trigger_And_Validation__mdt> eachMD = [SELECT DeveloperName, CONTAINER_Skip_Trigger_Flag__c, CONTAINER_Trigger_Class_Name__c FROM CONTAINER_Control_Trigger_And_Validation__mdt WHERE CONTAINER_Skip_Trigger_Flag__c = TRUE];
                List<SBQQ__Quote__c> quoteID = [select Id from SBQQ__Quote__c where CONTAINER_ASO_ID__c ='3415'];
                quoteID[0].CONTAINER_Sales_Region__c=ContainerConstants.NAO;
                update quoteID[0];
                delete quoteID;
                List<SBQQ__Quote__c> undeletequoteID = [select Id from SBQQ__Quote__c where CONTAINER_ASO_ID__c ='3415' ALL ROWS];
                undelete undeletequoteID;
            }
            catch(Exception e){
                Boolean expectedExceptionThrown =  (e.getMessage().contains('You do not have permissions to delete the record:')) ? true : false;
               
            }
        }
    }
}