NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/NATT_ItemPriceStaging__c.object-meta.xml
<CustomObject>
    <description>Staging object for imported PartsNet item pricing from JDE (RCGWEB23 &amp; RCGWEB26). Includes standard list prices, customer-specific item prices, and quantity price tiers</description>
    <label>NATT Item Price Staging</label>
    <nameField>
        <displayFormat>IPS-{0000000000}</displayFormat>
        <label>NATT Item Price Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NATT Item Price Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_CustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>NATT_CustomerNumber__c</fullName>
    <description>Customer number this adjustment record applies to. If NULL the record is not customer specifc</description>
    <label>Customer Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_ExpiryDate__c</fullName>
    <description>Date this price expires and no longer applies</description>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_ItemNumber__c.field-meta.xml
<CustomField>
    <fullName>NATT_ItemNumber__c</fullName>
    <description>Unique number that identifies the item</description>
    <label>Item Number</label>
    <length>48</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_Product__c.field-meta.xml
<CustomField>
    <fullName>NATT_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>NATT Item Price Staging</relationshipLabel>
    <relationshipName>NATT_Item_Price_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/PricebookEntry/fields/NATT_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>NATT_Effective_Date__c</fullName>
    <description>Indicates the date this pricebook entry was effective. The field supports the PPG B2B Commerce implementation, and provides information necessary to generate price change reports.</description>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/InActivateExpiredPricingBtch.cls
global class InActivateExpiredPricingBtch  implements Database.Batchable<sObject>,  database.stateful {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        string query = 'select id,NATT_CustomerNumber__c,NATT_Product__c, NATT_ExpiryDate__c,NATT_ItemNumber__c from NATT_ItemPriceStaging__c  where NATT_CustomerNumber__c != 0  and   NATT_ExpiryDate__c<today order by NATT_ExpiryDate__c desc';
        return Database.getQueryLocator(query); 
    }
    
    global void execute(Database.BatchableContext BC, List<NATT_ItemPriceStaging__c> scope) {
        try{
            set<Id> prodId = new set<Id>(); 
            set<string> custNumberSet = new set<string>();
            list<PricebookEntry> pbEntryList = new list<PricebookEntry>();
            list<PricebookEntry> pbEntriersToUpdate = new list<PricebookEntry>();
            map<string, NATT_ItemPriceStaging__c> recentPASMap = new map<string, NATT_ItemPriceStaging__c>();
            
            for(NATT_ItemPriceStaging__c pas : scope){
                string productId = pas.NATT_Product__c ; 
                string customerNum = String.valueOf( pas.NATT_CustomerNumber__c );
                custNumberSet.add(customerNum);
                if( ! (recentPASMap.containsKey(productId+ customerNum))){
                recentPASMap.put( productId+customerNum  , pas );
                }
               
            }
            system.debug('recentPASMap-'+recentPASMap.size() );
            for(NATT_ItemPriceStaging__c pas : recentPASMap.values()) {
                prodId.add(pas.NATT_Product__c);
            }
            
            list<product2> productList = [ SELECT Id, Name, (select id,Name,Product2Id, NATT_Effective_Date__c,Pricebook2Id, Pricebook2.Name,IsActive from PricebookEntries where  Pricebook2.name =:custNumberSet and isActive=true ) FROM product2 where id =: prodId];
            system.debug('productList-'+productList.size());
            for(product2 prod: productList ){
                pbEntryList.addall(prod.PricebookEntries);
            }
            system.debug('pbEntryList-'+pbEntryList.size());
            for (PricebookEntry pbe : pbEntryList){
                If(pbe.IsActive == True){
                pbe.IsActive = false;
                pbEntriersToUpdate.add(pbe);
                }
            }
            system.debug('pbEntriersToUpdate-'+pbEntriersToUpdate.size());
            if (!pbEntriersToUpdate.isEmpty() ) {
                Database.SaveResult[] saveResults = Database.update (pbEntriersToUpdate,false);
            }
        } 
        catch(exception e){
            system.debug('line-'+e.getLineNumber ()+'-error- '+e);
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
   
    
}