NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/NATT_ItemPriceStaging__c.object-meta.xml
<CustomObject>
    <description>Staging object for imported PartsNet item pricing from JDE (RCGWEB23 &amp; RCGWEB26). Includes standard list prices, customer-specific item prices, and quantity price tiers</description>
    <label>NATT Item Price Staging</label>
    <nameField>
        <displayFormat>IPS-{0000000000}</displayFormat>
        <label>NATT Item Price Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NATT Item Price Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_Product__c.field-meta.xml
<CustomField>
    <fullName>NATT_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>NATT Item Price Staging</relationshipLabel>
    <relationshipName>NATT_Item_Price_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/recordTypes/NATT_Products.recordType-meta.xml
<RecordType>
    <fullName>NATT_Products</fullName>
    <active>true</active>
    <description>For use with NATT CPQ</description>
    <label>NATT Products</label>
</RecordType>

NATTQA-ENV/force-app/main/default/classes/ItemPriceStagingTrgHandlerTest.cls
@IsTest
private class ItemPriceStagingTrgHandlerTest {
    @IsTest
    static void myUnitTest(){
        Product2 p = new Product2(Name='Test',IsActive=true,RecordTypeId=Schema.SobjectType.Product2.getRecordTypeInfosByDeveloperName().get('NATT_Products').getRecordTypeId());
        insert p;

        WebStore testPp = new WebStore(Name = 'Test Performance Parts');
        insert testPp;

        ProductCatalog pCat = new ProductCatalog(Name='Test Cat');
        insert pCat;

        WebStoreCatalog wsc = new WebStoreCatalog(SalesStoreId=testPp.Id,ProductCatalogId=pCat.Id);
        insert wsc;

        

        ProductCategory pc = new ProductCategory(Name='Products',CatalogId=pCat.Id);
        insert pc;

        NATT_ItemPriceStaging__c ips = new NATT_ItemPriceStaging__c(NATT_Product__c=p.Id);
        insert ips;
    }
}