NATTQA-ENV/force-app/main/default/objects/CONTAINER_Quote_Revision_Mapping__mdt/CONTAINER_Quote_Revision_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Quote Revision Mapping</label>
    <pluralLabel>Quote Revision Mappings</pluralLabel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/CONTAINER_Quote_Revision_Mapping__mdt/fields/Revision_Name__c.field-meta.xml
<CustomField>
    <fullName>Revision_Name__c</fullName>
    <label>Revision Name</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/CONTAINER_Quote_Revision_Mapping__mdt/fields/Revision_Number__c.field-meta.xml
<CustomField>
    <fullName>Revision_Number__c</fullName>
    <label>Revision Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/CONTAINER_ASO_ID__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_ASO_ID__c</fullName>
    <label>ASO ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/CONTAINER_ASO_Rev__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_ASO_Rev__c</fullName>
    <formula>SBQQ__Quote__r.CONTAINER_ASO_Rev__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ASO Rev</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/CONTAINER_Job__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Job__c</fullName>
    <label>Job #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>The quote where the order is created from.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_ASO_ID__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_ASO_ID__c</fullName>
    <label>ASO ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_ASO_Rev__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_ASO_Rev__c</fullName>
    <label>ASO Rev</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Genset_Previous_ASO_ID__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Genset_Previous_ASO_ID__c</fullName>
    <label>Genset Previous ASO ID</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_GENSET_RevNumber__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_GENSET_RevNumber__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GENSET RevNumber</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_IsRevised__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_IsRevised__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsRevised</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Job__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Job__c</fullName>
    <label>Job #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_NT_Previous_ASO_ID__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_NT_Previous_ASO_ID__c</fullName>
    <label>NT Previous ASO ID</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_NT_RevNumber__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_NT_RevNumber__c</fullName>
    <label>NT RevNumber</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_QuotePath__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_QuotePath__c</fullName>
    <description>Container Sales Quote Path which updates based on Quote Status field</description>
    <label>Path</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending PM Approval</fullName>
            </value>
            <value>
                <fullName>Pending CAM Approval</fullName>
            </value>
            <value>
                <fullName>Pending VP Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Order/Pending for Job #</fullName>
            </value>
            <value>
                <fullName>Job # Issued</fullName>
            </value>
            <value>
                <fullName>ASO Released</fullName>
            </value>
            <value>
                <fullName>SO Released</fullName>
            </value>
            <value>
                <fullName>Lost/Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Revision_Date__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Revision_Date__c</fullName>
    <label>Revision Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Status__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Status__c</fullName>
    <description>It will populate here as per the actual status of the quote.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending PM Approval</fullName>
            </value>
            <value>
                <fullName>Pending RSM Acceptance for Special Req</fullName>
            </value>
            <value>
                <fullName>Pending CAM Approval</fullName>
            </value>
            <value>
                <fullName>Pending RSM Acceptance for Prod &amp; Ship Schedule</fullName>
            </value>
            <value>
                <fullName>Pending VP Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Order/Pending for Job #</fullName>
            </value>
            <value>
                <fullName>Job # Issued</fullName>
            </value>
            <value>
                <fullName>ASO Released</fullName>
            </value>
            <value>
                <fullName>SO Released</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
                <label>Lost/Cancelled</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
                <isActive>false</isActive>
                <label>Ordered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/Container_Quote_ASOID_Release_Handler.cls
public without sharing class Container_Quote_ASOID_Release_Handler {
    @InvocableMethod(label='Get ASO Quote Details')
    public static void container_ASOID_Update(List<String> SBQQQuoteId){
        system.debug('Ids----- :'+SBQQQuoteId);
        
        List<SBQQ__Quote__c> quoteList = [SELECT Id,CONTAINER_ASO_ID__c,CONTAINER_ASO_Rev__c,CONTAINER_Status__c,CONTAINER_GENSET_RevNumber__c,CONTAINER_NT_RevNumber__c,CONTAINER_Genset_Previous_ASO_ID__c,CONTAINER_NT_Previous_ASO_ID__c,CONTAINER_Job__c,RecordTypeId from SBQQ__Quote__c where Id =: SBQQQuoteId WITH SECURITY_ENFORCED];
        system.debug(quoteList);
        
        // Get all metadata revision mapping records
        Map<Integer,String> mapQuoteRevNumbertoName = new Map<Integer,String>();
        for(CONTAINER_Quote_Revision_Mapping__mdt obj : [SELECT Revision_Name__c, Revision_Number__c FROM CONTAINER_Quote_Revision_Mapping__mdt WITH SECURITY_ENFORCED]){
            if(!mapQuoteRevNumbertoName.containsKey(Integer.valueOf(obj.Revision_Number__c))){
                mapQuoteRevNumbertoName.put(Integer.valueOf(obj.Revision_Number__c),obj.Revision_Name__c);
            } 
        }
        
        // fetch current GENSET ASO ID from all GENSET Quote Filter based on record type & ASO_ID__c != null  sort by ASO_ID__c DESC LIMIT 1
        //List<SBQQ__Quote__c> currentGENSETASOId = [select CONTAINER_ASO_ID__c from SBQQ__Quote__c where CONTAINER_ASO_ID__c != '' and RecordType.name = 'Container GENSET Quote'  ORDER BY CONTAINER_ASO_ID__c DESC limit 1] ;
         SBQQ__Quote__c currentGENSETASOId;
        Integer GensetASOId = 0;
        for(SBQQ__Quote__c objGENSET : [SELECT CONTAINER_ASO_ID__c from SBQQ__Quote__c where CONTAINER_ASO_ID__c != '' and RecordType.name = 'Container GENSET Quote' WITH SECURITY_ENFORCED]){
            if(Integer.valueOf(objGENSET.CONTAINER_ASO_ID__c) > GensetASOId){
                GensetASOId = Integer.valueOf(objGENSET.CONTAINER_ASO_ID__c);
                currentGENSETASOId = objGENSET;
            }
        }
        
        // fetch current NT ASO ID from all NT Quote Filter based on record type & ASO_ID__c!= null  sort by ASO_ID__c DESC LIMIT 1
        //List<SBQQ__Quote__c> currentNTASOId = [select CONTAINER_ASO_ID__c from SBQQ__Quote__c where CONTAINER_ASO_ID__c != '' and RecordType.name = 'Container NT Quote'] ;
        SBQQ__Quote__c currentNTASOId;
        Integer NTASOId = 0;
        for(SBQQ__Quote__c objNT : [SELECT CONTAINER_ASO_ID__c from SBQQ__Quote__c where CONTAINER_ASO_ID__c != '' and RecordType.name = 'Container NT Quote' WITH SECURITY_ENFORCED]){
            if(Integer.valueOf(objNT.CONTAINER_ASO_ID__c) > NTASOId){
                NTASOId = Integer.valueOf(objNT.CONTAINER_ASO_ID__c);
                currentNTASOId = objNT;
            }
        }
        
        List<SBQQ__Quote__c> lstQuote = new List<SBQQ__Quote__c>();
        
        if(!quoteList.isEmpty()){
            for(SBQQ__Quote__c quote : quoteList){
                
                // If GENSET Record Type
                if(quote.RecordTypeId ==  Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByName().get('Container GENSET Quote').getRecordTypeId()){
                    if(currentGENSETASOId == null){
                        quote.CONTAINER_Genset_Previous_ASO_ID__c = '0001' ;
                        quote.CONTAINER_ASO_ID__c = '0001';
                        quote.CONTAINER_Status__c = 'ASO Released';
                        quote.CONTAINER_QuotePath__c = 'ASO Released';
                        
                    }else if(String.isBlank(quote.CONTAINER_ASO_ID__c) && String.isBlank(quote.CONTAINER_Genset_Previous_ASO_ID__c)){
                        
                        Integer iNext_ASO_Id = Integer.valueOf(currentGENSETASOId.CONTAINER_ASO_ID__c)+1;
                        system.debug('--'+iNext_ASO_Id);
                        if(String.valueOf(iNext_ASO_Id).length() == 3){
                            quote.CONTAINER_Genset_Previous_ASO_ID__c = '0'+String.valueOf(iNext_ASO_Id) ;
                            quote.CONTAINER_ASO_ID__c ='0'+String.valueOf(iNext_ASO_Id);
                        }else if(String.valueOf(iNext_ASO_Id).length() == 2){
                            quote.CONTAINER_Genset_Previous_ASO_ID__c = '00'+String.valueOf(iNext_ASO_Id) ;
                            quote.CONTAINER_ASO_ID__c ='00'+String.valueOf(iNext_ASO_Id);
                        }else if(String.valueOf(iNext_ASO_Id).length() == 1){
                            quote.CONTAINER_Genset_Previous_ASO_ID__c = '000'+String.valueOf(iNext_ASO_Id) ;
                            quote.CONTAINER_ASO_ID__c ='000'+String.valueOf(iNext_ASO_Id);
                        }else{
                            quote.CONTAINER_Genset_Previous_ASO_ID__c = String.valueOf(iNext_ASO_Id) ;
                            quote.CONTAINER_ASO_ID__c = String.valueOf(iNext_ASO_Id);
                        }
                        
                        
                        quote.CONTAINER_Status__c = 'ASO Released';
                        quote.CONTAINER_QuotePath__c = 'ASO Released';
                        
                        system.debug('-------updated record-----------');
                        system.debug('Previous ASO_ID ='+ quote.CONTAINER_Genset_Previous_ASO_ID__c);
                        system.debug('ASO ID ='+quote.CONTAINER_ASO_ID__c);
                        
                    }else if(String.isBlank(quote.CONTAINER_ASO_ID__c) && !String.isBlank(quote.CONTAINER_Genset_Previous_ASO_ID__c)){
                        if(quote.CONTAINER_ASO_ID__c == null && quote.CONTAINER_Genset_Previous_ASO_ID__c != null){
                            quote.CONTAINER_ASO_ID__c = quote.CONTAINER_Genset_Previous_ASO_ID__c;
                            
                            quote.CONTAINER_Status__c = 'ASO Released';
                            quote.CONTAINER_QuotePath__c = 'ASO Released';
                            system.debug('-------updated record-----------');
                            system.debug('Previous ASO_ID ='+ quote.CONTAINER_Genset_Previous_ASO_ID__c);
                            system.debug('ASO ID ='+quote.CONTAINER_ASO_ID__c);
                        }else if(Integer.valueOf(quote.CONTAINER_Genset_Previous_ASO_ID__c) > Integer.valueOf(currentGENSETASOId.CONTAINER_ASO_ID__c)){
                            Integer iNext_ASO_Id = Integer.valueOf(currentGENSETASOId.CONTAINER_ASO_ID__c)+1;
                            system.debug('--'+iNext_ASO_Id);
                            if(String.valueOf(iNext_ASO_Id).length() == 3){
                                quote.CONTAINER_Genset_Previous_ASO_ID__c = '0'+String.valueOf(iNext_ASO_Id) ;
                                quote.CONTAINER_ASO_ID__c ='0'+String.valueOf(iNext_ASO_Id);
                            }else if(String.valueOf(iNext_ASO_Id).length() == 2){
                                quote.CONTAINER_Genset_Previous_ASO_ID__c = '00'+String.valueOf(iNext_ASO_Id) ;
                                quote.CONTAINER_ASO_ID__c ='00'+String.valueOf(iNext_ASO_Id);
                            }else if(String.valueOf(iNext_ASO_Id).length() == 1){
                                quote.CONTAINER_Genset_Previous_ASO_ID__c = '000'+String.valueOf(iNext_ASO_Id) ;
                                quote.CONTAINER_ASO_ID__c ='000'+String.valueOf(iNext_ASO_Id);
                            }else{
                                quote.CONTAINER_Genset_Previous_ASO_ID__c = String.valueOf(iNext_ASO_Id) ;
                                quote.CONTAINER_ASO_ID__c = String.valueOf(iNext_ASO_Id);
                            }  
                            
                            
                            quote.CONTAINER_Status__c = 'ASO Released';
                            quote.CONTAINER_QuotePath__c = 'ASO Released';
                            
                            system.debug('-------updated record-----------');
                            system.debug('Previous ASO_ID ='+ quote.CONTAINER_Genset_Previous_ASO_ID__c);
                            system.debug('ASO ID ='+quote.CONTAINER_ASO_ID__c);
                        }
                        
                        
                    }else If (!String.isBlank(quote.CONTAINER_ASO_ID__c) && String.isBlank(quote.CONTAINER_ASO_Rev__c)){
                        quote.CONTAINER_GENSET_RevNumber__c = 0;
                        quote.CONTAINER_Revision_Date__c = system.today();
                        quote.CONTAINER_ASO_Rev__c = mapQuoteRevNumbertoName.get(Integer.valueOf(quote.CONTAINER_GENSET_RevNumber__c));
                        system.debug('-------updated 1st Revision record-----------');
                        system.debug('GENSET RevNumber ='+quote.CONTAINER_GENSET_RevNumber__c);
                        system.debug('ASO REV = '+ quote.CONTAINER_ASO_Rev__c);
                    }else If (!String.isBlank(quote.CONTAINER_ASO_ID__c) && !String.isBlank(quote.CONTAINER_ASO_Rev__c)){
                        
                        quote.CONTAINER_Revision_Date__c = system.today();
                        quote.CONTAINER_GENSET_RevNumber__c = quote.CONTAINER_GENSET_RevNumber__c +1;
                        quote.CONTAINER_ASO_Rev__c = mapQuoteRevNumbertoName.get(Integer.valueOf(quote.CONTAINER_GENSET_RevNumber__c));
                        system.debug('-------updated Revision record-----------');
                        system.debug('GENSET RevNumber ='+quote.CONTAINER_GENSET_RevNumber__c);
                        system.debug('ASO REV = '+ quote.CONTAINER_ASO_Rev__c);
                    }
                    quote.CONTAINER_IsRevised__c=TRUE;
                    lstQuote.add(quote);
                    
                }else if(quote.RecordTypeId == Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByName().get('Container NT Quote').getRecordTypeId()){
                    // If NT Record Type
                    if(currentNTASOId == null){
                        quote.CONTAINER_NT_Previous_ASO_ID__c = '0001' ;
                        quote.CONTAINER_ASO_ID__c = '0001';
                        quote.CONTAINER_Status__c = 'ASO Released';
                        quote.CONTAINER_QuotePath__c = 'ASO Released';
                        
                    }else if(quote.CONTAINER_ASO_ID__c == null && quote.CONTAINER_NT_Previous_ASO_ID__c == null){
                        Integer iNext_ASO_Id = Integer.valueOf(currentNTASOId.CONTAINER_ASO_ID__c)+1;
                        if(String.valueOf(iNext_ASO_Id).length() == 3){
                            quote.CONTAINER_NT_Previous_ASO_ID__c = '0'+String.valueOf(iNext_ASO_Id) ;
                            quote.CONTAINER_ASO_ID__c ='0'+String.valueOf(iNext_ASO_Id);
                        }else if(String.valueOf(iNext_ASO_Id).length() == 2){
                            quote.CONTAINER_NT_Previous_ASO_ID__c = '00'+String.valueOf(iNext_ASO_Id) ;
                            quote.CONTAINER_ASO_ID__c ='00'+String.valueOf(iNext_ASO_Id);
                        }else if(String.valueOf(iNext_ASO_Id).length() == 1){
                            quote.CONTAINER_NT_Previous_ASO_ID__c = '000'+String.valueOf(iNext_ASO_Id) ;
                            quote.CONTAINER_ASO_ID__c ='000'+String.valueOf(iNext_ASO_Id);
                        }else{
                            quote.CONTAINER_NT_Previous_ASO_ID__c = String.valueOf(iNext_ASO_Id) ;
                            quote.CONTAINER_ASO_ID__c = String.valueOf(iNext_ASO_Id);
                        }
                        
                        quote.CONTAINER_Status__c = 'ASO Released';
                        quote.CONTAINER_QuotePath__c = 'ASO Released';
                        
                        
                        system.debug('-------updated record-----------');
                        system.debug('Previous ASO_ID ='+ quote.CONTAINER_NT_Previous_ASO_ID__c);
                        system.debug('ASO ID ='+quote.CONTAINER_ASO_ID__c);
                        
                    }else if(quote.CONTAINER_ASO_ID__c == null && quote.CONTAINER_NT_Previous_ASO_ID__c != null){
                        if(Integer.valueOf(quote.CONTAINER_NT_Previous_ASO_ID__c) > Integer.valueOf(currentNTASOId.CONTAINER_ASO_ID__c)){
                            quote.CONTAINER_ASO_ID__c = quote.CONTAINER_NT_Previous_ASO_ID__c;
                            quote.CONTAINER_Status__c = 'ASO Released';
                            quote.CONTAINER_QuotePath__c = 'ASO Released';
                            
                            
                            system.debug('-------updated record-----------');
                            system.debug('Previous ASO_ID ='+ quote.CONTAINER_NT_Previous_ASO_ID__c);
                            system.debug('ASO ID ='+quote.CONTAINER_ASO_ID__c); 
                                                         
                        }else { //if(Integer.valueOf(quote.CONTAINER_NT_Previous_ASO_ID__c) < Integer.valueOf(currentNTASOId.CONTAINER_ASO_ID__c)){
                            Integer iNext_ASO_Id = Integer.valueOf(currentNTASOId.CONTAINER_ASO_ID__c)+1;
                            if(String.valueOf(iNext_ASO_Id).length() == 3){
                                quote.CONTAINER_NT_Previous_ASO_ID__c = '0'+String.valueOf(iNext_ASO_Id) ;
                                quote.CONTAINER_ASO_ID__c ='0'+String.valueOf(iNext_ASO_Id);
                            }else if(String.valueOf(iNext_ASO_Id).length() == 2){
                                quote.CONTAINER_NT_Previous_ASO_ID__c = '00'+String.valueOf(iNext_ASO_Id) ;
                                quote.CONTAINER_ASO_ID__c ='00'+String.valueOf(iNext_ASO_Id);
                            }else if(String.valueOf(iNext_ASO_Id).length() == 1){
                                quote.CONTAINER_NT_Previous_ASO_ID__c = '000'+String.valueOf(iNext_ASO_Id) ;
                                quote.CONTAINER_ASO_ID__c ='000'+String.valueOf(iNext_ASO_Id);
                            }else {
                                quote.CONTAINER_NT_Previous_ASO_ID__c = String.valueOf(iNext_ASO_Id) ;
                                quote.CONTAINER_ASO_ID__c = String.valueOf(iNext_ASO_Id);
                            }
                            
                            quote.CONTAINER_Status__c = 'ASO Released';
                            quote.CONTAINER_QuotePath__c = 'ASO Released';
                            
                            
                            system.debug('-------updated record-----------');
                            system.debug('Previous ASO_ID ='+ quote.CONTAINER_NT_Previous_ASO_ID__c);
                            system.debug('ASO ID ='+quote.CONTAINER_ASO_ID__c);
                        }
                        
                        
                    }else If (quote.CONTAINER_ASO_ID__c <> null && quote.CONTAINER_ASO_Rev__c == null){
                        quote.CONTAINER_NT_RevNumber__c = 0;
                        quote.CONTAINER_ASO_Rev__c = mapQuoteRevNumbertoName.get(Integer.valueOf(quote.CONTAINER_NT_RevNumber__c));
                        quote.CONTAINER_Revision_Date__c = system.today();
                        system.debug('-------updated 1st Revision record-----------');
                        system.debug('GENSET RevNumber ='+quote.CONTAINER_NT_RevNumber__c);
                        system.debug('ASO REV = '+ quote.CONTAINER_ASO_Rev__c);
                    }else If (quote.CONTAINER_ASO_ID__c <> null && quote.CONTAINER_ASO_Rev__c <> null){
                        quote.CONTAINER_Revision_Date__c = system.today();
                        quote.CONTAINER_NT_RevNumber__c = quote.CONTAINER_NT_RevNumber__c +1;
                        quote.CONTAINER_ASO_Rev__c = mapQuoteRevNumbertoName.get(Integer.valueOf(quote.CONTAINER_NT_RevNumber__c));
                        system.debug('-------updated Revision record-----------');
                        system.debug('GENSET RevNumber ='+quote.CONTAINER_NT_RevNumber__c);
                        system.debug('ASO REV = '+ quote.CONTAINER_ASO_Rev__c);
                    }
                    quote.CONTAINER_IsRevised__c=TRUE;
                    lstQuote.add(quote);
                }     
            }
            
            if(lstQuote != null && lstQuote.size() > 0){
                update lstQuote ;
            }
        }
    }    
}