NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/NATT_Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>NATT Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/Shipment_Schedule__c/Shipment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Shipment Schedule</label>
    <nameField>
        <displayFormat>SS-{0000}</displayFormat>
        <label>Shipment Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/Shipment_Schedule__c/fields/CONTAINER_Destination__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Destination__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>NATT_Address__c.NATT_Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.CONTAINER_Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>NATT_Address__c.NATT_Type__c</field>
            <operation>equals</operation>
            <value>Ship To</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>NATT_Address__c</referenceTo>
    <relationshipLabel>Shipment Schedules</relationshipLabel>
    <relationshipName>Shipment_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment_Schedule__c/fields/CONTAINER_Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Quote_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Number</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Shipment Schedules</relationshipLabel>
    <relationshipName>Shipment_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment_Schedule__c/fields/CONTAINER_WeekOf__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_WeekOf__c</fullName>
    <label>Week Of</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/ContainerQuoteRelatedShipmentRecords.cls
/********************************************************************************************************
* @author         Deloitte
* @description    An ContainerQuoteRelatedShipmentRecords class is created for Fetching the Shipment_Schedule records for given Quote Number.
* @date           07/12/2022 [MM/DD/YYYY]
* 
* Modification Log:
* -------------------------------------------------------------------------------------------------------
* Developer                Date                   Modification ID      Description
* -------------------------------------------------------------------------------------------------------
* Deloitte               07/12/2022                                   Initial version
*********************************************************************************************************/

public Inherited Sharing class ContainerQuoteRelatedShipmentRecords {
    public Id quoteId {get;set;}
   	public List<Shipment_Schedule__c> getShipmentRecords() {
        // return null or empty list if the source quote Id is null
        if(String.isEmpty(quoteId)) {
            return null;
        }
        try {
            List<Shipment_Schedule__c> shipmentRecords = [SELECT CONTAINER_Qty__c, CONTAINER_WeekOf__c, CONTAINER_Destination__c, CONTAINER_Destination__r.Name FROM Shipment_Schedule__c
                where CONTAINER_Quote_Number__c=:quoteId WITH SECURITY_ENFORCED];
                 // Return list if there are records, or else return null or empty list
                if(!shipmentRecords.isEmpty()) {
                    return shipmentRecords;
                } 
                else {
                    return null;
                }
        }
    	catch(QueryException ex) {
            return null;
    	}
    }
}