NATTQA-ENV/force-app/main/default/objects/AccountContactRelation/fields/NATT_External_ID__c.field-meta.xml
<CustomField>
    <fullName>NATT_External_ID__c</fullName>
    <formula>IF(
AND(
Account.NATT_Record_Type_Developer_Name__c = &apos;Dealer&apos;,
Contact.NATT_Record_Type_Developer_Name__c = &apos;NATT_Dealer&apos;
),  Account.NATT_Customer_Number__c+&apos;-&apos;+ Contact.NATT_Contact_Number__c , &apos;&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Contact Relation</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/AccountContactRelation/fields/NATT_isMigrated__c.field-meta.xml
<CustomField>
    <fullName>NATT_isMigrated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To check if it is migrated to destination.
Updated via SyncACRBatchCallout batch class</description>
    <label>Is Migrated</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/ACR_Batch__c/ACR_Batch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ACR Batch</label>
</CustomObject>

NATTQA-ENV/force-app/main/default/classes/SyncACRBatchCalloutTest.cls
/****
Created by LTI
Test class for SyncACRBatchCallout
****/

@isTest
public class SyncACRBatchCalloutTest {
    
    
    private static testmethod void testBacth(){
        
        ACR_Batch__c cs = new ACR_Batch__c();
        cs.Name = 'LastRun';
        cs.Last_run__c = Datetime.now().addMinutes(-360);
        insert cs;
        
        
        Account acc = NATT_DataFactory.accRecord();
        insert acc;
        
        Contact con = NATT_DataFactory.conRecord(acc.ID);
        insert con;
        
        List<AccountContactRelation> acrLst = [Select ID, NATT_External_ID__c
                                               from AccountContactRelation 
                                               WHERE accountID =: acc.ID
                                               AND contactID =: con.ID];
        System.assertEquals(1, acrLst.size());
        
        Test.startTest();
        
        SyncACRBatchCallout batch = new SyncACRBatchCallout();
        DataBase.executeBatch(batch); 
        
        Database.BatchableContext str;
        
        batch.execute(str, acrLst);
        
        Test.stopTest();
        
        //assertion check
        AccountContactRelation acrCheckObj = [Select id, NATT_isMigrated__c
                                              From AccountContactRelation
                                              Where id =: acrLst[0].ID];
        
        System.assertEquals(acrCheckObj.NATT_isMigrated__c, True);
    }
}