NATTQA-ENV/force-app/main/default/objects/HBI_Leads_Mapping_By_Org__mdt/HBI_Leads_Mapping_By_Org__mdt.object-meta.xml
<CustomObject>
    <label>HBI Leads Mapping By Org</label>
    <pluralLabel>HBI Leads Mapping By Org</pluralLabel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/HBI_Leads_Mapping_By_Org__mdt/fields/Lead_Reason_Field__c.field-meta.xml
<CustomField>
    <fullName>Lead_Reason_Field__c</fullName>
    <label>Lead Reason Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/HBI_Leads_Mapping_By_Org__mdt/fields/Opportunity_Reason_Field__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Reason_Field__c</fullName>
    <label>Opportunity Reason Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/HBI_Leads_Mapping_By_Org__mdt/fields/Status_Accepted__c.field-meta.xml
<CustomField>
    <fullName>Status_Accepted__c</fullName>
    <defaultValue>&quot;Accepted&quot;</defaultValue>
    <label>Status Accepted</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/HBI_Leads_Mapping_By_Org__mdt/fields/Status_Customer_Contacted__c.field-meta.xml
<CustomField>
    <fullName>Status_Customer_Contacted__c</fullName>
    <defaultValue>&quot;Contacted&quot;</defaultValue>
    <label>Status Customer Contacted</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/HBI_Leads_Mapping_By_Org__mdt/fields/Status_Lost__c.field-meta.xml
<CustomField>
    <fullName>Status_Lost__c</fullName>
    <label>Status Lost</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/HBI_Leads_Mapping_By_Org__mdt/fields/Status_Rejected__c.field-meta.xml
<CustomField>
    <fullName>Status_Rejected__c</fullName>
    <defaultValue>&quot;Unqualified&quot;</defaultValue>
    <label>Status Rejected</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/HBI_Leads_Mapping_By_Org__mdt/fields/Status_Won__c.field-meta.xml
<CustomField>
    <fullName>Status_Won__c</fullName>
    <label>Status Won</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/HBI_Leads_Mapping_By_Receiving_Business__mdt/HBI_Leads_Mapping_By_Receiving_Business__mdt.object-meta.xml
<CustomObject>
    <label>HBI Leads Mapping By Receiving Business</label>
    <pluralLabel>HBI Leads Mapping By Receiving Business</pluralLabel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/HBI_Leads_Mapping_By_Receiving_Business__mdt/fields/Org_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Org_Record_Type__c</fullName>
    <label>Org Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Integration__c/Integration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Integration Settings</description>
    <label>Integration</label>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/Integration__c/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <label>Timeout</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/Contact_Details__c.field-meta.xml
<CustomField>
    <fullName>Contact_Details__c</fullName>
    <inlineHelpText>Does this contact makes decisions for the Products identified in the SPIF and for the products associated with the lead receiving business?</inlineHelpText>
    <label>Contact Details</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/Customer_Budget__c.field-meta.xml
<CustomField>
    <fullName>Customer_Budget__c</fullName>
    <inlineHelpText>Does the Customer have budget to proceed?</inlineHelpText>
    <label>Customer Budget</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/Customer_Details__c.field-meta.xml
<CustomField>
    <fullName>Customer_Details__c</fullName>
    <inlineHelpText>Is the customer a building owner or design build contractor or other?</inlineHelpText>
    <label>Customer Details</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Building Owner</fullName>
            </value>
            <value>
                <fullName>Design Build Contractor</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/Customer_Discussion_Date__c.field-meta.xml
<CustomField>
    <fullName>Customer_Discussion_Date__c</fullName>
    <label>Customer Discussion Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/Customer_Interest__c.field-meta.xml
<CustomField>
    <fullName>Customer_Interest__c</fullName>
    <inlineHelpText>During your initial discussions what products/solutions is the customer interested in as it relates to &apos;Healthy building&apos; and/or what is the challenge or opportunity they are trying to solve?</inlineHelpText>
    <label>Customer Interest</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/Errors_on_Sending_Record__c.field-meta.xml
<CustomField>
    <fullName>Errors_on_Sending_Record__c</fullName>
    <label>Errors on Sending Record</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/Estimated_Payout__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Payout__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Estimated Payout</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/HBI_Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>HBI_Lead_Status__c</fullName>
    <label>HBI Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Customer Contacted</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Won Booked</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/Lead_Owner_Email__c.field-meta.xml
<CustomField>
    <fullName>Lead_Owner_Email__c</fullName>
    <label>Lead Owner Email</label>
    <type>Email</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/Lead_Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Owner_Name__c</fullName>
    <label>Lead Owner Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/Opportunity_Owner_Email__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Owner_Email__c</fullName>
    <label>Opportunity Owner Email</label>
    <type>Email</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/Opportunity_Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Owner_Name__c</fullName>
    <label>Opportunity Owner Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/Opportunity_Pipeline_Value_Est__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Pipeline_Value_Est__c</fullName>
    <label>Opportunity Pipeline Value(Est.)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/Opportunity_Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Reference_Id__c</fullName>
    <label>Opportunity Reference Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/Opportunity_Value_Won_Act__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Value_Won_Act__c</fullName>
    <label>Opportunity Value Won(Act.)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/Receiving_Business__c.field-meta.xml
<CustomField>
    <fullName>Receiving_Business__c</fullName>
    <label>Receiving Business</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sending_Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FSP Global Access - LENEL S2</fullName>
            </value>
            <value>
                <fullName>FSP Global Access - ONITY</fullName>
            </value>
            <value>
                <fullName>NORESCO</fullName>
            </value>
            <value>
                <fullName>Commercial HVAC Equipment</fullName>
            </value>
            <value>
                <fullName>Commercial HVAC Service</fullName>
            </value>
            <value>
                <fullName>HVAC Controls</fullName>
            </value>
            <value>
                <fullName>BSG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/Record_Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Reference_Id__c</fullName>
    <label>Record Reference Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/Sender_Email__c.field-meta.xml
<CustomField>
    <fullName>Sender_Email__c</fullName>
    <label>Sender Email</label>
    <type>Email</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Sender_Name__c</fullName>
    <label>Sender Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/Sender_Phone__c.field-meta.xml
<CustomField>
    <fullName>Sender_Phone__c</fullName>
    <label>Sender Phone</label>
    <type>Phone</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/Sending_Business__c.field-meta.xml
<CustomField>
    <fullName>Sending_Business__c</fullName>
    <label>Sending Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FSP Global Access - LENEL S2</fullName>
            </value>
            <value>
                <fullName>FSP Global Access - ONITY</fullName>
            </value>
            <value>
                <fullName>NORESCO</fullName>
            </value>
            <value>
                <fullName>Commercial HVAC Equipment</fullName>
                <isActive>false</isActive>
                <label>Commercial HVAC Equipment</label>
            </value>
            <value>
                <fullName>Commercial HVAC Service</fullName>
                <isActive>false</isActive>
                <label>Commercial HVAC Service</label>
            </value>
            <value>
                <fullName>HVAC Controls</fullName>
                <isActive>false</isActive>
                <label>HVAC Controls</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/Solutions_Interested__c.field-meta.xml
<CustomField>
    <fullName>Solutions_Interested__c</fullName>
    <label>Solutions Interested</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Receiving_Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Filtration Technology(Hepa Filters/UV lights/Aglon)</fullName>
            </value>
            <value>
                <fullName>OptiClean(TM) Negative Air Machine</fullName>
            </value>
            <value>
                <fullName>ActivAir(TM)</fullName>
            </value>
            <value>
                <fullName>Environmental Index</fullName>
            </value>
            <value>
                <fullName>DirectKey(TM) mobile access solution</fullName>
            </value>
            <value>
                <fullName>BlueDiamond(TM) touchless access</fullName>
            </value>
            <value>
                <fullName>MyWay(TM)</fullName>
            </value>
            <value>
                <fullName>Safe Start Service</fullName>
            </value>
            <value>
                <fullName>Indoor Air Quality Assessment</fullName>
            </value>
            <value>
                <fullName>Remote Airside Management</fullName>
            </value>
            <value>
                <fullName>Wellness Services</fullName>
            </value>
            <value>
                <fullName>Remote Energy Management</fullName>
            </value>
            <value>
                <fullName>Emergency Assets</fullName>
            </value>
            <value>
                <fullName>Advanced Access Services</fullName>
            </value>
            <value>
                <fullName>Security Assessment &amp; Upgrade Services</fullName>
            </value>
            <value>
                <fullName>ActivAir HHT air terminal</fullName>
            </value>
            <value>
                <fullName>Advanced airside system</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Reason__c</fullName>
    <label>Status Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/LeadController.cls
/*
@name: LeadController
@description: This class is used for Lead object
@date: 08 Aug 2020
@author: LTI
@changes:
*/
global class LeadController {
    
    //constants
    public static final String BLANK = '';
    public static final String SPACE = ' ';
    public static final String COMMA = ',';
    public static final String NAMED_CREDENTIAL = 'NAMED_CREDENTIAL';
    public static final String INTEGRATION_SENDLEAD = 'SendLead';
    public static final String INTEGRATION_QUERYEXTDATA = 'QueryExternalData';
    public static final String ERROR_START = 'Error: ';
    public static final String RESPONSE_NULL = 'No Response Received';
    public static final String STATUS_NEW = 'New';
    public static final String STATUS_ACCEPTED = 'Accepted';
    public static final String STATUS_REJECTED = 'Rejected';
    public static final String STATUS_CONTACTED = 'Customer Contacted';
    public static final String STATUS_CONVERTED = 'Qualified';
    public static final String STATUS_OPP_WON = 'Won Booked';
    public static final String STATUS_Opp_LOST = 'Lost';
    public static final String CONTENT_TYPE = 'Content-Type';
    public static final String UTF_8 = 'UTF-8';
    public static final String STATUSREASON_BLANK = 'No Reason Specified';
    
    /*
    @name: createLead
    @description: This method is used by createLeadLWC to insert Lead records
    @date: 08 Aug 2020
    @author: LTI
    @changes:
    */
    @AuraEnabled
    global static String createLead(Lead objLeadRec){
        String strToReturn = BLANK;
        String errors = ERROR_START;
        try{
            Database.SaveResult saveRes = Database.insert(objLeadRec);
            if(saveRes.isSuccess()){
                sendandUpdateLead(objLeadRec.Id);
                strToReturn = objLeadRec.Id;
            }else{
                for(Database.Error objErr : saveRes.getErrors()) {
                    errors = errors + objErr.getMessage() + SPACE;
                }
                strToReturn = errors;
            }
        }catch(Exception ex){
            system.debug('Exception on line : '+ex.getLineNumber()+' Exception '+ex.getMessage());
            strToReturn = errors +ex.getMessage();
        }
        return strToReturn;
    }
    
    /*
    @name: sendandUpdateLead
    @description: This future method is used to send Lead record to respective orgs and store ext lead id or error in lead record
    @date: 08 Aug 2020
    @author: LTI
    @changes:
    */
    @future(callout=true)
    public static void sendandUpdateLead(String leadId){
        try{
            String sourceLeadId = BLANK;
            String errorOnLeadCreation = BLANK;
            String extRecordTypeName = BLANK;
            String extRecordTypeId = BLANK;
            String namedCred = BLANK;
            
            Lead leadRec = [SELECT Id, Sender_Name__c, Sender_Email__c, Sender_Phone__c, Sending_Business__c, Receiving_Business__c, Customer_Discussion_Date__c, LastName, FirstName, Salutation, MiddleName, Suffix, Name, Title, Company, Street, City, State, PostalCode, Country, Phone, MobilePhone, Email, Website, Status, LeadSource, Industry , Customer_Details__c, Contact_Details__c, Customer_Interest__c, Customer_Budget__c, Solutions_Interested__c FROM Lead where Id=:leadId];
            for(HBI_Leads_Mapping_By_Receiving_Business__mdt objMdt : [SELECT Id, Named_Credential__c, Industry__c, Org_Record_Type__c FROM HBI_Leads_Mapping_By_Receiving_Business__mdt WHERE MasterLabel = :leadRec.Receiving_Business__c Order By Industry__c]){
                if(String.isBlank(objMdt.Industry__c)){
                    extRecordTypeName = objMdt.Org_Record_Type__c;
                    namedCred = objMdt.Named_Credential__c;
                }else if(String.isNotBlank(objMdt.Industry__c) && leadRec.Industry == objMdt.Industry__c){
                    extRecordTypeName = objMdt.Org_Record_Type__c;
                    namedCred = objMdt.Named_Credential__c;
                }
            }
            
            if(String.isNotBlank(extRecordTypeName) && String.isNotBlank(namedCred)){
            	String queryToGetRecordType = 'SELECT Id, Name FROM RecordType where sObjectType=\'Lead\' AND Name=\''+extRecordTypeName+'\'';
                String respBody = calloutToQueryExtData(namedCred,queryToGetRecordType);
                if(String.isNotBlank(respBody)){
                    RecordTypeResp objResp = (RecordTypeResp) JSON.deserialize(respBody, RecordTypeResp.class);
                    List<RecordTypeWrap> objRecType = objResp.records;
                    for(RecordTypeWrap obj : objRecType){
                        extRecordTypeId = obj.Id;
                    }
                }
            }
            
            //update lead with ref id or error
            if(String.isNotBlank(extRecordTypeId)){
                String strBody = getExtLeadBody(extRecordTypeId,leadRec);
                ExtLeadWrap extLead = calloutToSendLead(namedCred, strBody);
                Lead objLead = new Lead(Id = leadId);
                if(String.isNotBlank(extLead.Id)){
                    objLead.Record_Reference_Id__c = extLead.Id;
                    objLead.HBI_Lead_Status__c = STATUS_NEW;
                }
                if(String.isNotBlank(extLead.Error)){
                    objLead.Errors_on_Sending_Record__c = extLead.Error;
                }
                Database.update(objLead); 
            }            
        }catch(Exception ex){
            system.debug('Exception on line : '+ex.getLineNumber()+' Exception '+ex.getMessage());
        }
    }
    
    /*
    @name: processDataFromAllOrgs
    @description: This method is called from HBILeadsBatch it get data from ext lead and updates lead records
    @date: 08 Aug 2020
    @author: LTI
    @changes:
    */
    public static void processDataFromAllOrgs(List<Lead> lstLead){
        
        List<Lead> lstLeadToUpdate = new List<Lead>();
        Map<String, List<Lead>> mapOfLeadByOrg = new Map<String, List<Lead>>();
        Set<String> setOfRecBusiness = new Set<String>();
        Map<String,String> mapOrgByRecBusiness = new Map<String,String>();
        Set<String> setOfOrgs = new Set<String>();
        Map<String,HBI_Leads_Mapping_By_Org__mdt> mapOfMdtByOrg = new Map<String,HBI_Leads_Mapping_By_Org__mdt>();

        for(Lead objLead : lstLead){
            setOfRecBusiness.add(objLead.Receiving_Business__c);
        }
        if(!setOfRecBusiness.isEmpty()){
            for(HBI_Leads_Mapping_By_Receiving_Business__mdt obj : [SELECT MasterLabel, Named_Credential__c FROM HBI_Leads_Mapping_By_Receiving_Business__mdt WHERE MasterLabel IN :setOfRecBusiness AND Industry__c = :BLANK]){
                mapOrgByRecBusiness.put(obj.MasterLabel,obj.Named_Credential__c);
                setOfOrgs.add(obj.Named_Credential__c);
            }
        }
        
        for(Lead objLead :lstLead){
            String receivingOrg = BLANK;
            if(!mapOrgByRecBusiness.isEmpty() && mapOrgByRecBusiness.containsKey(objLead.Receiving_Business__c)){
                receivingOrg = mapOrgByRecBusiness.get(objLead.Receiving_Business__c);
            }
            if(String.isNotBlank(receivingOrg)){
                if(mapOfLeadByOrg.containsKey(receivingOrg)){
                    mapOfLeadByOrg.get(receivingOrg).add(objLead);
                }else{
                    mapOfLeadByOrg.put(receivingOrg ,new List<Lead>{objLead});
                }
            }
        }
        
        if(!setOfOrgs.isEmpty()){
            for(HBI_Leads_Mapping_By_Org__mdt objMdt : [SELECT MasterLabel, Lead_Reason_Field__c, Opportunity_Reason_Field__c, Status_Accepted__c, Status_Customer_Contacted__c, Status_Rejected__c, Status_Won__c, Status_Lost__c FROM HBI_Leads_Mapping_By_Org__mdt WHERE Masterlabel IN :setOfOrgs ]){
                mapOfMdtByOrg.put(objMdt.MasterLabel,objMdt);
            }
        }
        
        Map<Id,OpportunityWrap> mapOfExtOppByExtOppId = new Map<Id,OpportunityWrap>();
        Map<Id,LeadWrap> mapOfExtLeadByLeadId = new Map<Id,LeadWrap>();
        
        for(String receivingOrg : mapOfLeadByOrg.keySet()){
            if(mapOfLeadByOrg.get(receivingOrg) != null && !mapOfLeadByOrg.get(receivingOrg).isEmpty()){
                String leadReasonField = BLANK;
                String oppReasonField = BLANK;
                if(!mapOfMdtByOrg.isEmpty() && mapOfMdtByOrg.containsKey(receivingOrg)){
                    if(String.isNotBlank(mapOfMdtByOrg.get(receivingOrg).Lead_Reason_Field__c)){
                        leadReasonField = mapOfMdtByOrg.get(receivingOrg).Lead_Reason_Field__c;
                    }
                    if(String.isNotBlank(mapOfMdtByOrg.get(receivingOrg).Opportunity_Reason_Field__c)){
                        oppReasonField = mapOfMdtByOrg.get(receivingOrg).Opportunity_Reason_Field__c;
                    }
                }
                
                String strExtLeadIds = '('; 
                String strFailedLeadIds = '('; 
                for(Lead objLead : mapOfLeadByOrg.get(receivingOrg)){
                    if(String.isNotBlank(objLead.Record_Reference_Id__c)){
                        strExtLeadIds = strExtLeadIds +'\''+ objLead.Record_Reference_Id__c + '\',';
                    }else{
                        strFailedLeadIds = strFailedLeadIds + '\''+ objLead.Id + '\',';
                    }
                }
                strExtLeadIds = strExtLeadIds.removeEnd(',');
                strExtLeadIds = strExtLeadIds + ')';
                strFailedLeadIds = strFailedLeadIds.removeEnd(',');
                strFailedLeadIds = strFailedLeadIds + ')';
                
                String queryToGetLeadRecs = 'SELECT Id, HBI_HQ_Lead_Id__c, Owner.Name, Owner.Email, IsConverted, Status, ConvertedOpportunityId FROM Lead WHERE LeadSource=\'Healthy Buildings - SPIFF\'';
                if(String.isNotBlank(leadReasonField)){
                    queryToGetLeadRecs = 'SELECT Id, HBI_HQ_Lead_Id__c, Owner.Name, Owner.Email, '+leadReasonField+', IsConverted, Status, ConvertedOpportunityId FROM Lead WHERE LeadSource=\'Healthy Buildings - SPIFF\'';
                }
                if(strExtLeadIds != '()' && strFailedLeadIds!='()'){
                    queryToGetLeadRecs = queryToGetLeadRecs + ' AND (Id IN'+strExtLeadIds+' OR HBI_HQ_Lead_Id__c IN'+strFailedLeadIds+')';
                }else if(strExtLeadIds != '()' && strFailedLeadIds=='()'){
                    queryToGetLeadRecs = queryToGetLeadRecs + ' AND Id IN'+strExtLeadIds;
                }else if(strExtLeadIds == '()' && strFailedLeadIds!='()'){
                    queryToGetLeadRecs = queryToGetLeadRecs + ' AND HBI_HQ_Lead_Id__c IN'+strFailedLeadIds;
                }
                List<String> convOppIds = new List<String>();
                String respLeadBody = calloutToQueryExtData(receivingOrg,queryToGetLeadRecs);
                if(String.isNotBlank(respLeadBody)){
                    if(String.isNotBlank(leadReasonField)){
                        respLeadBody = respLeadBody.replaceAll(leadReasonField, 'StatusReason');
                    }
                    respLeadBody = respLeadBody.replaceAll('HBI_HQ_Lead_Id__c', 'LeadReferenceId');
                    
                    LeadResp objLeadResp = (LeadResp) JSON.deserialize(respLeadBody, LeadResp.class);
                    for(LeadWrap obj : objLeadResp.records){
                        mapOfExtLeadByLeadId.put(obj.LeadReferenceId,obj);
                        if(obj.ConvertedOpportunityId !=null){
                            convOppIds.add(obj.ConvertedOpportunityId);
                        }
                    }
                }
                if(!convOppIds.isEmpty()){
                    String oppIds = '(';
                    for(String oid : convOppIds){
                        oppIds = oppIds +'\''+ oid + '\',';
                    }
                    oppIds = oppIds.removeEnd(',');
                    oppIds = oppIds + ')';
                    String queryToGetOppRecs = BLANK;
                    if(String.isBlank(oppReasonField)){
                        queryToGetOppRecs = 'SELECT Id, Amount, StageName, isWon, isClosed, Owner.Name, Owner.Email FROM Opportunity WHERE Id IN '+oppIds;
                    }else{
                        queryToGetOppRecs = 'SELECT Id, Amount, StageName, isWon, isClosed, Owner.Name, Owner.Email,'+oppReasonField+' FROM Opportunity WHERE Id IN '+oppIds;
                    }
                    String respOppBody = calloutToQueryExtData(receivingOrg,queryToGetOppRecs);
                    if(String.isNotBlank(respOppBody)){
                        if(String.isNotBlank(oppReasonField)){
                            respLeadBody = respLeadBody.replaceAll(oppReasonField, 'StageReason');
                        }
                        OpportunityResp opptyResp = (OpportunityResp) JSON.deserialize(respOppBody, OpportunityResp.class);
                        for(OpportunityWrap opp : opptyResp.records){
                            mapOfExtOppByExtoppId.put(opp.Id, opp);
                        }
                    }
                }
            }
        }
        system.debug('mapOfExtOppByExtOppId'+mapOfExtOppByExtOppId.size());
        system.debug('mapOfExtLeadByLeadId'+mapOfExtLeadByLeadId.size());
        
        //update lead status from external Leads
        if(!mapOfExtLeadByLeadId.isEmpty()){
            for(Lead objLead :lstLead){
                if(mapOfExtLeadByLeadId.containsKey(objLead.Id)){
                    LeadWrap objextLead = mapOfExtLeadByLeadId.get(objLead.Id);
                    Lead objLeadToUpdate = new Lead(Id = objLead.Id);
                    HBI_Leads_Mapping_By_Org__mdt objMdt;
                    if(!mapOrgByRecBusiness.isEmpty() && mapOrgByRecBusiness.containsKey(objLead.Receiving_Business__c) && !mapOfMdtByOrg.isEmpty() && mapOfMdtByOrg.containsKey(mapOrgByRecBusiness.get(objLead.Receiving_Business__c))){
                    	objMdt = mapOfMdtByOrg.get(mapOrgByRecBusiness.get(objLead.Receiving_Business__c));
                    }
                    if(String.isBlank(objLead.Record_Reference_Id__c)){
                        objLeadToUpdate.Record_Reference_Id__c = objextLead.Id;
                        objLeadToUpdate.HBI_Lead_Status__c = STATUS_NEW;
                    }
                    if(objExtLead.Owner != null){
                        objLeadToUpdate.Lead_Owner_Name__c = objExtLead.Owner.Name;
                        objLeadToUpdate.Lead_Owner_Email__c = objExtLead.Owner.Email;
                    }
                    if(objExtLead.IsConverted){
                        objLeadToUpdate.HBI_Lead_Status__c = STATUS_CONVERTED;
                        objLeadToUpdate.Opportunity_Reference_Id__c = objExtLead.ConvertedOpportunityId;
              
                        if(mapOfExtOppByExtoppId!=null && objExtLead.ConvertedOpportunityId!=null && mapOfExtOppByExtoppId.containsKey(objExtLead.ConvertedOpportunityId)){
                            OpportunityWrap objExtOpp = mapOfExtOppByExtoppId.get(objExtLead.ConvertedOpportunityId);
                            if(objExtOpp.Amount !=null && !objExtOpp.IsWon){
                                objLeadToUpdate.Opportunity_Pipeline_Value_Est__c = objExtOpp.Amount;
                            }
                            if(objExtOpp.Owner != null){
                                objLeadToUpdate.Opportunity_Owner_Name__c = objExtOpp.Owner.Name;
                                objLeadToUpdate.Opportunity_Owner_Email__c = objExtOpp.Owner.Email;
                            }
                            if(objMdt!=null){
                                if(objMdt.Status_Won__c.split(COMMA).contains(objExtLead.Status)){
                                    objLeadToUpdate.HBI_Lead_Status__c = STATUS_OPP_WON;
                                    objLeadToUpdate.Estimated_Payout__c = 500;
                                    objLeadToUpdate.Opportunity_Value_Won_Act__c = objExtOpp.Amount;
                                }else if(objMdt.Status_Lost__c.split(COMMA).contains(objExtLead.Status)){
                                    objLeadToUpdate.HBI_Lead_Status__c = STATUS_OPP_LOST;
                                    objLeadToUpdate.Status_Reason__c = String.isNotBlank(objExtOpp.StageReason) ? objExtOpp.StageReason : STATUSREASON_BLANK;
                                }
                            }
                        }
                    }else if(String.isNotBlank(objExtLead.Status)){
                        if(objMdt!=null){
                            if(objMdt.Status_Rejected__c.split(COMMA).contains(objExtLead.Status)){
                                objLeadToUpdate.HBI_Lead_Status__c = STATUS_REJECTED;
                                objLeadToUpdate.Status_Reason__c = String.isNotBlank(objExtLead.StatusReason) ? objExtLead.StatusReason : STATUSREASON_BLANK;
                            }else if(objMdt.Status_Customer_Contacted__c.split(COMMA).contains(objExtLead.Status)){
                            	objLeadToUpdate.HBI_Lead_Status__c = STATUS_CONTACTED;
                            	objLeadToUpdate.Estimated_Payout__c = 100;
                            }else if(objMdt.Status_Accepted__c.split(COMMA).contains(objExtLead.Status)){
                            	objLeadToUpdate.HBI_Lead_Status__c = STATUS_ACCEPTED;
                            }
                        }
                    }
                    lstLeadToUpdate.add(objLeadToUpdate);
                }
            }
        }
        if(lstLeadToUpdate!=null && !lstLeadToUpdate.isEmpty()){
            Database.update(lstLeadToUpdate);
        }
    }
    
    /*
    @name: calloutToQueryExtData
    @description: This method takes named credential name and query to get data from external org
    @date: 08 Aug 2020
    @author: LTI
    @changes:
    */
    public static String calloutToQueryExtData(String namedCred, String strQuery){
        String responseBody = BLANK;
        try{
                Integration__c csQueryExtData = Integration__c.getValues(INTEGRATION_QUERYEXTDATA);
            String strEndpoint = csQueryExtData.Endpoint__c;
            strEndpoint = strEndpoint.replace(NAMED_CREDENTIAL,namedCred);
            String strMethod = csQueryExtData.Method__c;
            Integer intTimeOut = Integer.valueOf(csQueryExtData.Timeout__c);
            String strHeaderContentType = csQueryExtData.Content_Type__c;

            String strEnQuery = EncodingUtil.urlEncode(strQuery,UTF_8);
            String strCompleteEndpoint =  strEndpoint + strEnQuery;
            
            HTTPResponse response = getCalloutResponse(strCompleteEndpoint, strMethod, intTimeOut, null, null);
            if(response!=null && response.getStatusCode() == 200){
                responseBody = response.getBody();
            }else{
                if(response!=null){
                    system.debug(ERROR_START + response.getBody());
                }else{
                    system.debug(ERROR_START + RESPONSE_NULL);
                }
            }
            
        }catch(Exception ex){
            system.debug('Exception on line : '+ex.getLineNumber()+' Exception '+ex.getMessage());
        }
        return responseBody;
    }
    
    /*
    @name: calloutToSendLead
    @description: This method takes named credential name and json body to send lead to external org
    @date: 08 Aug 2020
    @author: LTI
    @changes:
    */
    public static ExtLeadWrap calloutToSendLead(String namedCred, String strBody){
        ExtLeadWrap extLead = new ExtLeadWrap();
        try{
            Integration__c csSendLead = Integration__c.getValues(INTEGRATION_SENDLEAD);
            String strMethod = csSendLead.Method__c;
            Integer intTimeOut = Integer.valueOf(csSendLead.Timeout__c);
            String strHeaderContentType = csSendLead.Content_Type__c;
            String strEndpoint = csSendLead.Endpoint__c;
            strEndpoint = strEndpoint.replace(NAMED_CREDENTIAL, namedCred);
            
            HTTPResponse response = getCalloutResponse(strEndpoint, strMethod, intTimeOut, strBody, strHeaderContentType);            
            if(response!=null && Response.getStatusCode() == 201){
                SendLead_Response objResp = (SendLead_Response)JSON.deserialize(response.getBody(), SendLead_Response.class);
                if(objResp.success){
                    extLead.Id = objResp.id;
                }else{
                    extLead.Error = Response.getBody();
                }
            }else if(response!=null){
                extLead.Error = Response.getBody();
            }else{
                extLead.Error = RESPONSE_NULL;
            }
        }catch(Exception ex){
            system.debug('Exception on line : '+ex.getLineNumber()+' Exception '+ex.getMessage());
        }
        return extLead;
    }
    
    /*
    @name: getCalloutResponse
    @description: This method does callout and returns response
    @date: 08 Aug 2020
    @author: LTI
    @changes:
    */
    public static HTTPResponse getCalloutResponse(String strEndpoint, String strMethod, Integer intTimeOut, String strBody, String strHeaderContentType){
        HTTPResponse response = null;
        try{
            HttpRequest request = new HttpRequest();
            if(String.isNotBlank(strEndpoint)){
                request.setEndpoint(strEndpoint);
            }
            if(String.isNotBlank(strMethod)){
                request.setMethod(strMethod);
            }
            if(intTimeOut!=null){
                request.setTimeout(intTimeOut);
            }
            if(String.isNotBlank(strHeaderContentType)){
                request.setHeader(CONTENT_TYPE, strHeaderContentType);
            }
            if(String.isNotBlank(strBody)){
                request.setBody(strBody);
            }
            Http http = new Http();
            response = http.send(request);
            system.debug('Request: '+request);
        	system.debug('Response: '+response);
        }catch(Exception ex){
            system.debug('Exception on line : '+ex.getLineNumber()+' Exception '+ex.getMessage());
        }
        return response;
    }
    
    /*
    @name: getExtLeadBody
    @description: This method creates external Lead record as Json
    @date: 08 Aug 2020
    @author: LTI
    @changes:
    */
    public static String getExtLeadBody(String extRecTypeId, Lead leadRec){
        String jsonLead = '';
        try{
            jsonLead = '{';
            if(String.isNotBlank(extRecTypeId)){
                jsonLead = jsonLead + '"RecordTypeId" : "'+extRecTypeId+'",';
            }
            if(String.isNotBlank(leadRec.Id)){
                jsonLead = jsonLead + '"HBI_HQ_Lead_Id__c" : "'+leadRec.Id+'",';
            }    
            if(String.isNotBlank(leadRec.Sender_Name__c)){
                jsonLead = jsonLead + '"Sender_Name__c" : "'+leadRec.Sender_Name__c+'",';
            }
            if(String.isNotBlank(leadRec.Sender_Email__c)){
                jsonLead = jsonLead + '"Sender_Email__c" : "'+leadRec.Sender_Email__c+'",';
            }
            if(String.isNotBlank(leadRec.Sender_Phone__c)){
                jsonLead = jsonLead + '"Sender_Phone__c" : "'+leadRec.Sender_Phone__c+'",';
            }
            if(String.isNotBlank(leadRec.Sending_Business__c)){
                jsonLead = jsonLead + '"Sending_Business__c" : "'+leadRec.Sending_Business__c+'",';
            }
            if(String.isNotBlank(leadRec.Receiving_Business__c)){
                jsonLead = jsonLead + '"Receiving_Business__c" : "'+leadRec.Receiving_Business__c+'",';
            }
            if(leadRec.Customer_Discussion_Date__c != null){
                String month = String.valueOf(leadRec.Customer_Discussion_Date__c.month()).leftPad(2, '0');
                String year = String.valueOf(leadRec.Customer_Discussion_Date__c.year());  
                String day = String.valueOf(leadRec.Customer_Discussion_Date__c.day()).leftPad(2, '0');
                String dateFormat = year+'-'+month+'-'+day;
                jsonLead = jsonLead + '"Customer_Discussion_Date__c" : "'+dateFormat+'",';
            }
            if(String.isNotBlank(leadRec.Company)){
                jsonLead = jsonLead + '"Company" : "'+leadRec.Company+'",'; 
            }
            if(String.isNotBlank(leadRec.Street)){
                jsonLead = jsonLead + '"Street" : "'+ leadRec.Street+'",';
            }
            if(String.isNotBlank(leadRec.Country)){
                jsonLead = jsonLead + '"Country" : "'+leadRec.Country+'",';
            }
            if(String.isNotBlank(leadRec.City)){
                jsonLead = jsonLead + '"City" : "'+leadRec.City+'",';
            }
            if(String.isNotBlank(leadRec.State)){
                jsonLead = jsonLead + '"State" : "'+leadRec.State+'",';
            }
            if(String.isNotBlank(leadRec.PostalCode)){
                jsonLead = jsonLead + '"PostalCode" : "'+leadRec.PostalCode+'",';
            }
            if(String.isNotBlank(leadRec.Industry)){
                jsonLead = jsonLead + '"Industry" : "'+leadRec.Industry+'",';
            }
            if(String.isNotBlank(leadRec.FirstName)){
                jsonLead = jsonLead + '"FirstName" : "'+leadRec.FirstName+'",';
            }
            if(String.isNotBlank(leadRec.LastName)){
                jsonLead = jsonLead + '"LastName" : "'+leadRec.LastName+'",';
            }
            if(String.isNotBlank(leadRec.Title)){
                jsonLead = jsonLead + '"Title" : "'+leadRec.Title+'",';
                if(leadRec.Receiving_Business__c == 'BSG' ||
                   leadRec.Receiving_Business__c == 'Commercial HVAC Equipment' ||
                   leadRec.Receiving_Business__c == 'Commercial HVAC Service' ||
                   leadRec.Receiving_Business__c == 'HVAC Controls'){
                    if(!leadRec.Title.contains('Other')){
                        jsonLead = jsonLead + '"Role__c" : "'+leadRec.Title+'",';
                    }else{
                        jsonLead = jsonLead + '"Role__c" : "Other",';
                    }
                }
            }
            if(String.isNotBlank(leadRec.Email)){
                jsonLead = jsonLead + '"Email" : "'+leadRec.Email+'",';
            }
            if(String.isNotBlank(leadRec.Phone)){
                jsonLead = jsonLead + '"Phone" : "'+leadRec.Phone+'",';
            }
            if(String.isNotBlank(leadRec.Customer_Details__c)){
                jsonLead = jsonLead + '"Customer_Details__c" : "'+leadRec.Customer_Details__c+'",';
            }
            if(String.isNotBlank(leadRec.Contact_Details__c)){
                jsonLead = jsonLead + '"Contact_Details__c" : "'+leadRec.Contact_Details__c+'",';
            }
            if(String.isNotBlank(leadRec.Customer_Interest__c)){
                jsonLead = jsonLead + '"Customer_Interest__c" : "'+leadRec.Customer_Interest__c+'",';
            }
            if(String.isNotBlank(leadRec.Customer_Budget__c)){
                jsonLead = jsonLead + '"Customer_Budget__c" : "'+leadRec.Customer_Budget__c+'",';
            }
            if(String.isNotBlank(leadRec.Solutions_Interested__c)){
                jsonLead = jsonLead + '"Solutions_Interested__c" : "'+leadRec.Solutions_Interested__c+'",';
            }
            if(String.isNotBlank(leadRec.LeadSource)){
                jsonLead = jsonLead + '"LeadSource" : "'+leadRec.LeadSource+'"';
            }
            jsonLead = jsonLead + '}';
        }catch(Exception ex){
            system.debug('Exception on line : '+ex.getLineNumber()+' Exception '+ex.getMessage());
        }
        return jsonLead;
    }
      
    //wrapper class
    public class SendLead_Response{
        public String id;
        public Boolean success;
    }
    public class RecordTypeResp{
        public Integer totalSize;	
        public boolean done;
        public RecordTypeWrap[] records; 
    }
    public class RecordTypeWrap{
        public String Name;
        public String Id;
    }
    public class ExtLeadWrap{
        public String Id;
        public String Error;
    }
    public class LeadResp{
        public Integer totalsize;
        public Boolean done;
        public List<LeadWrap> records;
    }
    public class LeadWrap{
        public String Id;
        public Boolean IsConverted;
        public String Status;
        public String StatusReason;
        public String ConvertedOpportunityId;
        public String LeadReferenceId;
        public OwnerWrap Owner;
    }
    public class OpportunityResp{
        public Integer totalSize;	
        public boolean done;
        public OpportunityWrap[] records; 
    }
    public class OpportunityWrap {
        public String Id;	
        public Decimal Amount;
        public String StageName;
        public String StageReason;
        public Boolean IsWon;
        public Boolean IsClosed;
        public OwnerWrap Owner;
    }
    public class OwnerWrap{
        public String Name;
        public String Email;
    }
}