NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_P_N__c</fullName>
    <description>The Part Number for NATT JDE</description>
    <label>Part Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__ProductFeature__c/SBQQ__ProductFeature__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__ProductFeatureHelp</customHelpPage>
    <description>Feature of a configurable product that consists of one or more options. Features are configured by selecting one or more options.</description>
    <label>Product Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__ProductFeature__c/fields/SBQQ__Category__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Category__c</fullName>
    <description>Category of options in this feature. Allows for another level of grouping.</description>
    <inlineHelpText>Assign this feature to a category such that multiple features with related options are grouped together.</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CHINA</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>FRANCIA</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Truck Selection</fullName>
            </value>
            <value>
                <fullName>Unit Selection</fullName>
            </value>
            <value>
                <fullName>Evaporator Selection</fullName>
            </value>
            <value>
                <fullName>Accessories Selection</fullName>
                <label>Options</label>
            </value>
            <value>
                <fullName>Recorder &amp; Telematics</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>KITS</fullName>
            </value>
            <value>
                <fullName>Related Options</fullName>
            </value>
            <value>
                <fullName>Standard Sales Options</fullName>
            </value>
            <value>
                <fullName>Non-Standard Sales Options</fullName>
            </value>
            <value>
                <fullName>Special Options</fullName>
            </value>
            <value>
                <fullName>BluEdge</fullName>
            </value>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>Enhanced</fullName>
            </value>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Chiquita UG Option package</fullName>
            </value>
            <value>
                <fullName>Matson UG Option package</fullName>
            </value>
            <value>
                <fullName>No Category</fullName>
            </value>
            <value>
                <fullName>Atmosphere</fullName>
            </value>
            <value>
                <fullName>Controls</fullName>
            </value>
            <value>
                <fullName>Refrigeration</fullName>
            </value>
            <value>
                <fullName>Electrical</fullName>
            </value>
            <value>
                <fullName>TELEMATICS</fullName>
            </value>
            <value>
                <fullName>Convenience Features</fullName>
            </value>
            <value>
                <fullName>Unit Info</fullName>
            </value>
            <value>
                <fullName>Warranty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__ProductFeature__c/fields/SBQQ__ConfiguredSKU__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ConfiguredSKU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product bundle that includes this feature. If you created the feature from the product detail page, this should already be populated.</description>
    <inlineHelpText>The product bundle that includes this feature. If you created the feature from the product detail page, this should already be populated.</inlineHelpText>
    <label>Configured SKU</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Features</relationshipLabel>
    <relationshipName>Features</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__ProductOption__c/SBQQ__ProductOption__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__ProductOptionHelp</customHelpPage>
    <description>Option for a configurable product.</description>
    <label>Product Option</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__ProductOption__c/fields/NATT_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_P_N__c</fullName>
    <description>NATT</description>
    <formula>SBQQ__OptionalSKU__r.NATT_P_N__c</formula>
    <label>P/N</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__ProductOption__c/fields/SBQQ__ConfiguredSKU__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ConfiguredSKU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product SKU of the bundle that is being configured with this option. If you create the option from the product detail page, this should already be populated.</description>
    <inlineHelpText>Product SKU of the bundle that is being configured with this option. If you create the option from the product detail page, this should already be populated.</inlineHelpText>
    <label>Configured SKU</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Options</relationshipLabel>
    <relationshipName>Options</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__ProductOption__c/fields/SBQQ__Feature__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Feature that selects this option.</description>
    <inlineHelpText>Enter or lookup the feature that includes this option. This will be dependent on the Configured SKU.</inlineHelpText>
    <label>Feature</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.SBQQ__ConfiguredSKU__c</field>
            <operation>equals</operation>
            <valueField>SBQQ__ProductFeature__c.SBQQ__ConfiguredSKU__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SBQQ__ProductFeature__c</referenceTo>
    <relationshipLabel>Product Options</relationshipLabel>
    <relationshipName>ProductOptions</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__ProductOption__c/fields/SBQQ__Number__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Number__c</fullName>
    <description>Sequential number that determines this option&apos;s sort order.</description>
    <inlineHelpText>Set the display order of this option within the feature it&apos;s assigned to.</inlineHelpText>
    <label>Number</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__ProductOption__c/fields/SBQQ__OptionalSKU__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__OptionalSKU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product SKU added if this option is selected.</description>
    <inlineHelpText>Enter or lookup the product SKU that should be added when this product is selected.</inlineHelpText>
    <label>Optional SKU</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Optional For</relationshipLabel>
    <relationshipName>OptionalFor</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_ASO_ID__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_ASO_ID__c</fullName>
    <label>ASO ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_P_N__c</fullName>
    <description>for NATT quotes</description>
    <label>P/N</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__ProductOption__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ProductOption__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product option that generated this line (if any).</description>
    <inlineHelpText>Product option that generated this line (if any).</inlineHelpText>
    <label>Product Option</label>
    <referenceTo>SBQQ__ProductOption__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/CONTAINER_Quote_ASO_QL_Warranty_Test.cls
@isTest
public class CONTAINER_Quote_ASO_QL_Warranty_Test {
    @testSetup 
    static void setup() {
        
        // This code runs as the system user
        Profile prof = [SELECT Id FROM Profile WHERE Name='CONTAINER Administrator'];
        User newUser = new User(Alias = 'contAdm', Email='contAdmin@carrier.com', LastName='AdminTest', ProfileId = prof.Id, 
                                UserName='testAdminUser@carrier.com', EmailEncodingKey='UTF-8', 
                                LanguageLocaleKey='en_US', LocaleSidKey='en_US', TimeZoneSidKey='America/Los_Angeles');
        insert newUser;       
        
    }
    @isTest
    public static void WarrantyTest1(){
        User containerAdmin = [select id from user where Alias = 'contAdm' limit 1];
        CONTAINER_UtilityClass.createCustomerQuote();        
        
        Test.startTest();
        system.runAs(containerAdmin){
            List<SBQQ__Quote__c> quoteID = [SELECT Id from SBQQ__Quote__c where CONTAINER_ASO_ID__c ='3415'];
            List<SBQQ__QuoteLine__c> qtLine = [SELECT Id, NATT_P_N__c, SBQQ__Quote__c, SBQQ__Product__c from SBQQ__QuoteLine__c where SBQQ__Quote__c =: quoteID[0].Id];
            List<Product2> productId = [SELECT Id, productCode from Product2 where productCode ='SJ PD 1'];
            
            SBQQ__ProductFeature__c objPF = new SBQQ__ProductFeature__c();
            objPF.Name = 'Test Feature';
            objPF.SBQQ__ConfiguredSKU__c = productId[0].Id;
            objPF.SBQQ__Number__c = 2;
            objPF.SBQQ__MinOptionCount__c = 1;
            objPF.SBQQ__Category__c = 'Warranty';
            insert objPF;
            
            SBQQ__ProductOption__c objPopt = new SBQQ__ProductOption__c();
            objPopt.SBQQ__Number__c = 2;
            objPopt.SBQQ__ConfiguredSKU__c = productId[0].Id;
            objPopt.SBQQ__Feature__c = objPF.Id;
            objPopt.SBQQ__OptionalSKU__c = productId[0].Id;
            insert objPopt;        
            
            qtLine[0].SBQQ__ProductOption__c = objPopt.Id;
            update qtLine[0];
            
            ContainerQuote_ASO_QL_Warranty objASOQL = new ContainerQuote_ASO_QL_Warranty();
            objASOQL.quoteId = quoteID[0].Id;
            objASOQL.getwarrantyRecords();
            
            system.assert(quoteID.size()>0 , 'Checking Quote Size');
            Test.stopTest();
        }
        
    }
    
    @isTest
    public static void WarrantyTest2(){
        User containerAdmin = [select id from user where Alias = 'contAdm' limit 1];
        CONTAINER_UtilityClass.createCustomerQuote();
        Test.startTest();
        system.runAs(containerAdmin){
            List<SBQQ__Quote__c> quoteID = [select Id from SBQQ__Quote__c where CONTAINER_ASO_ID__c ='3415'];
            ContainerQuote_ASO_QL_Warranty objASOQL = new ContainerQuote_ASO_QL_Warranty();
            objASOQL.getwarrantyRecords();
            
            objASOQL.quoteId = quoteID[0].Id;
            objASOQL.getwarrantyRecords();
            
            
            system.assert(quoteID.size()>0 , 'Checking Quote Size');
            Test.stopTest();
        }
    }
}