NATTQA-ENV/force-app/main/default/objects/User/fields/CTBR_Dealer__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Dealer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CTBR Dealer</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/User/fields/CTBR_Internal__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Internal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CTBR Internal</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/User/fields/CTM_Dealer_Region_1__c.field-meta.xml
<CustomField>
    <fullName>CTM_Dealer_Region_1__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CTM Dealer Region 1 - Mexico</description>
    <label>CTM Dealer Region 1</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/User/fields/CTM_Dealer_Region_2__c.field-meta.xml
<CustomField>
    <fullName>CTM_Dealer_Region_2__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CTM Dealer Region 2 - Central America and Caribbean</description>
    <label>CTM Dealer Region 2</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/User/fields/CTM_Dealer_Region_3__c.field-meta.xml
<CustomField>
    <fullName>CTM_Dealer_Region_3__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CTM Dealer Region 3 - South America</description>
    <label>CTM Dealer Region 3</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/User/fields/CTM_Internal__c.field-meta.xml
<CustomField>
    <fullName>CTM_Internal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Assign to CTM Internal</description>
    <label>CTM Internal</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/User/fields/NATT_Associate__c.field-meta.xml
<CustomField>
    <fullName>NATT_Associate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT</description>
    <label>Associate</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/User/fields/NATT_Customer__c.field-meta.xml
<CustomField>
    <fullName>NATT_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT</description>
    <label>Customer</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/User/fields/NATT_Dealer__c.field-meta.xml
<CustomField>
    <fullName>NATT_Dealer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT</description>
    <label>Dealer</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/User/fields/NATT_Dealer_Principal__c.field-meta.xml
<CustomField>
    <fullName>NATT_Dealer_Principal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT</description>
    <label>Dealer Principal</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/User/fields/NATT_Internal__c.field-meta.xml
<CustomField>
    <fullName>NATT_Internal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT</description>
    <label>Internal</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/UserTriggerHandlerNattTest.cls
@IsTest
private class UserTriggerHandlerNattTest {
    @isTest static void handlePermissions(){
		Profile profileId = [SELECT Id FROM Profile WHERE Name = 'NATT Dealer Master User' LIMIT 1];
        
     	User usr = new User(LastName = 'User',
                           FirstName='Test',
                           Alias = 'txyz123',
                           Email = 'test@testxyz123.com',
                           Username = 'kn@testxyz123.com',
                           ProfileId = profileId.id,
                           TimeZoneSidKey = 'America/New_York',
                           LanguageLocaleKey = 'en_US',
                           EmailEncodingKey = 'UTF-8',
                           LocaleSidKey = 'en_US',
                           NATT_Dealer__c=true,
                           CTM_Dealer_Region_2__c=true,
                           CTBR_Dealer__c=true
                           );        
        insert usr;
        
        usr.NATT_Associate__c=true;
        usr.NATT_Dealer__c=false;
        usr.CTM_Dealer_Region_1__c=true;
        usr.CTBR_Internal__c=true;
        usr.NATT_Customer__c=true;
        usr.NATT_Dealer_Principal__c=true;
        usr.NATT_Internal__c=true;
        usr.CTM_Internal__c=true;
        usr.CTM_Dealer_Region_3__c=true;
        
        update usr;
    }
}