NATTQA-ENV/force-app/main/default/objects/Salesforce_API_Logs__c/Salesforce_API_Logs__c.object-meta.xml
<CustomObject>
    <description>Object to log Integration Errors.</description>
    <label>Salesforce API Logs</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Salesforce API Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/Salesforce_API_Logs__c/fields/CTBR_ClassName__c.field-meta.xml
<CustomField>
    <fullName>CTBR_ClassName__c</fullName>
    <label>ClassName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Salesforce_API_Logs__c/fields/CTBR_Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Exception_Message__c</fullName>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Salesforce_API_Logs__c/fields/CTBR_Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Exception_Type__c</fullName>
    <label>Exception Type</label>
    <type>TextArea</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Salesforce_API_Logs__c/fields/CTBR_Line_Number__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Line_Number__c</fullName>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Salesforce_API_Logs__c/fields/CTBR_MethodName__c.field-meta.xml
<CustomField>
    <fullName>CTBR_MethodName__c</fullName>
    <label>MethodName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Salesforce_API_Logs__c/fields/CTBR_Request_From_Salesforce__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Request_From_Salesforce__c</fullName>
    <description>To log Salesforce Request</description>
    <label>Request From Salesforce</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Salesforce_API_Logs__c/fields/CTBR_Request_Time__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Request_Time__c</fullName>
    <description>Log time of the Request</description>
    <label>Request Time</label>
    <type>DateTime</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Salesforce_API_Logs__c/fields/CTBR_Response_From_SAP__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Response_From_SAP__c</fullName>
    <description>Log Response from SAP.</description>
    <label>Response From SAP</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Salesforce_API_Logs__c/fields/CTBR_Response_Time__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Response_Time__c</fullName>
    <description>Log the time of the Response</description>
    <label>Response Time</label>
    <type>DateTime</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Salesforce_API_Logs__c/fields/CTBR_StackTrace__c.field-meta.xml
<CustomField>
    <fullName>CTBR_StackTrace__c</fullName>
    <label>StackTrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/ctbrUtility.cls
/*Author: LTI
* Created Date: 4th October 2022
* Class Name: ctbrUtility
* Description: This class is used to store common methods 
*/
public class ctbrUtility {
    public static void LogException(Exception ex,String ClassName,String MethodName) {
        
        Salesforce_API_Logs__c log = new Salesforce_API_Logs__c();
        log.CTBR_ClassName__c=ClassName; 
        log.CTBR_MethodName__c=MethodName; 
        log.CTBR_StackTrace__c=ex.getStackTraceString(); 
        log.CTBR_Exception_Type__c=ex.getTypeName();
        log.CTBR_Exception_Message__c=ex.getMessage(); 
        log.CTBR_Line_Number__c=ex.getLineNumber(); 
        
        insert log; 
    }
    
    
    //this method is used to log all api transaction from SAP
   /*
    public static void logAPI(HttpResponse response, String requestBody,Datetime requestTime) {
        
        Salesforce_API_Logs__c log = new Salesforce_API_Logs__c();
        log.CTBR_Request_From_Salesforce__c = requestBody;
        log.CTBR_Request_Time__c = requestTime;
        log.CTBR_Response_Time__c = System.now();
        
        if(response.getStatusCode() == 200){
            log.CTBR_Response_From_SAP__c = response.getBody();
        }else{
            log.CTBR_Response_From_SAP__c = 'API Callout Error with status code '+ response.getStatusCode()+' and Status '+ response.getStatus()+response.getBody(); 
        }
        
        insert log;
    }*/
    
}