NATTQA-ENV/force-app/main/default/objects/BuyerGroup/fields/NAC_Type__c.field-meta.xml
<CustomField>
    <fullName>NAC_Type__c</fullName>
    <description>This field shall store the values for Buyer Group type for example V1H
V1K
C3
C5
C7
C11</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>V1H</fullName>
            </value>
            <value>
                <fullName>V1K</fullName>
            </value>
            <value>
                <fullName>C3</fullName>
            </value>
            <value>
                <fullName>C5</fullName>
            </value>
            <value>
                <fullName>C7</fullName>
            </value>
            <value>
                <fullName>C11</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_AlternativeItem__c/NATT_AlternativeItem__c.object-meta.xml
<CustomObject>
    <description>Custom object for storing alternative item entries (e.g. items that supersede other catalog items)</description>
    <label>NATT Alternative Item</label>
    <nameField>
        <displayFormat>NAI-{00000000}</displayFormat>
        <label>NATT Alternative Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NATT Alternative Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_AlternativeItem__c/fields/NATT_AlternativeItem__c.field-meta.xml
<CustomField>
    <fullName>NATT_AlternativeItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Item that is being provided as an alternative to the Product Item</description>
    <inlineHelpText>Item that is being provided as an alternative to the Product Item</inlineHelpText>
    <label>Alternative Item</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>NATT Alternative Items (Alternative Item)</relationshipLabel>
    <relationshipName>NATT_Alternative_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_AlternativeItem__c/fields/NATT_EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_EffectiveDate__c</fullName>
    <description>Date the alternative item effectively supersedes the product item</description>
    <inlineHelpText>Date the alternative item effectively supersedes the product item</inlineHelpText>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_AlternativeItem__c/fields/NATT_ProductItem__c.field-meta.xml
<CustomField>
    <fullName>NATT_ProductItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Item that is being superseded by the item shown in the Alternative Item field</description>
    <inlineHelpText>Item that is being superseded by the item shown in the Alternative Item field</inlineHelpText>
    <label>Product Item</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>NATT Alternative Items</relationshipLabel>
    <relationshipName>NATT_Alternative_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/recordTypes/NAC.recordType-meta.xml
<RecordType>
    <fullName>NAC</fullName>
    <active>true</active>
    <description>Record type created for NAC Orders</description>
    <label>NAC</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/PricebookEntry/fields/NATT_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>NATT_Effective_Date__c</fullName>
    <description>Indicates the date this pricebook entry was effective. The field supports the PPG B2B Commerce implementation, and provides information necessary to generate price change reports.</description>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NAC_Country_of_Origin_COO__c.field-meta.xml
<CustomField>
    <fullName>NAC_Country_of_Origin_COO__c</fullName>
    <label>Country of Origin (COO)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NAC_HTSUS__c.field-meta.xml
<CustomField>
    <fullName>NAC_HTSUS__c</fullName>
    <label>HTSUS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NAC_Line_Of_Business__c.field-meta.xml
<CustomField>
    <fullName>NAC_Line_Of_Business__c</fullName>
    <description>Line of business formula based on Item price Group</description>
    <formula>CASE( NATT_ItemPriceGroup__c , 
&quot;111&quot;,&quot;A&quot;,&quot;120&quot;,&quot;G&quot;,&quot;123&quot;,&quot;A&quot;,&quot;128&quot;,&quot;G&quot;,&quot;300&quot;,&quot;C&quot;,&quot;301&quot;,&quot;C&quot;,&quot;302&quot;,&quot;C&quot;,&quot;306&quot;,&quot;C&quot;,&quot;310&quot;,&quot;C&quot;,&quot;317&quot;,&quot;C&quot;,&quot;320&quot;,&quot;C&quot;,&quot;500&quot;,&quot;G&quot;,&quot;510&quot;,&quot;G&quot;,&quot;517&quot;,&quot;G&quot;,&quot;600&quot;,&quot;G&quot;,&quot;601&quot;,&quot;G&quot;,&quot;602&quot;,&quot;G&quot;,&quot;603&quot;,&quot;G&quot;,&quot;604&quot;,&quot;G&quot;,&quot;610&quot;,&quot;G&quot;,&quot;611&quot;,&quot;G&quot;,&quot;612&quot;,&quot;G&quot;,&quot;Unknown&quot;)</formula>
    <label>Line Of Business</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NAC_Stocking_Type_UTC__c.field-meta.xml
<CustomField>
    <fullName>NAC_Stocking_Type_UTC__c</fullName>
    <label>NAOCAP Stocking Type (UTC) ATL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>O</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NAOCAP_Not_Orderable__c.field-meta.xml
<CustomField>
    <fullName>NAOCAP_Not_Orderable__c</fullName>
    <description>Field to check the orderability of the product</description>
    <formula>if(NATT_Core__c==true,true,if((NATT_Sales_Code__c==&apos;S01&apos;|| NATT_Sales_Code__c==&apos;SB1&apos;),if (ISPICKVAL( NATT_SignalCode__c, &quot;NLO&quot;),if (ISPICKVAL( NAC_Stocking_Type_UTC__c,&quot;O&quot;),true,false),ISPICKVAL( NATT_SignalCode__c, &quot;S2&quot;) || ISPICKVAL( NATT_SignalCode__c, &quot;PRC&quot;) || ISPICKVAL( NATT_SignalCode__c, &quot;FIN&quot;) || ISPICKVAL( NATT_SignalCode__c, &quot;BY2&quot;)),true))</formula>
    <label>NAOCAP Not Orderable ATL</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Branch_Plant_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>NATT_Branch_Plant_Warehouse__c</fullName>
    <description>NATT</description>
    <label>Branch Plant/Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TT Units items 3706000000</fullName>
            </value>
            <value>
                <fullName>PPG 3712910000</fullName>
            </value>
            <value>
                <fullName>BNA</fullName>
            </value>
            <value>
                <fullName>ANA</fullName>
            </value>
            <value>
                <fullName>PAN</fullName>
            </value>
            <value>
                <fullName>CHI</fullName>
            </value>
            <value>
                <fullName>TES</fullName>
            </value>
            <value>
                <fullName>CTB01</fullName>
            </value>
            <value>
                <fullName>CTB02</fullName>
            </value>
            <value>
                <fullName>ATL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_CoreItem_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_CoreItem_P_N__c</fullName>
    <description>Text field containing the part number of the core item. Core items are not stored in the product catalog.</description>
    <label>Core Item P/N</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_CorePrice__c.field-meta.xml
<CustomField>
    <fullName>NATT_CorePrice__c</fullName>
    <description>Price (credit) value of the core item</description>
    <label>Core Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Discount_Code__c.field-meta.xml
<CustomField>
    <fullName>NATT_Discount_Code__c</fullName>
    <formula>CASE( NATT_ItemPriceGroup__c , 
$CustomMetadata.Discount_Code__mdt.Price_Group_110.Item_Price_Group__c, 
					$CustomMetadata.Discount_Code__mdt.Price_Group_110.Discount_Code_Value__c,
$CustomMetadata.Discount_Code__mdt.Price_Group_111.Item_Price_Group__c, 
					$CustomMetadata.Discount_Code__mdt.Price_Group_111.Discount_Code_Value__c,
$CustomMetadata.Discount_Code__mdt.Price_Group_112.Item_Price_Group__c, 
					$CustomMetadata.Discount_Code__mdt.Price_Group_112.Discount_Code_Value__c,
$CustomMetadata.Discount_Code__mdt.Price_Group_114.Item_Price_Group__c, 
					$CustomMetadata.Discount_Code__mdt.Price_Group_114.Discount_Code_Value__c,
$CustomMetadata.Discount_Code__mdt.Price_Group_115.Item_Price_Group__c, 
					$CustomMetadata.Discount_Code__mdt.Price_Group_115.Discount_Code_Value__c,
$CustomMetadata.Discount_Code__mdt.Price_Group_116.Item_Price_Group__c, 
					$CustomMetadata.Discount_Code__mdt.Price_Group_116.Discount_Code_Value__c,
$CustomMetadata.Discount_Code__mdt.Price_Group_123.Item_Price_Group__c, 
					$CustomMetadata.Discount_Code__mdt.Price_Group_123.Discount_Code_Value__c,
$CustomMetadata.Discount_Code__mdt.Price_Group_129.Item_Price_Group__c, 
					$CustomMetadata.Discount_Code__mdt.Price_Group_129.Discount_Code_Value__c,
$CustomMetadata.Discount_Code__mdt.Price_Group_223.Item_Price_Group__c, 
					$CustomMetadata.Discount_Code__mdt.Price_Group_223.Discount_Code_Value__c,
$CustomMetadata.Discount_Code__mdt.Price_Group_226.Item_Price_Group__c, 
					$CustomMetadata.Discount_Code__mdt.Price_Group_226.Discount_Code_Value__c,					
&apos;A&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NATT Discount Code</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Height__c.field-meta.xml
<CustomField>
    <fullName>NATT_Height__c</fullName>
    <description>Height of the item in Inches</description>
    <label>Height</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_ItemPriceGroup__c.field-meta.xml
<CustomField>
    <fullName>NATT_ItemPriceGroup__c</fullName>
    <description>A number identifying the price group to which the item belongs</description>
    <label>Item Price Group</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Length__c.field-meta.xml
<CustomField>
    <fullName>NATT_Length__c</fullName>
    <description>Length of the item in Inches</description>
    <label>Length</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_P_N__c</fullName>
    <description>The Part Number for NATT JDE</description>
    <label>Part Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_SignalCode__c.field-meta.xml
<CustomField>
    <fullName>NATT_SignalCode__c</fullName>
    <description>JDE Signal Code for the item</description>
    <label>Signal Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>NLO</fullName>
            </value>
            <value>
                <fullName>NSI</fullName>
            </value>
            <value>
                <fullName>NSU</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S1D</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
            <value>
                <fullName>NRC</fullName>
            </value>
            <value>
                <fullName>BY2</fullName>
                <label>BUYER HOLD</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <label>NOT AVAILABLE</label>
            </value>
            <value>
                <fullName>OB1</fullName>
            </value>
            <value>
                <fullName>OBS</fullName>
            </value>
            <value>
                <fullName>PRC</fullName>
            </value>
            <value>
                <fullName>NEW</fullName>
            </value>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>PSR</fullName>
            </value>
            <value>
                <fullName>VIN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_UOM_Conversion__c.field-meta.xml
<CustomField>
    <fullName>NATT_UOM_Conversion__c</fullName>
    <description>NATT unit of measure conversion factor</description>
    <label>UOM Conversion</label>
    <precision>15</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Weight__c.field-meta.xml
<CustomField>
    <fullName>NATT_Weight__c</fullName>
    <description>Item weight in US pounds</description>
    <label>Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Width__c.field-meta.xml
<CustomField>
    <fullName>NATT_Width__c</fullName>
    <description>Width of the item in Inches</description>
    <label>Width</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/NAC_CatalogPDFController.cls
public without sharing class NAC_CatalogPDFController {
    public Map<Integer, PriceBookWrapper> productData{get;set;}
    
    public NAC_CatalogPDFController(ApexPages.StandardController con) {
        DateTime dT = System.now();
        Set<Id> Product2Id = new Set<Id>();
        WebStoreBuyerGroup storeBuyerGroup;
        productData = new Map<Integer, PriceBookWrapper>();
        List<PricebookEntry> prodData = new List<PricebookEntry>();
        Map<Id, PricebookEntry> ProdDataMap = new Map<Id, PricebookEntry>();
        List<String> externalUserItemCode = Label.NAOCAP_External_User_Item_Code.split(',');
        Map<Id, NATT_AlternativeItem__c> mapOfproductSuperseded = new Map<Id, NATT_AlternativeItem__c>();
        String customerType, myDate = (String.valueOf(date.newinstance(dT.year(), dT.month(), dT.day()))).substring(0,10);
        Set<String> coreItemPNset = new Set<string>(), signalVal = new Set<String>{'A','BY2','FIN','PRC','S1'}, signalValsecond = new Set<String>{'N/A','OBS'}, signValthird = new Set<String>{'NSI','A','BY2','PRC','FIN','S1'}, signValfourth = new Set<String>{'S2','N/A','OBS','NSU'};
            Apexpages.currentPage().getHeaders().put('content-disposition', 'attachment; filename=Container List Price Book'+' '+myDate+'.pdf');
        User userDetail = [SELECT contactid, contact.AccountId, isportalenabled FROM User WHERE Id =: UserInfo.getUserId() LIMIT 1];
        Id containerStoreId = [SELECT id from Webstore WHERE Name =: Label.NAOCAP_Store_Name LIMIT 1]?.Id;
        Boolean hasCustomPermission = FeatureManagement.checkPermission ('UCP_Download_Pricebook_Access');
            list<PermissionSetAssignment> PermissionSetLicenseAssign = [SELECT Id, PermissionSet.Name, AssigneeId from PermissionSetAssignment where  AssigneeId =:UserInfo.getUserId() and (PermissionSet.Name = 'NAOCP_Commerce_Finance' or PermissionSet.Name = 'NAOCP_Commerce_Parts_Ordering') limit 1];
            boolean licenceAssigned = false;
            if(PermissionSetLicenseAssign.size() > 0){
                licenceAssigned = true;
            }
        if(userDetail.isportalenabled  && (!hasCustomPermission || licenceAssigned) ){
            storeBuyerGroup = [SELECT BuyerGroupId, BuyerGroup.NAC_Type__c from WebStoreBuyerGroup WHERE WebStoreId =: containerStoreId AND BuyerGroupId IN (SELECT BuyerGroupId FROM BuyerGroupMember WHERE BuyerId =: userDetail.contact.AccountId) LIMIT 1];
            customerType = storeBuyerGroup.BuyerGroup.NAC_Type__c;
        }
        //For external customers we need to filter products on Item code
        if(userDetail.isportalenabled && (hasCustomPermission || Label.NAOCAP_External_Customer_Group.contains(customerType))){
            //For external customers we need to filter products on Item code
            prodData=[SELECT CurrencyIsoCode,Name,NATT_Effective_Date__c,Pricebook2Id,Product2Id,Product2.id,Product2.NATT_Weight__c,Product2.ProductCode,Product2.NATT_SignalCode__c,
                      Product2.NATT_Height__c,Product2.NATT_Width__c,Product2.NATT_Discount_Code__c,Product2.NAC_Stocking_Type_UTC__c,Product2.NATT_Length__c,Product2.NAC_Country_of_Origin_COO__c,Product2.NAC_HTSUS__c,
                      Product2.NATT_P_N__c,Product2.Name, Product2.NATT_Core__c ,Product2.NATT_UOM_Conversion__c,Product2.NATT_CoreItem_P_N__c,
                      ProductCode,UnitPrice,UseStandardPrice, Product2.NAC_Line_Of_Business__c FROM PricebookEntry WHERE Pricebook2.Name = 'NA Containers Marketplace Strikethrough Price Book' AND Product2.NATT_ItemPriceGroup__c IN:externalUserItemCode];
            
        }else{
            prodData=[SELECT CurrencyIsoCode,Name,NATT_Effective_Date__c,Pricebook2Id,Product2Id,Product2.id,Product2.NATT_Weight__c,Product2.ProductCode,Product2.NATT_SignalCode__c,
                      Product2.NATT_Height__c,Product2.NATT_Width__c,Product2.NATT_Discount_Code__c,Product2.NAC_Stocking_Type_UTC__c,Product2.NATT_Length__c,Product2.NAC_Country_of_Origin_COO__c,Product2.NAC_HTSUS__c,
                      Product2.NATT_P_N__c,Product2.Name, Product2.NATT_Core__c ,Product2.NATT_UOM_Conversion__c,Product2.NATT_CoreItem_P_N__c,
                      ProductCode,UnitPrice,UseStandardPrice, Product2.NAC_Line_Of_Business__c FROM PricebookEntry WHERE Pricebook2.Name = 'NA Containers Marketplace Strikethrough Price Book'];
        }
        
        
        for(PricebookEntry pe:prodData){
            ProdDataMap.put(pe.product2Id,pe);
        } 
        
        for (Integer i = 0; i < prodData.size(); i++){
            Product2Id.add(prodData[i].Product2Id);
        }
        //getting products with core
        List<Product2> prWithCoreItem=new List<Product2>([SELECT Id, Name, NATT_CoreItem_P_N__c,NATT_CorePrice__c,NATT_Branch_Plant_Warehouse__c  FROM Product2 where Id IN:Product2Id AND NATT_CoreItem_P_N__c!=null and NATT_Branch_Plant_Warehouse__c ='ATL' ]);
        
        for(Product2 prod:prWithCoreItem){
            coreItemPNset.add(prod.NATT_CoreItem_P_N__c);
        }
        //getting the details of core with part number as key and storing in the map//
        MAp<String,Product2> mapOfCorePrDetails=new MAp<String,PRoduct2>();
        for(Product2 prIterator:[select id,ProductCode,Name,NATT_P_N__c,NAOCAP_Not_Orderable__c,NATT_CorePrice__c  from product2 where NATT_P_N__c IN :coreItemPNset and NATT_Branch_Plant_Warehouse__c ='ATL' AND recordtype.Name='NAC Products']){
            mapOfCorePrDetails.put(prIterator.NATT_P_N__c, prIterator);
        }
        for(NATT_AlternativeItem__c nAc:[SELECT Id, NATT_AlternativeItem__c,NATT_ProductItem__r.NAC_Stocking_Type_UTC__c, NATT_ProductItem__r.NATT_SignalCode__c , NATT_ProductItem__r.ProductCode,NATT_ProductItem__r.Name,NATT_AlternativeItem__r.Name,
                                         NATT_AlternativeItem__r.ProductCode,NATT_AlternativeItem__r.NATT_CoreItem_P_N__c ,NATT_ALternativeItem__r.NATT_P_N__c,NATT_ProductItem__r.NATT_P_N__c FROM NATT_AlternativeItem__c WHERE 
                                         NATT_ProductItem__c=:Product2Id AND NATT_ProductItem__r.NATT_SignalCode__c='S2' ORDER BY NATT_EffectiveDate__c DESC]){
                                             mapOfproductSuperseded.put(nAc.NATT_ProductItem__c,nAc);
                                         }
        
        for(integer i=0;i<prodData.size();i++){
            PriceBookWrapper pbWrapper = new PriceBookWrapper();
            pbWrapper.Superseded = ' ';
            pbWrapper.PartNumber = ' ';  
            pbWrapper.PKG =0;
            pbWrapper.AlternatePart = '';
            pbWrapper.Weight = 0;
            pbWrapper.Length = 0;
            pbWrapper.core_Reference=' ';
            pbWrapper.lineOfBusiness='';
            pbWrapper.Width = 0;
            pbWrapper.Height = 0;
            pbWrapper.COO = ''; 
            pbWrapper.HTSUS = ''; 
            pbWrapper.SignalCode ='';    
            pbWrapper.Description = prodData[i].Name;
            pbWrapper.Price =0;
            pbWrapper.Each_price =0; 
            //pbWrapper.totalproductPrice=0;
            pbWrapper.coreListPrice='';
            
            if(mapOfproductSuperseded.containsKey(prodData[i].Product2Id)){
                pbWrapper.Superseded = mapOfproductSuperseded.get(prodData[i].Product2Id).NATT_ALternativeItem__r.ProductCode;
            }
            /*Signal Code Updated Logic CXREF- 3820*/
            if(signalVal.contains(prodData[i].Product2.NATT_SignalCode__c))
                pbWrapper.SignalCode ='A';
            if(prodData[i].Product2.NATT_SignalCode__c == 'NLO' && prodData[i].Product2.NAC_Stocking_Type_UTC__c == 'U')
                pbWrapper.SignalCode ='A';
            if(prodData[i].Product2.NATT_SignalCode__c == 'NLO' && prodData[i].Product2.NAC_Stocking_Type_UTC__c == 'O')
                pbWrapper.SignalCode ='NLO';
            if(signalValsecond.contains(prodData[i].Product2.NATT_SignalCode__c))
                pbWrapper.SignalCode ='NLO';
            if(prodData[i].Product2.NATT_SignalCode__c == 'NSI')
                pbWrapper.SignalCode ='NSI';
            if(prodData[i].Product2.NATT_SignalCode__c == 'NSU' || prodData[i].Product2.NATT_SignalCode__c == 'NEW')
                pbWrapper.SignalCode ='NSU';
            
            if(prodData[i].Product2.ProductCode != null){
                pbWrapper.PartNumber = prodData[i].Product2.ProductCode;
            }
            /*packaging*/
            if(prodData[i].Product2.NATT_UOM_Conversion__c != null){
                pbWrapper.PKG=prodData[i].Product2.NATT_UOM_Conversion__c;
            }
            ////superseded
            if(mapOfproductSuperseded.get(prodData[i].Product2Id) != null){
                if(mapOfproductSuperseded.get(prodData[i].Product2Id).NATT_ProductItem__r.NATT_P_N__c != null){
                    
                    pbWrapper.AlternatePart = mapOfproductSuperseded.get(prodData[i].Product2Id).NATT_ALternativeItem__r.NATT_P_N__c;
                }else{
                    pbWrapper.AlternatePart = '';
                }
            }
            /*Pricing */
            if(prodData[i].UnitPrice != null && signValthird.contains(prodData[i].Product2.NATT_SignalCode__c)){
                pbWrapper.Price=prodData[i].UnitPrice;
              if(prodData[i].Product2.NATT_UOM_Conversion__c != null && prodData[i].Product2.NATT_UOM_Conversion__c != 0){
                    Decimal up           =pbWrapper.Price;
                    Decimal UOM          =prodData[i].Product2.NATT_UOM_Conversion__c;
                    pbWrapper.Each_price =up/UOM; 
                }else{
                    pbWrapper.Each_price =pbWrapper.Price;
                }
                //Calculating core item pricing CXREF- 3280//
                if(mapOfCorePrDetails.containsKey(prodData[i].product2.NATT_CoreItem_P_N__c )){
                    if(ProdDataMap.containsKey(mapOfCorePrDetails.get(prodData[i].product2.NATT_CoreItem_P_N__c).id)){
                        if(ProdDataMap.get(mapOfCorePrDetails.get(prodData[i].product2.NATT_CoreItem_P_N__c).id).UnitPrice != null){
                            pbWrapper.totalproductPrice = pbWrapper.Price + ProdDataMap.get(mapOfCorePrDetails.get(prodData[i].product2.NATT_CoreItem_P_N__c).id).UnitPrice;
                            pbWrapper.coreListPrice = String.ValueOf(ProdDataMap.get(mapOfCorePrDetails.get(prodData[i].product2.NATT_CoreItem_P_N__c).id).UnitPrice);
                        }else{
                            pbWrapper.totalproductPrice = pbWrapper.Price;
                            pbWrapper.coreListPrice = '';
                        }
                    }
                    else{
                        pbWrapper.totalproductPrice = pbWrapper.Price;
                        pbWrapper.coreListPrice = '';
                    }
                }else{
                    //pbWrapper.totalproductPrice= pbWrapper.Price;
                    pbWrapper.coreListPrice = '';
                }
            }
            if(prodData[i].UnitPrice != null && prodData[i].Product2.NATT_SignalCode__c == 'NLO' && prodData[i].Product2.NAC_Stocking_Type_UTC__c == 'U'){
                pbWrapper.Price=prodData[i].UnitPrice;
                if(prodData[i].Product2.NATT_UOM_Conversion__c != null && prodData[i].Product2.NATT_UOM_Conversion__c != 0){
                    Decimal up           =pbWrapper.Price;
                    Decimal UOM          =prodData[i].Product2.NATT_UOM_Conversion__c;
                    pbWrapper.Each_price =up/UOM; 
                }else{
                    pbWrapper.Each_price =pbWrapper.Price;
                }
                //Calculating core item pricing CXREF- 3280//
                if(mapOfCorePrDetails.containsKey(prodData[i].product2.NATT_CoreItem_P_N__c )){
                    if(ProdDataMap.containsKey(mapOfCorePrDetails.get(prodData[i].product2.NATT_CoreItem_P_N__c).id)){
                        if(ProdDataMap.get(mapOfCorePrDetails.get(prodData[i].product2.NATT_CoreItem_P_N__c).id).UnitPrice != null){
                            pbWrapper.totalproductPrice = pbWrapper.Price + ProdDataMap.get(mapOfCorePrDetails.get(prodData[i].product2.NATT_CoreItem_P_N__c).id).UnitPrice;
                            pbWrapper.coreListPrice = String.ValueOf(ProdDataMap.get(mapOfCorePrDetails.get(prodData[i].product2.NATT_CoreItem_P_N__c).id).UnitPrice);
                        }else{
                            pbWrapper.totalproductPrice = pbWrapper.Price;
                            pbWrapper.coreListPrice = '';
                        }
                    }
                    else{
                        pbWrapper.totalproductPrice = pbWrapper.Price;
                        pbWrapper.coreListPrice = '';
                    }
                }else{
                    //pbWrapper.totalproductPrice = pbWrapper.Price;
                    pbWrapper.coreListPrice = '';
                }
            }
            if(prodData[i].UnitPrice != null && signValfourth.contains(prodData[i].Product2.NATT_SignalCode__c)){
                pbWrapper.Price=0;
                pbWrapper.Each_price=0;
                //pbWrapper.totalproductPrice = 0;
                pbWrapper.coreListPrice = '';
            }
            if(prodData[i].UnitPrice != null && prodData[i].Product2.NATT_SignalCode__c == 'NLO' && prodData[i].Product2.NAC_Stocking_Type_UTC__c == 'O'){
                pbWrapper.Price=0;
                pbWrapper.Each_price=0;
                //pbWrapper.totalproductPrice = 0;
                pbWrapper.coreListPrice = ' ';
            }
            if(prodData[i].Product2.NATT_CoreItem_P_N__c != null){
                pbWrapper.EXCH_CORE='Exchange';
            }else if(prodData[i].Product2.NATT_Core__c){
                pbWrapper.EXCH_CORE='Core';
            }
            else{
                pbWrapper.EXCH_CORE='';
            }
            
            if(prodData[i].Product2.NATT_Weight__c != null){
                pbWrapper.Weight = prodData[i].Product2.NATT_Weight__c;
            }
            
            if(prodData[i].Product2.NATT_Length__c != null){
                pbWrapper.Length = prodData[i].Product2.NATT_Length__c;
            }
            
            if(prodData[i].Product2.NATT_CoreItem_P_N__c != null){
                pbWrapper.core_Reference=prodData[i].Product2.NATT_CoreItem_P_N__c;
            }
            
            if(prodData[i].Product2.NAC_Line_Of_Business__c !=null){
                pbWrapper.lineOfBusiness=prodData[i].Product2.NAC_Line_Of_Business__c;
            }
            
            if(prodData[i].Product2.NATT_Width__c != null){
                pbWrapper.Width = prodData[i].Product2.NATT_Width__c;
            }            
            if(prodData[i].Product2.NATT_Height__c != null){
                pbWrapper.Height = prodData[i].Product2.NATT_Height__c;
            }
            
            if(prodData[i].Product2.NAC_Country_of_Origin_COO__c != null){
                pbWrapper.COO = prodData[i].Product2.NAC_Country_of_Origin_COO__c;
            }
            if(prodData[i].Product2.NAC_HTSUS__c != null){
                pbWrapper.HTSUS = prodData[i].Product2.NAC_HTSUS__c;
            }
            
            productData.put(i,pbWrapper);
        }
    }
    
    public class PriceBookWrapper{
        @AuraEnabled public String PartNumber{get;set;}
        @AuraEnabled public string Description{get;set;}
        @AuraEnabled public Decimal PKG{get;set;}
        @AuraEnabled public String AlternatePart{get;set;}
        @AuraEnabled public Decimal Price{get;set;}
        @AuraEnabled public String EXCH_CORE{get;set;}
        @AuraEnabled public String SignalCode{get;set;}
        @AuraEnabled public String Superseded{get;set;}
        @AuraEnabled public Double Each_price{get;set;}
        @AuraEnabled public String core_Reference{get;set;}
        @AuraEnabled public Decimal Weight{get;set;}
        @AuraEnabled public Decimal Length{get;set;}
        @AuraEnabled public Decimal Width{get;set;}
        @AuraEnabled public Decimal Height{get;set;}
        @AuraEnabled public String COO{get;set;}
        @AuraEnabled public String HTSUS{get;set;}
        @AuraEnabled public String lineOfBusiness{get;set;}
        @AuraEnabled public string coreListPrice {get;set;}
        @AuraEnabled public Decimal totalproductPrice {get;set;}
    }
}