NATTQA-ENV/force-app/main/default/objects/PricebookEntry/fields/NATT_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>NATT_Effective_Date__c</fullName>
    <description>Indicates the date this pricebook entry was effective. The field supports the PPG B2B Commerce implementation, and provides information necessary to generate price change reports.</description>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NAC_Country_of_Origin_COO__c.field-meta.xml
<CustomField>
    <fullName>NAC_Country_of_Origin_COO__c</fullName>
    <label>Country of Origin (COO)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NAC_HTSUS__c.field-meta.xml
<CustomField>
    <fullName>NAC_HTSUS__c</fullName>
    <label>HTSUS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NAC_Stocking_Type_UTC__c.field-meta.xml
<CustomField>
    <fullName>NAC_Stocking_Type_UTC__c</fullName>
    <label>NAOCAP Stocking Type (UTC) ATL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>O</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Branch_Plant_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>NATT_Branch_Plant_Warehouse__c</fullName>
    <description>NATT</description>
    <label>Branch Plant/Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TT Units items 3706000000</fullName>
            </value>
            <value>
                <fullName>PPG 3712910000</fullName>
            </value>
            <value>
                <fullName>BNA</fullName>
            </value>
            <value>
                <fullName>ANA</fullName>
            </value>
            <value>
                <fullName>PAN</fullName>
            </value>
            <value>
                <fullName>CHI</fullName>
            </value>
            <value>
                <fullName>TES</fullName>
            </value>
            <value>
                <fullName>CTB01</fullName>
            </value>
            <value>
                <fullName>CTB02</fullName>
            </value>
            <value>
                <fullName>ATL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_CoreItem_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_CoreItem_P_N__c</fullName>
    <description>Text field containing the part number of the core item. Core items are not stored in the product catalog.</description>
    <label>Core Item P/N</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Height__c.field-meta.xml
<CustomField>
    <fullName>NATT_Height__c</fullName>
    <description>Height of the item in Inches</description>
    <label>Height</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_ItemPriceGroup__c.field-meta.xml
<CustomField>
    <fullName>NATT_ItemPriceGroup__c</fullName>
    <description>A number identifying the price group to which the item belongs</description>
    <label>Item Price Group</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Length__c.field-meta.xml
<CustomField>
    <fullName>NATT_Length__c</fullName>
    <description>Length of the item in Inches</description>
    <label>Length</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_P_N__c</fullName>
    <description>The Part Number for NATT JDE</description>
    <label>Part Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_SignalCode__c.field-meta.xml
<CustomField>
    <fullName>NATT_SignalCode__c</fullName>
    <description>JDE Signal Code for the item</description>
    <label>Signal Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>NLO</fullName>
            </value>
            <value>
                <fullName>NSI</fullName>
            </value>
            <value>
                <fullName>NSU</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S1D</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
            <value>
                <fullName>NRC</fullName>
            </value>
            <value>
                <fullName>BY2</fullName>
                <label>BUYER HOLD</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <label>NOT AVAILABLE</label>
            </value>
            <value>
                <fullName>OB1</fullName>
            </value>
            <value>
                <fullName>OBS</fullName>
            </value>
            <value>
                <fullName>PRC</fullName>
            </value>
            <value>
                <fullName>NEW</fullName>
            </value>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>PSR</fullName>
            </value>
            <value>
                <fullName>VIN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_UOM_Conversion__c.field-meta.xml
<CustomField>
    <fullName>NATT_UOM_Conversion__c</fullName>
    <description>NATT unit of measure conversion factor</description>
    <label>UOM Conversion</label>
    <precision>15</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Weight__c.field-meta.xml
<CustomField>
    <fullName>NATT_Weight__c</fullName>
    <description>Item weight in US pounds</description>
    <label>Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/recordTypes/NAC_Products.recordType-meta.xml
<RecordType>
    <fullName>NAC_Products</fullName>
    <active>true</active>
    <description>Record type created for NAC business</description>
    <label>NAC Products</label>
</RecordType>

NATTQA-ENV/force-app/main/default/classes/NAC_CatalogPDFControllerTest.cls
@isTest
public class NAC_CatalogPDFControllerTest {
    
    @isTest
    static void createTest(){
        
        Id prodRecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByDeveloperName().get('NAC_Products').getRecordTypeId();
        
        List<Id> product2ATLIdList = new List<Id>();
        Map<Id, Decimal> product2PriceMap = new Map<Id, Decimal>(), allProduct2PriceMap = new Map<Id, Decimal>();
        List<Product2> product2List = NAC_TestDataFactory.createProductList(52);
        for(integer i = 0; i < product2List.size(); i++){
            product2List[i].RecordTypeId = prodRecordTypeId;
            Product2List[i].NAC_Stocking_Type_UTC__c = 'U';
            product2List[i].NATT_ItemPriceGroup__c = '510';
            product2List[i].NATT_Branch_Plant_Warehouse__c = 'ATL';
            product2List[i].ProductCode = 'TEST-' + String.valueOf(i);
            product2List[i].NATT_P_N__c = 'TEST-' + String.valueOf(i);
            product2List[i].NATT_UOM_Conversion__c = 5;
            switch on Math.Mod(i, 14) {
                when 0 {
                    product2List[i].NATT_SignalCode__c = 'A';
                }when 1 {
                    product2List[i].NATT_SignalCode__c = 'NLO';
                }when 2 {
                    product2List[i].NATT_SignalCode__c = 'NSI';
                }when 3 {
                    product2List[i].NATT_SignalCode__c = 'NSU';
                }when 4 {
                    product2List[i].NATT_SignalCode__c = 'S1';
                }when 5 {
                    product2List[i].NATT_SignalCode__c = 'S2';
                    product2List[i].NATT_CoreItem_P_N__c = 'TEST-' + String.valueOf(i - 1);
                }when 6 {
                    product2List[i].NATT_SignalCode__c = 'NRC';
                }when 7 {
                    product2List[i].NATT_SignalCode__c = 'BY2';
                }when 8 {
                    product2List[i].NATT_SignalCode__c = 'N/A';
                }when 9 {
                    product2List[i].NATT_SignalCode__c = 'OB1';
                }when 10 {
                    product2List[i].NATT_SignalCode__c = 'OBS';
                }when 11 {
                    product2List[i].NATT_SignalCode__c = 'PRC';
                }when 12 {
                    product2List[i].NATT_SignalCode__c = 'A';
                }when else {		  
                    product2List[i].NATT_SignalCode__c = 'A';
                }
            }
        }
        Product2 prod5 = new Product2(Name ='testProd1'+Math.random(),
                                     StockkeepingUnit ='SKU'+Math.random(),NATT_SignalCode__c='NLO',NAC_Stocking_Type_UTC__c='O',ProductCode='2345678',NATT_UOM_Conversion__c=2.0, NATT_CoreItem_P_N__c='2345678',
                                     NATT_Weight__c=32,NATT_Length__c=37,NATT_Height__c=23, NAC_Country_of_Origin_COO__c='xya',NAC_HTSUS__c='rtyy'
                                    );
        product2List.add(prod5);
        insert product2List;
        for(integer i = 0; i < product2List.size(); i++){
            if(i != 0){
                if(i < product2List.size() - 10){
                    product2PriceMap.put(product2List[i].Id, Math.random() * 100);
                }
                product2ATLIdList.add(product2List[i].Id);
            }
            allProduct2PriceMap.put(product2List[i].Id, Math.random() * 100);
        }
        
        List<PriceBook2> priceBookList = NAC_TestDataFactory.createPriceBook(4);
        priceBookList[0].Name = Label.NAOCAP_Prefix + 'C3';
        priceBookList[1].Name = Label.NAOCAP_Prefix + 'V1H';
        priceBookList[2].Name = Label.NAOCAP_Prefix + '48093801';
        priceBookList[3].Name = Label.NAOCAP_Strikethrough_Price_Book;
        insert priceBookList;
        NAC_TestDataFactory.createPriceBookEntry(new Map<Id, Map<Id,Decimal>>{priceBookList[0].Id => product2PriceMap, priceBookList[1].Id => product2PriceMap, priceBookList[2].Id => product2PriceMap, priceBookList[3].Id => allProduct2PriceMap});        
        
        
        PricebookEntry pd=[SELECT CurrencyIsoCode,Name,NATT_Effective_Date__c,Pricebook2Id,Product2Id,Product2.id,
                           Product2.NATT_P_N__c,Product2.Name, Product2.NATT_Core__c ,Product2.NATT_UOM_Conversion__c, 
                           ProductCode,UnitPrice,UseStandardPrice FROM PricebookEntry WHERE Pricebook2.Name =:Label.NAOCAP_Strikethrough_Price_Book LIMIT 1];
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(pd);
        USer us=[select id from User where id=:userinfo.getUserId()];
        system.runAs(us){
            try{
                NAC_CatalogPDFController nc1=new NAC_CatalogPDFController(sc); 
            }
            catch(Exception ex){
                
            }
        }
        Test.stopTest();
    }
}