NATTQA-ENV/force-app/main/default/objects/CONTAINER_Quote_Snapshot__c/CONTAINER_Quote_Snapshot__c.object-meta.xml
<CustomObject>
    <label>Quote Snapshot</label>
    <nameField>
        <displayFormat>QSN-{000000}</displayFormat>
        <label>Quote Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Snapshots</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/CONTAINER_Quote_Snapshot__c/fields/CONTAINER_ASO_Number__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_ASO_Number__c</fullName>
    <label>ASO Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_ASO_ID__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_ASO_ID__c</fullName>
    <label>ASO ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Payment_Terms__c</fullName>
    <description>Picklist field to be added under Production &amp; Scheduling Tab of Quote</description>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CONTAINER_Sales_Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0 DAYS CN RETURN PAY</fullName>
            </value>
            <value>
                <fullName>102 DAYS PAYMENT TERM - 102</fullName>
            </value>
            <value>
                <fullName>12 DAYS PAYMENT TERM - 12</fullName>
            </value>
            <value>
                <fullName>14 DAYS PAYMENT TERM - 14</fullName>
            </value>
            <value>
                <fullName>15 DAYS PAYMENT TERM - 15</fullName>
            </value>
            <value>
                <fullName>21 DAYS PAYMENT TERM - 21</fullName>
            </value>
            <value>
                <fullName>30 DAYS PAYMENT TERM - 30</fullName>
            </value>
            <value>
                <fullName>40 DAYS PAYMENT TERM - 40</fullName>
            </value>
            <value>
                <fullName>45 DAYS PAYMENT TERM - 45</fullName>
            </value>
            <value>
                <fullName>46 DAYS PAYMENT TERM - 46</fullName>
            </value>
            <value>
                <fullName>50 DAYS PAYMENT TERM - 50</fullName>
            </value>
            <value>
                <fullName>60 DAYS PAYMENT TERM - 60</fullName>
            </value>
            <value>
                <fullName>65 DAYS PAYMENT TERM - 65</fullName>
            </value>
            <value>
                <fullName>90 DAYS PAYMENT TERM - 90</fullName>
            </value>
            <value>
                <fullName>120 DAYS PAYMENT TERM - 120</fullName>
            </value>
            <value>
                <fullName>CASH IN ADVANCE - CIA</fullName>
            </value>
            <value>
                <fullName>CASH ON DELIVERY - COD</fullName>
            </value>
            <value>
                <fullName>LETTER OF CREDIT - LOC</fullName>
            </value>
            <value>
                <fullName>NET 30 DAYS – N30</fullName>
            </value>
            <value>
                <fullName>NET 45 DAYS – N45</fullName>
            </value>
            <value>
                <fullName>NET 60 DAYS – N60</fullName>
            </value>
            <value>
                <fullName>NOT APPLICABLE - NAO</fullName>
            </value>
            <value>
                <fullName>NET 365 DAYS – N75</fullName>
            </value>
            <value>
                <fullName>NET 75 DAYS – N97</fullName>
            </value>
            <value>
                <fullName>NET 90 DAYS – N78</fullName>
            </value>
            <value>
                <fullName>LC 30 DAYS FROM BL D - L30</fullName>
            </value>
            <value>
                <fullName>LC 45 DAYS FROM BL D - L45</fullName>
            </value>
            <value>
                <fullName>LC AT SIGHT - 21 DAY - L00</fullName>
            </value>
            <value>
                <fullName>50% CASH IN ADVANCE - CIA 50%</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/CONTAINERQuoteSnapshotReview_Test.cls
/********************************************************************************************************
* @author         Deloitte
* @description    This is a test class for CONTAINERQuoteSnapshotReview class code coverage.
* @date           08/01/2022 [MM/DD/YYYY]
* 
* Modification Log:
* -------------------------------------------------------------------------------------------------------
* Developer                Date                   Modification ID      Description
* -------------------------------------------------------------------------------------------------------
* Deloitte               08/01/2022                                   Initial version
*********************************************************************************************************/
@isTest
public class CONTAINERQuoteSnapshotReview_Test {
    
    //Test data created to handle the process
    @testSetup 
    static void setup() {
        
        // This code runs as the system user
        Profile prof = [SELECT Id FROM Profile WHERE Name='CONTAINER Administrator'];
        User newUser = new User(Alias = 'contAdm', Email='contAdmin@carrier.com', LastName='AdminTest', ProfileId = prof.Id, 
                                UserName='testAdminUser@carrier.com', EmailEncodingKey='UTF-8', 
                                LanguageLocaleKey='en_US', LocaleSidKey='en_US', TimeZoneSidKey='America/Los_Angeles');
        insert newUser;
        
        System.runAs(newUser) {
            CONTAINER_UtilityClass.createCustomerQuote();
        }
    }
    
    
    @isTest
    static void validateQuoteSnapshotReport() {
        User containerAdmin = [select id from user where Alias = 'contAdm' limit 1];
        
        System.runAs(containerAdmin) {
            Test.startTest();
            CONTAINERQuoteSnapshotReview.deleteQuoteSnapshotRecords();
            
            Test.stopTest();
            
            List<SBQQ__Quote__c> updateQuote = [select id, CONTAINER_ASO_ID__c from SBQQ__Quote__c where CONTAINER_ASO_ID__c = '3415'];
            //Validate the changes
            system.assertEquals(updateQuote[0].CONTAINER_ASO_ID__c, '3415', 'Error while Asserting Record');
        }
    }
    
    @isTest
    static void validateQuoteSnapshotRecCreation() {
        User containerAdmin = [select id from user where Alias = 'contAdm' limit 1];
        
        System.runAs(containerAdmin) {
            Test.startTest();
            List<SBQQ__Quote__c> updateQuote = [select id, ApprovalStatus__c, CONTAINER_Payment_Terms__c from SBQQ__Quote__c where CONTAINER_ASO_ID__c = '3415'];
            CONTAINERQuoteSnapshotReview.Processbatch(updateQuote);
            Test.stopTest();
            
            List<CONTAINER_Quote_Snapshot__c> quoteSnapshotID = [select id, CONTAINER_ASO_Number__c from CONTAINER_Quote_Snapshot__c];
            //Validate the changes
            system.assertEquals(quoteSnapshotID[0].CONTAINER_ASO_Number__c, '3415', 'Error while Asserting Record');
        }
    }
    
     @isTest
    static void validateQuoteSnapshotRecBatchClass() {
        User containerAdmin = [select id from user where Alias = 'contAdm' limit 1];
        
        System.runAs(containerAdmin) {
            Test.startTest();
               CONTAINERQuoteSnapshotBatchClass sch = new CONTAINERQuoteSnapshotBatchClass();
               Id batchJobId = Database.executeBatch(sch, 50);
            Test.stopTest();
            
            List<AsyncApexJob> bacthJobRec = [SELECT Id FROM AsyncApexJob WHERE Id =:batchJobId];
            //Validate the changes
            system.assertEquals(bacthJobRec[0].Id, batchJobId, 'Error while Asserting Record');
        }
    }
    
    @isTest
    static void validateQuoteSnapshotRecBatchScheduler() {
        User containerAdmin = [select id from user where Alias = 'contAdm' limit 1];
        
        System.runAs(containerAdmin) {
            Test.startTest();
               String CRON_EXP = '0 0 * * * ?';
               CONTAINERQuoteSnapshotBatchClass sch = new CONTAINERQuoteSnapshotBatchClass();
               system.schedule('Hourly Example Batch Schedule job', CRON_EXP, sch);
            Test.stopTest();
            
            List<SBQQ__Quote__c> updateQuote = [select id, CONTAINER_ASO_ID__c from SBQQ__Quote__c where CONTAINER_ASO_ID__c = '3415'];
            //Validate the changes
            system.assertEquals(updateQuote[0].CONTAINER_ASO_ID__c, '3415', 'Error while Asserting Record');
        }
    }
}