NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/CTBR_List_Unit_Price_USD__c.field-meta.xml
<CustomField>
    <fullName>CTBR_List_Unit_Price_USD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CTBR List Unit Price (USD)</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/CTBR_List_Unit_Pricing_BRL__c.field-meta.xml
<CustomField>
    <fullName>CTBR_List_Unit_Pricing_BRL__c</fullName>
    <formula>IF(NATT_Quote_Recordtype_Dev_Name__c = &apos;CTBR_BluEdge&apos;, CTBR_List_Unit_Price_USD__c*CTBR_Previous_Exchange_Rate__c, CTBR_List_Unit_Price_USD__c*CTBR_Current_Exchange_Rate__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CTBR List Unit Pricing (BRL)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_Quote_Recordtype_Dev_Name__c.field-meta.xml
<CustomField>
    <fullName>NATT_Quote_Recordtype_Dev_Name__c</fullName>
    <description>for use with flow to identify the record type for this quote line</description>
    <formula>SBQQ__Quote__r.RecordType.DeveloperName</formula>
    <label>Quote Recordtype Dev Name</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_Quote_Status__c.field-meta.xml
<CustomField>
    <fullName>NATT_Quote_Status__c</fullName>
    <description>for natt for flow</description>
    <formula>TEXT(SBQQ__Quote__r.SBQQ__Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote Status</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__ListPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ListPrice__c</fullName>
    <description>List unit price for the product quoted by this line item. List Price originates from the price book.</description>
    <inlineHelpText>List unit price for the product quoted by this line item. List Price originates from the price book.</inlineHelpText>
    <label>List Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__OriginalPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__OriginalPrice__c</fullName>
    <description>The original unit price for the product quoted by this line item.  Original Price originates from the price book.  Also known as MSRP.</description>
    <inlineHelpText>The original unit price for the product quoted by this line item.  Original Price originates from the price book.</inlineHelpText>
    <label>Original Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__SubscribedQuoteLine__c/SBQQ__SubscribedQuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscribedAssetHelp</customHelpPage>
    <description>Links a particular asset to the subscription that covers it.</description>
    <label>Subscribed Quote Line</label>
    <nameField>
        <displayFormat>SQL-{00000000}</displayFormat>
        <label>Subscribed Quote Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribed Quote Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__SubscribedQuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies the quote for the quoteLines.</description>
    <inlineHelpText>Identifies the quote for the quoteLines.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/RecalculateCTBRQuoteLines.cls
global class RecalculateCTBRQuoteLines Implements Schedulable{
    global void execute(SchedulableContext sc){
        UpdateCTBRPricing();
    }
    
    public void UpdateCTBRPricing(){
        
        List<SBQQ__QuoteLine__c> listCTBRQL = new List<SBQQ__QuoteLine__c>();
        listCTBRQL = [SELECT Id, Name, SBQQ__ListPrice__c, SBQQ__OriginalPrice__c, CTBR_List_Unit_Price_USD__c, CTBR_List_Unit_Pricing_BRL__c, SBQQ__Quote__c, SBQQ__Quote__r.CurrencyIsoCode, NATT_Quote_Status__c, NATT_Quote_Recordtype_Dev_Name__c 
                      FROM  SBQQ__QuoteLine__c 
                      WHERE NATT_Quote_Status__c = 'Draft' 
                      AND (NATT_Quote_Recordtype_Dev_Name__c = 'CTBR_Units_Quote' OR NATT_Quote_Recordtype_Dev_Name__c = 'CTBR_BluEdge')]; 
                      //AND (SBQQ__ListPrice__c > 0 OR SBQQ__OriginalPrice__c > 0)];
        
        for(SBQQ__QuoteLine__c ql : listCTBRQL){
            if(ql.SBQQ__Quote__r.CurrencyIsoCode == 'BRL'){
                if(ql.NATT_Quote_Recordtype_Dev_Name__c == 'CTBR_Units_Quote'){
                    ql.SBQQ__ListPrice__c = ql.CTBR_List_Unit_Pricing_BRL__c;
                } else if(ql.NATT_Quote_Recordtype_Dev_Name__c == 'CTBR_BluEdge'){
                    ql.SBQQ__OriginalPrice__c = ql.CTBR_List_Unit_Pricing_BRL__c;
                }   
            } else if(ql.SBQQ__Quote__r.CurrencyIsoCode == 'USD'){
                ql.SBQQ__ListPrice__c = ql.CTBR_List_Unit_Price_USD__c;
            }
        }
        update listCTBRQL;
    }
}