NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_ASO_ID__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_ASO_ID__c</fullName>
    <label>ASO ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/Container_Factory_Rework_Comments__c.field-meta.xml
<CustomField>
    <fullName>Container_Factory_Rework_Comments__c</fullName>
    <label>Factory Rework Comments</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Job__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Job__c</fullName>
    <label>Job #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Payment_Terms__c</fullName>
    <description>Picklist field to be added under Production &amp; Scheduling Tab of Quote</description>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CONTAINER_Sales_Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0 DAYS CN RETURN PAY</fullName>
            </value>
            <value>
                <fullName>102 DAYS PAYMENT TERM - 102</fullName>
            </value>
            <value>
                <fullName>12 DAYS PAYMENT TERM - 12</fullName>
            </value>
            <value>
                <fullName>14 DAYS PAYMENT TERM - 14</fullName>
            </value>
            <value>
                <fullName>15 DAYS PAYMENT TERM - 15</fullName>
            </value>
            <value>
                <fullName>21 DAYS PAYMENT TERM - 21</fullName>
            </value>
            <value>
                <fullName>30 DAYS PAYMENT TERM - 30</fullName>
            </value>
            <value>
                <fullName>40 DAYS PAYMENT TERM - 40</fullName>
            </value>
            <value>
                <fullName>45 DAYS PAYMENT TERM - 45</fullName>
            </value>
            <value>
                <fullName>46 DAYS PAYMENT TERM - 46</fullName>
            </value>
            <value>
                <fullName>50 DAYS PAYMENT TERM - 50</fullName>
            </value>
            <value>
                <fullName>60 DAYS PAYMENT TERM - 60</fullName>
            </value>
            <value>
                <fullName>65 DAYS PAYMENT TERM - 65</fullName>
            </value>
            <value>
                <fullName>90 DAYS PAYMENT TERM - 90</fullName>
            </value>
            <value>
                <fullName>120 DAYS PAYMENT TERM - 120</fullName>
            </value>
            <value>
                <fullName>CASH IN ADVANCE - CIA</fullName>
            </value>
            <value>
                <fullName>CASH ON DELIVERY - COD</fullName>
            </value>
            <value>
                <fullName>LETTER OF CREDIT - LOC</fullName>
            </value>
            <value>
                <fullName>NET 30 DAYS – N30</fullName>
            </value>
            <value>
                <fullName>NET 45 DAYS – N45</fullName>
            </value>
            <value>
                <fullName>NET 60 DAYS – N60</fullName>
            </value>
            <value>
                <fullName>NOT APPLICABLE - NAO</fullName>
            </value>
            <value>
                <fullName>NET 365 DAYS – N75</fullName>
            </value>
            <value>
                <fullName>NET 75 DAYS – N97</fullName>
            </value>
            <value>
                <fullName>NET 90 DAYS – N78</fullName>
            </value>
            <value>
                <fullName>LC 30 DAYS FROM BL D - L30</fullName>
            </value>
            <value>
                <fullName>LC 45 DAYS FROM BL D - L45</fullName>
            </value>
            <value>
                <fullName>LC AT SIGHT - 21 DAY - L00</fullName>
            </value>
            <value>
                <fullName>50% CASH IN ADVANCE - CIA 50%</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Not Applicable - N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Sales_Region__c</fullName>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>APO</fullName>
            </value>
            <value>
                <fullName>NAO</fullName>
            </value>
            <value>
                <fullName>SNAO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Status__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Status__c</fullName>
    <description>It will populate here as per the actual status of the quote.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending PM Approval</fullName>
            </value>
            <value>
                <fullName>Pending RSM Acceptance for Special Req</fullName>
            </value>
            <value>
                <fullName>Pending CAM Approval</fullName>
            </value>
            <value>
                <fullName>Pending RSM Acceptance for Prod &amp; Ship Schedule</fullName>
            </value>
            <value>
                <fullName>Pending VP Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Order/Pending for Job #</fullName>
            </value>
            <value>
                <fullName>Job # Issued</fullName>
            </value>
            <value>
                <fullName>ASO Released</fullName>
            </value>
            <value>
                <fullName>SO Released</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
                <label>Lost/Cancelled</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
                <isActive>false</isActive>
                <label>Ordered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/CONTAINER_Quote_Trigger_Test.cls
/********************************************************************************************************
* @author         Deloitte
* @description    This is a test class for CONTAINER_Quote_Trigger_Helper class code coverage.
* @date           09/03/2022 [MM/DD/YYYY]
* 
* Modification Log:
* -------------------------------------------------------------------------------------------------------
* Developer                Date                   Modification ID      Description
* -------------------------------------------------------------------------------------------------------
* Deloitte               09/03/2022                                   Initial version
*********************************************************************************************************/
@isTest
public class CONTAINER_Quote_Trigger_Test {
    
    //Test data created to handle the process
    @testSetup 
    static void setup() {
        //Query Sales RSM Role
        UserRole RSMRole = [SELECT Id FROM UserRole where Name = 'Container Sales RSM NAO' ];
        
        // Create users with public group and role
        Profile prof = [SELECT Id FROM Profile WHERE Name='CONTAINER Administrator'];
        User newUserWithGroup = new User(Alias = 'contAdm', Email='contAdmin@carrier.com', LastName='AdminTest', ProfileId = prof.Id, 
                                         UserName='testAdminUser@carrier.com', EmailEncodingKey='UTF-8', 
                                         LanguageLocaleKey='en_US', LocaleSidKey='en_US', TimeZoneSidKey='America/Los_Angeles', UserRoleId = RSMRole.Id);
        insert newUserWithGroup;
        Group salesVP = [ Select Id  From Group Where DeveloperName = 'CONTAINER_Sales_VP_Approval_NT_Quote'];
        GroupMember salesVPGM = new GroupMember(GroupId = salesVP.Id, UserOrGroupId = newUserWithGroup.Id);
        insert salesVPGM;
        Group salesVP2 = [ Select Id  From Group Where DeveloperName = 'CONTAINER_Sales_CAM_Approval_NT_Quote'];  
        GroupMember salesVP2GM = new GroupMember(GroupId = salesVP2.Id, UserOrGroupId = newUserWithGroup.Id);
        insert salesVP2GM;
        Group salesVP3 = [ Select Id  From Group Where DeveloperName = 'CONTAINER_Sales_PM_Approval_NT_Quote'];   
        GroupMember salesVP3GM = new GroupMember(GroupId = salesVP3.Id, UserOrGroupId = newUserWithGroup.Id);
        insert salesVP3GM;
        
        
        //User without any public group
        User newUserWithoutGroup = new User(Alias = 'contAdm2', Email='contAdmin2@carrier.com', LastName='AdminTest2', ProfileId = prof.Id, 
                                            UserName='testAdminUser2@carrier.com', EmailEncodingKey='UTF-8', 
                                            LanguageLocaleKey='en_US', LocaleSidKey='en_US', TimeZoneSidKey='America/Los_Angeles');
        insert newUserWithoutGroup;
        Group salesVP4 = [ Select Id  From Group Where DeveloperName = 'CONTAINER_Sales_CAM_Approvl_GENSET_Quote'];   
        GroupMember salesVP4GM = new GroupMember(GroupId = salesVP4.Id, UserOrGroupId = newUserWithoutGroup.Id);
        insert salesVP4GM;
        Group salesVP5 = [ Select Id  From Group Where DeveloperName = 'CONTAINER_Sales_RSM_Accep_GENSET_Quote'];   
        GroupMember salesVP5GM = new GroupMember(GroupId = salesVP5.Id, UserOrGroupId = newUserWithoutGroup.Id);
        insert salesVP5GM;
        Group salesVP6 = [ Select Id  From Group Where DeveloperName = 'CONTAINER_Sales_VP_Approval_GENSET_Quote'];
        GroupMember salesVP6GM = new GroupMember(GroupId = salesVP6.Id, UserOrGroupId = newUserWithoutGroup.Id);
        insert salesVP6GM;
        System.runAs(newUserWithGroup) {
            CONTAINER_UtilityClass.createCustomerQuote();
        }
    }
    
    @isTest
    static void validatePendingStatusPositiveSce() {
        User VPApprovalUser = [select id from user where Alias = 'contAdm' limit 1];
        User PMApproalUser = [select id from user where Alias = 'contAdm2' limit 1];
        List<SBQQ__Quote__c> updateQuote2 = new List<SBQQ__Quote__c>();
        Test.startTest();
        //Update quote record as VP Sales approver
        System.runAs(VPApprovalUser) {
            
            List<SBQQ__Quote__c> updateQuote = [select id, ApprovalStatus__c, CONTAINER_Payment_Terms__c from SBQQ__Quote__c where CONTAINER_ASO_ID__c = '3415'];
            //updateQuote[0].CONTAINER_Payment_Terms__c = 'Not Applicable - N/A';
            updateQuote[0].ApprovalStatus__c = 'Pending';
            update updateQuote;
            
            updateQuote[0].CONTAINER_Status__c = 'Pending RSM Acceptance for Special Req';
            update updateQuote;
           
            updateQuote[0].CONTAINER_Status__c = 'Pending PM Approval';
            update updateQuote;
            
            updateQuote[0].ApprovalStatus__c = 'Recalled';
           // updateQuote[0].Container_Factory_Rework_Comments__c = 'ReTest';
            update updateQuote;
            
        }
        
        //Update Quote as RSM Sales User
        System.runAs(PMApproalUser) {
            String GENSETRecord = Schema.getGlobalDescribe().get('SBQQ__Quote__c').getDescribe().getRecordTypeInfosByName().get('Container GENSET Quote').getRecordTypeId();
            String NTRecord = Schema.getGlobalDescribe().get('SBQQ__Quote__c').getDescribe().getRecordTypeInfosByName().get('Container NT Quote').getRecordTypeId();
            updateQuote2 = [select id, ApprovalStatus__c, CONTAINER_Payment_Terms__c, CONTAINER_Sales_Region__c, RecordTypeId from SBQQ__Quote__c where CONTAINER_ASO_ID__c = '3415'];
            
            updateQuote2[0].Container_Factory_Rework_Comments__c = 'ReTest';
            updateQuote2[0].CONTAINER_Job__c = null;
            update updateQuote2;
            
            updateQuote2[0].CONTAINER_Sales_Region__c = 'NAO';
            updateQuote2[0].CONTAINER_Payment_Terms__c = 'NOT APPLICABLE - NAO';
            updateQuote2[0].RecordTypeId = GENSETRecord;
            update updateQuote2;
            
            updateQuote2[0].CONTAINER_Status__c = 'Pending RSM Acceptance for Prod & Ship Schedule';
            update updateQuote2;
            
            updateQuote2[0].Container_Factory_Rework_Comments__c = 'RedoTest';
            updateQuote2[0].CONTAINER_Status__c = 'Pending CAM Approval';
            update updateQuote2;
            
            updateQuote2[0].Container_Factory_Rework_Comments__c = 'RedoTest2';
            update updateQuote2;
            
            updateQuote2[0].CONTAINER_Sales_Region__c = 'APO';
            updateQuote2[0].CONTAINER_Payment_Terms__c = 'Not Applicable - N/A';
            updateQuote2[0].RecordTypeId = NTRecord;
            update updateQuote2;
            
            updateQuote2[0].CONTAINER_Status__c = 'Pending CAM Approval';
            update updateQuote2;
            
            updateQuote2[0].Container_Factory_Rework_Comments__c = 'ReworkTest';
            updateQuote2[0].ApprovalStatus__c = 'Approved';
            update updateQuote2;
        }
        Test.stopTest();
        
        //Get list of updated quote record.
        List<SBQQ__Quote__c> quoteRecordID = [select id, ApprovalStatus__c, CONTAINER_Payment_Terms__c from SBQQ__Quote__c where id =:updateQuote2[0].id];
        system.assertEquals(quoteRecordID[0].ApprovalStatus__c, 'Approved', 'Error while Asserting Record');
    }
    
    @isTest
    static void validatePendingStatusPositiveSce2() {
        User VPApprovalUser = [select id from user where Alias = 'contAdm' limit 1];
        User PMApproalUser = [select id from user where Alias = 'contAdm2' limit 1];
        List<SBQQ__Quote__c> updateQuote2 = new List<SBQQ__Quote__c>();
        Test.startTest();
        
        //Update Quote as RSM Sales User
        System.runAs(PMApproalUser) {
            String GENSETRecord = Schema.getGlobalDescribe().get('SBQQ__Quote__c').getDescribe().getRecordTypeInfosByName().get('Container GENSET Quote').getRecordTypeId();
            String NTRecord = Schema.getGlobalDescribe().get('SBQQ__Quote__c').getDescribe().getRecordTypeInfosByName().get('Container NT Quote').getRecordTypeId();
            updateQuote2 = [select id, ApprovalStatus__c, CONTAINER_Payment_Terms__c, CONTAINER_Sales_Region__c, RecordTypeId from SBQQ__Quote__c where CONTAINER_ASO_ID__c = '3415'];
            
            updateQuote2[0].CONTAINER_Sales_Region__c = 'NAO';
            updateQuote2[0].CONTAINER_Payment_Terms__c = 'NOT APPLICABLE - NAO';
            updateQuote2[0].CONTAINER_Job__c = null;
            updateQuote2[0].ApprovalStatus__c = 'Pending';
            updateQuote2[0].RecordTypeId = GENSETRecord;
            update updateQuote2;
            
            updateQuote2[0].CONTAINER_Status__c = 'Pending RSM Acceptance for Special Req';
            update updateQuote2;
            
            updateQuote2[0].Container_Factory_Rework_Comments__c = 'RedoTest';
            updateQuote2[0].CONTAINER_Status__c = 'Pending CAM Approval';
            update updateQuote2;
            
            updateQuote2[0].Container_Factory_Rework_Comments__c = 'ReworkTest';
            updateQuote2[0].ApprovalStatus__c = 'Approved';
            update updateQuote2;
        }
        Test.stopTest();
        
        //Get list of updated quote record.
        List<SBQQ__Quote__c> quoteRecordID = [select id, ApprovalStatus__c, CONTAINER_Payment_Terms__c from SBQQ__Quote__c where id =:updateQuote2[0].id];
        system.assertEquals(quoteRecordID[0].ApprovalStatus__c, 'Approved', 'Error while Asserting Record');
    }
}