NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CTBR_Condicoes_comerciais__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Condicoes_comerciais__c</fullName>
    <label>Condições comerciais</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A vista ( in cash)</fullName>
            </value>
            <value>
                <fullName>Credito (credit)</fullName>
            </value>
            <value>
                <fullName>Parcelado - com entrada (Installments - with deposit)</fullName>
            </value>
            <value>
                <fullName>Parcelado - sem entrada (Installments - with deposit)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CTBR_Freight_Price__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Freight_Price__c</fullName>
    <description>Freight Price</description>
    <label>Freight Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CTBR_Freight_Terms__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Freight_Terms__c</fullName>
    <label>Freight Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CTBR_Payment_Condition_Code__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Payment_Condition_Code__c</fullName>
    <description>Payment Condition Code</description>
    <label>Payment Condition Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CTBR_Quote_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Quote_Delivery_Date__c</fullName>
    <label>Quote Delivery Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CTBR_Subtotal_ICMS__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Subtotal_ICMS__c</fullName>
    <description>Sum R$ Itens + Sum ICMS + Sum IPI</description>
    <label>Subtotal ICMS</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CTBR_Tax_Observation__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Tax_Observation__c</fullName>
    <label>Tax Observation</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CTBR_Total_ICMS__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Total_ICMS__c</fullName>
    <description>Sum ICMS</description>
    <label>Total ICMS</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CTBR_Total_ICMS_ST__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Total_ICMS_ST__c</fullName>
    <description>Sum ICMS ST</description>
    <label>Total ICMS ST</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CTBR_Total_IPI__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Total_IPI__c</fullName>
    <description>Sum IPI</description>
    <label>Total IPI</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CTBR_Total_Payable__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Total_Payable__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Quote total price (DocTotal)</description>
    <label>Total Payable</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Dealer_Comments__c.field-meta.xml
<CustomField>
    <fullName>NATT_Dealer_Comments__c</fullName>
    <description>NATT</description>
    <label>Dealer Comments</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Product_Family__c.field-meta.xml
<CustomField>
    <fullName>NATT_Product_Family__c</fullName>
    <description>NATT</description>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Product_Family</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Quote_Request_Date__c.field-meta.xml
<CustomField>
    <fullName>NATT_Quote_Request_Date__c</fullName>
    <description>NATT</description>
    <label>Quote Request Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Shipment_Method__c.field-meta.xml
<CustomField>
    <fullName>NATT_Shipment_Method__c</fullName>
    <description>NATT</description>
    <label>Shipment Method</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Product_Family__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BW</fullName>
                <label>Best Way</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Customer Pickup</label>
            </value>
            <value>
                <fullName>ABF</fullName>
            </value>
            <value>
                <fullName>OTH</fullName>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PaymentTerms__c</fullName>
    <description>Terms that govern payment of the items in this quote.</description>
    <inlineHelpText>Terms that govern payment of the items in this quote.</inlineHelpText>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Due on receipt</fullName>
            </value>
            <value>
                <fullName>Net 15</fullName>
            </value>
            <value>
                <fullName>Net 30</fullName>
                <default>true</default>
                <label>Net 30</label>
            </value>
            <value>
                <fullName>Net 45</fullName>
            </value>
            <value>
                <fullName>Net 55</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
            <value>
                <fullName>Net 90</fullName>
            </value>
            <value>
                <fullName>Net 120</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/CTBR_Purchase_Number_Optional__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Purchase_Number_Optional__c</fullName>
    <label>Purchase Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/CTBR_Purchase_Number_U_IB_OrdemCompra__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Purchase_Number_U_IB_OrdemCompra__c</fullName>
    <label>Purchase Number (U_IB_OrdemCompra)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__AllowAssetRefund__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__AllowAssetRefund__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether the underlying asset may have its quantity refunded. Only relevant for Amendments.</description>
    <inlineHelpText>Indicates whether the asset represented by this line may be refunded.</inlineHelpText>
    <label>Allow Asset Refunds</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Bundle__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Bundle__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this line item represents a package; meaning, it includes other line items in this quote.</description>
    <inlineHelpText>Indicates whether this line item represents a package; meaning, it includes other line items in this quote.</inlineHelpText>
    <label>Package</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Bundled__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Bundled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates the product on this line item is bundled (included) by another product in this quote. Bundled lines items are zero price and do not allow price or quantity to be edited.</description>
    <inlineHelpText>Indicates the product on this line item is bundled (included) by another product in this quote. Bundled lines items have a zero price and do not allow price or quantity to be edited.</inlineHelpText>
    <label>Bundled</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__CarryoverLine__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__CarryoverLine__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes this line as an auto-mapped option on an Upgraded Bundle.</description>
    <inlineHelpText>Denotes this line as an auto-selected option of an upgrade bundle.</inlineHelpText>
    <label>Carry-Over Line</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Discount__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Discount__c</fullName>
    <description>Additional customer discount extended for this line item expressed in terms of percentage.</description>
    <inlineHelpText>Additional customer discount extended to this line item expressed in form of a percentage.</inlineHelpText>
    <label>Additional Disc. (%)</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__ListPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ListPrice__c</fullName>
    <description>List unit price for the product quoted by this line item. List Price originates from the price book.</description>
    <inlineHelpText>List unit price for the product quoted by this line item. List Price originates from the price book.</inlineHelpText>
    <label>List Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__NetPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__NetPrice__c</fullName>
    <description>Net unit price for the product quoted by this line item.</description>
    <inlineHelpText>Net unit price for the product quoted by this line item.</inlineHelpText>
    <label>Net Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quantity__c</fullName>
    <description>Quantity being quoted.</description>
    <inlineHelpText>Quantity being quoted.</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Trailer</fullName>
    </customValue>
    <customValue>
        <fullName>Diesel Truck</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Drive</fullName>
    </customValue>
    <customValue>
        <fullName>APU</fullName>
    </customValue>
    <customValue>
        <fullName>Solara</fullName>
    </customValue>
    <customValue>
        <fullName>Electric Truck</fullName>
    </customValue>
    <customValue>
        <fullName>Electric Trailer</fullName>
        <isActive>false</isActive>
        <label>Electric Trailer</label>
    </customValue>
    <customValue>
        <fullName>DD Truck</fullName>
        <isActive>false</isActive>
        <label>DD Truck</label>
    </customValue>
    <masterLabel>NATT Product Family</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/ctbrQuoteInboundIntegration_Test.cls
@isTest(seeAllData = true)
public class ctbrQuoteInboundIntegration_Test {
    public static SBQQ__Quote__c quote;
    public static SBQQ__QuoteLine__c quoteLine;
    public static Product2 prod;

    static void setData() {
        
        prod = new Product2();
        prod.Name = 'Test';
        prod.ProductCode = '0908777';
        insert prod;
        
        Recordtype recType = [select id,name,SobjectType from RecordType where name = 'CTBR Units Quote'];
        
        quote = new SBQQ__Quote__c();
        quote.SBQQ__Status__c = 'Approved';
        quote.NATT_Quote_Request_Date__c = date.today();
        quote.NATT_Dealer_Comments__c = 'Test';
        quote.CTBR_Quote_Delivery_Date__c = date.today().addDays(1);
        quote.CTBR_Freight_Terms__c = 'CIF';
        quote.NATT_Product_Family__c = 'Trailer';
        quote.recordtypeId = recType.Id;
        //quote.NATT_Shipment_Method__c = 'Best Way';
        quote.SBQQ__PaymentTerms__c = 'Net 31';
        quote.CTBR_Condicoes_comerciais__c='Credito (credit)';
        quote.CTBR_Tax_Observation__c = 'tax';
        insert quote;
        System.debug('Quote id is'+quote.id);

        quoteLine = new SBQQ__QuoteLine__c();
        quoteLine.SBQQ__Discount__c = 10;
        //quoteLine.SBQQ__ProductName__c = 'CITIMAX 280 12V R404a';
        quoteLine.SBQQ__Product__c = prod.id;
        quoteLine.CTBR_Purchase_Number_Optional__c = null;
        quoteLine.CTBR_Purchase_Number_U_IB_OrdemCompra__c = null;
        quoteLine.SBQQ__Quantity__c = 2;
        quoteLine.SBQQ__ListPrice__c = 100;
        quoteLine.SBQQ__NetPrice__c = 200;
        quoteLine.SBQQ__Quote__c = quote.id;
        quoteLine.SBQQ__AllowAssetRefund__c = false;
        quoteLine.SBQQ__Bundle__c = false;
        quoteLine.SBQQ__Bundled__c = false;
        quoteLine.SBQQ__CarryoverLine__c = false;
        quoteline.SBQQ__Quote__c = quote.id;
        try {
            insert quoteLine;
        } catch (Exception e) {
            e.getMessage();
        }
        
        

    }

    static testMethod void updateQuoteTest() {
        setData();
        SBQQ__Quote__c quoteObj = [SELECT id, recordtype.name, CTBR_Payment_Condition_Code__c, CTBR_Freight_Price__c, CTBR_Subtotal_ICMS__c, CTBR_Total_ICMS__c, CTBR_Total_ICMS_ST__c, CTBR_Total_IPI__c, CTBR_Total_Payable__c, CTBR_Fixed_Payment__c, CTBR_Has_Global_Price_List__c, CTBR_Global_Price_List_Code__c, CTBR_Taxation__c FROM SBQQ__Quote__c where id =: quote.id];
        quoteObj.CTBR_Payment_Condition_Code__c = 780;
        quoteObj.CTBR_Freight_Price__c = 1000;
        quoteObj.CTBR_Subtotal_ICMS__c = 8000;
        quoteObj.CTBR_Total_ICMS__c = 670;
        quoteObj.CTBR_Total_ICMS_ST__c = 6098;
        quoteObj.CTBR_Total_IPI__c = 1093;
        quoteObj.CTBR_Total_Payable__c = 4000;
        quoteObj.CTBR_Has_Global_Price_List__c = False;
        quoteObj.CTBR_Fixed_Payment__c = False;
        quoteObj.CTBR_Global_Price_List_Code__c = 3234;
        quoteObj.CTBR_Taxation__c = 3243.00;
        update quoteObj;
    }

    static testMethod void testgetQuoteAndQuoteLineItems() {
        setData();
        SBQQ__Quote__c quo = [SELECT Id, SBQQ__Status__c, CTBR_Tax_Observation__c, NATT_Dealer_Comments__c, SBQQ__PaymentTerms__c, NATT_Quote_Request_Date__c, CTBR_Freight_Terms__c, NATT_Shipment_Method__c FROM SBQQ__Quote__c where id =: quote.id];
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/retrieveQuotes/' + quo.Id;
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        ctbrQuoteInboundIntegration.getQuoteAndQuoteLineItems();
        Test.stopTest();
        system.assertEquals(quo.SBQQ__Status__c, 'Approved');
        system.assertEquals(quo.NATT_Dealer_Comments__c, 'Test');
        system.assertEquals(quo.NATT_Quote_Request_Date__c, date.today());
        system.assertEquals(quo.CTBR_Freight_Terms__c, 'CIF');
        system.assertEquals(quo.SBQQ__PaymentTerms__c, 'Net 31');
        //system.assertEquals(quo.NATT_Shipment_Method__c, 'Best Way');
        system.assertEquals(quo.CTBR_Tax_Observation__c, 'tax');
    }

    static testMethod void testPut() {
        setData();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/retrieveQuotes/';
        req.httpMethod = 'PUT';
        RestContext.request = req;
        RestContext.response = res;
        SBQQ__Quote__c qcc = [SELECT Id, CTBR_Payment_Condition_Code__c, CTBR_Freight_Price__c FROM SBQQ__Quote__c where id =: quote.id];
        try {
            ctbrQuoteInboundIntegration.updateQuote(null);
        } catch (Exception e) {}
        try {
            ctbrQuoteInboundIntegration.getQuoteAndQuoteLineItems();
        } catch (Exception e) {}
    }
    
    static testMethod void testquoteWrapper() {
        List<ctbrQuoteInboundIntegration.quoteWrapper> quoteWrap = new List<ctbrQuoteInboundIntegration.quoteWrapper>();
        List<ctbrQuoteInboundIntegration.quoteLineWrapper> quoteLWrap = new List<ctbrQuoteInboundIntegration.quoteLineWrapper>();
        
        ctbrQuoteInboundIntegration.quoteLineWrapper cL = new ctbrQuoteInboundIntegration.quoteLineWrapper();
        cL.name = 'TestL';
        cL.discount = 10.20;
        cL.componentCost = 12.12;
        //cL.quoteLineExternalId = '12';
        cL.quantity = '1.00';
        cL.product = '';
        //cL.productCode =
        //cL.purchaseNumberOptional =
        cL.purchaseNumberUIB =
        cL.unitMeasurement =
        cL.listPrice =
        cL.netPrice =
        cL.NCM = 'CTBR_NCM__c';
        cL.totalPrice = '14.22';
        cL.priceStTax = '14.22';
        cL.percentageIpiTax = '14.22';
        cL.priceIpiTax = '14.33';
        cL.netTotalPlusPriceIpiTax = '14.33';
        cL.exchangeTaxOfTheQuoteCreation = '14.33';
        cL.actualUnitPrice = '14.33';
        cL.materialGroupPercent ='14.22';
        cL.freightPercentOfGlobalParameter = '14.22';
        cL.customFeesPercentOfGlobalParameter =  '14.22';
        cL.netValueInDollar = '12.22';
        cL.realNetValue = '12.22';
        cL.totalTax = '12.22';
        cL.icmsTax = '12.22';
        cL.pisTax ='12.22';
        cL.cofinsTax = '12.22';
        cL.discountPercentInCustomerGroup =  '14.22';
        cL.itemQuantityAvailableForSales = '11';
        quoteLWrap.add(cL);
        
        ctbrQuoteInboundIntegration.quoteWrapper c = new ctbrQuoteInboundIntegration.quoteWrapper();    
        c.quoteline = quoteLWrap;
        c.name = 'Test';
        c.status = 'Approved';
        c.SenttoSAP = false;
        c.requestDate = '12-12-12';
        c.dealerComments = '12-12-12';
        c.paymentTerms = 'Net 31';
        c.freightTerms = 'Net 31';
        c.shipmentMethod = 'Best Way';
        c.taxObservation = 'tax';
        c.salesRep = userinfo.getUserId();
        c.paymentCCode = '11';
        c.freightPrice = '11.5666';
        c.subICMS = '11.5666';
        c.totalICMS = '11.5666';
        c.totalIPI = '11.5666';
        c.totalICMSST = '11.5666';
        c.totalPayable = '11.5666';
        c.fixedPayment = 'true';
        c.hasGlobalPriceList = 'true';
        c.globalPriceListCode = '11.0';
        c.taxation  = 'tax';
        c.taxation  = '11.5666';
        quoteWrap.add(c);
        
        ctbrQuoteInboundIntegration.updateQuote(quoteWrap);
        
    }
}