NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CTBR_Current_Exchange_Rate__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Current_Exchange_Rate__c</fullName>
    <formula>$CustomMetadata.CTBR_Exchange_Rate__mdt.CTBR_Units.Current_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Exchange Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Quote_Record_Type_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>NATT_Quote_Record_Type_Developer_Name__c</fullName>
    <description>Used to default Quote Record Developer Name through a Process Builder.</description>
    <label>Quote Record Type Developer Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/CTBR_Current_Exchange_Rate__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Current_Exchange_Rate__c</fullName>
    <formula>$CustomMetadata.CTBR_Exchange_Rate__mdt.CTBR_Units.Current_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Exchange Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/CTBR_List_Unit_Price_USD__c.field-meta.xml
<CustomField>
    <fullName>CTBR_List_Unit_Price_USD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CTBR List Unit Price (USD)</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/CTBR_List_Unit_Pricing_BRL__c.field-meta.xml
<CustomField>
    <fullName>CTBR_List_Unit_Pricing_BRL__c</fullName>
    <formula>IF(NATT_Quote_Recordtype_Dev_Name__c = &apos;CTBR_BluEdge&apos;, CTBR_List_Unit_Price_USD__c*CTBR_Previous_Exchange_Rate__c, CTBR_List_Unit_Price_USD__c*CTBR_Current_Exchange_Rate__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CTBR List Unit Pricing (BRL)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/CTBR_Previous_Exchange_Rate__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Previous_Exchange_Rate__c</fullName>
    <formula>$CustomMetadata.CTBR_Exchange_Rate__mdt.CTBR_BlueEdge.Previous_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Previous Exchange Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__ListPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ListPrice__c</fullName>
    <description>List unit price for the product quoted by this line item. List Price originates from the price book.</description>
    <inlineHelpText>List unit price for the product quoted by this line item. List Price originates from the price book.</inlineHelpText>
    <label>List Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__SubscribedQuoteLine__c/SBQQ__SubscribedQuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscribedAssetHelp</customHelpPage>
    <description>Links a particular asset to the subscription that covers it.</description>
    <label>Subscribed Quote Line</label>
    <nameField>
        <displayFormat>SQL-{00000000}</displayFormat>
        <label>Subscribed Quote Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribed Quote Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__SubscribedQuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies the quote for the quoteLines.</description>
    <inlineHelpText>Identifies the quote for the quoteLines.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/RecalculateCTBRQuoteLinesTest.cls
@isTest(SeeAllData=true)
private class RecalculateCTBRQuoteLinesTest{

    static testMethod void myTestMethod() {        
         Test.startTest();
           
         List<SBQQ__QuoteLine__c> listCTBRQL = new List<SBQQ__QuoteLine__c>();
         listCTBRQL = [SELECT Id, Name, SBQQ__ListPrice__c, CTBR_List_Unit_Price_USD__c, CTBR_List_Unit_Pricing_BRL__c, CTBR_Current_Exchange_Rate__c, CTBR_Previous_Exchange_Rate__c, SBQQ__Quote__c, SBQQ__Quote__r.CurrencyIsoCode, SBQQ__Quote__r.SBQQ__Status__c, SBQQ__Quote__r.NATT_Quote_Record_Type_Developer_Name__c FROM  SBQQ__QuoteLine__c WHERE SBQQ__Quote__r.SBQQ__Status__c = 'Draft' AND (SBQQ__Quote__r.NATT_Quote_Record_Type_Developer_Name__c = 'CTBR_Units_Quote' OR SBQQ__Quote__r.NATT_Quote_Record_Type_Developer_Name__c = 'CTBR_BluEdge') AND SBQQ__Quote__r.CurrencyIsoCode = 'BRL'];
        
         for(SBQQ__QuoteLine__c ql : listCTBRQL){
            ql.SBQQ__ListPrice__c = ql.CTBR_List_Unit_Pricing_BRL__c;
         }
         update listCTBRQL;
         
         RecalculateCTBRQuoteLines myClass = new RecalculateCTBRQuoteLines();   
         String chron = '0 0 23 * * ?';        
         system.schedule('Test Sched', chron, myClass);
         test.stopTest();
    }
    
    static testMethod void myTestMethod2() {        
         Test.startTest();
           
         List<SBQQ__QuoteLine__c> listCTBRQL = new List<SBQQ__QuoteLine__c>();
         listCTBRQL = [SELECT Id, Name, SBQQ__ListPrice__c, CTBR_List_Unit_Price_USD__c, CTBR_List_Unit_Pricing_BRL__c, CTBR_Current_Exchange_Rate__c, CTBR_Previous_Exchange_Rate__c, SBQQ__Quote__c, SBQQ__Quote__r.CurrencyIsoCode, SBQQ__Quote__r.SBQQ__Status__c, SBQQ__Quote__r.NATT_Quote_Record_Type_Developer_Name__c FROM  SBQQ__QuoteLine__c WHERE SBQQ__Quote__r.SBQQ__Status__c = 'Draft' AND (SBQQ__Quote__r.NATT_Quote_Record_Type_Developer_Name__c = 'CTBR_Units_Quote' OR SBQQ__Quote__r.NATT_Quote_Record_Type_Developer_Name__c = 'CTBR_BluEdge') AND SBQQ__Quote__r.CurrencyIsoCode = 'USD'];
        
         for(SBQQ__QuoteLine__c ql : listCTBRQL){
            ql.SBQQ__ListPrice__c = ql.CTBR_List_Unit_Price_USD__c;
         }
         update listCTBRQL;
         
         RecalculateCTBRQuoteLines myClass = new RecalculateCTBRQuoteLines();   
         String chron = '0 0 23 * * ?';        
         system.schedule('Test Sched', chron, myClass);
         test.stopTest();
    }
}