NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/Sent_Cancelled_to_SAP__c.field-meta.xml
<CustomField>
    <fullName>Sent_Cancelled_to_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will be set when Cancelled quotes are sent to SAP, to avoid resending.</description>
    <label>Sent Cancelled to SAP</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__ComponentCost__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ComponentCost__c</fullName>
    <description>Total cost of components in this package.</description>
    <inlineHelpText>Total cost of components in this package.</inlineHelpText>
    <label>Component Cost</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Discount__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Discount__c</fullName>
    <description>Additional customer discount extended for this line item expressed in terms of percentage.</description>
    <inlineHelpText>Additional customer discount extended to this line item expressed in form of a percentage.</inlineHelpText>
    <label>Additional Disc. (%)</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/ctbr_RetrieveCancelQuoteInbound.cls
/*Author: LTI
* Created Date: 13th October 2022
* Class Name: ctbr_RetrieveCancelQuoteInbound
* Description: This class is used to retrieve CTBR Units Cancelled quote from Salesforce
*/
@RestResource(urlMapping='/queryCancelQuote/*')
global without sharing class ctbr_RetrieveCancelQuoteInbound {
 
    // this method is used to fetch all the Cancelled CTBR quote records requested from SAP
    @HttpGet
    global static List<quoteWrapper> getQuoteAndQuoteLineItems() {
        try{
            List<SBQQ__Quote__c> quoteAndQuoteLineItemsLst = new List<SBQQ__Quote__c>();
            List<quoteWrapper> cancelledQuoteWrapperLst = new List<quoteWrapper>();
            //Only quote information needs to be sent, quote lines need not be sent. 
            for(SBQQ__Quote__c quoteObj : [SELECT id,recordtype.name,SBQQ__Status__c,name FROM SBQQ__Quote__c 
                                           WHERE recordtype.name = 'CTBR Units Quote'
                                           AND SBQQ__Status__c = 'Canceled' AND Sent_Cancelled_to_SAP__c = FALSE]) //1/19 corrected the flag to Sent_Cancelled_to_SAP__c
            {
                           quoteWrapper quoteWrapperObj = new quoteWrapper();
                           quoteWrapperObj.name = quoteObj.name;
                           quoteWrapperObj.status = quoteObj.SBQQ__Status__c;
                           quoteWrapperObj.quoteExternalId = quoteObj.id;
                           //    quoteWrapperObj.quoteline = storeQuoteLine(quoteObj.SBQQ__LineItems__r);
                           quoteobj.Sent_Cancelled_to_SAP__c = true;//17/10 this avoids resending of Cancelled quotes to SAP
                           // in the successive requests to Salesforce.
                           cancelledQuoteWrapperLst.add(quoteWrapperObj);
                           quoteAndQuoteLineItemsLst.add(quoteobj);//17/10
             }
                                          
            if(!quoteAndQuoteLineItemsLst.isempty())
            {	update quoteAndQuoteLineItemsLst;//17/10 
            }
            
            return cancelledQuoteWrapperLst;
        }catch(Exception ex){
            ctbrUtility.LogException(ex, 'ctbrRetrieveCancelQuoteIntegration', 'getQuoteAndQuoteLineItems');
            return null;
        }
    }
    
    //this method is used to store quoteLineItems in the quoteWrapperObj.. not required..
   /* public static List<quoteLineWrapper> storeQuoteLine(List<SBQQ__QuoteLine__c> lstQuoteLine) {
        
        List<quoteLineWrapper> quoteLineList = new List<quoteLineWrapper>();
        
        for(SBQQ__QuoteLine__c  quoteLineObj: lstQuoteLine){
            quoteLineWrapper quoteLineWrapperObj = new quoteLineWrapper();
            quoteLineWrapperObj.name = quoteLineObj.name;
            quoteLineWrapperObj.discount = quoteLineObj.SBQQ__Discount__c;
            quoteLineWrapperObj.componentCost = quoteLineObj.SBQQ__ComponentCost__c;
            quoteLineWrapperObj.quoteLineExternalId = quoteLineObj.id;
            quoteLineList.add(quoteLineWrapperObj);
        }
        return quoteLineList;   
    }*/
    
    global class quoteWrapper {
    //    public List<quoteLineWrapper> quoteline;
        public String name;
        public String status;
        public String quoteExternalId;
    }
    
    global class quoteLineWrapper {
        public String name;
        public double discount;
        public double componentCost;
        public String quoteLineExternalId;
    }
    
    global class ResponseSummary {
        //List of custom attributes that we want to check the status of the org
         
    }
}