NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Cost_Contract_Price__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Cost_Contract_Price__c</fullName>
    <label>Contract Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_GrossMargin_w_o_Warranty1__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_GrossMargin_w_o_Warranty1__c</fullName>
    <formula>IF(OR(ISBLANK(CONTAINER_Gross_Margin_w_o_Warranty1__c),CONTAINER_Gross_Margin_w_o_Warranty1__c = 0,ISBLANK(CONTAINER_Net_Sales1__c ),CONTAINER_Net_Sales1__c = 0),
0,( CONTAINER_Gross_Margin_w_o_Warranty1__c / CONTAINER_Net_Sales1__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gross Margin w/o Warranty %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_GrossMargin_w_Warranty1__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_GrossMargin_w_Warranty1__c</fullName>
    <formula>IF(OR(ISBLANK(CONTAINER_Gross_Margin_w_Warranty1__c), CONTAINER_Gross_Margin_w_Warranty1__c = 0,ISBLANK(CONTAINER_Net_Sales1__c ), CONTAINER_Net_Sales1__c  = 0),
0, (CONTAINER_Gross_Margin_w_Warranty1__c / CONTAINER_Net_Sales1__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gross Margin w/ Warranty %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_List_Price__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_List_Price__c</fullName>
    <formula>IF(BEGINS(RecordType.DeveloperName, &apos;CONTAINER&apos;), CONTAINER_Unit_Base_Price_Sales__c + 
CONTAINER_Standard_Option_Sales__c + 
CONTAINER_Special_Options_Sales__c + 
CONTAINER_Extended_Warranty_Sales__c + 
CONTAINER_Special_Requirement_Sales__c + 
CONTAINER_Total_Contract_Obligation__c + 
CONTAINER_Total_Extended_AppliedSales__c + 
CONTAINER_Total_Spare_Parts__c  +  
CONTAINER_Total_ORBCOMM_AppliedCost__c,  SBQQ__NetAmount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Model_Number__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Model_Number__c</fullName>
    <label>Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Net_Sales1__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Net_Sales1__c</fullName>
    <formula>( CONTAINER_Cost_Contract_Price__c  - (CONTAINER_Total_Contract_Obligation__c  +  CONTAINER_Total_Extended_AppliedSales__c  +  CONTAINER_Total_Spare_Parts__c  +  CONTAINER_Total_ORBCOMM_AppliedCost__c +  CONTAINER_Total_Freight_Applied_to_Sales__c  ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Sales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/CONTAINER_Customer_Part_number__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Customer_Part_number__c</fullName>
    <label>Customer Part number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/CONTAINER_List_Price__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_List_Price__c</fullName>
    <description>List price from product</description>
    <label>Product List Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/CONTAINER_Model_Number__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Model_Number__c</fullName>
    <description>This field is used to store the model number for selected product.</description>
    <inlineHelpText>This field is used to store the model number for selected product.</inlineHelpText>
    <label>Model Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/CONTAINER_Option_Type__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Option_Type__c</fullName>
    <description>Twin Field from product option</description>
    <label>Option Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Special</fullName>
            </value>
            <value>
                <fullName>Warranty</fullName>
            </value>
            <value>
                <fullName>Special Requirements</fullName>
            </value>
            <value>
                <fullName>Reserves</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_P_N__c</fullName>
    <description>for NATT quotes</description>
    <label>P/N</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Bundle__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Bundle__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this line item represents a package; meaning, it includes other line items in this quote.</description>
    <inlineHelpText>Indicates whether this line item represents a package; meaning, it includes other line items in this quote.</inlineHelpText>
    <label>Package</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__RequiredBy__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RequiredBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this line to another line in the same quote whose product requires this line&apos;s product.</description>
    <inlineHelpText>Indicates which other product on this quote requires it.</inlineHelpText>
    <label>Required By</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__SubscribedQuoteLine__c/SBQQ__SubscribedQuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscribedAssetHelp</customHelpPage>
    <description>Links a particular asset to the subscription that covers it.</description>
    <label>Subscribed Quote Line</label>
    <nameField>
        <displayFormat>SQL-{00000000}</displayFormat>
        <label>Subscribed Quote Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribed Quote Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__SubscribedQuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies the quote for the quoteLines.</description>
    <inlineHelpText>Identifies the quote for the quoteLines.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/CONTAINER_Quote_Summary_Page_Helper.cls
public with sharing class CONTAINER_Quote_Summary_Page_Helper {
    @AuraEnabled(cacheable=true)
    public static List<DataWrapper> getQuoteSummary(String recId) {

        id myId = recId;
        list<DataWrapper> listLineItems  = new list<DataWrapper>();
        list<DataWrapper> listLineItems1  = new list<DataWrapper>();
        list<DataWrapper> listLineItems2  = new list<DataWrapper>();
        list<DataWrapper> listLineItems3  = new list<DataWrapper>();
        list<DataWrapper> listLineItems4  = new list<DataWrapper>();
        list<DataWrapper> listLineItems5  = new list<DataWrapper>();

        List<SBQQ__QuoteLine__c> quoteList = [SELECT Id,Name,
                                                    SBQQ__RequiredBy__c,SBQQ__OptionLevel__c,SBQQ__Bundle__c,NATT_P_N__c,
                                                    CONTAINER_Model_Number__c,SBQQ__ProductName__c,CONTAINER_List_Price__c,
                                                    CONTAINER_Customer_Part_number__c,SBQQ__Quote__r.CONTAINER_Model_Number__c,
                                                    CONTAINER_Option_Type__c,SBQQ__ProductCode__c,CONTAINER_Warranty_Description__c,
                                                    SBQQ__Quote__r.CONTAINER_Cost_Contract_Price__c,SBQQ__Quote__r.CONTAINER_Net_Sales1__c,
                                                    SBQQ__Quote__r.CONTAINER_GrossMargin_w_Warranty1__c,SBQQ__Quote__r.CONTAINER_GrossMargin_w_o_Warranty1__c
                                                FROM SBQQ__QuoteLine__c WHERE SBQQ__Quote__c =:recId] ; 

        for(SBQQ__QuoteLine__c qItemVar : quoteList){


                if(qItemVar.SBQQ__RequiredBy__c == null && qItemVar.SBQQ__OptionLevel__c == null && 
                    qItemVar.SBQQ__Bundle__c == true && qItemVar.NATT_P_N__c != null){
                    listLineItems1.add(new DataWrapper('Bundle1',qItemVar));
                }
                else if('Extended Warranty Bundle'.equalsIgnoreCase(qItemVar.NATT_P_N__c )){
                    listLineItems2.add(new DataWrapper('Bundle2',qItemVar));
                }
                else if(qItemVar.SBQQ__ProductCode__c == 'Reserves Applied Sales'){
                    listLineItems3.add(new DataWrapper('optionProd1Sales',qItemVar));
                }
                else if(qItemVar.SBQQ__ProductCode__c== 'Reserves Applied Cost'){
                    listLineItems4.add(new DataWrapper('optionProd1Service',qItemVar));
                }
                

        } 
        if(quoteList.size() > 0){
            listLineItems5.add(new DataWrapper('blankColumn',quoteList[0]));
            listLineItems5.add(new DataWrapper('blankColumn',quoteList[0]));
            listLineItems5.add(new DataWrapper('ContractPrice',quoteList[0]));
            listLineItems5.add(new DataWrapper('NetSales',quoteList[0]));
            listLineItems5.add(new DataWrapper('GrossMarginwithWarranty',quoteList[0]));
            listLineItems5.add(new DataWrapper('GrossMarginwithOutWarranty',quoteList[0]));
        }
        // Adding all list to main list
        listLineItems.addAll(listLineItems1);
        listLineItems.addAll(listLineItems2);
        listLineItems.addAll(listLineItems3);
        listLineItems.addAll(listLineItems4);
        listLineItems.addAll(listLineItems5);

        return listLineItems;
    }

    //A wrapper class that will be use do display the data of the object
    public class DataWrapper{

        @AuraEnabled public string Product_Description {get;set;} 
        @AuraEnabled public string Net_Unit_Price {get;set;}

        public DataWrapper(String strVal, SBQQ__QuoteLine__c qItemVarRec){

            if(strVal == 'Bundle1'){
                this.Product_Description =  qItemVarRec.SBQQ__Quote__r.CONTAINER_Model_Number__c + ' - ' + qItemVarRec.SBQQ__ProductName__c;
                this.Net_Unit_Price = String.valueOf(qItemVarRec.CONTAINER_List_Price__c);
            }
            else if(strVal == 'Bundle2'){
                this.Product_Description = qItemVarRec.CONTAINER_Customer_Part_number__c ;
                this.Net_Unit_Price = String.valueOf(qItemVarRec.CONTAINER_List_Price__c);
            }
            else if(strVal == 'optionProd1Sales'){
                if(qItemVarRec.CONTAINER_Warranty_Description__c == null){
                    this.Product_Description =  qItemVarRec.SBQQ__ProductName__c;
                    this.Net_Unit_Price = String.valueOf(qItemVarRec.CONTAINER_List_Price__c);
                }else{
                    this.Product_Description =  qItemVarRec.SBQQ__ProductName__c + ' - ' + qItemVarRec.CONTAINER_Warranty_Description__c;
                    this.Net_Unit_Price = String.valueOf(qItemVarRec.CONTAINER_List_Price__c);
                }
            }
            else if(strVal == 'optionProd1Service'){
                if(qItemVarRec.CONTAINER_Warranty_Description__c == null){
                    this.Product_Description =  qItemVarRec.SBQQ__ProductName__c;
                    this.Net_Unit_Price = String.valueOf(qItemVarRec.CONTAINER_List_Price__c);
                }else{
                    this.Product_Description =  qItemVarRec.SBQQ__ProductName__c + ' - ' + qItemVarRec.CONTAINER_Warranty_Description__c;
                    this.Net_Unit_Price = String.valueOf(qItemVarRec.CONTAINER_List_Price__c);
                }
            }else{
                if(strVal == 'blankColumn'){
                    this.Product_Description =  '       ';
                    this.Net_Unit_Price = '   ';
                }
                if(strVal == 'ContractPrice'){
                    this.Product_Description =  'Contract Price';
                    this.Net_Unit_Price = (qItemVarRec.SBQQ__Quote__r.CONTAINER_Cost_Contract_Price__c != null) ? (String.valueOf(qItemVarRec.SBQQ__Quote__r.CONTAINER_Cost_Contract_Price__c)) : '';
                }
                if(strVal == 'NetSales'){
                    this.Product_Description =  'Net Sales';
                    this.Net_Unit_Price = String.valueOf(qItemVarRec.SBQQ__Quote__r.CONTAINER_Net_Sales1__c);
                }
                if(strVal == 'GrossMarginwithWarranty'){
                    this.Product_Description =  'Gross Margin w/ Warranty %';
                    this.Net_Unit_Price = (qItemVarRec.SBQQ__Quote__r.CONTAINER_GrossMargin_w_Warranty1__c != null) ? String.valueOf(qItemVarRec.SBQQ__Quote__r.CONTAINER_GrossMargin_w_Warranty1__c)+ ' %' : '';
                }
                if(strVal == 'GrossMarginwithOutWarranty'){
                    this.Product_Description =  'Gross Margin w/o Warranty %';
                    this.Net_Unit_Price = (qItemVarRec.SBQQ__Quote__r.CONTAINER_GrossMargin_w_o_Warranty1__c != null ) ? String.valueOf(qItemVarRec.SBQQ__Quote__r.CONTAINER_GrossMargin_w_o_Warranty1__c)+ ' %' : '';
                }
            }

            //this.Net_Unit_Price = qItemVarRec.CONTAINER_List_Price__c;
                    
        }
    }
}