NATTQA-ENV/force-app/main/default/objects/NATT_Tracking__mdt/NATT_Tracking__mdt.object-meta.xml
<CustomObject>
    <description>To link company name to URL</description>
    <label>NATT_Tracking</label>
    <pluralLabel>NATT_Tracking</pluralLabel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_Tracking__mdt/fields/NATT_ShippingCompanyURL__c.field-meta.xml
<CustomField>
    <fullName>NATT_ShippingCompanyURL__c</fullName>
    <description>Contains Tracking URL</description>
    <label>NATT_ShippingCompanyURL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Tracking__mdt/fields/ShippingCompanyName__c.field-meta.xml
<CustomField>
    <fullName>ShippingCompanyName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Contains Company names</description>
    <label>ShippingCompanyName</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>NATT_Ship_Date__c</fullName>
    <description>NATT</description>
    <label>Ship Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <description>twin field from quote</description>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Unit</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_Available_Promise_Date__c.field-meta.xml
<CustomField>
    <fullName>NATT_Available_Promise_Date__c</fullName>
    <description>Avalaible to Promis date</description>
    <label>Available Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_Backordered_Quantity__c.field-meta.xml
<CustomField>
    <fullName>NATT_Backordered_Quantity__c</fullName>
    <description>Back Order</description>
    <label>Backordered Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_Order_Line_Status__c.field-meta.xml
<CustomField>
    <fullName>NATT_Order_Line_Status__c</fullName>
    <description>Determines the status of the Product order lines by comparing the shipped quantity against the ordered quantity, and returns the appropriate status message. Charge lines are excluded as these represent fees and other charges that are not shipped to customers.</description>
    <formula>IF( NOT(ISBLANK(NATT_JDEItemStatus__c)), NATT_JDEItemStatus__c,  
IF( TEXT(TypeCode) == &quot;Charge&quot;, &quot;&quot;,
IF( NATT_Shipped_Quantity__c == Quantity,  $Label.NATT_Order_Detail_Shipped ,
IF( NATT_Shipped_Quantity__c == 0,  $Label.NATT_Order_Detail_Not_Shipped ,
IF( NATT_Shipped_Quantity__c &lt; Quantity, $Label.NATT_Order_Detail_Partially_Shipped,
&quot;&quot;
)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Line Status</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_OrderBy__c.field-meta.xml
<CustomField>
    <fullName>NATT_OrderBy__c</fullName>
    <description>Used in the PPG store to set the order by.  This field originally uses the order entered by the customer until JDE returns updated line numbers.</description>
    <formula>if(ISNULL(NATT_OrderLineNumber__c), NATT_CartItemLineNumber__c, NATT_OrderLineNumber__c)</formula>
    <label>Order By</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_OrderLineNumber__c.field-meta.xml
<CustomField>
    <fullName>NATT_OrderLineNumber__c</fullName>
    <description>Field representing the order line number in JDE. Standard salesforce LineNumber field is unusable.</description>
    <label>Order Line Number</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_P_N__c</fullName>
    <description>Has a value if the line item is a Kit. Null if the line item is a part of the unit</description>
    <label>P/N</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_QuantityUOM__c.field-meta.xml
<CustomField>
    <fullName>NATT_QuantityUOM__c</fullName>
    <formula>TEXT(Product2.QuantityUnitOfMeasure)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity Unit of Measure</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>NATT_Ship_Date__c</fullName>
    <description>NATT</description>
    <label>Last Ship Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_Shipped_Quantity__c.field-meta.xml
<CustomField>
    <fullName>NATT_Shipped_Quantity__c</fullName>
    <label>Quantity shipped to date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <formula>Product2.NATT_P_N__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Part Number</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_P_N__c</fullName>
    <description>The Part Number for NATT JDE</description>
    <label>Part Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <description>for quoting NATT Units</description>
    <label>Unit NATT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Unit</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_UOM_Conversion__c.field-meta.xml
<CustomField>
    <fullName>NATT_UOM_Conversion__c</fullName>
    <description>NATT unit of measure conversion factor</description>
    <label>UOM Conversion</label>
    <precision>15</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_BillOfLading__c.field-meta.xml
<CustomField>
    <fullName>NATT_BillOfLading__c</fullName>
    <description>Bill of Lading number for freight shipments</description>
    <label>Bill of Lading #</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_DateShipped__c.field-meta.xml
<CustomField>
    <fullName>NATT_DateShipped__c</fullName>
    <description>Date the shipment was shipped from the warehouse</description>
    <label>Date Shipped</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>NATT_InvoiceNumber__c</fullName>
    <description>Number of the invoice for the shipment</description>
    <label>Invoice Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_Order__c.field-meta.xml
<CustomField>
    <fullName>NATT_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The order to which the shipment is related</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_PackingSlipNumber__c.field-meta.xml
<CustomField>
    <fullName>NATT_PackingSlipNumber__c</fullName>
    <description>Packing slip number of the shipment</description>
    <label>Packing Slip Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_ShippingCompanyName__c.field-meta.xml
<CustomField>
    <fullName>NATT_ShippingCompanyName__c</fullName>
    <description>Name of the company transporting the shipment</description>
    <label>Shipping Company Name</label>
    <length>48</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/ShipmentItem/fields/NATT_Amount__c.field-meta.xml
<CustomField>
    <fullName>NATT_Amount__c</fullName>
    <description>Dollar amount of the shipment item passed by JDE</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/ShipmentItem/fields/NATT_DateShipped__c.field-meta.xml
<CustomField>
    <fullName>NATT_DateShipped__c</fullName>
    <description>Date the order item was shipped</description>
    <label>Date Shipped</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/ShipmentItem/fields/NATT_InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>NATT_InvoiceNumber__c</fullName>
    <description>Number of the invoice on which this shipment item appears</description>
    <label>Invoice Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/ShipmentItem/fields/NATT_OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>NATT_OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product line (i.e. Order Line) on the original order</description>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Shipment Items</relationshipLabel>
    <relationshipName>Shipment_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/ShipmentItem/fields/NATT_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_P_N__c</fullName>
    <formula>NATT_OrderProduct__r.Product2.NATT_P_N__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>P/N</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>200INT ComfortPro Integrated APU</fullName>
    </customValue>
    <customValue>
        <fullName>210STA ComfortPro Stand-alone APU</fullName>
    </customValue>
    <customValue>
        <fullName>220PWR ComfortPro Power-only APU</fullName>
    </customValue>
    <customValue>
        <fullName>230SKY ComfortPro ClearSky DPF APU</fullName>
    </customValue>
    <customValue>
        <fullName>240EPS ComfortPro Electric APU</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S6 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S7 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S8 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S9 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>20X Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>30S Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>30S with 115v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>30S with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>35X Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>35X with 115v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>35X with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>35X with 230v-3ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>40X with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>40XR with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>50X with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>50XR Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>50XR with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>50XR with 230v-3ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>Neos 100S - Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>Solara APX</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8100</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8500</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 01</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 02</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 03</fullName>
    </customValue>
    <description>for quoting in cpq for NATT</description>
    <masterLabel>NATT Unit</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/NATT_orderDetailsController.cls
public without sharing class NATT_orderDetailsController {

    /**
     * Wrapper classs that are used to store Order and Invoice page data.
     */
    public Class OrderWrapper {
        @AuraEnabled public List < OrderItemWrapper > orderItems{get;set;}
        @AuraEnabled public List < Shipment > shipments {get;set;}
        @AuraEnabled public Decimal partTotal {get;set;}
        @AuraEnabled public Decimal freightTotal {get;set;}
        @AuraEnabled public Decimal rushOrderTotal {get;set;}
        @AuraEnabled public Decimal orderTotal {get;set;}
        @AuraEnabled public Decimal partTotalValue {get;set;}
        @AuraEnabled public Decimal freightTotalValue {get;set;}
        @AuraEnabled public Decimal rushOrderTotalValue {get;set;}
        @AuraEnabled public Decimal orderTotalValue {get;set;}
        @AuraEnabled public Decimal shippedTotalValue {get;set;}
        @AuraEnabled public String Id {get;set;}
       // @AuraEnabled public String TrackingNumberNew {get;set;}
        @AuraEnabled public Map<String,String> TrackingNumberNew {get;set;}

    }
    
    public Class OrderItemWrapper {
        @AuraEnabled public String Id {get;set;}
        @AuraEnabled public Decimal lineNum {get;set;}
        @AuraEnabled public String partNum {get;set;}
        @AuraEnabled public String description {get;set;}
        @AuraEnabled public Decimal  ordered {get;set;}
        @AuraEnabled public Decimal  delivered {get;set;}
        @AuraEnabled public Decimal  backOrdered {get;set;}
        @AuraEnabled public Decimal  amount {get;set;}
        @AuraEnabled public String status {get;set;}
        @AuraEnabled public Integer shipments {get;set;}
        @AuraEnabled public Decimal orderLineNum {get;set;}
        @AuraEnabled public Decimal unitPrice {get;set;}
        @AuraEnabled public String unitOfMeasure {get;set;}
        @AuraEnabled public Decimal orderItemPrice {get;set;}
        @AuraEnabled public Decimal orderItemAmount {get;set;}
        @AuraEnabled public Decimal shipmentItemAmount {get;set;}
        @AuraEnabled public String orderItemUOM {get;set;}
        @AuraEnabled public String trackingNumber {get;set;}
        @AuraEnabled public String expectedDelivery {get;set;}
        @AuraEnabled public String shipItemNum {get;set;}
        @AuraEnabled public Decimal rushFeeItem {get;set;}
        @AuraEnabled public String availablePromiseDate {get;set;}
    }
    
     public Class ShipmentItemWrapper {
        @AuraEnabled public String partNum {get;set;}
        @AuraEnabled public String description {get;set;}
        @AuraEnabled public List < ShipmentItem > shipmentItems {get;set;}
    }

    /**
     * Method used to grab data for Order Lines section of Order Details page.
     * Grabs a list of Order Items and populates a OrderItemWrapper.
     * OrderItemWrapper is stored in OrderWrapper, which is cycled through on details page.
     */
    @AuraEnabled(cacheable = true)
    public static OrderWrapper fetchOrderlines(String recordId) {
        List < OrderItemWrapper > orderItemList = new List < OrderItemWrapper >();
        OrderWrapper wrapper = wrapperCreation('Order Total Values');
        
        //method used to grab orderitems (products) for invoice
        List <OrderItem> orderLines = grabOrderItems(recordId);
        
        for(OrderItem oi : orderlines){
            if(oi.TypeCode=='Charge' && oi.Type=='Delivery Charge'){ 
                //Freight Product 
                if(oi.Product2.Name.contains('Freight')){
                    wrapper.freightTotalValue += oi.UnitPrice;
                    wrapper.orderTotalValue += oi.UnitPrice;
                    continue;
                }
                //Rush Fee Product
                if(oi.Product2.Name.contains('Rush Fee') || oi.NATT_OrderLineNumber__c == 990){
                    wrapper.rushOrderTotalValue += oi.UnitPrice;
                    wrapper.orderTotalValue += oi.UnitPrice;
                    continue;
                }
            }
            OrderItemWrapper oItemWrapper = assignOrderItemWrapperFields(oi, wrapper);
            Decimal amountHold = 0;
            orderItemList.add(oItemWrapper);

            //assignments for Totals            
            wrapper.partTotalValue += oItemWrapper.amount;
            wrapper.orderTotalValue += (oItemWrapper.amount);
        }

        //grab order total
        //Order orderInfo = [SELECT TotalAmount FROM Order WHERE Id = :recordId];
        //System.debug('TOTAL AMOUNT: ' + orderInfo.TotalAmount);

        //Query shipment objects for Shipment column in Order Lines
        List < Shipment > shpmnts = [SELECT Id, NATT_InvoiceNumber__c, NATT_PackingSlipNumber__c, NATT_DateShipped__c, NATT_ShippingCompanyName__c,
            TrackingNumber, NATT_BillOfLading__c FROM Shipment WHERE NATT_Order__c =: recordId];
        Map<String, Id> mapShippingcompany = new Map<String, Id>();
        for(Shipment sh : shpmnts){
           mapShippingcompany.put(sh.NATT_ShippingCompanyName__c, sh.Id); 
            }
        system.debug('shpmnts ---- > '+shpmnts);
        List<NATT_Tracking__mdt> lstTrack = new List<NATT_Tracking__mdt>();
        Map<String,String> mapTrack = new Map<String,String>();
        if(mapShippingcompany != null){
            lstTrack = [select NATT_ShippingCompanyURL__c,ShippingCompanyName__c FROM NATT_Tracking__mdt where ShippingCompanyName__c IN: mapShippingcompany.keySet()];
        }   

        for(NATT_Tracking__mdt lst: lstTrack){
            mapTrack.put(lst.ShippingCompanyName__c,lst.NATT_ShippingCompanyURL__c);
        }
           
        wrapper.shipments = shpmnts;
        wrapper.orderItems = orderItemList;
        wrapper.partTotal = (wrapper.partTotalValue);
        wrapper.freightTotal = (wrapper.freightTotalValue);
        wrapper.rushOrderTotal = (wrapper.rushOrderTotalValue);
        //wrapper.orderTotal = (orderInfo.TotalAmount);
        wrapper.orderTotal = wrapper.orderTotalValue;
        if(lstTrack != null && !lstTrack.isempty()){
            wrapper.TrackingNumberNew = mapTrack;
        }
        else {
            wrapper.TrackingNumberNew = null;
        }
        return wrapper;
    }

    /**
     * Method used to grab data for Parts Details section of Invoice page.
     * Grabs a list of Order Items and populates a OrderItemWrapper.
     * OrderItemWrapper is stored in OrderWrapper, which is cycled through on details page.
     */
    @AuraEnabled
    public static OrderWrapper fetchInvoiceInformation(String shipmentId){
        List < OrderItemWrapper > orderItemList = new List < OrderItemWrapper >();
        List <Order> orderList = new List <Order>();
        
        Shipment shipmentInfo = [SELECT Id, NATT_InvoiceNumber__c, NATT_PackingSlipNumber__c, NATT_DateShipped__c, NATT_ShippingCompanyName__c,
                                        TrackingNumber, NATT_BillOfLading__c, NATT_Order__c
                                        FROM Shipment 
                                        WHERE Id = :shipmentId];

        /*List <ShipmentItem> shipmentItemDetail = [SELECT NATT_Amount__c, Quantity, NATT_OrderProduct__c 
                                        FROM ShipmentItem 
                                        WHERE ShipmentId = :shipmentInfo.Id];*/

        OrderWrapper wrapper = wrapperCreation('Invoice Total Values');
        
        //method used to grab orderitems (products) for invoice
        List <OrderItem> orderLines = grabOrderItems(shipmentInfo.NATT_Order__c);
        
        for(OrderItem o : orderlines){
            for(ShipmentItem shipItm : o.Shipment_Items__r){
                if(shipItm.ShipmentId == shipmentInfo.Id ){
                    if(o.TypeCode=='Charge' && o.Type=='Delivery Charge'){
                        //Freight Product for Total
                        if(o.Product2.Name.contains('Freight') ){                            
                            wrapper.freightTotalValue += o.UnitPrice;
                            continue;
                        }
                        //Rush Fee Product for Total
                        if(o.Product2.Name.contains('Rush Fee') || o.NATT_OrderLineNumber__c == 990){                    
                            wrapper.rushOrderTotalValue += o.UnitPrice;
                            continue;
                        }
                    }
                    OrderItemWrapper oItem = assignOrderItemWrapperFields(o, wrapper);
                    Decimal amountHold = 0;
                    
                    //Invoice Specific fields that require shipment item fields
                    oItem.trackingNumber = shipItm.TrackingNumber;
                    if(shipItm.ExpectedDeliveryDate != null){
                        String dateTimeDelivery = shipItm.ExpectedDeliveryDate.format('MM/dd/yyyy');
                        oItem.expectedDelivery = dateTimeDelivery;
                    }
                    oItem.shipItemNum = shipItm.ShipmentItemNumber;
                    
                    orderItemList.add(oItem);   
                    wrapper.partTotalValue += oItem.amount;
                    wrapper.orderTotalValue += (wrapper.rushOrderTotalValue + oItem.amount); //totalamount
                    System.debug('OrderItemValue: ' + oItem);
                }
            }     
        }
        wrapper.orderItems = orderItemList; 
        wrapper.partTotal = (wrapper.partTotalValue);
        wrapper.freightTotal = (wrapper.freightTotalValue);
        wrapper.rushOrderTotal = (wrapper.rushOrderTotalValue);
        wrapper.orderTotal = (wrapper.orderTotalValue);         
        return wrapper;
    }


    /**
     * Method used to assign values to Order Item Wrapper.
     * Assigns values for both Order and Invoice details page.
     */
    private static OrderItemWrapper assignOrderItemWrapperFields(OrderItem oi, OrderWrapper wrapper){
        OrderItemWrapper oItem = new OrderItemWrapper();  
        oItem.Id = oi.Id;
        //Line Number Order
        oItem.lineNum = oi.NATT_OrderBy__c;
        //Line Number Invoice
        oItem.orderLineNum = oi.NATT_OrderBy__c;

        
        oItem.partNum = oi.Part_Number__c;
        oItem.description = oi.Product2.Name;
        oItem.ordered = oi.Quantity;
        oItem.delivered = oi.NATT_Shipped_Quantity__c;
        oItem.backOrdered = oi.NATT_Backordered_Quantity__c;
        oItem.unitOfMeasure = oi.NATT_QuantityUOM__c;
        if(oi.NATT_Available_Promise_Date__c != null){
            String dateTimeDelivery = oi.NATT_Available_Promise_Date__c.format();
            oItem.availablePromiseDate = dateTimeDelivery;
        }else{
            oItem.availablePromiseDate = '-';
        }
        oItem.orderItemAmount = oi.AdjustedLineAmount;//(o.UnitPrice * o.Quantity).setScale(2); //Order Table - Amount | Invoice Table - Extended        
        oItem.orderItemPrice = oi.UnitPrice; //Invoice Table - Price
        oItem.amount = oi.AdjustedLineAmount;//o.UnitPrice * o.Quantity; //Used to calculate total
        oItem.status = oi.NATT_Order_Line_Status__c;
        oItem.shipments = oi.Shipment_Items__r.size();
        oItem.shipmentItemAmount=0;
        oItem.unitPrice = oi.UnitPrice;
        for(ShipmentItem si : oi.Shipment_Items__r){
            oItem.shipmentItemAmount += si.NATT_Amount__c;
        }
        wrapper.shippedTotalValue+=oItem.shipmentItemAmount;
        String conversionHold = null;
        if(oi.Product2.NATT_UOM_Conversion__c != null){
            conversionHold = String.valueOf(oi.Product2.NATT_UOM_Conversion__c.intValue());
        }
       // oItem.orderItemUOM = conversionHold + ' ' + oi.Product2.QuantityUnitOfMeasure;
        oItem.unitOfMeasure = conversionHold + ' ' + oi.Product2.QuantityUnitOfMeasure;
        return oItem;
       
    }

    /**
     * Creates OrderWrapper object for Order and Invoice details page.
     * OrderWrapper used to display the different totals.
     */
    private static OrderWrapper wrapperCreation(String wrapperName){
        OrderWrapper wrapper = new OrderWrapper();
        wrapper.Id = wrapperName;
        wrapper.partTotalValue = 0;
        wrapper.freightTotalValue = 0;
        wrapper.rushOrderTotalValue = 0;
        wrapper.orderTotalValue = 0;
        wrapper.shippedTotalValue=0;
        return wrapper;
    }

    /**
     * Queries List of Products (OrderItems) related to the order.
     */
    // added NATT_QuantityUOM__c field for CXREF-4855
    private static List <OrderItem> grabOrderItems (String orderId){
        List <OrderItem> orderItemList = 
        [SELECT 
        Id, 
        Type, 
        TypeCode,
        UnitPrice, 
        TotalPrice,
        Quantity, 
        NATT_OrderBy__c, 
        NATT_Available_Promise_Date__c, 
        NATT_Shipped_Quantity__c,
        NATT_Backordered_Quantity__c, 
        NATT_OrderLineNumber__c,
        NATT_Order_Line_Status__c,
        NATT_Ship_Date__c,
        Part_Number__c,
        Product2.Id,
        Product2.NATT_P_N__c, 
        Product2.Name, 
        Product2.NATT_UOM_Conversion__c,
        Product2.NATT_Unit__c, 
        Product2.QuantityUnitOfMeasure,
        AdjustedLineAmount,
        NATT_QuantityUOM__c,
                (SELECT 
                    Id, 
                    ShipmentId,
                    Quantity,
                    TrackingNumber, 
                    ExpectedDeliveryDate, 
                    ShipmentItemNumber,
                    NATT_OrderProduct__r.NATT_Shipped_Quantity__c,
                    NATT_OrderProduct__r.Quantity,
                    NATT_Amount__c,
                    Product2.NATT_P_N__c, 
                    Product2.Name, 
                    Product2.NATT_Unit__c,
                    Product2.NATT_UOM_Conversion__c,
                    Shipment.NATT_InvoiceNumber__c, 
                    Shipment.NATT_DateShipped__c, 
                    Shipment.NATT_PackingSlipNumber__c,
                    Shipment.TrackingNumber,
                    Shipment.NATT_BillOfLading__c
                FROM Shipment_Items__r)
            FROM OrderItem 
            WHERE OrderID =:orderId 
            ORDER BY NATT_OrderBy__c];
            system.debug('Orderline list---->' +orderItemList);

        return orderItemList;
    }
    
    /**
     * Grabs individual items for each shipment when shipment is clicked on in Order Line table
     */
    @AuraEnabled
    public static ShipmentItemWrapper fetchShipmentItems(String recordId) {
        ShipmentItemWrapper warpper = new ShipmentItemWrapper();
        OrderItem orderline = [SELECT Id, Product2.NATT_P_N__c, Product2.Name, (Select Id, Shipment.NATT_DateShipped__c, Shipment.NATT_InvoiceNumber__c,
            NATT_OrderProduct__r.Quantity, Quantity, NATT_Amount__c, Shipment.NATT_PackingSlipNumber__c, Shipment.TrackingNumber,Shipment.NATT_ShippingCompanyName__c,
            Shipment.NATT_BillOfLading__c from Shipment_Items__r) FROM OrderItem WHERE Id  =: recordId];
        warpper.partNum = orderline.Product2.NATT_P_N__c;
        warpper.description = orderline.Product2.Name;
        warpper.shipmentItems = orderline.Shipment_Items__r;
        system.debug(orderline.Shipment_Items__r[0].Shipment.NATT_DateShipped__c);
        System.debug('Shipment Wrapper: ' + warpper);
        return warpper;
    }
    
    /**
     * Grabs Shipments to be displayed in Order Lines table
     * 
     
    @AuraEnabled
    public static List < Shipment > fetchShipments(String recordId) {
        List < Shipment > shpmnts = [Select Id, NATT_InvoiceNumber__c, NATT_PackingSlipNumber__c, NATT_DateShipped__c, NATT_ShippingCompanyName__c,
            TrackingNumber, NATT_BillOfLading__c from Shipment where NATT_Order__c =: recordId ORDER BY NATT_InvoiceNumber__c];
            
        return shpmnts;
    }*/


}