NATTQA-ENV/force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/Knowledge__kav/fields/NATT_eFlash__c.field-meta.xml
<CustomField>
    <fullName>NATT_eFlash__c</fullName>
    <defaultValue>false</defaultValue>
    <label>eFlash</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Knowledge__kav/fields/NATT_General_Bulletin__c.field-meta.xml
<CustomField>
    <fullName>NATT_General_Bulletin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>General Bulletin</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Knowledge__kav/fields/NATT_Parts_Bulletin__c.field-meta.xml
<CustomField>
    <fullName>NATT_Parts_Bulletin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Parts Bulletin</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Knowledge__kav/fields/NATT_Product_Manual_Updates__c.field-meta.xml
<CustomField>
    <fullName>NATT_Product_Manual_Updates__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Product Manual Updates</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Knowledge__kav/fields/NATT_Service_Bulletin__c.field-meta.xml
<CustomField>
    <fullName>NATT_Service_Bulletin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Service Bulletin</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Knowledge__kav/fields/NATT_Training_Bulletin__c.field-meta.xml
<CustomField>
    <fullName>NATT_Training_Bulletin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Training Bulletin</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Knowledge__kav/fields/UCP_Region__c.field-meta.xml
<CustomField>
    <fullName>UCP_Region__c</fullName>
    <label>UCP Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>AUS</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>SG/HK</fullName>
            </value>
            <value>
                <fullName>UCP (Global)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Knowledge__kav/fields/UCP_Software_Release__c.field-meta.xml
<CustomField>
    <fullName>UCP_Software_Release__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Software Release</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Knowledge__kav/recordTypes/CONTAINER.recordType-meta.xml
<RecordType>
    <fullName>CONTAINER</fullName>
    <active>true</active>
    <description>This can be used for CONTAINER related Articles.</description>
    <label>CONTAINER</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/User/fields/UCP_Region__c.field-meta.xml
<CustomField>
    <fullName>UCP_Region__c</fullName>
    <label>UCP Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>AUS</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>SG/HK</fullName>
            </value>
            <value>
                <fullName>UCP (Global)</fullName>
                <isActive>false</isActive>
                <label>UCP (Global)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/UCP_ArticleCarouselRecentlyController.cls
public without sharing class UCP_ArticleCarouselRecentlyController {
    
    @AuraEnabled
    public static Map<String, Object> getRecentlyModifiedArticles() {
        List<Knowledge> ltKnowledge = new List<UCP_ArticleCarouselRecentlyController.Knowledge>();
        Map<String, Object> mpReturn = new Map<String, Object>{'success' => true, 'message' => '', 'isAccessible' => true};
        String status = 'Online';

        try {

            if (!NATT_Utils.isAccessible('Knowledge__kav')) {
                mpReturn.put('isAccessible', false);
                throw new AuraHandledException('Not able to access this content.');
            }
			User objUser = [SELECT Id,Name,UCP_Region__c FROM User WHERE Id =:UserInfo.getUserId()];
            for (Knowledge__kav knowledge : [SELECT Id, Title, Summary, CreatedDate, LastPublishedDate, UrlName, NATT_General_Bulletin__c, NATT_Parts_Bulletin__c, NATT_Service_Bulletin__c, NATT_Training_Bulletin__c, 
                                             NATT_Product_Manual_Updates__c, NATT_eFlash__c,UCP_Software_Release__c 
                                             FROM Knowledge__kav WHERE PublishStatus = :status 
                                             AND RecordType.Name = 'UCP Container'
                                             AND (UCP_Region__c	 = 'UCP (Global)' OR UCP_Region__c	 =: objUser.UCP_Region__c)
                                             AND (NATT_General_Bulletin__c = TRUE OR NATT_Parts_Bulletin__c = TRUE OR NATT_Service_Bulletin__c = TRUE OR 
                                                                                                    NATT_Training_Bulletin__c = TRUE OR NATT_Product_Manual_Updates__c = TRUE OR NATT_eFlash__c = TRUE OR UCP_Software_Release__c = TRUE) ORDER BY LastModifiedDate DESC LIMIT 15]) {
                
                                                                                                        
                Knowledge knowledgeObj = new Knowledge();
                
                String assetName = getKwnowledgeCategorization(knowledge.NATT_General_Bulletin__c, knowledge.NATT_Parts_Bulletin__c, knowledge.NATT_Service_Bulletin__c, knowledge.NATT_Training_Bulletin__c, knowledge.NATT_Product_Manual_Updates__c, knowledge.NATT_eFlash__c,knowledge.UCP_Software_Release__c);
                                                                                                        
                                                                                                        
                knowledgeObj.id = knowledge.Id;
                knowledgeObj.title = knowledge.Title;
                knowledgeObj.summary = knowledge.Summary;
                knowledgeObj.url = 'article/' + knowledge.UrlName;
                knowledgeObj.publishedDate = knowledge.LastPublishedDate.format('MMMM dd, yyyy');
                knowledgeObj.image = assetName;
                knowledgeObj.iconType = assetName;
                ltKnowledge.add(knowledgeObj);
            }
	
            mpReturn.put('data', ltKnowledge);
            
            List<Knowledge__kav> knowledge = [SELECT Id FROM Knowledge__kav];
            
			if (Test.isRunningTest() && NATT_Utils.isError ) { throw new NATT_Utils.TestException('Error'); }
        } catch (Exception e) {
            mpReturn.put('success', false);   
            system.debug('message'+e.getMessage());
            mpReturn.put('message', e.getMessage());
        }
        

        return mpReturn;
    }

    private static String getKwnowledgeCategorization(Boolean general, Boolean parts, Boolean service, Boolean training, Boolean product, Boolean eFlash,Boolean softwareRelease) {
        String category = '';

        if (general) {
            category = 'NATT_general_bulletin';
        } else if (parts) {
            category = 'NATT_parts_bulletin';            
        } else if (service) {
            category = 'NATT_service_bulletin';            
        } else if (training) {
            category = 'NATT_training_bulletin';            
        } else if (product) {
            category = 'NATT_product_manual_updates';            
        }  else if(softwareRelease){
            category = 'UCP_Software_Release__c' ;
        }
        else{
            category = 'NATT_eflash';
        }

        return category;
    }

    // wrapper class
    public class Knowledge {
        @AuraEnabled public Id id;
        @AuraEnabled public String title;
        @AuraEnabled public String summary;
        @AuraEnabled public String type;
        @AuraEnabled public String url;
        @AuraEnabled public String publishedDate;
        @AuraEnabled public String image = '';
        @AuraEnabled public String iconType = '';
        
    }

}