NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>NATT_Account_Name__c</fullName>
    <formula>Account.Name</formula>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>NATT_Contact_Email__c</fullName>
    <description>email of contact for B2B order (no contact object record stored)</description>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>NATT_Contact_Name__c</fullName>
    <description>name of contact for B2B order (no contact object record stored)</description>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>NATT_Contact_Phone__c</fullName>
    <label>Contact Phone</label>
    <type>Phone</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_CustomerBilltoCode__c.field-meta.xml
<CustomField>
    <fullName>NATT_CustomerBilltoCode__c</fullName>
    <formula>Account.NATT_JDE_Parts_Bill_To_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer #</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_CustomerName__c.field-meta.xml
<CustomField>
    <fullName>NATT_CustomerName__c</fullName>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Freight_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>NATT_Freight_Account_Number__c</fullName>
    <description>Customer&apos;s freight account number if using Bill To Customer Delivery Term.</description>
    <label>Freight Account Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_JDE_Sales_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>NATT_JDE_Sales_Order_Number__c</fullName>
    <description>NATT</description>
    <externalId>true</externalId>
    <label>JDE Sales Order #</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_JdeOrderTypeName__c.field-meta.xml
<CustomField>
    <fullName>NATT_JdeOrderTypeName__c</fullName>
    <formula>IF(NATT_JdeOrderType__c == &apos;&apos;,&apos;&apos;,
IF(CONTAINS(NATT_JdeOrderType__c,&apos;1&apos;),&apos;Unit Down&apos;,
IF(CONTAINS(NATT_JdeOrderType__c,&apos;2&apos;),&apos;Same Day&apos;,
IF(CONTAINS(NATT_JdeOrderType__c,&apos;4&apos;),&apos;Stock&apos;,
IF(CONTAINS(NATT_JdeOrderType__c,&apos;C&apos;),&apos;Credit&apos;,
IF(CONTAINS(NATT_JdeOrderType__c,&apos;Y&apos;),&apos;Annual Return&apos;,&apos;&apos;))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Type</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Payment_Instruction__c.field-meta.xml
<CustomField>
    <fullName>NATT_Payment_Instruction__c</fullName>
    <label>Payment Instruction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Wire Transfer</fullName>
            </value>
            <value>
                <fullName>Terms</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>NATT_Purchase_Order__c</fullName>
    <description>NATT</description>
    <label>PO #</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>NATT_Ship_Date__c</fullName>
    <description>NATT</description>
    <label>Ship Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Shipment_Method__c.field-meta.xml
<CustomField>
    <fullName>NATT_Shipment_Method__c</fullName>
    <description>NATT</description>
    <label>Shipment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Shipment_Method</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Shipment_Terms__c.field-meta.xml
<CustomField>
    <fullName>NATT_Shipment_Terms__c</fullName>
    <description>NATT</description>
    <label>Shipment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Shipment_Terms</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <description>twin field from quote</description>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Unit</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>NATT_Warehouse__c</fullName>
    <description>The Warehouse, or Depot, from which the order is shipping.</description>
    <label>Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Warehouse_Picklist</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_Available_Promise_Date__c.field-meta.xml
<CustomField>
    <fullName>NATT_Available_Promise_Date__c</fullName>
    <description>Avalaible to Promis date</description>
    <label>Available Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_Backordered_Quantity__c.field-meta.xml
<CustomField>
    <fullName>NATT_Backordered_Quantity__c</fullName>
    <description>Back Order</description>
    <label>Backordered Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_Order_Line_Status__c.field-meta.xml
<CustomField>
    <fullName>NATT_Order_Line_Status__c</fullName>
    <description>Determines the status of the Product order lines by comparing the shipped quantity against the ordered quantity, and returns the appropriate status message. Charge lines are excluded as these represent fees and other charges that are not shipped to customers.</description>
    <formula>IF( NOT(ISBLANK(NATT_JDEItemStatus__c)), NATT_JDEItemStatus__c,  
IF( TEXT(TypeCode) == &quot;Charge&quot;, &quot;&quot;,
IF( NATT_Shipped_Quantity__c == Quantity,  $Label.NATT_Order_Detail_Shipped ,
IF( NATT_Shipped_Quantity__c == 0,  $Label.NATT_Order_Detail_Not_Shipped ,
IF( NATT_Shipped_Quantity__c &lt; Quantity, $Label.NATT_Order_Detail_Partially_Shipped,
&quot;&quot;
)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Line Status</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_OrderLineNumber__c.field-meta.xml
<CustomField>
    <fullName>NATT_OrderLineNumber__c</fullName>
    <description>Field representing the order line number in JDE. Standard salesforce LineNumber field is unusable.</description>
    <label>Order Line Number</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_P_N__c</fullName>
    <description>Has a value if the line item is a Kit. Null if the line item is a part of the unit</description>
    <label>P/N</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>NATT_Ship_Date__c</fullName>
    <description>NATT</description>
    <label>Last Ship Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_Shipped_Quantity__c.field-meta.xml
<CustomField>
    <fullName>NATT_Shipped_Quantity__c</fullName>
    <label>Quantity shipped to date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>NATT_Warehouse__c</fullName>
    <description>Warehouse identifier from order header.</description>
    <formula>TEXT(Order.NATT_Warehouse__c)</formula>
    <label>Warehouse</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <formula>Product2.NATT_P_N__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Part Number</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_P_N__c</fullName>
    <description>The Part Number for NATT JDE</description>
    <label>Part Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <description>for quoting NATT Units</description>
    <label>Unit NATT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Unit</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_UOM_Conversion__c.field-meta.xml
<CustomField>
    <fullName>NATT_UOM_Conversion__c</fullName>
    <description>NATT unit of measure conversion factor</description>
    <label>UOM Conversion</label>
    <precision>15</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_BillOfLading__c.field-meta.xml
<CustomField>
    <fullName>NATT_BillOfLading__c</fullName>
    <description>Bill of Lading number for freight shipments</description>
    <label>Bill of Lading #</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_DateShipped__c.field-meta.xml
<CustomField>
    <fullName>NATT_DateShipped__c</fullName>
    <description>Date the shipment was shipped from the warehouse</description>
    <label>Date Shipped</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_InvoiceDate__c</fullName>
    <description>Date the invoice was generated</description>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>NATT_InvoiceNumber__c</fullName>
    <description>Number of the invoice for the shipment</description>
    <label>Invoice Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_JDE_Sales_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>NATT_JDE_Sales_Order_Number__c</fullName>
    <formula>NATT_Order__r.NATT_JDE_Sales_Order_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>JDE Sales Order Number</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_Order__c.field-meta.xml
<CustomField>
    <fullName>NATT_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The order to which the shipment is related</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_PackingSlipNumber__c.field-meta.xml
<CustomField>
    <fullName>NATT_PackingSlipNumber__c</fullName>
    <description>Packing slip number of the shipment</description>
    <label>Packing Slip Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_Payment_Captured__c.field-meta.xml
<CustomField>
    <fullName>NATT_Payment_Captured__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox used in TES to indicate if the payment has been captured.</description>
    <label>Payment Captured</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_ShippingCompanyName__c.field-meta.xml
<CustomField>
    <fullName>NATT_ShippingCompanyName__c</fullName>
    <description>Name of the company transporting the shipment</description>
    <label>Shipping Company Name</label>
    <length>48</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/ShipmentItem/fields/NATT_Amount__c.field-meta.xml
<CustomField>
    <fullName>NATT_Amount__c</fullName>
    <description>Dollar amount of the shipment item passed by JDE</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/ShipmentItem/fields/NATT_DateShipped__c.field-meta.xml
<CustomField>
    <fullName>NATT_DateShipped__c</fullName>
    <description>Date the order item was shipped</description>
    <label>Date Shipped</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/ShipmentItem/fields/NATT_InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>NATT_InvoiceNumber__c</fullName>
    <description>Number of the invoice on which this shipment item appears</description>
    <label>Invoice Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/ShipmentItem/fields/NATT_OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>NATT_OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product line (i.e. Order Line) on the original order</description>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Shipment Items</relationshipLabel>
    <relationshipName>Shipment_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/ShipmentItem/fields/NATT_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_P_N__c</fullName>
    <formula>NATT_OrderProduct__r.Product2.NATT_P_N__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>P/N</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Shipment_Method.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>9</fullName>
        <label>Customer Pickup</label>
    </customValue>
    <customValue>
        <fullName>OTH</fullName>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>BW1</fullName>
        <label>Bestway</label>
    </customValue>
    <customValue>
        <fullName>CR1</fullName>
        <label>Customer Routing</label>
    </customValue>
    <customValue>
        <fullName>FX1</fullName>
        <label>Fedex - Next Day Air</label>
    </customValue>
    <customValue>
        <fullName>FX2</fullName>
        <label>Fedex - 2nd Day Air</label>
    </customValue>
    <customValue>
        <fullName>FX3</fullName>
        <label>Fedex - 3rd Day Air</label>
    </customValue>
    <customValue>
        <fullName>FXG</fullName>
        <label>Fedex - Ground</label>
    </customValue>
    <customValue>
        <fullName>FXX</fullName>
        <label>Fedex - Saturday Delivery</label>
    </customValue>
    <customValue>
        <fullName>OF</fullName>
        <label>Ocean Freight</label>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
        <label>Air Freight</label>
    </customValue>
    <customValue>
        <fullName>ABF</fullName>
    </customValue>
    <customValue>
        <fullName>BW</fullName>
        <label>Best Way</label>
    </customValue>
    <customValue>
        <fullName>FX6</fullName>
    </customValue>
    <customValue>
        <fullName>FX7</fullName>
    </customValue>
    <customValue>
        <fullName>OCN</fullName>
    </customValue>
    <customValue>
        <fullName>WCL</fullName>
    </customValue>
    <customValue>
        <fullName>LTL</fullName>
    </customValue>
    <customValue>
        <fullName>UP1</fullName>
        <label>UPS NEXT DAY</label>
    </customValue>
    <customValue>
        <fullName>UP2</fullName>
    </customValue>
    <customValue>
        <fullName>UP3</fullName>
    </customValue>
    <customValue>
        <fullName>UPG</fullName>
        <label>UPS GROUND</label>
    </customValue>
    <customValue>
        <fullName>UPX</fullName>
    </customValue>
    <customValue>
        <fullName>CPU</fullName>
        <label>Customer Pickup()</label>
    </customValue>
    <customValue>
        <fullName>AF1</fullName>
        <label>Air Freight()</label>
    </customValue>
    <customValue>
        <fullName>EI1</fullName>
        <label>EXPEDITORS INTERNATIONAL</label>
    </customValue>
    <customValue>
        <fullName>PKU</fullName>
        <label>PICKUP</label>
    </customValue>
    <customValue>
        <fullName>NDA</fullName>
        <label>NEXT DAY AIR</label>
    </customValue>
    <customValue>
        <fullName>OF1</fullName>
        <label>Ocean Freight()</label>
    </customValue>
    <customValue>
        <fullName>FCA</fullName>
    </customValue>
    <masterLabel>NATT Shipment Method</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Shipment_Terms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BIL</fullName>
        <label>Bill to Customer</label>
    </customValue>
    <customValue>
        <fullName>PPD</fullName>
        <label>Prepaid Freight</label>
    </customValue>
    <customValue>
        <fullName>COL</fullName>
        <label>Collect</label>
    </customValue>
    <customValue>
        <fullName>CPU</fullName>
        <label>Customer Pickup</label>
    </customValue>
    <customValue>
        <fullName>PPA</fullName>
        <label>Prepaid and Allowed</label>
    </customValue>
    <customValue>
        <fullName>PPB</fullName>
        <label>Prepaid and Billed</label>
    </customValue>
    <customValue>
        <fullName>EXW</fullName>
        <label>EXW - EX Works</label>
    </customValue>
    <customValue>
        <fullName>CIF</fullName>
    </customValue>
    <customValue>
        <fullName>DDP</fullName>
    </customValue>
    <customValue>
        <fullName>FOB</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>999</fullName>
    </customValue>
    <customValue>
        <fullName>AAA</fullName>
    </customValue>
    <customValue>
        <fullName>ABF</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AF1</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AVE</fullName>
    </customValue>
    <customValue>
        <fullName>BCB</fullName>
    </customValue>
    <customValue>
        <fullName>BW</fullName>
    </customValue>
    <customValue>
        <fullName>BW1</fullName>
    </customValue>
    <customValue>
        <fullName>CAR</fullName>
    </customValue>
    <masterLabel>Shipment Terms</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>200INT ComfortPro Integrated APU</fullName>
    </customValue>
    <customValue>
        <fullName>210STA ComfortPro Stand-alone APU</fullName>
    </customValue>
    <customValue>
        <fullName>220PWR ComfortPro Power-only APU</fullName>
    </customValue>
    <customValue>
        <fullName>230SKY ComfortPro ClearSky DPF APU</fullName>
    </customValue>
    <customValue>
        <fullName>240EPS ComfortPro Electric APU</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S6 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S7 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S8 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S9 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>20X Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>30S Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>30S with 115v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>30S with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>35X Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>35X with 115v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>35X with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>35X with 230v-3ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>40X with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>40XR with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>50X with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>50XR Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>50XR with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>50XR with 230v-3ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>Neos 100S - Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>Solara APX</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8100</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8500</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 01</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 02</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 03</fullName>
    </customValue>
    <description>for quoting in cpq for NATT</description>
    <masterLabel>NATT Unit</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Warehouse_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ANA</fullName>
    </customValue>
    <customValue>
        <fullName>BNA</fullName>
    </customValue>
    <customValue>
        <fullName>CHI</fullName>
    </customValue>
    <customValue>
        <fullName>PAN</fullName>
    </customValue>
    <customValue>
        <fullName>ATL</fullName>
    </customValue>
    <customValue>
        <fullName>MEX</fullName>
    </customValue>
    <customValue>
        <fullName>MIA</fullName>
    </customValue>
    <customValue>
        <fullName>TES</fullName>
    </customValue>
    <customValue>
        <fullName>LATAM</fullName>
    </customValue>
    <customValue>
        <fullName>CTB01</fullName>
    </customValue>
    <masterLabel>NATT Warehouse Picklist</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/NATT_TesOrderDetailsCon.cls
/** screens
 * Grabs Order Items for Order, Invoice/Shipments, Print View screens 
 */
public with sharing class NATT_TesOrderDetailsCon {
    /**
     * Wrapper classs that are used to store Order and Invoice page data.
     */
    public Class OrderWrapper {
        @AuraEnabled public List < OrderItemWrapper > orderItems{get;set;}
        @AuraEnabled public List < Shipment > shipments {get;set;}
        @AuraEnabled public Decimal partTotal {get;set;}
        @AuraEnabled public Decimal taxTotal {get;set;}
        @AuraEnabled public Decimal freightTotal {get;set;}
        @AuraEnabled public Decimal rushOrderTotal {get;set;}
        @AuraEnabled public Decimal orderTotal {get;set;}
        @AuraEnabled public Decimal partTotalValue {get;set;}
        @AuraEnabled public Decimal freightTotalValue {get;set;}
        @AuraEnabled public Decimal rushOrderTotalValue {get;set;}
        @AuraEnabled public Decimal orderTotalValue {get;set;}
        @AuraEnabled public Decimal shippedTotalValue {get;set;}
        @AuraEnabled public String Id {get;set;}
    }
    
    public Class OrderItemWrapper {
        @AuraEnabled public String Id {get;set;}
        @AuraEnabled public Decimal lineNum {get;set;}
        @AuraEnabled public String partNum {get;set;}
        @AuraEnabled public String description {get;set;}
        @AuraEnabled public Decimal  ordered {get;set;}
        @AuraEnabled public Decimal  delivered {get;set;}
        @AuraEnabled public Decimal  backOrdered {get;set;}
        @AuraEnabled public Decimal  amount {get;set;}
        @AuraEnabled public String status {get;set;}
        @AuraEnabled public Integer shipments {get;set;}
        @AuraEnabled public Decimal orderLineNum {get;set;}
        @AuraEnabled public Decimal unitPrice {get;set;}
        @AuraEnabled public Decimal orderItemPrice {get;set;}
        @AuraEnabled public Decimal orderItemAmount {get;set;}
        @AuraEnabled public Decimal shipmentItemAmount {get;set;}
        @AuraEnabled public String orderItemUOM {get;set;}
        @AuraEnabled public String trackingNumber {get;set;}
        @AuraEnabled public String expectedDelivery {get;set;}
        @AuraEnabled public String shipItemNum {get;set;}
        @AuraEnabled public Decimal rushFeeItem {get;set;}
        @AuraEnabled public String availablePromiseDate {get;set;}
    }
    /**
     * Method used to grab data for Order Lines section of Order Details page.
     * Grabs a list of Order Items and populates a OrderItemWrapper.
     * OrderItemWrapper is stored in OrderWrapper, which is cycled through on details page.
     */
    @AuraEnabled(cacheable = true)
    public static OrderWrapper fetchOrderlines(String recordId) {
        System.debug('Fetch Order Lines: ' + recordId);
        List < OrderItemWrapper > orderItemList = new List < OrderItemWrapper >();
        OrderWrapper wrapper = wrapperCreation('Order Total Values');
        
        //method used to grab orderitems (products) for invoice
        List <OrderItem> orderLines = grabOrderItems(recordId);
        
        for(OrderItem oi : orderlines){
            if(oi.TypeCode=='Charge' && oi.Type=='Delivery Charge'){ 
                //Freight Product 
                if(oi.Product2.Name.contains('FREIGHT')){
                    wrapper.freightTotalValue += oi.UnitPrice;
                    wrapper.orderTotalValue += oi.UnitPrice;
                    continue;
                }
                //Rush Fee Product
                if(oi.Product2.Name.contains('Rush Fee') || oi.NATT_OrderLineNumber__c == 990){
                    wrapper.rushOrderTotalValue += oi.UnitPrice;
                    wrapper.orderTotalValue += oi.UnitPrice;
                    continue;
                }
            }
            OrderItemWrapper oItemWrapper = assignOrderItemWrapperFields(oi, wrapper);
            Decimal amountHold = 0;
            orderItemList.add(oItemWrapper);

            //assignments for Totals            
            wrapper.partTotalValue += oItemWrapper.amount;
            wrapper.orderTotalValue += (oItemWrapper.amount);
        }

        //grab order total
        //Order orderInfo = [SELECT TotalAmount FROM Order WHERE Id = :recordId];
        //System.debug('TOTAL AMOUNT: ' + orderInfo.TotalAmount);

        //Query shipment objects for Shipment column in Order Lines
        List < Shipment > shpmnts = [SELECT Id, NATT_InvoiceNumber__c, NATT_PackingSlipNumber__c, NATT_DateShipped__c, NATT_ShippingCompanyName__c,
            TrackingNumber, NATT_BillOfLading__c FROM Shipment WHERE NATT_Order__c =: recordId];
            
        wrapper.shipments = shpmnts;
        wrapper.orderItems = orderItemList;
        wrapper.partTotal = (wrapper.partTotalValue);
        wrapper.freightTotal = (wrapper.freightTotalValue);
        wrapper.rushOrderTotal = (wrapper.rushOrderTotalValue);
        //wrapper.orderTotal = (orderInfo.TotalAmount);
        wrapper.orderTotal = wrapper.orderTotalValue;
       
        return wrapper;
    }

    /**
     * Creates OrderWrapper object for Order and Invoice details page.
     * OrderWrapper used to display the different totals.
     */
    private static OrderWrapper wrapperCreation(String wrapperName){
        OrderWrapper wrapper = new OrderWrapper();
        wrapper.Id = wrapperName;
        wrapper.partTotalValue = 0;
        wrapper.freightTotalValue = 0;
        wrapper.rushOrderTotalValue = 0;
        wrapper.orderTotalValue = 0;
        wrapper.shippedTotalValue=0;
        return wrapper;
    }

     /**
     * Method used to assign values to Order Item Wrapper.
     * Assigns values for both Order and Invoice details page.
     */
    private static OrderItemWrapper assignOrderItemWrapperFields(OrderItem oi, OrderWrapper wrapper){
        OrderItemWrapper oItem = new OrderItemWrapper();  
        oItem.Id = oi.Id;
        //Line Number Order
        oItem.lineNum = oi.NATT_OrderLineNumber__c;
        //Line Number Invoice
        oItem.orderLineNum = oi.NATT_OrderLineNumber__c;

        
        oItem.partNum = oi.Part_Number__c;
        System.debug('Product Name: ' + oItem.description);
        oItem.description = oi.Product2.Name;
        oItem.ordered = oi.Quantity;
        oItem.delivered = oi.NATT_Shipped_Quantity__c;
        oItem.backOrdered = oi.NATT_Backordered_Quantity__c;
        if(oi.NATT_Available_Promise_Date__c != null){
            String dateTimeDelivery = oi.NATT_Available_Promise_Date__c.format();
            oItem.availablePromiseDate = dateTimeDelivery;
        }else{
            oItem.availablePromiseDate = '-';
        }
        oItem.orderItemAmount = oi.AdjustedLineAmount;//(o.UnitPrice * o.Quantity).setScale(2); //Order Table - Amount | Invoice Table - Extended        
        oItem.orderItemPrice = oi.UnitPrice; //Invoice Table - Price
        oItem.amount = oi.AdjustedLineAmount;//o.UnitPrice * o.Quantity; //Used to calculate total
        oItem.status = oi.NATT_Order_Line_Status__c;
        oItem.shipments = oi.Shipment_Items__r.size();
        oItem.shipmentItemAmount=0;
        oItem.unitPrice = oi.UnitPrice;
        for(ShipmentItem si : oi.Shipment_Items__r){
            oItem.shipmentItemAmount += si.NATT_Amount__c;
        }
        wrapper.shippedTotalValue+=oItem.shipmentItemAmount;
        String conversionHold = null;
        if(oi.Product2.NATT_UOM_Conversion__c != null){
            conversionHold = String.valueOf(oi.Product2.NATT_UOM_Conversion__c.intValue());
        }
        oItem.orderItemUOM = conversionHold + ' ' + oi.Product2.QuantityUnitOfMeasure;
        
        return oItem;
    }


    @AuraEnabled(cacheable = true)
    public static List <OrderItem> grabOrderItems (String orderId){
        List <OrderItem> orderItemList = 
            [SELECT 
                Id, 
                Type, 
                TypeCode,
                UnitPrice, 
                TotalPrice,
                Quantity, 
                NATT_OrderLineNumber__c, 
                NATT_Available_Promise_Date__c, 
                NATT_Shipped_Quantity__c,
                NATT_Backordered_Quantity__c, 
                NATT_Order_Line_Status__c,
                NATT_Ship_Date__c,
                Part_Number__c,
                Product2.Id,
                Product2.NATT_P_N__c, 
                Product2.Name, 
                Product2.NATT_UOM_Conversion__c,
                Product2.NATT_Unit__c, 
                Product2.QuantityUnitOfMeasure,
                AdjustedLineAmount,
                (SELECT 
                    Id, 
                    ShipmentId,
                    Quantity,
                    TrackingNumber, 
                    ExpectedDeliveryDate, 
                    ShipmentItemNumber,
                    NATT_OrderProduct__r.NATT_Shipped_Quantity__c,
                    NATT_OrderProduct__r.Quantity,
                    NATT_Amount__c,
                    Product2.NATT_P_N__c, 
                    Product2.Name, 
                    Product2.NATT_Unit__c,
                    Product2.NATT_UOM_Conversion__c,
                    Shipment.NATT_InvoiceNumber__c, 
                    Shipment.NATT_DateShipped__c, 
                    Shipment.NATT_PackingSlipNumber__c,
                    Shipment.TrackingNumber,
                    Shipment.NATT_BillOfLading__c
                FROM Shipment_Items__r)
            FROM OrderItem 
            WHERE OrderID =:orderId 
            ORDER BY NATT_OrderLineNumber__c];
        return orderItemList;
    }

    @AuraEnabled(cacheable = true)
    public static Order grabOrder (String orderId){
        return [SELECT Id, 
        OrderNumber,
        TotalAdjustedDeliveryAmount,
        TotalTaxAmount,
        TotalProductAdjDistAmount, 
        GrandTotalAmount,
        NATT_CustomerName__c,
        NATT_Contact_Name__c,
        NATT_CustomerBilltoCode__c,
        shippingStreet,
        shippingCity,
        shippingCountry,
        shippingState,
        shippingPostalCode,
        NATT_Payment_Instruction__c
        FROM Order
        WHERE ID = :orderId];
    }

    // @AuraEnabled(cacheable = true)
    // public static List <Shipment> getShipment(String orderId){
    //     try {
    //         List <Shipment> s = 
    //          [SELECT Id,NATT_Order__c,NATT_Order__r.NATT_CustomerName__c,NATT_Order__r.NATT_Contact_Name__c,
    //         NATT_Order__r.NATT_CustomerBilltoCode__c,NATT_Order__r.NATT_Contact_Email__c,NATT_Order__r.NATT_Purchase_Order__c,
    //         NATT_Order__r.NATT_Contact_Phone__c,NATT_Order__r.NATT_JDE_Sales_Order_Number__c,NATT_Order__r.OrderedDate,
    //         NATT_Order__r.NATT_JdeOrderTypeName__c,NATT_Order__r.NATT_Warehouse__c,toLabel(NATT_Order__r.NATT_Shipment_Method__c),
    //         NATT_Order__r.ShippingAddress,NATT_Order__r.BillingAddress,toLabel(NATT_Order__r.NATT_Shipment_Terms__c),
    //         NATT_Order__r.NATT_Freight_Account_Number__c,NATT_PackingSlipNumber__c,NATT_ShippingCompanyName__c,NATT_BillOfLading__c,
    //         NATT_InvoiceDate__c,TrackingNumber,
    //         ExpectedDeliveryDate,NATT_InvoiceNumber__c,NATT_Order__r.OrderNumber,NATT_DateShipped__c,NATT_Payment_Captured__c,NATT_Order__r.NATT_Payment_Instruction__c,
    //         (SELECT Id,             
    //                 ShipmentId,
    //                 Quantity,
    //                 TrackingNumber, 
    //                 ExpectedDeliveryDate, 
    //                 ShipmentItemNumber,
    //                 NATT_OrderProduct__c,
    //                 NATT_Amount__c,
    //                 NATT_OrderProduct__r.NATT_OrderLineNumber__c,
    //                 NATT_OrderProduct__r.NATT_Shipped_Quantity__c,
    //                 NATT_OrderProduct__r.Quantity,
    //                 NATT_OrderProduct__r.Part_Number__c,
    //                 NATT_OrderProduct__r.UnitPrice,
    //                 NATT_OrderProduct__r.AdjustedLineAmount,            
    //                 NATT_OrderProduct__r.Product2.NATT_P_N__c, 
    //                 NATT_OrderProduct__r.Product2.Name, 
    //                 NATT_OrderProduct__r.Product2.NATT_Unit__c,
    //                 NATT_OrderProduct__r.Product2.NATT_UOM_Conversion__c,
    //                 NATT_OrderProduct__r.Product2.QuantityUnitOfMeasure,
    //                 NATT_OrderProduct__r.Type,
    //                 NATT_OrderProduct__r.TypeCode,
    //                 Shipment.NATT_InvoiceNumber__c, 
    //                 Shipment.NATT_DateShipped__c, 
    //                 Shipment.NATT_PackingSlipNumber__c,
    //                 Shipment.TrackingNumber,
    //                 Shipment.NATT_BillOfLading__c 
    //             FROM ShipmentItems)
    //         FROM Shipment WHERE NATT_Order__c=:orderId];
    //         System.debug('getShipmentValue: ' + s);
    //         return s;
    //     } catch (Exception e) {
    //         throw new AuraHandledException(e.getMessage());
    //     }
    // }

    // @AuraEnabled(cacheable = true)
    // public static Shipment getShipmentInvoice(String shipmentId){
    //     try {
    //         Shipment s = 
    //          [SELECT Id,NATT_Order__c,NATT_Order__r.NATT_CustomerName__c,NATT_Order__r.NATT_Contact_Name__c,
    //         NATT_Order__r.NATT_CustomerBilltoCode__c,NATT_Order__r.NATT_Contact_Email__c,NATT_Order__r.NATT_Purchase_Order__c,
    //         NATT_Order__r.NATT_Contact_Phone__c,NATT_Order__r.NATT_JDE_Sales_Order_Number__c,NATT_Order__r.OrderedDate,
    //         NATT_Order__r.NATT_JdeOrderTypeName__c,NATT_Order__r.NATT_Warehouse__c,toLabel(NATT_Order__r.NATT_Shipment_Method__c),
    //         NATT_Order__r.ShippingAddress,NATT_Order__r.BillingAddress,toLabel(NATT_Order__r.NATT_Shipment_Terms__c),
    //         NATT_Order__r.NATT_Freight_Account_Number__c,NATT_PackingSlipNumber__c,NATT_ShippingCompanyName__c,NATT_BillOfLading__c,
    //         NATT_InvoiceDate__c,TrackingNumber,
    //         ExpectedDeliveryDate,NATT_InvoiceNumber__c,NATT_Order__r.OrderNumber,NATT_DateShipped__c,NATT_Payment_Captured__c,NATT_Order__r.NATT_Payment_Instruction__c,
    //         (SELECT Id,             
    //         ShipmentId,
    //         Quantity,
    //         TrackingNumber, 
    //         ExpectedDeliveryDate, 
    //         ShipmentItemNumber,
    //         NATT_OrderProduct__c,
    //         NATT_Amount__c,
    //         NATT_OrderProduct__r.NATT_OrderLineNumber__c,
    //         NATT_OrderProduct__r.NATT_Shipped_Quantity__c,
    //         NATT_OrderProduct__r.Quantity,
    //         NATT_OrderProduct__r.Part_Number__c,
    //         NATT_OrderProduct__r.UnitPrice,
    //         NATT_OrderProduct__r.AdjustedLineAmount,            
    //         NATT_OrderProduct__r.Product2.NATT_P_N__c, 
    //         NATT_OrderProduct__r.Product2.Name, 
    //         NATT_OrderProduct__r.Product2.NATT_Unit__c,
    //         NATT_OrderProduct__r.Product2.NATT_UOM_Conversion__c,
    //         NATT_OrderProduct__r.Product2.QuantityUnitOfMeasure,
    //         NATT_OrderProduct__r.Type,
    //         NATT_OrderProduct__r.TypeCode,
    //         Shipment.NATT_InvoiceNumber__c, 
    //         Shipment.NATT_DateShipped__c, 
    //         Shipment.NATT_PackingSlipNumber__c,
    //         Shipment.TrackingNumber,
    //         Shipment.NATT_BillOfLading__c FROM ShipmentItems ORDER BY NATT_OrderProduct__r.NATT_OrderLineNumber__c)
    //          FROM Shipment WHERE Id=:shipmentId];

    //         return s;
    //     } catch (Exception e) {
    //         throw new AuraHandledException(e.getMessage());
    //     }
    // }

    @AuraEnabled(cacheable = true)
    public static List <Order> grabMyOrders (String UserId, String CommunityId){
        String webstoreId = B2BUtils.resolveCommunityIdToWebstoreId(CommunityId);
        return 
        [SELECT 
        Id, 
        OrderNumber,
        RecordTypeId,
        AccountId,
        NATT_Account_Name__c,
        TotalAmount,
        EffectiveDate,
        NATT_Order_Status__c,
        Status,
        SalesStoreId,
        ShippingAddress,
        GrandTotalAmount,
        NATT_Number_of_Order_Products__c,
        NATT_Number_of_Units_Ordered__c,
        NATT_Payment_Instruction__c
        FROM Order
        WHERE ownerId = :UserId AND SalesStoreId = :webstoreId
        ORDER BY OrderNumber DESC
        ];
    }

}