NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>NATT_Order_Status__c</fullName>
    <description>NATT</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enter Order (Default Value)</fullName>
            </value>
            <value>
                <fullName>Sabrix Run</fullName>
            </value>
            <value>
                <fullName>Fulfillment Run</fullName>
            </value>
            <value>
                <fullName>Order Acknowledge</fullName>
            </value>
            <value>
                <fullName>Release Order for Shipment</fullName>
            </value>
            <value>
                <fullName>Credit Check for Shipment</fullName>
            </value>
            <value>
                <fullName>Ready to Print Pick Slip</fullName>
            </value>
            <value>
                <fullName>Ready for Picking</fullName>
            </value>
            <value>
                <fullName>Ready for Shipping</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Sabrix</fullName>
            </value>
            <value>
                <fullName>Invoicing</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Not Shipped</fullName>
            </value>
            <value>
                <fullName>Partially Shipped</fullName>
            </value>
            <value>
                <fullName>Awaiting Pricing</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Approval</fullName>
            </value>
            <value>
                <fullName>Customer Approved</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>No Enviado</fullName>
            </value>
            <value>
                <fullName>Envío parcial</fullName>
            </value>
            <value>
                <fullName>Completo</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>The quote where the order is created from.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/recordTypes/NATT_Parts_Order.recordType-meta.xml
<RecordType>
    <fullName>NATT_Parts_Order</fullName>
    <active>true</active>
    <description>NATT Parts Order</description>
    <label>NATT Parts Order</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Order/recordTypes/NATT_Units_Order.recordType-meta.xml
<RecordType>
    <fullName>NATT_Units_Order</fullName>
    <active>true</active>
    <description>NATT Units Order</description>
    <label>NATT Units Order</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/NATT_MyProgressController.cls
public with sharing class NATT_MyProgressController {

    public static String periodProgress;

    @AuraEnabled
    public static Map<String, Object> getMyProgressSummary(String period) {
        Map<String, Object> mpReturn = new Map<String, Object>{'success' => true, 'message' => '', 'quoteIsAccessible' => NATT_Utils.isAccessible('SBQQ__Quote__c'), 'orderIsAccessible' => NATT_Utils.isAccessible('Order'), 'caseIsAccessible' => NATT_Utils.isAccessible('Case'), 'claimIsAccessible' => true};
        periodProgress = setParamPeriod(period);

        try {

            mpReturn.put('countQuotesInProgress', getCountQuotesInProgress());
            mpReturn.put('countOrdersInProgress', getCountOrdersInProgress());
            mpReturn.put('countCasesInProgress', getCountCasesInProgress());
            mpReturn.put('countClaimsInProgress', getCountClaimsInProgress());

        } catch (AuraHandledException e) {
            mpReturn.put('success', false);
            mpReturn.put('message', e.getMessage());
        }
        
        return mpReturn;
    }

    @TestVisible
    private static Integer getCountQuotesInProgress() {
        Integer countNumber = 0;

        try {
            
            if (periodProgress == 'TODAY') {
                countNumber = [SELECT COUNT() FROM SBQQ__Quote__c WHERE SBQQ__Status__c IN :NATT_Constants.QUOTE_STATUS_IN_PROGRESS AND RecordType.DeveloperName = :NATT_Constants.QUOTE_NATT_UNIT_RT AND CreatedDate = TODAY];
            } else if (periodProgress == 'THIS_WEEK') {
                countNumber = [SELECT COUNT() FROM SBQQ__Quote__c WHERE SBQQ__Status__c IN :NATT_Constants.QUOTE_STATUS_IN_PROGRESS AND RecordType.DeveloperName = :NATT_Constants.QUOTE_NATT_UNIT_RT AND CreatedDate <= THIS_WEEK];
            } else if (periodProgress == 'THIS_MONTH') {
                countNumber = [SELECT COUNT() FROM SBQQ__Quote__c WHERE SBQQ__Status__c IN :NATT_Constants.QUOTE_STATUS_IN_PROGRESS AND RecordType.DeveloperName = :NATT_Constants.QUOTE_NATT_UNIT_RT AND CreatedDate <= THIS_MONTH];
            }

            //countNumber = Database.countQuery('SELECT COUNT() FROM SBQQ__Quote__c WHERE SBQQ__Status__c IN ' + NATT_Constants.QUOTE_STATUS_IN_PROGRESS + ' AND CreatedDate < ' + periodProgress);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        return countNumber;
    }
    
    @TestVisible
    private static Map<String, Integer> getCountOrdersInProgress() {
        Map<String, Integer> mpOrderTypeCount = new Map<String, Integer>();
        List<AggregateResult> ltAggregateOrder = new List<AggregateResult>();
        
        try {

            if (periodProgress == 'TODAY') {
                ltAggregateOrder = [SELECT COUNT(Id), RecordType.DeveloperName FROM Order WHERE NATT_Order_Status__c IN :NATT_Constants.ORDER_STATUS_IN_PROGRESS AND CreatedDate = TODAY GROUP BY RecordType.DeveloperName];
            } else if (periodProgress == 'THIS_WEEK') {
                ltAggregateOrder = [SELECT COUNT(Id), RecordType.DeveloperName FROM Order WHERE NATT_Order_Status__c IN :NATT_Constants.ORDER_STATUS_IN_PROGRESS AND CreatedDate <= THIS_WEEK GROUP BY RecordType.DeveloperName];
            } else if (periodProgress == 'THIS_MONTH') {
                ltAggregateOrder = [SELECT COUNT(Id), RecordType.DeveloperName FROM Order WHERE NATT_Order_Status__c IN :NATT_Constants.ORDER_STATUS_IN_PROGRESS AND CreatedDate <= THIS_MONTH GROUP BY RecordType.DeveloperName];
            }

            System.debug('ltAggregateOrder: ' + ltAggregateOrder);

            if (ltAggregateOrder.isEmpty()) {
                mpOrderTypeCount.put( 'NATT_Units_Order', 0);
                mpOrderTypeCount.put( 'NATT_Parts_Order', 0);
            } else {
                for (AggregateResult aggregateOrder : ltAggregateOrder) {
                    mpOrderTypeCount.put( (String) aggregateOrder.get('DeveloperName'), (Integer) aggregateOrder.get('expr0'));
                }
            }
            
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        
        System.debug('mpOrderTypeCount: ' + mpOrderTypeCount);
        return mpOrderTypeCount;
    }
    
    @TestVisible
    private static Integer getCountCasesInProgress() {
        Integer countNumber = 0;
        
        try {

            if (periodProgress == 'TODAY') {
                countNumber = [SELECT COUNT() FROM Case WHERE Status IN :NATT_Constants.CASE_STATUS_IN_PROGRESS AND CreatedDate = TODAY];
            } else if (periodProgress == 'THIS_WEEK') {
                countNumber = [SELECT COUNT() FROM Case WHERE Status IN :NATT_Constants.CASE_STATUS_IN_PROGRESS AND CreatedDate <= THIS_WEEK];
            } else if (periodProgress == 'THIS_MONTH') {
                countNumber = [SELECT COUNT() FROM Case WHERE Status IN :NATT_Constants.CASE_STATUS_IN_PROGRESS AND CreatedDate <= THIS_MONTH];
            }
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        
        return countNumber;
    }
    
    @TestVisible
    private static Integer getCountClaimsInProgress() {
        Integer countNumber = 0;
        
        try {

            /*if (periodProgress == 'TODAY') {
                countNumber = [SELECT COUNT() FROM SBQQ__Quote__c WHERE SBQQ__Status__c IN :NATT_Constants.QUOTE_STATUS_IN_PROGRESS AND CreatedDate = TODAY];
            } else if (periodProgress == 'THIS_WEEK') {
                countNumber = [SELECT COUNT() FROM SBQQ__Quote__c WHERE SBQQ__Status__c IN :NATT_Constants.QUOTE_STATUS_IN_PROGRESS AND CreatedDate <= THIS_WEEK];
            } else if (periodProgress == 'THIS_MONTH') {
                countNumber = [SELECT COUNT() FROM SBQQ__Quote__c WHERE SBQQ__Status__c IN :NATT_Constants.QUOTE_STATUS_IN_PROGRESS AND CreatedDate <= THIS_MONTH];
            }*/
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        
        System.debug('countNumber: ' + countNumber);
        return countNumber;
    }

    @TestVisible
    private static String setParamPeriod(String period) {
        String constantPeriod = '';

        switch on period {
            when 'Day' {
                constantPeriod = 'TODAY';
            }
            
            when 'Week' {
                constantPeriod = 'THIS_WEEK';
            }

            when 'Month' {
                constantPeriod = 'THIS_MONTH';
            }
        }

        return constantPeriod;
    }
    
}