NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>NATT_Contact_Email__c</fullName>
    <description>email of contact for B2B order (no contact object record stored)</description>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>NATT_Contact_Name__c</fullName>
    <description>name of contact for B2B order (no contact object record stored)</description>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>NATT_Contact_Phone__c</fullName>
    <label>Contact Phone</label>
    <type>Phone</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_CustomerBilltoCode__c.field-meta.xml
<CustomField>
    <fullName>NATT_CustomerBilltoCode__c</fullName>
    <formula>Account.NATT_JDE_Parts_Bill_To_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer #</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_CustomerName__c.field-meta.xml
<CustomField>
    <fullName>NATT_CustomerName__c</fullName>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Freight_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>NATT_Freight_Account_Number__c</fullName>
    <description>Customer&apos;s freight account number if using Bill To Customer Delivery Term.</description>
    <label>Freight Account Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_JDE_Sales_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>NATT_JDE_Sales_Order_Number__c</fullName>
    <description>NATT</description>
    <externalId>true</externalId>
    <label>JDE Sales Order #</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_JdeOrderTypeName__c.field-meta.xml
<CustomField>
    <fullName>NATT_JdeOrderTypeName__c</fullName>
    <formula>IF(NATT_JdeOrderType__c == &apos;&apos;,&apos;&apos;,
IF(CONTAINS(NATT_JdeOrderType__c,&apos;1&apos;),&apos;Unit Down&apos;,
IF(CONTAINS(NATT_JdeOrderType__c,&apos;2&apos;),&apos;Same Day&apos;,
IF(CONTAINS(NATT_JdeOrderType__c,&apos;4&apos;),&apos;Stock&apos;,
IF(CONTAINS(NATT_JdeOrderType__c,&apos;C&apos;),&apos;Credit&apos;,
IF(CONTAINS(NATT_JdeOrderType__c,&apos;Y&apos;),&apos;Annual Return&apos;,&apos;&apos;))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Type</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Payment_Instruction__c.field-meta.xml
<CustomField>
    <fullName>NATT_Payment_Instruction__c</fullName>
    <label>Payment Instruction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Wire Transfer</fullName>
            </value>
            <value>
                <fullName>Terms</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>NATT_Purchase_Order__c</fullName>
    <description>NATT</description>
    <label>PO #</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Shipment_Method__c.field-meta.xml
<CustomField>
    <fullName>NATT_Shipment_Method__c</fullName>
    <description>NATT</description>
    <label>Shipment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Shipment_Method</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Shipment_Terms__c.field-meta.xml
<CustomField>
    <fullName>NATT_Shipment_Terms__c</fullName>
    <description>NATT</description>
    <label>Shipment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Shipment_Terms</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <description>twin field from quote</description>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Unit</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>NATT_Warehouse__c</fullName>
    <description>The Warehouse, or Depot, from which the order is shipping.</description>
    <label>Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Warehouse_Picklist</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_P_N__c</fullName>
    <description>The Part Number for NATT JDE</description>
    <label>Part Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <description>for quoting NATT Units</description>
    <label>Unit NATT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Unit</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_UOM_Conversion__c.field-meta.xml
<CustomField>
    <fullName>NATT_UOM_Conversion__c</fullName>
    <description>NATT unit of measure conversion factor</description>
    <label>UOM Conversion</label>
    <precision>15</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_BillOfLading__c.field-meta.xml
<CustomField>
    <fullName>NATT_BillOfLading__c</fullName>
    <description>Bill of Lading number for freight shipments</description>
    <label>Bill of Lading #</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_DateShipped__c.field-meta.xml
<CustomField>
    <fullName>NATT_DateShipped__c</fullName>
    <description>Date the shipment was shipped from the warehouse</description>
    <label>Date Shipped</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_InvoiceDate__c</fullName>
    <description>Date the invoice was generated</description>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>NATT_InvoiceNumber__c</fullName>
    <description>Number of the invoice for the shipment</description>
    <label>Invoice Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_JDE_Sales_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>NATT_JDE_Sales_Order_Number__c</fullName>
    <formula>NATT_Order__r.NATT_JDE_Sales_Order_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>JDE Sales Order Number</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_Order__c.field-meta.xml
<CustomField>
    <fullName>NATT_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The order to which the shipment is related</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_PackingSlipNumber__c.field-meta.xml
<CustomField>
    <fullName>NATT_PackingSlipNumber__c</fullName>
    <description>Packing slip number of the shipment</description>
    <label>Packing Slip Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_Payment_Captured__c.field-meta.xml
<CustomField>
    <fullName>NATT_Payment_Captured__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox used in TES to indicate if the payment has been captured.</description>
    <label>Payment Captured</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_ShippingCompanyName__c.field-meta.xml
<CustomField>
    <fullName>NATT_ShippingCompanyName__c</fullName>
    <description>Name of the company transporting the shipment</description>
    <label>Shipping Company Name</label>
    <length>48</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Shipment_Method.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>9</fullName>
        <label>Customer Pickup</label>
    </customValue>
    <customValue>
        <fullName>OTH</fullName>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>BW1</fullName>
        <label>Bestway</label>
    </customValue>
    <customValue>
        <fullName>CR1</fullName>
        <label>Customer Routing</label>
    </customValue>
    <customValue>
        <fullName>FX1</fullName>
        <label>Fedex - Next Day Air</label>
    </customValue>
    <customValue>
        <fullName>FX2</fullName>
        <label>Fedex - 2nd Day Air</label>
    </customValue>
    <customValue>
        <fullName>FX3</fullName>
        <label>Fedex - 3rd Day Air</label>
    </customValue>
    <customValue>
        <fullName>FXG</fullName>
        <label>Fedex - Ground</label>
    </customValue>
    <customValue>
        <fullName>FXX</fullName>
        <label>Fedex - Saturday Delivery</label>
    </customValue>
    <customValue>
        <fullName>OF</fullName>
        <label>Ocean Freight</label>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
        <label>Air Freight</label>
    </customValue>
    <customValue>
        <fullName>ABF</fullName>
    </customValue>
    <customValue>
        <fullName>BW</fullName>
        <label>Best Way</label>
    </customValue>
    <customValue>
        <fullName>FX6</fullName>
    </customValue>
    <customValue>
        <fullName>FX7</fullName>
    </customValue>
    <customValue>
        <fullName>OCN</fullName>
    </customValue>
    <customValue>
        <fullName>WCL</fullName>
    </customValue>
    <customValue>
        <fullName>LTL</fullName>
    </customValue>
    <customValue>
        <fullName>UP1</fullName>
        <label>UPS NEXT DAY</label>
    </customValue>
    <customValue>
        <fullName>UP2</fullName>
    </customValue>
    <customValue>
        <fullName>UP3</fullName>
    </customValue>
    <customValue>
        <fullName>UPG</fullName>
        <label>UPS GROUND</label>
    </customValue>
    <customValue>
        <fullName>UPX</fullName>
    </customValue>
    <customValue>
        <fullName>CPU</fullName>
        <label>Customer Pickup()</label>
    </customValue>
    <customValue>
        <fullName>AF1</fullName>
        <label>Air Freight()</label>
    </customValue>
    <customValue>
        <fullName>EI1</fullName>
        <label>EXPEDITORS INTERNATIONAL</label>
    </customValue>
    <customValue>
        <fullName>PKU</fullName>
        <label>PICKUP</label>
    </customValue>
    <customValue>
        <fullName>NDA</fullName>
        <label>NEXT DAY AIR</label>
    </customValue>
    <customValue>
        <fullName>OF1</fullName>
        <label>Ocean Freight()</label>
    </customValue>
    <customValue>
        <fullName>FCA</fullName>
    </customValue>
    <masterLabel>NATT Shipment Method</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Shipment_Terms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BIL</fullName>
        <label>Bill to Customer</label>
    </customValue>
    <customValue>
        <fullName>PPD</fullName>
        <label>Prepaid Freight</label>
    </customValue>
    <customValue>
        <fullName>COL</fullName>
        <label>Collect</label>
    </customValue>
    <customValue>
        <fullName>CPU</fullName>
        <label>Customer Pickup</label>
    </customValue>
    <customValue>
        <fullName>PPA</fullName>
        <label>Prepaid and Allowed</label>
    </customValue>
    <customValue>
        <fullName>PPB</fullName>
        <label>Prepaid and Billed</label>
    </customValue>
    <customValue>
        <fullName>EXW</fullName>
        <label>EXW - EX Works</label>
    </customValue>
    <customValue>
        <fullName>CIF</fullName>
    </customValue>
    <customValue>
        <fullName>DDP</fullName>
    </customValue>
    <customValue>
        <fullName>FOB</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>999</fullName>
    </customValue>
    <customValue>
        <fullName>AAA</fullName>
    </customValue>
    <customValue>
        <fullName>ABF</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AF1</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AVE</fullName>
    </customValue>
    <customValue>
        <fullName>BCB</fullName>
    </customValue>
    <customValue>
        <fullName>BW</fullName>
    </customValue>
    <customValue>
        <fullName>BW1</fullName>
    </customValue>
    <customValue>
        <fullName>CAR</fullName>
    </customValue>
    <masterLabel>Shipment Terms</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>200INT ComfortPro Integrated APU</fullName>
    </customValue>
    <customValue>
        <fullName>210STA ComfortPro Stand-alone APU</fullName>
    </customValue>
    <customValue>
        <fullName>220PWR ComfortPro Power-only APU</fullName>
    </customValue>
    <customValue>
        <fullName>230SKY ComfortPro ClearSky DPF APU</fullName>
    </customValue>
    <customValue>
        <fullName>240EPS ComfortPro Electric APU</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S6 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S7 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S8 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S9 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>20X Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>30S Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>30S with 115v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>30S with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>35X Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>35X with 115v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>35X with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>35X with 230v-3ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>40X with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>40XR with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>50X with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>50XR Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>50XR with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>50XR with 230v-3ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>Neos 100S - Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>Solara APX</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8100</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8500</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 01</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 02</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 03</fullName>
    </customValue>
    <description>for quoting in cpq for NATT</description>
    <masterLabel>NATT Unit</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Warehouse_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ANA</fullName>
    </customValue>
    <customValue>
        <fullName>BNA</fullName>
    </customValue>
    <customValue>
        <fullName>CHI</fullName>
    </customValue>
    <customValue>
        <fullName>PAN</fullName>
    </customValue>
    <customValue>
        <fullName>ATL</fullName>
    </customValue>
    <customValue>
        <fullName>MEX</fullName>
    </customValue>
    <customValue>
        <fullName>MIA</fullName>
    </customValue>
    <customValue>
        <fullName>TES</fullName>
    </customValue>
    <customValue>
        <fullName>LATAM</fullName>
    </customValue>
    <customValue>
        <fullName>CTB01</fullName>
    </customValue>
    <masterLabel>NATT Warehouse Picklist</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/NATT_TesOrderDetailsConShipment.cls
public without sharing class NATT_TesOrderDetailsConShipment {
    @AuraEnabled(cacheable = true)
    public static List <Shipment> getShipment(String orderId){
        try {
            List <Shipment> s = 
             [SELECT Id,NATT_Order__c,NATT_Order__r.NATT_CustomerName__c,NATT_Order__r.NATT_Contact_Name__c,
            NATT_Order__r.NATT_CustomerBilltoCode__c,NATT_Order__r.NATT_Contact_Email__c,NATT_Order__r.NATT_Purchase_Order__c,
            NATT_Order__r.NATT_Contact_Phone__c,NATT_Order__r.NATT_JDE_Sales_Order_Number__c,NATT_Order__r.OrderedDate,
            NATT_Order__r.NATT_JdeOrderTypeName__c,NATT_Order__r.NATT_Warehouse__c,toLabel(NATT_Order__r.NATT_Shipment_Method__c),
            NATT_Order__r.ShippingAddress,NATT_Order__r.BillingAddress,toLabel(NATT_Order__r.NATT_Shipment_Terms__c),
            NATT_Order__r.NATT_Freight_Account_Number__c,NATT_PackingSlipNumber__c,NATT_ShippingCompanyName__c,NATT_BillOfLading__c,
            NATT_InvoiceDate__c,TrackingNumber,
            ExpectedDeliveryDate,NATT_InvoiceNumber__c,NATT_Order__r.OrderNumber,NATT_DateShipped__c,NATT_Payment_Captured__c,NATT_Order__r.NATT_Payment_Instruction__c,
            (SELECT Id,             
                    ShipmentId,
                    Quantity,
                    TrackingNumber, 
                    ExpectedDeliveryDate, 
                    ShipmentItemNumber,
                    NATT_OrderProduct__c,
                    NATT_Amount__c,
                    NATT_OrderProduct__r.NATT_OrderLineNumber__c,
                    NATT_OrderProduct__r.NATT_Shipped_Quantity__c,
                    NATT_OrderProduct__r.Quantity,
                    NATT_OrderProduct__r.Part_Number__c,
                    NATT_OrderProduct__r.UnitPrice,
                    NATT_OrderProduct__r.AdjustedLineAmount,            
                    NATT_OrderProduct__r.Product2.NATT_P_N__c, 
                    NATT_OrderProduct__r.Product2.Name, 
                    NATT_OrderProduct__r.Product2.NATT_Unit__c,
                    NATT_OrderProduct__r.Product2.NATT_UOM_Conversion__c,
                    NATT_OrderProduct__r.Product2.QuantityUnitOfMeasure,
                    NATT_OrderProduct__r.Type,
                    NATT_OrderProduct__r.TypeCode,
                    Shipment.NATT_InvoiceNumber__c, 
                    Shipment.NATT_DateShipped__c, 
                    Shipment.NATT_PackingSlipNumber__c,
                    Shipment.TrackingNumber,
                    Shipment.NATT_BillOfLading__c 
                FROM ShipmentItems)
            FROM Shipment WHERE NATT_Order__c=:orderId];
            System.debug('getShipmentValue: ' + s);
            return s;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable = true)
    public static Shipment getShipmentInvoice(String shipmentId){
        try {
            Shipment s = 
             [SELECT Id,NATT_Order__c,NATT_Order__r.NATT_CustomerName__c,NATT_Order__r.NATT_Contact_Name__c,
            NATT_Order__r.NATT_CustomerBilltoCode__c,NATT_Order__r.NATT_Contact_Email__c,NATT_Order__r.NATT_Purchase_Order__c,
            NATT_Order__r.NATT_Contact_Phone__c,NATT_Order__r.NATT_JDE_Sales_Order_Number__c,NATT_Order__r.OrderedDate,
            NATT_Order__r.NATT_JdeOrderTypeName__c,NATT_Order__r.NATT_Warehouse__c,toLabel(NATT_Order__r.NATT_Shipment_Method__c),
            NATT_Order__r.ShippingAddress,NATT_Order__r.BillingAddress,toLabel(NATT_Order__r.NATT_Shipment_Terms__c),
            NATT_Order__r.NATT_Freight_Account_Number__c,NATT_PackingSlipNumber__c,NATT_ShippingCompanyName__c,NATT_BillOfLading__c,
            NATT_InvoiceDate__c,TrackingNumber,
            ExpectedDeliveryDate,NATT_InvoiceNumber__c,NATT_Order__r.OrderNumber,NATT_DateShipped__c,NATT_Payment_Captured__c,NATT_Order__r.NATT_Payment_Instruction__c,
            (SELECT Id,             
            ShipmentId,
            Quantity,
            TrackingNumber, 
            ExpectedDeliveryDate, 
            ShipmentItemNumber,
            NATT_OrderProduct__c,
            NATT_Amount__c,
            NATT_OrderProduct__r.NATT_OrderLineNumber__c,
            NATT_OrderProduct__r.NATT_Shipped_Quantity__c,
            NATT_OrderProduct__r.Quantity,
            NATT_OrderProduct__r.Part_Number__c,
            NATT_OrderProduct__r.UnitPrice,
            NATT_OrderProduct__r.AdjustedLineAmount,            
            NATT_OrderProduct__r.Product2.NATT_P_N__c, 
            NATT_OrderProduct__r.Product2.Name, 
            NATT_OrderProduct__r.Product2.NATT_Unit__c,
            NATT_OrderProduct__r.Product2.NATT_UOM_Conversion__c,
            NATT_OrderProduct__r.Product2.QuantityUnitOfMeasure,
            NATT_OrderProduct__r.Type,
            NATT_OrderProduct__r.TypeCode,
            Shipment.NATT_InvoiceNumber__c, 
            Shipment.NATT_DateShipped__c, 
            Shipment.NATT_PackingSlipNumber__c,
            Shipment.TrackingNumber,
            Shipment.NATT_BillOfLading__c FROM ShipmentItems ORDER BY NATT_OrderProduct__r.NATT_OrderLineNumber__c)
             FROM Shipment WHERE Id=:shipmentId];

            return s;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}