NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Dealer_Comments__c.field-meta.xml
<CustomField>
    <fullName>NATT_Dealer_Comments__c</fullName>
    <description>NATT</description>
    <label>Dealer Comments</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Product_Family__c.field-meta.xml
<CustomField>
    <fullName>NATT_Product_Family__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Product_Family</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Shipment_Method__c.field-meta.xml
<CustomField>
    <fullName>NATT_Shipment_Method__c</fullName>
    <description>NATT</description>
    <label>Shipment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Shipment_Method</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>The quote where the order is created from.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CTBR_Freight_Terms__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Freight_Terms__c</fullName>
    <label>Freight Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CTBR_Quote_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Quote_Delivery_Date__c</fullName>
    <label>Quote Delivery Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CTBR_Tax_Observation__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Tax_Observation__c</fullName>
    <label>Tax Observation</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Dealer_Comments__c.field-meta.xml
<CustomField>
    <fullName>NATT_Dealer_Comments__c</fullName>
    <description>NATT</description>
    <label>Dealer Comments</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Product_Family__c.field-meta.xml
<CustomField>
    <fullName>NATT_Product_Family__c</fullName>
    <description>NATT</description>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Product_Family</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Quote_Request_Date__c.field-meta.xml
<CustomField>
    <fullName>NATT_Quote_Request_Date__c</fullName>
    <description>NATT</description>
    <label>Quote Request Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Shipment_Method__c.field-meta.xml
<CustomField>
    <fullName>NATT_Shipment_Method__c</fullName>
    <description>NATT</description>
    <label>Shipment Method</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Product_Family__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BW</fullName>
                <label>Best Way</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Customer Pickup</label>
            </value>
            <value>
                <fullName>ABF</fullName>
            </value>
            <value>
                <fullName>OTH</fullName>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PaymentTerms__c</fullName>
    <description>Terms that govern payment of the items in this quote.</description>
    <inlineHelpText>Terms that govern payment of the items in this quote.</inlineHelpText>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Due on receipt</fullName>
            </value>
            <value>
                <fullName>Net 15</fullName>
            </value>
            <value>
                <fullName>Net 30</fullName>
                <default>true</default>
                <label>Net 30</label>
            </value>
            <value>
                <fullName>Net 45</fullName>
            </value>
            <value>
                <fullName>Net 55</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
            <value>
                <fullName>Net 90</fullName>
            </value>
            <value>
                <fullName>Net 120</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Primary__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox which if checked designates the quote as the Primary Quote</description>
    <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Trailer</fullName>
    </customValue>
    <customValue>
        <fullName>Diesel Truck</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Drive</fullName>
    </customValue>
    <customValue>
        <fullName>APU</fullName>
    </customValue>
    <customValue>
        <fullName>Solara</fullName>
    </customValue>
    <customValue>
        <fullName>Electric Truck</fullName>
    </customValue>
    <customValue>
        <fullName>Electric Trailer</fullName>
        <isActive>false</isActive>
        <label>Electric Trailer</label>
    </customValue>
    <customValue>
        <fullName>DD Truck</fullName>
        <isActive>false</isActive>
        <label>DD Truck</label>
    </customValue>
    <masterLabel>NATT Product Family</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/ctbrUtility_Test.cls
@isTest(seeAllData = true)
public class ctbrUtility_Test {
    public static SBQQ__Quote__c quote;
    public static Order order;
    public static Account acc;
    
    static testmethod void setData() {
        acc = new Account();
        acc.Name = 'Test';
        insert acc;
        
        Recordtype recType = [select id,name,SobjectType from RecordType where name = 'CTBR Units Quote'];
        try{
            quote = new SBQQ__Quote__c();
        quote.SBQQ__Primary__c = true;
        quote.SBQQ__Status__c = 'Activated';
        quote.NATT_Quote_Request_Date__c = date.today();
        quote.NATT_Dealer_Comments__c = 'Test';
        quote.CTBR_Quote_Delivery_Date__c = date.today().addDays(1);
        quote.CTBR_Freight_Terms__c = 'COL';
        quote.NATT_Product_Family__c = 'Trailer';
        quote.recordtypeId = recType.Id;
  	    //quote.NATT_Shipment_Method__c = 'Best Way';
  	    //quote.SBQQ__Primary__c = true;
        quote.SBQQ__PaymentTerms__c = 'Net 31';
        quote.CTBR_Tax_Observation__c = 'tax';
        insert quote;
            system.debug('quote-->'+quote);
        } catch(Exception ex){
            system.debug('insidecatch');
            ctbrUtility.LogException(ex,'ctbrOrderInboundIntegration','getOrderandQuote');
        }
	}
}