NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Configured_Unit_Code__c.field-meta.xml
<CustomField>
    <fullName>NATT_Configured_Unit_Code__c</fullName>
    <description>NATT - this is a twin field from quote and represents the part number for the base unit.</description>
    <label>Product Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_End_Customer__c.field-meta.xml
<CustomField>
    <fullName>NATT_End_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NATT end customer</description>
    <label>End Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (End Customer)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Net_Amount__c.field-meta.xml
<CustomField>
    <fullName>NATT_Net_Amount__c</fullName>
    <description>from the originating quote, for calculating discounts</description>
    <formula>SBQQ__Quote__r.SBQQ__NetAmount__c</formula>
    <label>NATT Net Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Requested_Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>NATT_Requested_Ship_Date__c</fullName>
    <description>NATT</description>
    <label>Requested Ship Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <description>twin field from quote</description>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Unit</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>The quote where the order is created from.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Configured_Unit_Code__c.field-meta.xml
<CustomField>
    <fullName>NATT_Configured_Unit_Code__c</fullName>
    <description>natt</description>
    <label>Product Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_End_Customer__c.field-meta.xml
<CustomField>
    <fullName>NATT_End_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NATT End Customer</description>
    <label>End Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>MX_Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CTBR_Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (End Customer)</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Net_Amount__c.field-meta.xml
<CustomField>
    <fullName>NATT_Net_Amount__c</fullName>
    <description>NATT</description>
    <label>NATT Net Amount</label>
    <summarizedField>SBQQ__QuoteLine__c.SBQQ__NetTotal__c</summarizedField>
    <summaryFilterItems>
        <field>SBQQ__QuoteLine__c.SBQQ__NonDiscountable__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>SBQQ__QuoteLine__c.SBQQ__Optional__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>SBQQ__QuoteLine__c.SBQQ__Quote__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Quote_Record_Type_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>NATT_Quote_Record_Type_Developer_Name__c</fullName>
    <description>Used to default Quote Record Developer Name through a Process Builder.</description>
    <label>Quote Record Type Developer Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Requested_Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>NATT_Requested_Ship_Date__c</fullName>
    <description>NATT</description>
    <label>Requested Ship Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Total_Per_Unit_Without_EMCC_New__c.field-meta.xml
<CustomField>
    <fullName>NATT_Total_Per_Unit_Without_EMCC_New__c</fullName>
    <description>NATT</description>
    <formula>NATT_Total_Amount_Without_EMCC__c / NATT_Number_of_Units__c</formula>
    <label>Total Per Unit Without BluEdge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <description>NATT Unit selected for this quote</description>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Product_Family__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>NATT_Unit</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Ordered__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Ordered__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Internal flag to drive automatic order creation.</description>
    <inlineHelpText>Select this checkbox to automatically create an order from this quote, if it is a primary quote.</inlineHelpText>
    <label>Ordered</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__SubscribedQuoteLine__c/SBQQ__SubscribedQuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscribedAssetHelp</customHelpPage>
    <description>Links a particular asset to the subscription that covers it.</description>
    <label>Subscribed Quote Line</label>
    <nameField>
        <displayFormat>SQL-{00000000}</displayFormat>
        <label>Subscribed Quote Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribed Quote Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__SubscribedQuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies the quote for the quoteLines.</description>
    <inlineHelpText>Identifies the quote for the quoteLines.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>200INT ComfortPro Integrated APU</fullName>
    </customValue>
    <customValue>
        <fullName>210STA ComfortPro Stand-alone APU</fullName>
    </customValue>
    <customValue>
        <fullName>220PWR ComfortPro Power-only APU</fullName>
    </customValue>
    <customValue>
        <fullName>230SKY ComfortPro ClearSky DPF APU</fullName>
    </customValue>
    <customValue>
        <fullName>240EPS ComfortPro Electric APU</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S6 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S7 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S8 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S9 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>20X Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>30S Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>30S with 115v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>30S with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>35X Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>35X with 115v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>35X with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>35X with 230v-3ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>40X with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>40XR with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>50X with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>50XR Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>50XR with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>50XR with 230v-3ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>Neos 100S - Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>Solara APX</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8100</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8500</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 01</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 02</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 03</fullName>
    </customValue>
    <description>for quoting in cpq for NATT</description>
    <masterLabel>NATT Unit</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/NATT_OrderedQuoteDetails.cls
/**
* @File Name : NATT_OrderedQuoteDetails.cls
* @Description : Class created to fetch order details and amount of recent order from a Quote Detail page
* @Created By : Rajasekharreddy Kotella
* @created On : April 4, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | April 4, 2025 |   | Initial Version
**/

public class NATT_OrderedQuoteDetails {
	
    @AuraEnabled(cacheable=true)
    public static Order getOrderDetails(String quoteId) {
        Order orderDetails;
        
        List<SBQQ__Quote__c> quoteList = [
            SELECT Id, NATT_End_Customer__c, NATT_Unit__c, SBQQ__Ordered__c, SBQQ__Account__c, SBQQ__Account__r.Name
            FROM SBQQ__Quote__c
            WHERE Id = :quoteId
            AND NATT_Quote_Record_Type_Developer_Name__c like '%NATT_Units_Quote%'
        ];
        
        if (!quoteList.isEmpty()) {
            SBQQ__Quote__c quoteDetails = quoteList[0];
            
            List<Order> orderList = [
                SELECT Id, SBQQ__Quote__c,NATT_Requested_Ship_Date__c, OrderNumber,SBQQ__Quote__r.NATT_Total_Per_Unit_Without_EMCC_New__c,SBQQ__Quote__r.NATT_Configured_Unit_Code__c,SBQQ__Quote__r.NATT_Unit__c, NATT_Unit__c, NATT_Net_Amount__c, CreatedDate 
                FROM Order  
                WHERE RecordType.Name like '%NATT Unit%'
                AND SBQQ__Quote__r.NATT_End_Customer__c != null
                AND SBQQ__Quote__r.NATT_Unit__c = :quoteDetails.NATT_Unit__c 
                AND SBQQ__Quote__r.SBQQ__Account__c = :quoteDetails.SBQQ__Account__c
                AND SBQQ__Quote__r.NATT_End_Customer__c = :quoteDetails.NATT_End_Customer__c
                ORDER BY CreatedDate DESC  
                LIMIT 1
            ];
            
                if (!orderList.isEmpty()) {
                    orderDetails = orderList[0];
                }
        }
        
        return orderDetails; // will return null if nothing was found
    }
    
}