NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>NATT_Order_Status__c</fullName>
    <description>NATT</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enter Order (Default Value)</fullName>
            </value>
            <value>
                <fullName>Sabrix Run</fullName>
            </value>
            <value>
                <fullName>Fulfillment Run</fullName>
            </value>
            <value>
                <fullName>Order Acknowledge</fullName>
            </value>
            <value>
                <fullName>Release Order for Shipment</fullName>
            </value>
            <value>
                <fullName>Credit Check for Shipment</fullName>
            </value>
            <value>
                <fullName>Ready to Print Pick Slip</fullName>
            </value>
            <value>
                <fullName>Ready for Picking</fullName>
            </value>
            <value>
                <fullName>Ready for Shipping</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Sabrix</fullName>
            </value>
            <value>
                <fullName>Invoicing</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Not Shipped</fullName>
            </value>
            <value>
                <fullName>Partially Shipped</fullName>
            </value>
            <value>
                <fullName>Awaiting Pricing</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Approval</fullName>
            </value>
            <value>
                <fullName>Customer Approved</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>No Enviado</fullName>
            </value>
            <value>
                <fullName>Envío parcial</fullName>
            </value>
            <value>
                <fullName>Completo</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>The quote where the order is created from.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/recordTypes/NATT_Units_Order.recordType-meta.xml
<RecordType>
    <fullName>NATT_Units_Order</fullName>
    <active>true</active>
    <description>NATT Units Order</description>
    <label>NATT Units Order</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/NATT_MyProgressControllerTest.cls
@IsTest
public class NATT_MyProgressControllerTest {
    
    @TestSetup
    static void makeData(){
        
        SBQQ__Quote__c newQuote = new SBQQ__Quote__c(
            SBQQ__Status__c = NATT_Constants.QUOTE_DRAFT,
            RecordTypeId = Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByDeveloperName().get(NATT_Constants.QUOTE_NATT_UNIT_RT).getRecordTypeId()
        );
        Insert newQuote;
        
        SBQQ__Quote__c newQuote2 = new SBQQ__Quote__c(
            SBQQ__Status__c = NATT_Constants.QUOTE_DRAFT,
            RecordTypeId = Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByDeveloperName().get(NATT_Constants.QUOTE_NATT_UNIT_RT).getRecordTypeId()
        );
        Insert newQuote2;
        
        Test.setCreatedDate(newQuote2.Id, System.now().addDays(-1));
        
        SBQQ__Quote__c newQuote3 = new SBQQ__Quote__c(
            SBQQ__Status__c = NATT_Constants.QUOTE_DRAFT,
            RecordTypeId = Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByDeveloperName().get(NATT_Constants.QUOTE_NATT_UNIT_RT).getRecordTypeId()
        );
        Insert newQuote3;
        
        Test.setCreatedDate(newQuote3.Id, System.now().addDays(-8));

        /* ---- */

        Account newAccount = new Account(
            Name = 'Account Test 1'
        );
        Insert newAccount;

        Order newOrder = new Order(
            Name = 'Order Test 1',
            AccountId = newAccount.Id,
            NATT_Order_Status__c = NATT_Constants.ORDER_STATUS_IN_PROGRESS.get(0),
            RecordTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get(NATT_Constants.ORDER_NATT_UNIT_RT).getRecordTypeId(),
            EffectiveDate = System.today(),
            Status = 'Draft'
        );
        Insert newOrder;
        
        Order newOrder2 = new Order(
            Name = 'Order Test 2',
            AccountId = newAccount.Id,
            NATT_Order_Status__c = NATT_Constants.ORDER_STATUS_IN_PROGRESS.get(0),
            RecordTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get(NATT_Constants.ORDER_NATT_UNIT_RT).getRecordTypeId(),
            EffectiveDate = System.today(),
            Status = 'Draft'
        );
        Insert newOrder2;
        Test.setCreatedDate(newOrder2.Id, System.now().addDays(-1));
        
        Order newOrder3 = new Order(
            Name = 'Order Test 3',
            AccountId = newAccount.Id,
            NATT_Order_Status__c = NATT_Constants.ORDER_STATUS_IN_PROGRESS.get(0),
            RecordTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get(NATT_Constants.ORDER_NATT_UNIT_RT).getRecordTypeId(),
            EffectiveDate = System.today().addDays(-1),
            Status = 'Draft'
        );
        Insert newOrder3;
        Test.setCreatedDate(newOrder3.Id, System.now().addDays(-8));
        
        /* ---- */

        Case newCase = new Case(
            Status = NATT_Constants.CASE_STATUS_IN_PROGRESS.get(0)
        );
        Insert newCase;
        
        Case newCase2 = new Case(
            Status = NATT_Constants.CASE_STATUS_IN_PROGRESS.get(0)
        );
        Insert newCase2;
        Test.setCreatedDate(newCase2.Id, System.now().addDays(-1));
        
        Case newCase3 = new Case(
            Status = NATT_Constants.CASE_STATUS_IN_PROGRESS.get(0)
        );
        Insert newCase3;
        Test.setCreatedDate(newCase3.Id, System.now().addDays(-8));

    }

    @IsTest
    static void getMyProgressSummaryTest(){
        
        Test.startTest();
            Map<String, Object> mpReturn = NATT_MyProgressController.getMyProgressSummary('Week');
            System.assertEquals(true, mpReturn.get('success'));
        
        Test.stopTest();
        
    }
    
    @IsTest
    static void getCountQuotesInProgressTest(){
        
        Test.startTest();
        	NATT_MyProgressController.periodProgress = 'TODAY';
            Integer countNumber = NATT_MyProgressController.getCountQuotesInProgress();
            System.assertEquals(1, countNumber);
        
        	NATT_MyProgressController.periodProgress = 'THIS_WEEK';
            Integer countNumber2 = NATT_MyProgressController.getCountQuotesInProgress();
            System.assertEquals(3, countNumber2);
        
        	NATT_MyProgressController.periodProgress = 'THIS_MONTH';
            Integer countNumber3 = NATT_MyProgressController.getCountQuotesInProgress();
            System.assertEquals(3, countNumber3);        
        Test.stopTest();
        
    }    
    
    @IsTest
    static void getCountOrdersInProgressTest(){
        
        Test.startTest();
        	NATT_MyProgressController.periodProgress = 'TODAY';
            Map<String, Integer> mapCountNumber = NATT_MyProgressController.getCountOrdersInProgress();
            System.assertEquals(1, mapCountNumber.get('NATT_Units_Order'));
        
        	NATT_MyProgressController.periodProgress = 'THIS_WEEK';
            Map<String, Integer> mapCountNumber2 = NATT_MyProgressController.getCountOrdersInProgress();
            System.assertEquals(3, mapCountNumber2.get('NATT_Units_Order'));
        
        	NATT_MyProgressController.periodProgress = 'THIS_MONTH';
            Map<String, Integer> mapCountNumber3 = NATT_MyProgressController.getCountOrdersInProgress();
            System.assertEquals(3, mapCountNumber3.get('NATT_Units_Order'));
        Test.stopTest();
        
    }
    
    @IsTest
    static void getCountCasesInProgressTest(){
        
        Test.startTest();
        	NATT_MyProgressController.periodProgress = 'TODAY';
            Integer countNumber = NATT_MyProgressController.getCountCasesInProgress();
            System.assertEquals(1, countNumber);
        
        	NATT_MyProgressController.periodProgress = 'THIS_WEEK';
            Integer countNumber2 = NATT_MyProgressController.getCountCasesInProgress();
            System.assertEquals(3, countNumber2);
        
        	NATT_MyProgressController.periodProgress = 'THIS_MONTH';
            Integer countNumber3 = NATT_MyProgressController.getCountCasesInProgress();
            System.assertEquals(3, countNumber3);
        Test.stopTest();
        
    }

    @IsTest
    static void setParamPeriodTest(){
        
        Test.startTest();
            String paramPeriodDay = NATT_MyProgressController.setParamPeriod('Day');
            System.assertEquals('TODAY', paramPeriodDay);

            String paramPeriodWeek = NATT_MyProgressController.setParamPeriod('Week');
            System.assertEquals('THIS_WEEK', paramPeriodWeek);

            String paramPeriodMonth = NATT_MyProgressController.setParamPeriod('Month');
            System.assertEquals('THIS_MONTH', paramPeriodMonth);
        Test.stopTest();
        
    }

}