NATTQA-ENV/force-app/main/default/objects/CTBR_Exchange_Rate__mdt/CTBR_Exchange_Rate__mdt.object-meta.xml
<CustomObject>
    <label>CTBR Exchange Rate</label>
    <pluralLabel>CTBR Exchange Rates</pluralLabel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/CTBR_Exchange_Rate__mdt/fields/Current_Rate__c.field-meta.xml
<CustomField>
    <fullName>Current_Rate__c</fullName>
    <description>Exchange Rate with US Dollar</description>
    <label>Current Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Exchange_Rate__c/Exchange_Rate__c.object-meta.xml
<CustomObject>
    <description>Created to integrate CTBR Exchange Rates with SAP.</description>
    <label>Exchange Rate</label>
    <nameField>
        <label>Exchange Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchange Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/Exchange_Rate__c/fields/CTBR_Current_Rate__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Current_Rate__c</fullName>
    <description>Current Rate of Real</description>
    <label>Current Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Exchange_Rate__c/fields/CTBR_Previous_Rate__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Previous_Rate__c</fullName>
    <description>Yesterdays Rate of Real</description>
    <label>Previous Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/ctbrExchangeRateTriggerHandler.cls
public class ctbrExchangeRateTriggerHandler {
    //Created : Tejas Hatalkar,11/11/2022 to update Previous Rate with old value of Current Rate, invoke the CustomMetadata Utility.
	public static void afterUpdate(List<Exchange_Rate__c> exchNewList,Map<Id,Exchange_Rate__c> newExchMap,Map<Id,Exchange_Rate__c> oldExchMap){
    	if(!exchNewList.isEmpty() && !newexchMap.isEmpty() && !oldexchMap.isempty() ){
            System.debug('Inside ExchRate Trigger');
            Map<String, Object> currentRateMap = new Map<String, Object>();
            Map<String, Object> previousRateMap = new Map<String, Object>();
            Set<Id> ExchRateIds = new Set<Id>();
            for(Exchange_Rate__c exch : exchNewList){
            	System.debug('Old map value'+oldexchMap.get(exch.id).CTBR_Current_Rate__c);
            	System.debug('New Map value'+newexchMap.get(exch.id).CTBR_Current_Rate__c);
        		if(oldexchMap.get(exch.id).CTBR_Current_Rate__c != newexchMap.get(exch.id).CTBR_Current_Rate__c && newexchMap.get(exch.id).CTBR_Current_Rate__c !=null){
                    if(exch.Name == 'CTBR Units' || exch.Name == 'CTBR BlueEdge'){
                        System.debug('Inside exch Rate Trigger Handler for CTBR Units');
                        ExchRateIds.add(exch.id);
                        //currentRateMap.put('Current_Rate__c', exch.CTBR_Current_Rate__c);
                        //ExchangeRateMetadataUtil.updateCustomMetadata('CTBR_Exchange_Rate__mdt','CTBR_Units', 'CTBR Units',currentRateMap);
                        //previousRateMap.put('Yesterday_Rate__c', exch.CTBR_Previous_Rate__c);
                        //ExchangeRateMetadataUtil.updateCustomMetadata('CTBR_Exchange_Rate__mdt','CTBR_Units', 'CTBR Units',previousRateMap);
                    }
                    
                }
    		}
            if(!exchrateids.isempty()){
                ctbrExchangeRateMetadataUtil.updateCustomMetadataFuture(exchrateIds);
            }
    	}
	}
}