NATTQA-ENV/force-app/main/default/objects/sbaa__Approval__c/sbaa__Approval__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/sbaa__Approval__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Cost_Contract_Price__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Cost_Contract_Price__c</fullName>
    <label>Contract Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Freight_Terms__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Freight_Terms__c</fullName>
    <description>Picklist field to be added under Production &amp; Scheduling Tab of Quote</description>
    <label>Freight Terms</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CONTAINER_Sales_Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CIP- CIP</fullName>
                <label>CIP - CIP</label>
            </value>
            <value>
                <fullName>COLLECT - COL</fullName>
                <label>COLLECT - COLL</label>
            </value>
            <value>
                <fullName>DELIVERED AT PLACE - DAP</fullName>
            </value>
            <value>
                <fullName>DELIVERED DUTY PAID - DDP</fullName>
            </value>
            <value>
                <fullName>NOT APPLICABLE - N/A</fullName>
            </value>
            <value>
                <fullName>PREPAID &amp; ALLOWED - PPA</fullName>
            </value>
            <value>
                <fullName>PREPAID &amp; BILLED - PPB</fullName>
            </value>
            <value>
                <fullName>PREPAID - PPD</fullName>
            </value>
            <value>
                <fullName>FREIGHT COLLECT - C</fullName>
            </value>
            <value>
                <fullName>EX FACTORY – EXC</fullName>
                <label>EX FACTORY - EXC</label>
            </value>
            <value>
                <fullName>CARRIAGE AND INSURANCE PAID TO -CIP</fullName>
                <label>CARRIAGE AND INSURANCE PAID TO - CIP</label>
            </value>
            <value>
                <fullName>DELIVERED AT TERMINAL - DAT</fullName>
            </value>
            <value>
                <fullName>EX-FACTORY - EXW</fullName>
            </value>
            <value>
                <fullName>COST AND FREIGHT - CFR</fullName>
            </value>
            <value>
                <fullName>EX WORKS - EXW</fullName>
            </value>
            <value>
                <fullName>DELIVED AT PLACE - DAP</fullName>
            </value>
            <value>
                <fullName>DELIVED DUTY PAID - DDP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Freight_Terms_GENSET__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Freight_Terms_GENSET__c</fullName>
    <description>Container GENSET record type Freight Terms</description>
    <label>Freight Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CIP - CIP</fullName>
            </value>
            <value>
                <fullName>DELIVERED AT PLACE - DAP</fullName>
            </value>
            <value>
                <fullName>DELIVERED DUTY PAID - DDP</fullName>
            </value>
            <value>
                <fullName>NOT APPLICABLE – N/A</fullName>
                <label>NOT APPLICABLE - N/A</label>
            </value>
            <value>
                <fullName>PREPAID &amp; ALLOWED - PPA</fullName>
            </value>
            <value>
                <fullName>PREPAID &amp; BILLED - PPB</fullName>
            </value>
            <value>
                <fullName>PREPAID - PPD</fullName>
            </value>
            <value>
                <fullName>FREIGHT COLLECT - C</fullName>
            </value>
            <value>
                <fullName>COST AND FREIGHT - CFR</fullName>
            </value>
            <value>
                <fullName>EX WORKS - EXW</fullName>
            </value>
            <value>
                <fullName>FREIGHT PREPAID - PP</fullName>
            </value>
            <value>
                <fullName>FREE CARRIER - FCA</fullName>
            </value>
            <value>
                <fullName>CARRIAGE PAID TO - CPT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Method_of_Shipment__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Method_of_Shipment__c</fullName>
    <description>Picklist field to be added under Production &amp; Scheduling Tab of Quote</description>
    <label>Method of Shipment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CONTAINER_Sales_Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AIR FREIGHT - 461-63-02 - AF</fullName>
            </value>
            <value>
                <fullName>OCEAN FREIGHT - 461-63-02 - OF</fullName>
            </value>
            <value>
                <fullName>SURFACE FREIGHT - 461-63-02 – SF</fullName>
            </value>
            <value>
                <fullName>NOT APPLICABLE - 461-63-02 - NA</fullName>
            </value>
            <value>
                <fullName>RAIL FREIGHT - 461-63-02 - RF</fullName>
            </value>
            <value>
                <fullName>AIR FREIGHT - AF</fullName>
            </value>
            <value>
                <fullName>OCEAN FREIGHT - OF</fullName>
            </value>
            <value>
                <fullName>SURFACE FREIGHT - SF</fullName>
            </value>
            <value>
                <fullName>NOT APPLICABLE - NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Method_of_Shipment_GENSET__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Method_of_Shipment_GENSET__c</fullName>
    <description>Container genset record type field values</description>
    <label>Method of Shipment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AIR FREIGHT - 461-63-02 - AF</fullName>
            </value>
            <value>
                <fullName>OCEAN FREIGHT - 461-63-02 - OF</fullName>
            </value>
            <value>
                <fullName>SURFACE FREIGHT - 461-63-02 – SF</fullName>
            </value>
            <value>
                <fullName>NOT APPLICABLE - 461-63-02 - NA</fullName>
            </value>
            <value>
                <fullName>RAIL FREIGHT - 461-63-02 - RF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Model_Number__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Model_Number__c</fullName>
    <label>Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Payment_Terms__c</fullName>
    <description>Picklist field to be added under Production &amp; Scheduling Tab of Quote</description>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CONTAINER_Sales_Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0 DAYS CN RETURN PAY</fullName>
            </value>
            <value>
                <fullName>102 DAYS PAYMENT TERM - 102</fullName>
            </value>
            <value>
                <fullName>12 DAYS PAYMENT TERM - 12</fullName>
            </value>
            <value>
                <fullName>14 DAYS PAYMENT TERM - 14</fullName>
            </value>
            <value>
                <fullName>15 DAYS PAYMENT TERM - 15</fullName>
            </value>
            <value>
                <fullName>21 DAYS PAYMENT TERM - 21</fullName>
            </value>
            <value>
                <fullName>30 DAYS PAYMENT TERM - 30</fullName>
            </value>
            <value>
                <fullName>40 DAYS PAYMENT TERM - 40</fullName>
            </value>
            <value>
                <fullName>45 DAYS PAYMENT TERM - 45</fullName>
            </value>
            <value>
                <fullName>46 DAYS PAYMENT TERM - 46</fullName>
            </value>
            <value>
                <fullName>50 DAYS PAYMENT TERM - 50</fullName>
            </value>
            <value>
                <fullName>60 DAYS PAYMENT TERM - 60</fullName>
            </value>
            <value>
                <fullName>65 DAYS PAYMENT TERM - 65</fullName>
            </value>
            <value>
                <fullName>90 DAYS PAYMENT TERM - 90</fullName>
            </value>
            <value>
                <fullName>120 DAYS PAYMENT TERM - 120</fullName>
            </value>
            <value>
                <fullName>CASH IN ADVANCE - CIA</fullName>
            </value>
            <value>
                <fullName>CASH ON DELIVERY - COD</fullName>
            </value>
            <value>
                <fullName>LETTER OF CREDIT - LOC</fullName>
            </value>
            <value>
                <fullName>NET 30 DAYS – N30</fullName>
            </value>
            <value>
                <fullName>NET 45 DAYS – N45</fullName>
            </value>
            <value>
                <fullName>NET 60 DAYS – N60</fullName>
            </value>
            <value>
                <fullName>NOT APPLICABLE - NAO</fullName>
            </value>
            <value>
                <fullName>NET 365 DAYS – N75</fullName>
            </value>
            <value>
                <fullName>NET 75 DAYS – N97</fullName>
            </value>
            <value>
                <fullName>NET 90 DAYS – N78</fullName>
            </value>
            <value>
                <fullName>LC 30 DAYS FROM BL D - L30</fullName>
            </value>
            <value>
                <fullName>LC 45 DAYS FROM BL D - L45</fullName>
            </value>
            <value>
                <fullName>LC AT SIGHT - 21 DAY - L00</fullName>
            </value>
            <value>
                <fullName>50% CASH IN ADVANCE - CIA 50%</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Payment_Terms_GENSET__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Payment_Terms_GENSET__c</fullName>
    <description>Container genset record type field values</description>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CASH IN ADVANCE - CIA</fullName>
            </value>
            <value>
                <fullName>LETTER OF CREDIT - LOC</fullName>
            </value>
            <value>
                <fullName>NET 30 DAYS - N30</fullName>
            </value>
            <value>
                <fullName>NET 45 DAYS - N45</fullName>
            </value>
            <value>
                <fullName>NET 60 DAYS - N60</fullName>
            </value>
            <value>
                <fullName>NOT APPLICABLE - NAO</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Qty__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Qty__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Sum_Requested_Ship_Dates_Qty__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Sum_Requested_Ship_Dates_Qty__c</fullName>
    <label>Sum of Requested Ship Dates Qty</label>
    <summarizedField>Requested_Ship_Dates__c.CONTAINER_Qty__c</summarizedField>
    <summaryForeignKey>Requested_Ship_Dates__c.CONTAINER_Quote_Number__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Type__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Type__c</fullName>
    <description>CONTAINER QUOTE TYPES</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>End Customer Quote</fullName>
                <default>true</default>
                <label>End Customer Quote</label>
            </value>
            <value>
                <fullName>Stock Quote</fullName>
            </value>
            <value>
                <fullName>Cost PID quote</fullName>
            </value>
            <value>
                <fullName>Planning products spec quotes</fullName>
            </value>
            <value>
                <fullName>Internal Engineering</fullName>
                <label>Internal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/QuoteExtController.cls
public with sharing class QuoteExtController {
	public Id quoteId;
    public String errormessage {get;set;}
    public SBQQ__Quote__c quote{get;set;}
    public SBAA__Approval__c[] approvals{get;set;}
	public QuoteExtController(ApexPages.StandardController stdController) {
		quoteId = stdController.getId();
        system.debug('quoteId'+quoteId);
		errormessage = '';
	}
	public PageReference onSubmit() {
        quote = [SELECT Id, Name, ApprovalStatus__c, CONTAINER_Model_Number__c, CONTAINER_Cost_Contract_Price__c, CONTAINER_Payment_Terms__c, CONTAINER_Payment_Terms_GENSET__c, CONTAINER_Method_of_Shipment__c,
                CONTAINER_Method_of_Shipment_GENSET__c, CONTAINER_Freight_Terms__c, CONTAINER_Freight_Terms_GENSET__c, CONTAINER_Sum_Requested_Ship_Dates_Qty__c, CONTAINER_Qty__c, CONTAINER_Type__c FROM SBQQ__Quote__c WHERE Id = :quoteId LIMIT 1];
        if(quote.ApprovalStatus__c == ContainerConstants.APPROVED_STATUS){
            system.debug('Already approved');
            errormessage = ContainerConstants.APPROVED_QUOTE_ERROR_MSG;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,ContainerConstants.APPROVED_QUOTE_ERROR_MSG));  
            return null;
        }
        else if(quote.ApprovalStatus__c == ContainerConstants.SUBMITTED_STATUS){
            system.debug('Already submitted');
            errormessage = ContainerConstants.SUBMITTED_QUOTE_ERROR_MSG;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,ContainerConstants.SUBMITTED_QUOTE_ERROR_MSG));  
            return null;
        }
        
        else if(quote.CONTAINER_Model_Number__c == null || (quote.CONTAINER_Cost_Contract_Price__c == null && quote.CONTAINER_Type__c == 'End Customer Quote') || (quote.CONTAINER_Payment_Terms__c == null && quote.CONTAINER_Payment_Terms_GENSET__c == null)
               ||(quote.CONTAINER_Method_of_Shipment__c == null && quote.CONTAINER_Method_of_Shipment_GENSET__c == null)
               ||(quote.CONTAINER_Freight_Terms__c == null && quote.CONTAINER_Freight_Terms_GENSET__c == null)
               || (quote.CONTAINER_Freight_Terms__c == null && quote.CONTAINER_Freight_Terms_GENSET__c == null)
               || (quote.CONTAINER_Sum_Requested_Ship_Dates_Qty__c == null)
               ||(quote.CONTAINER_Qty__c != quote.CONTAINER_Sum_Requested_Ship_Dates_Qty__c) ) {
            //string errormessage = '';
                   if(quote.CONTAINER_Model_Number__c == null){
            errormessage = errormessage + ContainerConstants.Model_Number_Blank + '\n';
                   }
           // ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,ContainerConstants.Model_Number_Blank));
            
            if(quote.CONTAINER_Cost_Contract_Price__c == null && quote.CONTAINER_Type__c == 'End Customer Quote') {
            	errormessage = errormessage + ContainerConstants.Contract_Price + '\n';
                //ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,ContainerConstants.Contract_Price));
          	
        }
            if(quote.CONTAINER_Payment_Terms__c == null && quote.CONTAINER_Payment_Terms_GENSET__c == null) {
            	errormessage = errormessage + ContainerConstants.Payment_terms_Field_Blank + '\n';
                //ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,ContainerConstants.Payment_terms_Field_Blank));
        	
        }
            
             if(quote.CONTAINER_Method_of_Shipment__c == null && quote.CONTAINER_Method_of_Shipment_GENSET__c == null) {
            	errormessage = errormessage + ContainerConstants.Method_of_shipment_field_blank + '\n';
                 //ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,ContainerConstants.Method_of_shipment_field_blank));
        	
        }
             if(quote.CONTAINER_Freight_Terms__c == null && quote.CONTAINER_Freight_Terms_GENSET__c == null) {
            	errormessage = errormessage + ContainerConstants.Freight_Terms_Field_Blank + '\n';
                 //ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,ContainerConstants.Freight_Terms_Field_Blank));
        
        }
            if(quote.CONTAINER_Sum_Requested_Ship_Dates_Qty__c == null) {
           		errormessage = errormessage + ContainerConstants.Requested_Ship_Dates_Null_Records + '\n';
                //ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,ContainerConstants.Requested_Ship_Dates_Null_Records));
        	
        }
             if(quote.CONTAINER_Qty__c != quote.CONTAINER_Sum_Requested_Ship_Dates_Qty__c) {
            	errormessage = errormessage + ContainerConstants.Quantity_Not_Equal_To_RequestedShipDate_Quantity + '\n';
                 //ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,ContainerConstants.Quantity_Not_Equal_To_RequestedShipDate_Quantity));
        	
        }
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,errormessage));
            return null;
        }     
        
		else if (quoteId != null) {
            system.debug('inside approval call');
			SBAA.ApprovalAPI.submit(quoteId, SBAA__Approval__c.Quote__c);
            list<sbaa__Approval__c>lstApp = [select id from sbaa__Approval__c where Quote__c=:quoteId];
            system.debug('applist'+lstApp);
		}
		return new PageReference('/' + quoteId);
	}
	public PageReference onRecall() {
		if (quoteId != null) {
			SBAA.ApprovalAPI.recall(quoteId, SBAA__Approval__c.Quote__c);
		}
		return new PageReference('/' + quoteId);
	}
    public PageReference onPreview() {
		if (quoteId != null) {
			approvals = SBAA.ApprovalAPI.Preview(quoteId, SBAA__Approval__c.Quote__c);
		}
		return null;
	}
    public PageReference returnToQuote() {
		if (quoteId != null) {
			return new PageReference('/' + quoteId);
		}
		return null;
	}
    
}