NATTQA-ENV/force-app/main/default/objects/CONTAINER_Tentative_Production_Schedule__c/CONTAINER_Tentative_Production_Schedule__c.object-meta.xml
<CustomObject>
    <label>Tentative Production Schedule</label>
    <nameField>
        <displayFormat>TPS-{0000}</displayFormat>
        <label>Tentative Production Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tentative Production Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/CONTAINER_Tentative_Production_Schedule__c/fields/CONTAINER_Factory__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Factory__c</fullName>
    <label>Factory</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ATHENS</fullName>
            </value>
            <value>
                <fullName>ATHENS STOCK</fullName>
            </value>
            <value>
                <fullName>SINGAPORE</fullName>
            </value>
            <value>
                <fullName>SING STOCK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/CONTAINER_Tentative_Production_Schedule__c/fields/CONTAINER_Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Quote_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Number</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Tentative Production Schedule</relationshipLabel>
    <relationshipName>Tentative_Production_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/CONTAINER_Tentative_Production_Schedule__c/fields/CONTAINER_TentativeProdSchd_Job__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_TentativeProdSchd_Job__c</fullName>
    <formula>CONTAINER_Select_Stock__r.CONTAINER_Inventory_Job__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Job #</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/CONTAINER_Tentative_Production_Schedule__c/fields/CONTAINER_TentativeProductionSchd_Qty__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_TentativeProductionSchd_Qty__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/ContainerQuoteASOTentativeRecords.cls
/********************************************************************************************************
* @author         Deloitte
* @description    An ContainerQuoteASOTentativeRecords class is created for Fetching the Tentative_Production_Schedule records for given Quote Number.
* @date           07/06/2022 [MM/DD/YYYY]
* 
* Modification Log:
* -------------------------------------------------------------------------------------------------------
* Developer                Date                   Modification ID      Description
* -------------------------------------------------------------------------------------------------------
* Deloitte               07/19/2022                                   Initial version
*********************************************************************************************************/
public Inherited Sharing class ContainerQuoteASOTentativeRecords {
	 public Id quoteId {get;set;}
    Public List<CONTAINER_Tentative_Production_Schedule__c> tentativeRecords {get;set;}
    public String breakLine {get;set;}
   	public ContainerQuoteASOTentativeRecords() {
         quoteId  = ApexPages.currentPage().getParameters().get('qid');
        // return null or empty list if the source quote Id is null
        try {
                tentativeRecords = [SELECT CONTAINER_TentativeProductionSchd_Qty__c,CONTAINER_Week_Of__c,CONTAINER_Factory__c,CONTAINER_TentativeProdSchd_Job__c FROM CONTAINER_Tentative_Production_Schedule__c
                where CONTAINER_Quote_Number__c=:quoteId WITH SECURITY_ENFORCED];
            breakLine = '\r\n\r\n&nbsp;TENTATIVE PRODUCTION SCHEDULE';
        }
    	catch(QueryException ex) {
            
    	}
    }
}