NATTQA-ENV/force-app/main/default/objects/CONTAINER_Tentative_Production_Schedule__c/CONTAINER_Tentative_Production_Schedule__c.object-meta.xml
<CustomObject>
    <label>Tentative Production Schedule</label>
    <nameField>
        <displayFormat>TPS-{0000}</displayFormat>
        <label>Tentative Production Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tentative Production Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/CONTAINER_Tentative_Production_Schedule__c/fields/CONTAINER_Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Quote_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Number</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Tentative Production Schedule</relationshipLabel>
    <relationshipName>Tentative_Production_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/CONTAINER_Tentative_Production_Schedule__c/fields/CONTAINER_TentativeProductionSchd_Qty__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_TentativeProductionSchd_Qty__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Sales_Region__c</fullName>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>APO</fullName>
            </value>
            <value>
                <fullName>NAO</fullName>
            </value>
            <value>
                <fullName>SNAO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Type__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Type__c</fullName>
    <description>CONTAINER QUOTE TYPES</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>End Customer Quote</fullName>
                <default>true</default>
                <label>End Customer Quote</label>
            </value>
            <value>
                <fullName>Stock Quote</fullName>
            </value>
            <value>
                <fullName>Cost PID quote</fullName>
            </value>
            <value>
                <fullName>Planning products spec quotes</fullName>
            </value>
            <value>
                <fullName>Internal Engineering</fullName>
                <label>Internal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/ContainerQuoteRelatedTentativeTest.cls
/********************************************************************************************************
* @author         Aman(Deloitte)
* @description    This is a test class for ContainerQuoteRelatedShipmentRecords class code coverage.
* @date           08/01/2022 [MM/DD/YYYY]
* 
* Modification Log:
* -------------------------------------------------------------------------------------------------------
* Developer                Date                   Modification ID      Description
* -------------------------------------------------------------------------------------------------------
* Deloitte               08/01/2022                                   Initial version
*********************************************************************************************************/
@isTest
public class ContainerQuoteRelatedTentativeTest {
    @testSetup 
    static void setup() {
        // This code runs as the system user
        Profile prof = [SELECT Id FROM Profile WHERE Name='CONTAINER Administrator'];
        User newUser = new User(Alias = 'contAdm', Email='contAdmin@carrier.com', LastName='AdminTest', ProfileId = prof.Id, 
                                UserName='testAdminUser@carrier.com', EmailEncodingKey='UTF-8', 
                                LanguageLocaleKey='en_US', LocaleSidKey='en_US', TimeZoneSidKey='America/Los_Angeles');
        insert newUser;
        
        System.runAs(newUser) {
    
            //Create New Quote Record with values
            id qteRecTypeID = Schema.SobjectType.SBQQ__Quote__c.getRecordTypeInfosByDeveloperName().get('CONTAINER_NT_Quote').getRecordTypeId();
            SBQQ__Quote__c newQuote = new SBQQ__Quote__c();
            newQuote.RecordTypeId = qteRecTypeID;
            newQuote.CONTAINER_Sales_Region__c = 'NAO';
            newQuote.CONTAINER_Type__c = 'Stock Quote';
            //Insert quote new record
            insert newQuote;

            
            
            
        } 
    }
    
   
    @isTest
    static void validateQuoteRelatedShipmentRecords2() {
        User containerAdmin = [select id from user where Alias = 'contAdm' limit 1];
        id qteRecTypeID = Schema.SobjectType.SBQQ__Quote__c.getRecordTypeInfosByDeveloperName().get('CONTAINER_NT_Quote').getRecordTypeId();
            SBQQ__Quote__c newQuote = new SBQQ__Quote__c();
            newQuote.RecordTypeId = qteRecTypeID;
            newQuote.CONTAINER_Sales_Region__c = 'NAO';
            newQuote.CONTAINER_Type__c = 'Stock Quote';
            //Insert quote new record
            insert newQuote;
        System.runAs(containerAdmin) {
            Test.startTest();
            CONTAINER_Tentative_Production_Schedule__c objTenProdSch = new CONTAINER_Tentative_Production_Schedule__c();
            objTenProdSch.CONTAINER_Quote_Number__c = newQuote.id;
            objTenProdSch.CONTAINER_TentativeProductionSchd_Qty__c = 1;
            Insert objTenProdSch;
            ContainerQuoteRelatedTentativeRecords RSD = new ContainerQuoteRelatedTentativeRecords();
            RSD.quoteId = newQuote.id;
            List<CONTAINER_Tentative_Production_Schedule__c> records = RSD.gettentativeRecords();
            Test.stopTest();
            
            //Validate the changes
        }
    }
    @isTest
    static void validateQuoteRelatedShipmentRecords3() {
        User containerAdmin = [select id from user where Alias = 'contAdm' limit 1];
        id qteRecTypeID = Schema.SobjectType.SBQQ__Quote__c.getRecordTypeInfosByDeveloperName().get('CONTAINER_NT_Quote').getRecordTypeId();
            SBQQ__Quote__c newQuote = new SBQQ__Quote__c();
            newQuote.RecordTypeId = qteRecTypeID;
            newQuote.CONTAINER_Sales_Region__c = 'NAO';
            newQuote.CONTAINER_Type__c = 'Stock Quote';
            //Insert quote new record
            insert newQuote;
        System.runAs(containerAdmin) {
            Test.startTest();
            ContainerQuoteRelatedTentativeRecords RSD = new ContainerQuoteRelatedTentativeRecords();
           // RSD.quoteId = newQuote.id;
            List<CONTAINER_Tentative_Production_Schedule__c> records = RSD.gettentativeRecords();
            Test.stopTest();
            
            //Validate the changes
        }
    }
    @isTest
    static void validateQuoteRelatedShipmentRecords4() {
        User containerAdmin = [select id from user where Alias = 'contAdm' limit 1];
        id qteRecTypeID = Schema.SobjectType.SBQQ__Quote__c.getRecordTypeInfosByDeveloperName().get('CONTAINER_NT_Quote').getRecordTypeId();
            SBQQ__Quote__c newQuote = new SBQQ__Quote__c();
            newQuote.RecordTypeId = qteRecTypeID;
            newQuote.CONTAINER_Sales_Region__c = 'NAO';
            newQuote.CONTAINER_Type__c = 'Stock Quote';
            //Insert quote new record
            insert newQuote;
        System.runAs(containerAdmin) {
            Test.startTest();
            ContainerQuoteRelatedTentativeRecords RSD = new ContainerQuoteRelatedTentativeRecords();
            RSD.quoteId = newQuote.Id;
            List<CONTAINER_Tentative_Production_Schedule__c> records = RSD.gettentativeRecords();
            Test.stopTest();
            
            //Validate the changes
        }
    }
}