NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/NATT_ProductInventoryItem__c.object-meta.xml
<CustomObject>
    <description>Contains current inventory levels at each warehouse for all B2B Commerce product items.</description>
    <label>Product Inventory Item</label>
    <nameField>
        <displayFormat>INV-{000000000}</displayFormat>
        <label>Product Inventory Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/fields/NATT_AvailabilityDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_AvailabilityDate__c</fullName>
    <description>Date the product item is expected to be available at the specified warehouse.</description>
    <label>Availability Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/fields/NATT_AvailableQuantity__c.field-meta.xml
<CustomField>
    <fullName>NATT_AvailableQuantity__c</fullName>
    <description>Currently available quantity of the product item at the specified warehouse. Expected whole number values.</description>
    <label>Available Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/fields/NATT_ProductItem__c.field-meta.xml
<CustomField>
    <fullName>NATT_ProductItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product item to which the available quantity applies</description>
    <label>Product Item</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Inventory Items</relationshipLabel>
    <relationshipName>Product_Inventory_Items_del</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/fields/NATT_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>NATT_Warehouse__c</fullName>
    <description>Warehouse containing the available quantity of the product item</description>
    <label>Warehouse</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ANA</fullName>
            </value>
            <value>
                <fullName>BNA</fullName>
            </value>
            <value>
                <fullName>CHI</fullName>
            </value>
            <value>
                <fullName>PAN</fullName>
            </value>
            <value>
                <fullName>TES</fullName>
            </value>
            <value>
                <fullName>ATL</fullName>
            </value>
            <value>
                <fullName>MEX</fullName>
            </value>
            <value>
                <fullName>MIA</fullName>
            </value>
            <value>
                <fullName>CTB01</fullName>
            </value>
            <value>
                <fullName>CTB02</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NAOCAP_Signal_Code_ANA__c.field-meta.xml
<CustomField>
    <fullName>NAOCAP_Signal_Code_ANA__c</fullName>
    <label>NAOCAP Signal Code ANA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NAOCAP_Signal_Code</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NAOCAP_Signal_Code_CHI__c.field-meta.xml
<CustomField>
    <fullName>NAOCAP_Signal_Code_CHI__c</fullName>
    <label>NAOCAP Signal Code CHI</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NAOCAP_Signal_Code</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NAOCAP_Signal_Code_PAN__c.field-meta.xml
<CustomField>
    <fullName>NAOCAP_Signal_Code_PAN__c</fullName>
    <label>NAOCAP Signal Code PAN</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NAOCAP_Signal_Code</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_SignalCode__c.field-meta.xml
<CustomField>
    <fullName>NATT_SignalCode__c</fullName>
    <description>JDE Signal Code for the item</description>
    <label>Signal Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>NLO</fullName>
            </value>
            <value>
                <fullName>NSI</fullName>
            </value>
            <value>
                <fullName>NSU</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S1D</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
            <value>
                <fullName>NRC</fullName>
            </value>
            <value>
                <fullName>BY2</fullName>
                <label>BUYER HOLD</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <label>NOT AVAILABLE</label>
            </value>
            <value>
                <fullName>OB1</fullName>
            </value>
            <value>
                <fullName>OBS</fullName>
            </value>
            <value>
                <fullName>PRC</fullName>
            </value>
            <value>
                <fullName>NEW</fullName>
            </value>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>PSR</fullName>
            </value>
            <value>
                <fullName>VIN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/NAOCAP_Signal_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
    </customValue>
    <customValue>
        <fullName>NLO</fullName>
    </customValue>
    <customValue>
        <fullName>NSI</fullName>
    </customValue>
    <customValue>
        <fullName>NSU</fullName>
    </customValue>
    <customValue>
        <fullName>S1</fullName>
    </customValue>
    <customValue>
        <fullName>S1D</fullName>
    </customValue>
    <customValue>
        <fullName>S2</fullName>
    </customValue>
    <customValue>
        <fullName>NRC</fullName>
    </customValue>
    <customValue>
        <fullName>BY2</fullName>
        <label>BUYER HOLD</label>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
        <label>NOT AVAILABLE</label>
    </customValue>
    <customValue>
        <fullName>OB1</fullName>
    </customValue>
    <customValue>
        <fullName>OBS</fullName>
    </customValue>
    <customValue>
        <fullName>PRC</fullName>
    </customValue>
    <customValue>
        <fullName>NEW</fullName>
    </customValue>
    <customValue>
        <fullName>FIN</fullName>
    </customValue>
    <customValue>
        <fullName>PSR</fullName>
    </customValue>
    <masterLabel>NAOCAP Signal Code</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/NAC_InventoryUtility.cls
public without sharing class NAC_InventoryUtility {
    //Method to get inventory based on product and warehouse
    @AuraEnabled
    public static NATT_ProductInventoryItem__c getProductAvailability(Id productId, String warehouse) {

        return [SELECT NATT_AvailableQuantity__c,NATT_AvailabilityDate__c,NATT_ProductItem__c,NATT_ProductItem__r.NATT_SignalCode__c,
                NATT_ProductItem__r.NAOCAP_Signal_Code_ANA__c,NATT_ProductItem__r.NAOCAP_Signal_Code_CHI__c,NATT_ProductItem__r.NAOCAP_Signal_Code_PAN__c,NATT_ProductItem__r.NATT_Core__c  
                FROM NATT_ProductInventoryItem__c
                WHERE NATT_ProductItem__c = :productId AND NATT_Warehouse__c =: warehouse LIMIT 1];
    }
    //Method to get inventory based on list of products and warehouse
    @AuraEnabled
    public static Map<Id, NATT_ProductInventoryItem__c> getCartAvailability(List<String> productIds, String warehouse) {
        Map<Id, NATT_ProductInventoryItem__c> piiMap = new Map<Id, NATT_ProductInventoryItem__c>();
        for (NATT_ProductInventoryItem__c pii : [
            SELECT
                NATT_AvailableQuantity__c,
                NATT_AvailabilityDate__c,
                NATT_ProductItem__c,
                NATT_ProductItem__r.NATT_SignalCode__c,
                NATT_ProductItem__r.NAOCAP_Signal_Code_ANA__c,NATT_ProductItem__r.NAOCAP_Signal_Code_CHI__c,NATT_ProductItem__r.NAOCAP_Signal_Code_PAN__c,NATT_ProductItem__r.NATT_Core__c 
            FROM NATT_ProductInventoryItem__c
            WHERE NATT_ProductItem__c = :productIds AND NATT_Warehouse__c =: warehouse
        ]) {
            piiMap.put(pii.NATT_ProductItem__c, pii);
        }
        return piiMap;
    }

    //Method to get inventory for all the warehouses for a product
    @AuraEnabled
    public static Map<String,NATT_ProductInventoryItem__c> getAllWarehouseAvailability(Id productId) {
        Map<String,NATT_ProductInventoryItem__c> productAndInventories = new Map<String,NATT_ProductInventoryItem__c>();
        for(NATT_ProductInventoryItem__c item:[SELECT NATT_AvailableQuantity__c,NATT_AvailabilityDate__c,NATT_ProductItem__c,NATT_ProductItem__r.NATT_SignalCode__c,NATT_Warehouse__c
                                                FROM NATT_ProductInventoryItem__c
                                                WHERE NATT_ProductItem__c = :productId]){
            productAndInventories.put(item.NATT_Warehouse__c,item);
        } 
        return productAndInventories;
    }
    
    
}