NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/NATT_ProductInventoryItem__c.object-meta.xml
<CustomObject>
    <description>Contains current inventory levels at each warehouse for all B2B Commerce product items.</description>
    <label>Product Inventory Item</label>
    <nameField>
        <displayFormat>INV-{000000000}</displayFormat>
        <label>Product Inventory Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/fields/NATT_AvailabilityDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_AvailabilityDate__c</fullName>
    <description>Date the product item is expected to be available at the specified warehouse.</description>
    <label>Availability Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/fields/NATT_AvailableQuantity__c.field-meta.xml
<CustomField>
    <fullName>NATT_AvailableQuantity__c</fullName>
    <description>Currently available quantity of the product item at the specified warehouse. Expected whole number values.</description>
    <label>Available Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/fields/NATT_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_P_N__c</fullName>
    <formula>NATT_ProductItem__r.NATT_P_N__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>P/N</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/fields/NATT_ProductItem__c.field-meta.xml
<CustomField>
    <fullName>NATT_ProductItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product item to which the available quantity applies</description>
    <label>Product Item</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Inventory Items</relationshipLabel>
    <relationshipName>Product_Inventory_Items_del</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/fields/NATT_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>NATT_Warehouse__c</fullName>
    <description>Warehouse containing the available quantity of the product item</description>
    <label>Warehouse</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ANA</fullName>
            </value>
            <value>
                <fullName>BNA</fullName>
            </value>
            <value>
                <fullName>CHI</fullName>
            </value>
            <value>
                <fullName>PAN</fullName>
            </value>
            <value>
                <fullName>TES</fullName>
            </value>
            <value>
                <fullName>ATL</fullName>
            </value>
            <value>
                <fullName>MEX</fullName>
            </value>
            <value>
                <fullName>MIA</fullName>
            </value>
            <value>
                <fullName>CTB01</fullName>
            </value>
            <value>
                <fullName>CTB02</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>NATT_Warehouse__c</fullName>
    <description>The Warehouse, or Depot, from which the order is shipping.</description>
    <label>Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Warehouse_Picklist</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_CoreItem_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_CoreItem_P_N__c</fullName>
    <description>Text field containing the part number of the core item. Core items are not stored in the product catalog.</description>
    <label>Core Item P/N</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_P_N__c</fullName>
    <description>The Part Number for NATT JDE</description>
    <label>Part Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_SignalCode__c.field-meta.xml
<CustomField>
    <fullName>NATT_SignalCode__c</fullName>
    <description>JDE Signal Code for the item</description>
    <label>Signal Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>NLO</fullName>
            </value>
            <value>
                <fullName>NSI</fullName>
            </value>
            <value>
                <fullName>NSU</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S1D</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
            <value>
                <fullName>NRC</fullName>
            </value>
            <value>
                <fullName>BY2</fullName>
                <label>BUYER HOLD</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <label>NOT AVAILABLE</label>
            </value>
            <value>
                <fullName>OB1</fullName>
            </value>
            <value>
                <fullName>OBS</fullName>
            </value>
            <value>
                <fullName>PRC</fullName>
            </value>
            <value>
                <fullName>NEW</fullName>
            </value>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>PSR</fullName>
            </value>
            <value>
                <fullName>VIN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_UOM_Conversion__c.field-meta.xml
<CustomField>
    <fullName>NATT_UOM_Conversion__c</fullName>
    <description>NATT unit of measure conversion factor</description>
    <label>UOM Conversion</label>
    <precision>15</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Warehouse_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ANA</fullName>
    </customValue>
    <customValue>
        <fullName>BNA</fullName>
    </customValue>
    <customValue>
        <fullName>CHI</fullName>
    </customValue>
    <customValue>
        <fullName>PAN</fullName>
    </customValue>
    <customValue>
        <fullName>ATL</fullName>
    </customValue>
    <customValue>
        <fullName>MEX</fullName>
    </customValue>
    <customValue>
        <fullName>MIA</fullName>
    </customValue>
    <customValue>
        <fullName>TES</fullName>
    </customValue>
    <customValue>
        <fullName>LATAM</fullName>
    </customValue>
    <customValue>
        <fullName>CTB01</fullName>
    </customValue>
    <masterLabel>NATT Warehouse Picklist</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/NATT_PpgCartController.cls
/**
 * @description Demonstrates how to make Apex calls to ConnectApi.CommerceCart class
 * to perform Cart Operations for B2B Commerce on Lightning.
 *
 * @see B2BUtils
 */
public with sharing class NATT_PpgCartController {
  /**
   * @description Demonstrates how to call ConnectApi.CommerceCart.getCartItems
   * @param  communityId The Id of the community from which the call originated
   * @param effectiveAccountId ID of the account for which the request is made. If null, defaults to the account ID for the context user.
   * @param activeCartOrId ID of the cart, active, or current.
   * @param pageParam Specifies the page token to be used to view a page of information.
   * @param sortParam Sort order for items in a cart.
   * @return CartItemCollection A collection of cart items
   */
  @AuraEnabled
  public static ConnectApi.CartItemCollection getCartItems(
    String communityId,
    String effectiveAccountId,
    String activeCartOrId,
    String pageParam,
    String sortParam
  ) {
    // Lookup the webstore ID associated with the community
    String webstoreId = B2BUtils.resolveCommunityIdToWebstoreId(communityId);

    // Get the ConnectApi.CartItemSortOrder enum value from string.
    // For the list of possible values, see:
    // see https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/connectAPI_enums.htm#cartItemSortOrderEnum
    ConnectApi.CartItemSortOrder resolvedSortParam = B2BUtils.resolveSortParam(
      sortParam
    );

    // For more details, see:
    // https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_ConnectAPI_CommerceCart_static_methods.htm
    ConnectApi.CartItemCollection cic = ConnectApi.CommerceCart.getCartItems(
      webstoreId,
      effectiveAccountId,
      activeCartOrId,
      'NATT_P_N__c,NATT_CoreItem_P_N__c,QuantityUnitOfMeasure,NATT_UOM_Conversion__c',
      pageParam,
      100,
      resolvedSortParam
    );

    if(cic.nextPageToken!=null){
      String nextPageToken = cic.nextPageToken;
      ConnectApi.CartItemCollection cicTemp;
      do{
        cicTemp = ConnectApi.CommerceCart.getCartItems(
          webstoreId,
          effectiveAccountId,
          activeCartOrId,
          'NATT_P_N__c,NATT_CoreItem_P_N__c,QuantityUnitOfMeasure,NATT_UOM_Conversion__c',
          nextPageToken,
          100,
          resolvedSortParam
        );
        cic.cartItems.addAll(cicTemp.cartItems);
        nextPageToken=cicTemp.nextPageToken;
      }while(nextPageToken!=null);
    }

    return cic;
  }

  /**
   * @description Demonstrates how to call ConnectApi.CommerceCart.updateCartItem
   * @param  communityId The Id of the community from which the call originated
   * @param effectiveAccountId ID of the account for which the request is made. If null, defaults to the account ID for the context user.
   * @param activeCartOrId ID of the cart, active, or current.
   * @param cartItemId ID of the cart item to be updated.
   * @return CartItem The updated cart item
   */
  @AuraEnabled
  public static ConnectApi.CartItem updateCartItem(
    String communityId,
    String effectiveAccountId,
    String activeCartOrId,
    String cartItemId,
    ConnectApi.CartItemInput cartItem
  ) {
    // Lookup the webstore ID associated with the community
    String webstoreId = B2BUtils.resolveCommunityIdToWebstoreId(communityId);

    // For more details, see:
    // https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_ConnectAPI_CommerceCart_static_methods.htm
    return ConnectApi.CommerceCart.updateCartItem(
      webstoreId,
      effectiveAccountId,
      activeCartOrId,
      cartItemId,
      cartItem
    );
  }

  /**
   * @description Demonstrates how to call ConnectApi.CommerceCart.deleteCartItem
   * @param  communityId The Id of the community from which the call originated
   * @param effectiveAccountId ID of the account for which the request is made. If null, defaults to the account ID for the context user.
   * @param activeCartOrId ID of the cart, active, or current.
   * @param cartItemId ID of the cart item to be deleted.
   */
  @AuraEnabled
  public static void deleteCartItem(
    String communityId,
    String effectiveAccountId,
    String activeCartOrId,
    String cartItemId
  ) {
    // Lookup the webstore ID associated with the community
    String webstoreId = B2BUtils.resolveCommunityIdToWebstoreId(communityId);

    // For more details, see:
    // https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_ConnectAPI_CommerceCart_static_methods.htm
    ConnectApi.CommerceCart.deleteCartItem(
      webstoreId,
      effectiveAccountId,
      activeCartOrId,
      cartItemId
    );
  }

  /**
   * @description Demonstrates how to call ConnectApi.CommerceCart.getCartSummary
   * @param  communityId The Id of the community from which the call originated
   * @param effectiveAccountId ID of the account for which the request is made. If null, defaults to the account ID for the context user.
   * @param activeCartOrId ID of the cart, active, or current.
   */
  @AuraEnabled
  public static ConnectApi.CartSummary getCartSummary(
    String communityId,
    String effectiveAccountId,
    String activeCartOrId
  ) {
    // Lookup the webstore ID associated with the community
    String webstoreId = B2BUtils.resolveCommunityIdToWebstoreId(communityId);

    // For more details, see:
    // https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_ConnectAPI_CommerceCart_static_methods.htm
    return ConnectApi.CommerceCart.getCartSummary(
      webstoreId,
      effectiveAccountId,
      activeCartOrId
    );
  }

  /**
   * @description Demonstrates how to call ConnectApi.CommerceCart.createCart
   * @param  communityId The Id of the community from which the call originated
   * @param effectiveAccountId ID of the account for which the request is made. If null, defaults to the account ID for the context user.
   */
  @AuraEnabled
  public static ConnectApi.CartSummary createCart(
    String communityId,
    String effectiveAccountId
  ) {
    // Lookup the webstore ID associated with the community
    String webstoreId = B2BUtils.resolveCommunityIdToWebstoreId(communityId);
    ConnectApi.CartInput cartInput = new ConnectApi.CartInput();
    cartInput.effectiveAccountId = effectiveAccountId;
    // For more details, see:
    // https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_ConnectAPI_CommerceCart_static_methods.htm
    return ConnectApi.CommerceCart.createCart(webstoreId, cartInput);
  }

  /**
   * @description Demonstrates how to call ConnectApi.CommerceCart.deleteCart
   * @param  communityId The Id of the community from which the call originated
   * @param effectiveAccountId ID of the account for which the request is made. If null, defaults to the account ID for the context user.
   * @param activeCartOrId ID of the cart, active, or current.
   */
  @AuraEnabled
  public static void deleteCart(
    String communityId,
    String effectiveAccountId,
    String activeCartOrId
  ) {
    // Lookup the webstore ID associated with the community
    String webstoreId = B2BUtils.resolveCommunityIdToWebstoreId(communityId);

    // For more details, see:
    // https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_ConnectAPI_CommerceCart_static_methods.htm
    ConnectApi.CommerceCart.deleteCart(
      webstoreId,
      effectiveAccountId,
      activeCartOrId
    );
  }

  @AuraEnabled
  public static Map<Id, NATT_ProductInventoryItem__c> getCartAvailability(
    List<String> productIds
  ) {
    Map<Id, NATT_ProductInventoryItem__c> piiMap = new Map<Id, NATT_ProductInventoryItem__c>();
    for (NATT_ProductInventoryItem__c pii : [
      SELECT
        NATT_AvailableQuantity__c,
        NATT_AvailabilityDate__c,
        NATT_ProductItem__c,
        NATT_ProductItem__r.NATT_SignalCode__c
      FROM NATT_ProductInventoryItem__c
      WHERE NATT_ProductItem__c = :productIds AND NATT_Warehouse__c = 'ATL'
    ]) {
      piiMap.put(pii.NATT_ProductItem__c, pii);
    }
    return piiMap;
  }
}