NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/NATT_PriceAdjustmentStaging__c.object-meta.xml
<CustomObject>
    <description>Staging object for imported PartsNet price adjustments (discount or markup) for the assorted Customer Price Group/Item Price Group combinations (RCGWEB22 &amp; RCGWEB25). Does not include quantity price break information.</description>
    <label>NATT Price Adjustment Staging</label>
    <nameField>
        <displayFormat>PAS-{000000000}</displayFormat>
        <label>NATT Price Adjustment Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NATT Price Adjustment Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_AdjustmentType__c.field-meta.xml
<CustomField>
    <fullName>NATT_AdjustmentType__c</fullName>
    <description>Alphanumeric code indicating the type of adjustment (e.x. REGD - Regular Discount, SURCHG - Surcharge)</description>
    <label>Adjustment Type</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_AdjustmentValue__c.field-meta.xml
<CustomField>
    <fullName>NATT_AdjustmentValue__c</fullName>
    <description>Contains the decimal percentage value that the list price or standard cost should be adjusted. If the value in NATT_AdjustmentName__c == SURCHG, this field will be interpreted as a MARKUP, if REGD, then will be interpreted as a discount.</description>
    <label>Adjustment Value</label>
    <precision>10</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_CustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>NATT_CustomerNumber__c</fullName>
    <description>Customer number this adjustment record applies to.</description>
    <label>Customer Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_CustomerPriceGroup__c.field-meta.xml
<CustomField>
    <fullName>NATT_CustomerPriceGroup__c</fullName>
    <description>Identifes the Customer Price Group to which the adjustment applies.</description>
    <label>Customer Price Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_EffectiveDate__c</fullName>
    <description>Date this price becomes effective</description>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_ExpiryDate__c</fullName>
    <description>Date this price expires and no longer applies</description>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_ItemPriceGroup__c.field-meta.xml
<CustomField>
    <fullName>NATT_ItemPriceGroup__c</fullName>
    <description>Identifies the item price group the adjustment applies to.</description>
    <label>Item Price Group</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/recordTypes/NATT_PPG.recordType-meta.xml
<RecordType>
    <fullName>NATT_PPG</fullName>
    <active>true</active>
    <label>NATT PPG</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_ItemPriceGroup__c.field-meta.xml
<CustomField>
    <fullName>NATT_ItemPriceGroup__c</fullName>
    <description>A number identifying the price group to which the item belongs</description>
    <label>Item Price Group</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_UnitCost__c.field-meta.xml
<CustomField>
    <fullName>NATT_UnitCost__c</fullName>
    <description>Contains the unit cost of the item in USD. The purpose of the field is to overcome a B2B Commerce limitation of 1 basis price per storefront, and is used when generating price book prices for internal PPG customers.</description>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/NattBatchProductPriceGroupAdjustmentTest.cls
@IsTest
private class NattBatchProductPriceGroupAdjustmentTest {
  @IsTest
    static void myUnitTest() {
        List<String> errorMessages = new List<String>();
        errorMessages.add('Error 1: Sample error message 1');
        errorMessages.add('Error 2: Sample error message 2');

        NattBatchProductPriceGroupAdjustment batch = new NattBatchProductPriceGroupAdjustment();
        Test.startTest();
        Database.executeBatch(batch);
        batch.sendMessage(errorMessages);
        Test.stopTest();
    }

    @TestSetup
    static void setupData() {
        Id pricebookId = Test.getStandardPricebookId();

        Pricebook2 standardPb = new Pricebook2(
            Id = pricebookId,
            IsActive = true
        );
        update standardPb;

        List<Product2> pList = new List<Product2>();
        pList.add(new Product2(Name = 'Test Product 1', IsActive = true, NATT_UnitCost__c = 1, NATT_ItemPriceGroup__c = '1'));
        pList.add(new Product2(Name = 'Test Product 2', IsActive = true, NATT_UnitCost__c = 2, NATT_ItemPriceGroup__c = '2'));
        pList.add(new Product2(Name = 'Test Product 3', IsActive = true, NATT_UnitCost__c = 3, NATT_ItemPriceGroup__c = '3'));
        insert pList;

        List<PricebookEntry> pbeList = new List<PricebookEntry>();
        pbeList.add(new PricebookEntry(
            Pricebook2Id = standardPb.Id,
            Product2Id = pList.get(0).Id,
            UnitPrice = 1,
            IsActive = true
        ));
        pbeList.add(new PricebookEntry(
            Pricebook2Id = standardPb.Id,
            Product2Id = pList.get(1).Id,
            UnitPrice = 2,
            IsActive = true
        ));
        pbeList.add(new PricebookEntry(
            Pricebook2Id = standardPb.Id,
            Product2Id = pList.get(2).Id,
            UnitPrice = 2,
            IsActive = true
        ));
        insert pbeList;

        List<NATT_PriceAdjustmentStaging__c> pasList = new List<NATT_PriceAdjustmentStaging__c>();
        Id rtId = Schema.SObjectType.NATT_PriceAdjustmentStaging__c.getRecordTypeInfosByDeveloperName().get('NATT_PPG').getRecordTypeId();
        pasList.add(new NATT_PriceAdjustmentStaging__c(NATT_EffectiveDate__c = Date.today(), NATT_ExpiryDate__c = Date.today().addDays(10), NATT_CustomerNumber__c = 0, NATT_ItemPriceGroup__c = '1', NATT_CustomerPriceGroup__c = 'CPG1', NATT_AdjustmentValue__c = 1, NATT_AdjustmentType__c = 'REGD', RecordTypeId = rtId));
        pasList.add(new NATT_PriceAdjustmentStaging__c(NATT_EffectiveDate__c = Date.today(), NATT_ExpiryDate__c = Date.today().addDays(10), NATT_CustomerNumber__c = 0, NATT_ItemPriceGroup__c = '2', NATT_CustomerPriceGroup__c = 'CPG2', NATT_AdjustmentValue__c = 20, NATT_AdjustmentType__c = 'SURCHG', RecordTypeId = rtId));
        pasList.add(new NATT_PriceAdjustmentStaging__c(NATT_EffectiveDate__c = Date.today(), NATT_ExpiryDate__c = Date.today().addDays(10), NATT_CustomerNumber__c = 0, NATT_ItemPriceGroup__c = '3', NATT_CustomerPriceGroup__c = 'CPG3', NATT_AdjustmentValue__c = -10, NATT_AdjustmentType__c = 'REGD', RecordTypeId = rtId));
        insert pasList;
    }
}