NATTQA-ENV/force-app/main/default/objects/NATT_AlternativeItem__c/NATT_AlternativeItem__c.object-meta.xml
<CustomObject>
    <description>Custom object for storing alternative item entries (e.g. items that supersede other catalog items)</description>
    <label>NATT Alternative Item</label>
    <nameField>
        <displayFormat>NAI-{00000000}</displayFormat>
        <label>NATT Alternative Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NATT Alternative Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_AlternativeItem__c/fields/NATT_AlternativeItem__c.field-meta.xml
<CustomField>
    <fullName>NATT_AlternativeItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Item that is being provided as an alternative to the Product Item</description>
    <inlineHelpText>Item that is being provided as an alternative to the Product Item</inlineHelpText>
    <label>Alternative Item</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>NATT Alternative Items (Alternative Item)</relationshipLabel>
    <relationshipName>NATT_Alternative_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_AlternativeItem__c/fields/NATT_EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_EffectiveDate__c</fullName>
    <description>Date the alternative item effectively supersedes the product item</description>
    <inlineHelpText>Date the alternative item effectively supersedes the product item</inlineHelpText>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_AlternativeItem__c/fields/NATT_ProductItem__c.field-meta.xml
<CustomField>
    <fullName>NATT_ProductItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Item that is being superseded by the item shown in the Alternative Item field</description>
    <inlineHelpText>Item that is being superseded by the item shown in the Alternative Item field</inlineHelpText>
    <label>Product Item</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>NATT Alternative Items</relationshipLabel>
    <relationshipName>NATT_Alternative_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/NATT_ItemPriceStaging__c.object-meta.xml
<CustomObject>
    <description>Staging object for imported PartsNet item pricing from JDE (RCGWEB23 &amp; RCGWEB26). Includes standard list prices, customer-specific item prices, and quantity price tiers</description>
    <label>NATT Item Price Staging</label>
    <nameField>
        <displayFormat>IPS-{0000000000}</displayFormat>
        <label>NATT Item Price Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NATT Item Price Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_EffectiveDate__c</fullName>
    <description>Date this price becomes effective</description>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/NATT_ProductInventoryItem__c.object-meta.xml
<CustomObject>
    <description>Contains current inventory levels at each warehouse for all B2B Commerce product items.</description>
    <label>Product Inventory Item</label>
    <nameField>
        <displayFormat>INV-{000000000}</displayFormat>
        <label>Product Inventory Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/fields/NATT_AvailabilityDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_AvailabilityDate__c</fullName>
    <description>Date the product item is expected to be available at the specified warehouse.</description>
    <label>Availability Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/fields/NATT_AvailableQuantity__c.field-meta.xml
<CustomField>
    <fullName>NATT_AvailableQuantity__c</fullName>
    <description>Currently available quantity of the product item at the specified warehouse. Expected whole number values.</description>
    <label>Available Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/fields/NATT_NSI_Availability__c.field-meta.xml
<CustomField>
    <fullName>NATT_NSI_Availability__c</fullName>
    <description>concatination of signal code and availablity</description>
    <formula>IF(ISPICKVAL(NATT_ProductItem__r.NATT_SignalCode__c , &quot;NSI&quot; ),&quot;NSI (&quot; &amp; Text(NATT_AvailableQuantity__c) &amp;&quot;)&quot;, &quot;&quot;)</formula>
    <label>NATT NSI Availability</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/fields/NATT_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_P_N__c</fullName>
    <formula>NATT_ProductItem__r.NATT_P_N__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>P/N</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/fields/NATT_ProductItem__c.field-meta.xml
<CustomField>
    <fullName>NATT_ProductItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product item to which the available quantity applies</description>
    <label>Product Item</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Inventory Items</relationshipLabel>
    <relationshipName>Product_Inventory_Items_del</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/fields/NATT_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>NATT_Warehouse__c</fullName>
    <description>Warehouse containing the available quantity of the product item</description>
    <label>Warehouse</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ANA</fullName>
            </value>
            <value>
                <fullName>BNA</fullName>
            </value>
            <value>
                <fullName>CHI</fullName>
            </value>
            <value>
                <fullName>PAN</fullName>
            </value>
            <value>
                <fullName>TES</fullName>
            </value>
            <value>
                <fullName>ATL</fullName>
            </value>
            <value>
                <fullName>MEX</fullName>
            </value>
            <value>
                <fullName>MIA</fullName>
            </value>
            <value>
                <fullName>CTB01</fullName>
            </value>
            <value>
                <fullName>CTB02</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>NATT_Warehouse__c</fullName>
    <description>The Warehouse, or Depot, from which the order is shipping.</description>
    <label>Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Warehouse_Picklist</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_P_N__c</fullName>
    <description>The Part Number for NATT JDE</description>
    <label>Part Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_SignalCode__c.field-meta.xml
<CustomField>
    <fullName>NATT_SignalCode__c</fullName>
    <description>JDE Signal Code for the item</description>
    <label>Signal Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>NLO</fullName>
            </value>
            <value>
                <fullName>NSI</fullName>
            </value>
            <value>
                <fullName>NSU</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S1D</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
            <value>
                <fullName>NRC</fullName>
            </value>
            <value>
                <fullName>BY2</fullName>
                <label>BUYER HOLD</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <label>NOT AVAILABLE</label>
            </value>
            <value>
                <fullName>OB1</fullName>
            </value>
            <value>
                <fullName>OBS</fullName>
            </value>
            <value>
                <fullName>PRC</fullName>
            </value>
            <value>
                <fullName>NEW</fullName>
            </value>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>PSR</fullName>
            </value>
            <value>
                <fullName>VIN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Warehouse_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ANA</fullName>
    </customValue>
    <customValue>
        <fullName>BNA</fullName>
    </customValue>
    <customValue>
        <fullName>CHI</fullName>
    </customValue>
    <customValue>
        <fullName>PAN</fullName>
    </customValue>
    <customValue>
        <fullName>ATL</fullName>
    </customValue>
    <customValue>
        <fullName>MEX</fullName>
    </customValue>
    <customValue>
        <fullName>MIA</fullName>
    </customValue>
    <customValue>
        <fullName>TES</fullName>
    </customValue>
    <customValue>
        <fullName>LATAM</fullName>
    </customValue>
    <customValue>
        <fullName>CTB01</fullName>
    </customValue>
    <masterLabel>NATT Warehouse Picklist</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/NATT_PriceAvailabilityController.cls
public with sharing class NATT_PriceAvailabilityController {
    @AuraEnabled
    public static NATT_ProductInventoryItem__c getAvailable(String productId) {
        List<NATT_ProductInventoryItem__c> piiList = new List<NATT_ProductInventoryItem__c>(
            [ SELECT NATT_AvailableQuantity__c, NATT_AvailabilityDate__c,NATT_NSI_Availability__c 
            FROM NATT_ProductInventoryItem__c
            WHERE NATT_ProductItem__c = :productId AND NATT_Warehouse__c = 'ATL'
            LIMIT 1]);
        system.debug('---> pli' +piiList);
        system.debug('---> productId' +productId);
        if(!piiList.isEmpty()){
            return piiList.get(0);
        }else{
            return new NATT_ProductInventoryItem__c();
        }   
    }
    
     @AuraEnabled
    public static NATT_ProductInventoryItem__c getCtmAvailablity(string productId,string warehouse){
        List<NATT_ProductInventoryItem__c> piiList = new List<NATT_ProductInventoryItem__c>(
            [ SELECT NATT_AvailableQuantity__c,NATT_Warehouse__c, NATT_AvailabilityDate__c,NATT_NSI_Availability__c 
            FROM NATT_ProductInventoryItem__c
            WHERE NATT_ProductItem__c = :productId AND  NATT_ProductItem__r.RecordType.Name ='CTM Product' and NATT_Warehouse__c = :warehouse
            LIMIT 1]);
        system.debug('---> pli' +piiList);
        system.debug('---> productId' +productId);
        if(!piiList.isEmpty()){
            return piiList.get(0);
        }else{
            return new NATT_ProductInventoryItem__c();
        }   
    }

    
    @AuraEnabled
    public static String getSolutionCenterURL(){
        Network solutionId = [SELECT ID FROM Network WHERE Name = 'Carrier SolutionCenter'];
        ConnectApi.Community solutionCenter = ConnectApi.Communities.getCommunity(solutionId.Id);
        return solutionCenter.siteUrl;
    }

    @AuraEnabled
    public static List<Product2> getHistory(String prodID) {
        
        List<Product2> returnList = new List<Product2>();
        //get the current product to add to the list
        Product2 currentProduct = [SELECT Id,NATT_P_N__c FROM Product2 WHERE Id=:prodId];
        
        //get any products that replace the current product
        for(NATT_AlternativeItem__c altItem : [SELECT Id, NATT_AlternativeItem__c, NATT_AlternativeItem__r.NATT_P_N__c 
                                               FROM NATT_AlternativeItem__c 
                                               WHERE NATT_ProductItem__c=:prodId 
                                               AND NATT_ProductItem__r.NATT_SignalCode__c='S2'
                                               ORDER BY NATT_EffectiveDate__c DESC]){
            returnList.add(new Product2(Id=altItem.NATT_AlternativeItem__c,NATT_P_N__c=altItem.NATT_AlternativeItem__r.NATT_P_N__c));
        }

        if(returnList.isEmpty()){     
            returnList.add(currentProduct);
        }

        //get all the products that have been superseded
        List<NATT_AlternativeItem__c> altItemList = new List<NATT_AlternativeItem__c>([SELECT Id,NATT_ProductItem__c,NATT_ProductItem__r.NATT_P_N__c 
                                            FROM NATT_AlternativeItem__c WHERE NATT_AlternativeItem__c=:prodId
                                            ORDER BY NATT_EffectiveDate__c DESC]);
        for(NATT_AlternativeItem__c altItem : altItemList){
            returnList.add(new Product2(Id=altItem.NATT_ProductItem__c,NATT_P_N__c=altItem.NATT_ProductItem__r.NATT_P_N__c));
        }
        if(altItemList.isEmpty()){
            returnList.add(currentProduct);
            //need to add part again because modal table starts at prodHist[1]
            returnList.add(currentProduct);
        }
        return returnList;
        /*
        //check if is original part and has been superseded
        List<NATT_AlternativeItem__c> pnHist = [
            SELECT Id, NATT_AlternativeItem__c, NATT_EffectiveDate__c
            FROM NATT_AlternativeItem__c
            WHERE NATT_ProductItem__c = :prodID
            ORDER BY NATT_EffectiveDate__c DESC
        ];
        
        List<Product2> prodHist = new List<Product2>();
        
        if (!pnHist.isEmpty()) {
            Set<Id> altItemIdSet = new Set<Id>();
            for (NATT_AlternativeItem__c ai : pnHist) {
                altItemIdSet.add(ai.NATT_AlternativeItem__c);
            }
            //go through original parts alternative items and add them to return list
            
            for(Product2 prod : [SELECT Id, NATT_P_N__c
                                FROM Product2
                                WHERE Id in :altItemIdSet]){
                prodHist.add(prod);
            }
            
            //add og part to list of part history
            Product2 prod = [SELECT Id, NATT_P_N__c FROM Product2 WHERE Id = :prodID];
            prodHist.add(prod);
        } else {
            //check if part has superseded original
            List<NATT_AlternativeItem__c> interm = [
                SELECT Id, NATT_ProductItem__c
                FROM NATT_AlternativeItem__c
                WHERE NATT_AlternativeItem__c = :prodID
                ORDER BY NATT_EffectiveDate__c
                LIMIT 1
            ];
            
            if (!interm.isEmpty()) {
                //get original parts alternative items list
                List<NATT_AlternativeItem__c> ogItemList = [
                    SELECT Id, NATT_AlternativeItem__c
                    FROM NATT_AlternativeItem__c
                    WHERE NATT_ProductItem__c = :interm[0].NATT_ProductItem__c
                    ORDER BY NATT_EffectiveDate__c DESC
                ];
                Set<Id> altItemIdSet = new Set<Id>();
                for(NATT_AlternativeItem__c ai : ogItemList){
                    altItemIdSet.add(ai.NATT_AlternativeItem__c);
                }
                //go through original parts alternative items and add them to return list
                for(Product2 prod : [SELECT Id, NATT_P_N__c
                                        FROM Product2
                                        WHERE Id IN :altItemIdSet]){
                    prodHist.add(prod);
                }
                
                //add og part to list of part history
                Product2 prod = [
                    SELECT Id, NATT_P_N__c
                    FROM Product2
                    WHERE Id = :interm[0].NATT_ProductItem__c
                ];
                prodHist.add(prod);
            } else {
                //if has never been superseded, add current part to part history
                Product2 prod = [SELECT Id, NATT_P_N__c
                                 FROM Product2
                                 WHERE Id = :prodID];
                prodHist.add(prod);
                //need to add part again because modal table starts at prodHist[1]
                prodHist.add(prod);
            }
        }        
        return prodHist;*/
    }
    
     /*@AuraEnabled
    public static ConnectApi.ProductDetail getUserGuide(String prodID) {

       
        List<ContentDocumentLink> file = [
            SELECT Id, LinkedEntityId, ContentDocumentId
            FROM ContentDocumentLink
            WHERE LinkedEntityId = :prodID
            LIMIT 1
        ];
        
        if (!file.isEmpty()) {
            List<ContentDocument> usrGuide = [
                SELECT Id, Title
                FROM ContentDocument
                WHERE Id = :file[0].ContentDocumentId
            ];
            return usrGuide;
        } else {
            List<ContentDocument> usrGuide = new List<ContentDocument>();
            return usrGuide;
        }
    }*/

    @AuraEnabled
    public static List<NATT_ItemPriceStaging__c> getQuantityBreakListPrices(){
        return NATT_PriceAvailWoSharing.getQuantityBreakListPrices();
    }
}