NATTQA-ENV/force-app/main/default/objects/Lead/fields/HBI_Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>HBI_Lead_Status__c</fullName>
    <label>HBI Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Customer Contacted</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Won Booked</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/Receiving_Business__c.field-meta.xml
<CustomField>
    <fullName>Receiving_Business__c</fullName>
    <label>Receiving Business</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sending_Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FSP Global Access - LENEL S2</fullName>
            </value>
            <value>
                <fullName>FSP Global Access - ONITY</fullName>
            </value>
            <value>
                <fullName>NORESCO</fullName>
            </value>
            <value>
                <fullName>Commercial HVAC Equipment</fullName>
            </value>
            <value>
                <fullName>Commercial HVAC Service</fullName>
            </value>
            <value>
                <fullName>HVAC Controls</fullName>
            </value>
            <value>
                <fullName>BSG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Lead/fields/Record_Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Reference_Id__c</fullName>
    <label>Record Reference Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/HBILeadsBatch.cls
/*
@name: HBILeadsBatch
@description: This Batch is used to update HBI Lead Status based on Source Lead
@date: 08 Aug 2020
@author: LTI
@changes:
*/
global class HBILeadsBatch implements Database.Batchable<sObject>,Database.Stateful,Database.AllowsCallouts {
    private String whereClause;
    global HBILeadsBatch(){
        whereClause = '';
    }
    global HBILeadsBatch(String whereClauseString){
        whereClause = whereClauseString;
    }
    
    /*
    @name: start
    @description: This method returns Lead records to be processed
    @date: 11 Aug 2020
    @author: LTI
    @changes:
    */
    global Database.Querylocator start (Database.BatchableContext BC) {
        String query;
        String filter = '(\'New\',\'Customer Contacted\',\'Qualified\',\'Accepted\',\'Rejected\',\'\')';
         if(whereClause.length() > 0){
            query = 'SELECT Id, HBI_Lead_Status__c, Record_Reference_Id__c, Receiving_Business__c FROM Lead'+whereClause;
        }else{
            query = 'SELECT Id, HBI_Lead_Status__c, Record_Reference_Id__c, Receiving_Business__c FROM Lead WHERE HBI_Lead_Status__c IN '+filter;
        } 
        return Database.getQueryLocator(query);
    }
    
    /*
    @name: execute
    @description: This method updates lead records in chunks
    @date: 11 Aug 2020
    @author: LTI
    @changes:
    */
    global void execute (Database.BatchableContext BC, List<Lead> scope) {
        List<Lead> leads = (List<Lead>) scope;
        LeadController.processDataFromAllOrgs(leads);
    }
    
    /*
    @name: execute
    @description: finish method
    @date: 11 Aug 2020
    @author: LTI
    @changes:
    */
    global void finish(Database.BatchableContext BC){  
    }
    
}