NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/CONTAINER_Customer.recordType-meta.xml
<RecordType>
    <fullName>CONTAINER_Customer</fullName>
    <active>true</active>
    <description>Record type for Container Customer Account</description>
    <label>CONTAINER Customer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Opportunity/recordTypes/CONTAINER_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>CONTAINER_Opportunity</fullName>
    <active>true</active>
    <businessProcess>CONTAINER Opportunity Sales Process</businessProcess>
    <description>Container opportunity report type for sales user</description>
    <label>CONTAINER Opportunity</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_P_N__c</fullName>
    <description>The Part Number for NATT JDE</description>
    <label>Part Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Model_Number__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Model_Number__c</fullName>
    <label>Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CONTAINER_Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Sales_Region__c</fullName>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>APO</fullName>
            </value>
            <value>
                <fullName>NAO</fullName>
            </value>
            <value>
                <fullName>SNAO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/CONTAINER_Model_Number__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Model_Number__c</fullName>
    <description>This field is used to store the model number for selected product.</description>
    <inlineHelpText>This field is used to store the model number for selected product.</inlineHelpText>
    <label>Model Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_P_N__c</fullName>
    <description>for NATT quotes</description>
    <label>P/N</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Bundle__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Bundle__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this line item represents a package; meaning, it includes other line items in this quote.</description>
    <inlineHelpText>Indicates whether this line item represents a package; meaning, it includes other line items in this quote.</inlineHelpText>
    <label>Package</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/CONTAINER_Quote_Summary_Page_Helper_Test.cls
@isTest
public class CONTAINER_Quote_Summary_Page_Helper_Test {
    
    @testsetup
    static void testName()
    {
        Test.startTest();
        //creating account record-
        id accRecTypeID = Schema.SobjectType.Account.getRecordTypeInfosByDeveloperName().get('CONTAINER_Customer').getRecordTypeId();
        Account acc = new Account();
        acc.Name = 'Test Acc1'; 
        acc.RecordTypeId = accRecTypeID;
        insert acc;
        
        //creating product record-
        Product2 p = new Product2();
        p.Name = ' Test Product ';
        p.Description='Test Product Entry For Product';
        p.productCode = 'SJ PD 1';
        p.isActive = true;
        insert p;
        
        // insert pricebook entry for the product
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry pbe = new PricebookEntry(Product2Id = p.Id,
                                         pricebook2Id = pricebookId,
                                         unitprice=100, isActive=true);
  		insert pbe;
        
        //creating opportunity record-
        id oppRecTypeID = Schema.SobjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('CONTAINER_Opportunity').getRecordTypeId();
        Opportunity opp = new Opportunity();
        opp.RecordTypeId = oppRecTypeID;
        opp.AccountId = acc.Id;
        opp.Name = 'test opp';
        opp.CloseDate= System.Today();
        opp.StageName='new';
        opp.Pricebook2Id = Test.getStandardPricebookId();
        insert opp;
        
        //creating quote record-
        id qteRecTypeID = Schema.SobjectType.SBQQ__Quote__c.getRecordTypeInfosByDeveloperName().get('CONTAINER_GENSET_Quote').getRecordTypeId();
        SBQQ__Quote__c qteRec = new SBQQ__Quote__c();
        qteRec.CONTAINER_Sales_Region__c = 'EMEA';
        qteRec.RecordTypeId = qteRecTypeID;
        qteRec.SBQQ__Opportunity2__c = opp.Id;
        qteRec.CONTAINER_Model_Number__c = '69NT40-489-114';
        insert qteRec;

        //Creating User
        String uniqueUserName = 'ctsalesuser' + DateTime.now().getTime() + '@testorg.com';
        // This code runs as the system user
        Profile prof = [SELECT Id FROM Profile WHERE Name='CONTAINER Sales'];
        User u = new User(Alias = 'ctSales', Email='salesuser@testorg.com',
                            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                            LocaleSidKey='en_US', ProfileId = prof.Id,TimeZoneSidKey='America/Los_Angeles',
                            UserName=uniqueUserName);
        insert u;

        Test.stopTest();
    }

    @isTest
    public static void test1(){
        
        SBQQ__QuoteLine__c qtLine = new SBQQ__QuoteLine__c();
        qtLine.SBQQ__Bundle__c = true;
        qtLine.NATT_P_N__c = 'SPARE PARTS';
        qtLine.SBQQ__Quote__c = [select id from SBQQ__Quote__c limit 1].Id;
        qtLine.SBQQ__Product__c = [select id from Product2 limit 1].Id;
        insert qtLine;
        
        List<CONTAINER_Quote_Summary_Page_Helper.DataWrapper> result = new List<CONTAINER_Quote_Summary_Page_Helper.DataWrapper>();
        System.runAs(new User(Id = Userinfo.getUserId())) {
            result = CONTAINER_Quote_Summary_Page_Helper.getQuoteSummary(qtLine.SBQQ__Quote__c);
        }
        system.assert(result.size()>0 , 'Checking result is not Null');
    }

    @isTest
    public static void test2(){
        
        //creating quoteline items records-
        SBQQ__QuoteLine__c qtLine = new SBQQ__QuoteLine__c();
        qtLine.NATT_P_N__c = 'Extended Warranty Bundle';
        qtLine.SBQQ__Quote__c = [select id from SBQQ__Quote__c limit 1].Id;
        qtLine.SBQQ__Product__c = [select id from Product2 limit 1].Id;
        insert qtLine;
        
        List<CONTAINER_Quote_Summary_Page_Helper.DataWrapper> result = new List<CONTAINER_Quote_Summary_Page_Helper.DataWrapper>();
        System.runAs(new User(Id = Userinfo.getUserId())) {
            result = CONTAINER_Quote_Summary_Page_Helper.getQuoteSummary(qtLine.SBQQ__Quote__c);
        }
        system.assert(result.size()>0 , 'Checking result is not Null');
    }
    
    @isTest
    public static void test3(){
        
        //creating product record-
        Product2 p = new Product2();
        p.Name = ' Test Product ';
        p.Description='Test Product Entry For Product';
        p.productCode = 'Reserves Applied Sales';
        p.isActive = true;
        insert p;
        
        //creating quoteline items records-
        SBQQ__QuoteLine__c qtLine = new SBQQ__QuoteLine__c();
        qtLine.SBQQ__Quote__c = [select id from SBQQ__Quote__c limit 1].Id;
        qtLine.SBQQ__Product__c = p.Id;
        insert qtLine;
        
        List<CONTAINER_Quote_Summary_Page_Helper.DataWrapper> result = new List<CONTAINER_Quote_Summary_Page_Helper.DataWrapper>();
        System.runAs(new User(Id = Userinfo.getUserId())) {
            result = CONTAINER_Quote_Summary_Page_Helper.getQuoteSummary(qtLine.SBQQ__Quote__c);
        }
        system.assert(result.size()>0 , 'Checking result is not Null');
    }
    
    @isTest
    public static void test3Method1(){
        
        //creating product record-
        Product2 p = new Product2();
        p.Name = ' Test Product ';
        p.Description='Test Product Entry For Product';
        p.productCode = 'Reserves Applied Sales';
        p.isActive = true;
        insert p;
        
        //creating quoteline items records-
        SBQQ__QuoteLine__c qtLine = new SBQQ__QuoteLine__c();
        qtLine.SBQQ__Quote__c = [select id from SBQQ__Quote__c limit 1].Id;
        qtLine.SBQQ__Product__c = p.Id;
        qtLine.CONTAINER_Warranty_Description__c = 'Test';
        insert qtLine;
        
        List<CONTAINER_Quote_Summary_Page_Helper.DataWrapper> result = new List<CONTAINER_Quote_Summary_Page_Helper.DataWrapper>();
        System.runAs(new User(Id = Userinfo.getUserId())) {
            result = CONTAINER_Quote_Summary_Page_Helper.getQuoteSummary(qtLine.SBQQ__Quote__c);
        }
        system.assert(result.size()>0 , 'Checking result is not Null');
    }
    
    @isTest
    public static void test4(){
        
        //creating product record-
        Product2 p = new Product2();
        p.Name = ' Test Product ';
        p.Description='Test Product Entry For Product';
        p.productCode = 'Reserves Applied Cost';
        p.isActive = true;
        insert p;
        
        //creating quoteline items records-
        SBQQ__QuoteLine__c qtLine = new SBQQ__QuoteLine__c();
        qtLine.SBQQ__Quote__c = [select id from SBQQ__Quote__c limit 1].Id;
        qtLine.SBQQ__Product__c = p.Id;
        insert qtLine;
        
        List<CONTAINER_Quote_Summary_Page_Helper.DataWrapper> result = new List<CONTAINER_Quote_Summary_Page_Helper.DataWrapper>();
        System.runAs(new User(Id = Userinfo.getUserId())) {
            result = CONTAINER_Quote_Summary_Page_Helper.getQuoteSummary(qtLine.SBQQ__Quote__c);
        }
        system.assert(result.size()>0 , 'Checking result is not Null');
    }
    
    @isTest
    public static void test4Method1(){
        
        //creating product record-
        Product2 p = new Product2();
        p.Name = ' Test Product ';
        p.Description='Test Product Entry For Product';
        p.productCode = 'Reserves Applied Cost';
        p.isActive = true;
        insert p;
        
        //creating quoteline items records-
        SBQQ__QuoteLine__c qtLine = new SBQQ__QuoteLine__c();
        qtLine.SBQQ__Quote__c = [select id from SBQQ__Quote__c limit 1].Id;
        qtLine.SBQQ__Product__c = p.Id;
        qtLine.CONTAINER_Warranty_Description__c = 'Test';
        insert qtLine;
        
        List<CONTAINER_Quote_Summary_Page_Helper.DataWrapper> result = new List<CONTAINER_Quote_Summary_Page_Helper.DataWrapper>();
        System.runAs(new User(Id = Userinfo.getUserId())) {
            result = CONTAINER_Quote_Summary_Page_Helper.getQuoteSummary(qtLine.SBQQ__Quote__c);
        }
        system.assert(result.size()>0 , 'Checking result is not Null');
    }
}