NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>NATT End User/End Customer Accounts</description>
    <label>Customer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/NATT_B2B_Shipping_Option__c/NATT_B2B_Shipping_Option__c.object-meta.xml
<CustomObject>
    <label>B2B Shipping Option</label>
    <nameField>
        <label>B2B Shipping Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2B Shipping Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_B2B_Shipping_Option__c/fields/NATT_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>NATT_Order_Type__c</fullName>
    <label>Order Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Order_Type</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_B2B_Shipping_Option__c/fields/NATT_Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>NATT_Shipping_Method__c</fullName>
    <label>Shipping Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Shipment_Method</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_B2B_Shipping_Option__c/recordTypes/NATT_Shipment.recordType-meta.xml
<RecordType>
    <fullName>NATT_Shipment</fullName>
    <active>true</active>
    <label>NATT Shipment</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/WebCart/fields/NATT_Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>NATT_Shipping_Method__c</fullName>
    <description>3-Digit JDE code representing the shipping method</description>
    <label>Shipping Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Shipment_Method</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Order_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>4</fullName>
        <label>Stock</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Same Day</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
        <label>Unit Down</label>
    </customValue>
    <customValue>
        <fullName>TES</fullName>
    </customValue>
    <customValue>
        <fullName>CTM</fullName>
    </customValue>
    <customValue>
        <fullName>CTBR</fullName>
    </customValue>
    <masterLabel>NATT Order Type</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/NATT_B2bDeliveryTest.cls
@IsTest
private class NATT_B2bDeliveryTest {
	@IsTest
    static void validTest(){        
        Account a = new Account(Name='TestAccount');
        insert a;
        Contact contact = new Contact(LastName='TestContact', AccountId=a.Id);
        insert contact;
        
        BuyerAccount buyerAccount = new BuyerAccount();
        buyerAccount.BuyerId = a.Id;
        buyerAccount.Name = 'Test Buyer Account (BA-AJ)';
        buyerAccount.IsActive = true;
        insert buyerAccount;

        WebStore webStore = new WebStore(Name='Performance Parts');
		insert webstore;
        
        WebCart cart = new WebCart(Name='Cart', WebStoreId=webStore.Id, AccountId=a.Id);
        insert cart;
        
        CartDeliveryGroup cartDeliveryGroup = new CartDeliveryGroup(CartId=cart.Id, Name='Default Delivery');
        insert cartDeliveryGroup;
        
        NATT_B2bDelivery.SyncDeliveryActionRequest ar = new NATT_B2bDelivery.SyncDeliveryActionRequest();
        ar.cartId=cart.Id;
        ar.orderType='1';
        
        NATT_B2bDelivery.syncDelivery(new List<NATT_B2bDelivery.SyncDeliveryActionRequest>{ar});        
    }
    
    @IsTest
    static void testNoCart(){        
        
        NATT_B2bDelivery.SyncDeliveryActionRequest ar = new NATT_B2bDelivery.SyncDeliveryActionRequest();
        ar.cartId='';
        ar.orderType='1';
        try{
        	NATT_B2bDelivery.syncDelivery(new List<NATT_B2bDelivery.SyncDeliveryActionRequest>{ar});        
        }catch(Exception e){
            
        }
    }
    
    @IsTest
    static void testNoCartDeliveryGroup(){        
        Account a = new Account(Name='TestAccount');
        insert a;
        Contact contact = new Contact(LastName='TestContact', AccountId=a.Id);
        insert contact;
        
        BuyerAccount buyerAccount = new BuyerAccount();
        buyerAccount.BuyerId = a.Id;
        buyerAccount.Name = 'Test Buyer Account (BA-AJ)';
        buyerAccount.IsActive = true;
        insert buyerAccount;

        WebStore webStore = new WebStore(Name='Performance Parts');
		insert webstore;
        
        WebCart cart = new WebCart(Name='Cart', WebStoreId=webStore.Id, AccountId=a.Id);
        insert cart;
        
        NATT_B2bDelivery.SyncDeliveryActionRequest ar = new NATT_B2bDelivery.SyncDeliveryActionRequest();
        ar.cartId=cart.Id;
        ar.orderType='1';
        try{
        	NATT_B2bDelivery.syncDelivery(new List<NATT_B2bDelivery.SyncDeliveryActionRequest>{ar});        
        }catch(Exception e){
            
        }
    }
    
    @TestSetup
    static void makeData(){
        Id rtId = [SELECT Id FROM RecordType WHERE SobjectType='NATT_B2B_Shipping_Option__c' AND DeveloperName='NATT_Shipment'].Id;
        
        List<NATT_B2B_Shipping_Option__c> soList = new List<NATT_B2B_Shipping_Option__c>();
        soList.add(new NATT_B2B_Shipping_Option__c(Name='BW1 - BESTWAY',RecordTypeId=rtId,
                                                                         NATT_Order_Type__c='2;4;1',NATT_Shipping_Method__c='BW1'));
        
        soList.add(new NATT_B2B_Shipping_Option__c(Name='CR1 - CUSTOMER ROUTING',RecordTypeId=rtId,
                                                                         NATT_Order_Type__c='2;1',NATT_Shipping_Method__c='CR1'));
        
        soList.add(new NATT_B2B_Shipping_Option__c(Name='FX1 - FEDEX - NEXT DAY AIR',RecordTypeId=rtId,
                                                                         NATT_Order_Type__c='2;1',NATT_Shipping_Method__c='FX1'));
        
        soList.add(new NATT_B2B_Shipping_Option__c(Name='FX2 - FEDEX - 2ND DAY AIR',RecordTypeId=rtId,
                                                                         NATT_Order_Type__c='2;1',NATT_Shipping_Method__c='FX2'));
        
        soList.add(new NATT_B2B_Shipping_Option__c(Name='FX3 - FEDEX - 3RD DAY AIR',RecordTypeId=rtId,
                                                                         NATT_Order_Type__c='2;1',NATT_Shipping_Method__c='FX3'));
        
        soList.add(new NATT_B2B_Shipping_Option__c(Name='FXG - FEDEX - GROUND',RecordTypeId=rtId,
                                                                         NATT_Order_Type__c='2;1',NATT_Shipping_Method__c='FXG'));
        
        soList.add(new NATT_B2B_Shipping_Option__c(Name='OF - OCEAN FREIGHT',RecordTypeId=rtId,
                                                                         NATT_Order_Type__c='2;1',NATT_Shipping_Method__c='OF'));
        
        soList.add(new NATT_B2B_Shipping_Option__c(Name='AF - AIR FREIGHT',RecordTypeId=rtId,
                                                                         NATT_Order_Type__c='2;1',NATT_Shipping_Method__c='AF'));
        
        insert soList;
    }
}