NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>NATT End User/End Customer Accounts</description>
    <label>Customer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Order/fields/CTBR_TaxObservation__c.field-meta.xml
<CustomField>
    <fullName>CTBR_TaxObservation__c</fullName>
    <label>Tax Observation</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Dealer_Comments__c.field-meta.xml
<CustomField>
    <fullName>NATT_Dealer_Comments__c</fullName>
    <description>NATT</description>
    <label>Dealer Comments</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>NATT_Order_Status__c</fullName>
    <description>NATT</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enter Order (Default Value)</fullName>
            </value>
            <value>
                <fullName>Sabrix Run</fullName>
            </value>
            <value>
                <fullName>Fulfillment Run</fullName>
            </value>
            <value>
                <fullName>Order Acknowledge</fullName>
            </value>
            <value>
                <fullName>Release Order for Shipment</fullName>
            </value>
            <value>
                <fullName>Credit Check for Shipment</fullName>
            </value>
            <value>
                <fullName>Ready to Print Pick Slip</fullName>
            </value>
            <value>
                <fullName>Ready for Picking</fullName>
            </value>
            <value>
                <fullName>Ready for Shipping</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Sabrix</fullName>
            </value>
            <value>
                <fullName>Invoicing</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Not Shipped</fullName>
            </value>
            <value>
                <fullName>Partially Shipped</fullName>
            </value>
            <value>
                <fullName>Awaiting Pricing</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Approval</fullName>
            </value>
            <value>
                <fullName>Customer Approved</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>No Enviado</fullName>
            </value>
            <value>
                <fullName>Envío parcial</fullName>
            </value>
            <value>
                <fullName>Completo</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Shipment_Method__c.field-meta.xml
<CustomField>
    <fullName>NATT_Shipment_Method__c</fullName>
    <description>NATT</description>
    <label>Shipment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Shipment_Method</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Shipment_Terms__c.field-meta.xml
<CustomField>
    <fullName>NATT_Shipment_Terms__c</fullName>
    <description>NATT</description>
    <label>Shipment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Shipment_Terms</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>The quote where the order is created from.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/Sent_to_SAP__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will be sent when Orders are sent to SAP in GET Requests.</description>
    <label>Sent to SAP</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/CTBR_SapItemStatus__c.field-meta.xml
<CustomField>
    <fullName>CTBR_SapItemStatus__c</fullName>
    <label>SAP Item Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>NATT_Product_Name__c</fullName>
    <description>used in flow to present the name of the order product during selection</description>
    <formula>Product2.Name</formula>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <formula>Product2.NATT_P_N__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Part Number</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/Purchase_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Number__c</fullName>
    <formula>Order.NATT_Purchase_Order__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Purchase Order Number</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CTBR_Freight_Terms__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Freight_Terms__c</fullName>
    <label>Freight Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CTBR_Quote_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Quote_Delivery_Date__c</fullName>
    <label>Quote Delivery Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Dealer_Comments__c.field-meta.xml
<CustomField>
    <fullName>NATT_Dealer_Comments__c</fullName>
    <description>NATT</description>
    <label>Dealer Comments</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Quote_Request_Date__c.field-meta.xml
<CustomField>
    <fullName>NATT_Quote_Request_Date__c</fullName>
    <description>NATT</description>
    <label>Quote Request Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Shipment_Method__c.field-meta.xml
<CustomField>
    <fullName>NATT_Shipment_Method__c</fullName>
    <description>NATT</description>
    <label>Shipment Method</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Product_Family__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BW</fullName>
                <label>Best Way</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Customer Pickup</label>
            </value>
            <value>
                <fullName>ABF</fullName>
            </value>
            <value>
                <fullName>OTH</fullName>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Shipment_Terms__c.field-meta.xml
<CustomField>
    <fullName>NATT_Shipment_Terms__c</fullName>
    <description>NATT</description>
    <label>Shipment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Shipment_Terms</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PaymentTerms__c</fullName>
    <description>Terms that govern payment of the items in this quote.</description>
    <inlineHelpText>Terms that govern payment of the items in this quote.</inlineHelpText>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Due on receipt</fullName>
            </value>
            <value>
                <fullName>Net 15</fullName>
            </value>
            <value>
                <fullName>Net 30</fullName>
                <default>true</default>
                <label>Net 30</label>
            </value>
            <value>
                <fullName>Net 45</fullName>
            </value>
            <value>
                <fullName>Net 55</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
            <value>
                <fullName>Net 90</fullName>
            </value>
            <value>
                <fullName>Net 120</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/Sent_to_SAP__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will be set to Yes if Quote has been transferred to SAP via a GET Operation</description>
    <label>Sent to SAP</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Shipment_Terms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BIL</fullName>
        <label>Bill to Customer</label>
    </customValue>
    <customValue>
        <fullName>PPD</fullName>
        <label>Prepaid Freight</label>
    </customValue>
    <customValue>
        <fullName>COL</fullName>
        <label>Collect</label>
    </customValue>
    <customValue>
        <fullName>CPU</fullName>
        <label>Customer Pickup</label>
    </customValue>
    <customValue>
        <fullName>PPA</fullName>
        <label>Prepaid and Allowed</label>
    </customValue>
    <customValue>
        <fullName>PPB</fullName>
        <label>Prepaid and Billed</label>
    </customValue>
    <customValue>
        <fullName>EXW</fullName>
        <label>EXW - EX Works</label>
    </customValue>
    <customValue>
        <fullName>CIF</fullName>
    </customValue>
    <customValue>
        <fullName>DDP</fullName>
    </customValue>
    <customValue>
        <fullName>FOB</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>999</fullName>
    </customValue>
    <customValue>
        <fullName>AAA</fullName>
    </customValue>
    <customValue>
        <fullName>ABF</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AF1</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AVE</fullName>
    </customValue>
    <customValue>
        <fullName>BCB</fullName>
    </customValue>
    <customValue>
        <fullName>BW</fullName>
    </customValue>
    <customValue>
        <fullName>BW1</fullName>
    </customValue>
    <customValue>
        <fullName>CAR</fullName>
    </customValue>
    <masterLabel>Shipment Terms</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/ctbrApprovedOrderParts_Test.cls
@isTest(seeAllData = true)
public class ctbrApprovedOrderParts_Test {
    public static Order order;
    public static OrderItem orderItem;
    public static Account acc;
    public static SBQQ__Quote__c quote;
    public static Product2 testProduct;
    
    static void setData() {
        acc = new Account();
        acc.Name = 'Test';
        insert acc;

        quote = new SBQQ__Quote__c();
        quote.NATT_Quote_Request_Date__c = date.today();
        quote.NATT_Dealer_Comments__c = 'Test';
        quote.CTBR_Quote_Delivery_Date__c = date.today().addDays(1);
        quote.CTBR_Freight_Terms__c = 'CIF';
        //quote.NATT_Shipment_Method__c = 'Best Way';
        quote.SBQQ__PaymentTerms__c = 'Net 31';
        insert quote;
        
        testProduct = new Product2();
        testProduct.Name = 'Product Test';              
        insert testProduct;
        
        Recordtype recType = [select id,name,SobjectType from RecordType where name = 'CTBR Parts Order'];
        
        order = new Order ();
        order.Status = 'Draft';
        order.RecordTypeId = recType.Id;
        order.CTBR_TaxObservation__c = 'Test';
        order.NATT_Dealer_Comments__c = 'ok';
        //order.NATT_Shipment_Method__c = 'BW1';
        order.NATT_Shipment_Terms__c = 'COL';
        order.AccountId = acc.id;
        order.EffectiveDate = date.today();
        //order.SBQQ__Quote__c = quote.id;
        insert order;
        order.NATT_Order_Status__c = 'Customer Approved';
        update order;
        
        orderItem = new OrderItem();
        orderItem.Quantity = 10;
        orderItem.UnitPrice = 100;
        orderItem.ListPrice = 200;
        orderItem.OrderId = order.Id;
        orderItem.Product2Id = testProduct.Id; 
        try {
            insert orderItem;
        } catch (Exception e) {
            e.getMessage();
        }
    }
    
    static testMethod void testgetOrderandQuote() {
        setData();
        Order ord =  [SELECT id,recordtype.name,Sent_to_SAP__c,SBQQ__Quote__c,Status,AccountId,EffectiveDate,NATT_Order_Status__c,
                      (select id,Product2Id,CTBR_SapItemStatus__c,Purchase_Order_Number__c,Part_Number__c,NATT_Product_Name__c,OrderItemNumber,Quantity,
                      UnitPrice,ListPrice,TotalPrice from orderitems) FROM Order where id =: order.id];
        system.debug('ord-->>'+ord);
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/retrieveApprovedPartsOrders/' + ord.Id;
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        try {
            ctbrOrderInboundApproved_Parts.getOrderandOrdItem();
        } catch (Exception e) {}
        Test.stopTest();
        system.assertEquals(ord.Sent_to_SAP__c, false);
        system.assertEquals(ord.Status, 'Draft');
        system.assertEquals(ord.AccountId, acc.id);
        system.assertEquals(ord.EffectiveDate,date.today());
    }   
}