NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Accounts</description>
    <label>Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>NATT_Order_Status__c</fullName>
    <description>NATT</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enter Order (Default Value)</fullName>
            </value>
            <value>
                <fullName>Sabrix Run</fullName>
            </value>
            <value>
                <fullName>Fulfillment Run</fullName>
            </value>
            <value>
                <fullName>Order Acknowledge</fullName>
            </value>
            <value>
                <fullName>Release Order for Shipment</fullName>
            </value>
            <value>
                <fullName>Credit Check for Shipment</fullName>
            </value>
            <value>
                <fullName>Ready to Print Pick Slip</fullName>
            </value>
            <value>
                <fullName>Ready for Picking</fullName>
            </value>
            <value>
                <fullName>Ready for Shipping</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Sabrix</fullName>
            </value>
            <value>
                <fullName>Invoicing</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Not Shipped</fullName>
            </value>
            <value>
                <fullName>Partially Shipped</fullName>
            </value>
            <value>
                <fullName>Awaiting Pricing</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Approval</fullName>
            </value>
            <value>
                <fullName>Customer Approved</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>No Enviado</fullName>
            </value>
            <value>
                <fullName>Envío parcial</fullName>
            </value>
            <value>
                <fullName>Completo</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>The quote where the order is created from.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/recordTypes/NATT_Units_Order.recordType-meta.xml
<RecordType>
    <fullName>NATT_Units_Order</fullName>
    <active>true</active>
    <description>NATT Units Order</description>
    <label>NATT Units Order</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/NATT_Constants.cls
public with sharing class NATT_Constants {
    
    /* QUOTE CONSTANTS */
    public static final String QUOTE_DRAFT = 'Draft';
    public static final String QUOTE_PENDING_APPROVAL = 'Pending Approval';
    public static final List<String> QUOTE_STATUS_IN_PROGRESS = getQuoteStatusValues();
    public static final String QUOTE_NATT_UNIT_RT = 'NATT_Units_Quote';

    /* ORDER CONSTANTS */    
    public static final List<String> ORDER_STATUS_IN_PROGRESS = getOrderStatusValues();    
    public static final String ORDER_NATT_UNIT_RT = 'NATT_Units_Order';
    public static final String ORDER_STATUS_COMPLETED = 'Complete';
    public static final String ORDER_STATUS_CANCELLED = 'Cancelled';

    public static final List<String> ORDER_STATUS_COMPLETE_OR_CANCELLED = new List<String>{
        ORDER_STATUS_COMPLETED,
        ORDER_STATUS_CANCELLED
    };

    /* CASE CONSTANTS */
    public static final List<String> CASE_STATUS_IN_PROGRESS = getCaseStatusValues();

    /* ACCOUNT CONSTANTS */
    public static final String ACCOUNT_ACTIVE = 'Active';

    /* KNOWLEDGE CONSTANTS*/
    public static final Map<String, String> KNOWLEDGE_CATEGORIES_BY_LABEL_VIEW = new Map<String, String>{
        'General Bulletin' => 'generalBulletins',
        'Parts Bulletin' => 'partsBulletins',
        'Service Bulletin'  => 'serviceBulletins',
        'Training Bulletin' => 'trainingBulletins',
        'Product Manual Updates'  => 'productManualUpdates',
        'eFlash'  => 'eFlash',
        'Dealer News'  => 'dealerNews'
    };

    /* NATT ADDRESS CONTANSTS */
    public static final String NATT_ADDRESS_TYPE_HEADQUARTERS = 'Headquarters';
    public static final String NATT_ADDRESS_TYPE_PHYSICAL = 'Physical';
    public static final String NATT_ADDRESS_TYPE_MAILING = 'Mailing';

    public static final List<String> NATT_ADDRESS_TYPE_TRIGGER = new List<String>{
        NATT_ADDRESS_TYPE_HEADQUARTERS,
        NATT_ADDRESS_TYPE_PHYSICAL,
        NATT_ADDRESS_TYPE_MAILING
    };
        
   /*User Constants*/
   public static final List<String> NATT_USER_PROFILE_LIST = new List<String>{'CGI Administrator','NATT Account Super User','NATT Accounts Read Only','NATT Associate With Tavant Community','NATT Associate Without Tavant Community',
            'NATT Dealer Master User','NATT Field Staff','NATT Full Access Community','NATT Partner Community User','NATT Parts and Service Community','NATT Parts Only Community',
            'NATT Parts Sales','NATT Sales Only Community','NATT Technical Community','NATT Warranty Only Community'};
                
    /* UTILS */
    private static List<String> getCaseStatusValues() {
        List<CaseStatus> ltCaseStatus = [SELECT Id, MasterLabel FROM CaseStatus WHERE IsClosed = false];
        List<String> ltStringValues = new List<String>();
        
        for (CaseStatus cs : ltCaseStatus) {
            ltStringValues.add(cs.MasterLabel);
        }
        
        return ltStringValues;
    }
    
    private static List<String> getOrderStatusValues() {
        List<String> ltStringValues = new List<String>();
        for (Schema.PicklistEntry pe : Order.NATT_Order_Status__c.getDescribe().getPicklistValues()) {
            if (pe.getLabel() != 'Complete' && pe.getLabel() != 'Cancelled') {
                ltStringValues.add(pe.getLabel());
            }
        }

        return ltStringValues;
    }

    private static List<String> getQuoteStatusValues() {
        List<String> ltStringValues = new List<String>();
        for (Schema.PicklistEntry pe : SBQQ__Quote__c.SBQQ__Status__c.getDescribe().getPicklistValues()) {
            if (pe.getLabel() == QUOTE_DRAFT || pe.getLabel() == QUOTE_PENDING_APPROVAL) {
                ltStringValues.add(pe.getLabel());
            }
        }

        return ltStringValues;
    }

}