NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Accounts</description>
    <label>Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/AccountContactRelation/fields/NATT_External_ID__c.field-meta.xml
<CustomField>
    <fullName>NATT_External_ID__c</fullName>
    <formula>IF(
AND(
Account.NATT_Record_Type_Developer_Name__c = &apos;Dealer&apos;,
Contact.NATT_Record_Type_Developer_Name__c = &apos;NATT_Dealer&apos;
),  Account.NATT_Customer_Number__c+&apos;-&apos;+ Contact.NATT_Contact_Number__c , &apos;&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Contact Relation</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/AccountContactRelation/fields/NATT_isMigrated__c.field-meta.xml
<CustomField>
    <fullName>NATT_isMigrated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To check if it is migrated to destination.
Updated via SyncACRBatchCallout batch class</description>
    <label>Is Migrated</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/ACR_Batch__c/ACR_Batch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ACR Batch</label>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/Contact/recordTypes/NATT_Dealer.recordType-meta.xml
<RecordType>
    <fullName>NATT_Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Contacts</description>
    <label>NATT Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/classes/SyncACRBatchCallout.cls
/**
Batch class to keep ACR in sync with NATT and TAVANT org.
Need to call this batch every 6 hours
**/
global class SyncACRBatchCallout implements Database.Batchable<sObject>, Schedulable, Database.AllowsCallouts, Database.Stateful {
    
    global integer totalSizeRecords=0;
    private static final String calloutEndpoint = 'callout:UATCallout/services/apexrest/v1/acrSync/';
    
    public void execute(SchedulableContext sc){
        SyncACRBatchCallout batch = new SyncACRBatchCallout();
        Database.executeBatch(batch,50);
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        ACR_Batch__c cs = ACR_Batch__c.getInstance('LastRun');
        Datetime lastRun = cs.Last_run__c; 
        
        //Record type fecthing of Account and Contact
        String accdealerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId();
        String condealerRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('NATT_Dealer').getRecordTypeId();
        
        return Database.getQueryLocator('Select id, NATT_External_ID__c from AccountContactRelation WHERE '+
                                        +' account.recordTypeID =:accdealerRecordTypeId and NATT_isMigrated__c = false'+
                                        +' and contact.recordTypeID =:condealerRecordTypeId and LastModifiedDate >: lastRun');
        
    }
    
    global void execute(Database.BatchableContext bc, List<AccountContactRelation> scope) {
        
        Map<String, ID> externalIDMap = new Map<String, ID>();
        totalSizeRecords += scope.size();
        List<ACRWrapper.Records> recLst = new List<ACRWrapper.Records>();
        
        for(AccountContactRelation acr : scope){
            if(!String.isBlank(acr.NATT_External_ID__c)){
                ACRWrapper.Records rec = new ACRWrapper.Records();
                rec.acrExternal = acr.NATT_External_ID__c;
                externalIDMap.put(acr.NATT_External_ID__c, acr.ID);
                recLst.add(rec);
            }
        }
        
        if(!recLst.isEmpty()){
            ACRWrapper wrap = new ACRWrapper();
            wrap.rec = recLst;
            String jsonstr = System.JSON.serialize(wrap, true);
            String jsonResponse;
            
            try{
                HttpResponse response = new HttpResponse();
                HttpRequest request = new HttpRequest();
                Http http = new Http();
                
                request.setHeader('Content-Type', 'application/json;charset=UTF-8');
                request.setEndpoint(calloutEndpoint);
                request.setMethod('PUT');
                request.setTimeout(120000);
                request.setBody(jsonstr);
                
                if(!Test.isRunningTest()){
                    response = http.send(request);
                }
                else{
                    response = SyncACRBatchCalloutMock.getResp(externalIDMap);
                }
                
                //checking callout status
                if (response.getStatusCode() == 200) {
                    List<AccountContactRelation> updateACRLst = new List<AccountContactRelation>();
                    jsonResponse = response.getBody();
                    
                    //deserializing
                    Map<String, ResponseWrapper> respResult = (Map<String, ResponseWrapper>) JSON.deserialize(jsonResponse, Map<String, ResponseWrapper>.class);
                    
                    for(String respExternalID : respResult.keySet()){
                        AccountContactRelation acrObj = new AccountContactRelation();
                        acrObj.ID = externalIDMap.get(respExternalID);
                        acrObj.NATT_isMigrated__c = true;
                        updateACRLst.add(acrObj);
                    }
                    
                    if(!updateACRLst.isEmpty()){
                        Database.update(updateACRLst, false);
                    }
                }
            }
            catch(Exception e){
                System.debug('Error-' + e.getMessage() + e.getLineNumber());   
            }
        }
    }
    
    global void finish(Database.BatchableContext bc){
        
        system.debug('Total number of records processed' +totalSizeRecords);
    }
    
    public class ResponseWrapper{
        String success;
        String externalID;
        String message;
    }
}