NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Accounts</description>
    <label>Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Contact/fields/NATT_Key_Business_Role__c.field-meta.xml
<CustomField>
    <fullName>NATT_Key_Business_Role__c</fullName>
    <description>NATT</description>
    <label>Key Business Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Co-Principal</fullName>
            </value>
            <value>
                <fullName>VP/Director</fullName>
            </value>
            <value>
                <fullName>VP/Director - Sales</fullName>
            </value>
            <value>
                <fullName>VP/Director - Parts</fullName>
            </value>
            <value>
                <fullName>VP/Director - Service</fullName>
            </value>
            <value>
                <fullName>VP/Director – Parts &amp; Service</fullName>
            </value>
            <value>
                <fullName>General Manager</fullName>
            </value>
            <value>
                <fullName>Branch Manager</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Service Manager</fullName>
            </value>
            <value>
                <fullName>Parts Manager</fullName>
            </value>
            <value>
                <fullName>Warranty Manager</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>Unit Sales Person</fullName>
            </value>
            <value>
                <fullName>Parts Sales Person</fullName>
            </value>
            <value>
                <fullName>Technician</fullName>
            </value>
            <value>
                <fullName>Warranty Admin</fullName>
            </value>
            <value>
                <fullName>Billing Admin</fullName>
            </value>
            <value>
                <fullName>General Admin</fullName>
            </value>
            <value>
                <fullName>Corporate Officer</fullName>
            </value>
            <value>
                <fullName>Director General</fullName>
            </value>
            <value>
                <fullName>Subdirector</fullName>
            </value>
            <value>
                <fullName>Vice-Presidente/Director</fullName>
            </value>
            <value>
                <fullName>Gerente General</fullName>
            </value>
            <value>
                <fullName>Gerente de Sucursal</fullName>
            </value>
            <value>
                <fullName>Gerente de Ventas</fullName>
            </value>
            <value>
                <fullName>Gerente de Servicio</fullName>
            </value>
            <value>
                <fullName>Gerente de Partes</fullName>
            </value>
            <value>
                <fullName>Gerente de Garantías</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Contact/recordTypes/NATT_Dealer.recordType-meta.xml
<RecordType>
    <fullName>NATT_Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Contacts</description>
    <label>NATT Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/ContactPointAddress/fields/NATT_Address__c.field-meta.xml
<CustomField>
    <fullName>NATT_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the JDE Address record</description>
    <label>NATT Address</label>
    <referenceTo>NATT_Address__c</referenceTo>
    <relationshipLabel>Contact Point Addresses</relationshipLabel>
    <relationshipName>Contact_Point_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/NATT_Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>NATT Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_Account__c.field-meta.xml
<CustomField>
    <fullName>NATT_Account__c</fullName>
    <description>NATT</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>NATT_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_Street__c.field-meta.xml
<CustomField>
    <fullName>NATT_Street__c</fullName>
    <description>NATT</description>
    <label>Street</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/NATT_AccountInformationHelperTest.cls
@isTest
public with sharing class NATT_AccountInformationHelperTest {

    @TestSetup
    static void setupTestData() {
        Profile testProfile = [SELECT Id FROM Profile WHERE Name = 'NATT Full Access Community' LIMIT 1];
        Account a = new Account(
            Name='Test',
            RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()
            );
        insert a;
        Contact c = new Contact(
            AccountId=a.Id,
            FirstName='Test',
            LastName='User',
            NATT_Key_Business_Role__c='Principal',
            RecordTypeId=Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('NATT_Dealer').getRecordTypeId()
            );
        insert c;
        User testUser = new User(
            Username = 'testUser@testclass.com', 
            LastName = 'testing', 
            Email = 'test@test.test', 
            Alias = 'tuser', 
            TimeZoneSidKey = 'America/New_York', 
            LocaleSidKey = 'en_US', 
            EmailEncodingKey = 'ISO-8859-1', 
            ProfileId = testProfile.Id,
            LanguageLocaleKey = 'en_US',
            ContactId = c.Id
        );
        insert testUser;
    }

    //EffectiveAccount method used to grab account details.
    @isTest
    public static void grabEfectiveAccount_Test(){
        Account testAccount = [SELECT ID FROM Account];
        Account newAcct = new Account();
        Test.startTest();
        newAcct = NATT_AccountInformationHelper.grabEffectiveAccount(testAccount.Id);
        Test.stopTest();
        System.assertEquals(testAccount.Id, newAcct.Id, 'We expect the method to return a detailed view of the Account.');
    }


    @isTest
    public static void grabAddresses_Test(){
        Account testAccount = [SELECT ID FROM Account];
        User testUserNew = [SELECT ID FROM User WHERE Email = 'test@test.test'];
        ContactPointAddress testAddress = new ContactPointAddress(
           Name = 'Test Address', 
           ParentId = testAccount.id,  
           street = '105 Test Street', 
           city = 'Atlanta', 
           state = 'GA',
           Country='US',
           NATT_Address__c = null,
           AddressType = 'Shipping'
        );
        insert testAddress;
        ContactPointAddress contactPointAddresses = [SELECT Id, Name, ParentId, Address, street, city, state, NATT_Address__c, AddressType FROM ContactPointAddress]; 

        List <ContactPointAddress> newAddressGrab = new List <ContactPointAddress>();

        Test.startTest();
            newAddressGrab = NATT_AccountInformationHelper.grabAddresses(testAccount.Id);
        Test.stopTest();
       
        String addressName = '';
        for(ContactPointAddress contactAddress : newAddressGrab){
            addressName = contactAddress.Name;
        }
        System.assertEquals('Test Address', addressName, 'We expect the User Id to query the Address.');
    }

    @isTest
    public static void grabJdeAddresses_Test(){
        Account testAccount = [SELECT ID FROM Account];
        User testUserNew = [SELECT ID FROM User WHERE Email = 'test@test.test'];
        NATT_Address__c testJdeAddress = new NATT_Address__c(
            Name = 'Test JDE',
            NATT_Street__c = '123 Test Drive',
            NATT_Account__c = testAccount.Id
        );
        insert testJdeAddress;

        ContactPointAddress testAddress = new ContactPointAddress(
           Name = 'Test Address', 
           ParentId = testAccount.id,  
           street = '105 Test Street', 
           city = 'Atlanta', 
           state = 'GA',
           Country='US',
           NATT_Address__c = testJdeAddress.Id,
           AddressType = 'Shipping'
        );
        insert testAddress;
        ContactPointAddress contactPointAddresses = [SELECT Id, Name, ParentId, Address, street, city, state, NATT_Address__c, AddressType FROM ContactPointAddress]; 

        List <ContactPointAddress> newAddressGrab = new List <ContactPointAddress>();

        Test.startTest();
            newAddressGrab = NATT_AccountInformationHelper.grabJdeAddresses(testAccount.Id);
        Test.stopTest();
       
        String addressName = '';
        for(ContactPointAddress contactAddress : newAddressGrab){
            addressName = contactAddress.Name;
        }
        System.assertEquals('Test Address', addressName, 'We expect the User Id to query the Address.');
    }


    @isTest
    public static void updateAddress_Test(){
        Boolean updateCheck = false;
        Boolean updateCheckFailure = false;
        Account testAccount = [SELECT ID FROM Account];
        User testUserNew = [SELECT ID FROM User WHERE Email = 'test@test.test'];
        List <ContactPointAddress> addressList = new List <ContactPointAddress> ();
        List <ContactPointAddress> addressListToFail = new List <ContactPointAddress> ();
        ContactPointAddress testAddress = new ContactPointAddress(
           Name = 'Test Address', 
           ParentId = testAccount.id,  
           street = '105 Test Street', 
           city = 'Atlanta', 
           state = 'GA',
           Country='US'
        );
        insert testAddress;

        ContactPointAddress testAddressToFail = new ContactPointAddress(
            Name = 'Failed Address', 
            ParentId = testAccount.id,  
            street = '001 First Street', 
            city = 'Atlanta', 
            state = 'GA'
         );
         addressListToFail.add(testAddressToFail);

        Test.startTest();
        addressList = [SELECT Id, Name FROM ContactPointAddress WHERE Id = :testAddress.Id];
        for(ContactPointAddress cpa : addressList){
            cpa.Name = 'Updated Address';
        }
        updateCheck = NATT_AccountInformationHelper.updateAddresses(addressList);
        updateCheckFailure = NATT_AccountInformationHelper.updateAddresses(addressListToFail);
        Test.stopTest();

        System.assertEquals(true, updateCheck, 'We expect the Contact Point Address List to successfully update.');
        System.assertEquals(false, updateCheckFailure, 'We do not expect this List to update because the Contact Point Address has not been properly inserted yet.');

    }

    @isTest
    public static void grabAccountDetails_Test(){
        Account testAccount = [SELECT ID FROM Account];
        Test.startTest();
        NATT_AccountInformationHelper.grabAccountDetails(testAccount.Id);
        Test.stopTest();
    }

    @isTest
    public static void deleteAddress_test(){
        Boolean updateCheck = false;
        Boolean updateCheckFailure = false;
        Account testAccount = [SELECT ID FROM Account];
        User testUserNew = [SELECT ID FROM User WHERE Email = 'test@test.test'];
        List <ContactPointAddress> addressList = new List <ContactPointAddress> ();
        List <ContactPointAddress> addressListToFail = new List <ContactPointAddress> ();

        ContactPointAddress testAddress = new ContactPointAddress(
           Name = 'Test Address', 
           ParentId = testAccount.id,  
           street = '105 Test Street', 
           city = 'Atlanta', 
           state = 'GA',
           Country='US'
        );
        insert testAddress;
        List <ContactPointAddress> listOfAddressesBeforeDelete = new List <ContactPointAddress>();
        List <ContactPointAddress> listOfAddressesAfterDelete = new List <ContactPointAddress>();

        Test.startTest();
        listOfAddressesBeforeDelete = [SELECT ID, Name FROM ContactPointAddress WHERE Id = :testAddress.Id];
        NATT_AccountInformationHelper.deleteAddress(testAddress);
        listOfAddressesAfterDelete = [SELECT ID FROM ContactPointAddress WHERE Id = :testAddress.Id];

        Test.stopTest();

        System.assertEquals(false, listOfAddressesBeforeDelete.isEmpty(), 'We expect the Contact Point Address List to successfully update.');
        System.assertEquals(true, listOfAddressesAfterDelete.isEmpty(), 'We do not expect this List to update because the Contact Point Address has not been properly inserted yet.');

    }

}