NATTQA-ENV/force-app/main/default/objects/Account/fields/Authorized_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Authorized_Service_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Authorized Service Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>CONTAINER Authorized Service Provider</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Service Account)</relationshipLabel>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Organization__c.field-meta.xml
<CustomField>
    <fullName>NATT_Organization__c</fullName>
    <description>NATT</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Geography</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <description>NATT</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>NATT End User/End Customer Accounts</description>
    <label>Customer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <description>Contact type picklist for Container Users</description>
    <label>Contact Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales Contact</fullName>
            </value>
            <value>
                <fullName>Service Contact</fullName>
            </value>
            <value>
                <fullName>Parts Contact</fullName>
            </value>
            <value>
                <fullName>Warranty Contact</fullName>
            </value>
            <value>
                <fullName>Executive Contact</fullName>
            </value>
            <value>
                <fullName>Finance Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Contact/fields/CONTAINER_Is_Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Is_Primary_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To identify Primary contact record in service.</description>
    <label>Is Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/CONTAINER_Service_Agreement__c/CONTAINER_Service_Agreement__c.object-meta.xml
<CustomObject>
    <description>Custom Container Service Agreement object</description>
    <label>Service Agreement</label>
    <nameField>
        <displayFormat>SA-{00000}</displayFormat>
        <label>Service Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/Knowledge__kav/fields/NATT_Whos_Who__c.field-meta.xml
<CustomField>
    <fullName>NATT_Whos_Who__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Who&apos;s Who</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Knowledge__kav/recordTypes/CONTAINER.recordType-meta.xml
<RecordType>
    <fullName>CONTAINER</fullName>
    <active>true</active>
    <description>This can be used for CONTAINER related Articles.</description>
    <label>CONTAINER</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Knowledge__kav/recordTypes/NATT.recordType-meta.xml
<RecordType>
    <fullName>NATT</fullName>
    <active>true</active>
    <label>NATT</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/User/fields/Container_Service_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Container_Service_Agreement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Container Service Agreement (UCP)</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/User/fields/NATT_Whos_Who__c.field-meta.xml
<CustomField>
    <fullName>NATT_Whos_Who__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Who&apos;s Who</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/Geography.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NATT</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>CTB</fullName>
    </customValue>
    <customValue>
        <fullName>Need the others listed</fullName>
        <isActive>false</isActive>
        <label>Need the others listed</label>
    </customValue>
    <masterLabel>Geography</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>East</fullName>
    </customValue>
    <customValue>
        <fullName>West</fullName>
    </customValue>
    <customValue>
        <fullName>South</fullName>
    </customValue>
    <customValue>
        <fullName>Central</fullName>
    </customValue>
    <customValue>
        <fullName>National</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Latin America</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Region 1</fullName>
    </customValue>
    <customValue>
        <fullName>Region 2</fullName>
    </customValue>
    <customValue>
        <fullName>Region 3</fullName>
    </customValue>
    <customValue>
        <fullName>Northeast</fullName>
    </customValue>
    <customValue>
        <fullName>Southeast</fullName>
    </customValue>
    <customValue>
        <fullName>Midwest</fullName>
    </customValue>
    <customValue>
        <fullName>North</fullName>
    </customValue>
    <customValue>
        <fullName>Europe, Middle East and Africa</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pacific and Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>Americas</fullName>
        <isActive>false</isActive>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>undefined</fullName>
        <isActive>false</isActive>
        <label>undefined</label>
    </customValue>
    <customValue>
        <fullName>Asia</fullName>
        <isActive>false</isActive>
        <label>Asia</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/UCP_WhoswhoControllerTest.cls
@IsTest
public with sharing class UCP_WhoswhoControllerTest {
    
    @TestSetup
    static void makeData() {
        UserRole userrole = [Select Id, DeveloperName From UserRole Where DeveloperName = 'Container' Limit 1];
        
        User adminUser = [Select Id, UserRoleId From User Where Profile.Name='System Administrator' AND IsActive = true Limit 1];
        
        adminUser.UserRoleId = userRole.Id;
        update adminUser;
        
        System.runAs(adminUser){
            
            Account authorizedServiceProviderAccount = new Account(
                Name = 'Test CONTAINER Authorized Service Provider',
                RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('CONTAINER Authorized Service Provider').getRecordTypeId()
            );
            insert authorizedServiceProviderAccount;
            
            Account a = new Account(name = 'Test Account',Authorized_Service_Provider__c = authorizedServiceProviderAccount.Id ,NATT_Organization__c = 'NATT',NATT_Region__c = 'East',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('CONTAINER Customer').getRecordTypeId());
            insert a;
            
            Contact c = new Contact(LastName = 'Contact Last Name', AccountId = a.id,CONTAINER_Is_Primary_Contact__c = true,Contact_Type__c = 'Service Contact',Email = 'test@xyz.com');
            insert c;
            
            Contact objContact = new Contact(LastName = 'Contact Service', AccountId = authorizedServiceProviderAccount.id,CONTAINER_Is_Primary_Contact__c = true,Contact_Type__c = 'Service Contact',Email = 'test@xyz.com');
            insert objContact;
            
            User user = new User();
            user.ProfileID = [Select Id From Profile Where Name='UCP Profile'].id;
            user.EmailEncodingKey = 'ISO-8859-1';
            user.LanguageLocaleKey = 'en_US';
            user.TimeZoneSidKey = 'America/New_York';
            user.LocaleSidKey = 'en_US';
            user.FirstName = 'first';
            user.LastName = 'last';
            user.Username = 'test@uniquedomain.com';
            user.CommunityNickname = 'testUser123';
            user.Alias = 't1';
            user.Email = 'no@email.com';
            user.IsActive = true;
            user.Container_Service_Agreement__c = true;
            user.ContactId = c.Id;
            user.NATT_Whos_Who__c = true;
            
            insert user;
            
            User aspUser = new User();
            aspUser.ProfileID = [Select Id From Profile Where Name='UCP Profile'].id;
            aspUser.EmailEncodingKey = 'ISO-8859-1';
            aspUser.LanguageLocaleKey = 'en_US';
            aspUser.TimeZoneSidKey = 'America/New_York';
            aspUser.LocaleSidKey = 'en_US';
            aspUser.FirstName = 'first';
            aspUser.LastName = 'last';
            aspUser.Username = 'test@uniquedomainsss.com';
            aspUser.CommunityNickname = 'testDomain';
            aspUser.Alias = 't1';
            aspUser.Email = 'no@email.com';
            aspUser.IsActive = true;
            aspUser.ContactId = objContact.Id;
            aspUser.NATT_Whos_Who__c = true;
            
            insert aspUser;
            
            
        }
        
    }
    
    @IsTest
    static void getWhosWhoArticleTest(){
        
        Knowledge__kav knowObj1 = new Knowledge__kav(
            Title = 'Article Test 1',
            UrlName = 'article-test-1',
            NATT_Whos_who__c = false
        );
        Insert knowObj1;
        
        Knowledge__kav knowObj2 = new Knowledge__kav(
            Title = 'Who is who article',
            UrlName = 'who-is-who',
            NATT_Whos_who__c = true
        );
        Insert knowObj2;
        
        Knowledge__kav know = [SELECT Id, KnowledgeArticleId FROM Knowledge__kav WHERE Title = 'Who is who article' LIMIT 1];
        KbManagement.PublishingService.publishArticle(know.KnowledgeArticleId, true);
        
        Knowledge__kav know2 = [SELECT Id, KnowledgeArticleId FROM Knowledge__kav WHERE Title = 'Article Test 1' LIMIT 1];
        KbManagement.PublishingService.publishArticle(know2.KnowledgeArticleId, true);
        
        Test.startTest();
        
        // Fetch the test user details
        Contact objContact = [SELECT Id,Name FROM Contact LIMIT 1];
        User testUser = [SELECT Id, ContactId FROM User WHERE ContactId =: objContact.Id LIMIT 1];
        System.runAs(testUser) {
            
            Map<String, Object> mpReturn = UCP_WhoswhoController.getWhosWhoArticle();
            List<Knowledge__kav> ltKnowledge = (List<Knowledge__kav>) mpReturn.get('data');
        }
        Test.stopTest();
        
    }
    
    @IsTest
    static void getWhosWhoArticleFailTest() {
        Test.startTest();
        
        User adminUser = [Select Id, UserRoleId From User Where Profile.Name='System Administrator' AND IsActive = true Limit 1];
        
        Contact objContact = [SELECT Id, Name FROM Contact LIMIT 1];
        User testUser = [SELECT Id, ContactId FROM User WHERE ContactId =: objContact.Id LIMIT 1];        
        System.runAs(adminUser){
            
            
            testUser.NATT_Whos_Who__c = false;
            Update testUser;
        }
        // Fetch the test user details
        
        
        System.runAs(testUser) {
            // Mock a scenario that throws an exception (e.g., null value for a required field)
            try {
                Map<String, Object> response = UCP_WhosWhoController.getWhosWhoArticle();
                //System.assert(false, 'Exception was expected but not thrown.');
            } catch (Exception e) {
                // Assert the exception is caught and handled
                System.assertEquals(false, e != null, 'Exception should be handled gracefully.');
            }
        }
        Test.stopTest();
    }
    
}