NATTQA-ENV/force-app/main/default/objects/Account/fields/Authorized_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Authorized_Service_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Authorized Service Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>CONTAINER Authorized Service Provider</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Service Account)</relationshipLabel>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>NATT End User/End Customer Accounts</description>
    <label>Customer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Contact/fields/Container_Service_Agreement_UCP__c.field-meta.xml
<CustomField>
    <fullName>Container_Service_Agreement_UCP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Container Service Agreement (UCP)</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Contact/fields/Federation_ID__c.field-meta.xml
<CustomField>
    <fullName>Federation_ID__c</fullName>
    <label>Federation ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Contact/fields/UCP_Permission_Set__c.field-meta.xml
<CustomField>
    <fullName>UCP_Permission_Set__c</fullName>
    <label>UCP Permission Set</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UCP All</fullName>
            </value>
            <value>
                <fullName>UCP Purchase</fullName>
            </value>
            <value>
                <fullName>UCP Warranty</fullName>
            </value>
            <value>
                <fullName>UCP Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Contact/fields/UCP_Region__c.field-meta.xml
<CustomField>
    <fullName>UCP_Region__c</fullName>
    <label>UCP Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>AUS</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>SG/HK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/CONTAINER_Service_Agreement__c/CONTAINER_Service_Agreement__c.object-meta.xml
<CustomObject>
    <description>Custom Container Service Agreement object</description>
    <label>Service Agreement</label>
    <nameField>
        <displayFormat>SA-{00000}</displayFormat>
        <label>Service Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/CONTAINER_Service_Agreement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Account for Container Service Agreement object</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Agreements</relationshipLabel>
    <relationshipName>Service_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/User/fields/Container_Service_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Container_Service_Agreement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Container Service Agreement (UCP)</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/User/fields/Federation_ID__c.field-meta.xml
<CustomField>
    <fullName>Federation_ID__c</fullName>
    <formula>FederationIdentifier</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Federation ID</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/User/fields/UCP_Region__c.field-meta.xml
<CustomField>
    <fullName>UCP_Region__c</fullName>
    <label>UCP Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>AUS</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>SG/HK</fullName>
            </value>
            <value>
                <fullName>UCP (Global)</fullName>
                <isActive>false</isActive>
                <label>UCP (Global)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/UpdateUserQueueUCP.cls
public with sharing class UpdateUserQueueUCP {
    // Added for the story 
    @InvocableMethod(label = 'Add Users to Public Group UCP' description = 'Adds users to the specified public group. Pass userId and groupId as inputs.')
    public static void addUsersToGroup(List<GroupAssignmentRequest> requests) {
        System.debug('requests--' + requests);
        System.enqueueJob(new AddUsersToPublicGroupQueueable(requests));
    }
    
    public class AddUsersToPublicGroupQueueable implements Queueable {
        private List<GroupAssignmentRequest> requests;
        
        public AddUsersToPublicGroupQueueable(List<GroupAssignmentRequest> requests) {
            this.requests = requests;
        }
        
        public void execute(QueueableContext context) {
            List<GroupMember> groupMembersToInsert = new List<GroupMember>();
            List<GroupMember> groupMembersToDelete = new List<GroupMember>();
            Map<Id, Id> userWithGroupMap = new Map<Id, Id>();
            Set<Id> inactiveUsers = new Set<Id>();
            Set<Id> activeUsers = new Set<Id>();
            
            // Categorize users as active or inactive and build map for active users
            for (GroupAssignmentRequest request : this.requests) {
                if (request.userIsActive) {
                    userWithGroupMap.put(request.userId, request.groupId);
                    activeUsers.add(request.userId);
                } else {
                    inactiveUsers.add(request.userId);
                }
            }
            System.debug('userWithGroupMap-' + userWithGroupMap);
            System.debug('inactiveUsers-' + inactiveUsers);
            
            // Query to fetch all group members where users are in any of the specified groups
            List<GroupMember> grpMembers = [
                SELECT Id, UserOrGroupId, GroupId, Group.Name
                FROM GroupMember
                WHERE UserOrGroupId IN :userWithGroupMap.keySet() OR UserOrGroupId IN :inactiveUsers
            ];
            
            // Process each existing group member
            for (GroupMember member : grpMembers) {
                Id userId = member.UserOrGroupId;
                if (inactiveUsers.contains(userId)) {
                    // If the user is inactive, remove them from the group
                    groupMembersToDelete.add(member);
                } else if (userWithGroupMap.containsKey(userId)) {
                    // If the user is active, check group membership
                    Id targetGroupId = userWithGroupMap.get(userId);
                    if (member.GroupId != targetGroupId) {
                        // Remove from the current group if it's not the target group
                        groupMembersToDelete.add(member);
                    }
                }
            }
            
            // Add active users to their target groups
            for (GroupAssignmentRequest request : this.requests) {
                if (request.userIsActive) {
                    GroupMember gm = new GroupMember();
                    gm.UserOrGroupId = request.userId;
                    gm.GroupId = request.groupId;
                    groupMembersToInsert.add(gm);
                }
            }
            
            // Bulk DML operations: delete and insert group members
            try {
                if (!groupMembersToDelete.isEmpty()) {
                    delete groupMembersToDelete; // Remove users from groups
                }
                
                if (!groupMembersToInsert.isEmpty()) {
                    insert groupMembersToInsert; // Add active users to the correct groups
                }
            } catch (DmlException ex) {
                System.debug('Error processing group membership changes: ' + ex.getMessage());
            }
        }
    }
    
    public class GroupAssignmentRequest {
        @InvocableVariable(required=true)
        public String userId;
        
        @InvocableVariable(required=true)
        public String groupId;
        
        @InvocableVariable(required=true)
        public Boolean userIsActive;
    }
    
    @future
    public static void updateContactFedId(Set<Id> userIds) {
        List<User> users = [SELECT Id, ContactId, FederationIdentifier,UCP_Region__c,UCP_Permission_Set__c,Container_Service_Agreement__c FROM User WHERE Id IN :userIds];
        List<Contact> contactsToUpdate = new List<Contact>();
        
        // Loop through the users and update their related contact
        for (User u : users) {
            if (u.ContactId != null) {
                Contact con = new Contact(Id = u.ContactId);
                con.Federation_ID__c = u.FederationIdentifier;
                con.UCP_Permission_Set__c = u.UCP_Permission_Set__c;
                con.UCP_Region__c = u.UCP_Region__c;
                con.Container_Service_Agreement_UCP__c = u.Container_Service_Agreement__c;
                contactsToUpdate.add(con);
            }
        }
        
        // Update the contact records
        if (!contactsToUpdate.isEmpty()) {
            update contactsToUpdate;
        }
    }
    @future
    public static void ServiceAgreementShare(Set<Id> userIds) {
        set<Id> accountId = new set<Id>();
        List<User> users = [select Id, Name, Contact.AccountId,contact.account.Authorized_Service_Provider__c from User where Contact.AccountId  != null and Profile.Name In ('UCP Profile','NAC Customer Community Profile' ) and Id IN :userIds];
        system.debug('UCp users--'+users);
        for (user u: users){
            accountId.add(u.Contact.AccountId);  
            if(u.contact.account.Authorized_Service_Provider__c != null){
                accountId.add(u.contact.account.Authorized_Service_Provider__c); 
            }
        }
        system.debug('UCp Accounts--'+accountId);
        if(accountId.size()==0){
            return;
        }
        List<CONTAINER_Service_Agreement__c> SAList = [select id,name,Account__c, Account__r.RecordType.Name from CONTAINER_Service_Agreement__c where Account__r.RecordType.Name ='CONTAINER Authorized Service Provider' and account__c IN : accountId ];
       system.debug('UCp serviceAgg--'+SAList.size());
        if(SAList.size()>0){
        ServiceAgreementTriggerHelper.ShareServiceAgriment(SAList);
        }
    }
    
    
    
    
    
    
}