NATTQA-ENV/force-app/main/default/objects/Account/fields/Authorized_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Authorized_Service_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Authorized Service Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>CONTAINER Authorized Service Provider</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Service Account)</relationshipLabel>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>NATT End User/End Customer Accounts</description>
    <label>Customer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Contact/fields/CONTAINER_Is_Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_Is_Primary_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To identify Primary contact record in service.</description>
    <label>Is Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/CONTAINER_Service_Agreement__c/CONTAINER_Service_Agreement__c.object-meta.xml
<CustomObject>
    <description>Custom Container Service Agreement object</description>
    <label>Service Agreement</label>
    <nameField>
        <displayFormat>SA-{00000}</displayFormat>
        <label>Service Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/CONTAINER_Service_Agreement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Account for Container Service Agreement object</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Agreements</relationshipLabel>
    <relationshipName>Service_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/User/fields/Container_Service_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Container_Service_Agreement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Container Service Agreement (UCP)</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/ServiceAgreementTriggerHelperTest.cls
@isTest
public class ServiceAgreementTriggerHelperTest {
    
    @isTest
    static void testShareServiceAgreement() {
        Account acc1 = new account();
        Account acc2 = new account();
        Id customerAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('CONTAINER Authorized Service Provider').getRecordTypeId();
        Id NAcustomerAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('CONTAINER Customer').getRecordTypeId();
        Contact cnt = new contact();
        User communityUser = new user();
        User thisUser = new User(Id = UserInfo.getUserId());
        id UserRoleid = [SELECT Id FROM UserRole WHERE Name = 'NA Units Manager' LIMIT 1 ].Id;
        thisUser.UserRoleId = UserRoleid;
        System.runAs(thisUser) {
            update thisUser;
            acc1 = new Account(
                Name = 'Authorized Service Provider 7', 
                RecordTypeId = customerAccountRecordTypeId
                
            );
            insert acc1;
            
            
            // Create Contacts
            Contact contact1 = new Contact(
                FirstName = 'Primary', 
                LastName = 'Contact', 
                AccountId = acc1.Id,
                CONTAINER_Is_Primary_Contact__c = true
            );
            insert contact1;
            Profile profile = [SELECT Id FROM Profile WHERE Name='UCP Profile' LIMIT 1];
            
            communityUser = new User(Alias='UCPTest', Email='buyer@example.com', LastName='Buyer',
                                     TimeZoneSidKey='GMT', LocaleSidKey='en_US', Username= 'UCPTestUser321'+'@example.com',
                                     EmailEncodingKey='UTF-8', ProfileId=profile.Id, LanguageLocaleKey='en_US',
                                     ContactId=contact1.Id);
            insert communityUser;
        }
        
        // Create CONTAINER_Service_Agreement__c records
        CONTAINER_Service_Agreement__c serviceAgreement = new CONTAINER_Service_Agreement__c(
            Account__c = acc1.Id
        );
        insert serviceAgreement;
        List<CONTAINER_Service_Agreement__c> SAList = new List<CONTAINER_Service_Agreement__c>();
        SAList.add(serviceAgreement);
        System.runAs(thisUser) {
            acc2 = new Account(
                Name = 'Authorized Service Provider 7', 
                RecordTypeId = customerAccountRecordTypeId,
                Authorized_Service_Provider__c = acc1.id
            );
            insert acc2;
        }
        ServiceAgreementTriggerHelper.ShareServiceAgriment(SAList);
        System.runAs(thisUser) {
        acc2.Authorized_Service_Provider__c=null;
        update acc2;
        acc2.Authorized_Service_Provider__c = acc1.id;
        update acc2;
        }
    }
   
}