NATTQA-ENV/force-app/main/default/objects/Account/fields/CONTAINER_JDE_Bill_To_Code__c.field-meta.xml
<CustomField>
    <fullName>CONTAINER_JDE_Bill_To_Code__c</fullName>
    <description>CONTAINER JDE BILLT TO CODE</description>
    <externalId>true</externalId>
    <label>JDE Bill To Code</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Core_Return_Location__c.field-meta.xml
<CustomField>
    <fullName>NATT_Core_Return_Location__c</fullName>
    <description>Core Return Accounts will have an associated Core Return Location</description>
    <label>Core Return Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Core_Return_Location</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive/Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Case/fields/NAC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>NAC_Account_Number__c</fullName>
    <formula>Account.CONTAINER_JDE_Bill_To_Code__c</formula>
    <label>Account Number</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Case/fields/NATT_Case_Reason__c.field-meta.xml
<CustomField>
    <fullName>NATT_Case_Reason__c</fullName>
    <inlineHelpText>Reason that the Case is being created</inlineHelpText>
    <label>Case Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Management Issues</fullName>
            </value>
            <value>
                <fullName>Alarm</fullName>
            </value>
            <value>
                <fullName>Annual Returns</fullName>
            </value>
            <value>
                <fullName>Application Issue</fullName>
            </value>
            <value>
                <fullName>Availability</fullName>
            </value>
            <value>
                <fullName>Back Order</fullName>
            </value>
            <value>
                <fullName>Batch Issues</fullName>
                <isActive>false</isActive>
                <label>Batch Issues</label>
            </value>
            <value>
                <fullName>Cancellations</fullName>
            </value>
            <value>
                <fullName>Change</fullName>
                <isActive>false</isActive>
                <label>Change</label>
            </value>
            <value>
                <fullName>Change existing billing address</fullName>
            </value>
            <value>
                <fullName>Change existing shipping address</fullName>
            </value>
            <value>
                <fullName>Claim Rejection or Appeals</fullName>
            </value>
            <value>
                <fullName>Claim Update</fullName>
            </value>
            <value>
                <fullName>Commissioning Issues</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Concealed Damage</fullName>
            </value>
            <value>
                <fullName>Concession Request</fullName>
            </value>
            <value>
                <fullName>Consolidated Billing</fullName>
                <isActive>false</isActive>
                <label>Consolidated Billing</label>
            </value>
            <value>
                <fullName>Contract Issues</fullName>
            </value>
            <value>
                <fullName>Core Return</fullName>
            </value>
            <value>
                <fullName>Coverage Information</fullName>
            </value>
            <value>
                <fullName>Coverage Terms</fullName>
                <isActive>false</isActive>
                <label>Coverage Terms</label>
            </value>
            <value>
                <fullName>CPEC</fullName>
                <isActive>false</isActive>
                <label>CPEC</label>
            </value>
            <value>
                <fullName>Credit Memos</fullName>
            </value>
            <value>
                <fullName>Credits</fullName>
            </value>
            <value>
                <fullName>Customer Ordered in Error</fullName>
            </value>
            <value>
                <fullName>Damages</fullName>
            </value>
            <value>
                <fullName>Data Feed</fullName>
                <isActive>false</isActive>
                <label>Data Feed</label>
            </value>
            <value>
                <fullName>Deductible for a Repeat Charge</fullName>
                <isActive>false</isActive>
                <label>Deductible for a Repeat Charge</label>
            </value>
            <value>
                <fullName>Defective Shelf</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Case/fields/NATT_Core_Return_Location__c.field-meta.xml
<CustomField>
    <fullName>NATT_Core_Return_Location__c</fullName>
    <label>Core Return Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Core_Return_Location</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Case/fields/NATT_Core_Return_Location_Account__c.field-meta.xml
<CustomField>
    <fullName>NATT_Core_Return_Location_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Core Return Location Account</label>
    <referenceTo>NATT_Core_Return_Location__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Case/fields/NATT_Date_of_Entry__c.field-meta.xml
<CustomField>
    <fullName>NATT_Date_of_Entry__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date of Entry</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Case/fields/NATT_Disputed_Quantity__c.field-meta.xml
<CustomField>
    <fullName>NATT_Disputed_Quantity__c</fullName>
    <description>Disputed Quantity</description>
    <inlineHelpText>Disputed Quantity</inlineHelpText>
    <label>Disputed Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/ContactPointAddress/fields/NATT_Address__c.field-meta.xml
<CustomField>
    <fullName>NATT_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the JDE Address record</description>
    <label>NATT Address</label>
    <referenceTo>NATT_Address__c</referenceTo>
    <relationshipLabel>Contact Point Addresses</relationshipLabel>
    <relationshipName>Contact_Point_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/ContactPointAddress/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/ContactPointAddress/recordTypes/NAC.recordType-meta.xml
<RecordType>
    <fullName>NAC</fullName>
    <active>true</active>
    <description>Record type for NAC Container</description>
    <label>NAC</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/NATT_Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>NATT Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_Case_Sales_Order__c/NATT_Case_Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Junction object that links cases with sales orders and part numbers</description>
    <label>Case Line Item</label>
    <nameField>
        <displayFormat>CSO-{000000}</displayFormat>
        <label>Case Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_Case_Sales_Order__c/fields/NATT_Case__c.field-meta.xml
<CustomField>
    <fullName>NATT_Case__c</fullName>
    <description>Links the order product to the case</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Case_Order_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Case_Sales_Order__c/fields/NATT_Disputed_Quantity__c.field-meta.xml
<CustomField>
    <fullName>NATT_Disputed_Quantity__c</fullName>
    <label>Disputed Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Case_Sales_Order__c/fields/NATT_Quantity__c.field-meta.xml
<CustomField>
    <fullName>NATT_Quantity__c</fullName>
    <description>displays the quantity of the related order product</description>
    <formula>NATT_Order_Product__r.Quantity</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Core_Return_Location__c/NATT_Core_Return_Location__c.object-meta.xml
<CustomObject>
    <description>Data related to a Core Return Location</description>
    <label>Core Return Location</label>
    <nameField>
        <label>Core Return Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Core Return Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_Core_Return_Location__c/fields/Core_Return_Location__c.field-meta.xml
<CustomField>
    <fullName>Core_Return_Location__c</fullName>
    <label>Core Return Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Core_Return_Location</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Return_Item__c/NATT_Return_Item__c.object-meta.xml
<CustomObject>
    <description>Junction object that links cases to returned items</description>
    <label>Return Item</label>
    <nameField>
        <displayFormat>RTN-{000000}</displayFormat>
        <label>Return Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Return Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_Return_Item__c/fields/NATT_Case__c.field-meta.xml
<CustomField>
    <fullName>NATT_Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Return_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Return_Item__c/fields/NATT_Core_Return_Location__c.field-meta.xml
<CustomField>
    <fullName>NATT_Core_Return_Location__c</fullName>
    <formula>Text(NATT_Case__r.NATT_Core_Return_Location__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Core Return Location</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Return_Item__c/fields/NATT_Quantity__c.field-meta.xml
<CustomField>
    <fullName>NATT_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NAC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>NAC_Account_Number__c</fullName>
    <label>NAC Account Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/recordTypes/NAC.recordType-meta.xml
<RecordType>
    <fullName>NAC</fullName>
    <active>true</active>
    <description>Record type created for NAC Orders</description>
    <label>NAC</label>
</RecordType>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Core_Return_Location.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Carrier/Carlyle Compressor Core Returns</fullName>
    </customValue>
    <customValue>
        <fullName>Carrier Transicold Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>Carrier Transicold X430 Core Return</fullName>
    </customValue>
    <customValue>
        <fullName>Carrier Electric Motor Repair</fullName>
    </customValue>
    <customValue>
        <fullName>Starter &amp; Alternator Core Returns</fullName>
    </customValue>
    <customValue>
        <fullName>Weitron Refrigerant Cylinder Returns</fullName>
    </customValue>
    <customValue>
        <fullName>Return to Panama parts depot</fullName>
    </customValue>
    <customValue>
        <fullName>Return to Chile parts depot</fullName>
    </customValue>
    <description>Locations for equipment returned through the Core Returns program</description>
    <masterLabel>NATT Core Return Location</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/NAC_CreateCaseController.cls
public without sharing class NAC_CreateCaseController {
    
    @AuraEnabled
    public static caseWrapper getCaseDetails(String objectName) {
        caseWrapper caseWrap = new caseWrapper();
        Schema.SObjectType objectType = Schema.getGlobalDescribe().get(objectName);
        Schema.DescribeSObjectResult objectDescribe = objectType.getDescribe();
        Map<String, Schema.FieldSet> fieldSetMap = objectDescribe.fieldSets.getMap();
        for(String fieldSetName : fieldSetMap.keySet()){
            if(fieldSetName.toUppercase().contains('NAC_CORE_RETURN') || fieldSetName.toUppercase().contains('NAC_PERFORMANCE')){
                sections section = new sections();
                section.sectionLabel = fieldSetMap.get(fieldSetName).getLabel();
                section.sectionAPIName = fieldSetName;
                if(section.sectionLabel.contains('_')){
                    List<string> splitStr = section.sectionLabel.split('_',2);
                    if(splitStr[0].isNumeric()){
                        section.order = integer.valueof(splitStr[0]);
                        section.sectionLabel = splitStr[1];
                    }
                }
                for(Schema.FieldSetMember fsm : fieldSetMap.get(fieldSetName).getFields()){
                    section.fieldList.add(new field(fsm));
                }
                if(!section.fieldList.isEmpty()){
                    if(fieldSetName.toUppercase().contains('NAC_CORE_RETURN')){
                        caseWrap.coreFields.add(section);
                    }else if(fieldSetName.toUppercase().contains('NAC_PERFORMANCE')){
                        caseWrap.performancePartsFields.add(section);
                    }
                }
            }
        }
        caseWrap.addressList = [SELECT Id, Street, City, State, PostalCode, Country, IsDefault, NATT_Address__c, NATT_Address__r.Id, AddressType FROM ContactPointAddress WHERE Recordtype.Name='NAC' AND ParentId IN (SELECT AccountId FROM User WHERE Id =: UserInfo.getUserId()) AND Status__c = 'Approved'];
        return caseWrap;
    }

    @AuraEnabled
    public static resultWrapper createCoreReturns(Map<String,String> caseField, List<Map<String,String>> returnItemFields) {
        resultWrapper rWrap = new resultWrapper();
        Savepoint sp;
        sp = Database.setSavepoint();
        try{
            case coreRetunCase = new case();
            //Before saving case, get the core return location and stamp lookup field for return location
            Id coreLocationLookup = [SELECT id FROM NATT_Core_Return_Location__c WHERE Core_Return_Location__c =: caseField.get('NATT_Core_Return_Location__c') LIMIT 1]?.Id;
            if(coreLocationLookup != null){
                coreRetunCase.put('NATT_Core_Return_Location_Account__c',coreLocationLookup);
            }
            for(String field : caseField.keySet()){
                if(field == 'NATT_Date_of_Entry__c'){
                    //coreRetunCase.put(field,caseField.get(field));
                }else{
                    coreRetunCase.put(field,caseField.get(field));
                }
            }
            insert coreRetunCase;
            List<NATT_Return_Item__c> returnItemList = new List<NATT_Return_Item__c>();
            for(Map<String,String> returnItemMap : returnItemFields){
                NATT_Return_Item__c returnItem = new NATT_Return_Item__c();
                for(String field : returnItemMap.keySet()){
                    if(field == 'NATT_Quantity__c'){
                        returnItem.put(field,decimal.valueOf(returnItemMap.get(field)));
                    }else{
                        returnItem.put(field,returnItemMap.get(field));
                    }
                }
                returnItem.NATT_Case__c = coreRetunCase.Id;
                returnItemList.add(returnItem);
            }
            insert returnItemList;
            rWrap.caseId = coreRetunCase.Id;            
        }catch(Exception e){
            Database.rollback(sp);
            rWrap.hasError = true;
            rWrap.errorMessage = e.getTypeName() + ' ' + e.getMessage() + ' ' + e.getStackTraceString();
            system.debug('exception ' + e.getTypeName());
            system.debug('exception ' + e.getMessage());
            system.debug('exception ' + e.getStackTraceString());
        }
        
        return rWrap;
    }

    @AuraEnabled
    public static resultWrapper createPerfPartReturns(Map<String,String> caseField, List<Map<String,String>> returnItemFields) {
        resultWrapper rWrap = new resultWrapper();
        Savepoint sp;
        sp = Database.setSavepoint();
        try{
            Case corePerfPartCase = new Case();
            for(String field : caseField.keySet()){       
                corePerfPartCase.put(field,caseField.get(field));                
            }           
            insert corePerfPartCase;
            List<NATT_Case_Sales_Order__c> returnItemList = new List<NATT_Case_Sales_Order__c>();
            for(Map<String,String> returnItemMap : returnItemFields){
                NATT_Case_Sales_Order__c returnItem = new NATT_Case_Sales_Order__c();
                for(String field : returnItemMap.keySet()){  
                    if(field == 'NATT_Disputed_Quantity__c'){
                        returnItem.put(field,decimal.valueOf(returnItemMap.get(field)));
                    }else{
                        returnItem.put(field,returnItemMap.get(field));                    
                    }                 
                }
                returnItem.NATT_Case__c = corePerfPartCase.Id;
                returnItemList.add(returnItem);
            }
            insert returnItemList;
            rWrap.caseId = corePerfPartCase.Id;
        
        }catch(Exception e){
            Database.rollback(sp);
            rWrap.hasError = true;
            rWrap.errorMessage = e.getTypeName() + ' ' + e.getMessage() + ' ' + e.getStackTraceString();
            system.debug('exception ' + e.getTypeName());
            system.debug('exception ' + e.getMessage());
            system.debug('exception ' + e.getStackTraceString());
        }
        return rWrap;
    }

    @AuraEnabled
    public static resultWrapper createPerfPartReturnInternal(Map<String,String> caseField, List<Map<String,String>> returnItemFields,String caseId) {
        resultWrapper rWrap = new resultWrapper();
        Savepoint sp;
        sp = Database.setSavepoint();
        try{
            List<NATT_Case_Sales_Order__c> returnItemList = new List<NATT_Case_Sales_Order__c>();
            for(Map<String,String> returnItemMap : returnItemFields){
                NATT_Case_Sales_Order__c returnItem = new NATT_Case_Sales_Order__c();
                for(String field : returnItemMap.keySet()){  
                    if(field == 'NATT_Disputed_Quantity__c'){
                        returnItem.put(field,decimal.valueOf(returnItemMap.get(field)));
                    }else{
                        returnItem.put(field,returnItemMap.get(field));                    
                    }                 
                }
                returnItem.NATT_Case__c = caseId;
                returnItemList.add(returnItem);
            }
            insert returnItemList;
            rWrap.caseId = caseId;
        
        }catch(Exception e){
            Database.rollback(sp);
            rWrap.hasError = true;
            rWrap.errorMessage = e.getTypeName() + ' ' + e.getMessage() + ' ' + e.getStackTraceString();
            system.debug('exception ' + e.getTypeName());
            system.debug('exception ' + e.getMessage());
            system.debug('exception ' + e.getStackTraceString());
        }
        return rWrap;

    }
    
    @AuraEnabled(cacheable=true)
    public static list<sObject> fetchLookupData(string searchKey ,String corelocation, string sObjectApiName, string additionalCondition) {    
        List <sObject> returnList = new List <sObject> (); 
        string sWildCardText = '%' + searchKey + '%';
        string sQuery = 'Select Id,ProductCode,Name,NAOCAP_Core_Return_Location__c From ' + sObjectApiName + ' Where ProductCode Like : sWildCardText AND RecordType.Name = \'NAC Products\' AND NAOCAP_Core_Return_Location__c INCLUDES(\''+String.escapeSingleQuotes(corelocation)+'\'' +') order by createdDate DESC LIMIT 5';
        for (sObject obj: database.query(sQuery)) {
            returnList.add(obj);
        }
        return returnList;
    }
    
    public class caseWrapper{
        @AuraEnabled public List<sections> coreFields;
        @AuraEnabled public List<sections> performancePartsFields;
        @AuraEnabled public List<ContactPointAddress> addressList;        
        caseWrapper(){
            coreFields = new List<sections>();
            performancePartsFields = new List<sections>();
            addressList = new List<ContactPointAddress>();
        }
    }
    
    public class sections{
        @AuraEnabled public string sectionLabel;
        @AuraEnabled public string sectionAPIName;
        @AuraEnabled public Integer order;
        @AuraEnabled public List<field> fieldList;
        sections(){
            order = 999;
            fieldList = new List<field>();
        }
    }
    
    public class field{
        @AuraEnabled public string apiName;
        @AuraEnabled public boolean isRequired;
        @AuraEnabled public boolean isReadOnly;
        @AuraEnabled public string value;
        field(Schema.FieldSetMember fsm){
            apiName = fsm.getFieldPath();
            User u=[Select Id,ContactId from User where Id=:UserInfo.getUserId() Limit 1];
            Contact currentContact =[SELECT Id,Name,AccountId,Account.CONTAINER_JDE_Bill_To_Code__c from Contact where Id=:u.ContactId Limit 1];
            isReadOnly = false;
            if(apiName == 'Origin'){
                isReadOnly = true;
                value='Origin';
            }
            if(fsm.getDbRequired() || fsm.getRequired()){
                isRequired = true;
            }else{
                isRequired = false;
            }
            if(apiName == 'Type'){
                isRequired = true;
            }
            value = null;
            if(apiName == 'AccountId'){
                isReadOnly = true;
                value= currentContact.AccountId;
            }
            if(apiName == 'NAC_Account_Number__c'){
                isReadOnly = true;
                value= currentContact.Account.CONTAINER_JDE_Bill_To_Code__c;
            }
            if(apiName == 'ContactId'){
                isReadOnly = true;
                value= u.ContactId;
            }
            if(apiName == 'NATT_Case_Reason__c'){
                value= '';
            }
        }
    }
    
    public class resultWrapper{
        @AuraEnabled public String caseId;
        @AuraEnabled public boolean hasError;
        @AuraEnabled public String errorMessage;
        resultWrapper(){
            hasError = false;
            errorMessage = '';
        }
    }

}