NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Organization__c.field-meta.xml
<CustomField>
    <fullName>NATT_Organization__c</fullName>
    <description>NATT</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Geography</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <description>NATT</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Accounts</description>
    <label>Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/NATT_End_Customer__c.field-meta.xml
<CustomField>
    <fullName>NATT_End_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>the end customer associated with this deal</description>
    <label>End Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>MX_Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CTBR_Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (End Customer)</relationshipLabel>
    <relationshipName>NATTEndCustomerOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <formula>TEXT(Account.NATT_Region__c)</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/NATT_Stock__c.field-meta.xml
<CustomField>
    <fullName>NATT_Stock__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT users check this if there is no end customer</description>
    <label>Stock</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/recordTypes/NATT_Opportunity_Units.recordType-meta.xml
<RecordType>
    <fullName>NATT_Opportunity_Units</fullName>
    <active>true</active>
    <businessProcess>NATT Opportunity Units Sales Process</businessProcess>
    <description>NATT Opportunity Units Recordtype</description>
    <label>Units</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Opportunity_Scheduled_Pick_Date__c/Opportunity_Scheduled_Pick_Date__c.object-meta.xml
<CustomObject>
    <label>Opportunity Requested Ship Date</label>
    <nameField>
        <displayFormat>OSPD-{0000}</displayFormat>
        <label>Opportunity Requested Ship Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Requested Ship Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/Opportunity_Scheduled_Pick_Date__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Opportunity_Scheduled_Pick_Dates</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity_Scheduled_Pick_Date__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <label>Requested Ship Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity_Scheduled_Pick_Date__c/fields/Scheduled_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Quantity__c</fullName>
    <label>Requested Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Is_Base_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Is_Base_Unit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>for base units only</description>
    <label>Is Base Unit</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_End_Customer__c.field-meta.xml
<CustomField>
    <fullName>NATT_End_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NATT End Customer</description>
    <label>End Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>MX_Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CTBR_Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (End Customer)</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <description>for eSolutions quotes only</description>
    <formula>TEXT(SBQQ__Account__r.NATT_Region__c)</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Stock__c.field-meta.xml
<CustomField>
    <fullName>NATT_Stock__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT users check this if there is no end customer</description>
    <label>Stock</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Primary__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox which if checked designates the quote as the Primary Quote</description>
    <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/Geography.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NATT</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>CTB</fullName>
    </customValue>
    <customValue>
        <fullName>Need the others listed</fullName>
        <isActive>false</isActive>
        <label>Need the others listed</label>
    </customValue>
    <masterLabel>Geography</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>East</fullName>
    </customValue>
    <customValue>
        <fullName>West</fullName>
    </customValue>
    <customValue>
        <fullName>South</fullName>
    </customValue>
    <customValue>
        <fullName>Central</fullName>
    </customValue>
    <customValue>
        <fullName>National</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Latin America</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Region 1</fullName>
    </customValue>
    <customValue>
        <fullName>Region 2</fullName>
    </customValue>
    <customValue>
        <fullName>Region 3</fullName>
    </customValue>
    <customValue>
        <fullName>Northeast</fullName>
    </customValue>
    <customValue>
        <fullName>Southeast</fullName>
    </customValue>
    <customValue>
        <fullName>Midwest</fullName>
    </customValue>
    <customValue>
        <fullName>North</fullName>
    </customValue>
    <customValue>
        <fullName>Europe, Middle East and Africa</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pacific and Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>Americas</fullName>
        <isActive>false</isActive>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>undefined</fullName>
        <isActive>false</isActive>
        <label>undefined</label>
    </customValue>
    <customValue>
        <fullName>Asia</fullName>
        <isActive>false</isActive>
        <label>Asia</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/OpportunityQuoteCreationControllerTest.cls
@isTest
public class OpportunityQuoteCreationControllerTest {
    @TestSetup
    static void setupTestData(){
        // Create Record Types
        //Id unitRecordTypeID = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Units').getRecordTypeId();
        
        List<RecordType> opportunityRecordTypes = [SELECT Id, DeveloperName, Name 
                                                   FROM RecordType 
                                                   WHERE SObjectType = 'Opportunity'
                                                   AND IsActive =true];
        
        // Create Pricebooks
        Pricebook2 pb1 = new Pricebook2(Name = 'NATT BluEdge', IsActive = true);
        Pricebook2 pb2 = new Pricebook2(Name = 'NATT Lynx Fleet', IsActive = true);
        Pricebook2 pb3 = new Pricebook2(Name = 'NATT Units Price Book', IsActive = true);
        insert new List<Pricebook2>{pb1, pb2, pb3};
            
            // Create an Opportunity
            Opportunity opp = new Opportunity(Name = 'Test Opportunity', StageName = 'Qualification', CloseDate = Date.today());
        insert opp;
        Opportunity_Scheduled_Pick_Date__c schedulePickDate = new Opportunity_Scheduled_Pick_Date__c();
        schedulePickDate.Opportunity__c = opp.id;
        
        schedulePickDate.Scheduled_Quantity__c =  0 ;
        schedulePickDate.Scheduled_Date__c =  System.today().addDays(10);
        insert schedulePickDate;
        
        SBQQ__Quote__c quote = new SBQQ__Quote__c(NATT_Stock__c = opp.NATT_Stock__c,NATT_End_Customer__c=opp.NATT_End_Customer__c,SBQQ__Primary__c = true,SBQQ__Opportunity2__c=opp.id);
        insert quote;
    }
    
    @isTest
    static void testGetOpportunityRecordTypes() {
        Id standardPbId = Test.getStandardPricebookId();

        Id recordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Opportunity' AND Name = 'NATT Direct Sales' LIMIT 1].Id;
        
        Product2 prod = new Product2(
            Name = 'Test Product',
            IsActive = true,
            CanUseQuantitySchedule = true,
            CanUseRevenueSchedule = true,
            NATT_Is_Base_Unit__c = true
        );
        insert prod;
        
         PricebookEntry standardPbe = new PricebookEntry(
            Pricebook2Id = standardPbId,
            Product2Id = prod.Id,
            UnitPrice = 100,
            IsActive = true
        );
        insert standardPbe;
        
        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(10),
            Pricebook2Id = standardPbId,
            RecordTypeId = recordTypeId
        );
        insert opp;
        
        Id accountRecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Dealer' LIMIT 1].Id;
        
        Account objAccount = new Account(
                        Name = 'Dealer',
                        NATT_Organization__c = 'NATT',
                        NATT_Region__c = 'East',
                        RecordTypeId = accountRecordTypeId
                    );
       insert objAccount;

        
        Test.startTest();
        
        List<RecordType> oppRecordTypes = OpportunityQuoteCreationController.getRecordTypes('Opportunity',objAccount.Id);
        List<RecordType> quoteRecordTypes = OpportunityQuoteCreationController.getRecordTypes('SBQQ__Quote__c',opp.Id);
        Test.stopTest();
        System.assert(oppRecordTypes.size()>0, 'Expected more than 1 record types for Opportunity.');
        System.assert(quoteRecordTypes.size()>0, 'Expected more than 1 record types for Quote.');
    }
    
     @isTest
    static void testGetOpportunityRecordTypesData() {
        Id standardPbId = Test.getStandardPricebookId();

        Id recordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Opportunity' AND Name = 'Units' LIMIT 1].Id;
        
        Product2 prod = new Product2(
            Name = 'Test Product',
            IsActive = true,
            CanUseQuantitySchedule = true,
            CanUseRevenueSchedule = true,
            NATT_Is_Base_Unit__c = true
        );
        insert prod;
        
         PricebookEntry standardPbe = new PricebookEntry(
            Pricebook2Id = standardPbId,
            Product2Id = prod.Id,
            UnitPrice = 100,
            IsActive = true
        );
        insert standardPbe;
        
        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(10),
            Pricebook2Id = standardPbId,
            RecordTypeId = recordTypeId
        );
        insert opp;
        
        Id accountRecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Direct Sale' LIMIT 1].Id;
        
        Account objAccount = new Account(
                        Name = 'Dealer',
                        NATT_Organization__c = 'NATT',
                        NATT_Region__c = 'East',
                        RecordTypeId = accountRecordTypeId
                    );
       insert objAccount;

        
        Test.startTest();
        
        List<RecordType> oppRecordTypes = OpportunityQuoteCreationController.getRecordTypes('Opportunity',objAccount.Id);
        List<RecordType> quoteRecordTypes = OpportunityQuoteCreationController.getRecordTypes('SBQQ__Quote__c',opp.Id);
        
        OpportunityQuoteCreationController.getUserInfo(opp.Id);
        Test.stopTest();
        System.assert(oppRecordTypes.size()>0, 'Expected more than 1 record types for Opportunity.');
        System.assert(quoteRecordTypes.size()>0, 'Expected more than 1 record types for Quote.');
    }
    
    @isTest
    static void testGetPricebookFromRecordTypes() {
        RecordType rt = [SELECT Id FROM RecordType WHERE DeveloperName = 'NATT_Opportunity_Units' LIMIT 1];
        
        Test.startTest();
        String pricebookId = OpportunityQuoteCreationController.getPricebookFromRecordTypes(rt.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, pricebookId, 'Expected a valid Pricebook2Id.');
        Pricebook2 pb = [SELECT Id,Name FROM Pricebook2 WHERE Id = :pricebookId];
        System.assertEquals('NATT Units Price Book', pb.Name, 'Expected NATT BluEdge Pricebook.');
    }
    
    @isTest
    static void testUpdatePricebookOnOpportunity() {
        Opportunity opp = [SELECT Id, Pricebook2Id FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        Id rtId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Units').getRecordTypeId();
        
        Test.startTest();
        OpportunityQuoteCreationController.updatePricebookOnOpportunity(opp.Id, rtId);
        OpportunityQuoteCreationController.addressFromAccount(opp.Id);
        OpportunityQuoteCreationController.getScheduledPickDates(opp.Id);
        Test.stopTest();
        
        // Fetch the updated opportunity and assert that Pricebook2Id was updated
        Opportunity updatedOpp = [SELECT Id, Pricebook2Id FROM Opportunity WHERE Id = :opp.Id];
        System.assertNotEquals(null, updatedOpp.Pricebook2Id, 'Pricebook2Id should have been updated.');
        Pricebook2 pb = [SELECT Name FROM Pricebook2 WHERE Id = :updatedOpp.Pricebook2Id];
        System.assertEquals('NATT Units Price Book', pb.Name, 'Expected NATT Units Pricebook.');
    }  
    @isTest
    static void getProductsNull() {
        Opportunity opp = [SELECT Id, Pricebook2Id FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        try{
            OpportunityQuoteCreationController.getOpportunityProducts(null);
        }
        catch(exception e){
            system.debug(e);
        }
    }
    @isTest
    static void getProductsId() {
        Opportunity opp = [SELECT Id, Pricebook2Id FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        OpportunityQuoteCreationController.getOpportunityProducts(opp.Id);
        
    }
    @isTest
    static void getProductsException() {
        Id userId = userInfo.getUserId();
        OpportunityQuoteCreationController.getOpportunityProducts(userId);
    }
    
}