NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Dealership__c.field-meta.xml
<CustomField>
    <fullName>NATT_Dealership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For End Customer RT&apos;s. This is the dealer the End Customer belongs to.</description>
    <label>Dealership</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer, Direct Sale, CTM Dealer, CTBR Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>NATT End User/End Customer Accounts</description>
    <label>Customer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Accounts</description>
    <label>Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/NATT_Inventory__c/NATT_Inventory__c.object-meta.xml
<CustomObject>
    <description>Corresponds with the WOD_2_Inventory__c (Unit Information) object in Tavant</description>
    <label>NATT Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NATT_Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_Inventory__c/fields/NATT_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Business_Unit__c</fullName>
    <description>Drives the rules engine. This value will be TT for Truck/Trailer</description>
    <label>Business Category Configuration</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Inventory__c/fields/NATT_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>NATT_Serial_Number__c</fullName>
    <description>Asset serial number of the manufactured product</description>
    <externalId>true</externalId>
    <label>Serial Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/NATT_End_Customer__c.field-meta.xml
<CustomField>
    <fullName>NATT_End_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>the end customer associated with this deal</description>
    <label>End Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>MX_Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CTBR_Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (End Customer)</relationshipLabel>
    <relationshipName>NATTEndCustomerOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/NATT_Stock__c.field-meta.xml
<CustomField>
    <fullName>NATT_Stock__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT users check this if there is no end customer</description>
    <label>Stock</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <description>NATT for reports</description>
    <formula>TEXT(SBQQ__PrimaryQuote__r.NATT_Unit__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/recordTypes/NATT_Opportunity_Units.recordType-meta.xml
<RecordType>
    <fullName>NATT_Opportunity_Units</fullName>
    <active>true</active>
    <businessProcess>NATT Opportunity Units Sales Process</businessProcess>
    <description>NATT Opportunity Units Recordtype</description>
    <label>Units</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_End_Customer__c.field-meta.xml
<CustomField>
    <fullName>NATT_End_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NATT end customer</description>
    <label>End Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (End Customer)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Stock__c.field-meta.xml
<CustomField>
    <fullName>NATT_Stock__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stock</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <description>twin field from quote</description>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Unit</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/SBQQ__ContractingMethod__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ContractingMethod__c</fullName>
    <description>&quot;By Subscription End Date&quot; creates a separate Contract for each unique Subscription End Date, containing only those Subscriptions. &quot;Single Contract&quot; creates one Contract containing all Subscriptions, regardless of their End Dates.</description>
    <inlineHelpText>&quot;By Subscription End Date&quot; creates a separate Contract for each unique Subscription End Date, containing only those Subscriptions. &quot;Single Contract&quot; creates one Contract containing all Subscriptions, regardless of their End Dates.</inlineHelpText>
    <label>Contracting Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__ContractingMethod</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>The quote where the order is created from.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <description>for quoting NATT Units</description>
    <label>Unit NATT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Unit</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__LookupData__c/SBQQ__LookupData__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__LookupQueryHelp</customHelpPage>
    <label>Lookup Data</label>
    <nameField>
        <displayFormat>DATA-{0000}</displayFormat>
        <label>Lookup Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lookup Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__LookupData__c/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Unit</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_BluEdge_Core__c.field-meta.xml
<CustomField>
    <fullName>NATT_BluEdge_Core__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BluEdge Core</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_End_Customer__c.field-meta.xml
<CustomField>
    <fullName>NATT_End_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NATT End Customer</description>
    <label>End Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>MX_Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CTBR_Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (End Customer)</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Stock__c.field-meta.xml
<CustomField>
    <fullName>NATT_Stock__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT users check this if there is no end customer</description>
    <label>Stock</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <description>NATT Unit selected for this quote</description>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Product_Family__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>NATT_Unit</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__ContractingMethod__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ContractingMethod__c</fullName>
    <description>&quot;By Subscription End Date&quot; creates a separate Contract for each unique Subscription End Date, containing only those Subscriptions. &quot;Single Contract&quot; creates one Contract containing all Subscriptions, regardless of their End Dates.</description>
    <inlineHelpText>&quot;By Subscription End Date&quot; creates a separate Contract for each unique Subscription End Date, containing only those Subscriptions. &quot;Single Contract&quot; creates one Contract containing all Subscriptions, regardless of their End Dates.</inlineHelpText>
    <label>Contracting Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>By Subscription End Date</fullName>
                <default>true</default>
                <label>By Subscription End Date</label>
            </value>
            <value>
                <fullName>Single Contract</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Primary__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox which if checked designates the quote as the Primary Quote</description>
    <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__SalesRep__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SalesRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Sales rep responsible for this quote if different from the user who owns the quote record.</description>
    <inlineHelpText>Sales rep responsible for this quote if different from the user who owns the quote record.</inlineHelpText>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_Inventory__c.field-meta.xml
<CustomField>
    <fullName>NATT_Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Selected Serial Number</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Model Number does not match for the Inventory.</errorMessage>
        <filterItems>
            <field>$Source.NATT_Model_Number__c</field>
            <operation>equals</operation>
            <valueField>NATT_Inventory__c.NATT_Model_Number__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>NATT_Inventory__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>NATT_Serial_Number__c</fullName>
    <label>Serial Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>200INT ComfortPro Integrated APU</fullName>
    </customValue>
    <customValue>
        <fullName>210STA ComfortPro Stand-alone APU</fullName>
    </customValue>
    <customValue>
        <fullName>220PWR ComfortPro Power-only APU</fullName>
    </customValue>
    <customValue>
        <fullName>230SKY ComfortPro ClearSky DPF APU</fullName>
    </customValue>
    <customValue>
        <fullName>240EPS ComfortPro Electric APU</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S6 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S7 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S8 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S9 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>20X Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>30S Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>30S with 115v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>30S with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>35X Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>35X with 115v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>35X with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>35X with 230v-3ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>40X with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>40XR with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>50X with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>50XR Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>50XR with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>50XR with 230v-3ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>Neos 100S - Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>Solara APX</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8100</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8500</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 01</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 02</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 03</fullName>
    </customValue>
    <customValue>
        <fullName>X4 7500</fullName>
    </customValue>
    <description>for quoting in cpq for NATT</description>
    <masterLabel>NATT Unit</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/BluEdgeOrderSummaryFormControllerTest.cls
@IsTest
private class BluEdgeOrderSummaryFormControllerTest {
    @TestSetup static void setupData(){
        List<Pricebook2> pbList = new List<Pricebook2>();
        
        pbList.add(new Pricebook2(Name='NATT Units Price Book',IsActive=true));
        insert pbList;
        
        // insert products
        List<Product2> products = new List<Product2>();
        
        Product2 product1 = TestUtil.createProduct('BluEdge (See Options for Price)','BluEdge');
        products.add(product1);
        
        Product2 product2 = TestUtil.createProduct('BluEdge Core','BluEdge Core');
        products.add(product2);
        
        Product2 product3 = TestUtil.createProduct('BluEdge Enhance','BluEdge Enhance');
        products.add(product3);
        
        Product2 product4 = TestUtil.createProduct('BluEdge Elite','BluEdge Elite');
        products.add(product4);
        
        insert products;
        
        NATT_Inventory__c inventory = new NATT_Inventory__c();
        inventory.Name = 'Test';
        inventory.NATT_Serial_Number__c = 'SR12345';
        inventory.NATT_Business_Unit__c = 'TT';
        
        insert inventory;
        
        // get standard price book id
        Id pricebookId = Test.getStandardPricebookId();
        
        // insert price book entries
        List<PriceBookEntry> pBEs = new List<PriceBookEntry>();
        PriceBookEntry pBE1 = TestUtil.createPriceBookEntry(pricebookId, products[0].Id);
        pBEs.add(pBE1);   
        
        List<SBQQ__LookupData__c> lkDataList = new List<SBQQ__LookupData__c>();
        
        lkDataList.add(TestUtil.createLookupData(products[0].Id,Date.today().addYears(1),Date.today().addYears(2),'Unit Pricing'));
        insert lkDataList;
        
        List<Account> aList = new List<Account>();
        alist.add(new Account(Name='Test Dealer',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()));
        aList.add(new Account(Name='Customer',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId()));
        
        insert aList;
        
        // assignes dealership to end customer
        aList[1].NATT_Dealership__c = aList.get(0).Id;
        
        update aList[1];
        
        List<AccountTeamMember> atmList = new List<AccountTeamMember>();
        atmList.add(new AccountTeamMember(AccountId=aList.get(0).Id,UserId=UserInfo.getUserId(),TeamMemberRole='EAM - NATT'));
        atmList.add(new AccountTeamMember(AccountId=aList.get(0).Id,UserId=UserInfo.getUserId(),TeamMemberRole='RD - NATT'));
        atmList.add(new AccountTeamMember(AccountId=aList.get(0).Id,UserId=UserInfo.getUserId(),TeamMemberRole='Director of Sales - NATT'));
        insert atmList;
        
        List<Opportunity> oppList = new List<Opportunity>();
        oppList.add(new Opportunity(Name='UnitsTestOpp',
                                    CloseDate=Date.today().addDays(30),
                                    StageName='Qualification',
                                    AccountId=aList.get(0).Id,
                                    NATT_End_Customer__c = aList.get(1).Id,
                                    RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NATT_Opportunity_Units').getRecordTypeId(),
                                    NATT_Stock__c=true));
        oppList.add(new Opportunity(Name='UnitsTestOpp2',
                                    CloseDate=Date.today().addDays(30),
                                    StageName='Qualification',
                                    AccountId=aList.get(0).Id,
                                    NATT_End_Customer__c = aList.get(1).Id,
                                    RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NATT_Opportunity_Units').getRecordTypeId(),
                                    NATT_Stock__c=true));
        insert oppList;
    }
    
    
    @isTest static void setOrderQLDetailsTestCore(){
        Product2 prod2 = [Select Id From Product2 Where Name = 'BluEdge Core'];
        NATT_Inventory__c inv = [Select Id From NATT_Inventory__c LIMIT 1];
        Account acc = [Select Id From Account Where Name = 'Test Dealer'];
        Account accEndCustomer = [Select Id From Account Where Name = 'Customer'];
        List<Product2> prds = [Select Id,Name From Product2];
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new User(Alias = 'sysadm', Email='sysadm@testorg.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,
                          TimeZoneSidKey='America/Los_Angeles',
                          UserName='sysadm@testorg.com');
        insert u;
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name='UnitsTestOpp'];                 
        
        String quoteOriginalId = NattQuoteCon.createQuote(opp.Id,true);
        SBQQ__Quote__c quoteOrig = new SBQQ__Quote__c(Id=quoteOriginalId, SBQQ__Account__c = acc.Id, NATT_End_Customer__c = accEndCustomer.Id, SBQQ__SalesRep__c = u.Id,
                                                      NATT_BluEdge_Core__c = true, SBQQ__ContractingMethod__c = 'By Subscription End Date', SBQQ__Primary__c = true,
                                                      NATT_Unit__c = 'X4 7500', NATT_BluEdge_Price_Per_Hour_End_Customer__c = 100, NATT_Dealer_Copy__c = TRUE,
                                                      RecordTypeId = Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByDeveloperName().get('NATT_BluEdge').getRecordTypeId(),
                                                      NATT_Product_Family__c = 'Trailer', SBQQ__BillingStreet__c = '221B Baker Street',
                                                      SBQQ__ExpirationDate__c = System.Date.Today().addDays(30), NATT_Purchase_Order__c = 'PO123#',SBQQ__Status__c='Approved');
        update quoteOrig;
        
        List<SBQQ__QuoteLine__c> lstQuoteLines = new List<SBQQ__QuoteLine__c>();
        lstQuoteLines.add(new SBQQ__QuoteLine__c(SBQQ__Product__c = prod2.Id, NATT_P_N__c = 'BLUEDGE-CORE', SBQQ__Quantity__c = 10, SBQQ__Quote__c = quoteOriginalId,
                                                NATT_Is_Base_Unit__c = true, NATT_Requested_Ship_Date__c = System.Date.Today(), NATT_End_Customer_Price__c = 100,
                                                SBQQ__ListPrice__c = 100, NATT_Inventory__c = inv.Id));
        
        insert lstQuoteLines;
        
        List<Order> odrs = new List<Order>();
        odrs.add(TestUtil.createOrder(acc,Date.today(),'Draft'));
        insert odrs;
        
        odrs[0].SBQQ__Quote__c = quoteOriginalId;
        odrs[0].SBQQ__ContractingMethod__c = 'By Subscription End Date';
        odrs[0].NATT_Original_Order_Id__c = odrs[0].Id;
        
        update odrs[0];
        
        
        Test.StartTest();
        try{  
            PageReference pageRef = Page.BluEdgeQuoteSummaryForm;
            pageRef.getParameters().put('id', String.valueOf(odrs[0].Id));
            Test.setCurrentPage(pageRef);
            ApexPages.StandardController sc = new ApexPages.StandardController(odrs[0]);
            BluEdgeOrderSummaryFormController test234 = new BluEdgeOrderSummaryFormController(sc);
        }
        catch(Exception e){
            System.debug(e);
        }
        Test.StopTest();
    }
    
    @isTest static void setQuoteQLDetailsTestCore(){
        Product2 prod2 = [Select Id From Product2 Where Name = 'BluEdge Core'];
        NATT_Inventory__c inv = [Select Id From NATT_Inventory__c LIMIT 1];
        Account acc = [Select Id From Account Where Name = 'Test Dealer'];
        Account accEndCustomer = [Select Id From Account Where Name = 'Customer'];
        List<Product2> prds = [Select Id,Name From Product2];
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new User(Alias = 'sysadm', Email='sysadm@testorg.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,
                          TimeZoneSidKey='America/Los_Angeles',
                          UserName='sysadm@testorg.com');
        insert u;
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name='UnitsTestOpp'];                 
        
        String quoteOriginalId = NattQuoteCon.createQuote(opp.Id,true);
        SBQQ__Quote__c quoteOrig = new SBQQ__Quote__c(Id=quoteOriginalId, SBQQ__Account__c = acc.Id, NATT_End_Customer__c = accEndCustomer.Id, SBQQ__SalesRep__c = u.Id,
                                                      NATT_BluEdge_Core__c = true, SBQQ__ContractingMethod__c = 'By Subscription End Date', SBQQ__Primary__c = true,
                                                      NATT_Unit__c = 'X4 7500', NATT_BluEdge_Price_Per_Hour_End_Customer__c = 100, NATT_Dealer_Copy__c = TRUE,
                                                      RecordTypeId = Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByDeveloperName().get('NATT_BluEdge').getRecordTypeId(),
                                                      NATT_Product_Family__c = 'Trailer', SBQQ__BillingStreet__c = '221B Baker Street',
                                                      SBQQ__ExpirationDate__c = System.Date.Today().addDays(30), NATT_Purchase_Order__c = 'PO123#',SBQQ__Status__c='Approved');
        update quoteOrig;
        
        List<SBQQ__QuoteLine__c> lstQuoteLines = new List<SBQQ__QuoteLine__c>();
        lstQuoteLines.add(new SBQQ__QuoteLine__c(SBQQ__Product__c = prod2.Id, NATT_P_N__c = 'BLUEDGE-CORE', SBQQ__Quantity__c = 10, SBQQ__Quote__c = quoteOriginalId,
                                                NATT_Is_Base_Unit__c = true, NATT_Requested_Ship_Date__c = System.Date.Today(), NATT_End_Customer_Price__c = 100,
                                                SBQQ__ListPrice__c = 100, NATT_Inventory__c = inv.Id));
        
        insert lstQuoteLines;      
        
        Test.StartTest();
        try{
            PageReference pageRef = Page.BluEdgeQuoteSummaryForm;
            pageRef.getParameters().put('id', String.valueOf(quoteOrig.Id));
            Test.setCurrentPage(pageRef);
            ApexPages.StandardController sc = new ApexPages.StandardController(quoteOrig);
            BluEdgeOrderSummaryFormController test234 = new BluEdgeOrderSummaryFormController(sc);
        }
        catch(Exception e){
            System.debug(e);
        }
        Test.StopTest();
    }
}