NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Customer_Price_Group__c.field-meta.xml
<CustomField>
    <fullName>NATT_Customer_Price_Group__c</fullName>
    <description>PPG Price List to which the account is assigned</description>
    <label>Customer Price Group</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <description>NATT</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>NATT End User/End Customer Accounts</description>
    <label>Customer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>NATT Internal Customer Accounts</description>
    <label>Internal</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Discount_Code__mdt/Discount_Code__mdt.object-meta.xml
<CustomObject>
    <description>Discount Code value that is derived from Product2.NATT_ItemPriceGroup__c value</description>
    <label>Discount Code</label>
    <pluralLabel>Discount Codes</pluralLabel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/Discount_Code__mdt/fields/Discount_Code_Value__c.field-meta.xml
<CustomField>
    <fullName>Discount_Code_Value__c</fullName>
    <label>Discount Code Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Discount_Code__mdt/fields/Item_Price_Group__c.field-meta.xml
<CustomField>
    <fullName>Item_Price_Group__c</fullName>
    <label>Item Price Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_AlternativeItem__c/NATT_AlternativeItem__c.object-meta.xml
<CustomObject>
    <description>Custom object for storing alternative item entries (e.g. items that supersede other catalog items)</description>
    <label>NATT Alternative Item</label>
    <nameField>
        <displayFormat>NAI-{00000000}</displayFormat>
        <label>NATT Alternative Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NATT Alternative Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_AlternativeItem__c/fields/Alternative_P_N__c.field-meta.xml
<CustomField>
    <fullName>Alternative_P_N__c</fullName>
    <formula>NATT_AlternativeItem__r.NATT_P_N__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Alternative P/N</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_AlternativeItem__c/fields/NATT_AlternativeItem__c.field-meta.xml
<CustomField>
    <fullName>NATT_AlternativeItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Item that is being provided as an alternative to the Product Item</description>
    <inlineHelpText>Item that is being provided as an alternative to the Product Item</inlineHelpText>
    <label>Alternative Item</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>NATT Alternative Items (Alternative Item)</relationshipLabel>
    <relationshipName>NATT_Alternative_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_AlternativeItem__c/fields/NATT_ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_ExpiryDate__c</fullName>
    <description>Date the alternative item expires</description>
    <inlineHelpText>Date the alternative item expires</inlineHelpText>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_AlternativeItem__c/fields/NATT_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>NATT_Part_Number__c</fullName>
    <formula>NATT_ProductItem__r.NATT_P_N__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Part Number</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_AlternativeItem__c/fields/NATT_ProductItem__c.field-meta.xml
<CustomField>
    <fullName>NATT_ProductItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Item that is being superseded by the item shown in the Alternative Item field</description>
    <inlineHelpText>Item that is being superseded by the item shown in the Alternative Item field</inlineHelpText>
    <label>Product Item</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>NATT Alternative Items</relationshipLabel>
    <relationshipName>NATT_Alternative_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <formula>TEXT(Account.NATT_Region__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/recordTypes/NAC.recordType-meta.xml
<RecordType>
    <fullName>NAC</fullName>
    <active>true</active>
    <description>Record type created for NAC Orders</description>
    <label>NAC</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/PricebookEntry/fields/NATT_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>NATT_Effective_Date__c</fullName>
    <description>Indicates the date this pricebook entry was effective. The field supports the PPG B2B Commerce implementation, and provides information necessary to generate price change reports.</description>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Cat_Cde6_Description__c.field-meta.xml
<CustomField>
    <fullName>NATT_Cat_Cde6_Description__c</fullName>
    <label>Cat Cd6 Product Code Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Cat_Code7_Description_Family__c.field-meta.xml
<CustomField>
    <fullName>NATT_Cat_Code7_Description_Family__c</fullName>
    <label>Cat Cd7 Product Family Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Category__c.field-meta.xml
<CustomField>
    <fullName>NATT_Category__c</fullName>
    <description>Category for TES Products.</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APU</fullName>
            </value>
            <value>
                <fullName>COMPRESSOR</fullName>
            </value>
            <value>
                <fullName>DRIVE</fullName>
            </value>
            <value>
                <fullName>ELECTRICAL</fullName>
            </value>
            <value>
                <fullName>ENGINE</fullName>
            </value>
            <value>
                <fullName>GASKETS</fullName>
            </value>
            <value>
                <fullName>HARDWARE</fullName>
            </value>
            <value>
                <fullName>REFRIGERATION</fullName>
            </value>
            <value>
                <fullName>STRUCTURAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_CoreItem_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_CoreItem_P_N__c</fullName>
    <description>Text field containing the part number of the core item. Core items are not stored in the product catalog.</description>
    <label>Core Item P/N</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Height__c.field-meta.xml
<CustomField>
    <fullName>NATT_Height__c</fullName>
    <description>Height of the item in Inches</description>
    <label>Height</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_ItemPriceGroup__c.field-meta.xml
<CustomField>
    <fullName>NATT_ItemPriceGroup__c</fullName>
    <description>A number identifying the price group to which the item belongs</description>
    <label>Item Price Group</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Length__c.field-meta.xml
<CustomField>
    <fullName>NATT_Length__c</fullName>
    <description>Length of the item in Inches</description>
    <label>Length</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_P_N__c</fullName>
    <description>The Part Number for NATT JDE</description>
    <label>Part Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_PpgDiscountCode__c.field-meta.xml
<CustomField>
    <fullName>NATT_PpgDiscountCode__c</fullName>
    <description>PPG-specific discount code</description>
    <label>PPG Discount Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Price_Tier_Code__c.field-meta.xml
<CustomField>
    <fullName>NATT_Price_Tier_Code__c</fullName>
    <label>Price Tier Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_SignalCode__c.field-meta.xml
<CustomField>
    <fullName>NATT_SignalCode__c</fullName>
    <description>JDE Signal Code for the item</description>
    <label>Signal Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>NLO</fullName>
            </value>
            <value>
                <fullName>NSI</fullName>
            </value>
            <value>
                <fullName>NSU</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S1D</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
            <value>
                <fullName>NRC</fullName>
            </value>
            <value>
                <fullName>BY2</fullName>
                <label>BUYER HOLD</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <label>NOT AVAILABLE</label>
            </value>
            <value>
                <fullName>OB1</fullName>
            </value>
            <value>
                <fullName>OBS</fullName>
            </value>
            <value>
                <fullName>PRC</fullName>
            </value>
            <value>
                <fullName>NEW</fullName>
            </value>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>PSR</fullName>
            </value>
            <value>
                <fullName>VIN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_UnitCost__c.field-meta.xml
<CustomField>
    <fullName>NATT_UnitCost__c</fullName>
    <description>Contains the unit cost of the item in USD. The purpose of the field is to overcome a B2B Commerce limitation of 1 basis price per storefront, and is used when generating price book prices for internal PPG customers.</description>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_UOM_Conversion__c.field-meta.xml
<CustomField>
    <fullName>NATT_UOM_Conversion__c</fullName>
    <description>NATT unit of measure conversion factor</description>
    <label>UOM Conversion</label>
    <precision>15</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Weight__c.field-meta.xml
<CustomField>
    <fullName>NATT_Weight__c</fullName>
    <description>Item weight in US pounds</description>
    <label>Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Width__c.field-meta.xml
<CustomField>
    <fullName>NATT_Width__c</fullName>
    <description>Width of the item in Inches</description>
    <label>Width</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/recordTypes/NATT_Products.recordType-meta.xml
<RecordType>
    <fullName>NATT_Products</fullName>
    <active>true</active>
    <description>For use with NATT CPQ</description>
    <label>NATT Products</label>
</RecordType>

NATTQA-ENV/force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>East</fullName>
    </customValue>
    <customValue>
        <fullName>West</fullName>
    </customValue>
    <customValue>
        <fullName>South</fullName>
    </customValue>
    <customValue>
        <fullName>Central</fullName>
    </customValue>
    <customValue>
        <fullName>National</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Latin America</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Region 1</fullName>
    </customValue>
    <customValue>
        <fullName>Region 2</fullName>
    </customValue>
    <customValue>
        <fullName>Region 3</fullName>
    </customValue>
    <customValue>
        <fullName>Northeast</fullName>
    </customValue>
    <customValue>
        <fullName>Southeast</fullName>
    </customValue>
    <customValue>
        <fullName>Midwest</fullName>
    </customValue>
    <customValue>
        <fullName>North</fullName>
    </customValue>
    <customValue>
        <fullName>Europe, Middle East and Africa</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pacific and Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>Americas</fullName>
        <isActive>false</isActive>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>undefined</fullName>
        <isActive>false</isActive>
        <label>undefined</label>
    </customValue>
    <customValue>
        <fullName>Asia</fullName>
        <isActive>false</isActive>
        <label>Asia</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/NATT_PriceFileController.cls
public with sharing class NATT_PriceFileController {

    /**
     * Grabs Customer Price Group for LWC component
     * Has logic to check for CTM & CTBR Stores
     */
    @AuraEnabled
    public static String getCustomerPriceGroup(){
        User usr = [SELECT Id,Contact.Account.NATT_Customer_Price_Group__c, Contact.Account.NATT_Region__c FROM User WHERE Id=:UserInfo.getUserId()];
        //CTM Storefront Check
        if(usr.Contact.Account.NATT_Region__c == 'Mexico'){
            return 'CTM MEX';
        }else if(usr.Contact.Account.NATT_Region__c == 'Latin America'){
            return 'CTM LATM';
        //CTBR Storefront Check
        }else if(usr.Contact.Account.NATT_Customer_Price_Group__c== 'BCO'){
            return 'CTBR Storefront Container';
        }else if(usr.Contact.Account.NATT_Customer_Price_Group__c== 'BTT'){
            return 'CTBR Storefront Truck Trailer';
        //All Other Stores
        }else{
            return usr.Contact.Account.NATT_Customer_Price_Group__c;
        }
    }

    /**
     * Main method used for populating Price File tabs.
     * Uses different parameters to determine which tab the data is queried for (Complete, Price Changes, Advanced Books)
     * Customer Price Group will always be populated. 
     * DayValue used for Complete Price Files & Advanced Date used for Advanced Books
     */
    @ReadOnly
    @RemoteAction 
    @AuraEnabled(cacheable = false)
    public static PriceFileWrapper grabPriceFileDetails(String customerPriceGroup, Integer limitValue, String lastRecordId, String lastRecordName, String nextOrPrevious, String dayValue, String advancedDate){
        
        System.debug('Day value at start: ' + dayValue);
        Set<Id> productIdSet = new Set<Id>();
        PriceFileWrapper pFWrapper = new PriceFileWrapper();
        List<PriceFileEntry> priceFileEntryList = new List <PriceFileEntry>();
        String lastDayValue = null;
        Integer dayInt = 0;
        if (dayValue != null){
            lastDayValue = 'LAST_N_DAYS:'+dayValue;
            dayInt = Integer.valueOf(dayValue);
        }
        if (advancedDate != null){
            advancedDate = Datetime.now().format('yyyy-MM-dd');
        }
        //Exit this method and return null if no Customer Price Group was found
        if(customerPriceGroup == null || customerPriceGroup == ''){
            return pFWrapper;
        }

        Integer offsetValue = 0;
        Decimal priceValueIfNoCPG = 0;

        List<Discount_Code__mdt> discountCodeValues = [SELECT Discount_Code_Value__c, Item_Price_Group__c FROM Discount_Code__mdt];

        Integer pCount = [SELECT COUNT()
                            FROM PricebookEntry 
                            WHERE Pricebook2.Name = :customerPriceGroup 
                                AND IsActive = true 
                                AND Product2.IsActive = true AND Product2.RecordType.Name != 'NAC Products' ];
        pFWrapper.recordCount = pCount;
        grabProductItems(customerPriceGroup, limitValue, offsetValue, productIdSet, priceFileEntryList ,discountCodeValues, lastRecordId, lastRecordName, nextOrPrevious, lastDayValue, advancedDate, dayInt);
        pFWrapper.priceFiles = priceFileEntryList;
        for(PriceFileEntry pfe : pFWrapper.priceFiles){
            productIdSet.add(pfe.Id);
        }
        List<NATT_AlternativeItem__c> altItemList = [
            SELECT Alternative_P_N__c, NATT_Part_Number__c, NATT_ALternativeItem__c, NATT_ProductItem__c, NATT_ExpiryDate__c 
            FROM NATT_AlternativeItem__c
            WHERE NATT_ExpiryDate__c > TODAY AND NATT_ProductItem__c IN :productIdSet
            ORDER BY NATT_ExpiryDate__c ASC
        ];
        Map<String,String> altItemMatch = new Map<String,String>();
        for(NATT_AlternativeItem__c altItem : altItemList){
            if(altItemMatch.containsKey(altItem.NATT_ProductItem__c)){
                continue;
            }
            altItemMatch.put(altItem.NATT_ProductItem__c,altItem.Alternative_P_N__c);
        }
        for(PriceFileEntry entry : pFWrapper.priceFiles){
            //Signal Code Check here
            // if(entry.SignalCode == 'S2'){
            //     entry.Supersedure = altItemMatch.get(entry.Id);
            // }
        }
        return pFWrapper;
    }
    
    /**
     * Method used to grab and populate the Price File products.
     * PricebookEntry list gets queried and those values are used to populate the Price File Entry wrapper
     */
    private static void grabProductItems(String customerPriceGroup, Integer limitValue, Integer offsetValue, Set<Id> productIdSet, 
                                            List<PriceFileEntry> priceFileEntryList,  
                                            List<Discount_Code__mdt> discountCodeValues, String lastRecordId, String lastRecordName, String nextOrPrevious, String lastDayValue,  String advancedDate, Integer dayInt){
        List <PricebookEntry> pbeList = grabPricebookEntries(customerPriceGroup, limitValue, lastRecordId, lastRecordName, nextOrPrevious, lastDayValue, advancedDate, offsetValue);
        if(nextOrPrevious != null){
            pbeList.sort();
        }
        
        for(PricebookEntry pbe : pbeList){
            productIdSet.add(pbe.Product2Id);
        }
        Map<Id, PricebookEntry> priceBookCheck = new Map<Id, PricebookEntry>();
        Set <PricebookEntry> noDuplicatePBE = new Set <PricebookEntry>();
        List <PricebookEntry> standardPBE = new List <PricebookEntry>();
        List <PricebookEntry> pricebookEntryListBeforeCheck = new List <PricebookEntry>();

        //If lastDayValue found, Price Change logic used
        if(lastDayValue != null){
           String soql = 'SELECT ProductCode, UnitPrice, ID, Product2Id, Pricebook2Id, NATT_Effective_Date__c, Product2.Description, Product2.NATT_UnitCost__c,  Product2.NATT_Core__c, '+
            'Product2.NATT_SignalCode__c, Product2.NATT_PpgDiscountCode__c, Product2.NATT_Weight__c, Product2.NATT_Height__c, Product2.NATT_Length__c, Product2.NATT_Width__c, Product2.NATT_UOM_Conversion__c, '+
            'Product2.NATT_CoreItem_P_N__c, Product2.NATT_ItemPriceGroup__c,  Product2.Name, Product2.NATT_P_N__c, Product2.NATT_Price_Tier_Code__c,Product2.NATT_Cat_Code7_Description_Family__c,Product2.NATT_Cat_Cde6_Description__c, Product2.NATT_Category__c, Product2.NATT_SubCategory__c '+
            'FROM PricebookEntry WHERE IsActive = true AND Product2.IsActive = true AND Pricebook2.Name LIKE \'%'+ customerPriceGroup +'%\' AND Product2.RecordType.Name != \'NAC Products\' ORDER BY Product2.Name, Id ';
            pricebookEntryListBeforeCheck = Database.query(soql);
        }else{
            pricebookEntryListBeforeCheck = [SELECT Product2.NATT_P_N__c, UnitPrice, ID, Product2Id, Pricebook2Id, NATT_Effective_Date__c, Product2.Description, Product2.NATT_UnitCost__c
                                        FROM PricebookEntry 
                                        WHERE Product2Id IN :productIdSet
                                            AND Product2Id IN :productIdSet
                                            AND IsActive = true AND Pricebook2.IsStandard=true
                                            AND Product2Id IN :productIdSet AND Product2.RecordType.Name != 'NAC Products' LIMIT 100];
        }
        for(PricebookEntry pbe : pricebookEntryListBeforeCheck){
            priceBookCheck.put(pbe.Product2Id, pbe);
        }
        for(PricebookEntry entry : pbeList){
            PriceFileEntry pfItem = new PriceFileEntry();
            //If Price Change, checks to see if queried Standard Pricebook Entry exists in CPG Pricebook
            if(lastDayValue != null){
                if(priceBookCheck.containsKey(entry.Product2Id)){
                    pfItem = createPriceFileWrapperItem(entry, pfItem, priceBookCheck, lastDayValue, productIdSet, discountCodeValues, customerPriceGroup);
                    priceFileEntryList.add(pfItem);
                }
            }else{
                pfItem = createPriceFileWrapperItem(entry, pfItem, priceBookCheck, lastDayValue, productIdSet, discountCodeValues, customerPriceGroup);
                priceFileEntryList.add(pfItem);
            }
           
        }  

    }
    /**
     * Method used to create PriceFileEntry Wrapper.
     * Price Changes queries Standard Pricebook instead of CPG Pricebook, so logic changes based on if Price Changes is running
     */
    private static PriceFileEntry createPriceFileWrapperItem(PricebookEntry entry, PriceFileEntry pfItem, Map<Id, PricebookEntry> priceBookCheck, String lastDayValue, Set<Id> productIdSet, List<Discount_Code__mdt> discountCodeValues, String customerPriceGroup){
        pfItem.PKG = entry.Product2.NATT_UOM_Conversion__c;
 
        //Basis price should be from Standard Price Book
        if(lastDayValue != null){
            pfItem.BasisPrice = entry.UnitPrice.setScale(2, RoundingMode.HALF_UP);
        }else{
            pfItem.BasisPrice = priceBookCheck.containsKey(entry.Product2Id)?priceBookCheck.get(entry.Product2Id).UnitPrice.setScale(2, RoundingMode.HALF_UP):0;
        }
        if(pfItem.PKG > 1 && (pfItem.BasisPrice != null && pfItem.BasisPrice != 0)){
            pfItem.EachPrice = pfItem.BasisPrice/pfItem.PKG;
            pfItem.EachPrice = pfItem.EachPrice.setScale(2, RoundingMode.HALF_UP);
        }else{
            pfItem.EachPrice =  pfItem.BasisPrice.setScale(2, RoundingMode.HALF_UP);
        }
        //Internal Customer Check
        if(customerPriceGroup.startsWith('V1') && entry.Product2.NATT_UnitCost__c != null){
            //Transfer price assigned only for Internal Customers
            pfItem.TransferPrice = priceBookCheck.containsKey(entry.Product2Id)?priceBookCheck.get(entry.Product2Id).UnitPrice.setScale(2, RoundingMode.HALF_UP):0;//entry.UnitPrice.setScale(2, RoundingMode.HALF_UP);
        }
        
        pfItem.ExchCore = entry.Product2.NATT_CoreItem_P_N__c != null?'YES':'NO';               
        pfItem.CoreReference = entry.Product2.NATT_CoreItem_P_N__c;            

        if(entry.Product2.NATT_Core__c){
            pfItem.ExchCore = 'CORE';
        }                

        pfItem.PartNumber = entry.Product2.NATT_P_N__c;
        pfItem.Id = entry.Product2Id;
        pfItem.Description = entry.Product2.Name;
        pfItem.Description = pfItem.Description.replaceAll(',',' ').replaceAll('  ',' ').trim();
        pfItem.SignalCode = entry.Product2.NATT_SignalCode__c;
        pfItem.DiscountCode = grabDiscountCode(entry.Product2.NATT_ItemPriceGroup__c, discountCodeValues);
        pfItem.Weight = entry.Product2.NATT_Weight__c;
        pfItem.Length = entry.Product2.NATT_Length__c;
        pfItem.Width = entry.Product2.NATT_Width__c;
        pfItem.Height = entry.Product2.NATT_Height__c;
        //Effective date assigned from standard pricebook
        if(lastDayValue != null){
            pfItem.EffectiveDate = entry.NATT_Effective_Date__c;
        }else{
            pfItem.EffectiveDate = priceBookCheck.containsKey(entry.Product2Id)?priceBookCheck.get(entry.Product2Id).NATT_Effective_Date__c:null;
        }
        return pfItem;
    }

    /**
     * Queries Pricebook Entries. Depending on the values that are passed in, it will trigger different additions to the SOQL statement.
     * The different SOQL statemnet additions relate to the different funcitonalities/tabs related to Price Files
     * 
     */
    
    private static List <PricebookEntry> grabPricebookEntries(String customerPriceGroup, Integer limitValue, String lastRecordId, String lastRecordName, String nextOrPrevious, String lastDayValue, String advancedDate, Integer offsetValue){
        String soql = 'SELECT ProductCode, UnitPrice, ID, Product2Id, Pricebook2Id, NATT_Effective_Date__c, Product2.Description, Product2.NATT_UnitCost__c,  Product2.NATT_Core__c, '+
                            'Product2.NATT_SignalCode__c, Product2.NATT_PpgDiscountCode__c, Product2.NATT_Weight__c, Product2.NATT_Height__c, Product2.NATT_Length__c, Product2.NATT_Width__c, Product2.NATT_UOM_Conversion__c, '+
                            'Product2.NATT_CoreItem_P_N__c, Product2.NATT_ItemPriceGroup__c,  Product2.Name, Product2.NATT_P_N__c '+
                            'FROM PricebookEntry WHERE IsActive = true AND Product2.IsActive = true AND Product2.RecordType.Name != \'NAC Products\' ';
                    
        //lastDayValue used in Price Changes to determine amount of time for the query
        //CTM Storefront does not use Standard Price Book
        System.debug('CustomerPriceGroup Value: ' + customerPriceGroup);
        if(customerPriceGroup == 'CTM MEX' || customerPriceGroup == 'CTM LATM' || customerPriceGroup == 'CTBR Storefront Container' || customerPriceGroup == 'CTBR Storefront Truck Trailer'){
            if(lastDayValue != null){
                soql += 'AND Pricebook2.Name LIKE \'%'+ customerPriceGroup +'%\' AND (NATT_Effective_Date__c =' + lastDayValue + ' ) ';
            }else{
                soql += 'AND Pricebook2.Name LIKE \'%'+ customerPriceGroup +'%\'';
            }
        }else{
            if(lastDayValue != null){
                soql += 'AND Pricebook2.Name = \'Standard Price Book\' AND (NATT_Effective_Date__c =' + lastDayValue + ' ) ';
            }else{
                soql += 'AND Pricebook2.Name = \''+ customerPriceGroup +'\' ';
            }
        }
        //nextOrPrevious used in Complete Price Files for navigation
        System.debug('Next or Previous: ' + nextOrPrevious);
        if(nextOrPrevious != null){
            //replace catches '' in Product name and reformats characters so they work in SOQL query.
            lastRecordName = lastRecordName.replace('\'\'','\\'+'\''+'\\'+'\'' );
            lastRecordName = String.escapeSingleQuotes(lastRecordName);
        }

        //advancedDate used in Advanced Books to determine the current date used in query (queries any product thats effective after today)
        if(advancedDate != null){
             soql += 'AND (NATT_Effective_Date__c >' + advancedDate + ' )';
        }
        soql += ' ORDER BY Product2.Name, Id ';
        //limitValue determines how many products get queried. Used mainly for pagination in Complete Price Files
        if(limitValue != null && (lastDayValue == null || advancedDate == null)){
            soql += 'LIMIT ' + limitValue +'';
        }else{
            if(offsetValue != null){
                soql += ' OFFSET ' + offsetValue + '';
            }
        }
        List<PricebookEntry> pbeList = Database.query(soql);
        return pbeList;
    }

    /**
     * Queries Discount Code from metadata using the Product's itemPriceGroup value
     */
    private static String grabDiscountCode(String itemPriceGroup, List<Discount_Code__mdt> discountCodeValues){
        String returnValue;
        for(Discount_Code__mdt discountCodeMeta : discountCodeValues){
            if(discountCodeMeta.Item_Price_Group__c == itemPriceGroup){
                returnValue = discountCodeMeta.Discount_Code_Value__c;
                break;
            }else{
                returnValue = 'A';
            }
        }
        return returnValue;
    }

    public Class PriceFileWrapper {
        @AuraEnabled public List < PriceFileEntry > priceFiles {get;set;}
        @AuraEnabled public Integer recordCount {get;set;}
    }

    public class PriceFileEntry {
        @AuraEnabled public String Id {get;set;}
        @AuraEnabled public String PartNumber {get;set;}
        @AuraEnabled public String Description {get;set;}
        @AuraEnabled public Decimal PKG {get;set;}
        @AuraEnabled public String Supersedure {get;set;}
        @AuraEnabled public Decimal EachPrice {get;set;}
        @AuraEnabled public String ExchCore {get;set;}
        @AuraEnabled public String CoreReference {get;set;}
        @AuraEnabled public String SignalCode {get;set;}
        @AuraEnabled public String DiscountCode {get;set;}
        @AuraEnabled public Decimal Weight {get;set;}
        @AuraEnabled public Decimal Length {get;set;}
        @AuraEnabled public Decimal Width {get;set;}
        @AuraEnabled public Decimal Height {get;set;}
        @AuraEnabled public Date EffectiveDate {get;set;}
        @AuraEnabled public Decimal BasisPrice {get;set;}
        @AuraEnabled public Decimal TransferPrice {get;set;}
        @AuraEnabled public String CoreFlag {get;set;}
        @AuraEnabled public String ProductCategory {get;set;}
        @AuraEnabled public String ProductSubCategory {get;set;}
        @AuraEnabled public String PriceTierCode {get;set;}
    }

    @ReadOnly
    @RemoteAction
    @AuraEnabled
    public static PriceFileWrapper getPriceFileDetails(String customerPriceGroup){
        boolean isV1 = customerPriceGroup.startsWith('V1');
        customerPriceGroup = '%'+customerPriceGroup+'%';
        Map<Id,PricebookEntry> pbeMap = new Map<Id,PricebookEntry>();
        Map<Id,PricebookEntry> standardPbeMap = new Map<Id,PricebookEntry>();
        PriceFileWrapper pfw = new PriceFileWrapper();    
        //boolean isV1 = customerPriceGroup.startsWith('V1');
       
        List<PriceFileEntry> priceFileEntryList = new List <PriceFileEntry>();
        Map<String,String> discountCodeMap = new Map<String,String>();

        for(Discount_Code__mdt discountCode :  [SELECT Discount_Code_Value__c, Item_Price_Group__c FROM Discount_Code__mdt]){
            discountCodeMap.put(discountCode.Item_Price_Group__c,discountCode.Discount_Code_Value__c);
        }

        Integer pCount = [SELECT COUNT()
                            FROM PricebookEntry 
                            WHERE Pricebook2.Name LIKE :customerPriceGroup 
                                AND IsActive = true 
                                AND Product2.IsActive = true
                                AND Product2.NATT_SignalCode__c!='NSU' AND Product2.RecordType.Name != 'NAC Products'];
        pfw.recordCount=pCount;

        for(PricebookEntry pbe : [SELECT UnitPrice, Id, Product2Id, NATT_Effective_Date__c
                                    FROM PricebookEntry WHERE IsActive = true 
                                    AND Product2.IsActive = true AND Pricebook2.IsStandard=true
                                    AND Product2.RecordType.DeveloperName='NATT_Products'
                                    AND Product2.NATT_SignalCode__c!='NSU'])
        {
            standardPbeMap.put(pbe.Product2Id,pbe);
        }

        for(PricebookEntry pbe : [SELECT ProductCode, UnitPrice, ID, Product2Id, Pricebook2Id, NATT_Effective_Date__c, Product2.Description, Product2.NATT_UnitCost__c,  Product2.NATT_Core__c,  
                                    Product2.NATT_SignalCode__c, Product2.NATT_PpgDiscountCode__c, Product2.NATT_Weight__c, Product2.NATT_Height__c, Product2.NATT_Length__c, Product2.NATT_Width__c, Product2.NATT_UOM_Conversion__c, 
                                    Product2.NATT_CoreItem_P_N__c, Product2.NATT_ItemPriceGroup__c,  Product2.Name, Product2.NATT_P_N__c, Product2.NATT_Price_Tier_Code__c,Product2.NATT_Cat_Code7_Description_Family__c,Product2.NATT_Cat_Cde6_Description__c, Product2.NATT_Category__c, Product2.NATT_SubCategory__c 
                                    FROM PricebookEntry WHERE IsActive = true AND Product2.IsActive = true AND Pricebook2.Name LIKE :customerPriceGroup AND Product2.NATT_SignalCode__c!='NSU' AND Product2.RecordType.Name != 'NAC Products' ORDER BY Product2.Name])
            {           
            PriceFileEntry pfItem = new PriceFileEntry();         
            
            pfItem.PKG = pbe.Product2.NATT_UOM_Conversion__c;

            //Basis price should be from Standard Price Book if not CTM Storefront
            if(customerPriceGroup == '%CTM MEX%' || customerPriceGroup == '%CTM LATM%' || customerPriceGroup == '%CTBR Storefront Container%' || customerPriceGroup == '%CTBR Storefront Truck Trailer%'){
                pfItem.BasisPrice = pbe.UnitPrice;
            }else{
                pfItem.BasisPrice = standardPbeMap.containsKey(pbe.Product2Id)?standardPbeMap.get(pbe.Product2Id).UnitPrice:0;
            }
            // pfItem.BasisPrice = standardPbeMap.containsKey(pbe.Product2Id)?standardPbeMap.get(pbe.Product2Id).UnitPrice:0;
            
            if(pfItem.PKG > 1 && pfItem.BasisPrice != 0){
                pfItem.EachPrice = pfItem.BasisPrice/pfItem.PKG;
                pfItem.EachPrice = pfItem.EachPrice;
            }else{
                pfItem.EachPrice =  pfItem.BasisPrice;
            }
          
            //Internal Customer Check
            if(isV1 && pbe.Product2.NATT_UnitCost__c != null ){
                //Transfer price assigned only for Internal Customers
                pfItem.TransferPrice = pbe.UnitPrice;
            }
            
            pfItem.ExchCore = pbe.Product2.NATT_CoreItem_P_N__c != null?'YES':'NO';               
            pfItem.CoreReference = pbe.Product2.NATT_CoreItem_P_N__c;            

            if(pbe.Product2.NATT_Core__c){
                pfItem.ExchCore = 'CORE';
            }    
            pfItem.PartNumber = pbe.Product2.NATT_P_N__c;
            pfItem.Id = pbe.Product2Id;
            pfItem.Description = pbe.Product2.Name;
            pfItem.Description = pfItem.Description.replaceAll(',',' ').replaceAll('  ',' ').trim();            
            pfItem.SignalCode = pbe.Product2.NATT_SignalCode__c;
            pfItem.DiscountCode = 'A';
            if(discountCodeMap.containsKey(pbe.Product2.NATT_ItemPriceGroup__c)){
                pfItem.DiscountCode=discountCodeMap.get(pbe.Product2.NATT_ItemPriceGroup__c);
            }
            pfItem.Weight = pbe.Product2.NATT_Weight__c;
            pfItem.Length = pbe.Product2.NATT_Length__c;
            pfItem.Width = pbe.Product2.NATT_Width__c;
            pfItem.Height = pbe.Product2.NATT_Height__c;
                pfItem.ProductCategory = pbe.Product2.NATT_Cat_Code7_Description_Family__c;
                pfItem.ProductSubCategory = pbe.Product2.NATT_Cat_Cde6_Description__c;
                pfItem.PriceTierCode = pbe.Product2.NATT_Price_Tier_Code__c; 
            pfItem.EffectiveDate =standardPbeMap.containsKey(pbe.Product2Id)?standardPbemap.get(pbe.Product2Id).NATT_Effective_Date__c:null; 
            if (pfItem.EffectiveDate != null){System.debug('Name: ' + pbe.Product2.Name + ' || Date: ' + pfItem.EffectiveDate);     }   
         
            priceFileEntryList.add(pfItem);            
        }        
        pfw.priceFiles=priceFileEntryList;
        return pfw;
    }

    @AuraEnabled
    public static Map<String,String> getAltItemMap(){
        try {   
            Map<String,String> altItemMap = new Map<String,String>();
            for(List<NATT_AlternativeItem__c> altItemList :  [SELECT Alternative_P_N__c, NATT_Part_Number__c, NATT_AlternativeItem__c, NATT_ProductItem__c, NATT_ExpiryDate__c 
                                                                FROM NATT_AlternativeItem__c
                                                                WHERE NATT_ExpiryDate__c > TODAY 
                                                                ORDER BY NATT_ExpiryDate__c ASC]){
                for(NATT_AlternativeItem__c altItem: altItemList){
                    if(!altItemMap.containsKey(altItem.NATT_ProductItem__c)){
                        altItemMap.put(altItem.NATT_ProductItem__c,altItem.Alternative_P_N__c);
                    }
                }                
            }    
            return altItemMap;           
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}