NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Organization__c.field-meta.xml
<CustomField>
    <fullName>NATT_Organization__c</fullName>
    <description>NATT</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Geography</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <description>NATT</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Accounts</description>
    <label>Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/NATT_Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>NATT Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_Account__c.field-meta.xml
<CustomField>
    <fullName>NATT_Account__c</fullName>
    <description>NATT</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>NATT_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_City__c.field-meta.xml
<CustomField>
    <fullName>NATT_City__c</fullName>
    <description>NATT</description>
    <label>City</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_Country__c.field-meta.xml
<CustomField>
    <fullName>NATT_Country__c</fullName>
    <description>NATT</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Country_Picklist</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_State_Province__c.field-meta.xml
<CustomField>
    <fullName>NATT_State_Province__c</fullName>
    <description>NATT</description>
    <label>State/Province</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>NATT_State_Picklist</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_Street__c.field-meta.xml
<CustomField>
    <fullName>NATT_Street__c</fullName>
    <description>NATT</description>
    <label>Street</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_Type__c.field-meta.xml
<CustomField>
    <fullName>NATT_Type__c</fullName>
    <description>NATT</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Dealer Agreement</fullName>
            </value>
            <value>
                <fullName>Distribution Centers</fullName>
            </value>
            <value>
                <fullName>Headquarters</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Other Mailing</fullName>
            </value>
            <value>
                <fullName>Parts Ship To</fullName>
            </value>
            <value>
                <fullName>Physical</fullName>
            </value>
            <value>
                <fullName>Regional Offices</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Units Ship To</fullName>
            </value>
            <value>
                <fullName>Bill To</fullName>
            </value>
            <value>
                <fullName>Ship To</fullName>
            </value>
            <value>
                <fullName>TES Ship To</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>NATT_Zip_Postal_Code__c</fullName>
    <description>NATT</description>
    <label>Zip/Postal Code</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/NATT_End_Customer__c.field-meta.xml
<CustomField>
    <fullName>NATT_End_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>the end customer associated with this deal</description>
    <label>End Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>MX_Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CTBR_Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (End Customer)</relationshipLabel>
    <relationshipName>NATTEndCustomerOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <formula>TEXT(Account.NATT_Region__c)</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/NATT_Stock__c.field-meta.xml
<CustomField>
    <fullName>NATT_Stock__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT users check this if there is no end customer</description>
    <label>Stock</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/recordTypes/NATT_Opportunity_Units.recordType-meta.xml
<RecordType>
    <fullName>NATT_Opportunity_Units</fullName>
    <active>true</active>
    <businessProcess>NATT Opportunity Units Sales Process</businessProcess>
    <description>NATT Opportunity Units Recordtype</description>
    <label>Units</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_End_Customer__c.field-meta.xml
<CustomField>
    <fullName>NATT_End_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NATT end customer</description>
    <label>End Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (End Customer)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <formula>TEXT(Account.NATT_Region__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Stock__c.field-meta.xml
<CustomField>
    <fullName>NATT_Stock__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stock</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/recordTypes/NATT_Units_Order.recordType-meta.xml
<RecordType>
    <fullName>NATT_Units_Order</fullName>
    <active>true</active>
    <description>NATT Units Order</description>
    <label>NATT Units Order</label>
</RecordType>

NATTQA-ENV/force-app/main/default/globalValueSets/Geography.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NATT</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>CTB</fullName>
    </customValue>
    <customValue>
        <fullName>Need the others listed</fullName>
        <isActive>false</isActive>
        <label>Need the others listed</label>
    </customValue>
    <masterLabel>Geography</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>East</fullName>
    </customValue>
    <customValue>
        <fullName>West</fullName>
    </customValue>
    <customValue>
        <fullName>South</fullName>
    </customValue>
    <customValue>
        <fullName>Central</fullName>
    </customValue>
    <customValue>
        <fullName>National</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Latin America</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Region 1</fullName>
    </customValue>
    <customValue>
        <fullName>Region 2</fullName>
    </customValue>
    <customValue>
        <fullName>Region 3</fullName>
    </customValue>
    <customValue>
        <fullName>Northeast</fullName>
    </customValue>
    <customValue>
        <fullName>Southeast</fullName>
    </customValue>
    <customValue>
        <fullName>Midwest</fullName>
    </customValue>
    <customValue>
        <fullName>North</fullName>
    </customValue>
    <customValue>
        <fullName>Europe, Middle East and Africa</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pacific and Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>Americas</fullName>
        <isActive>false</isActive>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>undefined</fullName>
        <isActive>false</isActive>
        <label>undefined</label>
    </customValue>
    <customValue>
        <fullName>Asia</fullName>
        <isActive>false</isActive>
        <label>Asia</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/NattAddressSelectionConTest.cls
@IsTest
private class NattAddressSelectionConTest {
    @isTest static void myUnitTest(){
        List<Account> aList = [SELECT Id FROM Account];
        NattAddressSelectionCon.Wrapper w = NattAddressSelectionCon.getAddressList(aList.get(0).Id,aList.get(1).Id,'Billing');
        NattAddressSelectionCon.Wrapper unitsW = NattAddressSelectionCon.getAddressList(aList.get(0).Id,aList.get(1).Id,'Units Ship To');
        
        Opportunity opp = [SELECT Id FROM Opportunity];
        String quoteId = NattQuoteCon.createQuote(opp.Id,true);
        
        NattAddressSelectionCon.getQuoteInfo(quoteId);
        List<Map<String,String>> billingList  = w.dealerAddressList;
        List<Map<String,String>> unitsList  = unitsW.endCustomerAddressList;
        String billingId,unitsId;
        
        billingId=billingList.get(0).get('value');        
        unitsId=unitsList.get(0).get('value');
        
        NattAddressSelectionCon.updateQuote(quoteId,opp.Id,billingId,unitsId);
    }
    
    @isTest static void myUnitTestFromOrder(){
        List<Account> aList = [SELECT Id FROM Account];
        NattAddressSelectionCon.Wrapper w = NattAddressSelectionCon.getAddressList(aList.get(0).Id,aList.get(1).Id,'Billing');
        NattAddressSelectionCon.Wrapper unitsW = NattAddressSelectionCon.getAddressList(aList.get(0).Id,aList.get(1).Id,'Units Ship To');
        Order o = [SELECT Id FROM Order];
        o = NattAddressSelectionCon.getOrderInfo(o.Id);
        List<Map<String,String>> billingList  = w.dealerAddressList;
        List<Map<String,String>> unitsList  = unitsW.endCustomerAddressList;
        String billingId,unitsId;
        
        billingId=billingList.get(0).get('value');        
        unitsId=unitsList.get(0).get('value');
        
        NattAddressSelectionCon.updateOrder(o.Id,billingId,unitsId);
    }
    
    @TestSetup static void setupData(){        
        List<Pricebook2> pbList = new List<Pricebook2>();
        pbList.add(new Pricebook2(Name='NATT Units Price Book',IsActive=true));
        pbList.add(new Pricebook2(Name='NATT Parts Price Book',IsActive=true));
        insert pbList;
        
        List<Account> aList = new List<Account>();
        aList.add(new Account(Name='Test Dealer',NATT_Organization__c = 'NATT',NATT_Region__c = 'East',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()));
        aList.add(new Account(Name='Test Dealer2',NATT_Organization__c = 'NATT',NATT_Region__c = 'East',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()));
        insert aList;
        
        Account a = aList.get(0);
        Account b = aList.get(1);
        
        List<NATT_Address__c> addList = new List<NATT_Address__c>();
        addList.add(new NATT_Address__c(NATT_Account__c=a.Id,NATT_Type__c='Mailing',NATT_Street__c='111 Test Street',NATT_City__c='Dalton',NATT_State_Province__c='GA',NATT_Zip_Postal_Code__c='30720',NATT_Country__c='US'));
        addList.add(new NATT_Address__c(NATT_Account__c=a.Id,NATT_Type__c='Billing',NATT_Street__c='111 Test Street',NATT_City__c='Dalton',NATT_State_Province__c='GA',NATT_Zip_Postal_Code__c='30720',NATT_Country__c='US'));
        addList.add(new NATT_Address__c(NATT_Account__c=a.Id,NATT_Type__c='Units Ship To',NATT_Street__c='111 Test Street',NATT_City__c='Dalton',NATT_State_Province__c='GA',NATT_Zip_Postal_Code__c='30720',NATT_Country__c='US'));
        addList.add(new NATT_Address__c(NATT_Account__c=b.Id,NATT_Type__c='Mailing',NATT_Street__c='111 Test Street',NATT_City__c='Dalton',NATT_State_Province__c='GA',NATT_Zip_Postal_Code__c='30720',NATT_Country__c='US'));
        addList.add(new NATT_Address__c(NATT_Account__c=b.Id,NATT_Type__c='Billing',NATT_Street__c='111 Test Street',NATT_City__c='Dalton',NATT_State_Province__c='GA',NATT_Zip_Postal_Code__c='30720',NATT_Country__c='US'));
        addList.add(new NATT_Address__c(NATT_Account__c=b.Id,NATT_Type__c='Units Ship To',NATT_Street__c='111 Test Street',NATT_City__c='Dalton',NATT_State_Province__c='GA',NATT_Zip_Postal_Code__c='30720',NATT_Country__c='US'));
        insert addList;
        
        Opportunity opp = new Opportunity(Name='TestUnitsOpp',CloseDate=Date.today().addDays(30),StageName='Qualification',AccountId=a.Id,RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NATT_Opportunity_Units').getRecordTypeId(),NATT_Stock__c=true);
        insert opp;
        
        Order o = new Order(OpportunityId=opp.Id,AccountId=a.Id,NATT_End_Customer__c=b.Id,RecordTypeId=Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('NATT_Units_Order').getRecordTypeId(),EffectiveDate=Date.today(),Status='Draft');
        insert o;
    }
}