NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Organization__c.field-meta.xml
<CustomField>
    <fullName>NATT_Organization__c</fullName>
    <description>NATT</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Geography</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <description>NATT</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Status__c.field-meta.xml
<CustomField>
    <fullName>NATT_Status__c</fullName>
    <description>NATT</description>
    <label>NATT Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <isActive>false</isActive>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>NATT End User/End Customer Accounts</description>
    <label>Customer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Accounts</description>
    <label>Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>NATT Internal Customer Accounts</description>
    <label>Internal</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Contact/recordTypes/NATT_Dealer.recordType-meta.xml
<RecordType>
    <fullName>NATT_Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Contacts</description>
    <label>NATT Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Contact/recordTypes/NATT_Inactive_Contact.recordType-meta.xml
<RecordType>
    <fullName>NATT_Inactive_Contact</fullName>
    <active>true</active>
    <description>NATT Inactive Contact</description>
    <label>NATT Inactive Contact</label>
</RecordType>

NATTQA-ENV/force-app/main/default/globalValueSets/Geography.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NATT</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>CTB</fullName>
    </customValue>
    <customValue>
        <fullName>Need the others listed</fullName>
        <isActive>false</isActive>
        <label>Need the others listed</label>
    </customValue>
    <masterLabel>Geography</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>East</fullName>
    </customValue>
    <customValue>
        <fullName>West</fullName>
    </customValue>
    <customValue>
        <fullName>South</fullName>
    </customValue>
    <customValue>
        <fullName>Central</fullName>
    </customValue>
    <customValue>
        <fullName>National</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Latin America</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Region 1</fullName>
    </customValue>
    <customValue>
        <fullName>Region 2</fullName>
    </customValue>
    <customValue>
        <fullName>Region 3</fullName>
    </customValue>
    <customValue>
        <fullName>Northeast</fullName>
    </customValue>
    <customValue>
        <fullName>Southeast</fullName>
    </customValue>
    <customValue>
        <fullName>Midwest</fullName>
    </customValue>
    <customValue>
        <fullName>North</fullName>
    </customValue>
    <customValue>
        <fullName>Europe, Middle East and Africa</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pacific and Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>Americas</fullName>
        <isActive>false</isActive>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>undefined</fullName>
        <isActive>false</isActive>
        <label>undefined</label>
    </customValue>
    <customValue>
        <fullName>Asia</fullName>
        <isActive>false</isActive>
        <label>Asia</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/AccountTriggerHandlerNattTest.cls
@IsTest
private class AccountTriggerHandlerNattTest {
    @IsTest
    static void myUnitTest(){
        List<Account> aList = new List<Account>([SELECT Id, Name FROM Account]);
        delete aList;
    }
    @TestSetup
    static void setupData(){
        Map<String,Schema.RecordTypeInfo> rtMap = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName();
        List<Account> aList = new List<Account>();
        aList.add(new Account(Name='Dealer',NATT_Organization__c = 'NATT',NATT_Region__c = 'East',RecordTypeId=rtMap.get('Dealer').getRecordTypeId()));
        aList.add(new Account(Name='Internal',NATT_Organization__c = 'NATT',NATT_Region__c = 'East',RecordTypeId=rtMap.get('Internal').getRecordTypeId()));
        aList.add(new Account(Name='Customer',NATT_Organization__c = 'NATT',NATT_Region__c = 'East',RecordTypeId=rtMap.get('Customer').getRecordTypeId()));
        insert aList;
        
        update aList;
    }
    @isTest
    public static void testInactiveContactAccess(){
        Map<String,Schema.RecordTypeInfo> rtContactMap = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName();
        Profile testDealerProfile = [SELECT Id FROM Profile WHERE Name='NATT Full Access Community' LIMIT 1]; 
        
        Account testAccount = new Account(Name='Test Dealer Account',NATT_Organization__c = 'NATT',NATT_Region__c = 'East');
        insert testAccount;
        
        Contact testContact = new Contact(FirstName='Test',LastName='Contact',RecordTypeId=rtContactMap.get('NATT_Dealer').getRecordTypeId(),AccountId=testAccount.Id);
        insert testContact;
        
        User thisUser = new User(Id = UserInfo.getUserId());
        System.runAs(thisUser) {
            UserRole testInternalRole = new UserRole(Name='Test Internal Role',DeveloperName='Test_Internal_Role',PortalType='None');
            insert testInternalRole;
            
            thisUser.UserRoleId = testInternalRole.Id;
            update thisUser;
            
            User testDealerUser = new User(Alias='dealer',Email='dealer@example.com',LastName='Dealer',
                                           TimeZoneSidKey='GMT', LocaleSidKey='en_US',Username='dealer@example.com.carrier',
                                           EmailEncodingKey='UTF-8',ProfileId=testDealerProfile.Id,LanguageLocaleKey='en_US',
                                           ContactId=testContact.Id);
            insert testDealerUser;
        }
        
        testContact.RecordTypeId=rtContactMap.get('NATT_Inactive_Contact').getRecordTypeId();
        update testContact;
        
        User testDealerUser = [SELECT Id FROM User WHERE ContactId =: testContact.Id];
        
        // Perform test
        Test.startTest();       
        System.runAs(testDealerUser) {
            Account newTestAccount = new Account(Name='Test Dealer Account2',NATT_Organization__c = 'NATT',NATT_Region__c = 'East');
            try{
                insert newTestAccount;
            } catch (DmlException e){
                //Assert Error Message 
                System.assert(e.getMessage().contains(Label.NATT_Inactive_Contact_Check_Access), e.getMessage());
                //Assert Status Code
                System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION', e.getDmlStatusCode(0));
                System.debug('error' + e.getMessage());
            }
        }
        Test.stopTest(); 
    }
    
    @isTest
    public static void testValidateDelete(){
        Map<String,Schema.RecordTypeInfo> rtContactMap = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName();
        Profile testDealerProfile = [SELECT Id FROM Profile WHERE Name='NATT Full Access Community' LIMIT 1]; 
        
        Account testAccount = new Account(Name='Test Dealer Account',NATT_Status__c='Active',NATT_Organization__c = 'NATT',NATT_Region__c = 'East');
        insert testAccount;
        
        Contact testContact = new Contact(FirstName='Test',LastName='Contact',RecordTypeId=rtContactMap.get('NATT_Dealer').getRecordTypeId(),AccountId=testAccount.Id);
        insert testContact;
        
        User thisUser = new User(Id = UserInfo.getUserId());
        System.runAs(thisUser) {
            UserRole testInternalRole = new UserRole(Name='Test Internal Role',DeveloperName='Test_Internal_Role',PortalType='None');
            insert testInternalRole;
            
            thisUser.UserRoleId = testInternalRole.Id;
            update thisUser;
            
            User testDealerUser = new User(Alias='dealer',Email='dealer@example.com',LastName='Dealer',
                                           TimeZoneSidKey='GMT', LocaleSidKey='en_US',Username='dealer@example.com.carrier',
                                           EmailEncodingKey='UTF-8',ProfileId=testDealerProfile.Id,LanguageLocaleKey='en_US',
                                           ContactId=testContact.Id);
            insert testDealerUser;
        }
        
        update testContact;
        
        User testDealerUser = [SELECT Id FROM User WHERE ContactId =: testContact.Id];
        
        // Perform test
        Map<String,Schema.RecordTypeInfo> rtAccountMap = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName();
        Test.startTest();       
        System.runAs(testDealerUser) {
            Account newTestAccount = new Account(Name='Test Dealer Account2',NATT_Status__c='Active',NATT_Organization__c = 'NATT',NATT_Region__c = 'East');
            insert newTestAccount;
            try{
                delete newTestAccount;
            } catch (DmlException e){
                System.debug('error' + e.getMessage());
            }
        }
        Test.stopTest(); 
    }
}