NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Dealership__c.field-meta.xml
<CustomField>
    <fullName>NATT_Dealership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For End Customer RT&apos;s. This is the dealer the End Customer belongs to.</description>
    <label>Dealership</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer, Direct Sale, CTM Dealer, CTBR Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>NATT End User/End Customer Accounts</description>
    <label>Customer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Accounts</description>
    <label>Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>NATT Internal Customer Accounts</description>
    <label>Internal</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/NATT_Stock__c.field-meta.xml
<CustomField>
    <fullName>NATT_Stock__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT users check this if there is no end customer</description>
    <label>Stock</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/recordTypes/NATT_Opportunity_BluEdge.recordType-meta.xml
<RecordType>
    <fullName>NATT_Opportunity_BluEdge</fullName>
    <active>true</active>
    <businessProcess>NATT Opportunity Units Sales Process</businessProcess>
    <description>For BluEdge Aftermarket and Extension Quotes</description>
    <label>BluEdge</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Opportunity/recordTypes/NATT_Opportunity_eSolutions.recordType-meta.xml
<RecordType>
    <fullName>NATT_Opportunity_eSolutions</fullName>
    <active>true</active>
    <businessProcess>NATT Opportunity Units Sales Process</businessProcess>
    <description>For Lynx Fleet Quotes</description>
    <label>Lynx Fleet</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Opportunity/recordTypes/NATT_Opportunity_Units.recordType-meta.xml
<RecordType>
    <fullName>NATT_Opportunity_Units</fullName>
    <active>true</active>
    <businessProcess>NATT Opportunity Units Sales Process</businessProcess>
    <description>NATT Opportunity Units Recordtype</description>
    <label>Units</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Stock__c.field-meta.xml
<CustomField>
    <fullName>NATT_Stock__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT users check this if there is no end customer</description>
    <label>Stock</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Primary__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox which if checked designates the quote as the Primary Quote</description>
    <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_BluEdgeBundleUniqueKey__c.field-meta.xml
<CustomField>
    <fullName>NATT_BluEdgeBundleUniqueKey__c</fullName>
    <label>BluEdge Bundle Unique Key</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_RequiredByProductName__c.field-meta.xml
<CustomField>
    <fullName>NATT_RequiredByProductName__c</fullName>
    <label>Required By Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__RequiredBy__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RequiredBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this line to another line in the same quote whose product requires this line&apos;s product.</description>
    <inlineHelpText>Indicates which other product on this quote requires it.</inlineHelpText>
    <label>Required By</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/NATT_SBQQTest.cls
@IsTest
private class NATT_SBQQTest {
    
    @IsTest
    static void callbackTest(){
        SBQQ__Quote__c quote = new SBQQ__Quote__c(SBQQ__Status__c='Draft',SBQQ__Account__c=null);
        insert quote;
        
        
        NATT_SBQQCalculateCallback sbqqCC = new NATT_SBQQCalculateCallback();
        try{
        sbqqCC.callback(JSON.serialize(quote));
        }
        catch(Exception e){}
    }
    
    @IsTest
    static void readQuoteTest(){
        SBQQ__Quote__c quote = new SBQQ__Quote__c(SBQQ__Status__c='Draft',SBQQ__Account__c=null);
        insert quote;
        
        NATT_SBQQ.readQuote(quote.Id);
    }
    
    @IsTest
    static void calculateQuoteTest(){
        
        List<Opportunity> opps = [SELECT Id FROM Opportunity Where Name ='UnitsTestOpp'];
        
        Test.startTest();
        
        SBQQ.TriggerControl.disable();
        
        String quoteId = NattQuoteCon.createQuote(opps[0].Id,false);
        
        Pricebook2 pb = [Select Id From Pricebook2 Where Name = 'NATT Units Price Book'];
        
        List<PriceBookEntry> pbes = [Select Id,Product2Id From PriceBookEntry Where PriceBook2Id =:pb.Id];
        
        // insert quote lines
        List<SBQQ__QuoteLine__c> quoteLineList = new List<SBQQ__QuoteLine__c>();
        
        SBQQ__QuoteLine__c quoteLine = TestUtil.createQuoteLine(pbes[0].Product2Id, quoteId);
        quoteLine.SBQQ__PricebookEntryId__c = pBEs[0].Id;
        quoteLine.NATT_BluEdgeBundleUniqueKey__c = 'BluEdge';
        quoteLineList.add(quoteLine);
        
        SBQQ__QuoteLine__c quoteLine2 = TestUtil.createQuoteLine(pbes[1].Product2Id, quoteId);
        quoteLine2.SBQQ__PricebookEntryId__c = pBEs[1].Id;
        quoteLine.NATT_BluEdgeBundleUniqueKey__c = 'BluEdge';
        quoteLineList.add(quoteLine2);
        
        insert quoteLineList;
        
        SBQQ__QuoteLine__c quoteLine3 = TestUtil.createQuoteLine(pbes[2].Product2Id, quoteId);
        quoteLine3.SBQQ__PricebookEntryId__c = pBEs[2].Id;
        quoteLine3.NATT_RequiredByProductName__c = 'BluEdge';
        quoteLine.NATT_BluEdgeBundleUniqueKey__c = 'BluEdge';
        quoteLine3.SBQQ__RequiredBy__c = quoteLineList[0].Id;
        quoteLineList.add(quoteLine3);
        
        SBQQ__QuoteLine__c quoteLine4 = TestUtil.createQuoteLine(pbes[3].Product2Id, quoteId);
        quoteLine4.SBQQ__PricebookEntryId__c = pBEs[3].Id;
        quoteLine4.SBQQ__RequiredBy__c = quoteLineList[1].Id;        
        quoteLine4.NATT_RequiredByProductName__c = 'BluEdge';
        quoteLineList.add(quoteLine4);
        
        SBQQ__QuoteLine__c quoteLine5 = TestUtil.createQuoteLine(pbes[4].Product2Id, quoteId);
        quoteLine5.SBQQ__PricebookEntryId__c = pBEs[2].Id;
        quoteLine5.SBQQ__RequiredBy__c = quoteLineList[0].Id;
        quoteLineList.add(quoteLine5);
        
        SBQQ__QuoteLine__c quoteLine6 = TestUtil.createQuoteLine(pbes[5].Product2Id, quoteId);
        quoteLine6.SBQQ__PricebookEntryId__c = pBEs[3].Id;
        quoteLine6.SBQQ__RequiredBy__c = quoteLineList[1].Id;
        quoteLineList.add(quoteLine6);
        
        upsert quoteLineList;
        
                
        SBQQ__Quote__c quote = new SBQQ__Quote__c(Id=quoteId,SBQQ__Primary__c= true);
        update quote;
        
        NATT_SBQQ.QuoteModel qModel = new NATT_SBQQ.QuoteModel();
        qModel.record = quote;
        
        NATT_SBQQ.calculateQuote(qModel);
        
        
        SBQQ.TriggerControl.enable();
        Test.stopTest();
    }
    
    @TestSetup static void setupData(){
        List<Pricebook2> pbList = new List<Pricebook2>();
        pbList.add(new Pricebook2(Name='NATT Units Price Book',IsActive=true));
        pbList.add(new Pricebook2(Name='NATT Parts Price Book',IsActive=true));
        pbList.add(new Pricebook2(Name='NATT BluEdge',IsActive=true));
        pbList.add(new Pricebook2(Name='NATT Lynx Fleet',IsActive=true));
        insert pbList;
        
        // insert products
        List<Product2> products = new List<Product2>();
        
        Product2 product1 = TestUtil.createProduct('BluEdge (See Options for Price)','BluEdge');
        products.add(product1);
        
        Product2 product2 = TestUtil.createProduct('BluEdge Core','BluEdge Core');
        products.add(product2);
        
        Product2 product3 = TestUtil.createProduct('Extended Basic Coverage','Extended Basic Coverage');
        products.add(product3);
        
        Product2 product4 = TestUtil.createProduct('Extended Basic','APU-T0011');
        products.add(product4);
        
        Product2 product5 = TestUtil.createProduct('OTCC for Extended Basic','APU-T0240');
        products.add(product5);
        
        Product2 product6 = TestUtil.createProduct('Major Component Coverage','Major Component Coverage');
        products.add(product6);
        
        Product2 product7 = TestUtil.createProduct('Engine less accessories','APU-T0020');
        products.add(product7);
        
        Product2 product8 = TestUtil.createProduct('Compressor less accessories','APU-T0030');
        products.add(product8);
        
        insert products;
        
        // get standard price book id
        Id pricebookId = Test.getStandardPricebookId();
        
        // insert price book entries
        List<PriceBookEntry> pBEs = new List<PriceBookEntry>();
        PriceBookEntry pBE1 = TestUtil.createPriceBookEntry(pricebookId, products[0].Id);
        PriceBookEntry pBE2 = TestUtil.createPriceBookEntry(pricebookId, products[1].Id);
        PriceBookEntry pBE3 = TestUtil.createPriceBookEntry(pricebookId, products[2].Id);
        PriceBookEntry pBE4 = TestUtil.createPriceBookEntry(pricebookId, products[3].Id);
        PriceBookEntry pBE5 = TestUtil.createPriceBookEntry(pricebookId, products[4].Id);
        PriceBookEntry pBE6 = TestUtil.createPriceBookEntry(pricebookId, products[5].Id);
        PriceBookEntry pBE7 = TestUtil.createPriceBookEntry(pricebookId, products[6].Id);
        PriceBookEntry pBE8 = TestUtil.createPriceBookEntry(pricebookId, products[7].Id);
        pBEs.add(pBE1);
        pBEs.add(pBE2);
        pBEs.add(pBE3);
        pBEs.add(pBE4);
        pBEs.add(pBE5);
        pBEs.add(pBE6);
        pBEs.add(pBE7);
        pBEs.add(pBE8);
        
        PriceBookEntry pBE9 = TestUtil.createPriceBookEntry(pbList[0].Id, products[0].Id);
        PriceBookEntry pBE10 = TestUtil.createPriceBookEntry(pbList[1].Id, products[0].Id);
        PriceBookEntry pBE11 = TestUtil.createPriceBookEntry(pbList[2].Id, products[0].Id);
        PriceBookEntry pBE12 = TestUtil.createPriceBookEntry(pbList[3].Id, products[0].Id);
        pBEs.add(pBE9);
        pBEs.add(pBE10);
        pBEs.add(pBE11);
        pBEs.add(pBE12);        
        
        PriceBookEntry pBE13 = TestUtil.createPriceBookEntry(pbList[0].Id, products[1].Id);
        PriceBookEntry pBE14 = TestUtil.createPriceBookEntry(pbList[1].Id, products[1].Id);
        PriceBookEntry pBE15 = TestUtil.createPriceBookEntry(pbList[2].Id, products[1].Id);
        PriceBookEntry pBE16 = TestUtil.createPriceBookEntry(pbList[3].Id, products[1].Id);
        pBEs.add(pBE13);
        pBEs.add(pBE14);
        pBEs.add(pBE15);
        pBEs.add(pBE16);
        
        PriceBookEntry pBE17 = TestUtil.createPriceBookEntry(pbList[0].Id, products[2].Id);
        PriceBookEntry pBE18 = TestUtil.createPriceBookEntry(pbList[1].Id, products[2].Id);
        PriceBookEntry pBE19 = TestUtil.createPriceBookEntry(pbList[2].Id, products[2].Id);
        PriceBookEntry pBE20 = TestUtil.createPriceBookEntry(pbList[3].Id, products[2].Id);
        pBEs.add(pBE17);
        pBEs.add(pBE18);
        pBEs.add(pBE19);
        pBEs.add(pBE20);
        
        PriceBookEntry pBE21 = TestUtil.createPriceBookEntry(pbList[0].Id, products[3].Id);
        PriceBookEntry pBE22 = TestUtil.createPriceBookEntry(pbList[1].Id, products[3].Id);
        PriceBookEntry pBE23 = TestUtil.createPriceBookEntry(pbList[2].Id, products[3].Id);
        PriceBookEntry pBE24 = TestUtil.createPriceBookEntry(pbList[3].Id, products[3].Id);
        pBEs.add(pBE21);
        pBEs.add(pBE22);
        pBEs.add(pBE23);
        pBEs.add(pBE24);
        
        PriceBookEntry pBE25 = TestUtil.createPriceBookEntry(pbList[0].Id, products[4].Id);
        PriceBookEntry pBE26 = TestUtil.createPriceBookEntry(pbList[1].Id, products[4].Id);
        PriceBookEntry pBE27 = TestUtil.createPriceBookEntry(pbList[2].Id, products[4].Id);
        PriceBookEntry pBE28 = TestUtil.createPriceBookEntry(pbList[3].Id, products[4].Id);
        pBEs.add(pBE25);
        pBEs.add(pBE26);
        pBEs.add(pBE27);
        pBEs.add(pBE28);
        
        PriceBookEntry pBE29 = TestUtil.createPriceBookEntry(pbList[0].Id, products[5].Id);
        PriceBookEntry pBE30 = TestUtil.createPriceBookEntry(pbList[1].Id, products[5].Id);
        PriceBookEntry pBE31 = TestUtil.createPriceBookEntry(pbList[2].Id, products[5].Id);
        PriceBookEntry pBE32 = TestUtil.createPriceBookEntry(pbList[3].Id, products[5].Id);
        pBEs.add(pBE29);
        pBEs.add(pBE30);
        pBEs.add(pBE31);
        pBEs.add(pBE32);
        
        System.debug('pBEs'+pBEs);
        insert pBEs;
        
        List<Account> aList = new List<Account>();
        alist.add(new Account(Name='Test Dealer',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()));
        aList.add(new Account(Name='Test Internal',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Internal').getRecordTypeId()));
        aList.add(new Account(Name='Customer',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId()));
        
        insert aList;
        
        // assignes dealership to end customer
        aList[2].NATT_Dealership__c = aList.get(0).Id;
        
        update aList[2];
        
        List<AccountTeamMember> atmList = new List<AccountTeamMember>();
        atmList.add(new AccountTeamMember(AccountId=aList.get(0).Id,UserId=UserInfo.getUserId(),TeamMemberRole='EAM - NATT'));
        atmList.add(new AccountTeamMember(AccountId=aList.get(0).Id,UserId=UserInfo.getUserId(),TeamMemberRole='RD - NATT'));
        atmList.add(new AccountTeamMember(AccountId=aList.get(0).Id,UserId=UserInfo.getUserId(),TeamMemberRole='Director of Sales - NATT'));
        insert atmList;
        
        List<Opportunity> oppList = new List<Opportunity>();
        oppList.add(new Opportunity(Name='UnitsTestOpp',CloseDate=Date.today().addDays(30),StageName='Qualification',AccountId=aList.get(0).Id,RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NATT_Opportunity_Units').getRecordTypeId(),NATT_Stock__c=true));
        oppList.add(new Opportunity(Name='UnitsTestOppInternal',CloseDate=Date.today().addDays(30),StageName='Qualification',AccountId=aList.get(1).Id,RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NATT_Opportunity_Units').getRecordTypeId(),NATT_Stock__c=true));
        oppList.add(new Opportunity(Name='BluEdgeTestOpp',CloseDate=Date.today().addDays(30),StageName='Qualification',AccountId=aList.get(0).Id,RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NATT_Opportunity_BluEdge').getRecordTypeId(),NATT_Stock__c=true));
        oppList.add(new Opportunity(Name='eSolutionsOpp',CloseDate=Date.today().addDays(30),StageName='Qualification',AccountId=aList.get(1).Id,RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NATT_Opportunity_eSolutions').getRecordTypeId(),NATT_Stock__c=true));
        insert oppList;
    }

}