NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Division__c.field-meta.xml
<CustomField>
    <fullName>NATT_Division__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Division</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/CONTAINER_Service_Agreement__c/CONTAINER_Service_Agreement__c.object-meta.xml
<CustomObject>
    <description>Custom Container Service Agreement object</description>
    <label>Service Agreement</label>
    <nameField>
        <displayFormat>SA-{00000}</displayFormat>
        <label>Service Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/CONTAINER_Service_Agreement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Account for Container Service Agreement object</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Agreements</relationshipLabel>
    <relationshipName>Service_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/Division.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Truck Trailer</fullName>
        <default>true</default>
        <label>Truck Trailer</label>
    </customValue>
    <customValue>
        <fullName>Container</fullName>
    </customValue>
    <customValue>
        <fullName>Passenger Rail</fullName>
    </customValue>
    <customValue>
        <fullName>Marine</fullName>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/ContentDocumentLinkHelperTest.cls
@IsTest
public class ContentDocumentLinkHelperTest { 
    @IsTest
    public static void Test1() {
        // Create test data for the LinkedEntity
        Account testAcc1 = new Account(
            Name = 'test acc TT',
            NATT_Division__c = 'Truck Trailer'
        );
        CONTAINER_Service_Agreement__c serviceAgreement = new CONTAINER_Service_Agreement__c(account__c =testAcc1.id );
        insert serviceAgreement;
        
        // Create test ContentDocumentLink records
         Blob beforeblob=Blob.valueOf('Unit Test Attachment Body');

        ContentVersion cv = new ContentVersion();
        cv.title = 'test content trigger';      
        cv.PathOnClient ='test';           
        cv.VersionData =beforeblob;          
        insert cv;         

        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];

        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=serviceAgreement.id;
        contentlink.ShareType= 'I';
        contentlink.Visibility = 'InternalUsers';
        contentlink.ContentDocumentId=testcontent.ContentDocumentId;

        insert contentlink;
        
        list<ContentDocumentLink> cdlList = new list<ContentDocumentLink>();
        cdlList.add(contentlink);
       Test.startTest();
        ContentDocumentLinkHelper.updateVisiblePermission(cdlList);
        Test.stopTest();
    }
}