NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_JDE_Unit_Bill_To_Code__c.field-meta.xml
<CustomField>
    <fullName>NATT_JDE_Unit_Bill_To_Code__c</fullName>
    <description>NATT</description>
    <externalId>true</externalId>
    <label>JDE Unit Bill To Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <description>NATT</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Backlog_Item__c/NATT_Backlog_Item__c.object-meta.xml
<CustomObject>
    <label>Backlog Item</label>
    <nameField>
        <label>Backlog Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_Backlog_Item__c/fields/NATT_Account__c.field-meta.xml
<CustomField>
    <fullName>NATT_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Backlog Items</relationshipLabel>
    <relationshipName>Backlog_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Backlog_Item__c/fields/NATT_Bill_To_Address__c.field-meta.xml
<CustomField>
    <fullName>NATT_Bill_To_Address__c</fullName>
    <label>Bill To Address</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Backlog_Item__c/fields/NATT_Bill_To_Name__c.field-meta.xml
<CustomField>
    <fullName>NATT_Bill_To_Name__c</fullName>
    <label>Bill To Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Backlog_Item__c/fields/NATT_BklgQty__c.field-meta.xml
<CustomField>
    <fullName>NATT_BklgQty__c</fullName>
    <label>BklgQty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Backlog_Item__c/fields/NATT_Customer_PO__c.field-meta.xml
<CustomField>
    <fullName>NATT_Customer_PO__c</fullName>
    <label>Customer P.O.</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Backlog_Item__c/fields/NATT_End_User__c.field-meta.xml
<CustomField>
    <fullName>NATT_End_User__c</fullName>
    <label>End User</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Backlog_Item__c/fields/NATT_Freight_Code__c.field-meta.xml
<CustomField>
    <fullName>NATT_Freight_Code__c</fullName>
    <label>Freight Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PPA</fullName>
            </value>
            <value>
                <fullName>COL</fullName>
            </value>
            <value>
                <fullName>PPB</fullName>
            </value>
            <value>
                <fullName>EXW</fullName>
            </value>
            <value>
                <fullName>PP</fullName>
            </value>
            <value>
                <fullName>CPU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Backlog_Item__c/fields/NATT_JDE_AR_Code__c.field-meta.xml
<CustomField>
    <fullName>NATT_JDE_AR_Code__c</fullName>
    <label>JDE AR Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Backlog_Item__c/fields/NATT_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>NATT_Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CB</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Backlog_Item__c/fields/NATT_Prod_Description__c.field-meta.xml
<CustomField>
    <fullName>NATT_Prod_Description__c</fullName>
    <label>Prod Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Backlog_Item__c/fields/NATT_Prod_No__c.field-meta.xml
<CustomField>
    <fullName>NATT_Prod_No__c</fullName>
    <label>Prod No</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Backlog_Item__c/fields/NATT_Product_Family__c.field-meta.xml
<CustomField>
    <fullName>NATT_Product_Family__c</fullName>
    <label>Prod Family</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Backlog_Item__c/fields/NATT_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>NATT_Product_Line__c</fullName>
    <label>Prod Line</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Backlog_Item__c/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Backlog_Item__c/fields/NATT_Req_Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>NATT_Req_Ship_Date__c</fullName>
    <label>Req Ship Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Backlog_Item__c/fields/NATT_Sch_Pick_Date__c.field-meta.xml
<CustomField>
    <fullName>NATT_Sch_Pick_Date__c</fullName>
    <label>Sch Pick Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Backlog_Item__c/fields/NATT_Ship_To_City__c.field-meta.xml
<CustomField>
    <fullName>NATT_Ship_To_City__c</fullName>
    <label>Ship To City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Backlog_Item__c/fields/NATT_Ship_To_State__c.field-meta.xml
<CustomField>
    <fullName>NATT_Ship_To_State__c</fullName>
    <label>Ship To State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_State_Picklist</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Backlog_Item__c/fields/NATT_SO_Cat__c.field-meta.xml
<CustomField>
    <fullName>NATT_SO_Cat__c</fullName>
    <label>SO Cat.</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DDO</fullName>
            </value>
            <value>
                <fullName>DFO</fullName>
            </value>
            <value>
                <fullName>DGO</fullName>
            </value>
            <value>
                <fullName>DLO</fullName>
            </value>
            <value>
                <fullName>DSO</fullName>
            </value>
            <value>
                <fullName>HDO</fullName>
            </value>
            <value>
                <fullName>HFO</fullName>
            </value>
            <value>
                <fullName>HGO</fullName>
            </value>
            <value>
                <fullName>HIO</fullName>
            </value>
            <value>
                <fullName>HLO</fullName>
            </value>
            <value>
                <fullName>HSO</fullName>
            </value>
            <value>
                <fullName>INT</fullName>
            </value>
            <value>
                <fullName>TBO</fullName>
            </value>
            <value>
                <fullName>TDO</fullName>
            </value>
            <value>
                <fullName>TFO</fullName>
            </value>
            <value>
                <fullName>TGO</fullName>
            </value>
            <value>
                <fullName>TIO</fullName>
            </value>
            <value>
                <fullName>TLO</fullName>
            </value>
            <value>
                <fullName>TSO</fullName>
            </value>
            <value>
                <fullName>AFO</fullName>
            </value>
            <value>
                <fullName>ALO</fullName>
            </value>
            <value>
                <fullName>ADO</fullName>
            </value>
            <value>
                <fullName>ASO</fullName>
            </value>
            <value>
                <fullName>ADY</fullName>
            </value>
            <value>
                <fullName>VLO</fullName>
            </value>
            <value>
                <fullName>VSO</fullName>
            </value>
            <value>
                <fullName>VDO</fullName>
            </value>
            <value>
                <fullName>VGO</fullName>
            </value>
            <value>
                <fullName>VFO</fullName>
            </value>
            <value>
                <fullName>HBO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Backlog_Item__c/fields/NATT_SOLine__c.field-meta.xml
<CustomField>
    <fullName>NATT_SOLine__c</fullName>
    <label>SOLine</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>East</fullName>
    </customValue>
    <customValue>
        <fullName>West</fullName>
    </customValue>
    <customValue>
        <fullName>South</fullName>
    </customValue>
    <customValue>
        <fullName>Central</fullName>
    </customValue>
    <customValue>
        <fullName>National</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Latin America</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Region 1</fullName>
    </customValue>
    <customValue>
        <fullName>Region 2</fullName>
    </customValue>
    <customValue>
        <fullName>Region 3</fullName>
    </customValue>
    <customValue>
        <fullName>Northeast</fullName>
    </customValue>
    <customValue>
        <fullName>Southeast</fullName>
    </customValue>
    <customValue>
        <fullName>Midwest</fullName>
    </customValue>
    <customValue>
        <fullName>North</fullName>
    </customValue>
    <customValue>
        <fullName>Europe, Middle East and Africa</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pacific and Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>Americas</fullName>
        <isActive>false</isActive>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>undefined</fullName>
        <isActive>false</isActive>
        <label>undefined</label>
    </customValue>
    <customValue>
        <fullName>Asia</fullName>
        <isActive>false</isActive>
        <label>Asia</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/CSVFileReadLWCCntrl.cls
public class CSVFileReadLWCCntrl {
    @AuraEnabled
    public static void csvFileRead(Id contentDocumentId){
        list<NATT_Backlog_Item__c> backlogInsertList = new list<NATT_Backlog_Item__c>();
        list<NATT_Backlog_Item__c> backlogUpdateList = new list<NATT_Backlog_Item__c>();
        
        if(contentDocumentId != null) {
            System.debug('Inside the apex');
            // Fetch File Data based on the basic of document id 
            ContentVersion contentVersionObj = [SELECT Id, VersionData FROM ContentVersion WHERE ContentDocumentId =:contentDocumentId ];
            System.debug('VersionData--> '+contentVersionObj.VersionData);
            // split the file data
            System.debug('File Data Review:::'+contentVersionObj.VersionData.toString());
            //System.debug(EncodingUtil.base64Decode(contentVersionObj.VersionData.toString()));
            //list<String> csvRecordsList = contentVersionObj.VersionData.toString().split('\n');
            
            String csvRecords = contentVersionObj.VersionData.toString();
            CSVFileParser csvparser = new CSVFileParser();
            List<String> csvRecordsList = csvParser.safeSplit(csvRecords, '\n');
            System.debug('csvRecordsList.size::'+csvRecordsList.size());
            System.debug('csvRecordsList----> '+csvRecordsList);
            
            for(Integer i = 1; i < csvRecordsList.size(); i++){
                list<String> csvRowData = csvRecordsList[i].split(',');
                
                if(csvRowData[0] != ''){
                    NATT_Backlog_Item__c backlogObj = new NATT_Backlog_Item__c();               
                    System.debug('csvRowData----> '+csvRowData);
                    backlogObj.NATT_Prod_No__c = csvRowData[0];
                    backlogObj.NATT_Prod_Description__c = csvRowData[1];
                    System.debug(backlogObj.NATT_Prod_Description__c);
                    backlogObj.NATT_Bill_To_Address__c = csvRowData[2];
                    System.debug('tttt::'+backlogObj.NATT_Bill_To_Address__c);
                    backlogObj.NATT_JDE_AR_Code__c = csvRowData[2];
                    backlogObj.NATT_Bill_To_Name__c = csvRowData[3];
                    backlogObj.NATT_End_User__c = csvRowData[4];
                    backlogObj.NATT_Customer_PO__c = csvRowData[5];
                    backlogObj.NATT_Region__c = csvRowData[6];
                    backlogObj.NATT_SOLine__c = csvRowData[7];
                    backlogObj.NATT_Order_Type__c = csvRowData[8];
                    backlogObj.NATT_Sch_Pick_Date__c = Date.parse(csvRowData[9]);
                    backlogObj.NATT_BklgQty__c = Decimal.valueOf(csvRowData[10]);
                    backlogObj.NATT_Req_Ship_Date__c = Date.parse(csvRowData[11]);
                    //backlogObj.NATT_Freight_Code__c = csvRowData[13];
                    backlogObj.NATT_Ship_To_City__c = csvRowData[14];
                    backlogObj.NATT_Ship_To_State__c = csvRowData[15];
                    //backlogObj.NATT_SO_Cat__c = csvRowData[16];
                    backlogObj.NATT_Product_Family__c = csvRowData[17];
                    backlogObj.NATT_Product_Line__c = csvRowData[18];
                    
                    backlogInsertList.add(backlogObj);
                    
                }

                    
             }
                            
        }
        
            try{    
                System.debug('Before insert');
                if(!backlogInsertList.isEmpty()) {
                    insert backlogInsertList;
                    System.debug('InsertSizeList-->' + backlogInsertList.size());
                    System.debug('After Insert insert');
                    System.debug('Before Backlog Item Update'); 
                }
                String prevBillToAdress ='';
                Map<String, User> newMap = new Map<String, User>{};
                    List<User> UserList = new List<User>();
                UserList = [Select Id, Name, Alias, ProfileId,AccountId, isActive,Account.NATT_JDE_Unit_Bill_To_Code__c from User where Profile.Name = 'NATT Sales Only Community' and Account.NATT_JDE_Unit_Bill_To_Code__c != null];
                for (User usr: UserList){
                    String billToAddress = usr.Account.NATT_JDE_Unit_Bill_To_Code__c;
                    if(prevBillToAdress != usr.Account.NATT_JDE_Unit_Bill_To_Code__c){
                        newMap.put(usr.Account.NATT_JDE_Unit_Bill_To_Code__c, usr);
                        prevBillToAdress = usr.Account.NATT_JDE_Unit_Bill_To_Code__c;
                    }
                    
                }
                System.debug('MAPSIZE--> ' + newMap.size());
                //System.debug('MAP--> ' + newMap);
                
                for(NATT_Backlog_Item__c backlogItem : backlogInsertList){
                    System.debug('BacklogItem Id--> '+backlogItem.Id);
                    User newusr = newMap.get(backlogItem.NATT_Bill_To_Address__c);
                    System.debug('User Details--> '+ newusr);
                    if(newusr != null){
                        if(newusr.isActive = true && newusr.AccountId != null){
                            System.debug('AccountId--> '+ newusr.AccountId);
                            backlogItem.NATT_Account__c = newusr.AccountId;
                            System.debug('OwnerId--> '+ newusr.Name);
                            backlogItem.OwnerId = newusr.Id;
                        }
                        if(newusr.IsActive && newusr.AccountId == null){
                            System.debug('OwnerId--> '+ newusr.Name);
                            backlogItem.OwnerId = newusr.Id;
                            System.debug('Account Id--> '+ newusr.AccountId);
                            continue;
                        }
                        if(!newusr.IsActive && newusr.AccountId != NULL){
                            System.debug('AccountId--> '+ newusr.AccountId);
                            backlogItem.NATT_Account__c = newusr.AccountId;
                            System.debug('OwnerId--> '+ UserInfo.getUserId());
                            continue;
                        }
                    }
                    backlogUpdateList.add(backlogItem);
                    
                }
                System.debug('UpdatedListSize-->' + backlogUpdateList.size());
                update backlogUpdateList;
                System.debug('After Backlog Item Update');
                
            }
            catch (Exception ex) {
                throw new AuraHandledException(ex.getMessage());
            } 
  
    }
}