NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Division__c.field-meta.xml
<CustomField>
    <fullName>NATT_Division__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Division</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Organization__c.field-meta.xml
<CustomField>
    <fullName>NATT_Organization__c</fullName>
    <description>NATT</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Geography</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <description>NATT</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>NATT End User/End Customer Accounts</description>
    <label>Customer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Contact/fields/NAC_Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>NAC_Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parts Ordering</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Parts</fullName>
                <isActive>false</isActive>
                <label>Parts</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Contact/fields/NATT_Account_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>NATT_Account_Contact_Role__c</fullName>
    <label>Account Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>President</fullName>
            </value>
            <value>
                <fullName>Vice-President</fullName>
            </value>
            <value>
                <fullName>General Manager</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Billing Admin</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Service Manager</fullName>
            </value>
            <value>
                <fullName>Parts Manager</fullName>
            </value>
            <value>
                <fullName>Warranty Manager</fullName>
            </value>
            <value>
                <fullName>Gerente de Compras</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Purchasing Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Contact/recordTypes/NAOCAP_End_Customer.recordType-meta.xml
<RecordType>
    <fullName>NAOCAP_End_Customer</fullName>
    <active>true</active>
    <description>NAOCAP Customer Contacts</description>
    <label>NAOCAP End Customer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/NATT_AlternativeItem__c/NATT_AlternativeItem__c.object-meta.xml
<CustomObject>
    <description>Custom object for storing alternative item entries (e.g. items that supersede other catalog items)</description>
    <label>NATT Alternative Item</label>
    <nameField>
        <displayFormat>NAI-{00000000}</displayFormat>
        <label>NATT Alternative Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NATT Alternative Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_AlternativeItem__c/fields/NATT_AlternativeItem__c.field-meta.xml
<CustomField>
    <fullName>NATT_AlternativeItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Item that is being provided as an alternative to the Product Item</description>
    <inlineHelpText>Item that is being provided as an alternative to the Product Item</inlineHelpText>
    <label>Alternative Item</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>NATT Alternative Items (Alternative Item)</relationshipLabel>
    <relationshipName>NATT_Alternative_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_AlternativeItem__c/fields/NATT_EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_EffectiveDate__c</fullName>
    <description>Date the alternative item effectively supersedes the product item</description>
    <inlineHelpText>Date the alternative item effectively supersedes the product item</inlineHelpText>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_AlternativeItem__c/fields/NATT_ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_ExpiryDate__c</fullName>
    <description>Date the alternative item expires</description>
    <inlineHelpText>Date the alternative item expires</inlineHelpText>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_AlternativeItem__c/fields/NATT_ProductItem__c.field-meta.xml
<CustomField>
    <fullName>NATT_ProductItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Item that is being superseded by the item shown in the Alternative Item field</description>
    <inlineHelpText>Item that is being superseded by the item shown in the Alternative Item field</inlineHelpText>
    <label>Product Item</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>NATT Alternative Items</relationshipLabel>
    <relationshipName>NATT_Alternative_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/NATT_ItemPriceStaging__c.object-meta.xml
<CustomObject>
    <description>Staging object for imported PartsNet item pricing from JDE (RCGWEB23 &amp; RCGWEB26). Includes standard list prices, customer-specific item prices, and quantity price tiers</description>
    <label>NATT Item Price Staging</label>
    <nameField>
        <displayFormat>IPS-{0000000000}</displayFormat>
        <label>NATT Item Price Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NATT Item Price Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_CustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>NATT_CustomerNumber__c</fullName>
    <description>Customer number this adjustment record applies to. If NULL the record is not customer specifc</description>
    <label>Customer Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_EffectiveDate__c</fullName>
    <description>Date this price becomes effective</description>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_ExpiryDate__c</fullName>
    <description>Date this price expires and no longer applies</description>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_ItemPriceGroup__c.field-meta.xml
<CustomField>
    <fullName>NATT_ItemPriceGroup__c</fullName>
    <description>Identifies the sales price group number of the item</description>
    <label>Item Price Group</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_Product__c.field-meta.xml
<CustomField>
    <fullName>NATT_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>NATT Item Price Staging</relationshipLabel>
    <relationshipName>NATT_Item_Price_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_QuantityFrom__c.field-meta.xml
<CustomField>
    <fullName>NATT_QuantityFrom__c</fullName>
    <description>Specifies the quantity at which this price applies.</description>
    <label>Quantity From</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/recordTypes/NAOCAP.recordType-meta.xml
<RecordType>
    <fullName>NAOCAP</fullName>
    <active>true</active>
    <label>NAOCAP</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/NATT_ProductInventoryItem__c.object-meta.xml
<CustomObject>
    <description>Contains current inventory levels at each warehouse for all B2B Commerce product items.</description>
    <label>Product Inventory Item</label>
    <nameField>
        <displayFormat>INV-{000000000}</displayFormat>
        <label>Product Inventory Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/fields/NATT_AvailableQuantity__c.field-meta.xml
<CustomField>
    <fullName>NATT_AvailableQuantity__c</fullName>
    <description>Currently available quantity of the product item at the specified warehouse. Expected whole number values.</description>
    <label>Available Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/fields/NATT_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_P_N__c</fullName>
    <formula>NATT_ProductItem__r.NATT_P_N__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>P/N</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/fields/NATT_ProductItem__c.field-meta.xml
<CustomField>
    <fullName>NATT_ProductItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product item to which the available quantity applies</description>
    <label>Product Item</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Inventory Items</relationshipLabel>
    <relationshipName>Product_Inventory_Items_del</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ProductInventoryItem__c/fields/NATT_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>NATT_Warehouse__c</fullName>
    <description>Warehouse containing the available quantity of the product item</description>
    <label>Warehouse</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ANA</fullName>
            </value>
            <value>
                <fullName>BNA</fullName>
            </value>
            <value>
                <fullName>CHI</fullName>
            </value>
            <value>
                <fullName>PAN</fullName>
            </value>
            <value>
                <fullName>TES</fullName>
            </value>
            <value>
                <fullName>ATL</fullName>
            </value>
            <value>
                <fullName>MEX</fullName>
            </value>
            <value>
                <fullName>MIA</fullName>
            </value>
            <value>
                <fullName>CTB01</fullName>
            </value>
            <value>
                <fullName>CTB02</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_ItemPriceGroup__c.field-meta.xml
<CustomField>
    <fullName>NATT_ItemPriceGroup__c</fullName>
    <description>A number identifying the price group to which the item belongs</description>
    <label>Item Price Group</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_P_N__c</fullName>
    <description>The Part Number for NATT JDE</description>
    <label>Part Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_SignalCode__c.field-meta.xml
<CustomField>
    <fullName>NATT_SignalCode__c</fullName>
    <description>JDE Signal Code for the item</description>
    <label>Signal Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>NLO</fullName>
            </value>
            <value>
                <fullName>NSI</fullName>
            </value>
            <value>
                <fullName>NSU</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S1D</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
            <value>
                <fullName>NRC</fullName>
            </value>
            <value>
                <fullName>BY2</fullName>
                <label>BUYER HOLD</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <label>NOT AVAILABLE</label>
            </value>
            <value>
                <fullName>OB1</fullName>
            </value>
            <value>
                <fullName>OBS</fullName>
            </value>
            <value>
                <fullName>PRC</fullName>
            </value>
            <value>
                <fullName>NEW</fullName>
            </value>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>PSR</fullName>
            </value>
            <value>
                <fullName>VIN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Weight__c.field-meta.xml
<CustomField>
    <fullName>NATT_Weight__c</fullName>
    <description>Item weight in US pounds</description>
    <label>Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/Division.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Truck Trailer</fullName>
        <default>true</default>
        <label>Truck Trailer</label>
    </customValue>
    <customValue>
        <fullName>Container</fullName>
    </customValue>
    <customValue>
        <fullName>Passenger Rail</fullName>
    </customValue>
    <customValue>
        <fullName>Marine</fullName>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/Geography.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NATT</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>CTB</fullName>
    </customValue>
    <customValue>
        <fullName>Need the others listed</fullName>
        <isActive>false</isActive>
        <label>Need the others listed</label>
    </customValue>
    <masterLabel>Geography</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>East</fullName>
    </customValue>
    <customValue>
        <fullName>West</fullName>
    </customValue>
    <customValue>
        <fullName>South</fullName>
    </customValue>
    <customValue>
        <fullName>Central</fullName>
    </customValue>
    <customValue>
        <fullName>National</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Latin America</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Region 1</fullName>
    </customValue>
    <customValue>
        <fullName>Region 2</fullName>
    </customValue>
    <customValue>
        <fullName>Region 3</fullName>
    </customValue>
    <customValue>
        <fullName>Northeast</fullName>
    </customValue>
    <customValue>
        <fullName>Southeast</fullName>
    </customValue>
    <customValue>
        <fullName>Midwest</fullName>
    </customValue>
    <customValue>
        <fullName>North</fullName>
    </customValue>
    <customValue>
        <fullName>Europe, Middle East and Africa</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pacific and Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>Americas</fullName>
        <isActive>false</isActive>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>undefined</fullName>
        <isActive>false</isActive>
        <label>undefined</label>
    </customValue>
    <customValue>
        <fullName>Asia</fullName>
        <isActive>false</isActive>
        <label>Asia</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/NACon_PriceAvailabilityControllerTest.cls
@isTest
public class NACon_PriceAvailabilityControllerTest {

  private static String email = 'newuser@testorg.com';
  private static String email2 = 'newuser@testorg2.com';
    
    

  @testSetup
  private static void testSetup() {
      
    Id conRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('NAOCAP_End_Customer').getRecordTypeId();
    Id itempriceRecordTypeId = Schema.SObjectType.NATT_ItemPriceStaging__c.getRecordTypeInfosByDeveloperName().get('NAOCAP').getRecordTypeId();
      
    Pricebook2 standardPB = new Pricebook2(Name = 'Standard Price Book',IsActive = true );
    insert standardPB;
    standardPB.Id = Test.getStandardPricebookId();
     update standardPB;

    Pricebook2 testPB = new Pricebook2(Name = 'test pricebook',isActive = true);
    insert testPB;

    Product2 testProductNEW = new Product2(
      Name = 'Product Test NEW',
      NATT_P_N__c = 'PNtest123NEW',
      NATT_Weight__c = 10,
      Description = 'desc test',
      QuantityUnitOfMeasure = 'EA',
      StockKeepingUnit = 'skre',
      NATT_ItemPriceGroup__c = '111',
      NATT_SignalCode__c='S2'
    );

    insert testProductNEW;

    Product2 testProductOLD = new Product2(
      Name = 'Product Test OLD',
      NATT_P_N__c = 'PNtest123OLD',
      NATT_Weight__c = 10,
      Description = 'desc test',
      QuantityUnitOfMeasure = 'EA',
      StockKeepingUnit = 'OLDskre',
      NATT_ItemPriceGroup__c = '111',
      NATT_SignalCode__c='S2'
    );

    insert testProductOLD;

    Product2 testProductNeverReplaced = new Product2(
      Name = 'Product Test',
      NATT_P_N__c = 'PNtest123NOR',
      NATT_Weight__c = 10,
      Description = 'desc test',
      QuantityUnitOfMeasure = 'EA',
      StockKeepingUnit = 'NONREPLACEDSKU',
      NATT_ItemPriceGroup__c = '111'
    );

    insert testProductNeverReplaced;

    PriceBookEntry testPBE_NEW_s = new PriceBookEntry(
      Pricebook2Id = standardPB.Id,
      Product2Id = testProductNEW.Id,
      UnitPrice = 696,
      isActive = true
    );

    insert testPBE_NEW_s;

    PriceBookEntry testPBE_NEW = new PriceBookEntry(
      Pricebook2Id = testPB.Id,
      Product2Id = testProductNEW.Id,
      UnitPrice = 696,
      isActive = true,
      UseStandardPrice = true
    );

    insert testPBE_NEW;

    PriceBookEntry testPBE_OLD_s = new PriceBookEntry(
      Pricebook2Id = standardPB.Id,
      Product2Id = testProductOLD.Id,
      UnitPrice = 696,
      isActive = true
    );

    insert testPBE_OLD_s;

    PriceBookEntry testPBE_OLD = new PriceBookEntry(
      Pricebook2Id = testPB.Id,
      Product2Id = testProductOLD.Id,
      UnitPrice = 696,
      isActive = true,
      UseStandardPrice = true
    );

    insert testPBE_OLD;

    NATT_ProductInventoryItem__c availNEW = new NATT_ProductInventoryItem__c(
      NATT_ProductItem__c = testProductNEW.Id,
      NATT_AvailableQuantity__c = 69,
      NATT_Warehouse__c = 'ATL'
    );

    insert availNEW;

    NATT_ProductInventoryItem__c availOLD = new NATT_ProductInventoryItem__c(
      NATT_ProductItem__c = testProductOLD.Id,
      NATT_AvailableQuantity__c = 96,
      NATT_Warehouse__c = 'ATL'
    );

    insert availOLD;

    NATT_AlternativeItem__c hist = new NATT_AlternativeItem__c(
      NATT_AlternativeItem__c = testProductOLD.Id,
      NATT_ProductItem__c = testProductNEW.Id,
      NATT_EffectiveDate__c = date.parse('07/29/2021')
    );

    insert hist;
      
  // NATT_ItemPriceStaging__c  itempricing=new NATT_ItemPriceStaging__c(NATT_QuantityFrom__c=1000,NATT_EffectiveDate__c= date.parse('07/29/2021'),NATT_ExpiryDate__c= date.parse('08/29/2023'),NATT_CustomerNumber__c=0, NATT_Product__c=testProductNeverReplaced.Id,RecordTypeId=itempriceRecordTypeId);
   // insert itempricing;
    String username = email + Datetime.now().getTime();

    Account testAcc1 = new Account(
      Name = 'test acc TT' ,NATT_Organization__c = 'NATT',NATT_Region__c = 'East'
     //	 NATT_Division__c = 'Truck Trailer'
    );

    insert testAcc1;

  /*  Contact testContact = new Contact(
      LastName = 'test c TT',
      NATT_Account_Contact_Role__c = 'President',
      AccountId = testAcc1.Id
    ); */
      
   Contact testContact = new Contact(LastName='TestContactTestCon',RecordTypeId=conRecordTypeId ,NAC_Contact_Type__c='Parts Ordering', NATT_Key_Business_Role__c='Co-Principal',	
   Email='test@gmail.com', Phone='3456237654',  AccountId= testAcc1.Id);

    insert testContact;

    Account testAcc2 = new Account(
      Name = 'test acc C',
      NATT_Division__c = 'Container',NATT_Organization__c = 'NATT',NATT_Region__c = 'East'      
    );

    insert testAcc2;

   /* Contact testContact2 = new Contact(
      LastName = 'test c C',
      NATT_Account_Contact_Role__c = 'President',
      AccountId = testAcc2.Id
    ); */
      
       Contact testContact2 = new Contact(LastName='TestContactTestCon',RecordTypeId=conRecordTypeId ,NAC_Contact_Type__c='Parts Ordering', NATT_Key_Business_Role__c='Co-Principal',	
      Email='test@gmail.com', Phone='3456237654',  AccountId= testAcc2.Id);

    insert testContact2;

    Profile p = [
      SELECT Id
      FROM Profile
      WHERE Name = 'NAC Customer Community Profile'
    ];

    User testUser = new User(
      Contact = testContact,
      ContactId = testContact.Id,
      Alias = 'newUser',
      Email = email,
      EmailEncodingKey = 'UTF-8',
      LastName = 'Testing',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      ProfileId = p.Id,
      TimeZoneSidKey = 'America/Los_Angeles',
      //TimeZoneSidKey=String.valueOf(UserInfo.getTimeZone()),
      UserName = username
    );

    insert testUser;

    User testUser2 = new User(
      Contact = testContact2,
      ContactId = testContact2.Id,
      Alias = 'newUser',
      Email = email2,
      EmailEncodingKey = 'UTF-8',
      LastName = 'Testing',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      ProfileId = p.Id,
      TimeZoneSidKey = 'America/Los_Angeles',
      //TimeZoneSidKey=String.valueOf(UserInfo.getTimeZone()),
      UserName = username + '2'
    );

    insert testUser2;
  }

  @isTest
  private static void getAvailable_test() {
    Test.startTest();

    NATT_ProductInventoryItem__c testqtt = [
      SELECT
        Id,
        NATT_Warehouse__c,
        NATT_ProductItem__c,
        NATT_AvailableQuantity__c
      FROM NATT_ProductInventoryItem__c
      WHERE NATT_AvailableQuantity__c = 69
    ];
    Id accountId =[SELECT Id  FROM Account WHERE Name='test acc C'].Id;
   // NATT_ItemPriceStaging__c  itempricing=[Select NATT_QuantityFrom__c,NATT_EffectiveDate__c,NATT_ExpiryDate__c,NATT_CustomerNumber__c, NATT_Product__c FROM NATT_ItemPriceStaging__c where NATT_QuantityFrom__c=1000];
    
      
      
    NATT_ProductInventoryItem__c result = NACon_PriceAvailabilityController.getAvailable( testqtt.NATT_ProductItem__c,false, accountId);
     
   

    System.assert(result.NATT_AvailableQuantity__c == 69);
    NACon_PriceAvailabilityController.getQuantityBreakListPrices();
  //  NACon_PriceAvailWoSharing.getQuantityBreakListPrices();
    Test.stopTest();
  }

  @isTest
  private static void getHistory_testProductItem() {
    NATT_AlternativeItem__c alternativeItem = [
      SELECT Id, NATT_AlternativeItem__c, NATT_ProductItem__c
      FROM NATT_AlternativeItem__c
      LIMIT 1
    ];

    Test.startTest();
    List<Product2> history = NACon_PriceAvailabilityController.getHistory(
      alternativeItem.NATT_ProductItem__c
    );
    Test.stopTest();

    System.assertEquals(3, history.size());
    System.assertEquals(alternativeItem.NATT_AlternativeItem__c, history[0].Id);
  }

  @isTest
  private static void getHistory_testAlternativeItem() {
    NATT_AlternativeItem__c alternativeItem = [
      SELECT Id, NATT_AlternativeItem__c, NATT_ProductItem__c
      FROM NATT_AlternativeItem__c
      LIMIT 1
    ];

    Test.startTest();
    List<Product2> history = NACon_PriceAvailabilityController.getHistory(
      alternativeItem.NATT_AlternativeItem__c
    );
    Test.stopTest();

    System.assertEquals(2, history.size());
    System.assertEquals(alternativeItem.NATT_AlternativeItem__c, history[0].Id);
  }

  @isTest
  private static void getHistory_testNoHistory() {
    Product2 product = [
      SELECT Id
      FROM Product2
      WHERE Name = 'Product Test'
      LIMIT 1
    ];

    Test.startTest();
    List<Product2> history = NACon_PriceAvailabilityController.getHistory(
      product.Id
    );
    Test.stopTest();

    System.assertEquals(3, history.size());
    System.assertEquals(product.Id, history[0].Id);
  } 
    
    @isTest
    public static void getQuantityBreakListPricesException(){
         NACon_PriceAvailWoSharing.throwException = true;
        
         try{
             
        List<NATT_ItemPriceStaging__c>  itemlist=  NACon_PriceAvailWoSharing.getQuantityBreakListPrices();
          //  System.assert(false, 'Expected a thrown exception.');
        }catch(AuraHandledException e){
            system.assert(true);
            System.debug(e.getMessage());

        }
        
     
}
    
}