NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>NATT_Billing_Address__c</fullName>
    <formula>IF(NATT_Address_Billing__r.NATT_Street__c &lt;&gt; &quot;&quot;,NATT_Address_Billing__r.NATT_Street__c + BR(),NULL) +
IF(NATT_Address_Billing__r.NATT_City__c &lt;&gt; &quot;&quot;,NATT_Address_Billing__r.NATT_City__c + &quot;, &quot;,NULL) +
TEXT(NATT_Address_Billing__r.NATT_State_Province__c) + &quot; &quot; + NATT_Address_Billing__r.NATT_Zip_Postal_Code__c + BR() +
TEXT(NATT_Address_Billing__r.NATT_Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing Address</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/CTBR_Dealer.recordType-meta.xml
<RecordType>
    <fullName>CTBR_Dealer</fullName>
    <active>true</active>
    <label>CTBR Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>NATT End User/End Customer Accounts</description>
    <label>Customer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Accounts</description>
    <label>Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/NATT_Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>NATT Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_Account__c.field-meta.xml
<CustomField>
    <fullName>NATT_Account__c</fullName>
    <description>NATT</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>NATT_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_Type__c.field-meta.xml
<CustomField>
    <fullName>NATT_Type__c</fullName>
    <description>NATT</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Dealer Agreement</fullName>
            </value>
            <value>
                <fullName>Distribution Centers</fullName>
            </value>
            <value>
                <fullName>Headquarters</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Other Mailing</fullName>
            </value>
            <value>
                <fullName>Parts Ship To</fullName>
            </value>
            <value>
                <fullName>Physical</fullName>
            </value>
            <value>
                <fullName>Regional Offices</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Units Ship To</fullName>
            </value>
            <value>
                <fullName>Bill To</fullName>
            </value>
            <value>
                <fullName>Ship To</fullName>
            </value>
            <value>
                <fullName>TES Ship To</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/recordTypes/NATT_Address.recordType-meta.xml
<RecordType>
    <fullName>NATT_Address</fullName>
    <active>true</active>
    <description>NATT</description>
    <label>NATT Address</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>NATT_Billing_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NATT Billing Address</label>
    <referenceTo>NATT_Address__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>NATT_Order_Status__c</fullName>
    <description>NATT</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enter Order (Default Value)</fullName>
            </value>
            <value>
                <fullName>Sabrix Run</fullName>
            </value>
            <value>
                <fullName>Fulfillment Run</fullName>
            </value>
            <value>
                <fullName>Order Acknowledge</fullName>
            </value>
            <value>
                <fullName>Release Order for Shipment</fullName>
            </value>
            <value>
                <fullName>Credit Check for Shipment</fullName>
            </value>
            <value>
                <fullName>Ready to Print Pick Slip</fullName>
            </value>
            <value>
                <fullName>Ready for Picking</fullName>
            </value>
            <value>
                <fullName>Ready for Shipping</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Sabrix</fullName>
            </value>
            <value>
                <fullName>Invoicing</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Not Shipped</fullName>
            </value>
            <value>
                <fullName>Partially Shipped</fullName>
            </value>
            <value>
                <fullName>Awaiting Pricing</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Approval</fullName>
            </value>
            <value>
                <fullName>Customer Approved</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>No Enviado</fullName>
            </value>
            <value>
                <fullName>Envío parcial</fullName>
            </value>
            <value>
                <fullName>Completo</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>NATT_Shipping_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NATT</description>
    <label>NATT Shipping Address</label>
    <referenceTo>NATT_Address__c</referenceTo>
    <relationshipLabel>Orders (NATT Shipping Address)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/recordTypes/CTBR_Parts_Order.recordType-meta.xml
<RecordType>
    <fullName>CTBR_Parts_Order</fullName>
    <active>true</active>
    <label>CTBR Parts Order</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/CTBR_OutOfStockDuringApproval__c.field-meta.xml
<CustomField>
    <fullName>CTBR_OutOfStockDuringApproval__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CTBR - indicates that the customer approved the order when the line item was out of stock (added to their list to create a new order from once in stock)</description>
    <label>Out Of Stock During Approval</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/CTBR_QuantityAvailable__c.field-meta.xml
<CustomField>
    <fullName>CTBR_QuantityAvailable__c</fullName>
    <label>Quantity Available</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/NATT_CtbrPreQuoteConTest.cls
@IsTest
private class NATT_CtbrPreQuoteConTest {
    @IsTest
    static void testGetData(){
        List<Order> oList = NATT_CtbrPreQuoteCon.getOrders('Awaiting Customer Approval');

        List<OrderItem> oiLIst = NATT_CtbrPreQuoteCon.getOutOfStock();

        List<String> oosList = new List<String>();
        for(OrderItem oi : oiList){
            System.debug('qAvail : '+oi.CTBR_QuantityAvailable__c);
            if(oi.CTBR_QuantityAvailable__c==0){
                oosList.add(oi.Id);
            }
        }
        System.debug('oosList: '+oosList);
        NATT_CtbrPreQuoteCon.createOrderFromOutOfStock(oosList);

        NATT_CtbrPreQuoteCon.approveOrder(oList.get(0).Id);
    }

    @TestSetup
    static void makeData(){
        List<Account> aList = new List<Account>();
        alist.add(new Account(Name='Test CTBR Dealer',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CTBR_Dealer').getRecordTypeId()));        
        insert aList;
        
        List<NATT_Address__c> addList = new List<NATT_Address__c>();
        addList.add(new NATT_Address__c(NATT_Type__c='Billing',NATT_Account__c=aList.get(0).Id,RecordTypeId=Schema.SObjectType.NATT_Address__c.getRecordTypeInfosByDeveloperName().get('NATT_Address').getRecordTypeId()));
        addList.add(new NATT_Address__c(NATT_Type__c='Units Ship To',NATT_Account__c=aList.get(0).Id,RecordTypeId=Schema.SObjectType.NATT_Address__c.getRecordTypeInfosByDeveloperName().get('NATT_Address').getRecordTypeId()));
        insert addList;	
        	        
        List<Order> orderList = new List<Order>();
        orderList.add(new Order(AccountId=aList.get(0).Id,EffectiveDate=Date.today().addDays(3),Status='Draft',
            RecordTypeId=Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('CTBR_Parts_Order').getRecordTypeId(),
            NATT_Billing_Address__c=addList.get(0).Id,NATT_Shipping_Address__c=addList.get(1).Id,NATT_Order_Status__c='Awaiting Customer Approval'));
        insert orderList;
        
        
        Product2 testProduct = new Product2(Name = 'Product Test');
        
        insert testProduct;
        List<OrderItem> orderItemList = new List<OrderItem>();
        
        orderItemList.add(new OrderItem(
            OrderId = orderList[0].Id,
            Product2Id = testProduct.Id,
            Quantity = 4,
            UnitPrice = 1,
            ListPrice = 1,
            CTBR_QuantityAvailable__c=4
        ));

        orderItemList.add(new OrderItem(
            OrderId = orderList[0].Id,
            Product2Id = testProduct.Id,
            Quantity = 4,
            UnitPrice = 1,
            ListPrice = 1,
            CTBR_QuantityAvailable__c=0,
            CTBR_OutOfStockDuringApproval__c=true
        ));            
        
        insert orderItemList;        
    }
}