NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Organization__c.field-meta.xml
<CustomField>
    <fullName>NATT_Organization__c</fullName>
    <description>NATT</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Geography</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <description>NATT</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Accounts</description>
    <label>Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Contact/fields/NATT_Key_Business_Role__c.field-meta.xml
<CustomField>
    <fullName>NATT_Key_Business_Role__c</fullName>
    <description>NATT</description>
    <label>Key Business Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Co-Principal</fullName>
            </value>
            <value>
                <fullName>VP/Director</fullName>
            </value>
            <value>
                <fullName>VP/Director - Sales</fullName>
            </value>
            <value>
                <fullName>VP/Director - Parts</fullName>
            </value>
            <value>
                <fullName>VP/Director - Service</fullName>
            </value>
            <value>
                <fullName>VP/Director – Parts &amp; Service</fullName>
            </value>
            <value>
                <fullName>General Manager</fullName>
            </value>
            <value>
                <fullName>Branch Manager</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Service Manager</fullName>
            </value>
            <value>
                <fullName>Parts Manager</fullName>
            </value>
            <value>
                <fullName>Warranty Manager</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>Unit Sales Person</fullName>
            </value>
            <value>
                <fullName>Parts Sales Person</fullName>
            </value>
            <value>
                <fullName>Technician</fullName>
            </value>
            <value>
                <fullName>Warranty Admin</fullName>
            </value>
            <value>
                <fullName>Billing Admin</fullName>
            </value>
            <value>
                <fullName>General Admin</fullName>
            </value>
            <value>
                <fullName>Corporate Officer</fullName>
            </value>
            <value>
                <fullName>Director General</fullName>
            </value>
            <value>
                <fullName>Subdirector</fullName>
            </value>
            <value>
                <fullName>Vice-Presidente/Director</fullName>
            </value>
            <value>
                <fullName>Gerente General</fullName>
            </value>
            <value>
                <fullName>Gerente de Sucursal</fullName>
            </value>
            <value>
                <fullName>Gerente de Ventas</fullName>
            </value>
            <value>
                <fullName>Gerente de Servicio</fullName>
            </value>
            <value>
                <fullName>Gerente de Partes</fullName>
            </value>
            <value>
                <fullName>Gerente de Garantías</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Contact/recordTypes/NATT_Dealer.recordType-meta.xml
<RecordType>
    <fullName>NATT_Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Contacts</description>
    <label>NATT Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/NATT_ItemPriceStaging__c.object-meta.xml
<CustomObject>
    <description>Staging object for imported PartsNet item pricing from JDE (RCGWEB23 &amp; RCGWEB26). Includes standard list prices, customer-specific item prices, and quantity price tiers</description>
    <label>NATT Item Price Staging</label>
    <nameField>
        <displayFormat>IPS-{0000000000}</displayFormat>
        <label>NATT Item Price Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NATT Item Price Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_CustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>NATT_CustomerNumber__c</fullName>
    <description>Customer number this adjustment record applies to. If NULL the record is not customer specifc</description>
    <label>Customer Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_CustomerPriceGroup__c.field-meta.xml
<CustomField>
    <fullName>NATT_CustomerPriceGroup__c</fullName>
    <description>Specifies the customer price group</description>
    <label>Customer Price Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_EffectiveDate__c</fullName>
    <description>Date this price becomes effective</description>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_ExpiryDate__c</fullName>
    <description>Date this price expires and no longer applies</description>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_ItemPriceType__c.field-meta.xml
<CustomField>
    <fullName>NATT_ItemPriceType__c</fullName>
    <description>Alphanumeric code indicating the type of price (i.e. SRP - Standard Retail Price, INTPRC - Internal Price)</description>
    <label>Item Price Type</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_Product__c.field-meta.xml
<CustomField>
    <fullName>NATT_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>NATT Item Price Staging</relationshipLabel>
    <relationshipName>NATT_Item_Price_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/NATT_PriceAdjustmentStaging__c.object-meta.xml
<CustomObject>
    <description>Staging object for imported PartsNet price adjustments (discount or markup) for the assorted Customer Price Group/Item Price Group combinations (RCGWEB22 &amp; RCGWEB25). Does not include quantity price break information.</description>
    <label>NATT Price Adjustment Staging</label>
    <nameField>
        <displayFormat>PAS-{000000000}</displayFormat>
        <label>NATT Price Adjustment Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NATT Price Adjustment Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_AdjustmentType__c.field-meta.xml
<CustomField>
    <fullName>NATT_AdjustmentType__c</fullName>
    <description>Alphanumeric code indicating the type of adjustment (e.x. REGD - Regular Discount, SURCHG - Surcharge)</description>
    <label>Adjustment Type</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_AdjustmentValue__c.field-meta.xml
<CustomField>
    <fullName>NATT_AdjustmentValue__c</fullName>
    <description>Contains the decimal percentage value that the list price or standard cost should be adjusted. If the value in NATT_AdjustmentName__c == SURCHG, this field will be interpreted as a MARKUP, if REGD, then will be interpreted as a discount.</description>
    <label>Adjustment Value</label>
    <precision>10</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_CustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>NATT_CustomerNumber__c</fullName>
    <description>Customer number this adjustment record applies to.</description>
    <label>Customer Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_CustomerPriceGroup__c.field-meta.xml
<CustomField>
    <fullName>NATT_CustomerPriceGroup__c</fullName>
    <description>Identifes the Customer Price Group to which the adjustment applies.</description>
    <label>Customer Price Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_EffectiveDate__c</fullName>
    <description>Date this price becomes effective</description>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_ExpiryDate__c</fullName>
    <description>Date this price expires and no longer applies</description>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_Product__c.field-meta.xml
<CustomField>
    <fullName>NATT_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>NATT Price Adjustment Staging</relationshipLabel>
    <relationshipName>NATT_Price_Adjustment_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/recordTypes/NATT_PPG.recordType-meta.xml
<RecordType>
    <fullName>NATT_PPG</fullName>
    <active>true</active>
    <label>NATT PPG</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_UnitCost__c.field-meta.xml
<CustomField>
    <fullName>NATT_UnitCost__c</fullName>
    <description>Contains the unit cost of the item in USD. The purpose of the field is to overcome a B2B Commerce limitation of 1 basis price per storefront, and is used when generating price book prices for internal PPG customers.</description>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/Geography.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NATT</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>CTB</fullName>
    </customValue>
    <customValue>
        <fullName>Need the others listed</fullName>
        <isActive>false</isActive>
        <label>Need the others listed</label>
    </customValue>
    <masterLabel>Geography</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>East</fullName>
    </customValue>
    <customValue>
        <fullName>West</fullName>
    </customValue>
    <customValue>
        <fullName>South</fullName>
    </customValue>
    <customValue>
        <fullName>Central</fullName>
    </customValue>
    <customValue>
        <fullName>National</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Latin America</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Region 1</fullName>
    </customValue>
    <customValue>
        <fullName>Region 2</fullName>
    </customValue>
    <customValue>
        <fullName>Region 3</fullName>
    </customValue>
    <customValue>
        <fullName>Northeast</fullName>
    </customValue>
    <customValue>
        <fullName>Southeast</fullName>
    </customValue>
    <customValue>
        <fullName>Midwest</fullName>
    </customValue>
    <customValue>
        <fullName>North</fullName>
    </customValue>
    <customValue>
        <fullName>Europe, Middle East and Africa</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pacific and Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>Americas</fullName>
        <isActive>false</isActive>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>undefined</fullName>
        <isActive>false</isActive>
        <label>undefined</label>
    </customValue>
    <customValue>
        <fullName>Asia</fullName>
        <isActive>false</isActive>
        <label>Asia</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/NattBatchPriceAdjustmentTest.cls
@IsTest
public with sharing class NattBatchPriceAdjustmentTest {
      
    @TestSetup
    static void setupTestData() {
        Account a = new Account(
            Name = 'Test',
            NATT_Organization__c = 'NATT',
            NATT_Region__c = 'East',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()
        );
        insert a;
 Contact c = new Contact(
        AccountId = a.Id,
        FirstName = 'Test',
        LastName = 'User',
        NATT_Key_Business_Role__c = 'Principal',
        RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('NATT_Dealer').getRecordTypeId()
    );
    insert c;

    BuyerGroup testBuyerGroup = new BuyerGroup(
        Name = 'Test BG'
    );
    insert testBuyerGroup;

    Pricebook2 testPricebook = new Pricebook2(
        Id = Test.getStandardPricebookId(),
        IsActive = true
    );
    update testPricebook;

    Product2 testProduct = new Product2(
        Name = 'Test Product 1',
        IsActive = true
    );
    insert testProduct;

    Id pricebookId = Test.getStandardPricebookId();

    PricebookEntry testPricebookEntry = new PricebookEntry(
        Pricebook2Id = pricebookId,
        Product2Id = testProduct.Id,
        UnitPrice = 1000,
        IsActive = true
    );
    insert testPricebookEntry;

    Pricebook2 customPricebook = new Pricebook2(
        Name = 'Custom Test Pricebook',
        IsActive = true
    );
    insert customPricebook;

    Product2 testProduct2 = new Product2(
        Name = 'Test Product 2',
        IsActive = true,
        NATT_UnitCost__c = 999
    );
    insert testProduct2;

    WebStore testPPGStorefront = new WebStore(
        Name = 'Performance Parts'
    );
    insert testPPGStorefront;
}

@isTest
static void testBatchNattItemPriceStaging_PriceAdjustment() {
    Decimal originalPrice = null;
    BuyerGroup testBuyerGroup = [SELECT ID, Name FROM BuyerGroup LIMIT 1];

    Product2 testProduct = new Product2(
        Name = 'Test Product 01',
        IsActive = true,
        NATT_UnitCost__c = 2000
    );
    insert testProduct;

    Pricebook2 standardPB = new Pricebook2(
        Id = Test.getStandardPricebookId(),
        IsActive = true
    );
    update standardPB;

    PricebookEntry testPricebookEntry = new PricebookEntry(
        Pricebook2Id = standardPB.Id,
        Product2Id = testProduct.Id,
        UnitPrice = 1000,
        IsActive = true
    );
    insert testPricebookEntry;

    Product2 testProduct2 = new Product2(
        Name = 'Test Product 02',
        IsActive = true,
        NATT_UnitCost__c = 100
    );
    insert testProduct2;

    Pricebook2 customPb = new Pricebook2(
        Name = '1',
        IsActive = true
    );
    insert customPb;

    PricebookEntry pbe = new PricebookEntry(
        Product2Id = testProduct.Id,
        UnitPrice = 200,
        IsActive = true,
        Pricebook2Id = customPb.Id
    );
    insert pbe;

    NATT_ItemPriceStaging__c testNattIPS = new NATT_ItemPriceStaging__c(
        NATT_ItemPriceType__c = 'SRP',
        NATT_CustomerPriceGroup__c = testBuyerGroup.Id,
        NATT_CustomerNumber__c = 1,
        NATT_EffectiveDate__c = Date.today() - 1,
        NATT_ExpiryDate__c = Date.today() + 10,
        RecordTypeId = Schema.SObjectType.NATT_ItemPriceStaging__c.getRecordTypeInfosByDeveloperName().get('NATT_PPG').getRecordTypeId()
    );
    insert testNattIPS;

    Product2 testProductCostGrab = [SELECT NATT_UnitCost__c FROM Product2 WHERE Id = :testProduct.Id FOR UPDATE];
    System.debug('originalUnitCost:' + testProductCostGrab.NATT_UnitCost__c);

    NATT_PriceAdjustmentStaging__c nattPAS = new NATT_PriceAdjustmentStaging__c(
        NATT_Product__c = testProduct.Id,
        NATT_CustomerPriceGroup__c = testBuyerGroup.Id,
        NATT_CustomerNumber__c = 1,
        NATT_AdjustmentType__c = 'REGD',
        NATT_AdjustmentValue__c = -17,
        NATT_EffectiveDate__c = Date.today(),
        NATT_ExpiryDate__c = Date.today().addDays(10),
        RecordTypeId = Schema.SObjectType.NATT_PriceAdjustmentStaging__c.getRecordTypeInfosByDeveloperName().get('NATT_PPG').getRecordTypeId()
    );
    insert nattPAS;

    Test.startTest();
    NattBatchPriceAdjustment batchPriceAdj = new NattBatchPriceAdjustment();
    Database.executeBatch(batchPriceAdj);
    Test.stopTest();

    Decimal updatedPrice = (testProduct.NATT_UnitCost__c + (testProduct.NATT_UnitCost__c * (nattPAS.NATT_AdjustmentValue__c / 100)));
    System.debug('updatedPrice:' + updatedPrice);
    System.debug('pbeList:' + [SELECT Name, UnitPrice FROM PricebookEntry]);

    PricebookEntry productList = [SELECT Name, UnitPrice FROM PricebookEntry WHERE UnitPrice = :updatedPrice LIMIT 1];
    System.assertEquals(updatedPrice, productList.UnitPrice, 'We expect a new Pricebook Entry based on the NATT_PriceAdjustmentStagings Adjustment Value');
}

@isTest
static void testBatchPriceAdjustmentStaging_NoUpdate() {
    BuyerGroup testBuyerGroup = [SELECT ID, Name FROM BuyerGroup LIMIT 1];
    Product2 testProduct = new Product2(
        Name = 'Test Product 01',
        IsActive = true
    );
    insert testProduct;

    Pricebook2 standardPB = new Pricebook2(
        Id = Test.getStandardPricebookId(),
        IsActive = true
    );
    update standardPB;

    PricebookEntry testPricebookEntry = new PricebookEntry(
        Pricebook2Id = standardPB.Id,
        Product2Id = testProduct.Id,
        UnitPrice = 1000,
        IsActive = true
    );
    insert testPricebookEntry;

    Product2 testProduct2 = new Product2(
        Name = 'Test Product 02',
        IsActive = true,
        NATT_UnitCost__c = 100
    );
    insert testProduct2;

    Pricebook2 customPb = new Pricebook2(
        Name = 'Custom Pricebook',
        IsActive = true
    );
    insert customPb;

    List<PricebookEntry> pbCheckBef = [SELECT ID, Name FROM PricebookEntry];
    Integer listSizeBefore = pbCheckBef.size();
    System.debug('List Size: ' + listSizeBefore);

    NATT_ItemPriceStaging__c testNattIPS = new NATT_ItemPriceStaging__c(
        NATT_ItemPriceType__c = 'SRP',
        NATT_CustomerPriceGroup__c = testBuyerGroup.Id,
        NATT_CustomerNumber__c = 1,
        NATT_EffectiveDate__c = Date.today() - 1,
        NATT_ExpiryDate__c = Date.today() + 10,
        RecordTypeId = Schema.SObjectType.NATT_ItemPriceStaging__c.getRecordTypeInfosByDeveloperName().get('NATT_PPG').getRecordTypeId()
    );
    insert testNattIPS;

    NATT_PriceAdjustmentStaging__c nattPAS = new NATT_PriceAdjustmentStaging__c(
        NATT_Product__c = testProduct.Id,
        NATT_CustomerPriceGroup__c = testBuyerGroup.Id,
        NATT_CustomerNumber__c = 1,
        NATT_AdjustmentType__c = 'TREGD',
        NATT_AdjustmentValue__c = 17,
        RecordTypeId = Schema.SObjectType.NATT_PriceAdjustmentStaging__c.getRecordTypeInfosByDeveloperName().get('NATT_PPG').getRecordTypeId()
    );
    insert nattPAS;

    Test.startTest();
    NattBatchPriceAdjustment batchPriceAdj = new NattBatchPriceAdjustment();
    Database.executeBatch(batchPriceAdj);
    Test.stopTest();

    List<PricebookEntry> pbCheckAfter = [SELECT ID, Name FROM PricebookEntry];
    Integer listSizeAfter = pbCheckAfter.size();
    System.debug('List Size After: ' + listSizeAfter);
        

        System.assertEquals(listSizeBefore, listSizeAfter, 'Since the Test Product does not include a NATT_UnitCost__c, we do not expect a new Pricebook Entry to get created.');
    }
    
      @isTest
    static void testSendMessage() {
        
        NattBatchPriceAdjustment batchInstance = new NattBatchPriceAdjustment();

        
        List<String> errorMessages = new List<String>();
        errorMessages.add('Error 1: Sample error message 1');
        errorMessages.add('Error 2: Sample error message 2');
        
        Test.startTest();
        batchInstance.sendMessage(errorMessages);
        Test.stopTest();

          }



}