NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Organization__c.field-meta.xml
<CustomField>
    <fullName>NATT_Organization__c</fullName>
    <description>NATT</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Geography</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <description>NATT</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Accounts</description>
    <label>Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/NATT_OEM.recordType-meta.xml
<RecordType>
    <fullName>NATT_OEM</fullName>
    <active>true</active>
    <description>NATT OEM Accounts</description>
    <label>Direct Sale</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <formula>TEXT(Account.NATT_Region__c)</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/NATT_Stock__c.field-meta.xml
<CustomField>
    <fullName>NATT_Stock__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT users check this if there is no end customer</description>
    <label>Stock</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/recordTypes/NATT_Opportunity_Units.recordType-meta.xml
<RecordType>
    <fullName>NATT_Opportunity_Units</fullName>
    <active>true</active>
    <businessProcess>NATT Opportunity Units Sales Process</businessProcess>
    <description>NATT Opportunity Units Recordtype</description>
    <label>Units</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <description>for eSolutions quotes only</description>
    <formula>TEXT(SBQQ__Account__r.NATT_Region__c)</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Stock__c.field-meta.xml
<CustomField>
    <fullName>NATT_Stock__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT users check this if there is no end customer</description>
    <label>Stock</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__PricebookId__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PricebookId__c</fullName>
    <description>ID of the Price Book used by this quote.</description>
    <inlineHelpText>ID of the Price Book used by this quote.</inlineHelpText>
    <label>Pricebook ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Primary__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox which if checked designates the quote as the Primary Quote</description>
    <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Type__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Type__c</fullName>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
                <default>true</default>
                <label>Quote</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Re-Quote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__NetPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__NetPrice__c</fullName>
    <description>Net unit price for the product quoted by this line item.</description>
    <inlineHelpText>Net unit price for the product quoted by this line item.</inlineHelpText>
    <label>Net Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quantity__c</fullName>
    <description>Quantity being quoted.</description>
    <inlineHelpText>Quantity being quoted.</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__RequiredBy__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RequiredBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this line to another line in the same quote whose product requires this line&apos;s product.</description>
    <inlineHelpText>Indicates which other product on this quote requires it.</inlineHelpText>
    <label>Required By</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/Geography.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NATT</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>CTB</fullName>
    </customValue>
    <customValue>
        <fullName>Need the others listed</fullName>
        <isActive>false</isActive>
        <label>Need the others listed</label>
    </customValue>
    <masterLabel>Geography</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>East</fullName>
    </customValue>
    <customValue>
        <fullName>West</fullName>
    </customValue>
    <customValue>
        <fullName>South</fullName>
    </customValue>
    <customValue>
        <fullName>Central</fullName>
    </customValue>
    <customValue>
        <fullName>National</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Latin America</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Region 1</fullName>
    </customValue>
    <customValue>
        <fullName>Region 2</fullName>
    </customValue>
    <customValue>
        <fullName>Region 3</fullName>
    </customValue>
    <customValue>
        <fullName>Northeast</fullName>
    </customValue>
    <customValue>
        <fullName>Southeast</fullName>
    </customValue>
    <customValue>
        <fullName>Midwest</fullName>
    </customValue>
    <customValue>
        <fullName>North</fullName>
    </customValue>
    <customValue>
        <fullName>Europe, Middle East and Africa</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pacific and Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>Americas</fullName>
        <isActive>false</isActive>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>undefined</fullName>
        <isActive>false</isActive>
        <label>undefined</label>
    </customValue>
    <customValue>
        <fullName>Asia</fullName>
        <isActive>false</isActive>
        <label>Asia</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/CloneOpportunityQuoteDirectSalesTest.cls
@IsTest
public class CloneOpportunityQuoteDirectSalesTest {

    @TestSetup
    static void setupData() {
        // === Get and activate Standard Pricebook ===
        Id pricebookId = Test.getStandardPricebookId();
        Pricebook2 standardPricebook = new Pricebook2(
            Id = pricebookId,
            IsActive = true
        );
       // update standardPricebook;

        // === Create custom Pricebook ===
        Pricebook2 customPb = new Pricebook2(Name='NATT Units Price Book', IsActive=true);
        insert customPb;

        // === Create Products ===
        List<Product2> products = new List<Product2>();
        for(Integer i=1; i<=6; i++){
            products.add(new Product2(Name='Test Product '+i, Family='Test', IsActive=true));
        }
        insert products;

        // === Standard PricebookEntries (required before custom PB) ===
        List<PricebookEntry> stdPbes = new List<PricebookEntry>();
        for(Product2 p : products){
            stdPbes.add(new PricebookEntry(
                Product2Id = p.Id,
                Pricebook2Id = standardPricebook.Id,
                UnitPrice = 100,
                IsActive = true
            ));
        }
        insert stdPbes;

        // === Custom PricebookEntries ===
        List<PricebookEntry> customPbes = new List<PricebookEntry>();
        for(Product2 p : products){
            customPbes.add(new PricebookEntry(
                Product2Id = p.Id,
                Pricebook2Id = customPb.Id,
                UnitPrice = 100,
                IsActive = true
            ));
        }
        insert customPbes;

        // === Accounts ===
        Account dealerAcc = new Account(
            Name='Test Dealer',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId(),
            NATT_Organization__c = 'NATT',
            NATT_Region__c = 'East'
        );
        Account directSaleAcc = new Account(
            Name='Test Direct Sales',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('NATT_OEM').getRecordTypeId(),
            NATT_Organization__c = 'NATT',
            NATT_Region__c = 'East'
        );
        insert new List<Account>{dealerAcc, directSaleAcc};

        // === Opportunity ===
        Opportunity opp = new Opportunity(
            Name='UnitsTestOpp',
            CloseDate=Date.today().addDays(30),
            StageName='Qualification',
            AccountId=dealerAcc.Id,
            Pricebook2Id=customPb.Id,
            RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NATT_Opportunity_Units').getRecordTypeId(),
            NATT_Stock__c=true
        );
        insert opp;

        // === Quote ===
        SBQQ__Quote__c quote = new SBQQ__Quote__c(
            SBQQ__Opportunity2__c = opp.Id,
            SBQQ__PricebookId__c  = customPb.Id,
            SBQQ__Primary__c      = true,
            SBQQ__Status__c       = 'Draft',
            SBQQ__Type__c         = 'Quote'
           // Name = 'CloneTestQuote'
        );
        insert quote;

        // === Quote Lines ===
        List<SBQQ__QuoteLine__c> quoteLineList = new List<SBQQ__QuoteLine__c>();
        for(Integer i=0; i<6; i++){
            SBQQ__QuoteLine__c ql = new SBQQ__QuoteLine__c(
                SBQQ__Quote__c = quote.Id,
                SBQQ__Product__c = products[i].Id,
                SBQQ__PricebookEntryId__c = customPbes[i].Id,
                SBQQ__Quantity__c = 1,
                SBQQ__NetPrice__c = 100
            );

            // Example of RequiredBy links
            if(i==2) ql.SBQQ__RequiredBy__c = quoteLineList[0].Id;
            if(i==3) ql.SBQQ__RequiredBy__c = quoteLineList[1].Id;

            quoteLineList.add(ql);
        }
        insert quoteLineList;
    }

    @IsTest
    static void testCloneOpportunityWithQuote() {
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name='UnitsTestOpp' LIMIT 1];

        Test.startTest();
        CloneOpportunityQuoteDirectSales.CloneResult result =
            CloneOpportunityQuoteDirectSales.cloneOpportunityWithQuote(opp.Id);
        Test.stopTest();

        System.assert(result.success, 'Cloning should succeed');
        System.assertNotEquals(null, result.newOpportunityId, 'New Opportunity should be created');
        System.assertNotEquals(null, result.newQuoteId, 'New Quote should be created');
     //   System.assert(result.newQLICount > 0, 'At least one Quote Line should be cloned');

        // === Validate updates ===
        Opportunity clonedOpp = [SELECT Name FROM Opportunity WHERE Id = :result.newOpportunityId];
        System.assert(clonedOpp.Name.contains('Clone'), 'Cloned Opportunity name should be updated with Clone');
        
        SBQQ__Quote__c clonedQuote = [SELECT SBQQ__Primary__c FROM SBQQ__Quote__c WHERE Id = :result.newQuoteId];
        System.assertEquals(true, clonedQuote.SBQQ__Primary__c, 'Cloned Quote should be Primary');
    }

    @IsTest
    static void testCloneOpportunityNoQuote() {
        Account acc = [SELECT Id FROM Account WHERE Name='Test Dealer' LIMIT 1];
        Opportunity oppNoQuote = new Opportunity(
            Name='NoQuoteOpp',
            CloseDate=Date.today().addDays(30),
            StageName='Qualification',
            AccountId=acc.Id,
            RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NATT_Opportunity_Units').getRecordTypeId()
        );
        insert oppNoQuote;

        Test.startTest();
        CloneOpportunityQuoteDirectSales.CloneResult result =
            CloneOpportunityQuoteDirectSales.cloneOpportunityWithQuote(oppNoQuote.Id);
        Test.stopTest();

        System.assert(result.success, 'Cloning should succeed even with no Quote');
        System.assertEquals(null, result.newQuoteId, 'No Quote should be created');
        System.assert(result.message.contains('No CPQ Quote found'), 'Message should indicate no Quote found');
    }

    @IsTest
    static void testCloneWithNotificationFailure() {
        // Delete notification type to simulate error
        List<CustomNotificationType> notifTypes = [SELECT Id FROM CustomNotificationType WHERE DeveloperName='Clone_Notification' LIMIT 1];
        if(!notifTypes.isEmpty()) {
        //    delete notifTypes;
        }

        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name='UnitsTestOpp' LIMIT 1];

        Test.startTest();
        CloneOpportunityQuoteDirectSales.CloneResult result =
            CloneOpportunityQuoteDirectSales.cloneOpportunityWithQuote(opp.Id);
                    CloneOpportunityQuoteDirectSales.isQuoteApproved(opp.Id, null);
        Test.stopTest();

        System.assert(result.success, 'Cloning should still succeed even if notification fails');
    }

    @IsTest
    static void testCloneWithNullId() {
        Test.startTest();
        CloneOpportunityQuoteDirectSales.CloneResult result =
            CloneOpportunityQuoteDirectSales.cloneOpportunityWithQuote(null);
        Test.stopTest();

        System.assertEquals(false, result.success, 'Should fail if no Id provided');
        System.assert(result.message.contains('No Opportunity Id'), 'Message should indicate missing Id');
    }
}