NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Organization__c.field-meta.xml
<CustomField>
    <fullName>NATT_Organization__c</fullName>
    <description>NATT</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Geography</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <description>NATT</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Status__c.field-meta.xml
<CustomField>
    <fullName>NATT_Status__c</fullName>
    <description>NATT</description>
    <label>NATT Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <isActive>false</isActive>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Warranty_Status__c.field-meta.xml
<CustomField>
    <fullName>NATT_Warranty_Status__c</fullName>
    <label>Warranty Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Accounts</description>
    <label>Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Contact/fields/NATT_Key_Business_Role__c.field-meta.xml
<CustomField>
    <fullName>NATT_Key_Business_Role__c</fullName>
    <description>NATT</description>
    <label>Key Business Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Co-Principal</fullName>
            </value>
            <value>
                <fullName>VP/Director</fullName>
            </value>
            <value>
                <fullName>VP/Director - Sales</fullName>
            </value>
            <value>
                <fullName>VP/Director - Parts</fullName>
            </value>
            <value>
                <fullName>VP/Director - Service</fullName>
            </value>
            <value>
                <fullName>VP/Director – Parts &amp; Service</fullName>
            </value>
            <value>
                <fullName>General Manager</fullName>
            </value>
            <value>
                <fullName>Branch Manager</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Service Manager</fullName>
            </value>
            <value>
                <fullName>Parts Manager</fullName>
            </value>
            <value>
                <fullName>Warranty Manager</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>Unit Sales Person</fullName>
            </value>
            <value>
                <fullName>Parts Sales Person</fullName>
            </value>
            <value>
                <fullName>Technician</fullName>
            </value>
            <value>
                <fullName>Warranty Admin</fullName>
            </value>
            <value>
                <fullName>Billing Admin</fullName>
            </value>
            <value>
                <fullName>General Admin</fullName>
            </value>
            <value>
                <fullName>Corporate Officer</fullName>
            </value>
            <value>
                <fullName>Director General</fullName>
            </value>
            <value>
                <fullName>Subdirector</fullName>
            </value>
            <value>
                <fullName>Vice-Presidente/Director</fullName>
            </value>
            <value>
                <fullName>Gerente General</fullName>
            </value>
            <value>
                <fullName>Gerente de Sucursal</fullName>
            </value>
            <value>
                <fullName>Gerente de Ventas</fullName>
            </value>
            <value>
                <fullName>Gerente de Servicio</fullName>
            </value>
            <value>
                <fullName>Gerente de Partes</fullName>
            </value>
            <value>
                <fullName>Gerente de Garantías</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Contact/fields/NATT_Refrigeration_Technician__c.field-meta.xml
<CustomField>
    <fullName>NATT_Refrigeration_Technician__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Refrigeration Technician</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Contact/recordTypes/NATT_Dealer.recordType-meta.xml
<RecordType>
    <fullName>NATT_Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Contacts</description>
    <label>NATT Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/NATT_Extended_Warranty__c/NATT_Extended_Warranty__c.object-meta.xml
<CustomObject>
    <description>Used with Tavant integration</description>
    <label>Unit Terms</label>
    <nameField>
        <displayFormat>EW-{0000000}</displayFormat>
        <label>Unit Terms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NATT_Extended_Warranty</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_Extended_Warranty__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>This field will be used by Tavant when record is process based on Unit type. value will always be &apos;Update&apos; from Tavant</description>
    <label>Action</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Extended_Warranty__c/fields/Deductibles__c.field-meta.xml
<CustomField>
    <fullName>Deductibles__c</fullName>
    <description>Deductible value of the line item</description>
    <label>Deductibles</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Extended_Warranty__c/fields/IsProcessed__c.field-meta.xml
<CustomField>
    <fullName>IsProcessed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsProcessed</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/Geography.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NATT</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>CTB</fullName>
    </customValue>
    <customValue>
        <fullName>Need the others listed</fullName>
        <isActive>false</isActive>
        <label>Need the others listed</label>
    </customValue>
    <masterLabel>Geography</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>East</fullName>
    </customValue>
    <customValue>
        <fullName>West</fullName>
    </customValue>
    <customValue>
        <fullName>South</fullName>
    </customValue>
    <customValue>
        <fullName>Central</fullName>
    </customValue>
    <customValue>
        <fullName>National</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Latin America</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Region 1</fullName>
    </customValue>
    <customValue>
        <fullName>Region 2</fullName>
    </customValue>
    <customValue>
        <fullName>Region 3</fullName>
    </customValue>
    <customValue>
        <fullName>Northeast</fullName>
    </customValue>
    <customValue>
        <fullName>Southeast</fullName>
    </customValue>
    <customValue>
        <fullName>Midwest</fullName>
    </customValue>
    <customValue>
        <fullName>North</fullName>
    </customValue>
    <customValue>
        <fullName>Europe, Middle East and Africa</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pacific and Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>Americas</fullName>
        <isActive>false</isActive>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>undefined</fullName>
        <isActive>false</isActive>
        <label>undefined</label>
    </customValue>
    <customValue>
        <fullName>Asia</fullName>
        <isActive>false</isActive>
        <label>Asia</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/SyncSobjectTest.cls
/**
* @name SyncSobjectTest
* @description Test class for SyncSobject 
* @date 9 August 2021
* @author DS
* @changes
***/
@isTest
private class SyncSobjectTest {
    
    private static testmethod void testsyncSobject(){
        String uniqueUserName = 'sysadmin' + DateTime.now().getTime() + '@testorg.com';
        // This code runs as the system user
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new User(Alias = 'sysadm', Email='sysadm@testorg.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,
                          TimeZoneSidKey='America/Los_Angeles',
                          UserName=uniqueUserName);
        
        System.runAs(u) {
            List<Account> accLst = new List<Account>();
            //Account acc = NATT_DataFactory.accRecord();
            Id dealerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId();          
            Account acc = new Account(
            Name = 'Test Account1',
            recordTypeID = dealerRecordTypeId,
            AccountNumber = '4578');
            acc.NATT_Status__c = 'Active';
            acc.NATT_Warranty_Status__c = 'Active';
            acc.NATT_Organization__c = 'NATT';
            acc.NATT_Region__c = 'East';
            accLst.add(acc);
            insert accLst;
            
            List<Contact> conLst = new List<Contact>();
            //Contact con = NATT_DataFactory.conRecord(acc.ID);
            Id rectypeNattDealer = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('NATT_Dealer').getRecordTypeId();        
            Contact con = new Contact(
            firstName = 'TestContact',
            lastName = 'Con',
            recordTypeId = rectypeNattDealer,
            accountID = accLst[0].Id);
            conLst.add(con);
            insert conLst;
            
            Account a = new Account(Name='Test', NATT_Organization__c = 'NATT', NATT_Region__c = 'East',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId());
            insert a;
            Contact c = new Contact(AccountId=a.Id,FirstName='Test',LastName='User',NATT_Key_Business_Role__c='Technician',NATT_Refrigeration_Technician__c=true,
                                    RecordTypeId=Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('NATT_Dealer').getRecordTypeId());
            insert c;
            
            Test.startTest(); 
            
            c.NATT_Refrigeration_Technician__c=false;
            update c;
            
            delete c;   
                     
            delete a;
            
            PartnerNetworkConnection existingConnection = [SELECT Id, ConnectionName FROM PartnerNetworkConnection WHERE ConnectionName = 'Carrier Transicold Europe' AND ConnectionStatus = 'Accepted' LIMIT 1];
            system.assertequals('Carrier Transicold Europe',existingConnection.ConnectionName,'Proper connection found');

            List<NATT_Extended_Warranty__c> warrantyLst = new List<NATT_Extended_Warranty__c>();
            NATT_Extended_Warranty__c wartyObj = new NATT_Extended_Warranty__c();
            wartyObj.Action__c = 'dummyAction';
            wartyObj.IsProcessed__c = true;
            wartyObj.Deductibles__c = '3.5';
            wartyObj.CurrencyIsoCode = 'USD';
            warrantyLst.add(wartyObj);
            insert warrantyLst;
            
            //Assertion check
            System.assertEquals(1, accLst.size(), 'Account success');
            System.assertEquals(1, conLst.size(), 'Contact success');
            System.assertEquals(1, warrantyLst.size(), 'Warranty success');  
            Test.stopTest();   
        }
        
    }
}