NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Dealership__c.field-meta.xml
<CustomField>
    <fullName>NATT_Dealership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For End Customer RT&apos;s. This is the dealer the End Customer belongs to.</description>
    <label>Dealership</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer, Direct Sale, CTM Dealer, CTBR Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/NATT_Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>NATT Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_Account__c.field-meta.xml
<CustomField>
    <fullName>NATT_Account__c</fullName>
    <description>NATT</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>NATT_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_City__c.field-meta.xml
<CustomField>
    <fullName>NATT_City__c</fullName>
    <description>NATT</description>
    <label>City</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_State_Province__c.field-meta.xml
<CustomField>
    <fullName>NATT_State_Province__c</fullName>
    <description>NATT</description>
    <label>State/Province</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>NATT_State_Picklist</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_Street__c.field-meta.xml
<CustomField>
    <fullName>NATT_Street__c</fullName>
    <description>NATT</description>
    <label>Street</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_Type__c.field-meta.xml
<CustomField>
    <fullName>NATT_Type__c</fullName>
    <description>NATT</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Dealer Agreement</fullName>
            </value>
            <value>
                <fullName>Distribution Centers</fullName>
            </value>
            <value>
                <fullName>Headquarters</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Other Mailing</fullName>
            </value>
            <value>
                <fullName>Parts Ship To</fullName>
            </value>
            <value>
                <fullName>Physical</fullName>
            </value>
            <value>
                <fullName>Regional Offices</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Units Ship To</fullName>
            </value>
            <value>
                <fullName>Bill To</fullName>
            </value>
            <value>
                <fullName>Ship To</fullName>
            </value>
            <value>
                <fullName>TES Ship To</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>NATT_Zip_Postal_Code__c</fullName>
    <description>NATT</description>
    <label>Zip/Postal Code</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/AccountDetailsBillingShippingController.cls
/**
 * @class AccountDetailsBillingShippingController
 * @description This class provides a method to fetch related Billing and Shipping 
 *              addresses for a given Account.
 * @author Vamsi Mogidi
 * @createdDate 2024-12-12
 * @TestClass AccountDetailsControllerTest
 */
public class AccountDetailsBillingShippingController {

    /**AccountDetailsBillingShippingController.getRelatedAddresses();
     * @method getRelatedAddresses
     * @description Retrieves a list of Billing and Shipping addresses associated 
     *              with a specific Account.
     * @param accountId The Id of the Account whose related addresses are to be fetched.
     * @return A list of NATT_Address__c records representing the related addresses.
     * @developer Vamsi Mogidi
     * @example Example usage: List<NATT_Address__c> addresses = AccountDetailsBillingShippingController.getRelatedAddresses(accountId);
     */
    @AuraEnabled(cacheable=true)
    public static List<NATT_Address__c> getRelatedAddresses(Id accountId) {
        // Query to fetch related addresses of the specified Account
        return [
            SELECT Name, NATT_Type__c, NATT_Street__c, NATT_City__c, 
                   NATT_State_Province__c, NATT_Zip_Postal_Code__c
            FROM NATT_Address__c
            WHERE NATT_Account__c = :accountId
        ];
    }
    @AuraEnabled(cacheable=true)
    public static Account getAccountInfo(Id accountId) {
        // Query to fetch related addresses of the specified Account
        return [
            select Id, Name, RecordType.name, NATT_Dealership__c , NATT_Dealership__r.RecordType.name 
            from Account 
            where id = :accountId
        ];
    }
}