NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Organization__c.field-meta.xml
<CustomField>
    <fullName>NATT_Organization__c</fullName>
    <description>NATT</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Geography</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <description>NATT</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Contact/fields/NATT_Key_Business_Role__c.field-meta.xml
<CustomField>
    <fullName>NATT_Key_Business_Role__c</fullName>
    <description>NATT</description>
    <label>Key Business Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Co-Principal</fullName>
            </value>
            <value>
                <fullName>VP/Director</fullName>
            </value>
            <value>
                <fullName>VP/Director - Sales</fullName>
            </value>
            <value>
                <fullName>VP/Director - Parts</fullName>
            </value>
            <value>
                <fullName>VP/Director - Service</fullName>
            </value>
            <value>
                <fullName>VP/Director – Parts &amp; Service</fullName>
            </value>
            <value>
                <fullName>General Manager</fullName>
            </value>
            <value>
                <fullName>Branch Manager</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Service Manager</fullName>
            </value>
            <value>
                <fullName>Parts Manager</fullName>
            </value>
            <value>
                <fullName>Warranty Manager</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>Unit Sales Person</fullName>
            </value>
            <value>
                <fullName>Parts Sales Person</fullName>
            </value>
            <value>
                <fullName>Technician</fullName>
            </value>
            <value>
                <fullName>Warranty Admin</fullName>
            </value>
            <value>
                <fullName>Billing Admin</fullName>
            </value>
            <value>
                <fullName>General Admin</fullName>
            </value>
            <value>
                <fullName>Corporate Officer</fullName>
            </value>
            <value>
                <fullName>Director General</fullName>
            </value>
            <value>
                <fullName>Subdirector</fullName>
            </value>
            <value>
                <fullName>Vice-Presidente/Director</fullName>
            </value>
            <value>
                <fullName>Gerente General</fullName>
            </value>
            <value>
                <fullName>Gerente de Sucursal</fullName>
            </value>
            <value>
                <fullName>Gerente de Ventas</fullName>
            </value>
            <value>
                <fullName>Gerente de Servicio</fullName>
            </value>
            <value>
                <fullName>Gerente de Partes</fullName>
            </value>
            <value>
                <fullName>Gerente de Garantías</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_JDE_Sales_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>NATT_JDE_Sales_Order_Number__c</fullName>
    <description>NATT</description>
    <externalId>true</externalId>
    <label>JDE Sales Order #</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>NATT_Purchase_Order__c</fullName>
    <description>NATT</description>
    <label>PO #</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <formula>TEXT(Account.NATT_Region__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Shipment_Terms__c.field-meta.xml
<CustomField>
    <fullName>NATT_Shipment_Terms__c</fullName>
    <description>NATT</description>
    <label>Shipment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Shipment_Terms</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_Backordered_Quantity__c.field-meta.xml
<CustomField>
    <fullName>NATT_Backordered_Quantity__c</fullName>
    <description>Back Order</description>
    <label>Backordered Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_P_N__c</fullName>
    <description>Has a value if the line item is a Kit. Null if the line item is a part of the unit</description>
    <label>P/N</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_P_N__c.field-meta.xml
<CustomField>
    <fullName>NATT_P_N__c</fullName>
    <description>The Part Number for NATT JDE</description>
    <label>Part Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/Geography.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NATT</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>CTB</fullName>
    </customValue>
    <customValue>
        <fullName>Need the others listed</fullName>
        <isActive>false</isActive>
        <label>Need the others listed</label>
    </customValue>
    <masterLabel>Geography</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Shipment_Terms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BIL</fullName>
        <label>Bill to Customer</label>
    </customValue>
    <customValue>
        <fullName>PPD</fullName>
        <label>Prepaid Freight</label>
    </customValue>
    <customValue>
        <fullName>COL</fullName>
        <label>Collect</label>
    </customValue>
    <customValue>
        <fullName>CPU</fullName>
        <label>Customer Pickup</label>
    </customValue>
    <customValue>
        <fullName>PPA</fullName>
        <label>Prepaid and Allowed</label>
    </customValue>
    <customValue>
        <fullName>PPB</fullName>
        <label>Prepaid and Billed</label>
    </customValue>
    <customValue>
        <fullName>EXW</fullName>
        <label>EXW - EX Works</label>
    </customValue>
    <customValue>
        <fullName>CIF</fullName>
    </customValue>
    <customValue>
        <fullName>DDP</fullName>
    </customValue>
    <customValue>
        <fullName>FOB</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>999</fullName>
    </customValue>
    <customValue>
        <fullName>AAA</fullName>
    </customValue>
    <customValue>
        <fullName>ABF</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AF1</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AVE</fullName>
    </customValue>
    <customValue>
        <fullName>BCB</fullName>
    </customValue>
    <customValue>
        <fullName>BW</fullName>
    </customValue>
    <customValue>
        <fullName>BW1</fullName>
    </customValue>
    <customValue>
        <fullName>CAR</fullName>
    </customValue>
    <masterLabel>Shipment Terms</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>East</fullName>
    </customValue>
    <customValue>
        <fullName>West</fullName>
    </customValue>
    <customValue>
        <fullName>South</fullName>
    </customValue>
    <customValue>
        <fullName>Central</fullName>
    </customValue>
    <customValue>
        <fullName>National</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Latin America</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Region 1</fullName>
    </customValue>
    <customValue>
        <fullName>Region 2</fullName>
    </customValue>
    <customValue>
        <fullName>Region 3</fullName>
    </customValue>
    <customValue>
        <fullName>Northeast</fullName>
    </customValue>
    <customValue>
        <fullName>Southeast</fullName>
    </customValue>
    <customValue>
        <fullName>Midwest</fullName>
    </customValue>
    <customValue>
        <fullName>North</fullName>
    </customValue>
    <customValue>
        <fullName>Europe, Middle East and Africa</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pacific and Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>Americas</fullName>
        <isActive>false</isActive>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>undefined</fullName>
        <isActive>false</isActive>
        <label>undefined</label>
    </customValue>
    <customValue>
        <fullName>Asia</fullName>
        <isActive>false</isActive>
        <label>Asia</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/natt_TestDataFactory.cls
public class natt_TestDataFactory {
    public static User createUser(string userName, string profileName, string alias) {
        Profile profile = [SELECT Id FROM Profile WHERE Name =: profileName LIMIT 1];
        User user = new User(
            FirstName = 'Test',
            LastName = userName,
            Username = 'testuser' + userName + '@example.com',
            Email = 'testuser' +userName + '@example.com',
            Alias = alias,
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            ProfileId = profile.Id
            //RoleId = roleId
        );
        return user;
    }
    
    public static UserRole createRole() {
        UserRole role = new UserRole(
            Name = 'Test Role',
            DeveloperName = 'Test_Role'
        );
        return role;
    }
    
    public static Account createAccount(string name, Id recordtypeId) {
        Account account = new Account(
            Name = name,
            NATT_Region__c = 'East',
            RecordTypeId = recordtypeId,
            NATT_Organization__c = 'NATT'            
        );
        return account;
    }
    
    public static Contact createContact(Id accountId,string lastName, Id RecordTypeId) {
        Contact contact = new Contact(
            FirstName = 'Test',
            LastName = lastName,
            AccountId = accountId,
            Phone = '123-456-7890',
            RecordTypeId = RecordTypeId,
            NATT_Key_Business_Role__c = 'Principal',
            Email = 'testcontact' + lastName + '@example.com'
        );
        return contact;
    }
    
    public static Order createOrder(Id accountId,Id recordTypeId) {
        Order order = new Order(
            Type = 'Stock',
            Status = 'Draft',
            AccountId = accountId,
            NATT_Purchase_Order__c= '1234',
            NATT_Shipment_Terms__c = 'PPD',
            EffectiveDate = System.today(),
            NATT_JDE_Sales_Order_Number__c = '555',
            OrderedDate = (DateTime)System.today()             
        );
        return order;
    }
    
    
    public static OrderItem createOrderItem(Id orderId, Id productId, Decimal quantity) {
        //PricebookEntry pricebookEntry = [SELECT Id, UnitPrice FROM PricebookEntry WHERE IsActive = true LIMIT 1];
        OrderItem ordItem = new OrderItem(        	
            Quantity = 4,
            UnitPrice = 2,
            ListPrice = 123,
            LineNumber = 10,
            OrderId = orderId,
            Product2Id = productId,
            NATT_Backordered_Quantity__c = quantity
        );
        return ordItem;
    }
    
    public static Product2 createProduct(string name,string pin) {
        Product2 testProduct = new Product2(
            Name = name,
            NATT_P_N__c = pin        
        );
        return testProduct;
    }
}