NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Customer_Price_Group__c.field-meta.xml
<CustomField>
    <fullName>NATT_Customer_Price_Group__c</fullName>
    <description>PPG Price List to which the account is assigned</description>
    <label>Customer Price Group</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_JDE_Parts_Bill_To_Code__c.field-meta.xml
<CustomField>
    <fullName>NATT_JDE_Parts_Bill_To_Code__c</fullName>
    <description>JDE Address number used for the PPG Parts Bill-To Account</description>
    <externalId>true</externalId>
    <label>JDE Parts Bill To Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>NATT End User/End Customer Accounts</description>
    <label>Customer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/NATT_ItemPriceStaging__c.object-meta.xml
<CustomObject>
    <description>Staging object for imported PartsNet item pricing from JDE (RCGWEB23 &amp; RCGWEB26). Includes standard list prices, customer-specific item prices, and quantity price tiers</description>
    <label>NATT Item Price Staging</label>
    <nameField>
        <displayFormat>IPS-{0000000000}</displayFormat>
        <label>NATT Item Price Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NATT Item Price Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_BasisCode__c.field-meta.xml
<CustomField>
    <fullName>NATT_BasisCode__c</fullName>
    <description>Code that identifies the basis of the value in the List Price field. 3 represents Standard Cost, 5 represents Standard List Price. 

0    % of New Base Price
1    % of Base Price
2    % of Current Net Price
3    % of Cost
4    Cost Plus Amount
5    Add on Amount
6    Add on Variable Amount
7    Add on Formula Amount
8    Add on User Program Amount
9    Gross Profit Margin</description>
    <label>Basis Code</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_CustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>NATT_CustomerNumber__c</fullName>
    <description>Customer number this adjustment record applies to. If NULL the record is not customer specifc</description>
    <label>Customer Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_CustomerPriceGroup__c.field-meta.xml
<CustomField>
    <fullName>NATT_CustomerPriceGroup__c</fullName>
    <description>Specifies the customer price group</description>
    <label>Customer Price Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_EffectiveDate__c</fullName>
    <description>Date this price becomes effective</description>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_ExpiryDate__c</fullName>
    <description>Date this price expires and no longer applies</description>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_ItemNumber__c.field-meta.xml
<CustomField>
    <fullName>NATT_ItemNumber__c</fullName>
    <description>Unique number that identifies the item</description>
    <label>Item Number</label>
    <length>48</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_ItemPriceGroup__c.field-meta.xml
<CustomField>
    <fullName>NATT_ItemPriceGroup__c</fullName>
    <description>Identifies the sales price group number of the item</description>
    <label>Item Price Group</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_ItemPriceKeyId__c.field-meta.xml
<CustomField>
    <fullName>NATT_ItemPriceKeyId__c</fullName>
    <description>JDE key ID for the item price</description>
    <externalId>true</externalId>
    <label>Item Price Key ID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_ItemPriceType__c.field-meta.xml
<CustomField>
    <fullName>NATT_ItemPriceType__c</fullName>
    <description>Alphanumeric code indicating the type of price (i.e. SRP - Standard Retail Price, INTPRC - Internal Price)</description>
    <label>Item Price Type</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_ListPrice__c.field-meta.xml
<CustomField>
    <fullName>NATT_ListPrice__c</fullName>
    <description>Contains either the list price, standard cost or Customer Item price as indicated by value in Item Price Type field</description>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_PricePartial__c.field-meta.xml
<CustomField>
    <fullName>NATT_PricePartial__c</fullName>
    <defaultValue>false</defaultValue>
    <description>TBD</description>
    <label>Price Partial</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_Product__c.field-meta.xml
<CustomField>
    <fullName>NATT_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>NATT Item Price Staging</relationshipLabel>
    <relationshipName>NATT_Item_Price_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_QuantityFrom__c.field-meta.xml
<CustomField>
    <fullName>NATT_QuantityFrom__c</fullName>
    <description>Specifies the quantity at which this price applies.</description>
    <label>Quantity From</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_UOM__c.field-meta.xml
<CustomField>
    <fullName>NATT_UOM__c</fullName>
    <description>Item&apos;s unit of measure</description>
    <label>Unit of Measure</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/recordTypes/NATT_TES.recordType-meta.xml
<RecordType>
    <fullName>NATT_TES</fullName>
    <active>true</active>
    <label>NATT TES</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/NATT_PriceAdjustmentStaging__c.object-meta.xml
<CustomObject>
    <description>Staging object for imported PartsNet price adjustments (discount or markup) for the assorted Customer Price Group/Item Price Group combinations (RCGWEB22 &amp; RCGWEB25). Does not include quantity price break information.</description>
    <label>NATT Price Adjustment Staging</label>
    <nameField>
        <displayFormat>PAS-{000000000}</displayFormat>
        <label>NATT Price Adjustment Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NATT Price Adjustment Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_AdjustmentType__c.field-meta.xml
<CustomField>
    <fullName>NATT_AdjustmentType__c</fullName>
    <description>Alphanumeric code indicating the type of adjustment (e.x. REGD - Regular Discount, SURCHG - Surcharge)</description>
    <label>Adjustment Type</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_AdjustmentValue__c.field-meta.xml
<CustomField>
    <fullName>NATT_AdjustmentValue__c</fullName>
    <description>Contains the decimal percentage value that the list price or standard cost should be adjusted. If the value in NATT_AdjustmentName__c == SURCHG, this field will be interpreted as a MARKUP, if REGD, then will be interpreted as a discount.</description>
    <label>Adjustment Value</label>
    <precision>10</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_BasisCode__c.field-meta.xml
<CustomField>
    <fullName>NATT_BasisCode__c</fullName>
    <label>Basis Code</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_CustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>NATT_CustomerNumber__c</fullName>
    <description>Customer number this adjustment record applies to.</description>
    <label>Customer Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_CustomerPriceGroup__c.field-meta.xml
<CustomField>
    <fullName>NATT_CustomerPriceGroup__c</fullName>
    <description>Identifes the Customer Price Group to which the adjustment applies.</description>
    <label>Customer Price Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_EffectiveDate__c</fullName>
    <description>Date this price becomes effective</description>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_ExpiryDate__c</fullName>
    <description>Date this price expires and no longer applies</description>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_ItemNumber__c.field-meta.xml
<CustomField>
    <fullName>NATT_ItemNumber__c</fullName>
    <description>Unique number that identifies the item</description>
    <label>Item Number</label>
    <length>48</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_ItemPriceGroup__c.field-meta.xml
<CustomField>
    <fullName>NATT_ItemPriceGroup__c</fullName>
    <description>Identifies the item price group the adjustment applies to.</description>
    <label>Item Price Group</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_PricePartial__c.field-meta.xml
<CustomField>
    <fullName>NATT_PricePartial__c</fullName>
    <defaultValue>false</defaultValue>
    <description>TBD</description>
    <label>Price Partial</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_Product__c.field-meta.xml
<CustomField>
    <fullName>NATT_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>NATT Price Adjustment Staging</relationshipLabel>
    <relationshipName>NATT_Price_Adjustment_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_QuantityFrom__c.field-meta.xml
<CustomField>
    <fullName>NATT_QuantityFrom__c</fullName>
    <description>Specifies the quantity at which this price applies.</description>
    <label>Quantity From</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/fields/NATT_UOM__c.field-meta.xml
<CustomField>
    <fullName>NATT_UOM__c</fullName>
    <description>Unit of Measure</description>
    <label>Unit of Measure</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PriceAdjustmentStaging__c/recordTypes/NATT_PPG.recordType-meta.xml
<RecordType>
    <fullName>NATT_PPG</fullName>
    <active>true</active>
    <label>NATT PPG</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_ItemPriceGroup__c.field-meta.xml
<CustomField>
    <fullName>NATT_ItemPriceGroup__c</fullName>
    <description>A number identifying the price group to which the item belongs</description>
    <label>Item Price Group</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_UnitCost__c.field-meta.xml
<CustomField>
    <fullName>NATT_UnitCost__c</fullName>
    <description>Contains the unit cost of the item in USD. The purpose of the field is to overcome a B2B Commerce limitation of 1 basis price per storefront, and is used when generating price book prices for internal PPG customers.</description>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/NattBatchMultiListPrice.cls
public class NattBatchMultiListPrice implements Database.Batchable<sObject>,Database.Stateful{
    Id standardPbId = Test.isRunningTest()?Test.getStandardPricebookId():[SELECT Id FROM Pricebook2 WHERE IsStandard=true].Id;
    private Boolean hasErrors = false;
    private List<String> errorMessages = new List<String>();
    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator([SELECT Id,NATT_BasisCode__c,NATT_CustomerNumber__c,NATT_CustomerPriceGroup__c,NATT_EffectiveDate__c,NATT_ExpiryDate__c,NATT_ItemNumber__c,
                                         NATT_ItemPriceGroup__c,NATT_ItemPriceKeyId__c,NATT_ItemPriceType__c,NATT_ListPrice__c,NATT_PricePartial__c,NATT_QuantityFrom__c,NATT_UOM__c,
                                         NATT_Product__c,NATT_Product__r.NATT_UnitCost__c,NATT_Product__r.NATT_ItemPriceGroup__c
                                         FROM NATT_ItemPriceStaging__c 
                                         WHERE NATT_EffectiveDate__c<=TODAY AND NATT_ExpiryDate__c>=TODAY 
                                         AND NATT_ItemPriceType__c='SRP'
                                         AND NATT_CustomerPriceGroup__c=null
                                         AND NATT_ItemPriceGroup__c=null
                                         AND NATT_ListPrice__c>0
                                         AND NATT_Product__c!=''
                                         AND NATT_CustomerNumber__c!=null  
                                         AND RecordType.DeveloperName IN ('NATT_PPG','NATT_TES')                                       
                                         ORDER BY NATT_CustomerNumber__c DESC, NATT_QuantityFrom__c ASC]);
    }
    public void execute(Database.BatchableContext bc, List<NATT_ItemPriceStaging__c> scope){        
        Set<Id> srpIdSet = new Set<Id>();
        Set<String> accountPartCodeSet = new Set<String>();
        Map<Id,PricebookEntry> standardPbeMap = new Map<Id,PricebookEntry>();
        List<PricebookEntry> pbeUpsertList = new List<PricebookEntry>();        
        Map<String,Account> accountMap = new Map<String,Account>();
        Set<String> customerPriceGroupSet = new Set<String>();
        Map<String,NATT_PriceAdjustmentStaging__c> adjustmentMap = new Map<String,NATT_PriceAdjustmentStaging__c>();
        Set<String> itemPriceGroupSet = new Set<String>();
        Set<Id> pricebookIdSet = new Set<Id>();
        Map<String,Pricebook2> allReferencedPbMap = new Map<String,Pricebook2>();
        Map<String,Map<Id,PricebookEntry>> pbToPbeMap = new Map<String,Map<Id,PricebookEntry>>();
        Map<String,PricebookEntry> pbeUpsertMap = new Map<String,PricebookEntry>();		
        
        for(NATT_ItemPriceStaging__c ip : scope){            
            srpIdSet.add(ip.NATT_Product__c);
            accountPartCodeSet.add(String.valueOf(ip.NATT_CustomerNumber__c));
            itemPriceGroupSet.add(ip.NATT_Product__r.NATT_ItemPriceGroup__c);
        }

        for(Account a : [SELECT Id,NATT_JDE_Parts_Bill_To_Code__c,NATT_Customer_Price_Group__c FROM Account WHERE NATT_JDE_Parts_Bill_To_Code__c IN :accountPartCodeSet]){
            accountMap.put(a.NATT_JDE_Parts_Bill_To_Code__c,a);
            customerPriceGroupSet.add(a.NATT_Customer_Price_Group__c);            
        }
		System.debug('AccountMap:'+accountMap);
        System.debug('customerPriceGroupSet:'+customerPriceGroupSet);
        System.debug('itemPriceGroupSet:'+itemPriceGroupSet);
        //get all the referenced PBs so we can add PBEs to them
        for(Pricebook2 pb : [SELECT Id,Name FROM Pricebook2 WHERE Name IN :accountMap.keySet() AND IsStandard=false AND IsActive=true]){
            allReferencedPbMap.put(pb.Name,pb);
            pricebookIdSet.add(pb.Id);
        }
        
        //find pricebooks that have not been previously created (which is the case for most of the customer specific standard prices)
        Set<String> pbNotCreatedSet = new Set<String>();
        for(String accountCode : accountPartCodeSet){
            if(!allReferencedPbMap.containsKey(accountCode)){
                pbNotCreatedSet.add(accountCode);
            }
        }        
        if(!pbNotCreatedSet.isEmpty()){
            System.debug('creating: '+pbNotCreatedSet);
            PriceAdjustmentStagingTrgHandler.handleBuyerGroupSetup(pbNotCreatedSet);
            for(Pricebook2 pb : [SELECT Id,Name FROM Pricebook2 WHERE Name IN :accountMap.keySet() AND IsStandard=false AND IsActive=true]){
                allReferencedPbMap.put(pb.Name,pb);
                pricebookIdSet.add(pb.Id);
            }
        }
        
        for(PricebookEntry pbe : [SELECT Id,Pricebook2Id,Product2Id,CurrencyIsoCode,UnitPrice,Pricebook2.Name
                                      FROM PricebookEntry WHERE Product2Id in :srpIdSet 
                                      AND CurrencyIsoCode='USD' AND Pricebook2Id=:standardPbId]){
        	standardPbeMap.put(pbe.Product2Id,pbe);
         }
        
        for(PricebookEntry pbe : [SELECT Id,Pricebook2Id,Product2Id,CurrencyIsoCode,UnitPrice,Pricebook2.Name
                                      FROM PricebookEntry WHERE Product2Id in :srpIdSet
                                      AND CurrencyIsoCode='USD' AND Pricebook2Id IN :priceBookIdSet]){
                if(!pbToPbeMap.containsKey(pbe.Pricebook2.Name)){
                    pbToPbeMap.put(pbe.Pricebook2.Name,new Map<Id,PricebookEntry>());
                }
                //per Carrier: only adding if there is a standard price to adjust
                if(standardPbeMap.containsKey(pbe.Product2Id)){
                	pbToPbeMap.get(pbe.Pricebook2.Name).put(pbe.Product2Id,pbe);
                }
        }
		System.debug('pbToPbeMap:'+pbToPbeMap);
        for(NATT_PriceAdjustmentStaging__c stage : [SELECT Id,NATT_CustomerPriceGroup__c,NATT_ItemPriceGroup__c,NATT_AdjustmentValue__c 
                                                    FROM NATT_PriceAdjustmentStaging__c 
                                                    WHERE NATT_CustomerPriceGroup__c IN :customerPriceGroupSet
                                                    AND NATT_ItemPriceGroup__c IN :itemPriceGroupSet 
                                                    AND NATT_AdjustmentType__c='REGD' 
                                                    AND NATT_AdjustmentValue__c!=0
                                                    AND NATT_EffectiveDate__c<=TODAY AND NATT_ExpiryDate__c>=TODAY ]){
            adjustmentMap.put(stage.NATT_CustomerPriceGroup__c+':'+stage.NATT_ItemPriceGroup__c,stage);
        }
        System.debug('adjustmentMap:'+adjustmentMap);
        String key;
        decimal adjustmentValue;
        decimal pbeValue;
        String errorMsg='';
        for(NATT_ItemPriceStaging__c ip : scope){
            if(accountMap.containsKey(String.valueOf(ip.NATT_CustomerNumber__c))){
                Account a = accountMap.get(String.valueOf(ip.NATT_CustomerNumber__c));
                key = a.NATT_Customer_Price_Group__c+':'+ip.NATT_Product__r.NATT_ItemPriceGroup__c;
                if(adjustmentMap.containsKey(key)){
                    adjustmentValue = adjustmentMap.get(key).NATT_AdjustmentValue__c;
                    pbeValue = ip.NATT_ListPrice__c * (1 + (adjustmentValue/100));
                }
                if(pbToPbeMap.containsKey(a.NATT_JDE_Parts_Bill_To_Code__c) && pbToPbeMap.get(a.NATT_JDE_Parts_Bill_To_Code__c).containsKey(ip.NATT_Product__c)){
                    String pbkey = pbToPbeMap.get(a.NATT_JDE_Parts_Bill_To_Code__c)+':'+pbToPbeMap.get(a.NATT_JDE_Parts_Bill_To_Code__c).get(ip.NATT_Product__c).Id;
                    if(!pbeUpsertMap.containsKey(pbkey))
                        pbeUpsertMap.put(pbkey,new PricebookEntry(Id=pbToPbeMap.get(a.NATT_JDE_Parts_Bill_To_Code__c).get(ip.NATT_Product__c).Id,UnitPrice=pbeValue,IsActive=true));                    
                }else if ((!pbToPbeMap.containsKey(a.NATT_JDE_Parts_Bill_To_Code__c) || !pbToPbeMap.get(a.NATT_JDE_Parts_Bill_To_Code__c).containsKey(ip.NATT_Product__c)) && allReferencedPbMap.containsKey(a.NATT_JDE_Parts_Bill_To_Code__c)){
                    String pbkey = allReferencedPbMap.get(a.NATT_JDE_Parts_Bill_To_Code__c).Id+':'+ip.NATT_Product__c;
                    if(!pbeUpsertMap.containsKey(pbkey))
                        pbeUpsertMap.put(pbkey,new PricebookEntry(Pricebook2Id=allReferencedPbMap.get(a.NATT_JDE_Parts_Bill_To_Code__c).Id,CurrencyIsoCode='USD',Product2Id=ip.NATT_Product__c,UnitPrice=pbeValue,IsActive=true));                    
                }
            }
        }
        if(!pbeUpsertMap.isEmpty()){
            List<Database.UpsertResult> urList=Database.upsert(pbeUpsertMap.values(), PricebookEntry.Id, false);
            integer i = 0;
            for(Database.UpsertResult ur : urList){
                if(!ur.isSuccess()){
                    errorMsg+=pbeUpsertMap.values().get(i).Product2Id+':'+' UnitCost: '+pbeUpsertMap.values().get(i).UnitPrice+'-'+ur.getErrors().get(0).getMessage()+'<br/>';                    
                }
                i++;
            }
            System.debug('errorMsg'+errorMsg);
            if(String.isNotBlank(errorMsg)){
                //sendMessage(errorMsg);
                hasErrors = true;
                errorMessages.add(errorMsg);
            }
        }
    }

    public void finish(Database.BatchableContext bc){
        Boolean NATTEnableDebugBatchEmail = Boolean.valueOf(Label.NATTEnableDebugBatchEmail);
        if (hasErrors && NATTEnableDebugBatchEmail) {
            sendMessage(errorMessages);
        }
        if(!Test.isRunningTest())
        	Database.executeBatch(new NattBatchPriceAdjustment());
    }
    
    @TestVisible
    private void sendMessage(List<String> errorMessages){
        String emailAddress = Label.NATTBATCHEmailList;
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage(); 
         String body = 'The batch process encountered the following errors:\n' + String.join(errorMessages, '\n');
        message.toAddresses = emailAddress.split(','); 
        message.subject = 'NattBatchMultiListPrice Failure';
        message.htmlBody = body;
        Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage> {message};
        Messaging.SendEmailResult[] results;
        if(!Test.isRunningTest()){
            results = Messaging.sendEmail(messages);
            if (results[0].success) {
                System.debug('The email was sent successfully.');
            } else {
                System.debug('The email failed to send: ' + results[0].errors[0].message);
            }
        }
    }
}