NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Special_Products__c.field-meta.xml
<CustomField>
    <fullName>NATT_Special_Products__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Special Products</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PAR__c/NATT_PAR__c.object-meta.xml
<CustomObject>
    <description>NATT PAR (Primary Areas of Responsibility) records for Accounts</description>
    <label>PAR</label>
    <nameField>
        <label>PAR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PAR</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_PAR__c/fields/NATT_Account__c.field-meta.xml
<CustomField>
    <fullName>NATT_Account__c</fullName>
    <description>NATT Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PAR</relationshipLabel>
    <relationshipName>PAR</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PAR__c/fields/NATT_Country__c.field-meta.xml
<CustomField>
    <fullName>NATT_Country__c</fullName>
    <defaultValue>&quot;United States&quot;</defaultValue>
    <description>NATT Country</description>
    <label>Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PAR__c/fields/NATT_County__c.field-meta.xml
<CustomField>
    <fullName>NATT_County__c</fullName>
    <description>NATT County</description>
    <label>County</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PAR__c/fields/NATT_Special_Products__c.field-meta.xml
<CustomField>
    <fullName>NATT_Special_Products__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT</description>
    <label>Special Products</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PAR__c/fields/NATT_State__c.field-meta.xml
<CustomField>
    <fullName>NATT_State__c</fullName>
    <description>NATT State</description>
    <label>State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PAR__c/fields/NATT_Trailer__c.field-meta.xml
<CustomField>
    <fullName>NATT_Trailer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT</description>
    <label>Trailer</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_PAR__c/fields/NATT_Truck__c.field-meta.xml
<CustomField>
    <fullName>NATT_Truck__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT</description>
    <label>Truck</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/NATT_ParExportToCsvController.cls
/********************************************************************************************************
* @author         (Deloitte)
* @description    This class is for PAR Export Functionality.
* @date           05/04/2023 [MM/DD/YYYY]
* 
* Modification Log:
* -------------------------------------------------------------------------------------------------------
* Developer                Date                   Modification ID      Description
* -------------------------------------------------------------------------------------------------------
* Deloitte               05/04/2023                                  Initial version
*********************************************************************************************************/
public with sharing class NATT_ParExportToCsvController{
    @AuraEnabled
    public static List<NATT_PAR__c> getPARList(string accId){
        List<NATT_PAR__c> parlist = new List<NATT_PAR__c>();
        
        if(Site.getSiteType() != null){
           parlist = [SELECT Id, Name, NATT_Country__c, NATT_State__c, NATT_County__c, NATT_Trailer__c, NATT_Truck__c
                                     FROM NATT_PAR__c 
                                     where NATT_Account__c =:accId
                                     Order by Name];
        }else{
            parlist = [SELECT Id, Name, NATT_Country__c, NATT_State__c, NATT_County__c, NATT_Trailer__c, NATT_Truck__c, NATT_Special_Products__c	
                                     FROM NATT_PAR__c 
                                     where NATT_Account__c =:accId
                                     Order by Name];
        }
       
        if(!parlist.isEmpty()){
            if (parlist[0].NATT_Country__c == null){
                parlist[0].NATT_Country__c = 'ReplaceCountryNull';
            }if (parlist[0].NATT_State__c == null){
                parlist[0].NATT_State__c = 'ReplaceStateNull';
            }if (parlist[0].NATT_County__c == null){
                parlist[0].NATT_County__c = 'ReplaceCountyNull';
            }
        }
        
        return parlist;
    }
    
    @AuraEnabled
    public static account getAccountName(string accId){
        return [SELECT id, Name FROM Account where id =:accId];
    }
}