NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Organization__c.field-meta.xml
<CustomField>
    <fullName>NATT_Organization__c</fullName>
    <description>NATT</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Geography</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <description>NATT</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/NATT_OEM.recordType-meta.xml
<RecordType>
    <fullName>NATT_OEM</fullName>
    <active>true</active>
    <description>NATT OEM Accounts</description>
    <label>Direct Sale</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <formula>TEXT(Account.NATT_Region__c)</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/NATT_Stock__c.field-meta.xml
<CustomField>
    <fullName>NATT_Stock__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT users check this if there is no end customer</description>
    <label>Stock</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/Opportunity_Source__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Source</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities (Opportunity Source)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/recordTypes/NATT_Direct_Sales.recordType-meta.xml
<RecordType>
    <fullName>NATT_Direct_Sales</fullName>
    <active>true</active>
    <businessProcess>NATT Opportunity Units Sales Process</businessProcess>
    <description>Natt Direct Sales Record Type</description>
    <label>NATT Direct Sales</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Is_Base_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Is_Base_Unit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>for base units only</description>
    <label>Is Base Unit</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/Direct_Sales_Units__c.field-meta.xml
<CustomField>
    <fullName>Direct_Sales_Units__c</fullName>
    <label>Direct Sales Units</label>
    <summaryFilterItems>
        <field>SBQQ__QuoteLine__c.NATT_Is_Base_Unit__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>SBQQ__QuoteLine__c.SBQQ__Quote__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <description>for eSolutions quotes only</description>
    <formula>TEXT(SBQQ__Account__r.NATT_Region__c)</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Stock__c.field-meta.xml
<CustomField>
    <fullName>NATT_Stock__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT users check this if there is no end customer</description>
    <label>Stock</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__PricebookId__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PricebookId__c</fullName>
    <description>ID of the Price Book used by this quote.</description>
    <inlineHelpText>ID of the Price Book used by this quote.</inlineHelpText>
    <label>Pricebook ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Primary__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox which if checked designates the quote as the Primary Quote</description>
    <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Source__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Source of cloned quote.</description>
    <inlineHelpText>Source of cloned quote. If cloned, this references the original quote cloned.</inlineHelpText>
    <label>Source</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quotes (Source)</relationshipLabel>
    <relationshipName>Clones</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Type__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Type__c</fullName>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
                <default>true</default>
                <label>Quote</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Re-Quote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_Is_Base_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Is_Base_Unit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT for all products that are base units only</description>
    <label>Is Base Unit</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__NetPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__NetPrice__c</fullName>
    <description>Net unit price for the product quoted by this line item.</description>
    <inlineHelpText>Net unit price for the product quoted by this line item.</inlineHelpText>
    <label>Net Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quantity__c</fullName>
    <description>Quantity being quoted.</description>
    <inlineHelpText>Quantity being quoted.</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__RequiredBy__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RequiredBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this line to another line in the same quote whose product requires this line&apos;s product.</description>
    <inlineHelpText>Indicates which other product on this quote requires it.</inlineHelpText>
    <label>Required By</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Source__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Source of cloned quote line.</description>
    <inlineHelpText>Source of cloned quote line.</inlineHelpText>
    <label>Source</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Lines (Source)</relationshipLabel>
    <relationshipName>Clones</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__SubscribedQuoteLine__c/SBQQ__SubscribedQuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscribedAssetHelp</customHelpPage>
    <description>Links a particular asset to the subscription that covers it.</description>
    <label>Subscribed Quote Line</label>
    <nameField>
        <displayFormat>SQL-{00000000}</displayFormat>
        <label>Subscribed Quote Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribed Quote Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__SubscribedQuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies the quote for the quoteLines.</description>
    <inlineHelpText>Identifies the quote for the quoteLines.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/Geography.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NATT</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>CTB</fullName>
    </customValue>
    <customValue>
        <fullName>Need the others listed</fullName>
        <isActive>false</isActive>
        <label>Need the others listed</label>
    </customValue>
    <masterLabel>Geography</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>East</fullName>
    </customValue>
    <customValue>
        <fullName>West</fullName>
    </customValue>
    <customValue>
        <fullName>South</fullName>
    </customValue>
    <customValue>
        <fullName>Central</fullName>
    </customValue>
    <customValue>
        <fullName>National</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Latin America</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Region 1</fullName>
    </customValue>
    <customValue>
        <fullName>Region 2</fullName>
    </customValue>
    <customValue>
        <fullName>Region 3</fullName>
    </customValue>
    <customValue>
        <fullName>Northeast</fullName>
    </customValue>
    <customValue>
        <fullName>Southeast</fullName>
    </customValue>
    <customValue>
        <fullName>Midwest</fullName>
    </customValue>
    <customValue>
        <fullName>North</fullName>
    </customValue>
    <customValue>
        <fullName>Europe, Middle East and Africa</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pacific and Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>Americas</fullName>
        <isActive>false</isActive>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>undefined</fullName>
        <isActive>false</isActive>
        <label>undefined</label>
    </customValue>
    <customValue>
        <fullName>Asia</fullName>
        <isActive>false</isActive>
        <label>Asia</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/NATT_DirectSales_AddBundleOnParent_Test.cls
@IsTest
private class NATT_DirectSales_AddBundleOnParent_Test {

    @TestSetup
    static void setupData() { 
        // Activate Standard Pricebook
        Id stdPbId = Test.getStandardPricebookId();
        update new Pricebook2(Id = stdPbId, IsActive = true);

        // Products (bundle parent + two children)
        Product2 pParent = new Product2(Name = 'Bundle Parent', Family = 'Test', IsActive = true);
        Product2 pChild1 = new Product2(Name = 'Child 1',NATT_Is_Base_Unit__c = true, Family = 'Test', IsActive = true);
        Product2 pChild2 = new Product2(Name = 'Child 2', Family = 'Test', IsActive = true);
        insert new List<Product2>{ pParent, pChild1, pChild2 };

        // PBEs on Standard PB
        PricebookEntry pbeParent = new PricebookEntry(Product2Id = pParent.Id, Pricebook2Id = stdPbId, UnitPrice = 100, IsActive = true);
        PricebookEntry pbeChild1 = new PricebookEntry(Product2Id = pChild1.Id, Pricebook2Id = stdPbId, UnitPrice = 10,  IsActive = true);
        PricebookEntry pbeChild2 = new PricebookEntry(Product2Id = pChild2.Id, Pricebook2Id = stdPbId, UnitPrice = 20,  IsActive = true);
        insert new List<PricebookEntry>{ pbeParent, pbeChild1, pbeChild2 };

        // Basic Account & Opportunity
            Account acc = new Account(Name='Test Direct Sales',
                                      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('NATT_OEM').getRecordTypeId(),
                                      NATT_Organization__c = 'NATT',
                                      NATT_Region__c = 'East'
                                     );
        insert acc;
        Opportunity opp = new Opportunity(
            Name = 'Test Opp',
            AccountId = acc.Id,
            CloseDate=Date.today().addDays(30),
            StageName='Qualification',
            RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NATT_Direct_Sales').getRecordTypeId(),
            NATT_Stock__c=true,
            Pricebook2Id = stdPbId
        );
        insert opp;
          Opportunity opp2 = new Opportunity(
            Name = 'Test Opp',
            AccountId = acc.Id,
            CloseDate=Date.today().addDays(30),
            StageName='Qualification',
            RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NATT_Direct_Sales').getRecordTypeId(),
            NATT_Stock__c=true,
            Pricebook2Id = stdPbId,
            Opportunity_Source__c = opp.Id

        );
        insert opp2;

        // Destination quote (receives the clones)
        SBQQ__Quote__c qDest = new SBQQ__Quote__c(
            SBQQ__Opportunity2__c = opp.Id,
            SBQQ__PricebookId__c  = stdPbId,
            SBQQ__Primary__c      = true,
            SBQQ__Status__c       = 'Draft',
            SBQQ__Type__c         = 'Quote',
            RecordTypeId = Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByDeveloperName().get('NATT_Direct_Sales').getRecordTypeId()

        );
        insert qDest;

        // Input/template quote
        SBQQ__Quote__c qInput = new SBQQ__Quote__c(
            SBQQ__Opportunity2__c = opp.Id,
            SBQQ__PricebookId__c  = stdPbId,
            SBQQ__Primary__c      = false,
            SBQQ__Status__c       = 'Draft',
            SBQQ__Type__c         = 'Quote',
            SBQQ__Source__c		  = qDest.Id,
            RecordTypeId = Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByDeveloperName().get('NATT_Direct_Sales').getRecordTypeId()
        );
        insert qInput;

        // Create bundle on INPUT quote
        SBQQ__QuoteLine__c qlParent = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c          = qInput.Id,
            SBQQ__Product__c        = pParent.Id,
            SBQQ__PricebookEntryId__c = pbeParent.Id,
            SBQQ__Quantity__c       = 1,
            SBQQ__NetPrice__c       = 100,
            SBQQ__RequiredBy__c     = null,
            NATT_Is_Base_Unit__c    = true  // <-- required by your query
        );
        insert qlParent;

        SBQQ__QuoteLine__c qlChild1 = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c          = qInput.Id,
            SBQQ__Product__c        = pChild1.Id,
            SBQQ__PricebookEntryId__c = pbeChild1.Id,
            SBQQ__Quantity__c       = 1,
            SBQQ__NetPrice__c       = 10,
            SBQQ__RequiredBy__c     = qlParent.Id
        );
        SBQQ__QuoteLine__c qlChild2 = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c          = qInput.Id,
            SBQQ__Product__c        = pChild2.Id,
            SBQQ__PricebookEntryId__c = pbeChild2.Id,
            SBQQ__Quantity__c       = 1,
            SBQQ__NetPrice__c       = 20,
            SBQQ__RequiredBy__c     = qlParent.Id
        );
        insert new List<SBQQ__QuoteLine__c>{ qlChild1, qlChild2 };
    }

    @IsTest
    static void test_clone_then_add_same_product_again() {
        // Fetch our quotes
        SBQQ__Quote__c cloneQuote = [SELECT Id,Direct_Sales_Units__c  FROM SBQQ__Quote__c where SBQQ__Source__c != null LIMIT 1];
        // Pick the other quote as destination
        SBQQ__Quote__c SourceQuote  = [SELECT Id,Direct_Sales_Units__c FROM SBQQ__Quote__c WHERE SBQQ__Source__c = null LIMIT 1];
        Product2 productc1 = [select id, name from product2 where Name = 'Child 1' limit 1];
        PricebookEntry pbe = [SELECT Id,Name,Product2.Name from PricebookEntry where Product2.name = 'Child 1' limit 1] ;
        // Create bundle on INPUT quote
        SBQQ__QuoteLine__c qlParent = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c          = cloneQuote.Id,
            SBQQ__Product__c        = productc1.Id,
            SBQQ__PricebookEntryId__c = pbe.Id,
            SBQQ__Quantity__c       = 1,
            SBQQ__NetPrice__c       = 100,
            SBQQ__RequiredBy__c     = null,
            NATT_Is_Base_Unit__c    = true  // <-- required by your query
        );
        insert qlParent;

        SBQQ__QuoteLine__c qlChild1 = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c          = cloneQuote.Id,
            SBQQ__Product__c        = productc1.Id,
            SBQQ__PricebookEntryId__c = pbe.Id,
            SBQQ__Quantity__c       = 1,
            SBQQ__NetPrice__c       = 10,
            SBQQ__RequiredBy__c     = qlParent.Id
        );
        SBQQ__QuoteLine__c qlChild2 = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c          = cloneQuote.Id,
            SBQQ__Product__c        = productc1.Id,
            SBQQ__PricebookEntryId__c = pbe.Id,
            SBQQ__Quantity__c       = 1,
            SBQQ__NetPrice__c       = 20,
            SBQQ__RequiredBy__c     = qlParent.Id
        );
        insert new List<SBQQ__QuoteLine__c>{ qlChild1, qlChild2 };
          list<SBQQ__QuoteLine__c> qlList = [   SELECT Id, SBQQ__Quote__c, SBQQ__Quote__r.SBQQ__Source__c, NATT_Is_Base_Unit__c
                    FROM SBQQ__QuoteLine__c
                    WHERE SBQQ__Quote__c = :cloneQuote.Id];
        // Baseline counts on destination
        Decimal Source = [SELECT Direct_Sales_Units__c FROM SBQQ__Quote__c WHERE id = :SourceQuote.Id].Direct_Sales_Units__c;
        Decimal Clone = [SELECT Direct_Sales_Units__c FROM SBQQ__Quote__c WHERE id = :cloneQuote.Id ].Direct_Sales_Units__c;
        // 1) Clone from INPUT -> DEST (timesToAdd = 1)
        NATT_DirectSales_AddBundleOnParentQuote.Request r1 = new NATT_DirectSales_AddBundleOnParentQuote.Request();
        r1.QuoteId      = cloneQuote.Id;
        r1.SourceQuoteId = SourceQuote.Id;  // your class uses this as destination
        r1.timesToAdd   = 1;

        Test.startTest();
        List<NATT_DirectSales_AddBundleOnParentQuote.Result> res1 =
            NATT_DirectSales_AddBundleOnParentQuote.cloneOneBundleNtimes(
                new List<NATT_DirectSales_AddBundleOnParentQuote.Request>{ r1 }
            );
        Test.stopTest();
    }
    
        @IsTest
    static void test_clone_then_add_same_product_again2() {
       
 NATT_DirectSales_AddBundleOnParentQuote.Request r1 = new NATT_DirectSales_AddBundleOnParentQuote.Request();
        r1.QuoteId      = null;
        r1.SourceQuoteId = null;  // your class uses this as destination
        r1.timesToAdd   = 2;
        Test.startTest();
        List<NATT_DirectSales_AddBundleOnParentQuote.Result> res1 =
            NATT_DirectSales_AddBundleOnParentQuote.cloneOneBundleNtimes(
                new List<NATT_DirectSales_AddBundleOnParentQuote.Request>{ r1 }
            );
       
    }
        @IsTest
    static void test_clone_then_add_same_product_again3() {
        SBQQ__Quote__c cloneQuote = [SELECT Id,Direct_Sales_Units__c  FROM SBQQ__Quote__c where SBQQ__Source__c != null LIMIT 1];
        // Pick the other quote as destination
        SBQQ__Quote__c SourceQuote  = [SELECT Id,Direct_Sales_Units__c FROM SBQQ__Quote__c WHERE SBQQ__Source__c = null LIMIT 1];
         list<SBQQ__QuoteLine__c> qlList = [   SELECT Id, SBQQ__Quote__c, SBQQ__Quote__r.SBQQ__Source__c, NATT_Is_Base_Unit__c
                    FROM SBQQ__QuoteLine__c
                    WHERE SBQQ__Quote__c = :cloneQuote.Id OR  SBQQ__Quote__c = :SourceQuote.Id];
        delete qlList;
    NATT_DirectSales_AddBundleOnParentQuote.Request r1 = new NATT_DirectSales_AddBundleOnParentQuote.Request();
        r1.QuoteId      = cloneQuote.Id;
        r1.SourceQuoteId = SourceQuote.Id;  // your class uses this as destination
        r1.timesToAdd   = 2;
        Test.startTest();
        List<NATT_DirectSales_AddBundleOnParentQuote.Result> res1 =
            NATT_DirectSales_AddBundleOnParentQuote.cloneOneBundleNtimes(
                new List<NATT_DirectSales_AddBundleOnParentQuote.Request>{ r1 }
            );
       
    }

    @IsTest
    static void test_validation_guard_timesToAdd() {
        // Use any existing quote as both template and destination to hit guard
        SBQQ__Quote__c anyQuote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];

        NATT_DirectSales_AddBundleOnParentQuote.Request r = new NATT_DirectSales_AddBundleOnParentQuote.Request();
        r.QuoteId       = anyQuote.Id;
        r.SourceQuoteId = anyQuote.Id;
        r.timesToAdd    = 0; // invalid

        Test.startTest();
        List<NATT_DirectSales_AddBundleOnParentQuote.Result> res =
            NATT_DirectSales_AddBundleOnParentQuote.cloneOneBundleNtimes(
                new List<NATT_DirectSales_AddBundleOnParentQuote.Request>{ r }
            );
        Test.stopTest();

        System.assertEquals(1, res.size(), 'One result expected');
        System.assertEquals(false, res[0].IsSuccess, 'Should fail validation when timesToAdd <= 0');
        System.assert(res[0].Message != null && res[0].Message.contains('timesToAdd'),
            'Message should explain invalid timesToAdd');
    }
}