NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Dealer__c.field-meta.xml
<CustomField>
    <fullName>NATT_Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NATT</description>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Dealer Community Plus, Dealer Community Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Dealer_Principal__c.field-meta.xml
<CustomField>
    <fullName>NATT_Dealer_Principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dealer Principal of a NATT Account</description>
    <label>Dealer Principal</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.NATT_Key_Business_Role__c</field>
            <operation>equals</operation>
            <value>Principal</value>
        </filterItems>
        <infoMessage>The Dealer that you selected is not the Principal for Account</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Division__c.field-meta.xml
<CustomField>
    <fullName>NATT_Division__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Division</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_JDE_Parts_Bill_To_Code__c.field-meta.xml
<CustomField>
    <fullName>NATT_JDE_Parts_Bill_To_Code__c</fullName>
    <description>JDE Address number used for the PPG Parts Bill-To Account</description>
    <externalId>true</externalId>
    <label>JDE Parts Bill To Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Mailing_Address__c.field-meta.xml
<CustomField>
    <fullName>NATT_Mailing_Address__c</fullName>
    <description>NATT</description>
    <formula>IF(NATT_Address_Mailing__r.NATT_Street__c &lt;&gt; &quot;&quot;,NATT_Address_Mailing__r.NATT_Street__c + BR(),NULL) +
IF(NATT_Address_Mailing__r.NATT_City__c &lt;&gt; &quot;&quot;,NATT_Address_Mailing__r.NATT_City__c + &quot;, &quot;,NULL) +
TEXT(NATT_Address_Mailing__r.NATT_State_Province__c) + &quot; &quot; + NATT_Address_Mailing__r.NATT_Zip_Postal_Code__c + BR() +
TEXT(NATT_Address_Mailing__r.NATT_Country__c)</formula>
    <label>Mailing Address</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Parts_Account__c.field-meta.xml
<CustomField>
    <fullName>NATT_Parts_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT</description>
    <label>Parts Account</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Physical_Address__c.field-meta.xml
<CustomField>
    <fullName>NATT_Physical_Address__c</fullName>
    <description>NATT</description>
    <formula>IF(NATT_Address_Physical__r.NATT_Street__c &lt;&gt; &quot;&quot;,NATT_Address_Physical__r.NATT_Street__c + BR(),NULL) +
IF(NATT_Address_Physical__r.NATT_City__c &lt;&gt; &quot;&quot;,NATT_Address_Physical__r.NATT_City__c + &quot;, &quot;,NULL) +
TEXT(NATT_Address_Physical__r.NATT_State_Province__c) + &quot; &quot; + NATT_Address_Physical__r.NATT_Zip_Postal_Code__c + BR() +
TEXT(NATT_Address_Physical__r.NATT_Country__c)</formula>
    <label>Physical Address</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Primary_Location_Type__c.field-meta.xml
<CustomField>
    <fullName>NATT_Primary_Location_Type__c</fullName>
    <description>for NATT Dealers only</description>
    <label>Primary Location Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Dealer</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Associate</fullName>
            </value>
            <value>
                <fullName>Parts and Service</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Other/Auxiliary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/ContactPointAddress/fields/NATT_Address__c.field-meta.xml
<CustomField>
    <fullName>NATT_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the JDE Address record</description>
    <label>NATT Address</label>
    <referenceTo>NATT_Address__c</referenceTo>
    <relationshipLabel>Contact Point Addresses</relationshipLabel>
    <relationshipName>Contact_Point_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/NATT_Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>NATT Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/User/fields/NATT_Dealer__c.field-meta.xml
<CustomField>
    <fullName>NATT_Dealer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT</description>
    <label>Dealer</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/User/fields/NATT_Dealer_Principal__c.field-meta.xml
<CustomField>
    <fullName>NATT_Dealer_Principal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT</description>
    <label>Dealer Principal</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/Division.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Truck Trailer</fullName>
        <default>true</default>
        <label>Truck Trailer</label>
    </customValue>
    <customValue>
        <fullName>Container</fullName>
    </customValue>
    <customValue>
        <fullName>Passenger Rail</fullName>
    </customValue>
    <customValue>
        <fullName>Marine</fullName>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/NATT_AccountInformationHelper.cls
public with sharing class NATT_AccountInformationHelper {


    /*Query for Effective Acct for Acct Details, Addresses, Carts
    @AuraEnabled(cacheable=true)
    public static List <Account> grabEffectiveAccounts(String acctId){
        List <Account> accountList = [SELECT Name, NATT_Parts_Account__c, NATT_JDE_Parts_Bill_To_Code__c, NATT_Division__c, NATT_Primary_Location_Type__c, NATT_Dealer_Principal__c, NATT_Physical_Address__c, ShippingAddress, NATT_Dealer__c FROM Account WHERE Id = :acctId];
        return accountList;
    }*/

    //Query used to grab Effective Acct for Acct Details
    @AuraEnabled(cacheable=true)
    public static Account grabEffectiveAccount(String acctId){
        Account a = [SELECT Name, NATT_Parts_Account__c, NATT_JDE_Parts_Bill_To_Code__c, NATT_Division__c, NATT_Primary_Location_Type__c, NATT_Dealer_Principal__c, NATT_Physical_Address__c, ShippingAddress, NATT_Dealer__c FROM Account WHERE Id = :acctId];
        return a;
    }

    // //Old method used for grabbing Accounts via User instead of Effective Acct Id
    // @AuraEnabled(cacheable=true)
    // public static List <Account> grabAccounts(String userId){
    //     // List <Account> accountList2 = [SELECT Name, NATT_Parts_Account__c, NATT_JDE_Parts_Bill_To_Code__c, NATT_Division__c, NATT_Primary_Location_Type__c, NATT_Dealer_Principal__c, NATT_Physical_Address__c, ShippingAddress, NATT_Dealer__c FROM Account WHERE Id IN :acctIds];
    //     User userRecord = [SELECT ContactId FROM User WHERE Id = :userId];
    //     Contact userContact = [SELECT AccountId FROM Contact WHERE Id = :userRecord.ContactId];
    //     List <Account> accountList = [SELECT Name, NATT_Parts_Account__c, NATT_JDE_Parts_Bill_To_Code__c, NATT_Division__c, NATT_Primary_Location_Type__c, NATT_Dealer_Principal__c, NATT_Physical_Address__c, ShippingAddress, NATT_Dealer__c FROM Account WHERE Id = :userContact.AccountId];
    //     return accountList;
    // }

    @AuraEnabled
    public static List <ContactPointAddress> grabAddresses(String effAccountId){
        // List <Account> acctList = grabAccounts(userId);
        //SYstem.debug('Effective ACct Id: ' + effAccountId);
        //Account a  = grabEffectiveAccount(effAccountId);        
        List <ContactPointAddress> contactPointAddresses = [SELECT Id, Name, ParentId, Address, street, city, state, postalcode, country,NATT_Address__c FROM ContactPointAddress WHERE (NATT_Address__c = null) AND AddressType = 'Shipping' AND ParentId =:effAccountId];
        System.debug('contact point Addresses: ' + contactPointAddresses);
        return contactPointAddresses;
    }

    @AuraEnabled
    public static List <ContactPointAddress> grabJdeAddresses(String effAccountId){
        // List <Account> acctList = grabAccounts(userId);
        //List <Account> acctList = grabEffectiveAccount(userId);
        //List <Id> acctIds = new List <Id> ();
        //for (Account acct : acctList){
        //    acctIds.add(acct.Id);
        //}
        List <ContactPointAddress> contactPointAddresses = [SELECT Id, Name, ParentId, Address, street, city, state, postalcode, country,NATT_Address__c FROM ContactPointAddress WHERE (NATT_Address__c != null) AND AddressType = 'Shipping' AND ParentId =:effAccountId];
        return contactPointAddresses;
    }

    @AuraEnabled    
    public static boolean updateAddresses(List <ContactPointAddress> updatedAccountList) {    
        for (ContactPointAddress cpa : updatedAccountList){
            System.debug('ID VALUE : ' + cpa.id);
        }
        try {  
            update updatedAccountList;  
            return true;   
        } catch(Exception e) {  
            return false;      
        }   
    }  
    
    @AuraEnabled(cacheable=true)
    public static Account grabAccountDetails(String acctId){
        List<Account> accountList = [SELECT Name, NATT_Parts_Account__c, NATT_JDE_Parts_Bill_To_Code__c, NATT_Division__c, NATT_Primary_Location_Type__c, 
                                    NATT_Dealer_Principal__c, NATT_Physical_Address__c, NATT_Mailing_Address__c,NATT_Dealer_Principal__r.Email
                                    FROM Account  WHERE Id =:acctId];
        return accountList.isEmpty()? new Account():accountList.get(0);
    }

    @AuraEnabled
    public static void deleteAddress(ContactPointAddress conPointAddress){
        NATT_DeleteContactPointAddresses.deleteContactPointAddress(conPointAddress);
    } 

}