NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>NATT_Billing_Address__c</fullName>
    <formula>IF(NATT_Address_Billing__r.NATT_Street__c &lt;&gt; &quot;&quot;,NATT_Address_Billing__r.NATT_Street__c + BR(),NULL) +
IF(NATT_Address_Billing__r.NATT_City__c &lt;&gt; &quot;&quot;,NATT_Address_Billing__r.NATT_City__c + &quot;, &quot;,NULL) +
TEXT(NATT_Address_Billing__r.NATT_State_Province__c) + &quot; &quot; + NATT_Address_Billing__r.NATT_Zip_Postal_Code__c + BR() +
TEXT(NATT_Address_Billing__r.NATT_Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing Address</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>NATT End User/End Customer Accounts</description>
    <label>Customer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Accounts</description>
    <label>Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Contact/fields/NATT_AuthorizeDotNetProfileId__c.field-meta.xml
<CustomField>
    <fullName>NATT_AuthorizeDotNetProfileId__c</fullName>
    <description>Used to store the authorize.net profile Id created for a credit card transaction</description>
    <label>Authorize.net Profile Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/NATT_Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>NATT Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_Account__c.field-meta.xml
<CustomField>
    <fullName>NATT_Account__c</fullName>
    <description>NATT</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>NATT_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_Type__c.field-meta.xml
<CustomField>
    <fullName>NATT_Type__c</fullName>
    <description>NATT</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Dealer Agreement</fullName>
            </value>
            <value>
                <fullName>Distribution Centers</fullName>
            </value>
            <value>
                <fullName>Headquarters</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Other Mailing</fullName>
            </value>
            <value>
                <fullName>Parts Ship To</fullName>
            </value>
            <value>
                <fullName>Physical</fullName>
            </value>
            <value>
                <fullName>Regional Offices</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Units Ship To</fullName>
            </value>
            <value>
                <fullName>Bill To</fullName>
            </value>
            <value>
                <fullName>Ship To</fullName>
            </value>
            <value>
                <fullName>TES Ship To</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/recordTypes/NATT_Address.recordType-meta.xml
<RecordType>
    <fullName>NATT_Address</fullName>
    <active>true</active>
    <description>NATT</description>
    <label>NATT Address</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/NATT_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>NATT_Billing_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NATT Billing Address</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>NATT_Address__c.NATT_Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>NATT_Address__c.NATT_Type__c</field>
            <operation>equals</operation>
            <value>Billing</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>CTBR Units</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>NATT_Address__c</referenceTo>
    <relationshipLabel>Opportunities (NATT Billing Address)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/NATT_Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>NATT_Shipping_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NATT: only used to store the selected address when working with an opportunity to be passed to the Quote</description>
    <label>NATT Shipping Address</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>NATT_Address__c.NATT_Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>NATT_Address__c.NATT_Type__c</field>
            <operation>equals</operation>
            <value>Units Ship To</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>CTBR Units</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>NATT_Address__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/NATT_Stock__c.field-meta.xml
<CustomField>
    <fullName>NATT_Stock__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT users check this if there is no end customer</description>
    <label>Stock</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/recordTypes/NATT_Opportunity_Units.recordType-meta.xml
<RecordType>
    <fullName>NATT_Opportunity_Units</fullName>
    <active>true</active>
    <businessProcess>NATT Opportunity Units Sales Process</businessProcess>
    <description>NATT Opportunity Units Recordtype</description>
    <label>Units</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>NATT_Billing_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NATT Billing Address</label>
    <referenceTo>NATT_Address__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Payment_Instruction__c.field-meta.xml
<CustomField>
    <fullName>NATT_Payment_Instruction__c</fullName>
    <label>Payment Instruction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Wire Transfer</fullName>
            </value>
            <value>
                <fullName>Terms</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>NATT_Shipping_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NATT</description>
    <label>NATT Shipping Address</label>
    <referenceTo>NATT_Address__c</referenceTo>
    <relationshipLabel>Orders (NATT Shipping Address)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Stock__c.field-meta.xml
<CustomField>
    <fullName>NATT_Stock__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stock</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>NATT_Transaction_Id__c</fullName>
    <description>Used to hold the Authorize.net transaction Id if a CC payment is being used for the order.</description>
    <label>Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Transaction_Payment_Id__c.field-meta.xml
<CustomField>
    <fullName>NATT_Transaction_Payment_Id__c</fullName>
    <description>used to store the authorize.net payment method Id if using a CC.</description>
    <label>Transaction Payment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/recordTypes/NATT_Units_Order.recordType-meta.xml
<RecordType>
    <fullName>NATT_Units_Order</fullName>
    <active>true</active>
    <description>NATT Units Order</description>
    <label>NATT Units Order</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_AuthorizeDotNetProfileId__c.field-meta.xml
<CustomField>
    <fullName>NATT_AuthorizeDotNetProfileId__c</fullName>
    <formula>NATT_Order__r.Owner:User.Contact.NATT_AuthorizeDotNetProfileId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Authorize.net Profile Id</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_JdeInvoiceAmount__c.field-meta.xml
<CustomField>
    <fullName>NATT_JdeInvoiceAmount__c</fullName>
    <description>used to process the Credit Card amount when a shipment is created for TES(instead of the line rollup)</description>
    <label>JDE Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_Order__c.field-meta.xml
<CustomField>
    <fullName>NATT_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The order to which the shipment is related</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_PackingSlipNumber__c.field-meta.xml
<CustomField>
    <fullName>NATT_PackingSlipNumber__c</fullName>
    <description>Packing slip number of the shipment</description>
    <label>Packing Slip Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>NATT_Transaction_Id__c</fullName>
    <formula>IF(
				AND(TEXT(NATT_Order__r.NATT_Payment_Instruction__c)==&apos;Credit Card&apos;,NOT(ISBLANK(NATT_Order__r.NATT_Transaction_Id__c)))
				,NATT_Order__r.NATT_Transaction_Id__c,
				&apos;&apos;
  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Transaction Id</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Shipment/fields/NATT_Transaction_Payment_Id__c.field-meta.xml
<CustomField>
    <fullName>NATT_Transaction_Payment_Id__c</fullName>
    <formula>IF(
AND(TEXT(NATT_Order__r.NATT_Payment_Instruction__c)==&apos;Credit Card&apos;,NOT(ISBLANK(NATT_Order__r.NATT_Transaction_Payment_Id__c)))
,NATT_Order__r.NATT_Transaction_Payment_Id__c,
&apos;&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Transaction Payment Id</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/NattTesAuthorizeDotNetTest.cls
/**
 * Test Coverage for NattTesAuthorizeDotNet class
 */
@isTest
private class NattTesAuthorizeDotNetTest implements HttpCalloutMock {
    public HTTPResponse respond(HTTPRequest req) {
        // Create a fake response
        HttpResponse res = new HttpResponse();
        res.setHeader('Content-Type', 'application/json');
        res.setBody('{"customerProfileId":"1000177237","transactionRequest" : {"customer":{"id":"1000177237"}},"transactionResponse": {"profileResponse":{"customerProfileId": "1000177237"}, "responseCode": "1", "authCode": "HW617E", "avsResultCode": "Y", "cvvResultCode": "", "cavvResultCode": "", "transId": "2157047189", "refTransID": "", "transHash": "E7CEB0A9F1BECA32A02493E1B31D5955", "testRequest": "0", "accountNumber": "XXXX1111", "accountType": "Visa", "messages": [ { "code": "1", "description": "This transaction has been approved." } ], "transHashSha2": "D0C4FFF5648511A5862B917CFD9BB78ABF8A6E1D90C119CBBC4C0B454F4FF40DED15B204E042F36ECA5FB15D02588E4E4A7B85B94E7279599CE6020462CB7DEE", "SupplementalDataQualificationIndicator": 0, "networkTransId": "123456789NNNH" }, "messages": { "resultCode": "Ok", "message": [ { "code": "I00001", "text": "Successful." } ] }}');
        res.setStatusCode(200);
        return res;
    }
    @IsTest(SeeAllData=true) 
    static void nattTesAuthorize_Test(){
        Account a = new Account(Name='TestAccount');
        insert a;
        Contact contact = new Contact(LastName='TestContact', AccountId=a.Id, NATT_AuthorizeDotNetProfileId__c='123');
        insert contact;
        
        Profile profile1 = [SELECT Id FROM Profile WHERE Name='B2B Customer Community User' LIMIT 1];

        User shipUser = new User(Alias='ship', Email='buyer@example.com', LastName='Buyer',
                TimeZoneSidKey='GMT', LocaleSidKey='en_US', Username='buyer@example.com.carrier',
                EmailEncodingKey='UTF-8', ProfileId=profile1.Id, LanguageLocaleKey='en_US',
                ContactId=contact.Id);
        insert shipUser;

        //Variables to mimic CC input
        String email = 'test@test.com';
        String amount = '100';
        String cardNumber = '5555555555555555';
        String expirationDate = '';
        String cvv = '105';

        //Creation of required Order/Shipment information
        List<Account> aList = new List<Account>();
        alist.add(new Account(Name='Test Dealer',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()));
        aList.add(new Account(Name='Test Dealer2',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()));
        insert aList;
        
        List<NATT_Address__c> addList = new List<NATT_Address__c>();
        addList.add(new NATT_Address__c(NATT_Type__c='Billing',NATT_Account__c=aList.get(0).Id,RecordTypeId=Schema.SObjectType.NATT_Address__c.getRecordTypeInfosByDeveloperName().get('NATT_Address').getRecordTypeId()));
        addList.add(new NATT_Address__c(NATT_Type__c='Units Ship To',NATT_Account__c=aList.get(0).Id,RecordTypeId=Schema.SObjectType.NATT_Address__c.getRecordTypeInfosByDeveloperName().get('NATT_Address').getRecordTypeId()));
        insert addList;		
		
		List<Opportunity> oppList = new List<Opportunity>();
        oppList.add(new Opportunity(Name='UnitsTestOpp',CloseDate=Date.today().addDays(30),StageName='Qualification',AccountId=aList.get(0).Id,RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NATT_Opportunity_Units').getRecordTypeId(),NATT_Stock__c=true,NATT_Billing_Address__c=addList.get(0).Id,NATT_Shipping_Address__c=addList.get(1).Id));        
        insert oppList;
	        
        Test.setMock(HttpCalloutMock.class, new NattTesAuthorizeDotNetTest());
        Test.startTest();
        List<Order> orderList = new List<Order>();
        orderList.add(new Order(
            OwnerId = shipUser.Id,    
            NATT_Payment_Instruction__c='Credit Card', 
            AccountId=aList.get(0).Id,
            OpportunityId=oppList.get(0).Id,
            EffectiveDate=Date.today().addDays(3),
            Status='Draft',
            RecordTypeId=Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('NATT_Units_Order').getRecordTypeId(),
            NATT_Billing_Address__c=addList.get(0).Id,
            NATT_Shipping_Address__c=addList.get(1).Id,
            NATT_Transaction_Id__c = '40095530118',
            NATT_Transaction_Payment_Id__c = '555'));
        insert orderList;
        
        
        Product2 testProduct = new Product2(
        	Name = 'Product Test'        
        );
        
        insert testProduct;
        List<OrderItem> orderItemList = new List<OrderItem>();
        for (Integer i=0; i<200; i++){
            OrderItem testOrderItem = new OrderItem(
                OrderId = orderList[0].Id,
                LineNumber = i+1,
                Product2Id = testProduct.Id,
                Quantity = 4,
                UnitPrice = i+1,
                ListPrice = i+1
            );
            orderItemList.add(testOrderItem);
        }
        insert orderItemList;
        Shipment testShip = new Shipment(
        	ShipToName = 'test',
        	NATT_PackingSlipNumber__c = 345678,
            TrackingNumber = '12345',
            NATT_Order__c = orderList[0].Id,
            ExpectedDeliveryDate = System.today() + 1,
            NATT_JDEInvoiceAmount__c = 100
        );
        
        insert testShip;
        Set<Id> shipmentIdsSet = new Set<Id>();
        Shipment newShipment = [SELECT Id, NATT_Transaction_Id__c,NATT_JDEInvoiceAmount__c,NATT_AuthorizeDotNetProfileId__c,NATT_Transaction_Payment_Id__c FROM Shipment WHERE ShipToName = 'test' LIMIT 1];
        shipmentIdsSet.add(newShipment.Id);
        Test.stopTest();
        NattTesAuthorizeDotNet.AuthWrapper newAuth = NattTesAuthorizeDotNet.doAUth(email, amount, cardNumber, expirationDate, cvv);
        NattTesAuthorizeDotNet.processShipment(shipmentIdsSet);
        String paymentProfile = NattTesAuthorizeDotNet.buildCreateCustomerPaymentProfile('1',cardNumber,expirationDate,cvv);
    }

    @future
    private static void createUser(String cId){
        Profile profile = [SELECT Id FROM Profile WHERE Name='B2B Customer Community User' LIMIT 1];
        // Profile profile = [SELECT Id FROM Profile WHERE Name='NATT Full Access Community' LIMIT 1];
        User user = new User(Alias='buyer', Email='buyer@example.com', LastName='Buyer',
                TimeZoneSidKey='GMT', LocaleSidKey='en_US', Username='buyer@example.com.carrier',
                EmailEncodingKey='UTF-8', ProfileId=profile.Id, LanguageLocaleKey='en_US',
                ContactId=cId);
        insert user;
        
        List<PermissionSetAssignment> psaList = new List<PermissionSetAssignment>();
        for(PermissionSet ps : [SELECT Id FROM PermissionSet WHERE Name IN ('B2B_Commerce_Buyer','B2BBuyer')]){
            psaList.add(new PermissionSetAssignment(PermissionSetId = ps.Id, AssigneeId = user.Id));
        }
        insert psaList; 
    }
}