NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_City_State__c.field-meta.xml
<CustomField>
    <fullName>NATT_City_State__c</fullName>
    <formula>NATT_Address_Physical__r.NATT_City__c + 
IF(ISBLANK(NATT_Address_Physical__r.NATT_City__c),&quot;&quot;,&quot;/&quot;)
+  TEXT(NATT_Address_Physical__r.NATT_State_Province__c)</formula>
    <label>City/State</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Dealer_Principal__c.field-meta.xml
<CustomField>
    <fullName>NATT_Dealer_Principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dealer Principal of a NATT Account</description>
    <label>Dealer Principal</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.NATT_Key_Business_Role__c</field>
            <operation>equals</operation>
            <value>Principal</value>
        </filterItems>
        <infoMessage>The Dealer that you selected is not the Principal for Account</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Primary_Location_Type__c.field-meta.xml
<CustomField>
    <fullName>NATT_Primary_Location_Type__c</fullName>
    <description>for NATT Dealers only</description>
    <label>Primary Location Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Dealer</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Associate</fullName>
            </value>
            <value>
                <fullName>Parts and Service</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Other/Auxiliary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Status__c.field-meta.xml
<CustomField>
    <fullName>NATT_Status__c</fullName>
    <description>NATT</description>
    <label>NATT Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <isActive>false</isActive>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/NATT_ShowAccountHierarchyControllerTest.cls
@IsTest
public class NATT_ShowAccountHierarchyControllerTest {
    
    @TestSetup
    static void makeData(){
        
        Account currentAccount = NATT_DataFactory.createSimpleAccount();
        
        Account parentOneCurrentAccount = NATT_DataFactory.createSimpleAccount();
        
        currentAccount.ParentId = parentOneCurrentAccount.Id;
        Update currentAccount;
        
        Account brotherCurrentAccount = NATT_DataFactory.createSimpleAccount();
        brotherCurrentAccount.ParentId = parentOneCurrentAccount.Id;
        Update brotherCurrentAccount;
        
        Account childOneBrotherCurrentAccount = NATT_DataFactory.createSimpleAccount();
        childOneBrotherCurrentAccount.ParentId = brotherCurrentAccount.Id;
        Update childOneBrotherCurrentAccount;

        Account childCurrentAccount = NATT_DataFactory.createAccountWithParent(currentAccount.Id);
        
        Account parentTwoCurrentAccount = NATT_DataFactory.createSimpleAccount();        
        parentOneCurrentAccount.ParentId = parentTwoCurrentAccount.Id;
        Update parentOneCurrentAccount;
        
        Account parentThreeCurrentAccount = NATT_DataFactory.createSimpleAccount();        
        parentTwoCurrentAccount.ParentId = parentThreeCurrentAccount.Id;
        Update parentTwoCurrentAccount;
        
        Account parentFourCurrentAccount = NATT_DataFactory.createSimpleAccount();
        parentThreeCurrentAccount.ParentId = parentFourCurrentAccount.Id;
        Update parentThreeCurrentAccount;
        
        Account parentFiveCurrentAccount = NATT_DataFactory.createSimpleAccount();
        parentFourCurrentAccount.ParentId = parentFiveCurrentAccount.Id;
        Update parentFourCurrentAccount;
        
    }

    @IsTest
    static void getAccountHierarchyTest() {
        
        Account current = [SELECT Id, Name, NATT_City_State__c, NATT_Status__c, NATT_Dealer_Principal__r.Name, Owner.Name, NATT_Primary_Location_Type__c FROM Account ORDER BY CreatedDate ASC LIMIT 1];
        
        Test.startTest();
            Map<String, Object> mpReturn = NATT_ShowAccountHierarchyController.getAccountHierarchy(current.Id);
        	Map<String, Object> mpReturnError = NATT_ShowAccountHierarchyController.getAccountHierarchy(NULL);

            System.assertEquals(true, mpReturn.get('success'));
            System.assertEquals(true, mpReturn.get('data') != null);
        
        	System.assertEquals(false, mpReturnError.get('success'));        	
        Test.stopTest();
        
    }

    @IsTest
    static void fetchAccountHierarchyTest() {
        
        Account current = [SELECT Id, Name, NATT_City_State__c, NATT_Status__c, NATT_Dealer_Principal__r.Name, Owner.Name, NATT_Primary_Location_Type__c FROM Account ORDER BY CreatedDate ASC LIMIT 1];
        
        Test.startTest();
            System.assertEquals(true, !NATT_ShowAccountHierarchyController.fetchAccountHierarchy(current.Id).isEmpty());
        Test.stopTest();
        
    }

    @IsTest
    static void getAccountHierarchyObjectTest() {
        
        Account accCurrent = [SELECT Id, Name, NATT_City_State__c, NATT_Status__c, NATT_Dealer_Principal__r.Name, Owner.Name, NATT_Primary_Location_Type__c FROM Account ORDER BY CreatedDate ASC LIMIT 1];
        
        Test.startTest();
        	NATT_ShowAccountHierarchyController.AccountHierarchy accountHierarchy = NATT_ShowAccountHierarchyController.getAccountHierarchyObject(accCurrent, true, '', null);
        	System.assertEquals(accountHierarchy.name, accCurrent.name);
			System.assert(accountHierarchy.isCurrent);        
        Test.stopTest();
        
    }

    @IsTest
    static void buildMapChildrenByFatherTest() {
        
        Account current = [SELECT Id, Name FROM Account ORDER BY CreatedDate ASC LIMIT 1];
        
        List<Account> ltChilds = [SELECT Id, Name, NATT_City_State__c, NATT_Status__c, NATT_Dealer_Principal__r.Name, Owner.Name, NATT_Primary_Location_Type__c FROM Account WHERE ParentId =: current.Id];
        
        Account stepSon = NATT_DataFactory.createAccountWithParent(ltChilds.get(0).Id);
        
        Set<Id> stChildIds = (new Map<Id,Account>(ltChilds)).keySet().clone();
        
        Test.startTest();
            Map<Id, List<Account>> mpChildsByFather = NATT_ShowAccountHierarchyController.buildMapChildrenByFather(stChildIds);
        	System.assert(!mpChildsByFather.get(ltChilds.get(0).Id).isEmpty());
        Test.stopTest();
        
    }

    @IsTest
    static void getNewChildsTest() {
        
        Account current = [SELECT Id, Name, NATT_City_State__c, NATT_Status__c, NATT_Dealer_Principal__r.Name, Owner.Name, NATT_Primary_Location_Type__c FROM Account ORDER BY CreatedDate ASC LIMIT 1];
        current.Name = 'Account For Test Updated';
        
        Update current;
        
        Test.startTest();
            Map<String, Object> mpReturn = NATT_ShowAccountHierarchyController.getNewChildren(current.Name);
        	System.assertEquals(true, mpReturn.get('success'));
        	System.assert(mpReturn.get('data') != null);
        Test.stopTest();
        
    }

}