NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Organization__c.field-meta.xml
<CustomField>
    <fullName>NATT_Organization__c</fullName>
    <description>NATT</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Geography</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <description>NATT</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Accounts</description>
    <label>Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/NATT_Approval_Process__c/NATT_Approval_Process__c.object-meta.xml
<CustomObject>
    <label>NATT Approval Process</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>NATT Approval Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NATT Approval Process</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_Approval_Process__c/fields/Approval_Object__c.field-meta.xml
<CustomField>
    <fullName>Approval_Object__c</fullName>
    <label>Approval Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SBQQ__Quote__c</fullName>
                <label>Quote</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Approval_Process__c/fields/Business_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Sub_Type__c</fullName>
    <label>Business Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Units Quote</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>BluEdge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Approval_Process__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NATT</fullName>
            </value>
            <value>
                <fullName>CTM</fullName>
            </value>
            <value>
                <fullName>CTBR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Approval_Process__c/fields/Margin_DOS_Lower_Bound__c.field-meta.xml
<CustomField>
    <fullName>Margin_DOS_Lower_Bound__c</fullName>
    <label>Margin %  DOS Lower Bound</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Approval_Process__c/fields/Margin_EAM_Lower_Bound__c.field-meta.xml
<CustomField>
    <fullName>Margin_EAM_Lower_Bound__c</fullName>
    <label>Margin % EAM Lower Bound</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Approval_Process__c/fields/Margin_RD_Lower_Bound__c.field-meta.xml
<CustomField>
    <fullName>Margin_RD_Lower_Bound__c</fullName>
    <label>Margin % RD Lower Bound</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Approval_Process__c/fields/Margin_Sales_Ops_Lower_Bound__c.field-meta.xml
<CustomField>
    <fullName>Margin_Sales_Ops_Lower_Bound__c</fullName>
    <label>Margin %  Sales Ops Lower Bound</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Approval_Process__c/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <formula>TEXT(Product_Name__r.NATT_Unit__c)</formula>
    <label>NATT Unit</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Approval_Process__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <formula>TEXT(Product_Name__r.Family)</formula>
    <label>Product Family</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Approval_Process__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>NATT Approval Process</relationshipLabel>
    <relationshipName>NATT_Approval_Process</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <formula>TEXT(Account.NATT_Region__c)</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/NATT_Stock__c.field-meta.xml
<CustomField>
    <fullName>NATT_Stock__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT users check this if there is no end customer</description>
    <label>Stock</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <description>NATT for reports</description>
    <formula>TEXT(SBQQ__PrimaryQuote__r.NATT_Unit__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/recordTypes/NATT_Opportunity_Units.recordType-meta.xml
<RecordType>
    <fullName>NATT_Opportunity_Units</fullName>
    <active>true</active>
    <businessProcess>NATT Opportunity Units Sales Process</businessProcess>
    <description>NATT Opportunity Units Recordtype</description>
    <label>Units</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <description>for quoting NATT Units</description>
    <label>Unit NATT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Unit</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <description>for eSolutions quotes only</description>
    <formula>TEXT(SBQQ__Account__r.NATT_Region__c)</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Stock__c.field-meta.xml
<CustomField>
    <fullName>NATT_Stock__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT users check this if there is no end customer</description>
    <label>Stock</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <description>NATT Unit selected for this quote</description>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Product_Family__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>NATT_Unit</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <description>for quoting NATT units in CPQ</description>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Unit</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Discount__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Discount__c</fullName>
    <description>Additional customer discount extended for this line item expressed in terms of percentage.</description>
    <inlineHelpText>Additional customer discount extended to this line item expressed in form of a percentage.</inlineHelpText>
    <label>Additional Disc. (%)</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/Geography.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NATT</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>CTB</fullName>
    </customValue>
    <customValue>
        <fullName>Need the others listed</fullName>
        <isActive>false</isActive>
        <label>Need the others listed</label>
    </customValue>
    <masterLabel>Geography</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>200INT ComfortPro Integrated APU</fullName>
    </customValue>
    <customValue>
        <fullName>210STA ComfortPro Stand-alone APU</fullName>
    </customValue>
    <customValue>
        <fullName>220PWR ComfortPro Power-only APU</fullName>
    </customValue>
    <customValue>
        <fullName>230SKY ComfortPro ClearSky DPF APU</fullName>
    </customValue>
    <customValue>
        <fullName>240EPS ComfortPro Electric APU</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S6 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S7 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S8 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S9 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>20X Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>30S Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>30S with 115v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>30S with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>35X Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>35X with 115v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>35X with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>35X with 230v-3ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>40X with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>40XR with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>50X with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>50XR Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>50XR with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>50XR with 230v-3ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>Neos 100S - Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>Solara APX</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8100</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8500</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 01</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 02</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 03</fullName>
    </customValue>
    <description>for quoting in cpq for NATT</description>
    <masterLabel>NATT Unit</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>East</fullName>
    </customValue>
    <customValue>
        <fullName>West</fullName>
    </customValue>
    <customValue>
        <fullName>South</fullName>
    </customValue>
    <customValue>
        <fullName>Central</fullName>
    </customValue>
    <customValue>
        <fullName>National</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Latin America</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Region 1</fullName>
    </customValue>
    <customValue>
        <fullName>Region 2</fullName>
    </customValue>
    <customValue>
        <fullName>Region 3</fullName>
    </customValue>
    <customValue>
        <fullName>Northeast</fullName>
    </customValue>
    <customValue>
        <fullName>Southeast</fullName>
    </customValue>
    <customValue>
        <fullName>Midwest</fullName>
    </customValue>
    <customValue>
        <fullName>North</fullName>
    </customValue>
    <customValue>
        <fullName>Europe, Middle East and Africa</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pacific and Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>Americas</fullName>
        <isActive>false</isActive>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>undefined</fullName>
        <isActive>false</isActive>
        <label>undefined</label>
    </customValue>
    <customValue>
        <fullName>Asia</fullName>
        <isActive>false</isActive>
        <label>Asia</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/QuoteTriggerUnitsApproverHandlerTest.cls
@IsTest
public class QuoteTriggerUnitsApproverHandlerTest {
    @TestSetup static void setupData(){
        List<Pricebook2> pbList = new List<Pricebook2>();
        pbList.add(new Pricebook2(Name='NATT Units Price Book',IsActive=true));
        insert pbList;
         List<Product2> product2List = new List<Product2>();
        Product2 prod = new Product2(
            Name='Vector 8600 - System 01',
            ProductCode='Vector 8600 - System 01',
            Family = 'Trailer'
        );
        product2List.add(prod);
        insert product2List;
       List<PricebookEntry> pbeList = new List<PricebookEntry>();

// Create the standard price entry
PricebookEntry standardPbe = new PricebookEntry(
    Pricebook2Id = Test.getStandardPricebookId(),
    Product2Id = product2List[0].Id,
    UnitPrice = 5000001,
    IsActive = true
);
        
        // Add the standard price entry to the list
        pbeList.add(standardPbe);
        
        // Create the custom price entry
        PricebookEntry customPbe = new PricebookEntry(
            Pricebook2Id = pbList[0].Id,
            Product2Id = product2List[0].Id,
            UnitPrice = 5000009,
            IsActive = true
        );
        
        // Add the custom price entry to the list
        pbeList.add(customPbe);
        
        // Insert the list of price book entries
        insert pbeList;
        

        list<account> accList = new  List<account>(); 
        Account a = new Account(Name='Test Dealer',
                                RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId(),
                                NATT_Organization__c = 'NATT',
                                NATT_Region__c = 'East');
        accList.add(a);
        database.insert(accList);
        List<Opportunity> oppList = new List<Opportunity>();
        oppList.add(new Opportunity(Name='TestUnitsOpp',CloseDate=Date.today().addDays(30),StageName='Qualification',AccountId=a.Id,RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NATT_Opportunity_Units').getRecordTypeId(),NATT_Stock__c=true));
        insert oppList;
    }
    // Added by Rajasekhar for CCRN:2631
    @isTest static void myUnitTest1(){
        Account a = [SELECT Id FROM Account WHERE Name='Test Dealer'];
        NattQuoteCon.Wrapper w = NattQuoteCon.getData(a.Id);
        string qteRecTypeID = Schema.SobjectType.SBQQ__Quote__c.getRecordTypeInfosByDeveloperName().get('MX_Units_Quote').getRecordTypeId();
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name='TestUnitsOpp'];
        opp = NattQuoteCon.getOppData(opp.Id);  
        string QuoteJSON = '{"SBQQ__Status__c":"Draft"}';
        //string QuoteJSON = '{"MarkForCountry": "US","MarkForState": "TX","MarkForCity": "rythu","poNumber": "123","hasFreight":true, "RecordypeId":'+qteRecTypeID +'}';
        
        NattQuoteCon.createQuote(opp.Id,true,QuoteJSON);
        
        Pricebook2 pb = [Select Id From Pricebook2 Where Name = 'NATT Units Price Book'];
        
        //List<PriceBookEntry> pbes = [Select Id,Product2Id From PriceBookEntry Where PriceBook2Id =:pb.Id];
        
        // insert quote lines
        List<SBQQ__QuoteLine__c> quoteLineList = new List<SBQQ__QuoteLine__c>();
        SBQQ__Quote__c quoteRec = [select id,SBQQ__Status__c from SBQQ__Quote__c where SBQQ__Status__c = 'Draft' and SBQQ__Opportunity2__c =:opp.Id limit 1 ];
        
        List<Product2> product2List = [select id from Product2 where ProductCode='Vector 8600 - System 01'];
        
        //SBQQ__QuoteLine__c quoteLine = TestUtil.createQuoteLine(pbes[0].product2List.id, quoteRec.Id);
        
        SBQQ__QuoteLine__c quoteLine = TestUtil.createQuoteLine(product2List[0].id, quoteRec.Id);
        quoteLine.SBQQ__Product__c = product2List[0].id;
        quoteLine.SBQQ__Discount__c = 80;
        quoteLineList.add(quoteLine);
        upsert quoteLine;
        NATT_Approval_Process__c approvalProcess = new NATT_Approval_Process__c(
            //Name = 'AP-0000',
            Product_Name__c = product2List[0].id,
            //Product_Family__c = 'Trailer',
            Approval_Object__c = 'SBQQ__Quote__c',
            Business_Type__c = 'NATT',
            Business_Sub_Type__c = 'Units Quote',
            Margin_EAM_Lower_Bound__c = 100,
            Margin_RD_Lower_Bound__c = 36,
            Margin_DOS_Lower_Bound__c = 35,
            Margin_Sales_Ops_Lower_Bound__c = 0
        );
        insert approvalProcess;
        
        quoteRec.NATT_Unit__c='Vector 8600 - System 01';
        
        try{
            update quoteRec;
        }
        
        catch(exception e){
            system.debug('Error-'+ e);
        }
        quoteRec.SBQQ__Status__c='Pending Approval';
        try{
            update quoteRec;
        }
        
        catch(exception e){
            system.debug('Error-'+ e);
        }
    }
    
     @isTest static void justCoverage(){
         QuoteTriggerUnitsApproverHandler.justCoverage();
     }
}