NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Dealer_Principal__c.field-meta.xml
<CustomField>
    <fullName>NATT_Dealer_Principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dealer Principal of a NATT Account</description>
    <label>Dealer Principal</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.NATT_Key_Business_Role__c</field>
            <operation>equals</operation>
            <value>Principal</value>
        </filterItems>
        <infoMessage>The Dealer that you selected is not the Principal for Account</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Status__c.field-meta.xml
<CustomField>
    <fullName>NATT_Status__c</fullName>
    <description>NATT</description>
    <label>NATT Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <isActive>false</isActive>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Accounts</description>
    <label>Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Contact/fields/NATT_Key_Business_Role__c.field-meta.xml
<CustomField>
    <fullName>NATT_Key_Business_Role__c</fullName>
    <description>NATT</description>
    <label>Key Business Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Co-Principal</fullName>
            </value>
            <value>
                <fullName>VP/Director</fullName>
            </value>
            <value>
                <fullName>VP/Director - Sales</fullName>
            </value>
            <value>
                <fullName>VP/Director - Parts</fullName>
            </value>
            <value>
                <fullName>VP/Director - Service</fullName>
            </value>
            <value>
                <fullName>VP/Director – Parts &amp; Service</fullName>
            </value>
            <value>
                <fullName>General Manager</fullName>
            </value>
            <value>
                <fullName>Branch Manager</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Service Manager</fullName>
            </value>
            <value>
                <fullName>Parts Manager</fullName>
            </value>
            <value>
                <fullName>Warranty Manager</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>Unit Sales Person</fullName>
            </value>
            <value>
                <fullName>Parts Sales Person</fullName>
            </value>
            <value>
                <fullName>Technician</fullName>
            </value>
            <value>
                <fullName>Warranty Admin</fullName>
            </value>
            <value>
                <fullName>Billing Admin</fullName>
            </value>
            <value>
                <fullName>General Admin</fullName>
            </value>
            <value>
                <fullName>Corporate Officer</fullName>
            </value>
            <value>
                <fullName>Director General</fullName>
            </value>
            <value>
                <fullName>Subdirector</fullName>
            </value>
            <value>
                <fullName>Vice-Presidente/Director</fullName>
            </value>
            <value>
                <fullName>Gerente General</fullName>
            </value>
            <value>
                <fullName>Gerente de Sucursal</fullName>
            </value>
            <value>
                <fullName>Gerente de Ventas</fullName>
            </value>
            <value>
                <fullName>Gerente de Servicio</fullName>
            </value>
            <value>
                <fullName>Gerente de Partes</fullName>
            </value>
            <value>
                <fullName>Gerente de Garantías</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Contact/recordTypes/NATT_Dealer.recordType-meta.xml
<RecordType>
    <fullName>NATT_Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Contacts</description>
    <label>NATT Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/NATT_Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>NATT Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_Account__c.field-meta.xml
<CustomField>
    <fullName>NATT_Account__c</fullName>
    <description>NATT</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>NATT_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_City__c.field-meta.xml
<CustomField>
    <fullName>NATT_City__c</fullName>
    <description>NATT</description>
    <label>City</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_Country__c.field-meta.xml
<CustomField>
    <fullName>NATT_Country__c</fullName>
    <description>NATT</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Country_Picklist</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_JDE_Alpha_Name__c.field-meta.xml
<CustomField>
    <fullName>NATT_JDE_Alpha_Name__c</fullName>
    <label>JDE Alpha Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_State_Province__c.field-meta.xml
<CustomField>
    <fullName>NATT_State_Province__c</fullName>
    <description>NATT</description>
    <label>State/Province</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>NATT_State_Picklist</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/fields/NATT_Type__c.field-meta.xml
<CustomField>
    <fullName>NATT_Type__c</fullName>
    <description>NATT</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Dealer Agreement</fullName>
            </value>
            <value>
                <fullName>Distribution Centers</fullName>
            </value>
            <value>
                <fullName>Headquarters</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Other Mailing</fullName>
            </value>
            <value>
                <fullName>Parts Ship To</fullName>
            </value>
            <value>
                <fullName>Physical</fullName>
            </value>
            <value>
                <fullName>Regional Offices</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Units Ship To</fullName>
            </value>
            <value>
                <fullName>Bill To</fullName>
            </value>
            <value>
                <fullName>Ship To</fullName>
            </value>
            <value>
                <fullName>TES Ship To</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Address__c/recordTypes/NATT_Address.recordType-meta.xml
<RecordType>
    <fullName>NATT_Address</fullName>
    <active>true</active>
    <description>NATT</description>
    <label>NATT Address</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/NATT_Alert__c/NATT_Alert__c.object-meta.xml
<CustomObject>
    <label>NATT Alert</label>
    <nameField>
        <label>NATT Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NATT Alerts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_Alert__c/fields/NATT_AlertText__c.field-meta.xml
<CustomField>
    <fullName>NATT_AlertText__c</fullName>
    <label>Alert</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Alert__c/fields/NATT_End_Date__c.field-meta.xml
<CustomField>
    <fullName>NATT_End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Alert__c/fields/NATT_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>NATT_Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>NATT_Order_Status__c</fullName>
    <description>NATT</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enter Order (Default Value)</fullName>
            </value>
            <value>
                <fullName>Sabrix Run</fullName>
            </value>
            <value>
                <fullName>Fulfillment Run</fullName>
            </value>
            <value>
                <fullName>Order Acknowledge</fullName>
            </value>
            <value>
                <fullName>Release Order for Shipment</fullName>
            </value>
            <value>
                <fullName>Credit Check for Shipment</fullName>
            </value>
            <value>
                <fullName>Ready to Print Pick Slip</fullName>
            </value>
            <value>
                <fullName>Ready for Picking</fullName>
            </value>
            <value>
                <fullName>Ready for Shipping</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Sabrix</fullName>
            </value>
            <value>
                <fullName>Invoicing</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Not Shipped</fullName>
            </value>
            <value>
                <fullName>Partially Shipped</fullName>
            </value>
            <value>
                <fullName>Awaiting Pricing</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Approval</fullName>
            </value>
            <value>
                <fullName>Customer Approved</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>No Enviado</fullName>
            </value>
            <value>
                <fullName>Envío parcial</fullName>
            </value>
            <value>
                <fullName>Completo</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/NATT_DataFactory.cls
public with sharing class NATT_DataFactory {
    
    // ACCOUNT METHODS
    public static Account createSimpleAccount() {
        Account newAccount = new Account(
            Name = 'Account For Test',
            NATT_Status__c = NATT_Constants.ACCOUNT_ACTIVE
        );        
        Insert newAccount;
        
        Contact dealerPrincipal = createSimpleContact(newAccount.Id);
        newAccount.NATT_Dealer_Principal__c = dealerPrincipal.Id;
        
        return newAccount;
    }
    
    public static Account createAccountWithParent(String parentId) {
        if (parentId == null) {
            Account parentAccount = createSimpleAccount();
            Insert parentAccount;
            
            parentId = parentAccount.Id;
        }
        
        Account newAccount = new Account(Name = 'Account With Parent For Test', ParentId = parentId, NATT_Status__c = NATT_Constants.ACCOUNT_ACTIVE);        
        Insert newAccount;
        
        Contact dealerPrincipal = createSimpleContact(newAccount.Id);
        
        newAccount.NATT_Dealer_Principal__c = dealerPrincipal.Id;
        update newAccount;
        
        return newAccount;
    }
    
    public static Account createAccountWithName(String name) {
        Account newAccount = new Account(
            Name = name,
            NATT_Status__c = NATT_Constants.ACCOUNT_ACTIVE
        );        
        Insert newAccount;
        
        Contact dealerPrincipal = createSimpleContact(newAccount.Id);
        newAccount.NATT_Dealer_Principal__c = dealerPrincipal.Id;
        
        return newAccount;
    }
    
    // CONTACT METHODS
    
    public static Contact createSimpleContact(Id accId) {
        Contact ctc = new Contact(
            LastName = 'Contact For Test',
            NATT_Key_Business_Role__c = 'Principal',
            AccountId = accId
        );
        
        Insert ctc;
        return ctc;
    }
    
    // NATT ADDRESS METHODS
    
    public static NATT_Address__c createNATTAddress(Account acc, String type, String jdeAlpha) {
        NATT_Address__c addr = new NATT_Address__c();
        
        addr.Name = 'NATT Address Test';
        addr.NATT_Account__c = acc.Id;
        addr.NATT_Country__c = 'US';
        addr.NATT_City__c = 'Almada';
        addr.NATT_State_Province__c = 'AL';
        addr.NATT_JDE_Alpha_Name__c =  String.isNotBlank(jdeAlpha) ? jdeAlpha : '';
        addr.NATT_Type__c = type;
        addr.recordTypeId = Schema.SObjectType.NATT_Address__c.getRecordTypeInfosByDeveloperName().get('NATT_Address').getRecordTypeId();
        
        Insert addr;
        return addr;
    }
    
    // NATT ALERTS METHODS
    
    public static NATT_Alert__c createNATTAlert() {
        NATT_Alert__c obj = new NATT_Alert__c();
        
        Date today = System.today();
        
        obj.Name = 'NATT Alert Test';
        obj.NATT_AlertText__c = 'Alert text';
        obj.NATT_Start_Date__c = today;
        obj.NATT_End_Date__c = today.addDays(7);
        
        Insert obj;
        return obj;
    }
    
    // ORDER METHODS
    
    /*public static Order createSimpleOrder() {
        Order newOrder = new Order(
            Name = 'Order Test 1',
            NATT_Order_Status__c = NATT_Constants.ORDER_STATUS_COMPLETE_OR_CANCELLED.get(0),
            RecordTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get(NATT_Constants.ORDER_NATT_UNIT_RT).getRecordTypeId(),
            EffectiveDate = System.today(),
            OrderedDate = System.today().addDays(5),
            AccountId = createSimpleAccount().Id,
            Status = 'Draft'
        );
        
        Insert newOrder;
        return newOrder;
    }
    
    public static Order createOrderWithValues(Map<String, Object> params) {
        Order newOrder = new Order(
            Name = 'Order Test 1',
            NATT_Order_Status__c = String.valueOf(params.get('NATT_Order_Status__c')),
            RecordTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get(NATT_Constants.ORDER_NATT_UNIT_RT).getRecordTypeId(),
            EffectiveDate = System.today(),
            OrderedDate = Date.valueOf(params.get('OrderedDate')),
            AccountId = String.valueOf(params.get('AccountId')),
            OrderReferenceNumber = String.valueOf(params.get('OrderReferenceNumber')),
            PoNumber = String.valueOf(params.get('PoNumber')),
            Status = 'Draft'
        );
        
        Insert newOrder;
        return newOrder;
    } */
    
    //DS
    public static Account accRecord(){
        Id dealerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId();          
        Account acc = new Account(
            Name = 'Test Account1',
            recordTypeID = dealerRecordTypeId,
            AccountNumber = '4578');
        
        return acc;
    }
    
    public static Contact conRecord(string accID){
        
        Id RECTYPE_NATT_DEALER = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('NATT_Dealer').getRecordTypeId();        
        Contact con = new Contact(
            firstName = 'TestContact',
            lastName = 'Con',
            recordTypeId = RECTYPE_NATT_DEALER,
            accountID = accID);
        
        return con;
    }
}