NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Customer_Price_Group__c.field-meta.xml
<CustomField>
    <fullName>NATT_Customer_Price_Group__c</fullName>
    <description>PPG Price List to which the account is assigned</description>
    <label>Customer Price Group</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Organization__c.field-meta.xml
<CustomField>
    <fullName>NATT_Organization__c</fullName>
    <description>NATT</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Geography</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <description>NATT</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Accounts</description>
    <label>Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/globalValueSets/Geography.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NATT</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>CTB</fullName>
    </customValue>
    <customValue>
        <fullName>Need the others listed</fullName>
        <isActive>false</isActive>
        <label>Need the others listed</label>
    </customValue>
    <masterLabel>Geography</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>East</fullName>
    </customValue>
    <customValue>
        <fullName>West</fullName>
    </customValue>
    <customValue>
        <fullName>South</fullName>
    </customValue>
    <customValue>
        <fullName>Central</fullName>
    </customValue>
    <customValue>
        <fullName>National</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Latin America</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Region 1</fullName>
    </customValue>
    <customValue>
        <fullName>Region 2</fullName>
    </customValue>
    <customValue>
        <fullName>Region 3</fullName>
    </customValue>
    <customValue>
        <fullName>Northeast</fullName>
    </customValue>
    <customValue>
        <fullName>Southeast</fullName>
    </customValue>
    <customValue>
        <fullName>Midwest</fullName>
    </customValue>
    <customValue>
        <fullName>North</fullName>
    </customValue>
    <customValue>
        <fullName>Europe, Middle East and Africa</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pacific and Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>Americas</fullName>
        <isActive>false</isActive>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>undefined</fullName>
        <isActive>false</isActive>
        <label>undefined</label>
    </customValue>
    <customValue>
        <fullName>Asia</fullName>
        <isActive>false</isActive>
        <label>Asia</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/Natt_Case_Queue_Email_Notification_Test.cls
@IsTest
public class Natt_Case_Queue_Email_Notification_Test {
    
    @Istest
    public static void crateCase(){
        try{
            Contact cnt = new contact();
            User communityUser = new user();
            User thisUser = new User(Id = UserInfo.getUserId());
            id UserRoleid = [SELECT Id FROM UserRole WHERE Name = 'NA Units Manager' LIMIT 1 ].Id;
            thisUser.UserRoleId = UserRoleid;
            System.runAs(thisUser) {
                update thisUser;
                Account acc = new Account(
                    Name='Test Dealer Natt',
                    NATT_Customer_Price_Group__c='BCO',
                    NATT_Organization__c = 'NATT',
                    NATT_Region__c = 'East',
                    //IsPartner = true,
                    RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()
                );
                insert acc;
                cnt=NAC_TestDataFactory.insertAssociatedContact(acc);
                Profile profile = [SELECT Id FROM Profile WHERE Name='NATT Parts and Service Community' LIMIT 1];
                
                communityUser = new User(Alias='CTMComm', Email='buyer@example.com', LastName='Buyer',
                                         TimeZoneSidKey='GMT', LocaleSidKey='en_US', Username= 'CTMCommunityUser321'+'@example.com',
                                         EmailEncodingKey='UTF-8', ProfileId=profile.Id, LanguageLocaleKey='en_US',
                                         ContactId=cnt.Id);
                insert communityUser;
            }
            system.runAs(communityUser){
                Test.startTest();
                Case cs = new Case();
                cs.Status = 'New';
                cs.Type = 'Information';
                cs.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('CTM Performance Parts').getRecordTypeId();
                insert cs;
                Test.stopTest();
            } 
        }
        catch(exception e ){
            system.debug(e.getlinenumber()+' -  '+ e);
        }
        
    }
     @Istest
    public static void getQueueMemberslist(){
        try{
            test.startTest();
            Group testGroup = new Group();
            testGroup.Name = 'testGroup';
            testGroup.DeveloperName = 'ABC';
            testGroup.type = 'Queue';
            insert testGroup;
            Natt_Case_Queue_Email_Notification.getQueueMemberslist(new set<Id>{testGroup.Id});
            test.stopTest();
        }
        catch(exception e){
            
        }
    }
}