NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Dealer__c.field-meta.xml
<CustomField>
    <fullName>NATT_Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NATT</description>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Dealer Community Plus, Dealer Community Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Dealership__c.field-meta.xml
<CustomField>
    <fullName>NATT_Dealership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For End Customer RT&apos;s. This is the dealer the End Customer belongs to.</description>
    <label>Dealership</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer, Direct Sale, CTM Dealer, CTBR Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Organization__c.field-meta.xml
<CustomField>
    <fullName>NATT_Organization__c</fullName>
    <description>NATT</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Geography</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <description>NATT</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>NATT End User/End Customer Accounts</description>
    <label>Customer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Accounts</description>
    <label>Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>NATT Internal Customer Accounts</description>
    <label>Internal</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/NATT_Product_Dealer_Type__c/NATT_Product_Dealer_Type__c.object-meta.xml
<CustomObject>
    <description>Used with NATT Dealers to show the dealer type per product</description>
    <label>Product Dealer Type</label>
    <nameField>
        <displayFormat>PDT-{000000}</displayFormat>
        <label>Product Dealer Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Dealer Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_Product_Dealer_Type__c/fields/NATT_Dealer__c.field-meta.xml
<CustomField>
    <fullName>NATT_Dealer__c</fullName>
    <description>For NATT Dealer Accounts to classify Dealers</description>
    <label>Dealer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Dealer Types</relationshipLabel>
    <relationshipName>Product_Dealer_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Product_Dealer_Type__c/fields/NATT_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>NATT_Product_Type__c</fullName>
    <description>NATT - to classify dealers</description>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Truck</fullName>
            </value>
            <value>
                <fullName>Trailer</fullName>
            </value>
            <value>
                <fullName>Special Products</fullName>
            </value>
            <value>
                <fullName>Electric Trailer</fullName>
            </value>
            <value>
                <fullName>Electric Truck</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/NATT_Product_Family__c.field-meta.xml
<CustomField>
    <fullName>NATT_Product_Family__c</fullName>
    <description>NATT</description>
    <formula>TEXT(SBQQ__PrimaryQuote__r.NATT_Product_Family__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Family</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <formula>TEXT(Account.NATT_Region__c)</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/NATT_Stock__c.field-meta.xml
<CustomField>
    <fullName>NATT_Stock__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT users check this if there is no end customer</description>
    <label>Stock</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <description>NATT for reports</description>
    <formula>TEXT(SBQQ__PrimaryQuote__r.NATT_Unit__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Opportunity/recordTypes/NATT_Opportunity_BluEdge.recordType-meta.xml
<RecordType>
    <fullName>NATT_Opportunity_BluEdge</fullName>
    <active>true</active>
    <businessProcess>NATT Opportunity Units Sales Process</businessProcess>
    <description>For BluEdge Aftermarket and Extension Quotes</description>
    <label>BluEdge</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Opportunity/recordTypes/NATT_Opportunity_eSolutions.recordType-meta.xml
<RecordType>
    <fullName>NATT_Opportunity_eSolutions</fullName>
    <active>true</active>
    <businessProcess>NATT Opportunity Units Sales Process</businessProcess>
    <description>For Lynx Fleet Quotes</description>
    <label>Lynx Fleet</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Opportunity/recordTypes/NATT_Opportunity_Units.recordType-meta.xml
<RecordType>
    <fullName>NATT_Opportunity_Units</fullName>
    <active>true</active>
    <businessProcess>NATT Opportunity Units Sales Process</businessProcess>
    <description>NATT Opportunity Units Recordtype</description>
    <label>Units</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <description>for quoting NATT Units</description>
    <label>Unit NATT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Unit</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Product_Family__c.field-meta.xml
<CustomField>
    <fullName>NATT_Product_Family__c</fullName>
    <description>NATT</description>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Product_Family</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <description>for eSolutions quotes only</description>
    <formula>TEXT(SBQQ__Account__r.NATT_Region__c)</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Stock__c.field-meta.xml
<CustomField>
    <fullName>NATT_Stock__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NATT users check this if there is no end customer</description>
    <label>Stock</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <description>NATT Unit selected for this quote</description>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Product_Family__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>NATT_Unit</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <description>for quoting NATT units in CPQ</description>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Unit</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/Geography.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NATT</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>CTB</fullName>
    </customValue>
    <customValue>
        <fullName>Need the others listed</fullName>
        <isActive>false</isActive>
        <label>Need the others listed</label>
    </customValue>
    <masterLabel>Geography</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Trailer</fullName>
    </customValue>
    <customValue>
        <fullName>Diesel Truck</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Drive</fullName>
    </customValue>
    <customValue>
        <fullName>APU</fullName>
    </customValue>
    <customValue>
        <fullName>Solara</fullName>
    </customValue>
    <customValue>
        <fullName>Electric Truck</fullName>
    </customValue>
    <customValue>
        <fullName>Electric Trailer</fullName>
        <isActive>false</isActive>
        <label>Electric Trailer</label>
    </customValue>
    <customValue>
        <fullName>DD Truck</fullName>
        <isActive>false</isActive>
        <label>DD Truck</label>
    </customValue>
    <masterLabel>NATT Product Family</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>200INT ComfortPro Integrated APU</fullName>
    </customValue>
    <customValue>
        <fullName>210STA ComfortPro Stand-alone APU</fullName>
    </customValue>
    <customValue>
        <fullName>220PWR ComfortPro Power-only APU</fullName>
    </customValue>
    <customValue>
        <fullName>230SKY ComfortPro ClearSky DPF APU</fullName>
    </customValue>
    <customValue>
        <fullName>240EPS ComfortPro Electric APU</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S6 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S7 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S8 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S9 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>20X Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>30S Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>30S with 115v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>30S with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>35X Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>35X with 115v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>35X with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>35X with 230v-3ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>40X with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>40XR with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>50X with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>50XR Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>50XR with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>50XR with 230v-3ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>Neos 100S - Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>Solara APX</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8100</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8500</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 01</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 02</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 03</fullName>
    </customValue>
    <customValue>
        <fullName>X4 7700</fullName>
    </customValue>
    <description>for quoting in cpq for NATT</description>
    <masterLabel>NATT Unit</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>East</fullName>
    </customValue>
    <customValue>
        <fullName>West</fullName>
    </customValue>
    <customValue>
        <fullName>South</fullName>
    </customValue>
    <customValue>
        <fullName>Central</fullName>
    </customValue>
    <customValue>
        <fullName>National</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Latin America</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Region 1</fullName>
    </customValue>
    <customValue>
        <fullName>Region 2</fullName>
    </customValue>
    <customValue>
        <fullName>Region 3</fullName>
    </customValue>
    <customValue>
        <fullName>Northeast</fullName>
    </customValue>
    <customValue>
        <fullName>Southeast</fullName>
    </customValue>
    <customValue>
        <fullName>Midwest</fullName>
    </customValue>
    <customValue>
        <fullName>North</fullName>
    </customValue>
    <customValue>
        <fullName>Europe, Middle East and Africa</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pacific and Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>Americas</fullName>
        <isActive>false</isActive>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>undefined</fullName>
        <isActive>false</isActive>
        <label>undefined</label>
    </customValue>
    <customValue>
        <fullName>Asia</fullName>
        <isActive>false</isActive>
        <label>Asia</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/GlobalProductSearchPluginTest.cls
@isTest(seeAllData=false)
public class GlobalProductSearchPluginTest{
    
    @testSetup
    static void testSetup(){
        List<Pricebook2> pbList = new List<Pricebook2>();
        pbList.add(new Pricebook2(Name='NATT Units Price Book',IsActive=true));
        pbList.add(new Pricebook2(Name='NATT Parts Price Book',IsActive=true));
        pbList.add(new Pricebook2(Name='NATT BluEdge',IsActive=true));
        pbList.add(new Pricebook2(Name='NATT Lynx FLeet',IsActive=true));
        insert pbList;
        
        // insert products
        List<Product2> products = new List<Product2>();
        
        Product2 product1 = TestUtil.createProduct('BluEdge (See Options for Price)','BluEdge');
        products.add(product1);
        
        Product2 product2 = TestUtil.createProduct('BluEdge Core','BluEdge Core');
        products.add(product2);
        
        Product2 product3 = TestUtil.createProduct('Extended Basic Coverage','Extended Basic Coverage');
        products.add(product3);
        
        Product2 product4 = TestUtil.createProduct('Extended Basic','APU-T0011');
        products.add(product4);
        
        Product2 product5 = TestUtil.createProduct('OTCC for Extended Basic','APU-T0240');
        products.add(product5);
        
        Product2 product6 = TestUtil.createProduct('Major Component Coverage','Major Component Coverage');
        products.add(product6);
        
        Product2 product7 = TestUtil.createProduct('Engine less accessories','APU-T0020');
        products.add(product7);
        
        Product2 product8 = TestUtil.createProduct('Compressor less accessories','APU-T0030');
        products.add(product8);
        Product2 product9 = TestUtil.createProduct('X4 7700','APU-T0040');
        products.add(product9);
        
        insert products;
        
        // get standard price book id
        Id pricebookId = Test.getStandardPricebookId();
        
        // insert price book entries
        List<PriceBookEntry> pBEs = new List<PriceBookEntry>();
        PriceBookEntry pBE1 = TestUtil.createPriceBookEntry(pricebookId, products[0].Id);
        PriceBookEntry pBE2 = TestUtil.createPriceBookEntry(pricebookId, products[1].Id);
        PriceBookEntry pBE3 = TestUtil.createPriceBookEntry(pricebookId, products[2].Id);
        PriceBookEntry pBE4 = TestUtil.createPriceBookEntry(pricebookId, products[3].Id);
        PriceBookEntry pBE5 = TestUtil.createPriceBookEntry(pricebookId, products[4].Id);
        PriceBookEntry pBE6 = TestUtil.createPriceBookEntry(pricebookId, products[5].Id);
        PriceBookEntry pBE7 = TestUtil.createPriceBookEntry(pricebookId, products[6].Id);
        PriceBookEntry pBE8 = TestUtil.createPriceBookEntry(pricebookId, products[7].Id);
        pBEs.add(pBE1);
        pBEs.add(pBE2);
        pBEs.add(pBE3);
        pBEs.add(pBE4);
        pBEs.add(pBE5);
        pBEs.add(pBE6);
        pBEs.add(pBE7);
        pBEs.add(pBE8);
        
        PriceBookEntry pBE9 = TestUtil.createPriceBookEntry(pbList[0].Id, products[0].Id);
        PriceBookEntry pBE10 = TestUtil.createPriceBookEntry(pbList[1].Id, products[0].Id);
        PriceBookEntry pBE11 = TestUtil.createPriceBookEntry(pbList[2].Id, products[0].Id);
        PriceBookEntry pBE12 = TestUtil.createPriceBookEntry(pbList[3].Id, products[0].Id);
        pBEs.add(pBE9);
        pBEs.add(pBE10);
        pBEs.add(pBE11);
        pBEs.add(pBE12);        
        
        PriceBookEntry pBE13 = TestUtil.createPriceBookEntry(pbList[0].Id, products[1].Id);
        PriceBookEntry pBE14 = TestUtil.createPriceBookEntry(pbList[1].Id, products[1].Id);
        PriceBookEntry pBE15 = TestUtil.createPriceBookEntry(pbList[2].Id, products[1].Id);
        PriceBookEntry pBE16 = TestUtil.createPriceBookEntry(pbList[3].Id, products[1].Id);
        pBEs.add(pBE13);
        pBEs.add(pBE14);
        pBEs.add(pBE15);
        pBEs.add(pBE16);
        
        PriceBookEntry pBE17 = TestUtil.createPriceBookEntry(pbList[0].Id, products[2].Id);
        PriceBookEntry pBE18 = TestUtil.createPriceBookEntry(pbList[1].Id, products[2].Id);
        PriceBookEntry pBE19 = TestUtil.createPriceBookEntry(pbList[2].Id, products[2].Id);
        PriceBookEntry pBE20 = TestUtil.createPriceBookEntry(pbList[3].Id, products[2].Id);
        pBEs.add(pBE17);
        pBEs.add(pBE18);
        pBEs.add(pBE19);
        pBEs.add(pBE20);
        
        PriceBookEntry pBE21 = TestUtil.createPriceBookEntry(pbList[0].Id, products[3].Id);
        PriceBookEntry pBE22 = TestUtil.createPriceBookEntry(pbList[1].Id, products[3].Id);
        PriceBookEntry pBE23 = TestUtil.createPriceBookEntry(pbList[2].Id, products[3].Id);
        PriceBookEntry pBE24 = TestUtil.createPriceBookEntry(pbList[3].Id, products[3].Id);
        pBEs.add(pBE21);
        pBEs.add(pBE22);
        pBEs.add(pBE23);
        pBEs.add(pBE24);
        
        PriceBookEntry pBE25 = TestUtil.createPriceBookEntry(pbList[0].Id, products[4].Id);
        PriceBookEntry pBE26 = TestUtil.createPriceBookEntry(pbList[1].Id, products[4].Id);
        PriceBookEntry pBE27 = TestUtil.createPriceBookEntry(pbList[2].Id, products[4].Id);
        PriceBookEntry pBE28 = TestUtil.createPriceBookEntry(pbList[3].Id, products[4].Id);
        pBEs.add(pBE25);
        pBEs.add(pBE26);
        pBEs.add(pBE27);
        pBEs.add(pBE28);
        
        PriceBookEntry pBE29 = TestUtil.createPriceBookEntry(pbList[0].Id, products[5].Id);
        PriceBookEntry pBE30 = TestUtil.createPriceBookEntry(pbList[1].Id, products[5].Id);
        PriceBookEntry pBE31 = TestUtil.createPriceBookEntry(pbList[2].Id, products[5].Id);
        PriceBookEntry pBE32 = TestUtil.createPriceBookEntry(pbList[3].Id, products[5].Id);
        pBEs.add(pBE29);
        pBEs.add(pBE30);
        pBEs.add(pBE31);
        pBEs.add(pBE32);
        
        System.debug('pBEs'+pBEs);
        insert pBEs;
        
        List<Account> aList = new List<Account>();
        alist.add(new Account(Name='Test Dealer',NATT_Organization__c = 'NATT',NATT_Region__c = 'East',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()));
        aList.add(new Account(Name='Test Internal',NATT_Organization__c = 'NATT',NATT_Region__c = 'East',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Internal').getRecordTypeId()));
        aList.add(new Account(Name='Customer',NATT_Organization__c = 'NATT',NATT_Region__c = 'East',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId()));
        
        insert aList;
        
        // assignes dealership to end customer
        aList[1].NATT_Dealership__c = aList.get(0).Id;
        
        // assignes dealership to end customer
        aList[2].NATT_Dealership__c = aList.get(0).Id;
        
        update aList[2];
        
        List<AccountTeamMember> atmList = new List<AccountTeamMember>();
        atmList.add(new AccountTeamMember(AccountId=aList.get(0).Id,UserId=UserInfo.getUserId(),TeamMemberRole='EAM - NATT'));
        atmList.add(new AccountTeamMember(AccountId=aList.get(0).Id,UserId=UserInfo.getUserId(),TeamMemberRole='RD - NATT'));
        atmList.add(new AccountTeamMember(AccountId=aList.get(0).Id,UserId=UserInfo.getUserId(),TeamMemberRole='Director of Sales - NATT'));
        insert atmList;
        
        List<Opportunity> oppList = new List<Opportunity>();
        oppList.add(new Opportunity(Name='UnitsTestOpp',CloseDate=Date.today().addDays(30),StageName='Qualification',AccountId=aList.get(0).Id,RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NATT_Opportunity_Units').getRecordTypeId(),NATT_Stock__c=true));
        oppList.add(new Opportunity(Name='UnitsTestOppInternal',CloseDate=Date.today().addDays(30),StageName='Qualification',AccountId=aList.get(1).Id,RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NATT_Opportunity_Units').getRecordTypeId(),NATT_Stock__c=true));
        oppList.add(new Opportunity(Name='BluEdgeTestOpp',CloseDate=Date.today().addDays(30),StageName='Qualification',AccountId=aList.get(0).Id,RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NATT_Opportunity_BluEdge').getRecordTypeId(),NATT_Stock__c=true));
        oppList.add(new Opportunity(Name='eSolutionsOpp',CloseDate=Date.today().addDays(30),StageName='Qualification',AccountId=aList.get(1).Id,RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NATT_Opportunity_eSolutions').getRecordTypeId(),NATT_Stock__c=true));
        insert oppList;
    }
    
    @isTest static void searchScenario(){
        
        Account a = [SELECT Id FROM Account WHERE Name='Test Dealer'];
        NattQuoteCon.Wrapper w = NattQuoteCon.getData(a.Id);
        
        Opportunity opp = [SELECT Id,RecordType.DeveloperName FROM Opportunity WHERE Name='UnitsTestOpp'];
        System.debug('Opp RecordType.DeveloperName:'+opp.RecordType.DeveloperName);
        opp = NattQuoteCon.getOppData(opp.Id);
        string QuoteJSON = '{}';
        Id quoteId = NattQuoteCon.createQuote(opp.Id,true,QuoteJSON);
        System.debug('quoteId:'+quoteId);
        SBQQ__Quote__c dbQuote = new SBQQ__Quote__c(Id=quoteId,NATT_Product_Family__c='Trailer',
                                                    NATT_Unit__c='X4 7700');
        update dbQuote;
        //System.debug('dbQuote RecordType.DeveloperName:'+dbQuote.RecordType.DeveloperName);
        //string productname=[Select NATT_Unit__c  from SBQQ__Quote__c where Id=:quoteId].NATT_Unit__c;
        //System.debug('productname:'+productname);
        Product2 pr=[Select id,Family from Product2 where Name ='X4 7700' LIMIT 1];
        pr.Family='Trailer';
        update pr;
        SBQQ__QuoteLine__c qline= new SBQQ__QuoteLine__c();
        qline.SBQQ__Quote__c=quoteId;
        qline.SBQQ__Product__c=pr.Id;
       /// qline.SBQQ__ProductFamily__c='Trailer';
        insert qline;
        SBQQ__Quote__c dbQuote2 = new SBQQ__Quote__c(Id=quoteId,
                                                    SBQQ__Status__c='Pending Approval');
       // update dbQuote2;
        
        List<String> fieldList = new List<String>(SBQQ__Quote__c.sObjectType.getDescribe().fields.getMap().keySet());
        
        String fields = String.join(fieldList,','); 
        
        SBQQ__Quote__c quote = Database.query('SELECT ' + fields + ' FROM SBQQ__Quote__c WHERE Id = :quoteId');        
        
        // instance
        GlobalProductSearchPlugin gp = new GlobalProductSearchPlugin();
        
        // default filter 
        gp.isFilterHidden(quote,'');
        
        // default filter values
        gp.getFilterDefaultValue(quote,'');
        
        NATT_Product_Dealer_Type__c dt1 = new NATT_Product_Dealer_Type__c(NATT_Dealer__c = a.Id,NATT_Product_Type__c = 'Truck');
        insert dt1;
        runSearch(gp,quote);
        NATT_Product_Dealer_Type__c dt2 = new NATT_Product_Dealer_Type__c(NATT_Dealer__c = a.Id,NATT_Product_Type__c = 'Trailer');
        insert dt2;
        runSearch(gp,quote);
        NATT_Product_Dealer_Type__c dt3 = new NATT_Product_Dealer_Type__c(NATT_Dealer__c = a.Id,NATT_Product_Type__c = 'Electric Trailer');
        insert dt3;
        runSearch(gp,quote);
        NATT_Product_Dealer_Type__c dt4 = new NATT_Product_Dealer_Type__c(NATT_Dealer__c = a.Id,NATT_Product_Type__c = 'Special Products');
        insert dt4;
        runSearch(gp,quote);
        NATT_Product_Dealer_Type__c dt5 = new NATT_Product_Dealer_Type__c(NATT_Dealer__c = a.Id,NATT_Product_Type__c = 'Electric Truck');
        insert dt5;
        runSearch(gp,quote);
    }
        
    public static void runSearch(GlobalProductSearchPlugin gp,SBQQ__Quote__c quote){
        Map<String,Object> fieldValuesMap = new Map<String,Object>();
        gp.isSearchCustom(quote,fieldValuesMap);
        
        gp.isSuggestCustom(quote,fieldValuesMap);
        
        gp.isInputHidden(quote,'Name');
        
        gp.getInputDefaultValue(quote,'');
                
        gp.getAdditionalSuggestFilters(quote,fieldValuesMap);
        
        gp.getAdditionalSearchFilters(quote,fieldValuesMap);
        
        gp.search(quote,fieldValuesMap);       
        
        gp.suggest(quote,fieldValuesMap);      
    }
}