NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Organization__c.field-meta.xml
<CustomField>
    <fullName>NATT_Organization__c</fullName>
    <description>NATT</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Geography</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/fields/NATT_Region__c.field-meta.xml
<CustomField>
    <fullName>NATT_Region__c</fullName>
    <description>NATT</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Accounts</description>
    <label>Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/Contact/fields/NATT_Key_Business_Role__c.field-meta.xml
<CustomField>
    <fullName>NATT_Key_Business_Role__c</fullName>
    <description>NATT</description>
    <label>Key Business Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Co-Principal</fullName>
            </value>
            <value>
                <fullName>VP/Director</fullName>
            </value>
            <value>
                <fullName>VP/Director - Sales</fullName>
            </value>
            <value>
                <fullName>VP/Director - Parts</fullName>
            </value>
            <value>
                <fullName>VP/Director - Service</fullName>
            </value>
            <value>
                <fullName>VP/Director – Parts &amp; Service</fullName>
            </value>
            <value>
                <fullName>General Manager</fullName>
            </value>
            <value>
                <fullName>Branch Manager</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Service Manager</fullName>
            </value>
            <value>
                <fullName>Parts Manager</fullName>
            </value>
            <value>
                <fullName>Warranty Manager</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>Unit Sales Person</fullName>
            </value>
            <value>
                <fullName>Parts Sales Person</fullName>
            </value>
            <value>
                <fullName>Technician</fullName>
            </value>
            <value>
                <fullName>Warranty Admin</fullName>
            </value>
            <value>
                <fullName>Billing Admin</fullName>
            </value>
            <value>
                <fullName>General Admin</fullName>
            </value>
            <value>
                <fullName>Corporate Officer</fullName>
            </value>
            <value>
                <fullName>Director General</fullName>
            </value>
            <value>
                <fullName>Subdirector</fullName>
            </value>
            <value>
                <fullName>Vice-Presidente/Director</fullName>
            </value>
            <value>
                <fullName>Gerente General</fullName>
            </value>
            <value>
                <fullName>Gerente de Sucursal</fullName>
            </value>
            <value>
                <fullName>Gerente de Ventas</fullName>
            </value>
            <value>
                <fullName>Gerente de Servicio</fullName>
            </value>
            <value>
                <fullName>Gerente de Partes</fullName>
            </value>
            <value>
                <fullName>Gerente de Garantías</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Contact/recordTypes/NATT_Dealer.recordType-meta.xml
<RecordType>
    <fullName>NATT_Dealer</fullName>
    <active>true</active>
    <description>NATT Dealer Contacts</description>
    <label>NATT Dealer</label>
</RecordType>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/NATT_ItemPriceStaging__c.object-meta.xml
<CustomObject>
    <description>Staging object for imported PartsNet item pricing from JDE (RCGWEB23 &amp; RCGWEB26). Includes standard list prices, customer-specific item prices, and quantity price tiers</description>
    <label>NATT Item Price Staging</label>
    <nameField>
        <displayFormat>IPS-{0000000000}</displayFormat>
        <label>NATT Item Price Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NATT Item Price Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_CustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>NATT_CustomerNumber__c</fullName>
    <description>Customer number this adjustment record applies to. If NULL the record is not customer specifc</description>
    <label>Customer Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_CustomerPriceGroup__c.field-meta.xml
<CustomField>
    <fullName>NATT_CustomerPriceGroup__c</fullName>
    <description>Specifies the customer price group</description>
    <label>Customer Price Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_EffectiveDate__c</fullName>
    <description>Date this price becomes effective</description>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>NATT_ExpiryDate__c</fullName>
    <description>Date this price expires and no longer applies</description>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_ItemPriceType__c.field-meta.xml
<CustomField>
    <fullName>NATT_ItemPriceType__c</fullName>
    <description>Alphanumeric code indicating the type of price (i.e. SRP - Standard Retail Price, INTPRC - Internal Price)</description>
    <label>Item Price Type</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_ListPrice__c.field-meta.xml
<CustomField>
    <fullName>NATT_ListPrice__c</fullName>
    <description>Contains either the list price, standard cost or Customer Item price as indicated by value in Item Price Type field</description>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_Product__c.field-meta.xml
<CustomField>
    <fullName>NATT_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>NATT Item Price Staging</relationshipLabel>
    <relationshipName>NATT_Item_Price_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_ItemPriceStaging__c/fields/NATT_QuantityFrom__c.field-meta.xml
<CustomField>
    <fullName>NATT_QuantityFrom__c</fullName>
    <description>Specifies the quantity at which this price applies.</description>
    <label>Quantity From</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/Geography.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NATT</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>CTB</fullName>
    </customValue>
    <customValue>
        <fullName>Need the others listed</fullName>
        <isActive>false</isActive>
        <label>Need the others listed</label>
    </customValue>
    <masterLabel>Geography</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>East</fullName>
    </customValue>
    <customValue>
        <fullName>West</fullName>
    </customValue>
    <customValue>
        <fullName>South</fullName>
    </customValue>
    <customValue>
        <fullName>Central</fullName>
    </customValue>
    <customValue>
        <fullName>National</fullName>
    </customValue>
    <customValue>
        <fullName>LAO</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Latin America</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Region 1</fullName>
    </customValue>
    <customValue>
        <fullName>Region 2</fullName>
    </customValue>
    <customValue>
        <fullName>Region 3</fullName>
    </customValue>
    <customValue>
        <fullName>Northeast</fullName>
    </customValue>
    <customValue>
        <fullName>Southeast</fullName>
    </customValue>
    <customValue>
        <fullName>Midwest</fullName>
    </customValue>
    <customValue>
        <fullName>North</fullName>
    </customValue>
    <customValue>
        <fullName>Europe, Middle East and Africa</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pacific and Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>Americas</fullName>
        <isActive>false</isActive>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>undefined</fullName>
        <isActive>false</isActive>
        <label>undefined</label>
    </customValue>
    <customValue>
        <fullName>Asia</fullName>
        <isActive>false</isActive>
        <label>Asia</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/NattBatchItemPriceTest.cls
@isTest
public class NattBatchItemPriceTest {
    
   
    
    @TestSetup
    static void setupTestData() {
        Pricebook2 standardPB = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        update standardPB;
        
        Pricebook2 pb2 = new Pricebook2(Name='Performance Parts Price Book', IsActive=true);
        insert pb2;
        
        Pricebook2 tesPb2 = new Pricebook2(Name='TES Storefront Pricebook', IsActive=true);
        insert tesPb2;
        
        CommerceEntitlementPolicy cep = new CommerceEntitlementPolicy(Name='All Access for TES Store', CanViewPrice=true, CanViewProduct=true);
        insert cep;

        Account a = new Account(
            Name='Test',
            NATT_Organization__c = 'NATT',
            NATT_Region__c = 'East',
            RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()
        );
        insert a;

        Contact c = new Contact(
            AccountId=a.Id,
            FirstName='Test',
            LastName='User',
            NATT_Key_Business_Role__c='Principal',
            RecordTypeId=Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('NATT_Dealer').getRecordTypeId()
        );
        insert c;

        BuyerGroup testBuyerGroup = new BuyerGroup(
            Name = '1'
        );
        insert testBuyerGroup;
        
        Product2 testProduct = new Product2(
            Name = 'Test Product 1',
            IsActive = true       
        );
        insert testProduct;

        Id standardPbId = Test.getStandardPricebookId();

        PricebookEntry testPricebookEntry = new PricebookEntry (
            Pricebook2Id = standardPbId,    
            Product2Id = testProduct.Id,
            UnitPrice = 1000,
            IsActive = true
        );
        insert testPricebookEntry;

        testPricebookEntry = new PricebookEntry (
            Pricebook2Id = tesPb2.Id,    
            Product2Id = testProduct.Id,
            UnitPrice = 1000,
            IsActive = true
        );
        insert testPricebookEntry;
        
        CommerceEntitlementProduct ceproduct = new CommerceEntitlementProduct(PolicyId=cep.Id, ProductId=testProduct.Id);
        insert ceproduct;
        
        Pricebook2 customPricebook = new Pricebook2 (
            Name = '1',
            isActive = true
        );
        insert customPricebook;

        BuyerGroupPricebook testBuyerGroupPricebook = new BuyerGroupPriceBook (
            BuyerGroupId = testBuyerGroup.Id,
            Pricebook2Id = customPricebook.Id
        );
        insert testBuyerGroupPricebook;

        PricebookEntry customPricebookEntry = new PricebookEntry(
            Pricebook2Id = customPricebook.Id,
            Product2Id = testProduct.Id,
            UnitPrice = 1000,
            isActive = true
        );
        insert customPricebookEntry;
    }

    @isTest
    static void testBatchNattItemPriceStaging() {
        BuyerGroup testBuyerGroup = [SELECT ID, Name FROM BuyerGroup LIMIT 1 FOR UPDATE];
        Product2 testProduct = [SELECT ID FROM Product2 LIMIT 1 FOR UPDATE];

        List<NATT_ItemPriceStaging__c> ipsList = new List<NATT_ItemPriceStaging__c>();
        ipsList.add(new NATT_ItemPriceStaging__c (
            NATT_ItemPriceType__c = 'SRP',   
            NATT_CustomerPriceGroup__c = testBuyerGroup.Id,
            NATT_CustomerNumber__c = 0,
            NATT_QuantityFrom__c = 1,
            NATT_EffectiveDate__c = Date.today() - 1,
            NATT_ExpiryDate__c = Date.today() + 10,           
            NATT_Product__c = testProduct.Id,
            NATT_ListPrice__c = 1995,
            RecordTypeId = Schema.SObjectType.NATT_ItemPriceStaging__c.getRecordTypeInfosByDeveloperName().get('NATT_PPG').getRecordTypeId()
        ));
        ipsList.add(new NATT_ItemPriceStaging__c (
            NATT_ItemPriceType__c = 'TINT',   
            NATT_CustomerPriceGroup__c = testBuyerGroup.Id,
            NATT_CustomerNumber__c = 0,
            NATT_QuantityFrom__c = 1,
            NATT_EffectiveDate__c = Date.today() - 1,
            NATT_ExpiryDate__c = Date.today() + 10,           
            NATT_Product__c = testProduct.Id,
            NATT_ListPrice__c = 1995,
            RecordTypeId = Schema.SObjectType.NATT_ItemPriceStaging__c.getRecordTypeInfosByDeveloperName().get('NATT_PPG').getRecordTypeId()
        ));
        insert ipsList;

        List<PriceBookEntry> pBEntryBefore = [SELECT Id, Name, Pricebook2Id, Product2Id, UnitPrice FROM PricebookEntry WHERE UnitPrice = 1995];

        Test.startTest();
        NattBatchItemPrice batchPrice = new NattBatchItemPrice();
        Database.executeBatch(batchPrice);
        Test.stopTest();

        List<PriceBookEntry> pBEntryAfter = [SELECT Id, Name, Pricebook2Id, Product2Id, UnitPrice FROM PricebookEntry WHERE UnitPrice = 1995];

        System.assertEquals(false, pBEntryBefore.size() > 0, 'A Pricebook Entry with Unit Price = 1995 should not exist yet.');
        for (PricebookEntry pbEntry : pBEntryAfter) {
            System.assertEquals(1995, pbEntry.UnitPrice, 'A Pricebook Entry with Unit Price = 1995 should have been queried after the batch ran.');
        }
    }
    
    @isTest
    static void testSchedule() {
        Test.startTest();
        NattBatchItemPrice bip = new NattBatchItemPrice();
        String sch = '0 0 4 ? * * *';        
        String cronId = System.schedule('Testing Schedule', sch, bip);
        CronTrigger ct = [SELECT Id, TimesTriggered, NextFireTime FROM CronTrigger WHERE Id = :cronId];
        System.assertEquals(0, ct.TimesTriggered);
        Test.stopTest(); 
    }
    
    @isTest
    static void testSendMessage() {
        NattBatchItemPrice batchInstance = new NattBatchItemPrice();
        List<String> errorMessages = new List<String>();
        errorMessages.add('Error 1: Sample error message 1');
        errorMessages.add('Error 2: Sample error message 2');
        
        Test.startTest();
        batchInstance.sendMessage(errorMessages);
        Test.stopTest();
    }

}