NATTQA-ENV/force-app/main/default/objects/Case/fields/CTM_Case_Reason__c.field-meta.xml
<CustomField>
    <fullName>CTM_Case_Reason__c</fullName>
    <description>Reason that the Case is being created (for CTM)</description>
    <inlineHelpText>Reason that the Case is being created</inlineHelpText>
    <label>CTM Case Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Management Issues</fullName>
            </value>
            <value>
                <fullName>Alarm</fullName>
            </value>
            <value>
                <fullName>Annual Returns</fullName>
            </value>
            <value>
                <fullName>Application Issue</fullName>
            </value>
            <value>
                <fullName>Availability</fullName>
            </value>
            <value>
                <fullName>Back Order</fullName>
            </value>
            <value>
                <fullName>Cancellations</fullName>
            </value>
            <value>
                <fullName>Claim Rejection or Appeals</fullName>
            </value>
            <value>
                <fullName>Claim Update</fullName>
            </value>
            <value>
                <fullName>Commissioning Issues</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Concealed Damage</fullName>
            </value>
            <value>
                <fullName>Concession Request</fullName>
            </value>
            <value>
                <fullName>Contract Issues</fullName>
            </value>
            <value>
                <fullName>Core Return</fullName>
            </value>
            <value>
                <fullName>Coverage Information</fullName>
            </value>
            <value>
                <fullName>Credit Memos</fullName>
            </value>
            <value>
                <fullName>Credits</fullName>
            </value>
            <value>
                <fullName>Customer Ordered in Error</fullName>
            </value>
            <value>
                <fullName>Damages</fullName>
            </value>
            <value>
                <fullName>Defective Shelf</fullName>
            </value>
            <value>
                <fullName>Direct Ship Overage</fullName>
            </value>
            <value>
                <fullName>Direct Ship Shortage</fullName>
            </value>
            <value>
                <fullName>Electrical Standby</fullName>
            </value>
            <value>
                <fullName>Engine Authorization Request</fullName>
            </value>
            <value>
                <fullName>Expedite - unit down/emergency orders</fullName>
            </value>
            <value>
                <fullName>Freight Charge/Surcharge</fullName>
            </value>
            <value>
                <fullName>Freight Company Complaints</fullName>
            </value>
            <value>
                <fullName>Freight Company Damage</fullName>
            </value>
            <value>
                <fullName>Freight Company O&amp;S</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Case/fields/NATT_Default_Queue__c.field-meta.xml
<CustomField>
    <fullName>NATT_Default_Queue__c</fullName>
    <description>Used in Flow logic</description>
    <inlineHelpText>Used to assign new Dealer generated Cases for a Queue for processing.</inlineHelpText>
    <label>Default Queue</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NATT_Application_Engineering</fullName>
            </value>
            <value>
                <fullName>NATT_BluEdge_Warranty</fullName>
            </value>
            <value>
                <fullName>NATT_Core_Returns</fullName>
            </value>
            <value>
                <fullName>NATT_eSolutions</fullName>
                <label>Lynx Fleet</label>
            </value>
            <value>
                <fullName>NATT_Performance_Parts</fullName>
            </value>
            <value>
                <fullName>NATT_Product_Support</fullName>
            </value>
            <value>
                <fullName>NATT_Service_Engineering_Field_Service</fullName>
            </value>
            <value>
                <fullName>NATT_Unit_Sales</fullName>
            </value>
            <value>
                <fullName>NATT_Warehouse</fullName>
            </value>
            <value>
                <fullName>CTM_Customer_Service</fullName>
            </value>
            <value>
                <fullName>CTM_eSolutions</fullName>
            </value>
            <value>
                <fullName>CTM_Finance</fullName>
            </value>
            <value>
                <fullName>CTM_Performance_Parts</fullName>
            </value>
            <value>
                <fullName>CTM_Service_Engineering_Field_Service</fullName>
            </value>
            <value>
                <fullName>CTM_Warranty</fullName>
            </value>
            <value>
                <fullName>CTM_Unit_Sales</fullName>
            </value>
            <value>
                <fullName>CTBR_Container</fullName>
            </value>
            <value>
                <fullName>CTBR_Finance</fullName>
            </value>
            <value>
                <fullName>CTBR_Lynx_Fleet</fullName>
            </value>
            <value>
                <fullName>CTBR_Parts_T_T</fullName>
            </value>
            <value>
                <fullName>CTBR_Unit_Sales</fullName>
            </value>
            <value>
                <fullName>CTBR_Warranty</fullName>
            </value>
            <value>
                <fullName>CTBR_Customer_Service</fullName>
            </value>
            <value>
                <fullName>CTBR_Warehouse</fullName>
            </value>
            <value>
                <fullName>CTBR_IT</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/Natt_Case_Queue_Email_Notification.cls
public class Natt_Case_Queue_Email_Notification { 
    
    public static void sendQueueeMailNotification(List<Case> caseList, map<Id,case> caseOldMap){
        List<case> casestoUpdate = new List<case>();
        List<string> sendTo = new List<string>();
        map<Id,string> grpMap = new map<id,string>();
        list<string> memberIdList = new list<string>();
        map<Id,string> caseDefaultQueueMap = new map<id,string>();
        map<Id,list<string>> caseMemberMap = new map<id,list<string>>();
        try{
            for(case c : caseList){
                string ownerIdVal = c.OwnerId;
                if (c.OwnerId != null && ownerIdVal.startsWith('00G') &&  caseOldMap !=null && ownerIdVal != caseOldMap.get(c.Id).ownerID ) { 
                    casestoUpdate.add(c);
                    caseDefaultQueueMap.put(c.Id, c.NATT_Default_Queue__c);
                }
            }
            if(casestoUpdate.size() < 1){
                return;
            }
            sendTo = getQueueMembers(caseDefaultQueueMap);
            
            List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
            for (Case newCase : casestoUpdate) {
                if(!sendTo.isempty()){
                    Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                    email.setToAddresses(sendTo); 
                    email.setSubject('New Case Notification.' 	+ newCase.CaseNumber);
                    String  body = 	'Case Number'+		':' + ''+ newCase.CaseNumber+'<br/>' +
                        'Priority'+			':' + ''+ newCase.Priority+'<br/>'+ 
                        'Case Record Type'+	':' + ''+ newCase.RecordTypeId+'<br/>'+
                        'Case Type'+		':' + ''+ newCase.Type+'<br/>' + 
                        'Case Reason'+		':' + ''+ newCase.CTM_Case_Reason__c+'<br/>';
                    email.setHtmlBody(body);    
                    emailList.add(email);
                }
            }
            Messaging.SendEmailResult[] emailResults = Messaging.sendEmail(emailList);
        }
        catch(exception e){
            system.debug(e);
        }
    }
    public static List<string> getQueueMembers( map<Id,string> caseDefaultQueueMap){
        list<string> sendMailsTo = new list<string>();
        set<Id> innerGroup = new set<Id>();
        List<Group> groups = new List<Group>([SELECT Id, Name,DeveloperName,Email  FROM Group WHERE Type = 'Queue' AND DeveloperName IN :  caseDefaultQueueMap.values() ]);
        List<GroupMember> queueMembers = [SELECT id,GroupId,  UserOrGroupId FROM GroupMember WHERE GroupId in : groups ];
        
        for(GroupMember member : queueMembers) {
            string memGroupId = member.UserOrGroupId;
            if(! memGroupId.startsWith('00G')){
                sendMailsTo.add(member.UserOrGroupId);
            }
            else{
                innerGroup.add(member.UserOrGroupId);
            }
        }
        if(innerGroup.size() >0 ){
            List<GroupMember> Memberslist =  getQueueMemberslist(innerGroup);
            for(GroupMember member : queueMembers) {
                string memGroupId = member.UserOrGroupId;
                if(! memGroupId.startsWith('00G')){
                    sendMailsTo.add(member.UserOrGroupId);
                }
                
            }
        }
        
        return  sendMailsTo;
    }
    public static List<GroupMember> getQueueMemberslist(set<id> groupId ){
        List<GroupMember> queueMembersList = [SELECT id,GroupId,  UserOrGroupId FROM GroupMember WHERE GroupId in : groupId ];
        return queueMembersList;
    }
    
    
}