NATTQA-ENV/force-app/main/default/objects/Case/fields/NAOCAP_Core_Return_Additional_Message__c.field-meta.xml
<CustomField>
    <fullName>NAOCAP_Core_Return_Additional_Message__c</fullName>
    <formula>NATT_Core_Return_Location_Account__r.NAOCAP_Additional_Comments__c</formula>
    <label>NAOCAP Core Return Additional Message</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Return_Item__c/NATT_Return_Item__c.object-meta.xml
<CustomObject>
    <description>Junction object that links cases to returned items</description>
    <label>Return Item</label>
    <nameField>
        <displayFormat>RTN-{000000}</displayFormat>
        <label>Return Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Return Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_Return_Item__c/fields/NATT_Accepted_Quantity__c.field-meta.xml
<CustomField>
    <fullName>NATT_Accepted_Quantity__c</fullName>
    <label>Accepted Quantity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Return_Item__c/fields/NATT_Case__c.field-meta.xml
<CustomField>
    <fullName>NATT_Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Return_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Return_Item__c/fields/NATT_MPR_Tag__c.field-meta.xml
<CustomField>
    <fullName>NATT_MPR_Tag__c</fullName>
    <label>MPR Tag #</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Return_Item__c/fields/NATT_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>NATT_Part_Number__c</fullName>
    <formula>NATT_Product__r.NATT_P_N__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Part Number</label>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Return_Item__c/fields/NATT_Quantity__c.field-meta.xml
<CustomField>
    <fullName>NATT_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Return_Item__c/fields/NATT_Received_Core__c.field-meta.xml
<CustomField>
    <fullName>NATT_Received_Core__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Received Core</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Return_Item__c/fields/NATT_Rejected_Quantity__c.field-meta.xml
<CustomField>
    <fullName>NATT_Rejected_Quantity__c</fullName>
    <label>Rejected Quantity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Return_Item__c/fields/NATT_Remarks_Notes__c.field-meta.xml
<CustomField>
    <fullName>NATT_Remarks_Notes__c</fullName>
    <inlineHelpText>Remarks and Notes from Carrier</inlineHelpText>
    <label>Remarks/Notes</label>
    <type>TextArea</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Return_Item__c/fields/NATT_Serial__c.field-meta.xml
<CustomField>
    <fullName>NATT_Serial__c</fullName>
    <label>Serial #</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Return_Item__c/fields/NATT_Warranty__c.field-meta.xml
<CustomField>
    <fullName>NATT_Warranty__c</fullName>
    <label>Warranty #</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/NAC_ReturnItemsPDF.cls
public without sharing class NAC_ReturnItemsPDF {
    public Case c {get;set;}
    public NAC_ReturnItemsPDF(ApexPages.StandardController con)
    {
        c = [SELECT Id,CaseNumber,NAOCAP_Core_Return_Additional_Message__c, (SELECT Name, NATT_Part_Number__c, NATT_Quantity__c, NATT_Serial__c, NATT_Warranty__c, NATT_MPR_Tag__c, NATT_Received_Core__c, NATT_Accepted_Quantity__c, NATT_Rejected_Quantity__c, NATT_Remarks_Notes__c   FROM Return_Items__r) FROM Case WHERE Id=:con.getId()];               
    } 
}