NATTQA-ENV/force-app/main/default/objects/Case/fields/NATT_Case_Reason__c.field-meta.xml
<CustomField>
    <fullName>NATT_Case_Reason__c</fullName>
    <inlineHelpText>Reason that the Case is being created</inlineHelpText>
    <label>Case Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Management Issues</fullName>
            </value>
            <value>
                <fullName>Alarm</fullName>
            </value>
            <value>
                <fullName>Annual Returns</fullName>
            </value>
            <value>
                <fullName>Application Issue</fullName>
            </value>
            <value>
                <fullName>Availability</fullName>
            </value>
            <value>
                <fullName>Back Order</fullName>
            </value>
            <value>
                <fullName>Batch Issues</fullName>
                <isActive>false</isActive>
                <label>Batch Issues</label>
            </value>
            <value>
                <fullName>Cancellations</fullName>
            </value>
            <value>
                <fullName>Change</fullName>
                <isActive>false</isActive>
                <label>Change</label>
            </value>
            <value>
                <fullName>Change existing billing address</fullName>
            </value>
            <value>
                <fullName>Change existing shipping address</fullName>
            </value>
            <value>
                <fullName>Claim Rejection or Appeals</fullName>
            </value>
            <value>
                <fullName>Claim Update</fullName>
            </value>
            <value>
                <fullName>Commissioning Issues</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Concealed Damage</fullName>
            </value>
            <value>
                <fullName>Concession Request</fullName>
            </value>
            <value>
                <fullName>Consolidated Billing</fullName>
                <isActive>false</isActive>
                <label>Consolidated Billing</label>
            </value>
            <value>
                <fullName>Contract Issues</fullName>
            </value>
            <value>
                <fullName>Core Return</fullName>
            </value>
            <value>
                <fullName>Coverage Information</fullName>
            </value>
            <value>
                <fullName>Coverage Terms</fullName>
                <isActive>false</isActive>
                <label>Coverage Terms</label>
            </value>
            <value>
                <fullName>CPEC</fullName>
                <isActive>false</isActive>
                <label>CPEC</label>
            </value>
            <value>
                <fullName>Credit Memos</fullName>
            </value>
            <value>
                <fullName>Credits</fullName>
            </value>
            <value>
                <fullName>Customer Ordered in Error</fullName>
            </value>
            <value>
                <fullName>Damages</fullName>
            </value>
            <value>
                <fullName>Data Feed</fullName>
                <isActive>false</isActive>
                <label>Data Feed</label>
            </value>
            <value>
                <fullName>Deductible for a Repeat Charge</fullName>
                <isActive>false</isActive>
                <label>Deductible for a Repeat Charge</label>
            </value>
            <value>
                <fullName>Defective Shelf</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Case/fields/NATT_Core_Return_Location__c.field-meta.xml
<CustomField>
    <fullName>NATT_Core_Return_Location__c</fullName>
    <label>Core Return Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Core_Return_Location</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Core_Return_Location__c/NATT_Core_Return_Location__c.object-meta.xml
<CustomObject>
    <description>Data related to a Core Return Location</description>
    <label>Core Return Location</label>
    <nameField>
        <label>Core Return Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Core Return Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Core_Return_Location.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Carrier/Carlyle Compressor Core Returns</fullName>
    </customValue>
    <customValue>
        <fullName>Carrier Transicold Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>Carrier Transicold X430 Core Return</fullName>
    </customValue>
    <customValue>
        <fullName>Carrier Electric Motor Repair</fullName>
    </customValue>
    <customValue>
        <fullName>Starter &amp; Alternator Core Returns</fullName>
    </customValue>
    <customValue>
        <fullName>Weitron Refrigerant Cylinder Returns</fullName>
    </customValue>
    <customValue>
        <fullName>Return to Panama parts depot</fullName>
    </customValue>
    <customValue>
        <fullName>Return to Chile parts depot</fullName>
    </customValue>
    <description>Locations for equipment returned through the Core Returns program</description>
    <masterLabel>NATT Core Return Location</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/CoreReturnsCaseCloseEmailAlertBatch_Test.cls
/*************************************************************************************************
Apex Class Name : CoreReturnsCaseCloseEmailAlertBatch_Test
Version : 1.0
Created Date : 11/05/2023
Function : This is a test class for CoreReturnsCaseCloseEmailAlertBatch

Modification Log:
-------------------------------------------------------------------------------------------------------------------------------------------------
* Developer                                Date                                Description
* -----------------------------------------------------------------------------------------------------------------------------------------------
* Sanjay Sarraf         		     06/06/2023                        Initial creation        
*************************************************************************************************/

@isTest
public class CoreReturnsCaseCloseEmailAlertBatch_Test {  
   
    static testMethod void testCoreReturnsCaseCloseEmailAlertBatch() {
        //Creating new Core Returns case 
        Case cs = new Case();
		cs.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Core Returns').getRecordTypeId();
		cs.Status = 'New';
		cs.Type = 'Core Return';
		cs.NATT_Case_Reason__c = 'Core Return';
		cs.Origin = 'SolutionCenter';
		cs.NATT_Core_Return_Location__c = 'Carrier/Carlyle Compressor Core Returns';
		insert cs;
		

		Test.setCreatedDate(cs.Id, Date.today().addDays(-14));

		Test.startTest();
		Case ppCase = [SELECT Id, CreatedDate FROM Case 
							 WHERE Type = 'Core Return' limit 1];
        System.debug('ppCase.CreatedDate++'+ppCase.CreatedDate);
		//System.assert to validate the result
		System.assertEquals(ppCase.CreatedDate, Date.today().addDays(-14));
		CoreReturnsCaseCloseEmailAlertBatch batchInstance= new CoreReturnsCaseCloseEmailAlertBatch();
        Id jobid= Database.executeBatch(batchInstance);		
        assert.isNotNull(jobid);
		Test.stopTest();
    }  
}