NATTQA-ENV/force-app/main/default/objects/Case/fields/NATT_Case_Reason__c.field-meta.xml
<CustomField>
    <fullName>NATT_Case_Reason__c</fullName>
    <inlineHelpText>Reason that the Case is being created</inlineHelpText>
    <label>Case Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Management Issues</fullName>
            </value>
            <value>
                <fullName>Alarm</fullName>
            </value>
            <value>
                <fullName>Annual Returns</fullName>
            </value>
            <value>
                <fullName>Application Issue</fullName>
            </value>
            <value>
                <fullName>Availability</fullName>
            </value>
            <value>
                <fullName>Back Order</fullName>
            </value>
            <value>
                <fullName>Batch Issues</fullName>
                <isActive>false</isActive>
                <label>Batch Issues</label>
            </value>
            <value>
                <fullName>Cancellations</fullName>
            </value>
            <value>
                <fullName>Change</fullName>
                <isActive>false</isActive>
                <label>Change</label>
            </value>
            <value>
                <fullName>Change existing billing address</fullName>
            </value>
            <value>
                <fullName>Change existing shipping address</fullName>
            </value>
            <value>
                <fullName>Claim Rejection or Appeals</fullName>
            </value>
            <value>
                <fullName>Claim Update</fullName>
            </value>
            <value>
                <fullName>Commissioning Issues</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Concealed Damage</fullName>
            </value>
            <value>
                <fullName>Concession Request</fullName>
            </value>
            <value>
                <fullName>Consolidated Billing</fullName>
                <isActive>false</isActive>
                <label>Consolidated Billing</label>
            </value>
            <value>
                <fullName>Contract Issues</fullName>
            </value>
            <value>
                <fullName>Core Return</fullName>
            </value>
            <value>
                <fullName>Coverage Information</fullName>
            </value>
            <value>
                <fullName>Coverage Terms</fullName>
                <isActive>false</isActive>
                <label>Coverage Terms</label>
            </value>
            <value>
                <fullName>CPEC</fullName>
                <isActive>false</isActive>
                <label>CPEC</label>
            </value>
            <value>
                <fullName>Credit Memos</fullName>
            </value>
            <value>
                <fullName>Credits</fullName>
            </value>
            <value>
                <fullName>Customer Ordered in Error</fullName>
            </value>
            <value>
                <fullName>Damages</fullName>
            </value>
            <value>
                <fullName>Data Feed</fullName>
                <isActive>false</isActive>
                <label>Data Feed</label>
            </value>
            <value>
                <fullName>Deductible for a Repeat Charge</fullName>
                <isActive>false</isActive>
                <label>Deductible for a Repeat Charge</label>
            </value>
            <value>
                <fullName>Defective Shelf</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Case/fields/NATT_Date_of_Entry__c.field-meta.xml
<CustomField>
    <fullName>NATT_Date_of_Entry__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date of Entry</label>
    <type>Date</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/NAC_CreateCaseControllerTest.cls
@IsTest
public class NAC_CreateCaseControllerTest {
    
    @IsTest
    static void getFieldsTest(){
        system.runAs(NAC_TestDataFactory.runAsNACUser()){
            Test.startTest();
            NAC_CreateCaseController.caseWrapper caseWrap = NAC_CreateCaseController.getCaseDetails('Case');
            Test.stopTest();
            System.assertNotEquals(caseWrap.coreFields, null, 'case creation failed');
            System.assertNotEquals(caseWrap.performancePartsFields, null, 'case creation failed');
        }
    }
    
    @IsTest
    static void createCoreReturnsTest(){
        Case cs = new Case();
        cs.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('NAOCAP Core Return').getRecordTypeId();
        cs.Status = 'New';
        cs.Type = 'Core Return';
        cs.NATT_Case_Reason__c = 'Core Return';
        insert cs;
        
        MAp<String,String> caseMap=new MAp<String,String>();
        String s=string.valueOfGmt(date.today());
        //Case cs=[SELECT Id, RecordTypeId, RecordType.Name FROM Case where RecordType.Name ='NAOCAP Core Return' LIMIT 1];
        caseMap.put('NATT_Date_of_Entry__c',s);
        List<MAp<String,sTring>> ListOfMap=new List<MAp<String,sTring>>();
        ListOfMap.add(caseMap);
        Test.startTest(); 
        NAC_CreateCaseController.resultWrapper resWrapper=NAC_CreateCaseController.createCoreReturns(caseMap,ListOfMap);
        NAC_CreateCaseController.resultWrapper resWrapperPfpart=NAC_CreateCaseController.createPerfPartReturns(caseMap,ListOfMap);
        NAC_CreateCaseController.resultWrapper returnedCreatePerfPartReturnInternal=NAC_CreateCaseController.createPerfPartReturnInternal(caseMap,ListOfMap,cs.id);
        Test.stopTest();
        System.assertNotEquals(resWrapper, null, 'case creation failed');
        System.assertNotEquals(resWrapperPfpart, null, 'case creation failed');
        System.assertNotEquals(returnedCreatePerfPartReturnInternal, null, 'case creation failed'); 
    }
    
    @IsTest
    static void fetchLookupData(){
        Test.startTest();
        list<sObject> sObjList=NAC_CreateCaseController.fetchLookupData('Test','ATL','Product2','test');
        Test.stopTest();
        System.assertNotEquals(sObjList.size(), null, 'case creation for a product failed'); 
    }
}