NATTQA-ENV/force-app/main/default/objects/NATT_Product_Dealer_Type__c/NATT_Product_Dealer_Type__c.object-meta.xml
<CustomObject>
    <description>Used with NATT Dealers to show the dealer type per product</description>
    <label>Product Dealer Type</label>
    <nameField>
        <displayFormat>PDT-{000000}</displayFormat>
        <label>Product Dealer Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Dealer Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/NATT_Product_Dealer_Type__c/fields/NATT_Dealer__c.field-meta.xml
<CustomField>
    <fullName>NATT_Dealer__c</fullName>
    <description>For NATT Dealer Accounts to classify Dealers</description>
    <label>Dealer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Dealer Types</relationshipLabel>
    <relationshipName>Product_Dealer_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Product_Dealer_Type__c/fields/NATT_Dealer_Type__c.field-meta.xml
<CustomField>
    <fullName>NATT_Dealer_Type__c</fullName>
    <description>Classify the Dealer for NATT</description>
    <label>Dealer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Dealer</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Mobile Location</fullName>
            </value>
            <value>
                <fullName>Associate Location</fullName>
            </value>
            <value>
                <fullName>Parts &amp; Service Dealer</fullName>
            </value>
            <value>
                <fullName>Direct Sell</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/NATT_Product_Dealer_Type__c/fields/NATT_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>NATT_Product_Type__c</fullName>
    <description>NATT - to classify dealers</description>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Truck</fullName>
            </value>
            <value>
                <fullName>Trailer</fullName>
            </value>
            <value>
                <fullName>Special Products</fullName>
            </value>
            <value>
                <fullName>Electric Trailer</fullName>
            </value>
            <value>
                <fullName>Electric Truck</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/CTBR_BluEdge_Unit__c.field-meta.xml
<CustomField>
    <fullName>CTBR_BluEdge_Unit__c</fullName>
    <description>twin field</description>
    <label>CTBR BluEdge Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CTBR_BluEdge_Unit</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <description>twin field from quote</description>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Unit</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>The quote where the order is created from.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/CTBR_Unit__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Unit__c</fullName>
    <label>CTBR Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Legacy_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Legacy_Unit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Legacy Unit</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Truck__c.field-meta.xml
<CustomField>
    <fullName>NATT_Truck__c</fullName>
    <defaultValue>false</defaultValue>
    <description>used for filtering NATT</description>
    <label>Truck</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <description>for quoting NATT Units</description>
    <label>Unit NATT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NATT_Unit</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CTBR_BluEdge_Unit__c.field-meta.xml
<CustomField>
    <fullName>CTBR_BluEdge_Unit__c</fullName>
    <label>CTBR BluEdge Unit</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CTBR_BluEdge_Product_Family__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>CTBR_BluEdge_Unit</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CTBR_Unit__c.field-meta.xml
<CustomField>
    <fullName>CTBR_Unit__c</fullName>
    <label>CTBR Unit</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CTBR_Product_Family__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vector 8500</fullName>
            </value>
            <value>
                <fullName>X4 7500</fullName>
            </value>
            <value>
                <fullName>X4 7700</fullName>
            </value>
            <value>
                <fullName>Vector HE19</fullName>
            </value>
            <value>
                <fullName>Vector 8600 MT</fullName>
            </value>
            <value>
                <fullName>SUPRA 750  STD-BY</fullName>
            </value>
            <value>
                <fullName>Supra 850 STD-BY</fullName>
            </value>
            <value>
                <fullName>Supra 850 MT</fullName>
            </value>
            <value>
                <fullName>Supra 1150 STD-BY</fullName>
            </value>
            <value>
                <fullName>Supra 1150 MT</fullName>
            </value>
            <value>
                <fullName>Supra 1250 MT</fullName>
            </value>
            <value>
                <fullName>Supra S7</fullName>
            </value>
            <value>
                <fullName>Supra S8</fullName>
            </value>
            <value>
                <fullName>Supra S9</fullName>
            </value>
            <value>
                <fullName>CITIMAX 280 12V LA</fullName>
            </value>
            <value>
                <fullName>CITIMAX 280 24V LA</fullName>
            </value>
            <value>
                <fullName>CITIMAX 400 12V LA</fullName>
            </value>
            <value>
                <fullName>CITIMAX 400 24V LA</fullName>
            </value>
            <value>
                <fullName>Citimax 500 12V AE</fullName>
            </value>
            <value>
                <fullName>Citimax 500 24V AE</fullName>
            </value>
            <value>
                <fullName>Citimax 600 12V AE</fullName>
            </value>
            <value>
                <fullName>Citimax 600 24V AE</fullName>
            </value>
            <value>
                <fullName>Citimax 700 12V AE</fullName>
            </value>
            <value>
                <fullName>Citimax 700 24V AE</fullName>
            </value>
            <value>
                <fullName>Xarios 6 R2 24V 220/3/60</fullName>
            </value>
            <value>
                <fullName>Xarios 6 R2 12V 220/3/60</fullName>
            </value>
            <value>
                <fullName>Citimax 280</fullName>
                <isActive>false</isActive>
                <label>Citimax 280</label>
            </value>
            <value>
                <fullName>Citimax 400</fullName>
                <isActive>false</isActive>
                <label>Citimax 400</label>
            </value>
            <value>
                <fullName>Citimax 500</fullName>
                <isActive>false</isActive>
                <label>Citimax 500</label>
            </value>
            <value>
                <fullName>Citimax 700</fullName>
                <isActive>false</isActive>
                <label>Citimax 700</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/CTM_BluEdge_Unit__c.field-meta.xml
<CustomField>
    <fullName>CTM_BluEdge_Unit__c</fullName>
    <label>CTM BluEdge Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CTM_BluEdge_Unit</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Active_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Active_Unit__c</fullName>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Product_Family__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>200INT ComfortPro Integrated APU</fullName>
            </value>
            <value>
                <fullName>210STA ComfortPro Stand-alone APU</fullName>
            </value>
            <value>
                <fullName>220PWR ComfortPro Power-only APU</fullName>
            </value>
            <value>
                <fullName>230SKY ComfortPro ClearSky DPF APU</fullName>
            </value>
            <value>
                <fullName>240EPS ComfortPro Electric APU</fullName>
            </value>
            <value>
                <fullName>Supra S6 Road Only</fullName>
            </value>
            <value>
                <fullName>Supra S6 with 230v-3ph-60Hz</fullName>
            </value>
            <value>
                <fullName>Supra S7 Road Only</fullName>
            </value>
            <value>
                <fullName>Supra S7 with 230v-3ph-60Hz</fullName>
            </value>
            <value>
                <fullName>Supra S8 Road Only</fullName>
            </value>
            <value>
                <fullName>Supra S8 with 230v-3ph-60Hz</fullName>
            </value>
            <value>
                <fullName>Supra S9 Road Only</fullName>
            </value>
            <value>
                <fullName>Supra S9 with 230v-3ph-60Hz</fullName>
            </value>
            <value>
                <fullName>20X Road Only</fullName>
            </value>
            <value>
                <fullName>30S Road Only</fullName>
            </value>
            <value>
                <fullName>30S with 115v-1ph-60Hz Standby</fullName>
            </value>
            <value>
                <fullName>30S with 230v-1ph-60Hz Standby</fullName>
            </value>
            <value>
                <fullName>35X Road Only</fullName>
            </value>
            <value>
                <fullName>35X with 115v-1ph-60Hz Standby</fullName>
            </value>
            <value>
                <fullName>35X with 230v-1ph-60Hz Standby</fullName>
            </value>
            <value>
                <fullName>35X with 230v-3ph-60Hz Standby</fullName>
            </value>
            <value>
                <fullName>40X with 230v-1ph-60Hz Standby</fullName>
            </value>
            <value>
                <fullName>40XR with 230v-1ph-60Hz Standby</fullName>
            </value>
            <value>
                <fullName>40XR with 230v-3ph-60Hz Standby</fullName>
            </value>
            <value>
                <fullName>50X with 230v-1ph-60Hz Standby</fullName>
            </value>
            <value>
                <fullName>50XR Road Only</fullName>
            </value>
            <value>
                <fullName>50XR with 230v-1ph-60Hz Standby</fullName>
            </value>
            <value>
                <fullName>50XR with 230v-3ph-60Hz Standby</fullName>
            </value>
            <value>
                <fullName>Neos 100S - Road Only</fullName>
            </value>
            <value>
                <fullName>Solara APX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Quote_Record_Type_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>NATT_Quote_Record_Type_Developer_Name__c</fullName>
    <description>Used to default Quote Record Developer Name through a Process Builder.</description>
    <label>Quote Record Type Developer Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/NATT_Unit__c.field-meta.xml
<CustomField>
    <fullName>NATT_Unit__c</fullName>
    <description>NATT Unit selected for this quote</description>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NATT_Product_Family__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>NATT_Unit</valueSetName>
    </valueSet>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__PricebookId__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PricebookId__c</fullName>
    <description>ID of the Price Book used by this quote.</description>
    <inlineHelpText>ID of the Price Book used by this quote.</inlineHelpText>
    <label>Pricebook ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

NATTQA-ENV/force-app/main/default/globalValueSets/CTBR_BluEdge_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Supra 750 SIII</fullName>
    </customValue>
    <customValue>
        <fullName>Supra 850 SIII</fullName>
    </customValue>
    <customValue>
        <fullName>Supra 1250</fullName>
    </customValue>
    <customValue>
        <fullName>Supra 1250 MT</fullName>
    </customValue>
    <customValue>
        <fullName>Supra 1150</fullName>
    </customValue>
    <customValue>
        <fullName>Supra 1150 MT</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S6 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S7 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S8 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S9 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8100</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8500</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 01</fullName>
    </customValue>
    <customValue>
        <fullName>X4 7300</fullName>
    </customValue>
    <customValue>
        <fullName>X4 7500</fullName>
    </customValue>
    <masterLabel>CTBR BluEdge Unit</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/CTM_BluEdge_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>200INT ComfortPro Integrated APU</fullName>
    </customValue>
    <customValue>
        <fullName>210STA ComfortPro Stand-alone APU</fullName>
    </customValue>
    <customValue>
        <fullName>220PWR ComfortPro Power-only APU</fullName>
    </customValue>
    <customValue>
        <fullName>230SKY ComfortPro ClearSky DPF APU</fullName>
    </customValue>
    <customValue>
        <fullName>240EPS ComfortPro Electric APU</fullName>
    </customValue>
    <customValue>
        <fullName>250ION-APU ION BATTERY</fullName>
    </customValue>
    <customValue>
        <fullName>C280 R404A 12V BASICO-SL</fullName>
    </customValue>
    <customValue>
        <fullName>C280 R404A 24V BASICO-SL</fullName>
    </customValue>
    <customValue>
        <fullName>C350 R404A 12V BASICO-SL</fullName>
    </customValue>
    <customValue>
        <fullName>C350 R404A 24V BASICO-SL</fullName>
    </customValue>
    <customValue>
        <fullName>C400 R404A 12V BASICO-SL</fullName>
    </customValue>
    <customValue>
        <fullName>C400 R404A 24V BASICO-SL</fullName>
    </customValue>
    <customValue>
        <fullName>C500 12V R404A- BASICO S</fullName>
    </customValue>
    <customValue>
        <fullName>C500 24V R404A-BASICO S</fullName>
    </customValue>
    <customValue>
        <fullName>C700 12V R404A-BASICO SA</fullName>
    </customValue>
    <customValue>
        <fullName>C700 24V R404A-BASICO SA</fullName>
    </customValue>
    <customValue>
        <fullName>CITIFRESH 500 12V R134a</fullName>
    </customValue>
    <customValue>
        <fullName>CITIMAX 1000 R404A 24V LA</fullName>
    </customValue>
    <customValue>
        <fullName>CITIMAX 1100 R404A BASICO-SA  24V</fullName>
    </customValue>
    <customValue>
        <fullName>CITIMAX 280 - R404A - 12 V -LA</fullName>
    </customValue>
    <customValue>
        <fullName>CITIMAX 280 - R404A - 12 V rooftop</fullName>
    </customValue>
    <customValue>
        <fullName>CITIMAX 280 - R404A - 24 V -LA</fullName>
    </customValue>
    <customValue>
        <fullName>CITIMAX 400 - R404A - 12 V -LA</fullName>
    </customValue>
    <customValue>
        <fullName>CITIMAX 400 - R404A - 24 V -LA</fullName>
    </customValue>
    <customValue>
        <fullName>Citimax 500 12V W/MH</fullName>
    </customValue>
    <customValue>
        <fullName>Citimax 500 24V W/MH</fullName>
    </customValue>
    <customValue>
        <fullName>Citimax 700 12V W/MH</fullName>
    </customValue>
    <customValue>
        <fullName>Citimax 700 24V W/MIV</fullName>
    </customValue>
    <customValue>
        <fullName>INTEGRA 30S 12V 115/1/60 (athens)</fullName>
    </customValue>
    <customValue>
        <fullName>INTEGRA 30S 12V 115/1/60 (francia)</fullName>
    </customValue>
    <masterLabel>CTM BluEdge Unit</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/globalValueSets/NATT_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>200INT ComfortPro Integrated APU</fullName>
    </customValue>
    <customValue>
        <fullName>210STA ComfortPro Stand-alone APU</fullName>
    </customValue>
    <customValue>
        <fullName>220PWR ComfortPro Power-only APU</fullName>
    </customValue>
    <customValue>
        <fullName>230SKY ComfortPro ClearSky DPF APU</fullName>
    </customValue>
    <customValue>
        <fullName>240EPS ComfortPro Electric APU</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S6 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S7 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S8 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>Supra S9 with 230v-3ph-60Hz</fullName>
    </customValue>
    <customValue>
        <fullName>20X Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>30S Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>30S with 115v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>30S with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>35X Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>35X with 115v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>35X with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>35X with 230v-3ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>40X with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>40XR with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>50X with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>50XR Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>50XR with 230v-1ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>50XR with 230v-3ph-60Hz Standby</fullName>
    </customValue>
    <customValue>
        <fullName>Neos 100S - Road Only</fullName>
    </customValue>
    <customValue>
        <fullName>Solara APX</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8100</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8500</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 01</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 02</fullName>
    </customValue>
    <customValue>
        <fullName>Vector 8600 - System 03</fullName>
    </customValue>
    <description>for quoting in cpq for NATT</description>
    <masterLabel>NATT Unit</masterLabel>
</GlobalValueSet>

NATTQA-ENV/force-app/main/default/classes/GlobalProductSearchPlugin.cls
/***************************************************************************
* Author - Sandeep Kumar
* Version: 1.0 
* Date: 03 Feb, 2021
* Product Search Plugin Class - ProductSearchPlugin 
* Description - 
* Test Class : ProductSearchPluginTest
* Code Reviewed By : (to be reviewed)
****************************************************************************/
global class GlobalProductSearchPlugin implements SBQQ.ProductSearchPlugin{
    
    public final string quoteRecordType = 'NATT_Units_Quote';

    global GlobalProductSearchPlugin(){
        System.debug('Default constructor');
    }
    
    global Boolean isFilterHidden(sObject quote, String fieldName){        
        
        SBQQ__Quote__c al = (SBQQ__Quote__c) quote;        
        return false;
    }
    
    global String getFilterDefaultValue(sObject quote, String fieldName){
        System.debug('METHOD CALLED: getFilterDefaultValue');
        System.debug('CTBRUNIT quote'+quote);
        System.debug('CTBRUNIT fieldName'+fieldName);
        SBQQ__Quote__c qt = (SBQQ__Quote__c) quote; 
        
        // This would set Unit filter based on Quote Unit value
        if(fieldName == 'NATT_Unit__c' && qt.NATT_Unit__c != null && (qt.NATT_Quote_Record_Type_Developer_Name__c != 'NATT_BluEdge' || qt.NATT_Quote_Record_Type_Developer_Name__c != 'CTBR_BluEdge')) {   
            System.debug('NATTUNIT value'+qt.NATT_Unit__c);
            return qt.NATT_Unit__c; 
        }
        else if(fieldName=='CTBR_Unit__c'){
            System.debug('CTBRUNIT value'+qt.CTBR_Unit__c);
             return qt.CTBR_Unit__c; 
        }
            //return qt.NATT_Unit__c;
        
        return null;
    }
    
    global Boolean isSearchCustom(sObject quote, Map<String,Object> fieldValuesMap){
        System.debug('METHOD: isSearchCustom 2'+quote);
        
        SBQQ__Quote__c quoteObj = (SBQQ__Quote__c) quote;
        //System.debug('Quote is '+quoteObj);
        
         //SBQQ__Quote__c quoteObj=[SELECT Id ,SBQQ__Account__c,RecordType.DeveloperName,NATT_Unit__c,CTBR_BluEdge_Unit__c,CTM_BluEdge_Unit__c from SBQQ__Quote__c where Id=:quote.Id limit 1];
        // retrieve all associated dealer types
        List<NATT_Product_Dealer_Type__c> productDealerTypes = [Select Id From NATT_Product_Dealer_Type__c Where NATT_Dealer__c = :quoteObj.SBQQ__Account__c];
        
        if(productDealerTypes.Size() > 0 && quoteObj.NATT_Quote_Record_Type_Developer_Name__c == 'NATT_Units_Quote' || quoteObj.NATT_Quote_Record_Type_Developer_Name__c=='CTBR_Units_Quote'){
            return true;
        }else if(quoteObj.NATT_Unit__c != null && quoteObj.NATT_Quote_Record_Type_Developer_Name__c == 'NATT_BluEdge'){ return true; }
        else if((quoteObj.NATT_Unit__c != null || quoteObj.CTBR_BluEdge_Unit__c != null) && quoteObj.NATT_Quote_Record_Type_Developer_Name__c == 'CTBR_BluEdge'){ return true;
        
        //CTM BLUEDGE    
        }else if(quoteObj.CTM_BluEdge_Unit__c != null && quoteObj.NATT_Quote_Record_Type_Developer_Name__c == 'CTM_BluEdge'){ return true;}
        else if(quoteObj.NATT_Active_Unit__c != null &&  quoteObj.NATT_Quote_Record_Type_Developer_Name__c =='NATT_Direct_Sales'){return true;}
        return false;
    }
    
    global Boolean isSuggestCustom(sObject quote, Map<String,Object> fieldValuesMap){
        return false;
    }
    
    global Boolean isInputHidden(sObject quote, String Field){
        return false;
    }
    
    global Object getInputDefaultValue(sObject query, String value){
        return '2';
    }
    
    global String getAdditionalSuggestFilters(sObject query, Map<String,Object> suggFilts){
        return '';
    }
    
    global List<PricebookEntry> suggest(sObject query, Map<String,Object> usg){
        return [SELECT Id FROM PricebookEntry LIMIT 1];
    }
    
    global String getAdditionalSearchFilters(sObject quote, Map<String,Object> fieldValuesMap){
        System.debug('METHOD: getAdditionalSearchFilters');
        
        String additionalFilter = NULL;
        
        return additionalFilter;
    }
    
    global List<PricebookEntry> search(sObject quote, Map<String,Object> fieldValuesMap){
        System.debug('METHOD CALLED: search Entered');
        
        //PRICEBOOKENTRY COLLECTION DECLARATION
        List<PricebookEntry> pbes = new List<PricebookEntry>();
        
        //GET ALL POSSIBLE FILTER FIELDS FROM THE SEARCH FILTER FIELD SET
        List<Schema.FieldSetMember> searchFilterFieldSetFields = SObjectType.Product2.FieldSets.SBQQ__SearchFilters.getFields();
        
        //GET ALL POSSIBLE FIELDS FROM THE SEARCH RESULTS FIELD SET
        List<Schema.FieldSetMember> searchResultFieldSetFields = SObjectType.Product2.FieldSets.SBQQ__SearchResults.getFields();
        
        String quotePricebookId = String.valueOf(quote.get('SBQQ__PricebookId__c'));
        String quoteCurrencyIsoCode = String.valueOf(quote.get('CurrencyIsoCode'));
        String quoteAccountId = String.valueOf(quote.get('SBQQ__Account__c'));
        
        // variable declaration
        Boolean truckFound = false;
        Boolean trailerFound = false;
        Boolean electricTrailerFound = false;
        Boolean electricTruckFound = false;
        Boolean specialProductsFound = false;
        
        // retrieve all associated dealer types
        List<NATT_Product_Dealer_Type__c> productDealerTypes = [Select Id,NATT_Dealer_Type__c,NATT_Product_Type__c From NATT_Product_Dealer_Type__c Where NATT_Dealer__c = :quoteAccountId];
        
        for(NATT_Product_Dealer_Type__c pdt : productDealerTypes){
            if(pdt.NATT_Product_Type__c == 'Truck'){
                truckFound = true;
            }else if(pdt.NATT_Product_Type__c == 'Trailer'){
                trailerFound = true;
            }else if(pdt.NATT_Product_Type__c == 'Electric Trailer'){
                System.debug('In Electric Trailer');
                electricTrailerFound = true;
            }else if(pdt.NATT_Product_Type__c == 'Electric Truck'){
                System.debug('In Electric Truck');
                electricTruckFound = true;
            }
            else if(pdt.NATT_Product_Type__c == 'Special Products'){ specialProductsFound = true; }
        }
        
        //BUILD THE SELECT STRING
        String selectClause = 'SELECT ';
        
        for(Schema.FieldSetMember field : searchResultFieldSetFields){
            selectClause += 'Product2.' + field.getFieldPath() + ', ';
        }
        
        selectClause += 'Id, UnitPrice, Pricebook2Id, Product2Id, Product2.Id';
        
        //BUILD THE WHERE CLAUSE
        String whereClause = '';
                
        for(Schema.FieldSetMember field : searchFilterFieldSetFields){
            System.debug('field =='+field);
            if(!fieldValuesMap.containsKey(field.getFieldPath())){
                continue;
            }
            
            if((String.valueOf(quote.get('NATT_Quote_Record_Type_Developer_Name__c')) == 'NATT_BluEdge' || String.valueOf(quote.get('NATT_Quote_Record_Type_Developer_Name__c')) == 'CTBR_BluEdge') && field.getFieldPath() == 'NATT_Unit__c'){ continue;
            }                
            
            if(field.getType() == Schema.DisplayType.String || field.getType() == Schema.DisplayType.Picklist){
               whereClause += 'Product2.' + field.getFieldPath() + ' LIKE \'' + fieldValuesMap.get(field.getFieldPath()) + '\' AND '+ 'Product2.NATT_Legacy_Unit__c = false' + ' AND ';                  
            }
        }
        
        String CUSTOMFILTER = '';
       // String BluEdgeFilter = '';
            
        // apply truck only filter
        if(truckFound && !trailerFound && !electricTrailerFound && !electricTruckFound)
            CUSTOMFILTER = 'Product2.NATT_Truck__c = true';
        
        // apply truck and trailer filters
        if(!truckFound && trailerFound && !electricTrailerFound && !electricTruckFound){
            CUSTOMFILTER = 'Product2.NATT_Trailer__c = true';
        }else if(truckFound && trailerFound && !electricTrailerFound && !electricTruckFound){
            CUSTOMFILTER = '(Product2.NATT_Truck__c = true OR Product2.NATT_Trailer__c = true)';
        }
        else if(truckFound && !trailerFound && !electricTrailerFound && !electricTruckFound){
            CUSTOMFILTER = 'Product2.NATT_Truck__c = true';
        }
        else if(!truckFound && !trailerFound && electricTrailerFound && !electricTruckFound){
            System.debug('Electric Trailer found');
            CUSTOMFILTER = 'Product2.NATT_Electric_Trailer__c = true';
        }else if(!truckFound && !trailerFound && !electricTrailerFound && electricTruckFound){
            System.debug('Electric Truck found');
            CUSTOMFILTER = 'Product2.NATT_Electric_Truck__c = true';
        }else if(truckFound && !trailerFound && !electricTrailerFound && electricTruckFound){
            CUSTOMFILTER = '(Product2.NATT_Truck__c = true OR Product2.NATT_Electric_Truck__c = true)';
        }else if(truckFound && trailerFound && !electricTrailerFound && electricTruckFound){
            CUSTOMFILTER = '(Product2.NATT_Trailer__c = true OR Product2.NATT_Electric_Truck__c = true)';
        }else if(truckFound && trailerFound && !electricTrailerFound && electricTruckFound){
            CUSTOMFILTER = '(Product2.NATT_Truck__c = true OR Product2.NATT_Trailer__c = true OR Product2.NATT_Electric_Truck__c = true)';
        }
        else if(truckFound && trailerFound && !electricTrailerFound && electricTruckFound){
            CUSTOMFILTER = '(Product2.NATT_Truck__c = true OR Product2.NATT_Trailer__c = true OR Product2.NATT_Electric_Truck__c = true)';
        }
        else if(truckFound && !trailerFound && electricTrailerFound && electricTruckFound){
            CUSTOMFILTER = '(Product2.NATT_Truck__c = true OR Product2.NATT_Electric_Trailer__c = true OR Product2.NATT_Electric_Truck__c = true)';
        }
        else if(!truckFound && trailerFound && electricTrailerFound && electricTruckFound){
            CUSTOMFILTER = '(Product2.NATT_Trailer__c = true OR Product2.NATT_Electric_Trailer__c = true OR Product2.NATT_Electric_Truck__c = true)';
        }
        else if(!truckFound && trailerFound && electricTrailerFound && !electricTruckFound){
            CUSTOMFILTER = '(Product2.NATT_Trailer__c = true OR Product2.NATT_Electric_Trailer__c = true)';
        }
        else if(truckFound && !trailerFound && electricTrailerFound && !electricTruckFound){
            CUSTOMFILTER = '(Product2.NATT_Truck__c = true OR Product2.NATT_Electric_Trailer__c = true)';
        }
        else if(truckFound && trailerFound && electricTrailerFound && !electricTruckFound){
            CUSTOMFILTER = '(Product2.NATT_Truck__c = true OR Product2.NATT_Trailer__c = true OR Product2.NATT_Electric_Trailer__c = true)';
        }
        else if(truckFound && trailerFound && electricTrailerFound && electricTruckFound){
            CUSTOMFILTER = '(Product2.NATT_Truck__c = true OR Product2.NATT_Trailer__c = true OR Product2.NATT_Electric_Trailer__c = true OR Product2.NATT_Electric_Truck__c = true)';
        }
        // apply truck, trailer and special products filters
        if(!truckFound && !trailerFound && !electricTrailerFound && !electricTruckFound && specialProductsFound){
            CUSTOMFILTER = 'Product2.NATT_SpecialProducts__c = true';
        }else if(!truckFound && trailerFound && !electricTrailerFound && !electricTruckFound && specialProductsFound){
            CUSTOMFILTER = '(Product2.NATT_Trailer__c = true OR Product2.NATT_SpecialProducts__c = true)';
        }else if(truckFound && !trailerFound && !electricTrailerFound && !electricTruckFound && specialProductsFound){
            CUSTOMFILTER = '(Product2.NATT_Truck__c = true OR Product2.NATT_SpecialProducts__c = true)';
        }else if(truckFound && trailerFound && !electricTrailerFound && !electricTruckFound && specialProductsFound){
            CUSTOMFILTER = '(Product2.NATT_Truck__c = true OR Product2.NATT_Trailer__c = true OR Product2.NATT_SpecialProducts__c = true)';
        }else if(!truckFound && !trailerFound && electricTrailerFound && !electricTruckFound && specialProductsFound){
            CUSTOMFILTER = '(Product2.NATT_Electric_Trailer__c = true OR Product2.NATT_SpecialProducts__c = true)';
        }else if(!truckFound && !trailerFound && !electricTrailerFound && electricTruckFound && specialProductsFound){
            CUSTOMFILTER = '(Product2.NATT_Electric_Truck__c = true OR Product2.NATT_SpecialProducts__c = true)';
        }else if(truckFound && trailerFound && electricTrailerFound && !electricTruckFound && specialProductsFound){
            CUSTOMFILTER = '(Product2.NATT_Truck__c = true OR Product2.NATT_Trailer__c = true OR Product2.NATT_Electric_Trailer__c = true OR Product2.NATT_SpecialProducts__c = true)';
        }else if(truckFound && trailerFound && !electricTrailerFound && electricTruckFound && specialProductsFound){
            CUSTOMFILTER = '(Product2.NATT_Truck__c = true OR Product2.NATT_Trailer__c = true OR Product2.NATT_Electric_Truck__c = true OR Product2.NATT_SpecialProducts__c = true)';
        }else if(!truckFound && trailerFound && electricTrailerFound && !electricTruckFound && specialProductsFound){
            CUSTOMFILTER = '(Product2.NATT_Trailer__c = true OR Product2.NATT_Electric_Trailer__c = true OR Product2.NATT_SpecialProducts__c = true)';
        }else if(!truckFound && trailerFound && !electricTrailerFound && electricTruckFound && specialProductsFound){
            CUSTOMFILTER = '(Product2.NATT_Trailer__c = true OR Product2.NATT_Electric_Truck__c = true OR Product2.NATT_SpecialProducts__c = true)';
        }else if(truckFound && !trailerFound && !electricTrailerFound && electricTruckFound && specialProductsFound){
            CUSTOMFILTER = '(Product2.NATT_Truck__c = true OR Product2.NATT_Electric_Truck__c = true OR Product2.NATT_SpecialProducts__c = true)';
        }else if(truckFound && !trailerFound && electricTrailerFound && !electricTruckFound && specialProductsFound){
            CUSTOMFILTER = '(Product2.NATT_Truck__c = true OR Product2.NATT_Electric_Trailer__c = true OR Product2.NATT_SpecialProducts__c = true)';
        }
        
        else if(truckFound && trailerFound && electricTrailerFound && electricTruckFound && specialProductsFound){
            CUSTOMFILTER = '(Product2.NATT_Truck__c = true OR Product2.NATT_Trailer__c = true OR Product2.NATT_Electric_Trailer__c = true OR Product2.NATT_Electric_Truck__c = true OR Product2.NATT_SpecialProducts__c = true)';
        }
          
        // if truck, trailer or special product is found apply the AND clause
        if(truckFound || trailerFound || electricTrailerFound || specialProductsFound || electricTruckFound)
            whereClause += ' '+CUSTOMFILTER+' AND ';
        
        if(String.valueOf(quote.get('NATT_Quote_Record_Type_Developer_Name__c')) == 'NATT_BluEdge'){
            whereClause += '(Product2.ProductCode = \'BluEdge\' OR Product2.ProductCode = \'BluEdge Core Best\' OR Product2.ProductCode = \'BluEdge Core Essential\' OR Product2.ProductCode = \'BluEdge Core Preferred\' OR Product2.ProductCode = \'BluEdge Core Advantage\') AND ';
        }
        
        if(String.valueOf(quote.get('NATT_Quote_Record_Type_Developer_Name__c')) == 'CTBR_BluEdge'){
            whereClause += 'Product2.ProductCode = \'CTBR BluEdge\' AND ';
        }
        
        //add for CTM BLUEDGE

        if(String.valueOf(quote.get('NATT_Quote_Record_Type_Developer_Name__c')) == 'CTM_BluEdge'){
            whereClause += 'Product2.ProductCode = \'MX-BluEdge\' AND ';
        }        

        // finally apply the quote pricebook and currency iso code filter to display only valid products matching the quote currency
        whereClause += ' Pricebook2Id = \''+quotePricebookId+'\' AND CurrencyIsoCode = \''+quoteCurrencyIsoCode+'\'';
        

        //BUILD THE QUERY
         String query;
         if(String.valueOf(quote.get('NATT_Quote_Record_Type_Developer_Name__c')) == 'NATT_BluEdge'){
             query = selectClause + ' FROM PricebookEntry WHERE '+ whereClause +' AND Product2.IsActive = true AND IsActive = true ORDER By Product2.SBQQ__SortOrder__c ASC ';
         }else{
              query = selectClause + ' FROM PricebookEntry WHERE '+ whereClause +' AND Product2.IsActive = true AND IsActive = true ORDER By Product2.Name DESC ';
         }
        
        if(Test.isRunningTest()){
            query = 'Select Id From PricebookEntry Where Product2.IsActive = true AND IsActive = true ORDER By Product2.Name DESC';
        }
        
        //DO THE QUERY
        System.debug('query'+query);
        
        pbes = Database.query(query);
        
        return pbes;
    }  
}