NATTQA-ENV/force-app/main/default/objects/OrderItem/fields/NATT_Core__c.field-meta.xml
<CustomField>
    <fullName>NATT_Core__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Core</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NAOCAP_Not_Orderable__c.field-meta.xml
<CustomField>
    <fullName>NAOCAP_Not_Orderable__c</fullName>
    <description>Field to check the orderability of the product</description>
    <formula>if(NATT_Core__c==true,true,if((NATT_Sales_Code__c==&apos;S01&apos;|| NATT_Sales_Code__c==&apos;SB1&apos;),if (ISPICKVAL( NATT_SignalCode__c, &quot;NLO&quot;),if (ISPICKVAL( NAC_Stocking_Type_UTC__c,&quot;O&quot;),true,false),ISPICKVAL( NATT_SignalCode__c, &quot;S2&quot;) || ISPICKVAL( NATT_SignalCode__c, &quot;PRC&quot;) || ISPICKVAL( NATT_SignalCode__c, &quot;FIN&quot;) || ISPICKVAL( NATT_SignalCode__c, &quot;BY2&quot;)),true))</formula>
    <label>NAOCAP Not Orderable ATL</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NAOCAP_Not_Orderable_ANA__c.field-meta.xml
<CustomField>
    <fullName>NAOCAP_Not_Orderable_ANA__c</fullName>
    <formula>if(NATT_Core__c==true || NATT_ItemPriceGroup__c ==&apos;123&apos;,true,if((NATT_Sales_Code__c==&apos;S01&apos; || NATT_Sales_Code__c==&apos;SM1&apos; || NATT_Sales_Code__c==&apos;SB1&apos;),if (ISPICKVAL( NAOCAP_Signal_Code_ANA__c, &quot;NLO&quot;),if (ISPICKVAL( NAOCAP_Stocking_Type_UTC_ANA__c,&quot;O&quot;),true,false),ISPICKVAL( NAOCAP_Signal_Code_ANA__c, &quot;S2&quot;) || ISPICKVAL( NAOCAP_Signal_Code_ANA__c, &quot;PRC&quot;) || ISPICKVAL( NAOCAP_Signal_Code_ANA__c, &quot;FIN&quot;) || ISPICKVAL( NAOCAP_Signal_Code_ANA__c, &quot;BY2&quot;)),true))</formula>
    <label>NAOCAP Not Orderable ANA</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NAOCAP_Not_Orderable_CHI__c.field-meta.xml
<CustomField>
    <fullName>NAOCAP_Not_Orderable_CHI__c</fullName>
    <formula>if((NATT_Core__c==true || NATT_DirectDelivery__c ==true || NATT_ItemPriceGroup__c ==&apos;123&apos;),true,if((NATT_Sales_Code__c==&apos;S01&apos; || NATT_Sales_Code__c==&apos;SM1&apos; || NATT_Sales_Code__c==&apos;SB1&apos;),if (ISPICKVAL( NAOCAP_Signal_Code_CHI__c, &quot;NLO&quot;),if (ISPICKVAL( NAOCAP_Stocking_Type_UTC_CHI__c,&quot;O&quot;),true,false),ISPICKVAL( NAOCAP_Signal_Code_CHI__c, &quot;S2&quot;) || ISPICKVAL( NAOCAP_Signal_Code_CHI__c, &quot;PRC&quot;) || ISPICKVAL( NAOCAP_Signal_Code_CHI__c, &quot;FIN&quot;) || ISPICKVAL( NAOCAP_Signal_Code_CHI__c, &quot;BY2&quot;)),true))</formula>
    <label>NAOCAP Not Orderable CHI</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/objects/Product2/fields/NAOCAP_Not_Orderable_PAN__c.field-meta.xml
<CustomField>
    <fullName>NAOCAP_Not_Orderable_PAN__c</fullName>
    <formula>if((NATT_Core__c==true|| NATT_ItemPriceGroup__c ==&apos;123&apos; ||( NATT_Sales_Code__c==&apos;S01&apos; &amp;&amp; NATT_DirectDelivery__c ==true)),true,if((NATT_Sales_Code__c==&apos;S01&apos; || NATT_Sales_Code__c==&apos;SM1&apos; || NATT_Sales_Code__c==&apos;SB1&apos;),if (ISPICKVAL( NAOCAP_Signal_Code_PAN__c, &quot;NLO&quot;),if (ISPICKVAL( NAOCAP_Stocking_Type_UTC_PAN__c,&quot;O&quot;),true,false),ISPICKVAL( NAOCAP_Signal_Code_PAN__c, &quot;S2&quot;) || ISPICKVAL( NAOCAP_Signal_Code_PAN__c, &quot;PRC&quot;) || ISPICKVAL( NAOCAP_Signal_Code_PAN__c, &quot;FIN&quot;) || ISPICKVAL( NAOCAP_Signal_Code_PAN__c, &quot;BY2&quot;)),true))</formula>
    <label>NAOCAP Not Orderable PAN</label>
    <type>Checkbox</type>
</CustomField>

NATTQA-ENV/force-app/main/default/classes/NAC_OrderControllerTest.cls
@isTest
public class NAC_OrderControllerTest {
  static string communityId = [SELECT Id, Name FROM Network WHERE Name =:NAC_Global_Constants.DEFAULT_COMMUNITY_NAME_NAC].Id;

  @isTest(SeeAllData=true)
    static void addtoCartTest(){
        Account acc = NAC_TestDataFactory.insertAccount();
        Contact con=NAC_TestDataFactory.insertAssociatedContact(acc);
        User us=NAC_TestDataFactory.runAsNACUser();
        String effectiveAccountId=acc.id;
        BuyerAccount buyerAccount=NAC_TestDataFactory.insertBuyerAccount(acc);
        
        BuyerGroup bg = NAC_TestDataFactory.insertBuyerGroup();
        BuyerGroupMember bgm = NAC_TestDataFactory.insertBuyerGroupMember(acc,bg);
        
        WebStore webstore = [SELECT id FROM WebStore WHERE Name =:NAC_Global_Constants.DEFAULT_COMMUNITY_NAME_NAC LIMIT 1];
        NAC_B2BUtils.communityIdToWebStoreIdCache.put(communityId,webstore.id);
        
        WebStoreBuyerGroup wsbg = NAC_TestDataFactory.insertWebStoreBuyerGroup(webstore,bg);
        List<PRiceBook2> pb=NAC_TestDataFactory.createPriceBook(1);
        Order ord=NAC_TestDataFactory.createOrder(con.ID,acc.ID,pb[0].id);
        List<String> fieldList= new List<String>();
        List<Id> ProductList=new List<Id>();
        Product2 prod = new Product2(Name ='testProd'+Math.random(),
                                     StockkeepingUnit ='SKU'+Math.random()                           
                                    );
        insert prod;
        ProductList.add(prod.id);
        Boolean excludeMedia=true;
        Boolean excludePrices=true;
        
        try{
                NAC_OrderController.getProducts(communityId,effectiveAccountId,fieldList,ProductList,excludeMedia,excludePrices);
        }
        catch(Exception e){
            
        }
		List<OrderItem> itemList = [SELECT Id, Product2.NAOCAP_Not_Orderable__c, Product2.NAOCAP_Not_Orderable_ANA__c, Product2.NAOCAP_Not_Orderable_CHI__c, Product2.NAOCAP_Not_Orderable_PAN__c, Product2.NATT_Core__c, Product2Id, Quantity FROM OrderItem WHERE OrderId =: ord.Id ];
         List<Id> productIdList = new List<Id>();
            for(OrderItem item : itemList){
                productIdList.add(item.Product2Id);
            }  
        List<Product2> updateProductList = new List<Product2>();
        for(Product2 pro : [Select id,NATT_Core__c from Product2 where Id In:productIdList]){
            pro.NATT_Core__c = true;
            updateProductList.add(pro);
            break;
        }
        update updateProductList;
        NAC_OrderController.resultWrapper roW=NAC_OrderController.addtoCart(ord.id,communityId,effectiveAccountId,'ANA');
      
        System.assertNotEquals(roW,null,'NOt able to add to Cart');
    }
    @isTest(SeeAllData=true)
    static void fetchDataTest(){
        Account acc = NAC_TestDataFactory.insertAccount();
        Contact con=NAC_TestDataFactory.insertAssociatedContact(acc);
        USer us=NAC_TestDataFactory.runAsNACUser();
        String effectiveAccountId=acc.id;
        BuyerAccount buyerAccount=NAC_TestDataFactory.insertBuyerAccount(acc);
        
        BuyerGroup bg = NAC_TestDataFactory.insertBuyerGroup();
        BuyerGroupMember bgm = NAC_TestDataFactory.insertBuyerGroupMember(acc,bg);
        
        WebStore webstore = [SELECT id FROM WebStore WHERE Name =:NAC_Global_Constants.DEFAULT_COMMUNITY_NAME_NAC LIMIT 1];
        NAC_B2BUtils.communityIdToWebStoreIdCache.put(communityId,webstore.id);
        
        WebStoreBuyerGroup wsbg = NAC_TestDataFactory.insertWebStoreBuyerGroup(webstore,bg);
        List<PRiceBook2> pb=NAC_TestDataFactory.createPriceBook(1);
        Order ord=NAC_TestDataFactory.createOrder(con.ID,acc.ID,pb[0].id);
     
        List<String> fieldList= new List<String>();
        List<Id> ProductList=new List<Id>();
        Product2 prod = new Product2(Name ='testProd'+Math.random(),NATT_Core__c=true,
                                     StockkeepingUnit ='SKU'+Math.random()                            
                                    );
        insert prod;
        ProductList.add(prod.id);
        Boolean excludeMedia=true;
        Boolean excludePrices=true;
        Test.startTest();
        system.runAs(us){
        try{
         NAC_OrderController.sObjectWrapper sOw=NAC_OrderController.fetchData(communityId,effectiveAccountId,'NAOCAP_Order_List_View','NAOCAP_Order_List_View_Sortable_Fields','Order');
         NAC_OrderController.sObjectWrapper rW=NAC_OrderController.fetchData(communityId,effectiveAccountId,'NAOCAP_Order_List_View','NAOCAP_Order_List_View_Sortable_Fields','Xyz');
         System.assertNotEquals(sOw,null,'Data fetching failed');
         System.assertNotEquals(rW,null,'NOt able to fetch data');
        }
        catch(Exception e){
            
        }
        }
        Test.stopTest();
    }
     @isTest(SeeAllData=true)
    static void getFieldsNegativeTest(){
        Test.startTest();
        NAC_OrderController.getFields('Test','Test','Order');
        //NAC_OrderController.getFields('Test','Test','Test');
        Test.stopTest();
    }
    
}